### ISSUE TITLE
Error while performing UNDO operation on pseudogene

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1001]
When performing an UNDO operation on a pseudogene, the annotation disappears. On refresh of the page, the user created annotations track show the following error:

<img width="819" alt="screen shot 2016-04-20 at 4 49 54 pm" src="https://cloud.githubusercontent.com/assets/4530272/14691698/4d6a605e-0718-11e6-99ce-ac4ff62386cb.png">

This is mostly due to the improper JSON object being returned to the client upon UNDO.

This was reproducible on `master`.

**Comment by nathandunn** [comment]
@deepakunni3  Can you elaborate on this . . or are you able to fix this?

**Comment by deepakunni3** [comment]
I feel it might be related to the way `addTranscript()` is being called for pseudogene when it should really be calling `addFeature()`.
Also, right now `addFeature()` stores the JSON object at RNA level and not at Gene level. I am thinking of rewriting the `addFeature()` method and see if that fixes this issue.

I am adding the issue here to keep track of this bug and to reference it in my PR.

**Comment by nathandunn** [comment]
What happens if you change it so that addFeature is called for pseudogenes (and all non-coding RNA)?  I'm assuming that that should fix it.   I don't think you'll need to rewrite addFeature() (hopefully).

**Comment by deepakunni3** [comment]
I will have to rewrite at least the way JSON object is added to history in `addFeature()`.

**Comment by nathandunn** [comment]
Whatever you think is best (for any of this).  I was just trying to recollect why I wrote it one way versus the other.  I just know that (like you previously inferred) that however it adds it the first time it should do the same when it does an "undo" operation as well.

**Comment by monicacecilia** [comment]
👍

**Comment by monicacecilia** [comment]
Fixed! 💃
