### ISSUE TITLE
Different assumptions made when converting a Feature to JSONObject and when converting a JSONObject back to a Feature

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1003]
The bug is specifically related to the way feature properties are handled.

In `FeatureService:convertFeatureToJSON()`:
* This method relies on a feature property's `type` attribute which is, currently, empty for all instances of FeatureProperty in Apollo. This leads to the following JSON:
`"properties":[{"value":"@VALUE@","type":{"cv":{"name":"feature_property"}}}]`

In `FeatureService:convertJSONToFeature()`:
* This method expects a feature property's tag and value to be as a `tag=value` pair but the input JSON Object doesn't have `tag=value` pairs for feature properties. Instead its of the form: 
`"properties":[{"value":"@VALUE@","type":{"name":"@TAG@","cv":{"name":"feature_property"}}}]`
* The assumption, while interpreting the JSONObject, is not in-sync with `convertFeatureToJSON()`.

**Comment by nathandunn** [comment]
Good catch.  I take it that this is part of #1002 . .  .

**Comment by deepakunni3** [comment]
Yes, I am trying to see which way would be better.
`"properties":[{"value":"@VALUE@","type":{"name":"@TAG@","cv":{"name":"feature_property"}}}]`
OR
`"properties":[{"value":"@TAG@=@VALUE@","type":{"cv":{"name":"feature_property"}}}]`

**Comment by nathandunn** [comment]
I like the first one.   Conversely . . . you could pull the TAG out, which is more of a key.  

```
"properties":[{"value":"@VALUE@","name":"@TAG@","type":{"cv":{"name":"feature_property"}}}]
```

It properly wouldn't hurt to emulate a triple (and maybe this above does that) . . so you have key, value, type.

**Comment by deepakunni3** [comment]
Right, your suggestion is more explicit. I'll make the changes accordingly to both the methods. (and add tests).

**Comment by nathandunn** [comment]
👍

**Comment by deepakunni3** [comment]
Also, a feature's symbol and feature's description are not interpreted in `convertJSONToFeature()`.

**Comment by nathandunn** [comment]
To Test: set properties on a feature and see that they take.

**Comment by monicacecilia** [comment]
💃
