### ISSUE TITLE
Increase UI and perfromance by calling setCurrentSequenceLocation less aggresively

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1007]
Every time I move I call "setCurrentSequenceLocation" . . . we should trigger an event to save the last position instead and just fire it off every 2 minutes (or so) via a staggered command.

**Comment by nathandunn** [comment]
In:

https://github.com/GMOD/Apollo/blob/master/src/gwt/org/bbop/apollo/gwt/client/MainPanel.java#L224-L242

This should be set automatically and we just send updates to the server periodically (with no callback necessary).

**Comment by nathandunn** [comment]
- [x] confirm that saves are working and preferences are being stored when going back and forth
- [ ] when using drop-down confirm that it is looking up the old location
- [ ] when using scaffold double-click confirm that it is looking up the old location '

**Comment by nathandunn** [comment]
I think that this may have been part of the reason we were running into errors on the branches used to fix  #1006   . .  https://github.com/nathandunn/Apollo/tree/multiple_orgnaism_client_v2

Maybe we can merge that back in and see if it doesn't fix it completely.

**Comment by nathandunn** [comment]
Fixed in 2.0.5 as part of #1272.

**Comment by monicacecilia** [comment]
@nathandunn Do the fixes pushed on #1272 confirm that is is looking up the old location:
- [ ] when using drop-down?
- [ ] when using scaffold double-click?

**Comment by monicacecilia** [comment]
Just re-opening to remind us to answer this question. Can close again if the answers are yes / not needed.

**Comment by nathandunn** [comment]
Grr . . I swore this was working earlier.   K, I will take a look.

**Comment by nathandunn** [comment]
The problem is that it is storing the data at the appropriate time, but it is over-writing preferences sometimes, instead of adding a new preference for a new sequence.

**Comment by nathandunn** [comment]
Calls to 

    Request URL:http://localhost:8080/apollo/sequence/setCurrentSequenceLocation/?name=Group1.2&start=365928&end=402682&suppressOutput=true&clientToken=31960575219237201951263567176

effectively save this, should be able to call this  via:

        SequenceRestService.setCurrentSequenceAndLocation(requestCallback, sequenceNameString, start, end, true);

**Comment by nathandunn** [comment]
@monicacecilia  On server and ready for testing on Monday, though it needs more robust testing.

**Comment by nathandunn** [comment]
Found a couple of errors on staging:

Error on load:

```
VM3304 AnnotTrack.js:338Uncaught TypeError: Cannot read property 'parent' of null
    at sendTracks (VM3304 AnnotTrack.js:338)
    at handleTrackVisibility (VM3304 AnnotTrack.js:357)
    at TBb (annotator-0.js:2633)
    at ZGb (annotator-0.js:1940)
    at CHb.DHb [as Fb] (annotator-0.js:3223)
    at xh (annotator-0.js:591)
    at bh (annotator-0.js:1480)
    at fh (annotator-0.js:1984)
    at eval (annotator-0.js:2611)
    at d (annotator-0.js:2548)
```

Error on switching from the drop-down:

```
annotator-0.js:3101 Uncaught TypeError: Cannot read property 'a' of null
    at XLb (annotator-0.js:3101)
    at wCb.yCb [as fc] (annotator-0.js:3222)
    at gs (annotator-0.js:2253)
    at vs.ws [as dc] (annotator-0.js:3220)
    at XMLHttpRequest.eval (annotator-0.js:2075)
    at bh (annotator-0.js:1480)
    at fh (annotator-0.js:1984)
    at XMLHttpRequest.eval (annotator-0.js:2611)
```

something like this here:

```
(a.n,(!sBb&&(sBb=new SBb),!!mBb&&Xjb(mBb.i,kkc)));KU(a.g,(!sBb&&(sBb=new SBb),!!mBb&&Xjb(mBb.i,kkc)));LDb(a,(!sBb&&(sBb=new SBb),!!mBb&&Xjb(mBb.i,kkc)))}
function XLb(a){var b;b=new VLb;OLb(b,yjb(eR(Mu(a,Ghc).kc().a)));QLb(b,Mu(a,gjc).mc().a);SLb(b,mjb(cw(Mu(a,'start').kc().a)));MLb(b,mjb(cw(Mu(a,'end').kc().a)));PLb(b,mjb(cw(Mu(a,ekc).kc().a)));RLb(b,(dib(),!!Mu(a,Zic)&&Mu(a,Zic).jc().a?cib:bib));!!Mu(a,Ulc)&&LLb(b,mjb(cw(Mu(a,Ulc).kc().a)));!!Mu(a,'aDefault')&&Mu(a,'aDefault').jc().a?cib:bib;TLb(b,Mu(a,'startBp')?new Qib(Mu(a,'startBp').kc().a):null);NLb(b,Mu(a,'endBp')?new Qib(Mu(a,'endBp').kc().a):null);return b}
function u8(a,b){var c,d,e;d=(b_(),$doc.createElement(bgc));a.c=$doc.createElement(Jfc);Dj(d,i_(a.c));if(!b){e=$doc.createElement(Kfc);Dj(a.c,i_(e))}a.g=b;c=(r6(),kfb((efb(),ifb)?ifb:(ifb=jfb())));Dj(c,i_(d));GU(a,c);Oe();gc(ie,a.eb);a.ab==-1?E0(a.eb,2225|(a.eb.__eventBits||0)):(a.ab|=2225);Vj(a.eb,'gwt-MenuBar');b?JU(a,QU(a.eb)+'-'+'vertical',true):JU(a,QU(a.eb)+'-'+'horizontal',true);a.eb.style['outline']='0px';Uj(a.eb,'hideFocus',cfc);aV
```

**Comment by nathandunn** [comment]
However, switching between organisms and scaffolds using the organism drop-down or panel or the sequence panel table (double-click) works well.

**Comment by nathandunn** [comment]
and logging out and back in works as expected as well (combing back to the last known location)

**Comment by nathandunn** [comment]
- [ ] fix error on load 
- [ ] fix drop-down selection error
