### ISSUE TITLE
retain location when going back and forth between scaffolds

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1008]
I think that this done automatically when using the scaffold switch in JBrowse, but using the URL from the side-panel we need to explicitly store these calls or use the official API.

**Comment by nathandunn** [comment]
From @cmdcolin  

> JBrowse API:  http://jbrowse.org/api/
> If you navigate to a URL, jbrowse will save that location as a cookie, and then even if you navigate inside the jbrowse, it'll save that too, so I don't exactly know what the scenario here is.
> In any case, browser.navigateTo/navigateToLocation might be of interest

Using the navigateTo is a good idea.  I have to register these in the iFrame, however, which isn't hard.

**Comment by nathandunn** [comment]
When I click back and forth on the scaffold, it seems to have forgotten the last location on that scaffold.

**Comment by nathandunn** [comment]
Just retested and it works as I would hope.  I think that the only difference is that the JBrowse drop-down may remember something differently than the Reference Sequence ones.   However, I think that (A) the JBrowse drop-down will be going away as it has limited utility,  (B) it works fine if things are consistent within the control, and (C) I think that this is working better most likely as a result of #1349.

**Comment by monicacecilia** [comment]
Yeah, checked and it remembers from scaffold to scaffold, if navigating with Annotator Panel. 

Reason (A) is true and already visible in 2.1 development. Does @enuggetry know about that?
