### ISSUE TITLE
Update database migration scripts for next release

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#1012]
There are a fair amount of things that need adding (e.g. client token) for 2.0.3

**Comment by cmdcolin** [comment]
Docs need to also point to "sdk install grails 2.5.4"

Technically that's a little awkward since that change will only make sense once 2.0.3 is released, but if we want, we can make the webapollo docs point to the docs for a specific release tag by default instead of whatever's on the master branch. Depends on what we want I guess

**Comment by nathandunn** [comment]
I added #1013 for making final changes to doc (like the sdk version)

**Comment by nathandunn** [comment]
Definitely getting this error:

```
 Position: 64. Stacktrace follows:
org.postgresql.util.PSQLException: ERROR: column this_.client_token does not exist
  Position: 64
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2161)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1890)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
```

I'll have a fix for it momentarily.

**Comment by deepakunni3** [comment]
@nathandunn yes, I had removed the unused generic clientToken from `Permission.groovy` domain object. (commit 6caceba)

**Comment by nathandunn** [comment]
@deepakunni3  I think this error is just that the clientToken is not there on a production site and needs to be added.   I have to bring up a production site, so I'll add these as I come across them.

**Comment by deepakunni3** [comment]
@nathandunn my bad. I thought it was because of removing a field.

**Comment by nathandunn** [comment]
That should fix it all, but we'll wait until your done to evaluate more schema changes.  That being said, it seemed to work fine migrating from a 2.0.2 DB to a 2.0.3 DB.

**Comment by nathandunn** [comment]
Tested and confirmed to be working.  Can re-open another issue if we run into issues.
