### ISSUE TITLE
More extensible feature annotation types

### ISSUE THREAD

**Issue by hexylena** [GMOD/Apollo#1014]
Today I had a request for annotating pRNA which I'd never heard of (https://en.wikipedia.org/wiki/Bacteriophage_pRNA). While we could annotate them as ncRNAs, it'd be nice to be able to annotate them as the class we believe them to be.

Since this isn't the first time that my org has filed issues for annotation of special feature types (and this time for one that wouldn't be very popular), I'm filing this issue as the ability to extend annotation types in deployer specific ways. E.g. allowing for admins to customise which features their users are allowed to create, possibly having that be a per-organism setting or a per-ref-seq setting (if that's appropriate).

Given the note of "pRNA is a ncRNA element," it would be very interesting if that menu had indentation levels indicating the hierarchy of annotatable elements. E.g.

```

Create new Annotation →

+========+
| gene   |
| ncRNA  |
|   tRNA |
|   pRNA |
| ...    |
+========+
```

**Comment by nathandunn** [comment]
@erasche  It looks like its not in the SO.   In the interim can you add it as an ncRNA with the comment that it a pRNA?  

We're still looking at (and I like the UI suggestion), just wanted to see if there was a workaround for this in the interim.

**Comment by erasche** [comment]
@nathandunn absolutely an interim solution! Just wanted to file this idea.

**Comment by monicacecilia** [comment]
Thanks for the idea @erasche. We are looking into other requests to the SO, and perhaps we can explore this as well as we communicate with that community. Thanks for the heads up.

**Comment by nathandunn** [comment]
@erasche  You should be able to add pRNA or any other feature type relatively easily if it is part of the SO.    You just follow the pattern for the other transcript types, unless it has special logic.   Let us know if we can help point you in the right direction.

**Comment by nathandunn** [comment]
FYI @jasonjgill .  @meiliucpt . @jrr-cpt . not sure if this is still relevant.

**Comment by nathandunn** [comment]
closing this as no longer relevant AFAIT, but we can later if need be
