### ISSUE TITLE
Login credentials for multiple Web Apollo instances

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#102]
It would be practical to have a single authentication event for users to annotate more than one Web Apollo instance, when a single group (e.g VectorBase, i5K@NAL) is hosting all the instances of interest.

@nathandunn I am not sure if this would be directly related to the "multiple genomes" issue (https://github.com/GMOD/Apollo/issues/50), as it does not involve visualization of multiple genomes in a single instance, but rather access to multiple Web Apollo instances, which will presumably be in the same server. 

Note: I could not find the issue / Trello card that describes the ability to run more than one Web Apollo instance on the same server. 

This is also related to creating the ability for a group managing multiple Web Apollo instances (for many genomes) to update all Web Apollo instances at once, instead of each separately.

**Comment by nathandunn** [comment]
I have a notion of sharing between instances for 2.1 . ..  we'll be able to get multiple organisms per instance . .  so we'll see how that scales.   We also have plans to allow logins with Drupal, Oauth, etc. etc.

**Comment by cmdcolin** [comment]
Not sure if this is the right card to comment on, but I just want to refresh interest in this sort of thing. 

For example, we don't really have a way for users to register, but we also don't have a way for users to change their own password. 


I think it would really be better for users to be able to "register" and for admins to "approve" them (and in fact, the admin must approve the permissions for particular organisms in 2.0 anyways, so it would really just be ideal if admin is informed of user registrations)

**Comment by nathandunn** [comment]
We have already solved this in 2.0.X and earlier.
