### ISSUE TITLE
clientToken not found for operation get_gff3 and get_sequence

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1027]
While trying to get the GFF3 or the sequence of an annotation the server throws the following error:

```
JSONObject["clientToken"] not found
Message: JSONObject["clientToken"] not found.
    Line | Method
->>  412 | $tt__hasPermissions in org.bbop.apollo.PermissionService
```

This would be related to the recent introduction of clientToken for supporting multiple concurrent organisms (#441).

**Comment by nathandunn** [comment]
Do you have a chance to look at it?   There is a ton of code in RequestHandlerService that handles the clientToken, so it should be a pretty easy fix.

**Comment by deepakunni3** [comment]
Sure, I can get this done quickly.

**Comment by nathandunn** [comment]
Alright.  Let me know if you need a hand with this.  

The fixes to URLMapping in #1029  *may* have already fixed this, but am unsure.

**Comment by nathandunn** [comment]
@deepakunni3   If you pull the upstream master, I was able to fix the "get_sequence" one by calling the handleInput method (sorry, though I'd done that everywhere):

```
diff --git a/grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy b/grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
index f1faed1..9291687 100644
--- a/grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
+++ b/grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy
@@ -894,7 +894,7 @@ class AnnotationEditorController extends AbstractApolloController implements Ann
     ] )
     def getSequence() {
         log.debug "getSequence ${params.data}"
-        JSONObject inputObject = (request.JSON ?: JSON.parse(params.data)) as JSONObject
+        JSONObject inputObject = permissionService.handleInput(request,params)
         if (!permissionService.hasPermissions(inputObject, PermissionEnum.EXPORT)) {
             render status: HttpStatus.UNAUTHORIZED
             return
```

**Comment by monicacecilia** [comment]
good catch!

**Comment by nathandunn** [comment]
To test do: "get_sequence" and "get_gff3" on a sequence.   . . Also do this at the track level for the annotation track.
