### ISSUE TITLE
create a docker image for 2.0.3 when released

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1030]
- [x] switch version to 2.0.3 hash key 
- [x] add tag for stable, latest, and 2.0.3

Related to #1016

**Comment by nathandunn** [comment]
Need to do this to support #1040.

**Comment by nathandunn** [comment]
@erasche   WRT to chado . . are you building off of my tag (latest?)  if so I can add chado to that, but not sure how that would integrate with the rest of the app

**Comment by erasche** [comment]
@nathandunn yeah, i'm building off latest/master.

If you add chado to that, the only thing we have to do is switch out the postgres image for erasche/chado (or integrate the docker-compose from https://github.com/erasche/docker-tripal/blob/master/docker-compose.yml if you want full tripal support as well ;) )

**Comment by erasche** [comment]
The tripal config linked automatically loads chado on first run. Would it be a problem for apollo / would apollo "notice" if the chado tables weren't created until ~1 minute after boot?

**Comment by erasche** [comment]
@nathandunn @deepakunni3 so with chado support, do we just switch apollo-config.groovy to use *only* a dataSource_chado and have "automatic" export by saving directly to chado? Or can it use both and only export to chado whenever the user presses the button?

**Comment by nathandunn** [comment]
@erasche  Finally got a chance to look a this.  You add the dataSource to it.  More next week.   

It doesn't do an automatic export.  Most user's want to have a view of what is in there first.

**Comment by erasche** [comment]
@nathandunn @deepakunni3 chado export works beautifully. I could not be more excited. I need to fix my tripal container, but I should have a full dockerized galaxy-apollo-chado-tripal for GMOD.

**Comment by nathandunn** [comment]
Awesome would love to see it.  Thanks for the attention to detail (as always @deepakunni3 ).

**Comment by deepakunni3** [comment]
@erasche Thank you! Let us know if there is some issue with the export.
