### ISSUE TITLE
Displaying BAM file in stand-alone JBrowse vs. Web Apollo  

### ISSUE THREAD

**Issue by adnguyen999** [GMOD/Apollo#1031]
Hi,

After uploading a BAM file in stand-alone JBrowse, I was able to see tooltips / labels of alignment features when the mouse hovers over them, e.g. a tooltip showing the query name found in the first column of a .sam file. However, I could not see this feature in JBrowse when accessing via Web Apollo. 

Thank you.
Anh-Dao

**Comment by nathandunn** [comment]
@adnguyen999   Apollo rewrites the JBrowse tracks when it gets added to Apollo, so that is to be expected.   However, I agree that we should still allow viewing of tooltips and labels of the alignments.

**Comment by adnguyen999** [comment]
Hi,

Do you have any documentation explaining the coloring scheme for BAM features (e.g. red, green, gray colors seen in the attached screenshot )?

Thanks
Anh-Dao

**Comment by nathandunn** [comment]
@adnguyen999   I don't think the screenshots got attached.    You should be able to add them to the code directly on the github issue: https://github.com/GMOD/Apollo/issues/1031

**Comment by adnguyen999** [comment]
Thanks Nathan. 

![bam_feature](https://cloud.githubusercontent.com/assets/16709226/15255973/14e9439c-190d-11e6-95e6-915ac81c5d46.png)

**Comment by monicacecilia** [comment]
Hi Anh-Dao, :smile:
Mismatches and deletions relative to the reference genome are shown in red and insertions are shown in green. 

I haven't come across those gray sticks before. Do you have a public browser example where I can see them?

**Comment by adnguyen999** [comment]
Hi Monica,

Sorry, we don't have a public browser. Can you see the gray bars in the screenshot above?

**Comment by monicacecilia** [comment]
@adnguyen999 that's ok. Do you think you could zoom in closer closer to the those gray bars and share with us a screenshot that includes 2 tracks: the "Reference Sequence" and the aligned reads from the BAM track? Hopefully we'll get a better idea of what those gray bars denote.

**Comment by monicacecilia** [comment]
By "zoom in closer" I mean to zoom in to the nucleotide level. thanks.

**Comment by adnguyen999** [comment]
Hi Moni,
Sorry, I was out of town for a couple of days.

![screen shot 2016-05-19 at 10 50 54 am](https://cloud.githubusercontent.com/assets/16709226/15397871/9ffd8dfc-1daf-11e6-9bdc-dcb93835bb68.png)

**Comment by adnguyen999** [comment]
FYI
Regarding my first post (tooltips / labels of alignment features)
A co-worker found the way to show the labels on the features by using the "Show labels" option.

Anh-Dao

**Comment by nathandunn** [comment]
👍

**Comment by monicacecilia** [comment]
@adnguyen999 ... I have looked and looked and I don't have an answer for those gray bars. I'm sending this pic to the JBrowse list, in case someone over there knows what's up.

**Comment by nathandunn** [comment]
Going to close unless this is still a problem.

**Comment by nathandunn** [comment]
Re-open if still a problem.
