### ISSUE TITLE
new url of the docs

### ISSUE THREAD

**Issue by MichelMoser** [GMOD/Apollo#1032]
Dear Apollo Team, 

You recently changed position of your docs from: 

http://webapollo.readthedocs.io/

to 

http://genomearchitect.readthedocs.io/en/latest/

Could you change or redirect relevant links to the url?

Thank you, 
michel

**Comment by monicacecilia** [comment]
Dear Michael, 

Thanks for your message. We are working on it.

As we announced to the list yesterday, we are in the process of upgrading a few aspects of our website, and with this, also portions of our documentation. As we mentioned in the message, things may be intermittently unavailable until we finalize our updates. 

Unfortunately there was little time to give notice about the updates, as we are addressing a few unexpected issues. We hope we will be able to get back to normal early next week. 

Thank you for your patience and understanding. We sincerely apologize for the inconveniences this may be causing. 

cheers,

**Comment by monicacecilia** [comment]
All but one instances of http://webapollo.readthedocs.io/ had been updated. Thanks for catching that. Let us know if you encounter any other hiccups. :bowtie:

**Comment by nathandunn** [comment]
Thanks.  So weird.  I could have sworn I did this already.
