### ISSUE TITLE
Apply for JOSS.org citation

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1034]
- [x] get a DOI (and DOI’s for any references)
- [x] register with zenodo (as they are all registered there) (and add a badge)
- [x] add DOI badge to README
- [ ] apply for joss.theoj.org and wait (and add a badge)
- [x] add DOI badge to BBOP
- [x] add DOI badge to GenomeArchitect

https://guides.github.com/activities/citable-code/

These are attached to releases so it would be 2.0.2 or 2.0.3 most likely.

**Comment by monicacecilia** [comment]
Started the Zendo + GitHub integration. Waiting on our nest release to sync so it produces the DOI.

**Comment by monicacecilia** [comment]
I have not been able to access Zenodo again since I initially did... and my computer does not want to talk to Zenodo anymore... @nathandunn you may need to jump in and do this from your end.

**Comment by monicacecilia** [comment]
neeeever miiiiind. After a few days, I'm finally in again...

**Comment by monicacecilia** [comment]
DOI badge is ready. 
- [![DOI](https://zenodo.org/badge/22312/GMOD/Apollo.svg)](https://zenodo.org/badge/latestdoi/22312/GMOD/Apollo)

**Comment by deepakunni3** [comment]
@monicacecilia The title says `WA2.0.2-RC1` when it should be `WA2.0.3-RC1`.

**Comment by monicacecilia** [comment]
That's all automatically done by the info Zenodo gets from GitHub... so let me go find out what's up. (because the rest of the page lists it correctly). grrrr.

**Comment by deepakunni3** [comment]
Oh, we did have a typo in the title when we released the RC1, which was changed within minutes.
But I guess Zenodo didn't update itself.

**Comment by monicacecilia** [comment]
Oh, so it's @nathandunn fault... 😉  hehe.

**Comment by monicacecilia** [comment]
yep... it's not going to be updated until we do a new release...

**Comment by nathandunn** [comment]
The very newest one should be: 

Apollo2.0.3-RC2(JB1.12.2-apollo)

Or .  . I could just do them as:

2.0.3(JB1.12.2-apollo)

??

**Comment by monicacecilia** [comment]
I like to differentiate RC from the real deal. Let's keep -RCx in the name.

**Comment by nathandunn** [comment]
Sorry . .  I meant:

2.0.3-RC2(JB1.12.2-apollo)

Didn't mean to drop the RC2

**Comment by monicacecilia** [comment]
Ok. I think the former. Thanks.
Apollo2.0.3-RC2(JB1.12.2-apollo)

**Comment by nathandunn** [comment]
How do we trigger Zenodo?  We made another release and it doesn't seem to be updating.   Maybe just need to wait.

**Comment by monicacecilia** [comment]
New releases are supposed to trigger it automatically. Nothing to do on our end. I noticed the same last night and figured it will be updated in a few hours. . .

**Comment by monicacecilia** [comment]
### Zenodo
The tag was updated with the latest RC.
[![DOI](https://zenodo.org/badge/22312/GMOD/Apollo.svg)](https://zenodo.org/badge/latestdoi/22312/GMOD/Apollo)

It's driving me nuts that the DOI in the original badge shows up as: 
[![DOI](https://zenodo.org/badge/22312/GMOD/Apollo.svg)](https://zenodo.org/badge/latestdoi/22312/GMOD/Apollo)

But in the Zenodo page, it actually has updated the DOI number. See this: 
<img width="324" alt="screen shot 2016-06-07 at 4 15 40 pm" src="https://cloud.githubusercontent.com/assets/1714621/15874890/1b69a3ca-2ccb-11e6-8a04-298e7c2dc0de.png">

It still goes to the same page, of course... but it drives me a little bananas. 


### JOSS, DOI badges on our websites
I will have to get on this after I get back in town, but it is not a show stopper. 
@nathandunn do you agree?

**Comment by nathandunn** [comment]
@monicacecilia  Looks like just the joss is waiting.

**Comment by nathandunn** [comment]
@monicacecilia  / @selewis   I think we are ready for the JOSS submission?  

http://joss.theoj.org/papers/new

**Comment by nathandunn** [comment]
joss review process: https://github.com/openjournals/joss-reviews/issues/57

**Comment by monicacecilia** [comment]
Will complete this and review docs from #1235 immediately after release.

**Comment by monicacecilia** [comment]
Update: @selewis chatted with editors of journal where we are about to submit our manuscript. They advised against getting JOSS doi due to conflict - it would effectively mean we would be scooping ourselves. That's unfortunate - and it is what it is. closing this.

**Comment by monicacecilia** [comment]
@nathandunn maybe this can be done after submission?
