### ISSUE TITLE
transposable elements should indicate strand

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1039]
From #1038 and #873.  

Transposable elements should allow flipping of strands as well as indicate strands when created.

**Comment by monicacecilia** [comment]
Let's make sure to read more on this before making the final push.
Transposable elements are transcribed - and some are later retro-transcribed - but I'm fuzzy on the directionality bit.

**Comment by nathandunn** [comment]
Makes me worried if you are fuzzy ;)    We'll definitely wait on this until you have had a chance to review.

**Comment by nathandunn** [comment]
Ditto thought on this on @monicacecilia  . . it might be pretty simple, but let me know.   We can also bump it as well.
