### ISSUE TITLE
change "group" to "team"

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1041]
Wanted to review with @monicacecilia  but I think that this makes sense.

**Comment by monicacecilia** [comment]
👍  Yes, 'team' is okay.

**Comment by nathandunn** [comment]
- [ ] change in "AnnotationPanel"
- [ ] change in GroupController web services (class names can rename) in the RestAPI
- [ ] use the UrlMapper to back-propagate any changes

**Comment by nathandunn** [comment]
@monicacecilia   Organism -> Genome as well?

**Comment by nathandunn** [comment]
I will say that this gets kind of ugly because we use the same verbiage everywhere for the Rest Doc.  So you'll have parameters describing a team and naming a "group".    Maybe that's okay, or maybe we leave the web services with the word "group" everywhere, but it describes team functionality.

**Comment by nathandunn** [comment]
This is fine:

![screen shot 2016-11-27 at 6 28 05 pm](https://cloud.githubusercontent.com/assets/751274/20654539/418b53aa-b4cf-11e6-83c0-b4a1f876568b.png)

but to change the web services to correspond we'll have this:

![screen shot 2016-11-27 at 6 27 03 pm](https://cloud.githubusercontent.com/assets/751274/20654532/32133e9c-b4cf-11e6-80b7-a60011ebd60a.png)

**Comment by nathandunn** [comment]
@deepakunni3  / @monicacecilia  Just curious of thoughts on this one.  My intuition is saying let's not do this as it confuses users more than it helps them and the only real confusion is the fact that we use Honeybee (which is awesome) so much.

**Comment by monicacecilia** [comment]
Leave it as 'Group'.
