### ISSUE TITLE
allow REMOTE_USER authentication

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1042]
- [x] establish a way to bypass logins using a REMOTE_USER header 
- [x] replace all "logins" with ```permissionService::authenticateWithToken```

REMOTE_USER authentication added to support galaxy authentication:

https://github.com/erasche/gx-cookie-proxy/

**Comment by nathandunn** [comment]
Need to support the case where its in the header.    In the case of the login, which we're not using, we can do something like this:

http://stackoverflow.com/a/7114285/1739366

**Comment by nathandunn** [comment]
Reference on Apache settings:

http://serverfault.com/questions/207301/get-the-authenticated-user-under-apache

Need to extend the Shiro AuthenticationToken and if acceptRemoteUser is configured on, then accept the header. 

https://shiro.apache.org/static/1.2.2/apidocs/org/apache/shiro/authc/AuthenticationToken.html

**Comment by nathandunn** [comment]
ShiroCas does something similar in their filters:

https://grails.org/plugin/shiro-cas
https://github.com/commercehub-oss/grails-shiro-cas/

**Comment by nathandunn** [comment]
@erasche  Do you have a flavor of the REMOTE_USER  call you use in nginx?   I'll figure it out either way, but figured it would be worth getting to work for one instance.

**Comment by nathandunn** [comment]
http://nginx.org/en/docs/http/ngx_http_core_module.html#var_remote_user

**Comment by nathandunn** [comment]
This is probably it:

https://wiki.galaxyproject.org/Admin/Config/NginxExternalUserAuth

More references:

https://wiki.galaxyproject.org/Admin/Config/nginxProxy#External_User_Authentication

http://serverfault.com/a/392096

**Comment by erasche** [comment]
@nathandunn yep, just set the `REMOTE_USER` header. 

As for nginx specifically, I've never done remote_user in nginx because it's painful (relative to apache) so that bit is new to me.

**Comment by nathandunn** [comment]
Active development here:  https://github.com/nathandunn/Apollo/tree/1042_remote_user

Current issue is getting the REMOTE_USER authenticated to a thread so that Shiro picks it up.   Getting this error with custom authentication:

```
Message: Realm [org.apache.shiro.grails.RealmWrapper@a942c33] does not support authentication token [org.bbop.apollo.security.RemoteUserAuthenticationToken@5e1cdb2].  Please ensure that the appropriate Realm implementation is configured correctly or that the realm accepts AuthenticationTokens of this type.
    Line | Method
->>  178 | doSingleRealmAuthentication in org.apache.shiro.authc.pam.ModularRealmAuthenticator
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    267 | doAuthenticate              in     ''
|    198 | authenticate . . . . . . .  in org.apache.shiro.authc.AbstractAuthenticator
|    106 | authenticate                in org.apache.shiro.mgt.AuthenticatingSecurityManager
|    270 | login . . . . . . . . . . . in org.apache.shiro.mgt.DefaultSecurityManager
|    274 | setCurrentUser              in org.bbop.apollo.PermissionService
|    161 | $tt__checkLogin . . . . . . in org.bbop.apollo.UserController
```

**Comment by nathandunn** [comment]
Was thinking that we can do this with REMOTE_USER by auto-generating passwords and storing the auto-generated passwords locally.   LDAP / CAS could be done similarly.

**Comment by erasche** [comment]
@nathandunn random passwords would be great! (And no need for separate ldap/cas implementations I think)

**Comment by nathandunn** [comment]
@erasche   Yeah, I was just thinking of what other users' will ask for and ways to plug / configure that.

**Comment by nathandunn** [comment]
Should be working now.   Nothing to test without additional configuration.
