### ISSUE TITLE
Berkley security message at genomearchitect.org 

### ISSUE THREAD

**Issue by damurdock** [GMOD/Apollo#1043]
Hi all,

Sorry in advance if this is the wrong place to post this. When I attempt to access genomearchitect.org, I get the following error:
<img width="1217" alt="screenshot" src="https://cloud.githubusercontent.com/assets/653537/15413897/8c9931d0-1dfa-11e6-8a57-8a45d5718832.png">

I'm not at Berkley Lab, so I think this is an issue with the server doing the redirect. I would contact the Berkley Security Team directly, but it seems like someone on the Apollo team would have better standing.

**Comment by nathandunn** [comment]
Thank you for reporting.  Well try to figure this out asap

**Comment by kltm** [comment]
I'm on this now. Pinging @cmungall and @hdietze as this could potentially have knock-on effects with other locations.

**Comment by kltm** [comment]
Funny, berkeleybop.org works just fine, and that is the *exact* same thing, IFAICR.

**Comment by nathandunn** [comment]
I'll try checking from some other places. 

Nathan

**Comment by kltm** [comment]
If I get it, it's not going to matter--I'm guessing they've caught this at the LBL firewall level, we'll need their help to fix it.

In addition to some other configuration notes, I've directed them at this item; if anything interesting comes up, feel free to tag it on.

**Comment by kltm** [comment]
@nathandunn Since the jekyll will compile down to a static site, we can always just get it up manually without the redirect in the interim.

**Comment by nathandunn** [comment]
They blocked it in a day (it was working when you initially flipped it), so they can unlock it just as quickly I bet.  

In the interim @damurdock  you can go to: 

https://genomearchitect.github.io/

Sorry if the migration has caused any inconvenience.

**Comment by nathandunn** [comment]
We were able to resolve it.  Thanks @damurdock
