### ISSUE TITLE
Export sequence API issue

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1045]
I'm having an issue right now with the organism flag to the IO api. This table summarizes a number of API calls. These results are not at all what I expect

Organism | exportAllSequences | sequences | returned seq count | expected seq count 
------ | ------ | ------- | ---- | ----- 
none   | true   | "ctgA"  | 0 | 0 
none   | false  | "ctgA"  | 0 | 1 
none   | true   |         | 1 | 3 
none   | false  |         | 1 | 0 
Merlin | true   | "ctgA"  | 0 | 1 
Merlin | false  | "ctgA"  | 0 | 0 
Merlin | true   |         | 1 | 1 
Merlin | false  |         | 1 | 0 
Volvox | true   | "ctgA"  | 0 | 2 
Volvox | false  | "ctgA"  | 0 | 1 
Volvox | true   |         | 0 | 2 
Volvox | false  |         | 0 | 0                                          

The API says:

 Export all sequences for an organism (over-rides 'sequences')

except that isn't followed at all, clearly. Additionally I cannot seem to receive the ctgA/ctgB sequences that are in Apollo.

I noticed that when I call use the export sequence button in the Web UI, it doesn't even pass an organism! It just uses whichever organism is currently loaded. Lo and behold "feature" applies to the API as well. By changing which organism I was looking at in the web interface to Volvox, the API now returns the following:

Organism | exportAllSequences | sequences | returned seq count
------ | ------ | ------- | ---- 
none   | true  | "ctgA" | 1
none   | false | "ctgA" | 1
none   | true  |        | 2
none   | false |        | 2
Merlin | true  | "ctgA" | 0
Merlin | false | "ctgA" | 0
Merlin | true  |        | 1
Merlin | false |        | 1
Volvox | true  | "ctgA" | 0
Volvox | false | "ctgA" | 0
Volvox | true  |        | 0                                                                                                                            
Volvox | false |        | 0

The API is churning out `java.lang.NullPointerException` without a stack trace, which I think is why the last couple of volvox requests fail.

**Comment by erasche** [comment]
Script is here, btw:

```
for org in {"none","Merlin","Volvox"}; do
for seq in {'"ctgA"',''}; do
for eas in {"true","false"}; do
                if [[ "$org" == "none" ]]; then
                        on="";
                else
                        on=", \"organism\": \"$org\""
                fi
                output=$(curl --silent 'http://apollo:8080/apollo/IOService/write'  \
                        -H 'Content-Type: application/json' \

                          --data "{\"type\":\"GFF3\", \"seqType\":\"genomic\", \"exportAllSequences\":\"$eas\", \"exportGff3Fasta\":\"true\", \"output\":\"text\", \"format\":\"gff3\", \"sequences\":[$seq], \"username\":\"admin@galaxy.org\", \"password\":\"password\"$on}"  | grep -c '>')

                echo "$org      $eas    $seq    $output"
done;
done;
done;
```

**Comment by nathandunn** [comment]
I'll take a look.  I have a feeling that if you pass the organism name / ID in as:

    /apollo/<name>/IOService/write  

. . it might work as expected, but unsure.   Does it work out of the interface as you would expect?

**Comment by erasche** [comment]
It works out of the UI as expected. You navigate to that organism, select ref seqs, everything works.

**Comment by nathandunn** [comment]
That's half the battle.   Hopefully its just bad doc.  Are you able to emulate what you see is being passed?

**Comment by erasche** [comment]
I am, but organism is never passed during UI based calls.

**Comment by nathandunn** [comment]
Okay . . . I'll fix / address that.

**Comment by nathandunn** [comment]
Just noting as I go.   If you don't use the organism, it will pull the organism from your preferences (last used), or from the first allowed, or from the clientToken (which can also be an organism name or ID, or a browser token).    

I'm less concerned with that.  The ```exportAllSequences``` option is used by Chado, but nothing else, so the description is wrong.  @deepakunni3   Do you have any insight into this?

**Comment by nathandunn** [comment]
@deepakunni3  I have a proposed fix for this (the exportAllSequences).  You can let me know.  I just want to make sure I wasn't over-thinking the design.

**Comment by nathandunn** [comment]
@erasche   This is the revised table.   When an organism is not defined it will use the preference.  

ExportAllSequences should always export ALL sequences if set to true (per definition).   If no sequences are defined, all sequences will be exported.  I'm going to double-check, but that is my understanding. 

Organism | exportAllSequences | sequences | returned seq count | expected seq count 
------ | ------ | ------- | ---- | ----- 
none   | true   | "ctgA"  | 0 | **undefined**
none   | false  | "ctgA"  | 0 | **undefined**
none   | true   |         | 1 | **undefined**
none   | false  |         | 1 | **undefined**
Merlin | true   | "ctgA"  | 0 | **2** 
Merlin | false  | "ctgA"  | 0 | **1**
Merlin | true   |         | 1 | **2** 
Merlin | false  |         | 1 | **2**
Volvox | true   | "ctgA"  | 0 | 2 
Volvox | false  | "ctgA"  | 0 | 1 
Volvox | true   |         | 0 | 2 
Volvox | false  |         | 0 | **2**

**Comment by nathandunn** [comment]
@erasche  FYI in your script the ```format``` should be ```text```, however it would have defaulted to that value. 

Also, my assumption is that Merlin and Volvox both have 2 sequences each (and they are similarly named).  

And to clarify, there are exported sequences (the scaffolds) in the GFF3 and then the GFF3 annotations.   The FASTA export option ONLY exports the annotations.

**Comment by nathandunn** [comment]
This was my script:

```
curl --silent 'http://localhost:8080/apollo/IOService/write'  \
	-H 'Content-Type: application/json' \
	--data "{\"type\":\"GFF3\", \"seqType\":\"genomic\", \"exportAllSequences\":\"false\", \"exportGff3Fasta\":\"true\", \"output\":\"text\", \"format\":\"text\", \"sequences\":[], \"username\":\"user@demo.com\", \"password\":\"password\",\"organism\":\"Merlin\" }" ;
```

**Comment by deepakunni3** [comment]
@nathandunn exportAllSequences is also used by the GFF3 and Fasta export. They play the same role where if exportAllSequences is true then the sequenceList sent to the server is empty. This implies exporting of all sequences where the server queries for all sequences for a given organism and exports them.

**Comment by erasche** [comment]
fyi Merlin has one seq (Merlin), and Volvox has the default 2 (ctgA, B), but the expected changes with volvox look good.

> ExportAllSequences should always export ALL sequences if set to true (per definition). If no sequences are defined, all sequences will be exported.

yeah, I would have expected exportAll + no organism + no seqs = exporting absolutely everything from apollo, rather than exporting the last accessed organism. Is there another way to export everything?

**Comment by nathandunn** [comment]
Thanks.  I updated the table to reflect that.  

WRT to exporting everything, there are many ways to do that.   Generally user's would use a web-service script to do an export for each organism since typically they aren't published at the same time.  

We could, however, refactor IOServiceController to do this.   What's the use-case, and how would you expect the input / output to look?

**Comment by erasche** [comment]
No need, `listOrgs | fetchData` will be fine for me, just my confusion over docs. All fixed.

**Comment by nathandunn** [comment]
Perfect, I'll test it tomorrow (if its pushed / rebuilt?)

**Comment by erasche** [comment]
the retrieve / fetch tool won't accept the organism json properly...I'll open an issue for that.

**Comment by nathandunn** [comment]
Nothing to test here (this was a web-service API issue)
