### ISSUE TITLE
overlapping regions of features combine incorrectly

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1052]
Unlike features and isoforms should not overlap. 

<img width="836" alt="screen shot 2016-05-25 at 9 28 30 am" src="https://cloud.githubusercontent.com/assets/751274/15547984/34ef1c6e-225b-11e6-80b6-d128396ff801.png">

FYI @deepakunni3 / @monicacecilia    . . . Not sure if these should be named separate genes or not, but definitely there should be no Repeat Region gene.

**Comment by nathandunn** [comment]
@deepakunni3 . . . I think that this is 2.0.2 being used . . sorry false-alarm.

**Comment by nathandunn** [comment]
@deepakunni3   I retested this in the master and it worked as you had originally written it, i.e., perfectly 👍

**Comment by deepakunni3** [comment]
@nathandunn Ah, okay! 👍
