### ISSUE TITLE
targetURL not preserved properly through login (loadLink, reports)

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1058]
At least I'm assuming that's the root cause.

**Issue:**

I open a url, such as `https://fqdn/apollo/annotator/loadLink?loc=&organism=142856&tracklist=1`

**Expected result:**

- If not logged in, I enter my credentials, and view organism 142856
- If logged in, I see organism 142856

**Actual result:**

- If not logged in, I enter my credentials, and view the very first organism in the list, available to me.
- If logged in, I see organism 142856

**Comment by nathandunn** [comment]
If you login again and paste the URL it works.  Not idea, but I want to do a more thorough rewrite of the security for 2.0.4 that will fix the rewriting.   There is a similar issue with reports as well.

**Comment by erasche** [comment]
Yep, that's basically what I do when I click the eyeball twice when using an Annotate dataset in galaxy.

**Comment by nathandunn** [comment]
If you login with the “remember-me” cookie on it should be good for a year or so. 

Do you have an existing “loadLink” for it?  If its a priority I *will* make it work.  If you are wired into it, I’ll make sure to fix it. 

Nathan

**Comment by erasche** [comment]
Not a priority. The annotate tool generates the full loadLink URL. This is a very minor issue.

**Comment by nathandunn** [comment]
Alright, well let me know if the status changes.   I want to make sure the work-flow actually flows without too much complication.

**Comment by erasche** [comment]
For a demo it'll be completely hidden.

You'll run the tools for the first time, the first org will be added, and you'll default to viewing that. No way to encouter this unless there are already orgs in, and you're logged out.

**Comment by nathandunn** [comment]
- [ ] /auth/login (submit) should respect the "targetUri" if passed in
- [ ] loadLink should create a "targetUri" automatically if not logged in
- [ ] report should create a "targetUri" automatically if not logged in

Eventually make more global. 

May get bumped to 2.0.4.

**Comment by nathandunn** [comment]
@erasche  this should be fixed by the PR #1081  . . . if you can test that it meets your needs, that would be great.

**Comment by monicacecilia** [comment]
Can't test until https://github.com/GMOD/Apollo/issues/1092 is fixed.

**Comment by monicacecilia** [comment]
This is resolved and I'm closing.  However... #1102
