### ISSUE TITLE
Shareable, Public JBrowse instances do not seem to link to other refseqs in organism.

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1059]
I recently hit the "public" button on a [test organism](https://cpt.tamu.edu/apollo/142856/jbrowse/index.html?loc=nHMqLGXaUvjsR3KSCD18RSETusGa:0..111906).

it just links to one of the two ref seqs, with no way to get between them. If you look at the original URL you'll note that it reads `loc=nHMqLGXaUvjsR3KSCD18RSETusGa`. The parent organism has a name of `nHMqLGXaUvjsR3KSCD18RSETusGa`, and two ref seqs, `v2` and `nHMqLGXaUvjsR3KSCD18RSETusGa` (yes, identical).

This is a low priority/possibly edge case issue.

Found on master.

**Comment by nathandunn** [comment]
@erasche   I'm not sure I understand the issue.  Are you clicking on the "link" icon?  

In the link, the 142856 is the organism ID.  nHMqLGXaUvjsR3KSCD18RSETusGa has to be the scaffold within that organism (not the organism name). 

However, it looks like the organism (with the ID) doesn't exist or is not public.  On the organism tab you can click on the "public" checkmark and it should become available.

**Comment by erasche** [comment]
@nathandunn looks like I did something wrong. I then removed the organism and forgot to close this. My apologies. If I can reproduce it again I'll re-open.
