### ISSUE TITLE
Possibly hide "None" permissions in Report::Annotator

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1061]
![utvalg_853](https://cloud.githubusercontent.com/assets/458683/15558781/59453014-22cc-11e6-8a22-9820d70b9d57.png)

Love the Report interfaces, they're awesome! The Nones clutter up the UI a bit though.

**Comment by nathandunn** [comment]
Ha . . good point!

**Comment by nathandunn** [comment]
I see . . you have to turn the permissions on and off and then "none" will show up.  I should just hide it.

**Comment by erasche** [comment]
Ah, that explains it. I had a naive script to lock out student access following the course that just submitetd a "no permissions" on every combination of the set of students, and genomes.

**Comment by nathandunn** [comment]
I can fix it, just making a note.  Just wondering if I should remove the permission altogether or just from the interface .  .  anyway . . .

**Comment by nathandunn** [comment]
[Fixed here](https://github.com/GMOD/Apollo/commit/1bb53a792470024372c25de030f6447c0ccd1140).  It hides this instead of "None" permissions.

**Comment by erasche** [comment]
Similar thing is seen in the API, but that may be less of an issue?

```
         {
            "organism" : "Sh",
            "permissions" : "[]",
            "userId" : 142935
         },
         {
            "userId" : 142935,
            "organism" : "T2_Chi_KPatil",
            "permissions" : "[]"
         },
         {
            "userId" : 142935,
            "organism" : "Werner",
            "permissions" : "[]"
         }
      ],
      "lastName" : "min",
      "username" : "admin@local.host",
      "groups" : [],
      "availableGroups" : [
         {
            "name" : "lso-phage"
         },
         {
            "name" : "bich464-2016-spring"
         }
      ],
      "userId" : 142935,
      "firstName" : "Ad"
```

**Comment by nathandunn** [comment]
I don’t think its an issue, but if you run into anything, let me know and I’ll take care of it.  

Nathan

**Comment by erasche** [comment]
Not an issue, just leads to inflated JSON responses:

wc -c | du -h | transformation 
--- | --- | ---
130406 | 236K| None
12928 | 24K|  Remove permissions blocks without any permissions
12254 | 20K | Remove redundant user id in permission block + empty permission blocks.

**Comment by nathandunn** [comment]
I think that's a pretty worthwhile use-case with little up-side.   Let me take a look.

**Comment by nathandunn** [comment]
I meant little-upside for ignoring.  Weird that the user-id is redundant.

**Comment by nathandunn** [comment]
@erasche  I'm going to close this.  I'll open another bug for loading users, with ONLY a list of users.  We're looking at 20 minutes of work, but if its not urgent / necessary it can wait until after the 2.0.3 release.

**Comment by erasche** [comment]
@nathandunn delay it :) not necessary.
