### ISSUE TITLE
user / group selection goes the wrong direction 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1066]
On the user detail panel in the group tab, the "update membership" box sometimes goes up instead of down:

![screen shot 2016-05-26 at 12 08 32 pm](https://cloud.githubusercontent.com/assets/751274/15586718/ac45f7c6-233a-11e6-8ea2-31cec43a2e31.png)

Oddly on the demo page, these sometimes are adjustable and sometimes are not. 

https://gwtbootstrap3.github.io/gwtbootstrap3-demo/#select

Somehow the "dropup" class is inserted into the button-group.

**Comment by nathandunn** [comment]
On the group tab observe that the "user" detail tab at the bottom goes the correct direction (i.e., up).

**Comment by monicacecilia** [comment]
@nathandunn wait, what? should it not be "_(i.e., down)_"?

**Comment by nathandunn** [comment]
ah .. you're right . . . I think I forgot to say "not up"

**Comment by monicacecilia** [comment]
Ok. In that case, 💃 !
