### ISSUE TITLE
Weird hibernate RO issue

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1067]
```
$ curl https://cpt.tamu.edu/apollo/user/loadUsers \
    -H 'Content-Type: application/json' \
    --data '{"password": "my-password", "username": "my-username"}'

{"error":"Hibernate operation: could not execute statement; uncategorized SQLException 
for SQL [n/a]; SQL state [25006]; error code [0]; ERROR: cannot execute INSERT in a 
read-only transaction; nested exception is org.postgresql.util.PSQLException: 
ERROR: cannot execute INSERT in a read-only transaction"}
```

But with a client token...

```
$ curl https://cpt.tamu.edu/apollo/user/loadUsers?clientToken=14***************** \
    -H 'Content-Type: application/json' \
    --data '{"password": "my-password", "username": "my-username"}'

[{"organismPermissions":[{"id":21282,"userId":4793,"permissions":"[]","organism":"DUC4"}
```

I've tried selecting idle PG transactions and terminating them, but that does not seem to fix the issue. If anyone has any insights I'd really appreciate it.

**Comment by nathandunn** [comment]
I'll take a look.  In Grails-land, the service and controllers have multiple levels of transactional isolation.  

By default in UserController these are set to readOnly:

https://github.com/GMOD/Apollo/blob/master/grails-app/controllers/org/bbop/apollo/UserController.groovy#L19

If you put ```@Transactional``` above the method it should work:

https://github.com/GMOD/Apollo/blob/master/grails-app/controllers/org/bbop/apollo/UserController.groovy#L32

I'm not sure why / where it would be doing an insert, but at this point it doesn't matter.

**Comment by erasche** [comment]
@nathandunn okay, an RO transaction for looking up a user list makes **complete** sense. That's grea to see.

It does an insert into permissions. Sorry, I forgot the DB logs:

```
db_1         | ERROR:  cannot execute INSERT in a read-only transaction
db_1         | STATEMENT:  insert into preference (id, version, client_token, date_created, domain, last_updated, name, preferences_string, user_id, current_organism, endbp, native_track_list, organism_id, sequence_id, startbp, class) values (nextval ('hibernate_sequence'), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, 'org.bbop.apollo.UserOrganismPreference') RETURNING "id"
webapollo2_1 | 2016-05-26 20:25:22,881 [http-apr-8080-exec-10] ERROR spi.SqlExceptionHelper  - ERROR: cannot execute INSERT in a read-only transaction
webapollo2_1 | 2016-05-26 20:25:22,881 [http-apr-8080-exec-10] ERROR apollo.UserController  - {error=Hibernate operation: could not execute statement; uncategorized SQLException for SQL [n/a]; SQL state [25006]; error code [0]; ERROR: cannot execute INSERT in a read-only transaction; nested exception is org.postgresql.util.PSQLException: ERROR: cannot execute INSERT in a read-only transaction}
```

**Comment by nathandunn** [comment]
Ahh . . its checking for the organism permissions and setting a preference for the client token for the organism, which is completely un-necessary when you’re just loading users. 

I’ll fix that with a few other things.  

Nathan

**Comment by erasche** [comment]
Brilliant, thank you @nathandunn
