### ISSUE TITLE
Duplicate organisms

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1074]
Just ... fyi. I've seen this occur a couple times and I'm now realising that my tooling caused this. However, the fact that it is possible is probably worth treating.

```
$ docker exec -it ff1a308548ff psql -U postgres postgres -c "select * from organism where organism.common_name LIKE 'n%'"                     
   id   | version | abbreviation | blatdb | comment |         common_name          |           directory            | genus | public_mode | species | valid | metadata 
--------+---------+--------------+--------+---------+------------------------------+--------------------------------+-------+-------------+---------+-------+----------
 143010 |       2 |              |        |         | nHMqLGXaUvjsR3KSCD18RSETusGa | /opt/apollo/data/galaxy/98180  |       | f           |         | t     | 
 145007 |       2 |              |        |         | nHMqLGXaUvjsR3KSCD18RSETusGa | /opt/apollo/data/galaxy//98296 |       | f           |         | t     | 
 145014 |       2 |              |        |         | nHMqLGXaUvjsR3KSCD18RSETusGa | /opt/apollo/data/galaxy//98296 |       | t           |         | t     | 
(3 rows)
```

three orgs with identical (genus, species, common_name). Perhaps there should be a uniqueness constraint placed on those three?

**Comment by nathandunn** [comment]
So, we've kind of gone back and forth on this.  The discussion we had this morning (same organisms, but different / isolated groups of users) made me think that we should leave it as-is, but its worth discussion.

**Comment by nathandunn** [comment]
It shows up twice in the organism list.  The ID and annotation is different.  Allowing duplication of the name allows us to do sandboxing and training with minimal effort.

**Comment by erasche** [comment]
Since there was never any discussion on this issue...

It has made my life complicated in the past for users ("Which organism am I supposed to be updating?" "Why are there two?") but maybe this is my fault / some bug on my end in the organism upload process that's generating these dupes (and thereby generating support emails.) I had to place some uniqueness checks on my end because this was causing too much burden for no obvious wins on our end. 

Having two users seeing what look like the same organism from their end, but having them as two distinct entities with different permissions was just not a desirable feature.

Would be interested to hear how it works for y'all for sandboxing/training.

**Comment by nathandunn** [comment]
So, @erasche  definitely not wanting to make your life more difficult.  

If you have two similarly named organisms they will be named identically in the organism panel (sort by names just in case), so they should be easy to identify. 

For sandboxing, when we do a training, we setup the same organism, but only give permission to one group or another, so only one group at a time sees a single organism.

Please let us know if there is another use-case we are missing.
