### ISSUE TITLE
Write GFF3 adaptors to meet specific needs

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1084]
- [ ] Ability to export GFF3 including '[polypeptide](http://www.sequenceontology.org/miso/release_2.5/term/SO:0000104)' subfeature. Use case as requested for parasite genomics

This adaptor will allow admins to activate as needed, delegating responsibility for implementation to admins, not user.

**Comment by nathandunn** [comment]
This should be an external "Handler" that could be configured in apollo-config.groovy.    I'm not sure if this should be a "replacement" for Gff3HandlerService called from IOServiceController.  

It could be a replacement or an addition.  I think that the idea would you could write a "CustomGff3HandlerService" and in apollo-config.groovy you would have:

The 'key' would be the FeatureStringEnum lookup used in both ExportPanel (used on creation?) and IOServiceController.  Maybe an option like "visible" might make sense as well.

```
 exportTypes:
[
{ key:"GFF3",label: "Standard GFF3" }
, {   key: "CHADO"  }
, {   key: "FASTA" }
, {   key: "PATHOGEN_GFF3",label:"Pathogen GFF3"}
]
```

What called what would still be handled internally, so not completely configurable, but easy to add different adapters per organization and either fold them back in or keep them separate.

**Comment by monicacecilia** [comment]
Thinking a little more about this issue. 

The flavor of GFF3 that we received as example is quite different from our own. 

```
LmjF.01	chado	gene	26405	27451	.	-	.	ID=LmjF.01.0100;previous_systematic_id=LmjF01.0100
LmjF.01	chado	mRNA	26405	27451	.	-	.	ID=LmjF.01.0100:mRNA;Parent=LmjF.01.0100;previous_systematic_id=LmjF1.0100,LmjF01.0100:mRNA
LmjF.01	chado	CDS	26405	27451	.	-	0	ID=LmjF.01.0100:exon:1;Parent=LmjF.01.0100:mRNA;previous_systematic_id=LmjF01.0100:exon:1
###
LmjF.01	chado	polypeptide	26405	27451	.	-	.	ID=LmjF.01.0100:pep;Derives_from=LmjF.01.0100:mRNA;Ontology_term=GO:0005975,GO:0008107,GO:0005794,GO:0016020;comment=constituitively expressed (PMID:17188763) [...continues...]
```

After a lengthy discussion, we decided to offer this response: 
- The model for annotation in Apollo is very transcript-centric.   
- The easiest thing to do would probably be for the interested parties to massage the exported GFF3. Coming from Apollo they would be Gene/mRNA/CDS/Exon and  the metadata for each annotated genomic element resides primarily on the mRNA / transcript and some on the Gene.
- If collaborators show interest -and have available time-, we would be happy to help them create their own GFF3 export handler. This is the current one (written in Groovy, a JVM language , which is a cross between Java and JavaScript): https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/Gff3HandlerService.groovy

As a consequence, I'm closing this issue.
