### ISSUE TITLE
hovering over feature, owner is not displayed and owner not recorded if not mRNA or genomic feature

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1085]
In the detail panel it is there correctly.  For some reason the hover is not there correctly. 

- [x] fix if owner set and not hovering
- [x] in the case of non-coding RNA (all but mRNA, repeat region and transposable element), owner is not set
- [x] retest with Canvas Track

found in 2.0.2? 

![screen shot 2016-06-01 at 11 30 44 am](https://cloud.githubusercontent.com/assets/751274/15721098/4ef7485c-27ec-11e6-8153-c46fd90ac3a5.png)

**Comment by nathandunn** [comment]
This was definitely showing up in 2.0.2

**Comment by monicacecilia** [comment]
good thing I had the burning urgency to make a screen capture....

**Comment by monicacecilia** [comment]
💃
