### ISSUE TITLE
Show track label function does not stay when changing scaffolds

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#109]
If I choose the option to not "Show track label", it works on the current scaffold/group, but it is not remembered from scaffold to scaffold. So when I change to a different group, the track labels are again visible, even though the option is unmarked from the "View" top-level menu. See image below. 

![screen shot 2014-12-08 at 4 04 30 pm](https://cloud.githubusercontent.com/assets/1714621/5350224/73af3ff6-7ef6-11e4-9698-08733558ba72.png)

**Comment by nathandunn** [comment]
@deepakunni3   Deepak, this is related to #119 and #120.   Need a better way to do persistence (maybe in the session?) between selections.

**Comment by cmdcolin** [comment]
I think it's not really a persistence thing. Reason being is that the mechanism of action was not to "prevent" the track labels from being drawn but rather to "hide them". Therefore if they are redrawn, we have to decide the hide them again.

**Comment by cmdcolin** [comment]
I added a change to the show/hide track labels that uses the track.label property, and I also made it persistent with the "cookie". We can also perhaps control how persistent it is with the cookie expiration or add it to the WebApollo session data as nathan said.

**Comment by selewis** [comment]
Be best to have the default be 'hidden' (rather than the other way around).

Another feature I'd like to add is color matching - make the text or
background color in the track list match the primary color of the track.

**Comment by cmdcolin** [comment]
Eh the thing I committed actually has bugs. If you don't mind i'll keep hacking away instead of reverting it for now

**Comment by nathandunn** [comment]
That is fine as long as its mostly useable if folks download the trunk.

**Comment by monicacecilia** [comment]
Tested - it works now.

**Comment by nathandunn** [comment]
@monicacecilia   Needs to be rested in 2.0.0

**Comment by monicacecilia** [comment]
Yep, still working!
