### ISSUE TITLE
JBrowse rendering issues for NeatFeatures

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1090]
Introns are no longer visible at certain zoom levels. For example, [see this region in Human instance](http://icebox.lbl.gov/Apollo-staging/annotator/loadLink?loc=chr13:49108380..49115740&organism=21&tracks=GenBank%20TopLevel%20MRNA).

![screen shot 2016-06-02 at 9 17 21 am](https://cloud.githubusercontent.com/assets/1714621/15752575/9d189920-28a3-11e6-851f-efd9321dd083.png)

![screen shot 2016-06-02 at 9 21 59 am](https://cloud.githubusercontent.com/assets/1714621/15752570/995310c2-28a3-11e6-930d-1e1e0bc158ba.png)

It's as thought the introns get "too flat" and are no longer visible.

**Comment by monicacecilia** [comment]
Also, this is specific to HTML tracks; does not occur in Canvas tracks.

**Comment by nathandunn** [comment]
These are all JBrowse issues, so I'll be expanding

- [ ] NeatHTMLFeatures disappear when zoomed in 
- [ ] NeatCanvasFeatures not using strand to calculate
- [ ] NeatCanvasFeatures have disappearing UTR

**Comment by nathandunn** [comment]
NeatHTMLFeatures disappear because subfeatures are not found when zoomed in. In that case, we should create a straight line.

**Comment by nathandunn** [comment]
Need to retag after merging this:  https://github.com/GMOD/jbrowse/pull/754

**Comment by nathandunn** [comment]
in NeatHTMLFeatures/main.js:


            if(subNodes.length==0){
                // TODO: view.blocks.nextLeft, view.blocks.nextRight
                // if (nextLeft and nextRight belong to this featurenode)
                //     draw a horizontal line
                // else return 
                return ;
            }

**Comment by nathandunn** [comment]
This is fixed as part of the JBrowse upgrade in 2.0.5  and  9334e76fd7530681fa2dcc71d4440141e1414cfd
