### ISSUE TITLE
Evidence tracks missing in 'Cat' on staging instance.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1093]
@nathandunn  Is this deliberate?
![screen shot 2016-06-02 at 11 26 21 am](https://cloud.githubusercontent.com/assets/1714621/15756140/d0c21844-28b4-11e6-9232-eaae8f923eb1.png)

**Comment by nathandunn** [comment]
Yes.  There are no cat tracks.

**Comment by monicacecilia** [comment]
10-4
