### ISSUE TITLE
'Change annotation type' menu and options need attention.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1095]
Dear @deepakunni3 

Regarding the end product of the [pull request to "Change annotation type"](https://github.com/GMOD/Apollo/pull/1002): 

- A genomic element of type 'gene' can be changed to anything else, including 'repeat_region' (RR) or 'transposable_element' (TE). 
![screen shot 2016-06-02 at 1 03 34 pm](https://cloud.githubusercontent.com/assets/1714621/15759318/17c7776c-28c3-11e6-9c54-c5a9b9421048.png)

- But a genomic element of type 'repeat_region' or 'transposable_element' can only be changed to one of these two (RR or TE).  __Question:__ If a curator changes the feature type of a gene model to RR, the action cannot be reversed. Is this deliberate? What is the reason for this? Is it due to the lack of directionality? 

![screen shot 2016-06-02 at 1 03 42 pm](https://cloud.githubusercontent.com/assets/1714621/15759330/1cefda9a-28c3-11e6-9d7b-6c968b8a4461.png)

__ToDo List__
- [ ] Add message so that when curator tries to change the annotation type from a genomic element with directionality to one that does not require it, they are warned that the action is not reversible.
- [ ] The menu options to "Change annotation type" only appear after _click_ over the words. Could we change this to react when user hovers over the words instead? The way the 'Create new annotation' menu (from _right click_ over evidence tracks) works? 

@nathandunn FYI.

**Comment by nathandunn** [comment]
@monicacecilia  Is that really necessary since they can use the history to undo the operation?

**Comment by monicacecilia** [comment]
What is *that*?

**Comment by deepakunni3** [comment]
Yes, like Nathan said, you can do a UNDO to go back from a RR/TE to a gene.

**Comment by monicacecilia** [comment]
Yes it is.

**Comment by nathandunn** [comment]
I think what we're trying to say is that it *IS* reversible.

**Comment by deepakunni3** [comment]
The reason for the limitation of not allowing users to change annotation type:
When you change the annotation type from Gene --> Repeat Region, the entire feature is reduced to a single level feature (i.e. no child features). 
Since the change annotation type relies heavily on the input that it gets, going from Repeat Region --> Gene would lead to a top level 'flat' feature, which is not desirable.

With history, we can revert back, via undo, because history tracking is smart to track the previous state's structure as JSONObject which makes it easy to recreate the feature.

**Comment by monicacecilia** [comment]
It is "really" necessary to have a warning. It is not intuitive to go with _Undo_.
The warning could say a whole lot, like: "You will not be able to revert back to this type of element using the 'Change annotation type' menu option. Use "Undo" instead."

But before that, then let's understand the reasons why it cannot be changed from non-directional element to directional element. (by "directional" I mean an element that has direction).

**Comment by monicacecilia** [comment]
__Updated ToDo List__
- [ ] When curators try to change annotation type from a genomic element with directionality to one that does not require it, warn them that action is only reversible using _Undo_ function.
- [ ] The menu options to "Change annotation type" only appear after _click_ over the words. Please change this to react when user hovers over the words instead? The way the 'Create new annotation' menu (from _right click_ over evidence tracks) works?

**Comment by nathandunn** [comment]
I thought we weren't doing the "warning" message?

**Comment by monicacecilia** [comment]
Incorrect. You thought we should not add a warning message because curators could grow tired of them. I said the action might be infrequent enough that it might not matter. 
I also said we should let curators know about this in ways different than user guide and mailing list. 
The only alternative offered was a message box.

**Comment by nathandunn** [comment]
okay

**Comment by nathandunn** [comment]
So, the "hover" doesn't work, but everything else does

**Comment by monicacecilia** [comment]
Thanks. I like it.
![screen shot 2016-06-02 at 5 35 56 pm](https://cloud.githubusercontent.com/assets/1714621/15765329/6a1597ae-28e8-11e6-9dc0-e6c407160a9e.png)

I'll close, but does not get a dancer, because of the _onFocus_ bit with the menu is not yet working. I've created #1101 to remind us of that.
