### ISSUE TITLE
Using ?organism=organismName doesn't work if logged in, only works in public/non logged in.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1096]
Quoting from original issue #845 
- The ?organism=organismName (instead of ?organism=organismId) was added in 2.0.1 but it doesn't work if you are logged in (goes through two different code paths)
- Issue brought to attention by @anaome http://gmod.827538.n3.nabble.com/Gmod-ajax-Navigate-to-ortholog-gene-in-a-different-organism-td4052815.html
- As a weird corallary, loadLink links work only if you are logged in. I.e., if you aren't logged in, and you click a loadLink method, then it doesn't take you to desired place
- Also, finally, it was also suggested to allow loadLink to accept a gene ID, as normally with ?loc=GENEID works in jbrowse but Apollo loadLink expects a chr:start..end format
- I'd just want to get @anaome a fix in some reasonable time frame. The scenario is just an interesting customization to link between organisms in a webapollo deployment using some callbacks, so just demonstrating ability to specify organism names and gene ids would be good for that
- @anaome also brought up the fact that this can cause issues because apollo fails when two organisms are browsed at the same time. #441 documents that.
- We need to codify the assertion that organism "name" is unique.
- Also, we should make additional use of the OrganismProperties table to store attributes.

------

Responses from @nathandunn 
- These all seem to work with the code popup (logged in or logged out), which is the major use-case, unless folks are entering in URL's themselves. We should probably support this, though not a high priority AFAIK.
- I like the idea supporting the GENEID (or just feature name) in general.
- Let me know if I mis-identified the severity. Will be happy to look at a pull request either way.
- Its a really neat use-case. I'm wondering if it would simply make more sense to add an "orthologs" section to the popup link below the first two, which would search for the GENE ID in other organisms and then supply the links for those additional organisms. 

<img width="592" alt="df481714-c9c4-11e5-83c8-2c7f4db76d8c" src="https://cloud.githubusercontent.com/assets/1714621/15759753/fd238b9c-28c4-11e6-8d60-2962cd2b7a82.png">.

- By "more below" I mean orthologs with the same or similar names. There are quite a few libraries out there for calculating word "distance".

**Comment by monicacecilia** [comment]
Waiting for @nathandunn to update staging so this can be tested.

**Comment by nathandunn** [comment]
👍

**Comment by monicacecilia** [comment]
@nathandunn not ready... still see this when trying to access public / logged out versions of our data in JBrowse (in staging): 
![screen shot 2016-06-02 at 2 01 16 pm](https://cloud.githubusercontent.com/assets/1714621/15760940/7ea37ee8-28ca-11e6-98c2-25ac82f4f71d.png)

**Comment by nathandunn** [comment]
Leave the "ready" on there and just assign it to nobody (or me).

**Comment by monicacecilia** [comment]
Need to solve https://github.com/GMOD/Apollo/issues/1092 before this can be re-tested.

**Comment by nathandunn** [comment]
@monicacecilia  I think that this can be retested still.

**Comment by monicacecilia** [comment]
- Organisms (not the manual annotation for each organism) are now visible when logged out. 
- We agreed to not pursue a GENEID look up at this point. 
- Other problems were identified - but this issue can be closed.
