### ISSUE TITLE
Error on BLAT search function.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1098]
When I try to run a BLAT search, the following error occurs. 
![screen shot 2016-06-02 at 3 16 26 pm](https://cloud.githubusercontent.com/assets/1714621/15762896/2f3999ae-28d5-11e6-812b-82dd3a08615b.png)

**Comment by nathandunn** [comment]
This is fixed.  It is a system upgrade issue.  It is now working.

**Comment by monicacecilia** [comment]
👍
