### ISSUE TITLE
No record of feature deletion

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#11]
Could you add a trigger to log when a user deletes an annotation?  Ideally it would have the id for the deleter, the locus of the feature and the creator of the deleted feature.  If this is just a tab-delimited text file in the directory it would be great.  If it was viewable for admins through the admin menu it would be even better.

**Comment by nathandunn** [comment]
This is related to the #488.    Its possible I'm not recording it, but would not be hard to add.

**Comment by nathandunn** [comment]
dupe of #1257
