### ISSUE TITLE
Make Login windows the same for Annotator Panel view and Full-screen view.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1103]
'Full-screen view' Login window
![screen shot 2016-06-02 at 6 13 08 pm](https://cloud.githubusercontent.com/assets/1714621/15765805/b8c45980-28ed-11e6-9487-9cbedab2ef10.png)

'Annotator Panel view' login window: 
![screen shot 2016-06-02 at 6 15 44 pm](https://cloud.githubusercontent.com/assets/1714621/15765834/02f2f566-28ee-11e6-9845-89dd25368f20.png)

**Comment by monicacecilia** [comment]
Goal: make both look like the 'Annotator Panel view' login window.

**Comment by nathandunn** [comment]
- [ ] replace Apollo login within bootstrap version

**Comment by nathandunn** [comment]
<img width="270" alt="screen shot 2016-11-27 at 9 51 40 pm" src="https://cloud.githubusercontent.com/assets/751274/20657574/bc7b29f2-b4eb-11e6-8cbe-6601faa76408.png">

**Comment by nathandunn** [comment]
@deepakunni3  Can you review when you have a chance?

**Comment by nathandunn** [comment]
This actually goes away, because it goes straight to the annotator panel.  However, if you are logged out of a report window, it will be nicer as well.

**Comment by monicacecilia** [comment]
.... beauty is in the eye of the beholder, I suppose. :bowtie: 
![screen shot 2016-12-01 at 4 51 05 pm](https://cloud.githubusercontent.com/assets/1714621/20819010/6f0eefd4-b7e6-11e6-843c-6e044e628ef0.png)
