### ISSUE TITLE
Volvox data in staging throws errors. 

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1107]
@nathandunn Is this deliberate? It may just be the case that you didn't add those data. I just wanted to check. If you meant to do this, then let's get rid of _Volvox mithicus_ for the demo instance. 

<img width="1426" alt="screen shot 2016-06-07 at 3 00 23 pm" src="https://cloud.githubusercontent.com/assets/1714621/15873845/23a22e86-2cc6-11e6-8991-56d64352970c.png">

**Comment by nathandunn** [comment]
I am missing the raw file directory it looks like?  . . I'll check.

**Comment by nathandunn** [comment]
Observing the same thing with some of the "raw" tracks.  

I'm checking locally.  I have this eerie feeling it doesn't like the sub-directory, but will see.

**Comment by nathandunn** [comment]
the data is there

**Comment by nathandunn** [comment]
I have a fix for this and will assign it back when deployed.

**Comment by monicacecilia** [comment]
done and done. 💃

**Comment by nathandunn** [comment]
Will need to be rested.

**Comment by nathandunn** [comment]
Still appears to work.

**Comment by monicacecilia** [comment]
I can confirm that it still works as intended.

**Comment by nathandunn** [comment]
I'm sure it still works, but re-opening to re-test

**Comment by monicacecilia** [comment]
Yes it does, and I checked. ... again. 😒

**Comment by nathandunn** [comment]
👍   points for thoroughness
