### ISSUE TITLE
Errors from Apollo 

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1108]
@nathandunn This error is appearing every time I go to the staging instance. It is repeated with every new window. This does not appear to affect anything I am testing; I am passing the message nonetheless. 

<img width="1418" alt="screen shot 2016-06-07 at 2 59 02 pm" src="https://cloud.githubusercontent.com/assets/1714621/15873890/496273ba-2cc6-11e6-99db-35a87c77a2d4.png">

**Comment by nathandunn** [comment]
@monicacecilia  Going to the same place and not seeing it

**Comment by nathandunn** [comment]
I am seeing it . . yeah . . . it is coming from the help menu.

**Comment by nathandunn** [comment]
If we do another pass I'll try to see if I can fix it.   Like you said it doesn't affect anything.  Why is it there?  I'm not sure.

**Comment by monicacecilia** [comment]
It's a myyyyystery...

**Comment by nathandunn** [comment]
I'm wondering if this is related  #1110  . . I'll try fixing it first and see if that helps.

**Comment by nathandunn** [comment]
yep . . .  I fixed this and #1110  works as well.

**Comment by monicacecilia** [comment]
Fixed. 💃
