### ISSUE TITLE
Using external URLs to visualize data in Apollo is not processing data correctly.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1110]
@nathandunn I sent you an email with the URLs I was trying to load. 
The data are there and available, but Apollo can't open the files and thus, it is unable to visualize it. No error warning is shown. 

The console error: 
<img width="1420" alt="screen shot 2016-06-07 at 4 54 53 pm" src="https://cloud.githubusercontent.com/assets/1714621/15876042/9b4e3ee8-2cd0-11e6-8ceb-e5328339b8d4.png">

**Comment by nathandunn** [comment]
K . . thnanks

**Comment by monicacecilia** [comment]
Brilliant. it works now.💃

**Comment by nathandunn** [comment]
Will need to be retested.

**Comment by nathandunn** [comment]
Confirmed that this still seems to work.

**Comment by monicacecilia** [comment]
Confirmed.
