### ISSUE TITLE
Remove one "Add sequence search track" option from "Track" menu.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1112]
I'm adding @enuggetry to this issue because I don't know if this was a JBrowse bug that snuck in or we did this. :bowtie: 

We need to remove one "Add sequence search track" option from new "Track" top-level menu.
<img width="299" alt="screen shot 2016-06-08 at 4 30 00 pm" src="https://cloud.githubusercontent.com/assets/1714621/15911696/82a35ede-2d96-11e6-838b-c15282ce4656.png">

**Comment by nathandunn** [comment]
This is from the RegexSearch plugin . . I think I might be adding the plugin twice.

**Comment by nathandunn** [comment]
I checked jbrowse and it is correct there.

**Comment by nathandunn** [comment]
There is a core plugin concept in JBrowse 1.12.  Now we register that internally.

**Comment by monicacecilia** [comment]
I can confirm that there is only one option to "Add sequence search track". 

However, the name of the top level menu has been reverted from "Track" to "File". 

@nathandunn Please let's make sure the name of this top-level menu remaisn as "Track", so it is consistent with JB1.12.2 as well.

**Comment by nathandunn** [comment]
I'll take a look.  Have no idea what this might be as it should just inherit from the current version.

**Comment by nathandunn** [comment]
of jbrowse   . . .
