### ISSUE TITLE
Update 'Help' top-level menu options and 'Help' box links.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1113]
The item to check the Apollo version under the 'Help' top-level menu has disappeared. Let's put it back. 

Also, the "Apollo user guide" under "Apollo links" in the "Help" box needs to be updated from the current http://genomearchitect.org/web_apollo_user_guide to the updated http://genomearchitect.org/users-guide/ 

I still don't like "User's Guide"... _but that is a different bug and shall be solved another time_.

**Comment by monicacecilia** [comment]
Nope. 
The URL to "Apollo User Guide" in Help is still the old one. . . here's the fix for the Help menu
https://github.com/GMOD/Apollo/pull/1130

**Comment by nathandunn** [comment]
👍  You fixed it!   There was an issue to web_services whih I will fix now.

**Comment by nathandunn** [comment]
👍  for using the PR

**Comment by monicacecilia** [comment]
💃
