### ISSUE TITLE
BLAT search hangs when 'Search all genomic sequences' is checked.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1114]
I have queried Group16.4 (honey bee) using this string of amino acids, and I see results almost immediately. However, when using the same string and checking the 'Search all genomic sequences' box, the query hangs, and after waiting over 10 minutes, I gave up and cancelled. 
It should return results much sooner than that.
```
MSDNKTLKSVTDQHSCLSESATSITDNAKSGTEIENSVSLTKEQDTPIQDTECSMLCNAESGISDMPIKE
INQTVVVEDVEVAYETSLAEKETKDSVTITKQNEQSPNVQQTSIGAGDTCFVFSPIQNENNDAQKMEEKI
```

Network console shows the following (see failed request in red):
<img width="1432" alt="screen shot 2016-06-08 at 5 21 51 pm" src="https://cloud.githubusercontent.com/assets/1714621/15913211/3b848160-2d9e-11e6-826c-8b72ade4552a.png">

Notice time difference (last row) when querying only Group 16.4
<img width="122" alt="screen shot 2016-06-08 at 5 27 53 pm" src="https://cloud.githubusercontent.com/assets/1714621/15913257/79d8f0c2-2d9e-11e6-9385-6869a8ed355a.png">

**Comment by monicacecilia** [comment]
Also tried a search in a different group (1.1), without selecting 'all sequences'. The response was immediate. When checking 'all sequences' behavior was the same.

**Comment by monicacecilia** [comment]
p.s: Apollo is not happy about having 'Developer Tools' window open at the bottom. It hiccups and does not re-render in the correct size.

**Comment by nathandunn** [comment]
I was able to do this in 23 seconds.   Blat was definitely pegged during that time (as it should be).  Would be great to get a queuing system or leverage @enuggetry  's JBrowse platform.

**Comment by nathandunn** [comment]
I would vote that we move this to 2.0.4, as I don't think its a new problem.   If I was compiling something on icebox (not the most powerful machine) it would effect this as well.

**Comment by nathandunn** [comment]
I think you should test it again to see if you see the same results I did.

**Comment by monicacecilia** [comment]
BLAT search seems to be working correctly and this issue seems to have been resolved. 💃
