### ISSUE TITLE
moving jbrowse "boundary" begins to halt 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1115]
Moving side-bar around begins to lag badly. 

This is new with 1.12.2 / 2.0.3 . . . I think either 1.12.1 or 2.0.2 may not have this error.

**Comment by nathandunn** [comment]
<img width="1432" alt="screen shot 2016-06-08 at 2 36 37 pm" src="https://cloud.githubusercontent.com/assets/751274/15913406/a64a66b4-2d8e-11e6-95c3-8332ec39ffe3.png">

**Comment by nathandunn** [comment]
Confirmed that this happens locally as well.

**Comment by nathandunn** [comment]
Tested in embedded jbrowse mode and did not get errors (in master).

**Comment by nathandunn** [comment]
Have this same issue with 1.11.6.

**Comment by nathandunn** [comment]
https://github.com/GMOD/Apollo/commit/afe39d282fc8aad31fd815c4c895174df480ad1d seems to be okay. 

Should move up from here:  

https://github.com/GMOD/Apollo/commits/master?page=2

**Comment by nathandunn** [comment]
working: https://github.com/GMOD/Apollo/commit/1bb53a792470024372c25de030f6447c0ccd1140

**Comment by nathandunn** [comment]
working: https://github.com/GMOD/Apollo/commit/e75ccadb913e3ae8f1a3ba867c5f7d17f98fd63e

**Comment by nathandunn** [comment]
working: https://github.com/GMOD/Apollo/commit/b5badcc04457ffe2ec812dd9056254b28200b0e3

jbrowse error appears when switching organisms, but not on initial load

**Comment by nathandunn** [comment]
seems to work: https://github.com/GMOD/Apollo/commit/bc53a52f5a45ab21db4d0cfe60c1750e108d4448  . . updated bootstrap plugin from 3.3.4 to 3.3.5 

Worth pointing out this bug: 

<img width="532" alt="screen shot 2016-06-09 at 4 57 17 am" src="https://cloud.githubusercontent.com/assets/751274/15928908/a4483754-2dfe-11e6-8c2f-8981e8fb2b33.png">
<img width="1413" alt="screen shot 2016-06-09 at 4 57 10 am" src="https://cloud.githubusercontent.com/assets/751274/15928909/a44971d2-2dfe-11e6-997b-7f3c22f0099e.png">

**Comment by nathandunn** [comment]
works: https://github.com/GMOD/Apollo/commit/be1bde324beaf6d592881735ac239dd1d8c629c0

**Comment by nathandunn** [comment]
works: https://github.com/GMOD/Apollo/commit/bc53a52f5a45ab21db4d0cfe60c1750e108d4448

**Comment by nathandunn** [comment]
Issues, 1 - defined in HTML or template or 2 - not destroyed properly (most likely since we only get this once)

https://www.sitepen.com/blog/2013/10/23/dojo-faq-why-am-i-getting-error-tried-to-register-widget-with-idxxx-but-that-id-is-already-registered/

**Comment by nathandunn** [comment]
http://stackoverflow.com/a/15361223/1739366  

Probably easiest to check and re-assign.

**Comment by nathandunn** [comment]
I think we can safely remove [this code](https://github.com/GMOD/Apollo/blob/master/client/apollo/js/main.js#L219-L247 ):

It is all from this commit:

https://github.com/GMOD/Apollo/commit/b8964c1bc6553bd7c3811f1f3efcfa750d055e20

@GreggHelt2  Do you remember what this was to fix (zooming, etc. works well without it seems), in case I missed something during testing.  I think that JBrowse + Dojo + Chrome upgrades may already be taking care of this.

**Comment by monicacecilia** [comment]
Yep. That's solved. Boundary is sliding without hiccup. 

The description in https://github.com/GMOD/Apollo/commit/b8964c1bc6553bd7c3811f1f3efcfa750d055e20 refers to some errors in zooming in and out of base level.  I have not come across this error again (bases are displayed correctly despite zoom level and with different settings (e.g. colored CDS, Dark theme, etc).  I agree with you. Chrome finally caught up and we can dispense with that code. 

Gets a 💃 !
