### ISSUE TITLE
attach evidence codes and pubs to cv / cv_term annotations and allow possibly more complex units

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1120]
> attach evidence codes and pubs to cv / cv_term annotations and allow possibly more complex units

When I've built these before, there is some pretty involved logic here.  

I'm really curious if we could leverage Noctua to Link to Lego models directly.

http://geneontology.org/page/connecting-annotations-lego-models

http://noctua.berkeleybop.org/

**Comment by nathandunn** [comment]
FYI @satta

**Comment by monicacecilia** [comment]
@nathandunn 
Do you mean something beyond having the ability to annotate PMIDs?
Or do you mean to add the ability to link the PMID to the annotations made using GO IDs?

**Comment by nathandunn** [comment]
The latter:

>  the ability to link the PMID to the annotations made using GO IDs

I'd done it this way before.   This might be a larger conversation for a long-term solution and a short-term solution using attributes / keys / comments as we'd talked about before.

**Comment by monicacecilia** [comment]
Copy that. Just clarifying for this issue.

**Comment by nathandunn** [comment]
Would love to do this with LEGO / Noctua annotations, but I don't know if we're there yet.

**Comment by nathandunn** [comment]
Discussed with @monicacecilia   . . probably not LEGO, but something like:

GENE (or Transcript) 1-N GO  1-N ECO 1-1 PMID

We can the allow these to be interpreted on export by the user.  

http://gmod.org/wiki/Chado_Sequence_Module#Table:_feature_cvtermprop

**Comment by nathandunn** [comment]
Related to #154
