### ISSUE TITLE
caching disabled for JBrowse files

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1125]
I think that this is because of the redirect.  It wouldn't be that bad because of the clientToken (doesn't actually seem to be hitting the database), but even when refreshing, some files are not appropriately cached (and the clientToken remains the same).

**Comment by nathandunn** [comment]
The problem is that when we have a referer:  

http://localhost:8080/apollo/849980139913682511949274315/jbrowse/index.html?loc=Group1.1%3A0..1382403&highlight=&tracklist=0

it calls jbrowse files:

http://localhost:8080/apollo/jbrowse/src/dojo/number.js

the final redirected from: 

http://localhost:8080/849980139913682511949274315/apollo/jbrowse/src/dojo/number.js

The redirected file IS using the cache.    The better solutions would be:

A) cache for the current client token instead of issuing a redirect
B) have the jbrowse calls pull from the "/"

In the case of anonymous JBrowse, I don't think that would work (B).

**Comment by nathandunn** [comment]
I confirmed that after you do a page reload it uses the cached version of files.

**Comment by monicacecilia** [comment]
Yes, and it loads a lot faster. Great!
