### ISSUE TITLE
'Genome' menu items throw errors - incorrect URLs

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1128]
When trying to access any of the organisms from this list: 
<img width="294" alt="screen shot 2016-06-13 at 4 57 45 pm" src="https://cloud.githubusercontent.com/assets/1714621/16027059/04087942-3188-11e6-8e7e-293454da3a42.png">

User is directed to this error page. URLs for all organisms respond in this manner: 
<img width="897" alt="screen shot 2016-06-13 at 4 56 44 pm" src="https://cloud.githubusercontent.com/assets/1714621/16027072/15279690-3188-11e6-88f7-791b3d4bc337.png">

**Comment by nathandunn** [comment]
yeah, this one of the things I fixed, but you should definitely recheck it.

**Comment by nathandunn** [comment]
Confirmed that this ifixed.

**Comment by monicacecilia** [comment]
Confirmed. 💃
