### ISSUE TITLE
"Open track file or URL" options discrepancy.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1129]
Different options from the "Open track file or URL" menu do not offer the same results opening the same files as local vs external binary files via URL.

If I open these three files from an external location, the three files are loaded simultaneously and Apollo is able to discern what they are and how the tracks should be organized: 

![screenshoturl-load](https://cloud.githubusercontent.com/assets/1714621/16060724/116e459c-323e-11e6-9e31-4304d7a03d1b.jpg)

If I open the same three files from a local copy, Apollo instead recognizes only one type of track: 

1) Select files: 
![screen shot 2016-06-14 at 2 19 18 pm](https://cloud.githubusercontent.com/assets/1714621/16060534/119a3da6-323d-11e6-8dfc-a97fc138e616.png)

2) After loading:
![screen shot 2016-06-14 at 2 19 26 pm](https://cloud.githubusercontent.com/assets/1714621/16060540/181d7792-323d-11e6-97ea-1fc7694a1db9.png)

Notice the difference in the list of "New Tracks" that appears. 

Ideas?

**Comment by nathandunn** [comment]
I'm having trouble reproducing this.  Everything I've tried has worked so far.   Can you email these URL's?    Not sure if its variant + BigWig that is the problem.

**Comment by nathandunn** [comment]
I couldn't reproduce it . . 
<img width="693" alt="screen shot 2016-06-14 at 9 05 54 pm" src="https://cloud.githubusercontent.com/assets/751274/16067794/856d1488-3274-11e6-8c88-b5b8b5c98623.png">
<img width="641" alt="screen shot 2016-06-14 at 9 06 15 pm" src="https://cloud.githubusercontent.com/assets/751274/16067793/856cecc4-3274-11e6-842c-e003b6700050.png">

 . . . am seeing two tracks.

**Comment by monicacecilia** [comment]
@nathandunn yes, as I said above (and you corroborated) it works well when you use the URLs. 

**BUT** when you try to upload those files from local copies in your computer, it does not work as expected. 

Please see above the part that reads "If I open the same three files from a local copy,"....

**Comment by nathandunn** [comment]
Crap, that’s right.  Was too tired when I read this.  Will take another look.

**Comment by nathandunn** [comment]
Testing against volvox local and it works on staging and locally.

**Comment by nathandunn** [comment]
Tested on honeybee locally (bai + bam) and worked for forager and the bigwig for the combined.    I'm wondering if the full VCF didn't download?  I'm taking another look at the VCF and see.

**Comment by nathandunn** [comment]
Only fails in one specific instance, though it is unclear why.  Failed in 2.0.2 as well (for this particular instance).  This code has not really been touched so its hard to know.

**Comment by nathandunn** [comment]
@monicacecilia types: because this is only apparent with one file type and has not resurfaced since then, I think we can close. Re-open if it is a problem again.
