### ISSUE TITLE
GFF3 stop-codon issue

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#113]
VectorBase reported:
We encountered the problem that using gff3 submissions from the community included some which visually looked fine but subsequently after export and processing contained in-frame stop codons. So the issue here is that the imported model from gff3 didn't highlight any internal stop codons (normal exon height for CDS). I had checked that the translation was sensible but didn't notice that the length of the peptide sequence was not in agreement with the length of the CDS sequence (peptide = CDS/3). There are a number of ways in which this could be made more useful for the user
 (a) Markup of internal stop codons, similar to the mark up of splice junctions
 (b) Get sequence could translate the entire CDS (stop codons and all) rather than truncating to the longest ORF. The issue here is really a mismatch between what is being shown in the browser and what is being chosen for translation
 (c) Highlight/warn when the peptide length is not equal to  CDS/3

**Comment by nathandunn** [comment]
@monicacecilia  I wonder if you could double-check this or I can shoot an email to the folks at VectorBase to see if they can reproduce it on our demo servers.

**Comment by monicacecilia** [comment]
@nathandunn the latter. I'll send the email.

**Comment by nathandunn** [comment]
Note: Moni has written and waiting.  We need their GFF3 in order to test.

**Comment by monicacecilia** [comment]
The example Vector Based offered was not actually a bug on Apollo. It had to do with the input GFF3 file they were receiving from their users. 
@mpoelchau this issue must not be related to #55  I'm closing this issue and commenting there to keep in mind for further review.
Thank you.
