### ISSUE TITLE
Warn users when 'Make Intron' is not possible

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1131]
We understand that the option to 'Make Intron' will only show results when indeed there is sufficient space to make an intron with canonical splice sites within the exon of interest. 

However, it is disconcerting to the user that Apollo does not issue any warning when this scenario is not available - when it is not possible to "Make Intron". 

Let's add a message (I thought we had one at some point, but I may have imagined it because I could not find it). 

![screen shot 2016-06-14 at 3 47 23 pm](https://cloud.githubusercontent.com/assets/1714621/16062405/bd40d520-3247-11e6-97be-8beba33c6480.png)

**Comment by nathandunn** [comment]
- [ ] issue a warning when it fails to add an intron because not sufficient room to create a splice site

<img width="442" alt="screen shot 2016-11-18 at 6 33 41 pm" src="https://cloud.githubusercontent.com/assets/751274/20452400/8e178554-adbd-11e6-8322-a75367246959.png">

**Comment by monicacecilia** [comment]
Reviewed and tested. 👍
