### ISSUE TITLE
notify user if a backend failure occurs

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#114]
From #111 

>There are still some annoying errors in the users console.log if the server crashes though (like if i intentionally cause some NullPointerException, then the user will probably never realize it and continue working without realizing a bug occured)

>My proposal is to actually alert the user if a fatal server error occurs. With an alert box and everything. Thoughts?

>https://cloud.githubusercontent.com/assets/6511937/5420812/b476dd6a-821f-11e4-8f25-bf63d4c2aa94.jpg

**Comment by nathandunn** [comment]
Should be working , if not need to fix.

**Comment by monicacecilia** [comment]
Nothing has broken yet... so I have not seen the error. __*here's hoping*__.
