### ISSUE TITLE
additional parameters dropped in loadLink

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1140]
Issue found by NAL tests of Blast (FYI @childers). 

This comes from wanting use a URL to add additional track information.  e.g., loc and organism, tracks, are picked up, but what is missing is:

- addStores
- addTracks

So the fix is multiple parts:

- [x] In AnnotatorController loadLink this information is filtered away into the clientToken, which is fine (it is a preference), but the other params.keys need to be preserved to be passed in (to /annotator/index)
- [x] in AnnotatorController::index we need to pass the keys through 
- [x] in MainPanel::updateGenomicViewerForLocation we need to pass the other parameters through as well as an additional field called in the constructor (the GWT will have to grab this all from the URL) and pass through

**Comment by nathandunn** [comment]
should be noted that the actual "public" jbrowse view works well (i.e., /apollo/jbrowse)

**Comment by nathandunn** [comment]
Calls: 

MainPanel::MainPanel() (pull params here)
MainPanel::loginUser()
MainPanel::getAppState()
MainPanel::setAppState()

- need to add "currentParams" to MainPanel and tie everything else into that . . should solve the problem.

**Comment by nathandunn** [comment]
Here is a better test string:

```
http://localhost:8080/apollo/annotator/loadLink?loc=scaffold_0:0..1768108&organism=1053513&tracks=%3Eloc=scaffold_5%3A460811..466180&addStores={%22url%22%3A{%22type%22%3A%22JBrowse%2FStore%2FSeqFeature%2FGFF3%22%2C%22urlTemp%20late%22%3A%22https%3A%2F%2Fgmod-dev.nal.usda.gov%2Fwebapp%2Fmedia%2Fblast%2Ftas%20k%2F0942657fdb4c4e4daeb29d1095c9db8b%2FTCALIF_genome_v1.0_new_ids.fasta.gff%20%22}}&addTracks=[{%22label%22%3A%22BLAST%2B%20Results%22%2C%22category%22%3A%220.%20Reference%20Assembly%22%2C%22type%22%3A%22WebApollo%2FView%2FTrack%2FDraggableBLASTFeatures%22%2C%20%22store%22%3A%22url%22%2C%22style%22%3A{%22renderClassName%22%3A%22gray-center-10pct%22%2C%22sub%20featureClasses%22%3A{%22match_part%22%3A%22blast-match_part%22}}}]&tracks=DNA%2CAnnot%20ations%2CBLAST%2B%20Results&highlight=
```

[Just as a link](http://localhost:8080/apollo/annotator/loadLink?loc=scaffold_0:0..1768108&organism=1053513&tracks=%3Eloc=scaffold_5%3A460811..466180&addStores={%22url%22%3A{%22type%22%3A%22JBrowse%2FStore%2FSeqFeature%2FGFF3%22%2C%22urlTemp%20late%22%3A%22https%3A%2F%2Fgmod-dev.nal.usda.gov%2Fwebapp%2Fmedia%2Fblast%2Ftas%20k%2F0942657fdb4c4e4daeb29d1095c9db8b%2FTCALIF_genome_v1.0_new_ids.fasta.gff%20%22}}&addTracks=[{%22label%22%3A%22BLAST%2B%20Results%22%2C%22category%22%3A%220.%20Reference%20Assembly%22%2C%22type%22%3A%22WebApollo%2FView%2FTrack%2FDraggableBLASTFeatures%22%2C%20%22store%22%3A%22url%22%2C%22style%22%3A{%22renderClassName%22%3A%22gray-center-10pct%22%2C%22sub%20featureClasses%22%3A{%22match_part%22%3A%22blast-match_part%22}}}]&tracks=DNA%2CAnnot%20ations%2CBLAST%2B%20Results&highlight=)

**Comment by monicacecilia** [comment]
@nathandunn and what about #1156? Are you still working on that one? Or did @childers respond about his testing to you outside of GH? 
I ask because this seems to be directly affected by that issue.

**Comment by nathandunn** [comment]
It largely works.  They were going to retest, but I don't think they've gotten to it.   If there is a bug there they will very likely be the only ones to run into it.   I can remove the other one from 2.0.4.   We can always patch that later if need be.

**Comment by monicacecilia** [comment]
_"largely"_ 😰

**Comment by nathandunn** [comment]
Well, it works perfect for me, but I can't test it the way @childers  can.   This feature was largely non-functional when doing loadLinks before, so this is a vast improvement.  Unclear what the edge-cases are in this case.

**Comment by monicacecilia** [comment]
Copy that. I'll close, then we leave #1156 pending, and move from there if we need to address additional issues. 👍
