### ISSUE TITLE
can not add featureType

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1144]
![image](https://cloud.githubusercontent.com/assets/751274/16419632/74720226-3d1c-11e6-9758-312238174b89.png)

Look like it didn't have the updated display field. 

Should be fixed.

**Comment by childers** [comment]
I tested this on our instance that uses mater as the upstream and it worked.  Thanks!
![create_featuretype_works](https://cloud.githubusercontent.com/assets/421248/16528745/b7bc91f0-3f8c-11e6-846b-118407f83f1d.png)

**Comment by nathandunn** [comment]
👍

**Comment by monicacecilia** [comment]
I can confirm that it is possible to create new _Feature Type_ entries. 💃
