### ISSUE TITLE
add_transcripts_from_gff3_to_annotations.pl 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1146]
Reported by Loraine Guéguen:

> For the 1.0.4 apollo version, the add_transcripts_from_gff3_to_annotations.pl script did pretty well, thanks. 
For a new project, we used the 2.0.2 version. We had the same problematic that was to keep the metadata and be able to edit them, so we loaded again the gff directly into the annotation track. However, for the 2.0.2 version, the "Note" attributes from the gff3 file are unfortunately not imported into the "comment" section of the "information editor" panel, but in the "attribute" section, with no tag. This display is not optimal, and what is more problematic : such an attribute with no tag is not exported when doing "get gff3".
I noticed that the json script output seems right with the "Note" attribute typed as "comment". The problem comes probably from the apollo web service code.

**Comment by nathandunn** [comment]
One should be able to do a round-trip.  Not sure if 2.0.2 introduced the error, but it really don't work for a round-trip.  I actually get errors.

**Comment by nathandunn** [comment]
I noted that I get these errors, which I think are all related:

- [ ] export Annotation to GFF3, delete the annotation, import the annotations.  Expected: The same annotation.  Found: missing child-features
- [ ] export Annotation to GFF3, import the annotations without deletion.  Expected: An identical isoform.  Found: An error about overlap. 
- [ ] add a "Comment" to an annotation, export Annotation to GFF3, delete annotation, import the Annotation.  Expected: An identical isoform with identical properties.  Found: A FeatureProperty error

**Comment by nathandunn** [comment]
@deepakunni3   If you want to rewrite the perl script into something else (or not) that would be fine as well, though I think it must have been a pretty small bug to have broken it so recently.

**Comment by deepakunni3** [comment]
After inspecting the script it looks like all features are added via `addFeature()`, including protein coding genes. This assumption seemed to have worked previously but as of Apollo 2.0.3 we changed the way `addFeature` and `addTranscript` methods are used. 

We clearly differentiate the use case where `addTranscript` is called for protein coding features and `addFeature` for all other non-coding feature types. Since the logic for handling coding transcripts (such as isoform overlap, calculating the ORF) are handled by `addTranscript` the errors seen above are expected.

**Comment by nathandunn** [comment]
Interesting, because the script seems to differentiate between the two.   Hopefully it will be an easyish fix by just calling the other service.

**Comment by deepakunni3** [comment]
The fix should be straightforward.

**Comment by loraine-gueguen** [comment]
Please find a test case with the enclosed files:

perl add_transcripts_from_gff3_to_annotations_test_print_lg.pl -U http://mmodev2:8085/apollo -u apollo_dev_admin@sb-roscoff.fr -p xxxxxxxx -i test_import_annotation_2.gff3 > perl_script.out

[bug_load_annotation.tgz.zip](https://github.com/GMOD/Apollo/files/354496/bug_load_annotation.tgz.zip)

**Comment by deepakunni3** [comment]
@loraine-gueguen Thank you for the GFF3. This should be helpful in debugging and testing out fixes.

**Comment by nathandunn** [comment]
@loraine-gueguen   This fixby @deepakunni3  is in master now.   There are actually quite a few changes as a result of this, but all to the better.    If you get a GFF3 from an annotation, you can see the type of annotation that is expected, but it should conform to the [GFF3 spec](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md) that we are using.   Let us know if you encounter any further problem.

**Comment by loraine-gueguen** [comment]
@nathandunn @deepakunni3 Thank you for the fix.

**Comment by monicacecilia** [comment]
I can confirm that exported GFF3 is doing what is expected according to the description in this issue. 

- In this image, the genes shown above were exported and re-imported as a track below. 

![screen shot 2016-07-27 at 5 43 46 pm](https://cloud.githubusercontent.com/assets/1714621/17197510/27b0d85a-5422-11e6-9c1b-2d81be28ab12.png)

- Metadata for the imported, manually annotated gene models, is incorporated in the new track; comments are incorporated in the 'Description' field, while dbxrefs, GO terms, and PMIDs are included in the 'dbxrefs' field. 

![screen shot 2016-07-27 at 5 44 54 pm](https://cloud.githubusercontent.com/assets/1714621/17197644/6c9f9fcc-5423-11e6-84c4-1561ee98d6b2.png)

- Of note, when annotations are imported from the _'Evidence'_ area into the _'User-created Annotations'_ area, all metadata but the name are lost. This is the current, and intended behaviour.

![screen shot 2016-07-27 at 5 48 00 pm](https://cloud.githubusercontent.com/assets/1714621/17197654/9018bda8-5423-11e6-9a37-c2775060a8aa.png)

💃
