### ISSUE TITLE
getting information editor data can be slow from long genes

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1147]
Reported by Loraine Guégen:

> We have a problem with "Information Editor" panel with "Edit Information".
There is always a 10 to 20 seconds delay before the "Information Editor" panel appears once we have clicked on "Edit Information". Apparently, it depends on the gene : the longest is the gene, the most time it takes. That is not very comfortable.
We have Apollo 2.0.2 release with a postgres database. And the gff3 is directly loaded into the User-Annotation track (can this be one of the reason for the delay ?).
It seems that the delay is due to 2 SQL requests in the database that are very long.

Currently we use convertFeatureToJSON instead of convertFeatureToJSON lite, or another optimized method.

**Comment by nathandunn** [comment]
Confirmed that as you add children (exons) the time it takes to generate the "information window".  From 100 ms, to 600 ms for around 50 exons.

**Comment by nathandunn** [comment]
The first call gets a gene and it is about 20 ms . . but the transcript (which is getting exons that it throws away) is taking much longer.   

To fix this we can just need to update the conversion process in a service from here and just add the missing properties:

<img width="784" alt="screen shot 2016-06-29 at 12 38 00 pm" src="https://cloud.githubusercontent.com/assets/751274/16460650/6c1eb882-3df6-11e6-9070-8f431cc43553.png">

into here:

<img width="763" alt="screen shot 2016-06-29 at 12 35 47 pm" src="https://cloud.githubusercontent.com/assets/751274/16460663/7e3ca20e-3df6-11e6-9691-4881a5394d32.png">

**Comment by nathandunn** [comment]
Missing:
- [ ] id
- [ ] name
- [ ] owner
- [ ] type
- [ ] unique_name? 
- [ ] parent_id / parent_type?
- [ ] parent_type? 
- [ ] properties? 
- [ ] sequence?

Ignored:
- [ ] location
- [ ] children?

**Comment by loraine-gueguen** [comment]
Time data for a 16,616 bp long gene:
![time_example](https://cloud.githubusercontent.com/assets/16136876/16691790/5cf4f1c0-452e-11e6-9a62-d5890dbb4667.png)

**Comment by monicacecilia** [comment]
💃

**Comment by loraine-gueguen** [comment]
I have tested apollo 2.0.4-RC3 : the display time for Information Editor panel is far better. Thanks !
