### ISSUE TITLE
Certain scripts that use web services fail

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1155]
- [x] add_users.groovy
- [x] alter_group_permissions.groovy 
- [x] alter_user_groups_and_permissions.groovy
- [ ] delete_annotations_from_organism.groovy

When trying to delete annotations for an organism, the server throws the following error:
```
- | Error org.codehaus.groovy.grails.web.json.JSONException: JSONObject["clientToken"] not found.
```

- [x] get_fasta.groovy
- [x] get_gff3.groovy
- [x] transfer_annotations2to2.groovy
- [ ] stress_test.groovy

While running a stress test the script returns the following error:
```
Caught: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object {...} with class 'java.util.ArrayList' to class 'net.sf.json.JSONArray' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: net.sf.json.JSONArray(groovy.json.internal.LazyMap ...)
```

**Comment by nathandunn** [comment]
👍   Thanks for doing this.  Will try to get these fixed.

**Comment by nathandunn** [comment]
@deepakunni3  Can you close / check this when you have a moment?

**Comment by nathandunn** [comment]
I'll close it if it is working.

**Comment by deepakunni3** [comment]
@nathandunn Yes, this was tested while testing the PR. The scripts work as intended.

**Comment by nathandunn** [comment]
Thanks
