### ISSUE TITLE
Add an option under the 'Tools' menu to extract a reference sequence slice

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#116]
From: https://trello.com/c/tLwokYuo

From Monica Poelchau

Based on an annotator comment who wanted a reference sequence slice when zoomed out. Setting 'ALWAYS_SHOW=true' in the deployed root (jbrowse/plugins/WebApollo/js/View/Track/SequenceTrack.js) works for this, but looks pretty awkward.

**Comment by cmdcolin** [comment]
I realized that the problem with simply adding this exportFormats thing is basically due to the fact that WebApollo's sequence track uses "two store classes". 

The main store class is called ScratchPad and it stores the sequence alterations.
The secondary store class is normal SequenceChunks class, but it is kept as a private variable.


Since we override the main store class with ScratchPad, the default jbrowse things like sequence export normally are lost. Therefore, it would require a custom solution to fix this. I would prefer to go back to inherit from the jbrowse track in 2.x but we could also try and make the custom solution for this in the 1.x if it's highly desirable

**Comment by selewis** [comment]
Hi Colin,

So would it be a decision left to the user whether to export the
ref-sequence with or without the edits incorporated?

For translational frameshifts (i.e. that only impact the resultant peptide)
I would assume these are incorporated on export. (please tell me that we
have added the ability to annotate translational frameshifts...)

-S

**Comment by cmdcolin** [comment]
Yes the sequence change do affect the protein coding sequence that you export. It is not yet optional how it is exported though, they are incorporated automatically. And the export is only from the "get sequence" menu on the specific features, while I think MP was interested in the export of the reference sequence for some whole region.

**Comment by monicacecilia** [comment]
@selewis: "please tell me that we have added the ability to annotate translational frameshifts..." 
Suzi, could I please ask you to explain what you mean by this? 

Currently Web Apollo allows users to make single base modifications to annotate frameshifts by creating genomic edits (in/del/sub). Operation from the right click menu when zoomed to base level. Outcome: ORFs are modified; underlying reference sequence is annotated but not modified. 

As a sanity check, and in the [hopefully] unlikely scenario that we may be once again calling two different processes by the same name, I'd very much like to hear your description of the behavior you expect and the operations in Web Apollo that should produce this behavior. 

Thank you! :)

**Comment by selewis** [comment]
Nothing to do with the DNA.

There are transcripts in existence that naturally have 'skips' during their
translation as the ribosome is chugging along down their length producing
the resultant peptide. When these are known to exist for certain proteins
we need to give the biologist curators the ability to annotate them in
order to correctly generate the naturally produced protein.

-S

**Comment by selewis** [comment]
p.s. we had this feature in the old version of apollo along with stop-codon
read-throughs. Two odd, but naturally occurring exceptions to the general
rules.

**Comment by monicacecilia** [comment]
aaaah, yes, that's a mainly viral thing, isn't it? 
In >45 annotated genomes (euk) I have not come across one such gene nor a request for the feature. 
Could come in handy if/when supporting viral genomes.

**Comment by selewis** [comment]
Drosophila has it apparently, the one I know best.

-S

**Comment by nathandunn** [comment]
You can download any highlighted sequence region.
