### ISSUE TITLE
Projection:  get annotation features from multiple sections of the same and different scaffolds

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1162]
Would be nice for phages, and let us "re-open" them when we discover that the left/right ends are not where the assembler opened them.

Discussed briefly with @nathandunn at GMOD2016 but wanted to document for the future. This would be a nice to have for the phage community.

**Comment by nathandunn** [comment]
@erasche   This would be splitting an existing scaffold at some arbitrary point and then re-arranging it using the existing projection code?

**Comment by erasche** [comment]
@nathandunn yep, precisely.

**Comment by nathandunn** [comment]
Once I get a little further along we'll see if its a part of the beta release or not.

**Comment by nathandunn** [comment]
Talked with @monicacecilia and we confirmed that this should be in the initial release of projection as the use-case with out of order scaffolds / transcripts is not uncommon.

**Comment by nathandunn** [comment]
- [ ] view two gene scaffolds next two each other (currently projects them on the same scaffold)
- [ ] view three scaffolds together (any order)

**Comment by nathandunn** [comment]
<img width="931" alt="screen shot 2016-08-30 at 5 53 04 pm" src="https://cloud.githubusercontent.com/assets/751274/18112200/a201a86e-6eda-11e6-9a33-5d85f95bffbe.png">

Selecting the combine gives me this:

<img width="1216" alt="screen shot 2016-08-30 at 5 54 07 pm" src="https://cloud.githubusercontent.com/assets/751274/18112230/e2a1d98e-6eda-11e6-8a57-cc303ae8546e.png">

with this error:

```
   Line | Method
->>   60 | getProperty                     in org.codehaus.groovy.runtime.NullObject
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    172 | getProperty                     in org.codehaus.groovy.runtime.InvokerHelper
|     47 | getProperty . . . . . . . . . . in org.codehaus.groovy.runtime.callsite.NullCallSite
|    296 | callGetProperty                 in org.codehaus.groovy.runtime.callsite.AbstractCallSite
|    162 | doCall . . . . . . . . . . . .  in org.bbop.apollo.BookmarkService$__tt__standardizeSequenceList_closure23
|     -1 | invoke                          in sun.reflect.GeneratedMethodAccessor1138
|     43 | invoke . . . . . . . . . . . .  in sun.reflect.DelegatingMethodAccessorImpl
|    606 | invoke                          in java.lang.reflect.Method
|     50 | invoke . . . . . . . . . . . .  in org.springsource.loaded.ri.OriginalClassInvoker
|   1461 | jlrMethodInvoke                 in org.springsource.loaded.ri.ReflectiveInterceptor
|     93 | invoke . . . . . . . . . . . .  in org.codehaus.groovy.reflection.CachedMethod
|    325 | doMethodInvoke                  in groovy.lang.MetaMethod
|   1210 | invokeMethod . . . . . . . . .  in groovy.lang.MetaClassImpl
|   1123 | invokeMethod                    in groovy.lang.ExpandoMetaClass
|   1019 | invokeMethod . . . . . . . . .  in groovy.lang.MetaClassImpl
|    426 | call                            in groovy.lang.Closure
|     -1 | call . . . . . . . . . . . . .  in org.bbop.apollo.BookmarkService$__tt__standardizeSequenceList_closure23
|    442 | call                            in groovy.lang.Closure
|     -1 | call . . . . . . . . . . . . .  in org.bbop.apollo.BookmarkService$__tt__standardizeSequenceList_closure23
|   3632 | collectEntries                  in org.codehaus.groovy.runtime.DefaultGroovyMethods
|   3539 | collectEntries . . . . . . . .  in     ''
|   3564 | collectEntries                  in     ''
```

**Comment by nathandunn** [comment]
Looks like  sequenceList is not returning the sequences properly, returning a null [here](https://github.com/nathandunn/Apollo/blob/project_v2_server_delta1/grails-app/services/org/bbop/apollo/BookmarkService.groovy#L162) when extracting from here: https://github.com/nathandunn/Apollo/blob/project_v2_server_delta1/grails-app/services/org/bbop/apollo/BookmarkService.groovy#L111

**Comment by nathandunn** [comment]
@era

**Comment by nathandunn** [comment]
@monicacecilia  / @erasche   What are the use-cases we envision for this? 

Given the scaffolds A (genes 1,2,3), B (genes 4,5), and C (genes 6,7)

- [x] view genes (1-3)/(4-5)/(6-7) from two scaffolds (this works) 
- [ ] view genes (1-3)/(4-5)/(6-7) from three scaffolds (pretty sure this works)
- [ ] view genes 1,2,3 as if they are right two each other (basically folding the space between transcripts)
- [ ] view genes 2,3,4 (makes sense)
- [ ] view genes 3,4,5,6 (makes sense)
- [ ] view genes 1,4,3 (I can not imagine why, but . . if we need to support it . . let me know)

**Comment by erasche** [comment]
> What are the use-cases we envision for this?

for re-opening phage genomes without having to re-map all of our datasets. When our phage genomes are sequenced, they're opened at a completely random position from the assembler. Once we've finished annotation and determined a large number of metadata about the genome we have a standardized position to "re-open" it in (i.e. set as the start, possibly with a rev+comp), but all of our analyses are already mapped to existing places.

So we'd be doing the operation:

- [ ] view genes 2,3,1 or view genes 3,2,1 (or so on)

**Comment by nathandunn** [comment]
Thanks @erasche  that is exactly what I needed to know.

**Comment by nathandunn** [comment]
@erasche  And genes 1,2,3 are all on the same scaffold?

**Comment by erasche** [comment]
Yep! Phage genomes are only ever one contig, we wouldn't be merging multiple contigs that we annotated separately. Just rerrnging a single contig

**Comment by nathandunn** [comment]
Perfect.  Just wanted to clarify.

**Comment by nathandunn** [comment]
I updated the checklist to put them all in the same place

**Comment by nathandunn** [comment]
note: updated so that TODO is at the top

**Comment by nathandunn** [comment]
Here we have two scaffolds and two viewable regions A1, A2, A3, B1, and B2 — which would correspond to some annotated genomic element. 

In Projection 1 it is very clear that, given a value within scaffold B or A, I can use the same scaffold ordering in my projection.  This allows me to easily use the order off the scaffolds, shared between the projected and unprojected regions to calculate the proper place in coordinate space.  

In Projection 2  the scaffold ordering can not be preserved without having two unprojected scaffold A’s.  If I received an unprojected value from Scaffold A (say an fmin from a feature), I would have to supply that context as well, which is do-able, but means I have to drag the context around even more than I already do.  

![image](https://cloud.githubusercontent.com/assets/751274/18211673/c92d8640-70f3-11e6-9897-b727ef255db1.png)

**Comment by nathandunn** [comment]
For some reason the LegendTrack is not being drawn properly.

**Comment by nathandunn** [comment]
Getting annotated features works now.   I split up the other functionality (getting track data, chunks, editing, reverse complement, etc.) on #1249, #482, #1247, #1248
