### ISSUE TITLE
Error when deleting a DBXRef entry or a Gene Ontology ID entry from the Information Editor

### ISSUE THREAD

**Issue by loraine-gueguen** [GMOD/Apollo#1163]
Hi,

I have apollo 2.0.3 with a postgres database.
It is not possible to delete a DBXRef entry or a Gene Ontology ID entry from the Information Editor. 
The SQL requests seems to try to delete the entry in the dbxref table without firstly removing the entry in the feature_dbxref table.

Here is the error message :

```
Caused by PSQLException: ERROR: update or delete on table "dbxref" violates foreign key constraint "fk_n6n7lheb1qkmlde8u6gvvjxne" on table "feature_dbxref"
  Detail: Key (id)=(12429) is still referenced from table "feature_dbxref".
```

Loraine Guéguen

**Comment by nathandunn** [comment]
Error is here:

https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy#L183-L187

It ignores that DBXref can be shared, which was not true in Apollo 1, but is very true in Apollo 2.  Should be an easy fix.

**Comment by nathandunn** [comment]
PR #1166 should fix this.   Thanks for reporting.

**Comment by loraine-gueguen** [comment]
thanks!

**Comment by monicacecilia** [comment]
💃

**Comment by loraine-gueguen** [comment]
I have tested apollo-2.0.4-RC3 : I can delete GO terms and dbxref now. Thanks !
