### ISSUE TITLE
upgrade to latest version failed

### ISSUE THREAD

**Issue by lfaino** [GMOD/Apollo#1170]
Dear Nathan
Luigi again. I upgraded my WebApollo from 2.0.1 to 2.0.3 version but the 2.0.3 do not work. I can login in WebApollo as user but it is loading for ever and does not display anything

any idea?

thanks
Luigi

**Comment by nathandunn** [comment]
Did you install bower?   npm install -g bower?   If not, then you need to install it (you may need sudo access) and then an ./apollo clean-all ./apollo deploy 

If you’d already installed  bower, then if you have tomcat log files (the catalina.out) or anything in the javascript console, that would be helpful. 

Thanks,

Nathan

**Comment by lfaino** [comment]
I installed the bower but i get this set of errors

cStack trace:
Error: EACCES: permission denied, open '/home/luigi/.cache/bower/registry/bower.herokuapp.com/lookup/dojox_3fc01'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 4.2.6


[ant:echo] Will be setting up jbrowse
:copy-resources
:javac
Note: /home/luigi/Downloads/Apollo-2.0.3/src/gwt/org/bbop/apollo/gwt/client/ReferenceSequenceOracle.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:gwtc

BUILD SUCCESSFUL

Total time: 4 mins 39.857 secs

| Compiling 15 source files

| Compiling 209 source files
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
| Compiling 306 source files

| Warning The [$tt__setCurrentOrganism] action in [org.bbop.apollo.AnnotatorController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__setCurrentSequence] action in [org.bbop.apollo.AnnotatorController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__index] action in [org.bbop.apollo.AvailableStatusController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__show] action in [org.bbop.apollo.AvailableStatusController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__save] action in [org.bbop.apollo.AvailableStatusController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__edit] action in [org.bbop.apollo.AvailableStatusController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__update] action in [org.bbop.apollo.AvailableStatusController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__delete] action in [org.bbop.apollo.AvailableStatusController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__index] action in [org.bbop.apollo.CannedCommentController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__show] action in [org.bbop.apollo.CannedCommentController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__save] action in [org.bbop.apollo.CannedCommentController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__edit] action in [org.bbop.apollo.CannedCommentController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__update] action in [org.bbop.apollo.CannedCommentController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__delete] action in [org.bbop.apollo.CannedCommentController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__report] action in [org.bbop.apollo.FeatureEventController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__index] action in [org.bbop.apollo.FeatureEventController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__show] action in [org.bbop.apollo.FeatureEventController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__save] action in [org.bbop.apollo.FeatureEventController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__edit] action in [org.bbop.apollo.FeatureEventController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__update] action in [org.bbop.apollo.FeatureEventController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__delete] action in [org.bbop.apollo.FeatureEventController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__index] action in [org.bbop.apollo.FeatureTypeController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__show] action in [org.bbop.apollo.FeatureTypeController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__save] action in [org.bbop.apollo.FeatureTypeController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__edit] action in [org.bbop.apollo.FeatureTypeController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__update] action in [org.bbop.apollo.FeatureTypeController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__delete] action in [org.bbop.apollo.FeatureTypeController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__index] action in [org.bbop.apollo.ProxyController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__show] action in [org.bbop.apollo.ProxyController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__request] action in [org.bbop.apollo.ProxyController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__save] action in [org.bbop.apollo.ProxyController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__edit] action in [org.bbop.apollo.ProxyController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__update] action in [org.bbop.apollo.ProxyController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__delete] action in [org.bbop.apollo.ProxyController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__setCurrentSequenceLocation] action in [org.bbop.apollo.SequenceController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__setCurrentSequence] action in [org.bbop.apollo.SequenceController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__loadSequences] action in [org.bbop.apollo.SequenceController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__lookupSequenceByName] action in [org.bbop.apollo.SequenceController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__lookupSequenceByNameAndOrganism] action in [org.bbop.apollo.SequenceController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__getSequences] action in [org.bbop.apollo.SequenceController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
| Warning The [$tt__report] action in [org.bbop.apollo.SequenceController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

**Comment by nathandunn** [comment]
Are you doing the install as root? (that should be fine).  This is what should be called:

bower install -f --allow-root

What happens if you type it again? 

Nathan

**Comment by nathandunn** [comment]
Though you may need to run it with sudo depending on how you are installing it.   It should have been run this way, so not sure why it's failing.

**Comment by deepakunni3** [comment]
@nathandunn I think this issue might be similar to #1150.

@lfaino Are you using the Apollo 2.0.3 release or deploying from master branch?

**Comment by lfaino** [comment]
I cloned from github and deployed my self.  If I remember well, apollo local works...

**Comment by deepakunni3** [comment]
@lfaino Ah, okay.

**Comment by nathandunn** [comment]
So Apollo local works and running through tomcat does not?  

Nathan

**Comment by lfaino** [comment]
I will check tomorrow to be sure but I think that it worked with apollo local. I do not think that it is a tomcat problem because the old version still works

**Comment by nathandunn** [comment]
If it worked with Apollo local and not remote it might be that the exploded war directory was not removed from the original webapp directory.  

Nathan

**Comment by lfaino** [comment]
hi Nathan,
if i run  "bower install -f --allow-root" as normal user, I get this error:

/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/home/luigi/.config/configstore/bower-github.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Object.Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)


if I run as sudo, I get this error

bower                           ENOENT No bower.json present


Luigi

**Comment by lfaino** [comment]
to install bower, I use:


sudo npm install -g bower

**Comment by nathandunn** [comment]
@lfaino  Since I think you installed the other files using sudo access, I think what you need to do is one of two things:

1 - fix permissions to not require sudo in your config and local directories (i.e., use owner):  ie., ```sudo chown -R luigi ~/.config``` 
- OR - 
2 - install the app using sudo:  ```sudo bower install -f --allow-root``` and then change the ownership in the directory afterwards if need be.

I would try 1 first and see if you can't run the command without sudo.

**Comment by lfaino** [comment]
Hi Nathan,
i re started from scratch and now when I run "apollo run-local 8085" i can see webapollo but jbrowse do not work. in the terminal where i started apollo, i see this error

|     83 | call                              in     ''
|    383 | execute . . . . . . . . . . . . . in org.apache.shiro.subject.support.DelegatingSubject
|    362 | doFilterInternal                  in org.apache.shiro.web.servlet.AbstractShiroFilter
|    125 | doFilter . . . . . . . . . . . .  in org.apache.shiro.web.servlet.OncePerRequestFilter
|   1142 | runWorker                         in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . . . . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                               in java.lang.Thread
| Error 2016-07-12 10:05:55,682 [http-bio-8085-exec-9] ERROR apollo.PermissionService  - Problem authenticating: org.apache.shiro.authc.AccountException: Null usernames are not allowed by this realm.
| Error 2016-07-12 10:05:55,684 [http-bio-8085-exec-9] ERROR apollo.UserController  - {error=Cannot cast object 'false' with class 'java.lang.Boolean' to class 'org.codehaus.groovy.grails.web.json.JSONObject'}
| Error 2016-07-12 10:05:55,687 [http-bio-8085-exec-11] ERROR apollo.PermissionService  - Problem authenticating: org.apache.shiro.authc.AccountException: Null usernames are not allowed by this realm.
| Error 2016-07-12 10:05:55,696 [http-bio-8085-exec-11] ERROR apollo.GroupController  - {error=Cannot cast object 'false' with class 'java.lang.Boolean' to class 'org.codehaus.groovy.grails.web.json.JSONObject'}
2016-07-12 10:05:57,902 [http-bio-8085-exec-8] INFO  apollo.LoginController  - updated operation: login
2016-07-12 10:05:57,903 [http-bio-8085-exec-8] DEBUG apollo.LoginController  - login -> login


any suggestion

**Comment by lfaino** [comment]
Hi @nathandunn ,
I find out the problem or at least what i did solved the problem.
I use mysql Server version: 5.7.12-0ubuntu1.1 as database and i think that the problem was there.

In the catalina.out file, i found this error:

2016-07-12 14:25:47,026 [http-bio-8080-exec-1] ERROR spi.SqlExceptionHelper  - Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp
2016-07-12 14:25:47,036 [http-bio-8080-exec-1] ERROR errors.GrailsExceptionResolver  - SQLException occurred when processing request: [GET] /Apollo3/annotator/getAppState
Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp. Stacktrace follows:
java.sql.SQLException: Value '0000-00-00 00:00:00' can not be represented as java.sql.Timestamp

and I realized that I already had the error using PASA software. I think that my version of mysql can not use anymore the value '0000-00-00 00:00:00' 

To fix it, I changed the url for the apollo database production in the apollo-conf.groovy in 
url = "jdbc:mysql://localhost/apollo_production?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8" 

and finally worked

cheers
Luigi

**Comment by nathandunn** [comment]
Thanks for sharing (and continuing to work on it).  I had another user with a similar problem.  They removed the preference database entires and that fixed it, but this solution is more correct.   I'll add some documentation to fix this.

**Comment by nathandunn** [comment]
@lfaino  Feel free to re-open if you run into additional issues.

**Comment by lfaino** [comment]
Hi @nathandunn ,
I have only one last question. why when i run the software in local i did not get the error?

Luigi

**Comment by nathandunn** [comment]
@lfaino  They use different databases.  When you use run-local it uses the development database and when you deploy into tomcat it uses a production database.   So, you may have had changes made when you ran production, but not local.
