### ISSUE TITLE
If client token isn't provided, garbage is logged.

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1172]
Made requests like 

`http://localhost:8080/apollo/group/loadGroups/`
and
`http://localhost:8080/apollo/group/loadGroups/?clientToken=1641778653382828351543745751`

Saw this in logs. The garbage being decoded worries me that it's accessing memory it shouldn't be somewhere.

```
apollo_1      | 2016-07-07 17:56:46,763 [http-apr-8080-exec-7] ERROR apollo.PermissionService  - User null for {"clientToken":"ధ゜쪫䁘㒸倅פּ쑶鄂㖟昿絴髊䘖쮾綠벙ﺣ"} does not exist in the database.
apollo_1      | 2016-07-07 17:56:50,390 [http-apr-8080-exec-3] ERROR apollo.PermissionService  - User null for {"clientToken":"1641778653382828351543745751"} does not exist in the database.
```

**Comment by nathandunn** [comment]
I think its just a log error, but good to note either way as I do occasionally see garbage loaded as a client_token in the preference table.

**Comment by childers** [comment]
FWIW, I saw that type of message yesterday when I was loading organisms into the database via web service calls.

**Comment by nathandunn** [comment]
Good to know. Thanks.

**Comment by nathandunn** [comment]
Observed in REST web services as well (delete_all_organims).

**Comment by nathandunn** [comment]
@childers  / @erasche   This should be generating proper tokens.  Not so worried about memory access in Java, but those were definitely garbage strings.
