### ISSUE TITLE
Improper handling of features in bulk import

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1173]
When doing a bulk importing, if the GFF3 has features on scaffolds/chromosome that doesn't exist in Apollo then these annotations are added to the first found sequence from the sequence list. 

The right behavior would be to return an error indicating that no sequence could be found for the feature.

**Comment by nathandunn** [comment]
@deepakunni3  Is this part of your other bug fix? #1171

**Comment by deepakunni3** [comment]
Unfortunately, no. It might have to come in separately.

**Comment by nathandunn** [comment]
Yikes okay.  Well, we definitely need to fix this as well.

**Comment by nathandunn** [comment]
@deepakunni3  A lot of not specifying the organism comes from the older version of Apollo (where you only ever had a single organism).  I think it would be good to tighten this up to either get it from the organism or the client_token (which contains other settings in addition to organism).

**Comment by nathandunn** [comment]
Related to #1277.

**Comment by nathandunn** [comment]
Will throw an error now.
