### ISSUE TITLE
can not delete user with annotations

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1175]
If a user has annotations the feature_event table is populated, so removing the user won't work.   Might be better to "inactivate" instead of delete so that we retain annotation history.   Need to discuss with @monicacecilia 

<img width="596" alt="screen shot 2016-07-12 at 9 33 12 am" src="https://cloud.githubusercontent.com/assets/751274/16775110/ea468ef2-4813-11e6-9001-d9ecb6a88a0e.png">

**Comment by erasche** [comment]
I've hit this as well. We have users we wish to remove from the system because they no longer do annoyation. (maybe this is just a visual clutter / UX issue).

**Comment by nathandunn** [comment]
Do you thing it would make more sense to have “inactive” users, so that you know what user’s did what, even if they are no longer part of the system.  

@childers / @mpoelchau  ?

**Comment by erasche** [comment]
Aye, :+1: for inactive. Retaining history of a user's actions is important IMO.

**Comment by nathandunn** [comment]
Looks like this is a dupe of #777  . . . where we indicated that we wanted an inactive user instead.   I'll expand that issue a bit.
