### ISSUE TITLE
adding comments to sequence alteration fails to create sequence alternation

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1179]
![screen shot 2016-07-14 at 10 59 45 am](https://cloud.githubusercontent.com/assets/751274/16850046/19305e60-49b2-11e6-8b5c-054f5fd19b68.png)
![screen shot 2016-07-14 at 10 59 41 am](https://cloud.githubusercontent.com/assets/751274/16850047/19310c7a-49b2-11e6-9fcb-3490db049781.png)

**Comment by nathandunn** [comment]
To test.  Add a genomic insertion with a comment and confirm that it works.

**Comment by monicacecilia** [comment]
💃
