### ISSUE TITLE
loadLink ambiguous method overloading

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1185]
http://icebox.lbl.gov/Apollo-staging/annotator/loadLink?loc=Group5.14:1102987..1158819&organism=3836&tracks=

Give: 

{"error":"Ambiguous method overloading for method org.apache.shiro.authc.UsernamePasswordToken#.\nCannot resolve which method to invoke for [null, null] due to overlapping prototypes between:\n\t[class java.lang.String, class [C]\n\t[class java.lang.String, class java.lang.String]"}

**Comment by nathandunn** [comment]
To Test:  Test loadLink as you normally would.  Should be working now.

**Comment by monicacecilia** [comment]
💃
