### ISSUE TITLE
Forward reference sequence barely visible in dark color scheme

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#119]
As shown in the image below, it is difficult to read the forward strand of the reference sequence when zoomed to base level.

![screen shot 2014-12-18 at 1 14 51 pm](https://cloud.githubusercontent.com/assets/1714621/5496043/22e198fc-86b8-11e4-8d74-e484f761787a.png)

**Comment by nathandunn** [comment]
@deepakunni3   I'm going to have moni do the final testing for user-related stuff.  Either way, thanks for getting it in.  I'm sure its fine.

**Comment by monicacecilia** [comment]
Fixed.

**Comment by monicacecilia** [comment]
Related to this, I just found an additional bug on the display. (notice it is already present on the first image posted at the top of this issue).
When visualizing the window on the "Dark" display, the labels for each element inside the User-created Annotation area are "invisible". This happens because in "Dark" mode the characters the labels are white, and not visible with the light yellow background. Please see image below, and notice the white markings peeking on the red highlight around the selected annotation in the Uc-A area


![screen shot 2015-02-24 at 5 30 16 pm](https://cloud.githubusercontent.com/assets/1714621/6363378/2870c9f8-bc4d-11e4-97c5-fe42902ec368.png)

**Comment by cmdcolin** [comment]
I was under the impression that we changed the color to teal @deepakunni3 


Apparently the webapollo_track_styles was using a css override over this but I think after correction it was planned to look like this


![screenshot-localhost 8080 2015-02-24 21-41-59](https://cloud.githubusercontent.com/assets/6511937/6364579/00610a7e-bc6e-11e4-8a4e-972319bc74fe.png)

**Comment by deepakunni3** [comment]
Yes, the idea was for the U-cA track to be teal. I checked what was going on and it does seem that webapollo_track_styles.css overrides the color to the default. 

I tried removing the !important tag from webapollo_track_styles.css and it looks just like above. But another thing that got my attention was that now U-cA becomes transparent on mouse-over action. @cmdcolin Have you noticed the same behavior?

**Comment by cmdcolin** [comment]
Ya I have noticed that, and fixed it on the refactor branch (i changed div.track_annotation with .track.track_annotation). I have several other fixes on my refactor branch that i'm going to backport here to fix this.

**Comment by nathandunn** [comment]
![screen shot 2015-02-27 at 12 00 57 pm](https://cloud.githubusercontent.com/assets/751274/6420143/71f887fa-be78-11e4-8bbc-f1b7164c2b22.png)

**Comment by selewis** [comment]
Black would show up equally well (if not better) on both the cream or the
blue background. Can we just keep it black in either mode please.

**Comment by cmdcolin** [comment]
I made it back to black on the annotation track. Sorry about the confusion (I mixed up the unused feature_name with feature-name)

**Comment by monicacecilia** [comment]
Fixed now.

**Comment by nathandunn** [comment]
@monicacecilia   Needs to be rested.

**Comment by cmdcolin** [comment]
Should be fine (all code changes were pulled through in the pull request #248)

**Comment by monicacecilia** [comment]
@nathandunn Both strands of the reference sequence are clearly visible. :heavy_check_mark:
