### ISSUE TITLE
There is an error when I run ./apollo release

### ISSUE THREAD

**Issue by wangzhennan14** [GMOD/Apollo#1190]
Hi, 
    When I use web apollo, there are so many troubles, now there is an error, can you help me to solve this  problem?

:installJBrowse
installing jbrowse [git:[url:https://github.com/gmod/jbrowse, tag:1.12.2-apollo, alwaysPull:false, alwaysRecheck:false], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
Cloning: https://github.com/gmod/jbrowse into jbrowse-download.
using bower to install: gmod/jbrowse#1.12.2-apollo
/usr/bin/env: ‘node’: No such file or directory
:installJBrowse FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/wangzhn/Downloads/Apollo/build.gradle' line: 326

* What went wrong:
Execution failed for task ':installJBrowse'.
> Process 'command 'bower'' finished with non-zero exit value 127

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.726 secs
***************************************
NOTE: Please set the memory for your servlet container (tomcat, jetty, etc.) or Apollo may not start correctly: http://genomearchitect.readthedocs.io/en/latest/Troubleshooting/#tomcat-memory
***************************************

I think the memory of tomcat is OK.

**Comment by nathandunn** [comment]
You need to install node.js and use node.js to install bower.  

Nathan

**Comment by nathandunn** [comment]
https://nodejs.org/en/download/

```npm install -g bower```

**Comment by nathandunn** [comment]
Also, you may wish to use ```./apollo deploy``` to confirm that you can get it to work and then use ```./apollo release``` (which is more experimental) once you have confirmed it is working.
