### ISSUE TITLE
'JSONObject["clientToken"] not found.' when running add_transcripts_from_gff3_to_annotations.pl

### ISSUE THREAD

**Issue by brkldj** [GMOD/Apollo#1193]
Hi,

I'm trying to add a gff file to the annotation track directly via command line (instead of dragging every gene model), as described [here](http://genomearchitect.readthedocs.io/en/latest/Data_loading.html#gff3). When running add_transcripts_from_gff3_to_annotations.pl, I get errors like this:
```
Processing evm.TU.scaffold00091.84: http://localhost:8080/apollo/annotationEditor/addFeature 
error: 500 Internal Server Error
```
catalina.out has entries of this type:
```
2016-07-28 15:57:12,510 [http-bio-8080-exec-49] ERROR errors.GrailsExceptionResolver  - JSONException occurred when processing request: [POST] /apollo/annotationEditor/addFeature
JSONObject["clientToken"] not found.. Stacktrace follows:
org.codehaus.groovy.grails.web.json.JSONException: JSONObject["clientToken"] not found.
        at org.bbop.apollo.PermissionService.$tt__hasPermissions(PermissionService.groovy:412)
        at org.bbop.apollo.AnnotationEditorController.addFeature(AnnotationEditorController.groovy:164)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
I'm assuming this has something to do with authentication. I'm using the admin email address and password - the same as logging in in the browser. Do you have any idea where am I going wrong? It might be something trivial since this is the first time I set up webapollo.

Semi-related question: is there an easy way to figure out which version am I using? (The Help->Get version link in browser is for some reason not working - but everything else does.)

Thanks!

**Comment by nathandunn** [comment]
Was just about to ask what version you were using.  We had a bug like that earlier, but am fairly certain it is now fixed.  This is how you check:

![screen shot 2016-07-28 at 7 43 22 am](https://cloud.githubusercontent.com/assets/751274/17216815/056679e2-5497-11e6-8da7-fd5d47201b90.png)

**Comment by brkldj** [comment]
Help->Get version returns a "HTTP Status 404" error by Tomcat, so I was wondering if there is an alternative (command-line?) option of checking the version.

**Comment by nathandunn** [comment]
Sure.  If you cloned from git, do ```git status``` or ``` git log | head -6``` and I can figure it out.

**Comment by nathandunn** [comment]
Otherwise, it is whatever release you downloaded from:  https://github.com/GMOD/Apollo/releases

**Comment by brkldj** [comment]
Great, thanks. Does this help?

```
commit dd7523314326c96c1f7d116aa5c13847738baea4
Author: Monica Munoz-Torres <monicacecilia@users.noreply.github.com>
Date:   Thu May 12 04:37:24 2016 -0700
```

**Comment by nathandunn** [comment]
Yes.  That is a pretty old non-release version (2.0.3-RC1 [release candidate 1] i.e., we fixed things after it went in).  We'll have a fully-vetted 2.0.4 release out sometime this month.  Master should be relatively stable (a couple more pull requests will be going in today) if you need to get stuff done sooner than later:

```
git pull
./apollo clean-all
./apollo deploy 
```

You should see a large number of file changes with the git pull.  If not type ```git status```.

**Comment by brkldj** [comment]
I now have:
```
commit e387b8beaf43de82eaf2c963066802470e831827
Author: Nathan Dunn <nathandunn@users.noreply.github.com>
Date:   Wed Jul 27 12:00:21 2016 -0700
```
The errors that I now get of the following type:
```
Processing evm.TU.scaffold00161.4: http://localhost:8080/apollo/annotationEditor/addTranscript 
error: JSONObject["clientToken"] not found.
```
-- the problematic part is now addTranscript (before it was addFeature).

**Comment by nathandunn** [comment]
How are you running the command (what is on the command-line)? 

If you have some sample GFF3, that would help as well. 

We’ve been testing this function, explicitly and it has been working, but there are always cases we didn’t consider.

**Comment by brkldj** [comment]
This is how I run it:
`/home/brkldj/software/Apollo/tools/data/add_transcripts_from_gff3_to_annotations.pl -U localhost:8080/apollo -u 'me@mail.com' -p 'pass' -i test7.gff -t mRNA -o "species1"`

Attached is a minimum example gff file with a random gene (I added .txt because otherwise I can't upload it)
[test7.gff.txt](https://github.com/GMOD/Apollo/files/388958/test7.gff.txt)

Here is the complete output for this example (if I remove the UTRs from the gff file, also the first two lines disappear):
```
Ignoring unsupported sub-feature type: five_prime_UTR
Ignoring unsupported sub-feature type: three_prime_UTR
Processing scaffold00263
Processing chunk 1: http://localhost:8080/apollo/annotationEditor/addTranscript 
error: JSONObject["clientToken"] not found.
Processing individual features for failed chunks
Processing evm.TU.scaffold00263.19: http://localhost:8080/apollo/annotationEditor/addTranscript 
error: JSONObject["clientToken"] not found.
```

**Comment by nathandunn** [comment]
```
./tools/data/add_transcripts_from_gff3_to_annotations.pl -i test.gff3 -o "Pipefish" -u 'me@myemail.com' -p 'password' -U localhost:8080/apollo
```

This worked for me:

![screen shot 2016-07-28 at 10 44 57 am](https://cloud.githubusercontent.com/assets/751274/17223208/68ee17d6-54b0-11e6-95d8-3f2bded881a2.png)

Somehow I don't think you have a clean build.  Did you replace your war file after you did deploy? 

http://genomearchitect.readthedocs.io/en/latest/Migration.html?highlight=tomcat#migration-from-2-0-x-to-2-0-y-on-production

If you did a clean-all, then you should just stop tomcat, remove the old war file and directory from tomcat and copy the new one over.

**Comment by brkldj** [comment]
Good point, I didn't replace the war file.

With the new version add_transcripts_from_gff3_to_annotations.pl works fine (it's still running, but it has none of the errors that appeared before). Thanks!
