### ISSUE TITLE
document "canned" things

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1194]
- [x] canned comments
- [x] canned tags / keys 
- [x] canned values 
- [x] note how they interact with FeatureType

~-[ ] change canned "keys" to canned "tags"~

**Comment by nathandunn** [comment]
For whenever.

**Comment by nathandunn** [comment]
Note that the canned comments can be filtered by FeatureType. 

![screen shot 2016-08-31 at 10 05 32 am](https://cloud.githubusercontent.com/assets/751274/18138765/33b27e4a-6f63-11e6-9d32-3ed619cd87d2.png)


![screen shot 2016-08-31 at 10 10 41 am](https://cloud.githubusercontent.com/assets/751274/18138764/30da783a-6f63-11e6-9f63-9464ffc184a5.png)

**Comment by monicacecilia** [comment]
The list of _Feature Types_ associated with each comment is visible, but this information is not currently available for admins to interact with from the UI. I.e. you can't click on a feature type to display all canned elements associated with it, are feature types listed in the details page for each canned element. 

@nathandunn you said: 
> Note that the canned comments can be filtered by FeatureType.

Do you mean that admins can programmatically search through canned comments, filtering by FeatureType as well?
