### ISSUE TITLE
clicking "show annotator panel" fails in logged-in apollo mode 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1195]
Clicking on "show annotator panel" in full-screen mode leads to this screen, where the clientToken is obviously not being transformed into a string properly.:

http://icebox.lbl.gov/Apollo-staging/annotator/index?clientToken=[Ljava.lang.String;@6acd68b8&tracklist=1&highlight=0..-1&tracks=DNA,Annotations,Nurse,Forager,Official%20Gene%20Set%20v3.2&nav=1&overview=1

<img width="1326" alt="screen shot 2016-07-28 at 11 05 48 pm" src="https://cloud.githubusercontent.com/assets/751274/17239298/db22ee32-5517-11e6-8254-3644bfeced95.png">

**Comment by nathandunn** [comment]
So, this is pretty inconsistent and flaky.    I think, related to #1126, we should change the behavior to open and close the side-bar only.  It would be a lot cleaner and give the eventual correct behavior:

<img width="565" alt="screen shot 2016-07-28 at 11 46 02 pm" src="https://cloud.githubusercontent.com/assets/751274/17240104/ffa8ec06-551d-11e6-95c5-52ab84cf603c.png">

**Comment by monicacecilia** [comment]
I did not see the 404 error; instead if I am currently in the _Full-screen view_ and choose to _Show Annotator Panel_, then the annotator panel shows up again, __and__ the JBrowse list of available tracks remains in the window as such: 
![screen shot 2016-07-29 at 1 34 13 pm](https://cloud.githubusercontent.com/assets/1714621/17262692/aeeca888-5591-11e6-8ce1-9df43055378c.png)

**Comment by nathandunn** [comment]
Would it be okay if the show annotate / full screen options just opened and closed the annotator panel (i.e., the same as the button at the top)? 

Nathan

**Comment by monicacecilia** [comment]
No, I think that dismisses the original intent of having the _Full-screen view_: to offer the ability to include the JBrowse menu, or remove it.

**Comment by nathandunn** [comment]
You can do that already be choosing the native track list from the track menu.   

Nathan

**Comment by nathandunn** [comment]
We can fix that either way. 

Nathan

**Comment by monicacecilia** [comment]
Yes. That's already addressed with the toggle menu to _Show JBrowse Track Selector_. Unfortunately, at the moment, the _Full-screen view_ is the __only__ way in which we can display the data in the browser without being logged into Apollo.

**Comment by nathandunn** [comment]
Talked with i5K people today and I proposed a solution where full-screen mode would just slide out the annotator panel.  They said they would be fine with that, but that users would be confused as to where the track panel went to and how do you get it back.   This brings up why doesn't the track panel not have a show-hide button in the first-place, which we could add? 

WRT to logged out, jbrowse only view, that shouldn't be affected, but that is an important use-case as well when switching.

- [ ] handle logged-in, full-screen view - to annotator view, multiple times
- [ ] handle logged-out, full-screen view to annotator view, multiple times
- [ ] handle logged-out, full-screen view to logged-in view, multiple times

**Comment by nathandunn** [comment]
To fix:

- [ ] initially (prior to this), we have 3 current organisms, but we only want the one with the sequence populated (others should be deleted, or never created).  If it is a different sequence it could just be ignored
- [ ] when coming back (clicking AnnotatorPanel) we should delete any preference that shares the organism, and doesn't have 
- [ ] when coming back (clicking AnnotatorPanel), tracklist is not set to 0, which seems to confuse the native track selector in the Annotator Panel
- [ ] add a "view track panel" button somewhere in JBrowse-land?

**Comment by monicacecilia** [comment]
@nathandunn This may be a little 'meta' but if you look up this thread, you can see that I had already shared the same objection to your idea that "full screen mode just slide[s] out the _Annotator Panel_". 
Your solution was to toggle the JBrowse track list, as it is already possible from the _Annotator Panel_ using the _Show JBrowse Track Selector_ button. 
Again I add: Unfortunately, at the moment, the _Full-screen view_ is the __only__ way in which we can display the data in the browser without being logged into Apollo. Please keep that in mind as well. As (I think) you mention, this function cannot be lost.

**Comment by nathandunn** [comment]
> Please keep that in mind as well. As (I think) you mention, this function cannot be lost.

Yeah.  That is what I was responding to.   We definitely need that functionality as well.

**Comment by nathandunn** [comment]
This proposal was just a proposal . .  I'm going try and address the stuff in [this comment](https://github.com/GMOD/Apollo/issues/1195#issuecomment-238260600) first.

**Comment by nathandunn** [comment]
ClientToken was being handled in twice, so it was a string array instead of a string . . which confused java

**Comment by monicacecilia** [comment]
Tested all functionality. Nearly all steps worked as expected, except: 

- if users is not given permissions, then they are unable to browse public genomes using the link in the 'You do not have permissions' dialog box. Instead, they see this window: 
![screen shot 2016-08-09 at 11 17 11 am](https://cloud.githubusercontent.com/assets/1714621/17528223/4c9e13ac-5e23-11e6-9cd6-e761ba4b96b2.png)

- if later on, users re-enter this URL http://icebox.lbl.gov/Apollo-staging/jbrowse/ then the list of organisms available for public browsing appears. 

@nathandunn are you experiencing the same? (is this what you were referring to above in your list 'To test'?

**Comment by nathandunn** [comment]
To reproduce, login, go to /apollo/jbrowse/  . . was because it was returning the index.html if you had a valid user, but not a valid organism or client_token.  

Fixed.

**Comment by monicacecilia** [comment]
It is fixed. All other steps in the above testing work. Gets a 💃 !
