### ISSUE TITLE
Can annotation track be exported as gff3 on command line?

### ISSUE THREAD

**Issue by brkldj** [GMOD/Apollo#1197]
Hi all,

does [this thread](http://gmod.827538.n3.nabble.com/Export-curation-track-using-command-line-tool-td4046178.html) reflect the most up-to-date information or is there by now a simpler way of exporting annotation track data on command line?

**Comment by monicacecilia** [comment]
Hi @brkldj,
The thread you refer to no longer reflects the most current information for Apollo. A number of changes have been introduced in the past 2 years, which included a substantial restructure of the architecture. 

@deepakunni3 has made tremendous improvements to our ability to export data in several formats using the _Annotator Panel_, and although there currently isn't a way to export GFF3 from the command line, I am positive that we can easily generate a script to assist in doing so. 
I have added this to our tasks for next release, although unfortunately this may not happen very rapidly. 

In the mean time, you can export a GFF3 with annotations from all or a selected group of scaffolds / chromosomes in your genome using the _Annotator Panel_. I am sure you have already checked this functionality, but please let us know if you have any questions. 

Should you feel inclined to explore the code and work on a script yourself before we get to it, please let us know and we can point you in the right direction. :bowtie:

**Comment by erasche** [comment]
https://github.com/TAMU-CPT/galaxy-apollo/blob/master/export.py will likely accomplish what you need. it requires the webapollo.py file that is in the same folder and a number of dependencies to function (bcbio-gff, biopython), but that downloads gff3 and fasta sequences from an apollo instance.

Hope this helps.
