### ISSUE TITLE
Changing the color scheme overwrites the 'color by CDS' command.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#120]
Changing the color scheme overwrites the 'color by CDS' command.

**Comment by monicacecilia** [comment]
Tested and it is fixed.

**Comment by nathandunn** [comment]
@monicacecilia  Needs to be retested.

**Comment by cmdcolin** [comment]
Color by CDS should be working in 2.0

**Comment by monicacecilia** [comment]
@nathandunn The function is maintained after changing color scheme. Also, it seems to work a lot faster!  - but it may just be me. :) :heavy_check_mark:
