### ISSUE TITLE
Fix display of 'Create User' button in User tab of the Annotator Panel

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1200]
The _Create User_ button in the _User_ tab of the _Annotator Panel_ is cut off in Firefox (v48.0) for Mac (MacOS 10.11.6). 

![screen shot 2016-08-09 at 11 09 46 am](https://cloud.githubusercontent.com/assets/1714621/17527889/fd34bb46-5e21-11e6-8f04-80372b80a406.png)

**Comment by nathandunn** [comment]
Fixed for firefox and updated the annotator panel as well (appears similar in Chrome, as well):

![screen shot 2016-08-09 at 11 42 13 am](https://cloud.githubusercontent.com/assets/751274/17528986/75f127e6-5e26-11e6-9671-81c321d88776.png)
![screen shot 2016-08-09 at 11 42 08 am](https://cloud.githubusercontent.com/assets/751274/17528983/75eaecdc-5e26-11e6-9ff5-a664e9d827f1.png)
![screen shot 2016-08-09 at 11 42 04 am](https://cloud.githubusercontent.com/assets/751274/17528984/75ed1692-5e26-11e6-8ce6-304ed35051d6.png)
![screen shot 2016-08-09 at 11 41 59 am](https://cloud.githubusercontent.com/assets/751274/17528985/75ef2298-5e26-11e6-8d70-7dbc818718bb.png)

**Comment by monicacecilia** [comment]
it is fixed! 💃
