### ISSUE TITLE
Refresh required to recalculate CDS after removing sequence alteration.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1201]
@deepakunni3 @nathandunn 
If there is a gene model in the U-cA area,  and I add a sequence alteration that modifies the CDS,
and then I remove the sequence alteration: the CDS does not go back to what it was before, until the window is refreshed. So although the longest ORF might be recalculated after each operation, it is not apparent until after refreshing.

**Comment by nathandunn** [comment]
The issue I am seeing is that it is not re-calculating the longestORF in that region, refresh or not.   I have to explicitly recalculate it.   The code is definitely in there.

**Comment by monicacecilia** [comment]
Exactly what I said to you earlier. 
And if you conduct a second operation (without refresh), you also force the ORF recalculation.

**Comment by nathandunn** [comment]
Sorry, by refresh I thought you meant refresh the screen.

**Comment by nathandunn** [comment]
Yes, what you are experience is consistent with what I see.   Hopefully an easy fix.

**Comment by nathandunn** [comment]
This was failing to flush properly (due to the grails upgrade, we have to do this a bit more explicitly now).  I'm going to check for a few other locations as well: 

```
diff --git a/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy b/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
index 5d99863..083ef59 100644
--- a/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
+++ b/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
@@ -1176,7 +1176,7 @@ class RequestHandlingService {
             FeatureLocation sequenceAlterationFeatureLocation = sequenceAlteration.getFeatureLocation()
             deleteFeatureContainer.getJSONArray(FeatureStringEnum.FEATURES.value).put(featureService.convertFeatureToJSON(sequenceAlteration, true));
             FeatureLocation.deleteAll(sequenceAlteration.featureLocations)
-            sequenceAlteration.delete()
+            sequenceAlteration.delete(flush: true)
 
             for (Feature feature : featureService.getOverlappingFeatures(sequenceAlterationFeatureLocation, false)) {
                 if (feature instanceof Gene) {
@@ -1185,7 +1185,7 @@ class RequestHandlingService {
                         nonCanonicalSplitSiteService.findNonCanonicalAcceptorDonorSpliceSites(transcript)
                         updateFeatureContainer.getJSONArray(FeatureStringEnum.FEATURES.value).put(featureService.convertFeatureToJSON(transcript, true));
                     }
-                    feature.save()
+                    feature.save(flush: true)
                 }
             }
         }
```

**Comment by deepakunni3** [comment]
@nathandunn Yes, I see what is happening. A flush seems to fix this issue. 
Its surprising that we didn't see this earlier in any of our previous releases.

**Comment by monicacecilia** [comment]
@deepakunni3 shhhhhh 👀  don't tell anybody.
:bowtie:

**Comment by nathandunn** [comment]
I went through and didn't see any more obvious places.  We have so many default operations that flush, sequence alteration just uses a slightly different mecahnism.

**Comment by deepakunni3** [comment]
@monicacecilia No, I am sure it wasn't there before (i.e. Apollo 2.0.1 or 2.0.2). 

Must be careful with the use of flush when saving or deleting.

**Comment by nathandunn** [comment]
@deepakunni3  It was the upgrade to 2.5.4 upgraded hibernate to make the use of flush a bit more required.

**Comment by deepakunni3** [comment]
Aah, okay! Thanks for getting the fix in. 👍

**Comment by monicacecilia** [comment]
@deepakunni3 I am certain that this delay was not there when I tested 2.0.2. I tested the behavior and it recalculated ORF right away.

**Comment by nathandunn** [comment]
@monicacecilia  Ready to test

**Comment by monicacecilia** [comment]
Tested. ORF is now being recalculated as expected. 💃
