### ISSUE TITLE
Schema update errors when upgrading to 2.0.4

### ISSUE THREAD

**Issue by loraine-gueguen** [GMOD/Apollo#1202]
Hi,

I had some errors when deploying release 2.0.4 (upgrade from 2.0.2) :

```
> 2016-08-16 17:51:31,031 [localhost-startStop-4] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: alter table preference add column client_token varchar(255) not null
> 2016-08-16 17:51:31,033 [localhost-startStop-4] ERROR hbm2ddl.SchemaUpdate  - ERROR: column "client_token" contains null values
> 2016-08-16 17:51:31,035 [localhost-startStop-4] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: alter table preference add column date_created timestamp not null
> 2016-08-16 17:51:31,035 [localhost-startStop-4] ERROR hbm2ddl.SchemaUpdate  - ERROR: column "date_created" contains null values
> 2016-08-16 17:51:31,036 [localhost-startStop-4] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: alter table preference add column last_updated timestamp not null
> 2016-08-16 17:51:31,036 [localhost-startStop-4] ERROR hbm2ddl.SchemaUpdate  - ERROR: column "last_updated" contains null values
```

And a warning probably linked to the previous error when I log in to apollo through a browser: 

`2016-08-16 17:57:39,317 [http-bio-8080-exec-1883] WARN  apollo.PreferenceService  - Multiple preferences found: 2`

Indeed, the table "preference" already had entries before upgrade to release 2.0.4, and the 3 new columns are null for these entries.

It does not seem a major issue, but I hope it can help to improve the database schema update.
Regards,

Loraine

**Comment by nathandunn** [comment]
@loraine-gueguen  Thanks for bringing this to our attention.  

If you type: ```delete from preference``` and restart does it solve your problem?

**Comment by nathandunn** [comment]
Sorry, to be more specific:

- stop tomcat (or wherever you're putting the .war file)
- In the database: ```delete from preference;```
- start tomcat

Please let me know if this does or does not fix it.   I'll upgrade the database migration script to correspond to this and let the community know once we get it fixed. 

Thanks.

**Comment by nathandunn** [comment]
@loraine-gueguen  If that doesn't work, then instead of deleting the content from the preference table, you can drop the preference table instead, and it will get regenerated when you start back up.

**Comment by nathandunn** [comment]
@loraine-gueguen  Just to clarify (and so I can better provide a solution for other users as well), what version are you upgrading from?  Typically we have scripts that do the upgrade between versions, but we might missed something between 2.0.3 and 2.0.4.  If you were running off of master, then the advice I'd given previously is probably the best option.

**Comment by loraine-gueguen** [comment]
@nathandunn 
I am upgrading from release 2.0.2.
Indeed, doing `delete from preference;` before upgrading from 2.0.2 to 2.0.4, fix it : no more ERROR messages, and the 3 new columns are clean with a "not null" constraint.

However, I have already upgraded my production instance to 2.0.4 yesterday and have had the ERROR messages for the schema update. So, the table "preference" is structured this way: 

```
apollo=# \d preference
                 Table "public.preference"
       Column       |           Type           | Modifiers 
--------------------+--------------------------+-----------
 id                 | bigint                   | not null
 version            | bigint                   | not null
 domain             | character varying(255)   | 
 name               | character varying(255)   | 
 preferences_string | character varying(255)   | 
 class              | character varying(255)   | not null
 user_id            | bigint                   | 
 current_organism   | boolean                  | 
 endbp              | integer                  | 
 native_track_list  | boolean                  | 
 organism_id        | bigint                   | 
 sequence_id        | bigint                   | 
 startbp            | integer                  | 
 client_token       | character varying(255)   | not null
 date_created       | timestamp with time zone | 
 last_updated       | timestamp with time zone | 
```

As you can see, no "not null" constraint for columns "date_created" and "last-updated" (as a consequence of the schema update errors).

So I have 2 questions:

1- Is it safe to do `delete from preference;` anytime ? This table only save the user last location on the genome ?

2- Is it right to add a "not null" constraint for columns "date_created" and "last-updated" afterwards ?
```
ALTER TABLE preference ALTER COLUMN date_created SET NOT NULL;
ALTER TABLE preference ALTER COLUMN last_updated SET NOT NULL;
```

**Comment by nathandunn** [comment]
> 1- Is it safe to do delete from preference; anytime ? This table only save the user last location on the genome ?

Yes it is safe.  And you are correct, that is its function.  

> 2- Is it right to add a "not null" constraint for columns "date_created" and "last-updated" afterwards ?

Yes.

**Comment by nathandunn** [comment]
Thanks.  Yes, these are mostly a benign warnings.  While I can't change the migration script, the current state should be fine.    In a subsequent release we'll probably just make the those nullable columns or delete preferences where these are null.  

The "multiple preferences" error should go away over time (I hope), but should not effect overall functionality.  

Thanks for reporting.

**Comment by loraine-gueguen** [comment]
thanks for your answers

**Comment by nathandunn** [comment]
Closing for now . . let me know if there are further problems
