### ISSUE TITLE
projection: partial feature not visible when getting features in a projection

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1215]
Full features (that don't cross) are visible, but not the partial features:

I did this by adding exons across two split scaffolds:

<img width="1272" alt="screen shot 2016-08-18 at 2 15 15 pm" src="https://cloud.githubusercontent.com/assets/751274/17791085/51515760-654e-11e6-91d8-89ebe18c54d8.png">

<img width="1312" alt="screen shot 2016-08-18 at 2 15 25 pm" src="https://cloud.githubusercontent.com/assets/751274/17791084/514d63c6-654e-11e6-8e21-07165c791268.png">

**Comment by monicacecilia** [comment]
Note: this is happening after refreshing the page, not immediately after bringing them together.

**Comment by nathandunn** [comment]
When observe 3 transcripts that span two combined / full  scaffolds:

![screen shot 2016-08-23 at 11 20 41 am](https://cloud.githubusercontent.com/assets/751274/17904308/b1f10b32-6923-11e6-8524-c0ff1f7584ff.png)

When we view the projected versions we see the two perfectly:

![screen shot 2016-08-23 at 11 20 56 am](https://cloud.githubusercontent.com/assets/751274/17904307/b1e16ef2-6923-11e6-8548-75b03983fe71.png)

We can confirm that the third should not have been visible (on the LHS it is clear, but not on the RHS without zooming in):

![screen shot 2016-08-23 at 11 21 48 am](https://cloud.githubusercontent.com/assets/751274/17904333/d07cf476-6923-11e6-81de-f4aa107177e3.png)
