### ISSUE TITLE
Typo on right-click menu: replace 'opposte' with 'opposite'

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#122]
![screen shot 2014-12-18 at 2 47 14 pm](https://cloud.githubusercontent.com/assets/1714621/5497275/d94a0640-86c4-11e4-98ff-67c715a71f79.png)

**Comment by nathandunn** [comment]
re-applying fix in 2.0.0

**Comment by cmdcolin** [comment]
Looks fine to me but as long as we're talking about it, the capitalization was inconsistent and so I updated it here https://github.com/GMOD/Apollo/commit/15ee09830fd9224a308bd0647a67f2948372d5c1

Hope that's ok

**Comment by monicacecilia** [comment]
@nathandunn I'm having flashbacks to a convo about caps per word... but I can't remember the details. 

Thanks @cmdcolin. I checked all menus. Typos have been fixed. :heavy_check_mark:
