### ISSUE TITLE
projection: sequence alteration

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1228]
- [x] fix general error (below)
- [x] single scaffold?
- [ ] dual scaffold, second position (not working)
- [ ] projected single scaffold (not working), puts in the wrong position
- [ ] projected dual scaffold, second position
# 

Getting an error:

<img width="256" alt="screen shot 2016-08-26 at 7 29 46 am" src="https://cloud.githubusercontent.com/assets/751274/18008938/fa95a374-6b5e-11e6-9757-751e5f1f3854.png">
<img width="1430" alt="screen shot 2016-08-26 at 7 29 53 am" src="https://cloud.githubusercontent.com/assets/751274/18008940/fa9ac4da-6b5e-11e6-9a6f-f2f794a634a4.png">
<img width="603" alt="screen shot 2016-08-26 at 7 29 59 am" src="https://cloud.githubusercontent.com/assets/751274/18008939/fa9678f8-6b5e-11e6-9c95-6b895cd25c4c.png">

The errant JSON is: 

```
"{ "track": "{"name":"Group11.4", "padding":0, "start":0, "end":75085, "sequenceList":[{"name":"Group11.4", "start":0, "end":75085}]}:0..75085", "features": [ { "location": { "fmin": 32499, "fmax": 32508, "strand": 1 }, "type": {"name": "substitution", "cv": { "name":"sequence" } }, "residues": "ATATAGATA", "non_reserved_properties": [{"tag": "justification", "value": "sfsafda" }] } ], "operation": "add_sequence_alteration" }"
```

should be fixed as follows, cleaning up the track attribute:

```
{ "track": {"name":"Group11.4", "padding":0, "start":0, "end":75085, "sequenceList":[{"name":"Group11.4", "start":0, "end":75085}]}, "features": [ { "location": { "fmin": 32499, "fmax": 32508, "strand": 1 }, "type": {"name": "substitution", "cv": { "name":"sequence" } }, "residues": "ATATAGATA", "non_reserved_properties": [{"tag": "justification", "value": "sfsafda" }] } ], "operation": "add_sequence_alteration" }
```

**Comment by deepakunni3** [comment]
@nathandunn I am also seeing the same bad JSON being prepared. But why is this not affecting other editing operations on AnnotTrack?

**Comment by nathandunn** [comment]
@deepakunni3  I think I clean it up or it somehow correctly gets cleaned up somewhere else.  

However, if its just adding the string values, should be an easy fix.

**Comment by deepakunni3** [comment]
I can work on it since its part of this issue.

Might find a way to have both AnnotTrack and SequenceTrack use the same operation to tidy up the sequence list.

**Comment by nathandunn** [comment]
Nice.  

Make sure to bring the fixes off of master in, as well.  Hopefully just a couple of small ones.

**Comment by deepakunni3** [comment]
So the main issues where that the sequence alterations were not being unprojected and then properly projected back again before sending JSON to the client.
