### ISSUE TITLE
projection: change annotation type

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1229]
- [ ] test single scaffold
- [ ] test dual scaffold in second position
- [ ] test projected single scaffold
- [ ] test projected dual scaffold in the second position

**Comment by deepakunni3** [comment]
@nathandunn 'Change annotation type' fails on reverse complement view.

**Comment by deepakunni3** [comment]
@nathandunn In reverse complement mode, change annotation type now works but with a small bug. If I change the annotation type the feature vanishes. After a page refresh the correct feature shows up. Probably has to do with not triggering an update properly after the annotation has been modified?

**Comment by nathandunn** [comment]
Okay.  I'll fix this as part of #1636.   I think its the same solution as for fixing history.
