### ISSUE TITLE
getUserPermissionsForUser is non-standard

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1230]
Getting webservices via:

```curl -i -X POST -H 'Content-Type: application/json' -d ‘{"data”:{"username": "admin-user@none.none", "password": "secret", "userId": “1156181"}}' https://apollo-dev.server.no/apollo/user/getOrganismPermissionsForUser``` 

produces:

```
git diff
diff --git a/grails-app/controllers/org/bbop/apollo/UserController.groovy b/grails-app/controllers/org/bbop/apollo/UserController.groovy
index 8d1fcdc..74925af 100644
--- a/grails-app/controllers/org/bbop/apollo/UserController.groovy
+++ b/grails-app/controllers/org/bbop/apollo/UserController.groovy
@@ -421,7 +421,8 @@ class UserController {
             , @RestApiParam(name = "userId", type = "long", paramType = RestApiParamType.QUERY, description = "User ID to fetch")
     ])
     def getOrganismPermissionsForUser() {
-        JSONObject dataObject = JSON.parse(params.data)
+//        JSONObject dataObject = JSON.parse(params.data)
+        JSONObject dataObject = permissionService.handleInput(request, params)
         User user = User.findById(dataObject.userId)
 
         List<UserOrganismPermission> userOrganismPermissionList = UserOrganismPermission.findAllByUser(user)
```

**Comment by erasche** [comment]
So that's the fix for this...had hit this bug forever ago (didn't see the email until just now). I had settled for getting the user list which happens to contain complete permission info and parsing that. Glad to see this route will be functional again.

**Comment by nathandunn** [comment]
Yeah, sorry about that.    I remember you asking about this and the complicated ways you were going about it.  

It seems to work for me, but let me know if it works for you or not.   Should return stuff of this nature:

```
[
   {
      "class":"org.bbop.apollo.UserOrganismPermission",
      "id":255080,
      "organism":{
         "class":"org.bbop.apollo.Organism",
         "id":16
      },
      "permissions":"[\"WRITE\"]",
      "user":{
         "class":"org.bbop.apollo.User",
         "id":243581
      }
   },
   {
      "class":"org.bbop.apollo.UserOrganismPermission",
      "id":255079,
      "organism":{
         "class":"org.bbop.apollo.Organism",
         "id":237860
      },
      "permissions":"[\"WRITE\"]",
      "user":{
         "class":"org.bbop.apollo.User",
         "id":243581
      }
   }
]
```

**Comment by nathandunn** [comment]
@erasche / @childers   If you want to add additional detail feel free to open another PR.   Currently it returns the minimum.  It could be expanded in the UserController method explicitly, or in the [DomainMarshallerService.groovy](https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/DomainMarshallerService.groovy).
