### ISSUE TITLE
Problems with API: loadUsers

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1238]
I'm also seeing the same error with the loadUsers API:

 ```
https://server.org/apollo/user/loadUsers?username=admin@server.org&password=secret&userId=18
```
```shell
{
  "error": "Cannot cast object 'false' with class 'java.lang.Boolean' to class 'org.codehaus.groovy.grails.web.json.JSONObject'"
}
```

**Comment by nathandunn** [comment]
It only uses POST commands:

    curl  -i -X POST -H 'Content-Type: application/json' -d "{'username': 'demo@demo.com', 'password': 'supersecret','userId':288335}" http://server.org/apollo/user/loadUsers

FYI, if you pass an a username as a string for userId. 

I could see how this should probably be a get operation, though I'm not sure I'd want to pass admin credentials in the URL versus the payload.

**Comment by childers** [comment]
That's an artifact of me using postman to run the calls.  It is strange that some calls work with postman while others don't, and all of them seem to work with curl so far.
