### ISSUE TITLE
UI glitch with more than ten groups

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1242]
Hi all, 
I've been working on building groups for our organisms, and found a fun visual artifact that had me rerunning my create-groups script. The main groups tab only shows ten groups and has no navigation for pagination and making the panel larger will not show more groups.

Looking at the groups interface in the users tab, I can see all of the groups.

**Comment by nathandunn** [comment]
Okay.  That should be easy to fix.   Yeah, we handled that for other cases (users, etc.), just not groups.

**Comment by nathandunn** [comment]
@childers  Is it blocking today? . . . otherwise I can get to it by the end of the week.

**Comment by childers** [comment]
Not a blocker, since I can verify them through the user tab.

**Comment by monicacecilia** [comment]
Solved.

**Comment by monicacecilia** [comment]
Tested.
