### ISSUE TITLE
Fix case in Webservice docs

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1244]
I was working on using the web service call to update group permissions, and I learned that the read write, export and administrate need to be in all CAPS to work, but that isn't shown in the documentation. It wasn't a huge deal to work out, but it would have saved me a few rounds of checking server logs to see why it wasn't working. In this particular case, it's also good to know you that the groupId is not required as long as you know the group name. 

```shell
username 	email
password 	password
groupId 	long Group ID to modify permissions for
name 	string Group name to modify permissions for
organism 	string Organism common name
administrate 	boolean Indicate if user has administrative (including user/group) privileges for the organism
write 	boolean Indicate if user has write privileges for the organism
export 	boolean Indicate if user has export privileges for the organism
read 	boolean Indicate if user has read privileges for the organism 
```

**Comment by nathandunn** [comment]
- [ ] UserController::updateOrganismPermissions
- [ ] GroupContrller::updateOrganismPermissions

@childers  You didn't mention the fact that I'd ended these all with prepositions.   Makes sense to update it.
