### ISSUE TITLE
information editor -> 'Add' button not working

### ISSUE THREAD

**Issue by alpapan** [GMOD/Apollo#125]
Hello

A critical issue:

In the NAL's installation of WebApollo, the Add button of the information editor seems broken. Second issue is that the existing data are not available to view either (e.g. Comments and GO terms)

This is separate for Gene and mRNA. For mRNA I can fix it if either i) select Get Sequence first or ii) select another mRNA (if one exists) and go back. However, no comments are viewable or addable for Gene.

This is not consistently happening across all user-contributed annotations. It has increased over time (only a few in early December, now most of them).

So it seems that there is something happening at the initialisation of the information editor and I think it is linked to the integrity of the berkeleyDB rather than the js code.

Using Firebug I can see that events are fired if I click Delete and not if I click Add. 

an example is available from Monica Poelchau (mention cercap) who can create accounts.

thanks
a
![untitled](https://cloud.githubusercontent.com/assets/608484/5591535/afe90e2c-91b9-11e4-8a49-8cc050caff74.png)

**Comment by nathandunn** [comment]
@alpapan    My intuition is that you are correct that it is a corrupt BDB.   Our 2.0 release is doing away with it.  My guess is that the information being retrieved is broken and is somehow killing any event code.  If this is seriously blocking then shoot me an email (Monica and Chris should have it) and I'll tree to see if there isn't a workaround.

**Comment by monicacecilia** [comment]
This seems to be another connectivity ^/∨ latency issue. 
We are confident that 2.0 will take scare of this conflicts; I am closing this issue.
