### ISSUE TITLE
Chado export does not export sequence

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1253]
I'm still on an older version (e1304103f6d45c0524d55f1e65e4149311827ec8) so not sure if this is still an issue, but as I'm working on some scripts to export data from a chado instance, I noticed that apollo was not exporting sequence data.

If it would be possible, it would be extremely helpful if Apollo could do this. This way only apollo has to be able to write to chado and I can completely control what goes into it. 

Otherwise I'll have to synchronise in sequence data to Chado and that sounds... quite unpleasant.

**Comment by nathandunn** [comment]
I think there is an ```exportAllSequences``` variable that if set to true should do what you want, but it takes forever, so it is off by default.  

@deepakunni3 does this sound accurate? 

<img width="871" alt="screen shot 2016-09-09 at 10 00 18 am" src="https://cloud.githubusercontent.com/assets/751274/18395662/43d6a34c-7674-11e6-9b8e-a2e72d68242e.png">

**Comment by erasche** [comment]
Ah, I was using the web interface for this. It would be helpful if that was exposed in the GUI.

**Comment by deepakunni3** [comment]
@erasche Due to the intense nature of exporting sequences into Chado we disabled this option by default.

This option is configurable in `Config.groovy`,
https://github.com/GMOD/Apollo/blob/master/grails-app/conf/Config.groovy#L214-L219

**Comment by deepakunni3** [comment]
As Nathan suggested, you can also override this option if you are using web-services.

**Comment by erasche** [comment]
@deepakunni3 aha, that's a new setting I hadn't seen before. Ok, great, thank you!

**Comment by deepakunni3** [comment]
np! 👍

**Comment by nathandunn** [comment]
My neither.  I’d completely forgotten that you put that there.  Thanks @deepakunni3!
