### ISSUE TITLE
Only allow the model creator to delete a model (or an admin)

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#1260]
Related to #1257: We've occasionally had problems where one curator has deleted a model that another curator has created, without informing them about it. If the original curator wants to retrieve the deleted model, we have to restore it from backups. A curator suggested to us to only allow the model creator to delete a model (or an admin). This seems like a reasonable precaution to me, although it might not be desirable for all the use cases Apollo has to cover. Would it be possible to make this an option that could be configured by the global admin? Has anyone else encountered similar problems?

**Comment by nathandunn** [comment]
I was thinking of making this a global admin option.

**Comment by nathandunn** [comment]
@monicacecilia typing here: we have not come across this case with other groups, because of that I have not prioritized this very highly thus far. This example makes us see the value in enabling this as an admin option... but still to be done in next milestone. Thanks for the report! We'll get to this asap after the upcoming release.

**Comment by nathandunn** [comment]
From @ loraine-gueguen in https://github.com/GMOD/Apollo/issues/1447#issue-201862040

> This is a need from one of my users: she would like that the annotators could not edit the annotations created by someone else, to prevent conflict.

> Another way to handle this, in my opinion, would be to inform the owner (by email or notification inside Apollo) when one of his annotation is modified. This way, it would leave the full collaborative perspective (any annotator can edit any annotation). Moreover, we can imagine that any annotator would have the opportunity to subscribe to the annotations he is interested in to receive notifications when these annotations are modified.

I think a couple of new things is the subscription to annotation edits.cc

**Comment by suryasaha** [comment]
Hi @nathandunn,

An email notification of any edits is nice but there should also be an option to prevent this, if desired. This is an important issue for us as we recently had a case where somebody modified a gene model created by another user and used it as a part of a publication without communicating with us. The price of openness :-) 

Thanks!

**Comment by nathandunn** [comment]
@suryasaha  Yes, we are definitely looking into this.   Preventing deletes from a non-owner would be pretty easy to do (yes @mpoelchau  let me know if you want a quick hack for this), however preventing a modification to an isoform would be more difficult.

**Comment by suryasaha** [comment]
Thank you for the quick response!

An email notification in case of updates will work out fine as it may be needed in cases where an expert user fixes preliminary gene models created by somebody else (with their knowledge). If the edit is undesirable, will it be possible for an Admin to recover the previous version from the DB and restore it?

**Comment by nathandunn** [comment]
@suryasaha  If the edit is undesirable, you can always revert back via "show history" or undo / redo when you right-click on a feature: 

<img width="642" alt="changeannotationhistory2" src="https://cloud.githubusercontent.com/assets/751274/23237245/5b55c7a8-f911-11e6-95d9-df25e104c944.png">

The exception to this if you delete a feature.   There is a feature request #1257 to fix this, but it will be a while until we get this.  

I think its good practice to make backups of your production database, daily if possible.  Hopefully the history option will serve most of your needs, though.

**Comment by suryasaha** [comment]
@nathandunn Thats good to know. An edit notification will alert us to these changes which can then be addressed. In our case, the annotator had curated 50+ models over 1.5 years and did not realize some models had been modified until we went back to it before final publication.

**Comment by nathandunn** [comment]
You can also look at the report changes page, which might be helpful as well (prior to publishing):

<img width="535" alt="screen shot 2017-02-23 at 9 26 22 am" src="https://cloud.githubusercontent.com/assets/751274/23270872/33d1ae60-f9aa-11e6-9cbd-548dee5c3017.png">
<img width="1352" alt="screen shot 2017-02-23 at 9 26 13 am" src="https://cloud.githubusercontent.com/assets/751274/23270873/33d830e6-f9aa-11e6-957f-6ab479f4f8fb.png">
