### ISSUE TITLE
double-clicking transcript in annotator panel focuses the jbrowse window

### ISSUE THREAD

**Issue by alpapan** [GMOD/Apollo#127]
Hello

Just a gripe that you're probably hearing a lot... it is really hard changing the co-ordinate of the exons using the current click, drag and drop function. 

One (difficult) option would be to automatically 'stick' to splice junction sites and start/stop codons, or sites supported by the 'ends' of other features (as per the red vertical bars currently visualised).

Another option would be to be allowed to go to Menu->change co-ordinate and type the actual co-ordinate.

Also the general selection of the exon end in order to activate the drag and drop is not straightforward and can be time-consuming.

At the moment I have to spent considerable time zooming out and in when I know exactly where the exon ought to be...

**Comment by nathandunn** [comment]
the idea with the 2.0 release is that you can do this directly similar to the older desktop apollo (still working on the exact UI, but you get the idea):  
![screen shot 2015-01-02 at 9 49 25 am](https://cloud.githubusercontent.com/assets/751274/5598097/bbfa405e-9264-11e4-89d1-aa96589462cd.png)

**Comment by monicacecilia** [comment]
The ability to modify the coordinates is now available on 2.0.

For now, however the panel on the right, where the coordinates are modified is not "talking" to the annotation on the UcA area. That is, although modifying the coordinates using the "Max" and "Min" fields will immediately and effectively change the coordinates of the feature in the UcA area, selecting the feature on the panel on the right does not highlight / select / mark in some form the feature on the UcA display. 

Action: connect panel with coordinate details to displayed feature so curator can easily locate the feature being modified.

**Comment by monicacecilia** [comment]
The action item in this issue has been completed. More functionality coming up in #225 
I am closing this one.
