### ISSUE TITLE
API: loadUsers throws wrong error when wrong password

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1275]
Some recent changes seem to have caused the following response whenever I try and call the API with credentials (i.e. not default cookie auth)

``` json
{"error":"Cannot cast object 'false' with class 'java.lang.Boolean' to class 'org.codehaus.groovy.grails.web.json.JSONObject'"}
```

This has temporarily disabled webapollo galaxy tools for me. It happened sometime a while back. (Sorry rebuilding images takes a while so harder to git bisect)

**Comment by nathandunn** [comment]
Shoot.  Are you running out of master? 

Nathan

**Comment by nathandunn** [comment]
@erasche  Also, what API calls were failing?  You can anything but all of them.

**Comment by nathandunn** [comment]
And that error is a bit of a read-heading . . basically is killing the authentication by returning false.   The SecurityFilters.groovy class would be issuing this.  Most likely the error is upstream in the code, however.

**Comment by erasche** [comment]
@nathandunn I've only gotten as far as loadUsers, can test some other routes in a bit.

Versions I've tried:

- f49142187db46d816a9f874984bee261389756b2
- b1743812a69cd6e771327db6a90599d0d6233dbc

Routes:

- user/loadUsers (fail)
- user/getOrganismPermissionsforUser (working)
- organism/findAllOrganisms (working)

ok, looks like loadUsers is the only bad one.

**Comment by nathandunn** [comment]
That makes me feel better (that it's the only bad one).  I'll take a look. 

Nathan

**Comment by nathandunn** [comment]
- f49142187db46d816a9f874984bee261389756b2 

is the most recent.  I'll take a look.

**Comment by nathandunn** [comment]
Using this script in f49142187db46d816a9f874984bee261389756b2 I was able to get users directly:

https://github.com/GMOD/Apollo/blob/master/scripts/load_users.sh

```
curl http://localhost:8080/apollo/user/loadUsers -i -H "Content-type: application/json" -X POST  -d '{"username": "demo@demo.com", "password": "demo"}'
```

I can add the userId and it works as expected:

```{"username": "demo@demo.com", "password": "demo","userId":12348}```


Is the webservice script you were trying to run part of this?

https://github.com/TAMU-CPT/galaxy-apollo

**Comment by erasche** [comment]
Ok, that curl request works fine (sorry, I need to do more testing with the "official" scripts before posting these...)

I'm testing against f491421 as well

Interestingly the "cannot cast object false" seems to be hiding a number of real error messages, e.g. for incorrect username/password.

I've re-tested my galaxy-apollo tools, they seem happy with f49. Not sure what I was doing wrong yesterday.

**Comment by erasche** [comment]
Sorry, re-opening (forgot policy here) and also the latent issue of hiding the real error under the failed object cast.

**Comment by nathandunn** [comment]
@erasche  Okay, I updated it so that the error is better documented for loadUsers.

**Comment by nathandunn** [comment]
I mean, I updated this bug.  I still haven't fixed the code.  Not sure why its not returning the other flags.

**Comment by nathandunn** [comment]
- [ ] add error logging for authentication failure

**Comment by monicacecilia** [comment]
👍
