### ISSUE TITLE
apollo is slow in some circumstances

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1276]
```
Webapollo config:
Version: 2.0.4
Grails version: 2.5.5
Groovy version: 2.4.4
JVM version: 1.7.0_111
```

> 5 - Are you seeing spikes in database (again using top) during this?

Yes postgres is going up to 100% CPU.

> 6 - What is your user load (i.e., is it like this when no one is on the system, or just sometimes when everyone is)?

The user load is quite low. But no matter how many people are using it. It is slow even if I’m alone to use it.

> 2 - roughly how many annotated features (genes, etc.) do you have in the organism in question? 

I guess you mean within the user-created annotation track: Between 4000 and 30 000 depending the organism.

> 7 - Also forgot to ask, how many scaffolds / sequences per organism are we looking at and what is the approximate size of these genomes? 

Between 1 and 35 000 for the most fragmented. 

Actually about the question 7) the value 35 000 is the total display in the report page (I read it as an organism).
And I forgot to mention the genome size. Actually we have only 4 big genomes (>1GB) and other are several hundreds mb.

**Comment by nathandunn** [comment]
Hopefully not related to #1277.

./tools/data/add_transcripts_from_gff3_to_annotations.pl -U localhost:8080/apollo -u demo@demo.com -p demo -o BrownRecluse -i /opt/apollo/brown_recluse/data/split_gff/sample_masked.gff  

Should add about 10K genes:  cut -f1 /opt/apollo/brown_recluse/data/split_gff/augustus_masked.gff | sort -u  | wc -l
10083

At 5K genes there was not really much of a problem.

select count(*) from feature f where f.class like '%Gene';
 count 
-------
  5584
(1 row)

**Comment by nathandunn** [comment]
Might also be worth logging directly:

Log directly:

http://stackoverflow.com/a/722236/1739366

or add logging to Apollo:

http://genomearchitect.readthedocs.io/en/stable/Configure.html?highlight=log4j#logging-configuration

```
log4j.main = {
    // log errors from dependencies
    error 'org.codehaus.groovy.grails.web.servlet',        // controllers
            'org.codehaus.groovy.grails.web.pages',          // GSP
            'org.codehaus.groovy.grails.web.sitemesh',       // layouts
            'org.codehaus.groovy.grails.web.mapping.filter', // URL mapping
            'org.codehaus.groovy.grails.web.mapping',        // URL mapping
            'org.codehaus.groovy.grails.commons',            // core / classloading
            'org.codehaus.groovy.grails.plugins',            // plugins
            'org.codehaus.groovy.grails.orm.hibernate',      // hibernate integration
            'org.springframework',
            'org.hibernate',
            'net.sf.ehcache.hibernate'


    // enable logging of our webapollo instance (uncomment debug for extensive output)
	warn 'grails.app'
//    debug 'liquibase'
//    debug 'org.bbop.apollo'

//     more find grained logging
    trace 'org.hibernate.type'
    debug ‘org.hibernate.SQL'
}
```

**Comment by nathandunn** [comment]
FYI @Juke34

**Comment by monicacecilia** [comment]
This wire went quiet about 5 days ago. Any updates on either side? 
@Juke34 ? @nathandunn ?

**Comment by nathandunn** [comment]
We've been emailing offline.   I'll report something here when I have something definitive.  In the interim I'm still loading data. 

Nathan

**Comment by monicacecilia** [comment]
Ok. I was about to open a new issue about Apollo being slow ... then found this name, but I don't know if it will turn out to be the same problem. That's why I was looking for an update. I'll start a new discussion.

**Comment by nathandunn** [comment]
148K sequences and 25 annotations (with isoforms for each).  

![screen shot 2016-10-04 at 10 37 29 am](https://cloud.githubusercontent.com/assets/751274/19085275/9d91d970-8a1e-11e6-831e-997f04b28163.png)

In the case of the Brown Recluse (loxrec), the annotations are gene only.  Times are <<  s.   For other operations it is closer to 2 seconds if multiple isoforms, but that is not really exceptional.

**Comment by nathandunn** [comment]
Master has slightly better performance than 2.0.4 as its not making as many "Save" calls.  Want to talk to other folks to see what other possibilities might be.

**Comment by nathandunn** [comment]
It is possible that NOT using websockets is causing slowness (has to repost a get), but it seems very unlikely.

**Comment by nathandunn** [comment]
![screen shot 2016-10-04 at 12 25 11 pm](https://cloud.githubusercontent.com/assets/751274/19089086/aecc038c-8a2d-11e6-930f-5848b20685ef.png)

Top 1:   50% ExonService.getSortedExons:218 . .. 211 invocations at 42 ms each

    select featureloc0_.feature_id as feature_3_23_0_, featureloc0_.id as id1_29_0_, featureloc0_.id as id1_29_1_, featureloc0_.version as version2_29_1_, featureloc0_.feature_id as feature_3_29_1_, featureloc0_.fmax as fmax4_29_1_, featureloc0_.fmin as fmin5_29_1_, featureloc0_.is_fmax_partial as is_fmax_6_29_1_, featureloc0_.is_fmin_partial as is_fmin_7_29_1_, featureloc0_.locgroup as locgroup8_29_1_, featureloc0_.phase as phase9_29_1_, featureloc0_.rank as rank10_29_1_, featureloc0_.residue_info as residue11_29_1_, featureloc0_.sequence_id as sequenc12_29_1_, featureloc0_.strand as strand13_29_1_, featureloc0_.FMAX-featureloc0_.FMIN as formula0_1_ from feature_location featureloc0_ where featureloc0_.feature_id=? 5227 24 211

Top 2: NameService.makeUniqueTranscriptName:89 (427 ms?)

    select transcript0_.name as col_0_0_ from feature transcript0_ inner join feature_location featureloc1_ on transcript0_.id=featureloc1_.feature_id inner join sequence sequence2_ on featureloc1_.sequence_id=sequence2_.id inner join organism organism3_ on sequence2_.organism_id=organism3_.id where transcript0_.class in ('org.bbop.apollo.Transcript', 'org.bbop.apollo.MiRNA', 'org.bbop.apollo.RRNA', 'org.bbop.apollo.TRNA', 'org.bbop.apollo.SnoRNA', 'org.bbop.apollo.MRNA', 'org.bbop.apollo.NcRNA', 'org.bbop.apollo.SnRNA', 'org.bbop.apollo.CustomTranscript') and organism3_.id=? and (transcript0_.name like ?) 3846 427 9

(not much to do here, this should take the longest):
Top 3:  Gene save() doGenerateTranscript (unsiprising) FeatureService:generateTranscript 246

**Comment by nathandunn** [comment]
Other notables:  generateOwnerString (FeatureService: 1586).

Get FeatureService::AllSequenceAlterationsForFeature (296) (rather significant)

Any method that gets parents or children. (it has to iterate)

**Comment by nathandunn** [comment]
Sequence Alteration code:  

    select sequenceal0_.id as id1_23_, sequenceal0_.version as version2_23_, sequenceal0_.date_created as date_cre3_23_, sequenceal0_.dbxref_id as dbxref_i4_23_, sequenceal0_.description as descript5_23_, sequenceal0_.is_analysis as is_analy6_23_, sequenceal0_.is_obsolete as is_obsol7_23_, sequenceal0_.last_updated as last_upd8_23_, sequenceal0_.md5checksum as md9_23_, sequenceal0_.name as name10_23_, sequenceal0_.sequence_length as sequenc11_23_, sequenceal0_.status_id as status_12_23_, sequenceal0_.symbol as symbol13_23_, sequenceal0_.unique_name as unique_14_23_, sequenceal0_.alteration_residue as alterat26_23_, sequenceal0_.deletion_length as deletio27_23_, sequenceal0_.class as class15_23_ from feature sequenceal0_ inner join feature_location featureloc1_ on sequenceal0_.id=featureloc1_.feature_id inner join sequence sequence2_ on featureloc1_.sequence_id=sequence2_.id where sequenceal0_.class in ('org.bbop.apollo.SequenceAlteration', 'org.bbop.apollo.Deletion', 'org.bbop.apollo.Substitution', 'org.bbop.apollo.Insertion') and sequence2_.id=? order by featureloc1_.fmin asc 2163 34 62

**Comment by nathandunn** [comment]
Solutions:

1 - parent / child calls:   use (or cache) graphs or minimize calls
2 - makeUnique names / genes: minimize calls or cache
3 - generateOwnerString ?
4 - getSortedExons: optimize or minimize calls

**Comment by nathandunn** [comment]
Multi-join when making unique names is VERY inefficient and makes no sense.   Better to see if there are any bad results first and then sort over those.

**Comment by nathandunn** [comment]
Most of the remaining optimizations have to do with aggressively denormalizing relationship between parent / child and feature locations / features.
