### ISSUE TITLE
projection: Flip entire assembled scaffold

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1278]
The idea is that you can lock the order and relative complement of an assembled scaffold. 

The idea behind this would be to have a lock in the Assemblage Detail panel, though it would not necessarily effect the other panels.   For a locked assemblage, when you did a reverse complement, you would preserve the relative order.  I guess a lock icon would be added to it and the reverse icon would be added to the top.
- ~~add lock to view~~
- [x] remove other icons
- [x] implement a flip ALL icon
- [x] flip order in addition to all orientations

- ~~implement scaffold switch when locked~~ (will be a general "flip")
- ~~wire lock to backend somehow~~ (not necessary and the front-end will do all of the work)
- ~~filter locks to other assemblages~~ (not necessary since we are marking used / vs unused)

**Comment by nathandunn** [comment]
@selewis and @monicacecilia feedback requested.  When I get to this I'll do some quick mock ups, but any input on this would be helpful.

**Comment by monicacecilia** [comment]
For what I can remember from this discussion: 

I agree that having a lock on the the order and reverse complement of a synthetic scaffold (not one originally in the assembly) should only be kept available in the 'Assemblage' panel and it should not affect the other panels. 

The lock should only be in place if the user 'enables' or 'activates' it. Not by default. 

A lock icon and a reverse complement icon seem useful.

**Comment by nathandunn** [comment]
Thanks.  I think we're all on the same page.

**Comment by nathandunn** [comment]
Forgot to flip the assemblage order (had just done the orientations).

**Comment by nathandunn** [comment]
Fixed with: 3d2d862967fbe3d970616b65aa8de8d79809072b
