### ISSUE TITLE
feature request: be nice to folks not praying at the Apple temple

### ISSUE THREAD

**Issue by alpapan** [GMOD/Apollo#128]
Hello (again)

On 
http://icebox.lbl.gov/WebApolloDemo/jbrowse

![untitled](https://cloud.githubusercontent.com/assets/608484/5591548/4dfc249a-91bb-11e4-92a1-085db976eede.png)

The Option key is an Apple phrase...

how about
from "option-click" change to "Opt/Ctrl click"
(or just not mention it all... the Help could have all the keyboard shortcuts)...

but in reality on Windows7 PCs it seems to be Alt-Control Click (which I thought was not the standard substitute for apple's 'option'). Control click is nicer

finally... Edit Annotation made me think I could edit the structural annotation, but in your case you meant provide comments and functional annotation. Having said that it would be great to edit the structural annotation on that window too (see previous comment about exons).

ok I'm done for this week ;-)
a

**Comment by nathandunn** [comment]
The apple gods were not be pleased, but all (modern) apple keyboards also have an "alt" above the word option, so I made that change.
