### ISSUE TITLE
projections: finish out editing functionality

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1282]
After #1281 (or other ones)

Include merges / splits across boundaries reversed (and not) and partials.

**Comment by deepakunni3** [comment]
Todo list:
- [ ] Get Sequence  
    - [ ] Single scaffold assemblage: Sequence header should refer to the sequence and feature coordinates (as before) 
    - [ ] Combined scaffold assemblage: Sequence header should refer to which assemblage the feature came from along with other pertinent information describing the assemblage.
- [ ] Get GFF3
    - [ ] Single scaffold assemblage: normal GFF3 export (as before)
    - [ ] Combined scaffold assemblage: 'sequence-region' in header should refer to the assemblage. The header should also include properties of the assemblage which can be used to recreate an assemblage on GFF3 import.
- [ ] 'Show in annotator panel' should open the feature in the Annotations tab
- [ ] Change annotations type should work on features that are located on any combination of assemblage.
- [ ] Split function should work as intended
- [ ] Merge function should merge two features, even if they are on different scaffolds within an assemblage
- [ ] Make intron
- [ ] Move to opposite strand
- [ ] Duplicate feature
- [ ] Set Translation Start/End
- [ ] Set Longest ORF 
- [ ] Set Read Through Stop Codon
- [ ] Set as 5' End / 3' End / Set Both Ends
- [ ] Set Downstream / Upstream Splice Donor
- [ ] Set Downstream / Upstream Splice Acceptor
- [ ] Undo / Redo / Show History
- [ ] Update `docs/TestScript.md` to account for new operations

**Comment by nathandunn** [comment]
@deepakunni3  The history stuff should have its own GH issue #1227.  

Same with #1229 (feel free to move further up, though).

I would move GetGFF3 and GetSequence to their own issue as well.

I don't think we have "Show in Annotator Panel" built yet.    Everything else looks good, though.

**Comment by deepakunni3** [comment]
@nathandunn Okay, I'll reference those issues from this list. So that we can trace back to this parent  issue.

**Comment by nathandunn** [comment]
@deepakunni3  Were all of these working in the case of reverse complement (unless referenced by another bug elsewhere)?

**Comment by deepakunni3** [comment]
@nathandunn I updated the checklist.

**Comment by nathandunn** [comment]
@deepakunni3   Thanks.  I close this in favor of any of the new bugs that were created / left over.
