### ISSUE TITLE
annotation approving and make it visible for all user

### ISSUE THREAD

**Issue by mictadlo** [GMOD/Apollo#1285]
Hi,
When user change the annotation then as administrator how could I approve and make the annotation visible for all user?

Thank you in advance.

Mic

**Comment by nathandunn** [comment]
The user would have to have some sort of login.  

I would probably just have a user group called "public-annotations" which has a "read-only" view of any organisms you wanted to share and then add any logged-in users to that group.  

If you don't want to require a login, I would export the annotation track as GFF3, and then use flat-file-to-json.pl to create a separate track and mark the organism as "public" in the organism tab.   Not dynamic, but it would publish it to all users.
