### ISSUE TITLE
documentation update: jump to next exon

### ISSUE THREAD

**Issue by alpapan** [GMOD/Apollo#129]
I think that in a previous version, we could jump to the next exon/intron junction of a gene model (Rob did it for us)

That has now disappeared and now we have to zoom out and back in again (or scroll endlessly across large intron).

It would be great to have a keyboard shortcut that can do that...

thanks
a

**Comment by nathandunn** [comment]
What version are you running?

**Comment by alpapan** [comment]
I used the public demo

**Comment by alpapan** [comment]
(no rush, for me it's 2pm on 1st Jan and I already had my new year
celebration ;-) )

**Comment by alpapan** [comment]
got it from an email. it is square brackets []. and the gene needs to be
selected.
Searching for 'shortcut' on the webapollo manual didn't show anything.
there are scattered mentions within the text for the various shortcuts


would be great to have a help cheatsheet.

**Comment by nathandunn** [comment]
The shortcut is “shift-[“ or “shift-]” after you have selected that genome (I think we are talking about the same thing).  Seems to work.

http://icebox.lbl.gov/WebApolloDemo/jbrowse/?loc=Group3.1%3A12821..21728&tracks=DNA%2CAnnotations%2COfficial%20Gene%20Set%20v3.2%2CGeneID%2COfficial%20Gene%20Set%20v1.0&highlight= <http://icebox.lbl.gov/WebApolloDemo/jbrowse/?loc=Group3.1:12821..21728&tracks=DNA,Annotations,Official%20Gene%20Set%20v3.2,GeneID,Official%20Gene%20Set%20v1.0&highlight=>

We did remove this from our help (http://icebox.lbl.gov/webapollo/docs/help.html <http://icebox.lbl.gov/webapollo/docs/help.html>) , but I think it is somewhere else.  Either way, it doesn’t have this useful tip.  

Nathan

**Comment by nathandunn** [comment]
@monicacecilia   
1 - should / do we incorporate the help here (http://icebox.lbl.gov/webapollo/docs/help.html)  . . . I can make sure it is in a drop-down if so, or if there is a more appropriate link
2 - Wherever we have this data, we should make sure to add this tip for Alexie if its not already in the user's guide.

**Comment by cmdcolin** [comment]
This is in the user guide under 4.2.2 Exon Structure Integrity. There is currently no documentation of this "inside" webapollo similar to how jbrowse has the help popup box, but that can be a separate issue i guess
