### ISSUE TITLE
Apollo is very slow when loading approx. 30 RNAseq tracks (at VectorBase)

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1291]
Dear @rwieck, @strumpfe, & @nathandunn, 

A VectorBase user (Hugh Robertson, not on GH) reported that lately he has faced severe slow downs and crashes in Apollo when trying to display ~30 RNAseq tracks at once in some of your instances. Unfortunately I forgot to take down the exact species he was working on. He did mention the slow downs seem to be pervasive.

I could not find a VB GH repo, so I am adding this in ours to make sure we can keep track of it.

**Comment by nathandunn** [comment]
- [ ] test with 30 identical RNASeq tracks

**Comment by monicacecilia** [comment]
Well, if we test it on the honey bee data we have, they would have to be thirty tracks of the same BAM data. 

Alternatively, we could ask someone at VectorBase to test with 30 different RNAseq tracks - because they seem to have at least on instance with that many! That would be a better test.

**Comment by nathandunn** [comment]
Definitely, let’s start with VB.  

Nathan

**Comment by nathandunn** [comment]
From conversation with Apollo Dev group:

5 - create an SVG track that gives the number of hits / reps (histograms for BAM readers)

6 - same as 5, but do this for the HTMLFeatures track

**Comment by monicacecilia** [comment]
- Because Apollo overwrites tracks to make them available, we plan to test showing only a "JBrowse" BAM that Apollo cannot overwrite, and make it available in the same window. 
- For every BAM track, we will have it pre-configured as the draggable one and one non-draggable. 
- @deepakunni3 will share an example with us from HGD.

**Comment by nathandunn** [comment]
The key points are:
1 - "overridePlugins" is true
2 -    "type" : "JBrowse/View/Track/Alignments2", for the Canvas track (usually this would be over-written)

```
{
   "overridePlugins" : "true",
   "storeClass" : "JBrowse/Store/SeqFeature/BAM",
   "urlTemplate" : "SRA_BAM/apis_mellifera_chromosomes_ERR413300_hisat2_aligned_08082016_sorted.bam",
   "type" : "JBrowse/View/Track/Alignments2",
   "label" : "ERR413300_canvas",
   "key" : "ERR413300 (Canvas)"
},
{
   "storeClass" : "JBrowse/Store/SeqFeature/BAM",
   "urlTemplate" : "SRA_BAM/apis_mellifera_chromosomes_ERR413301_hisat2_aligned_08082016_sorted.bam",
   "label" : "ERR413301_draggable",
   "type" : "WebApollo/View/Track/DraggableAlignments",
   "key" : "ERR413301 (Draggable)"
},
```

**Comment by nathandunn** [comment]
@monicacecilia  Can this be closed now?

**Comment by nathandunn** [comment]
FYI @rwieck, @strumpfe, https://github.com/GMOD/Apollo/issues/1291#issuecomment-252987667 should any problems with slow BAM tracks, but just providing some minor additional configuration.

**Comment by nathandunn** [comment]
If not, let us know and we can re-open.

**Comment by monicacecilia** [comment]
I'd like to wait to hear from VectorBase first - leaving open for confirmation.

**Comment by nathandunn** [comment]
@rwieck, @strumpfe  Closing for now.  Please re-open if there is more information or some actionable information.

**Comment by nathandunn** [comment]
@rwieck, @strumpfe  We added a PR into master that allows you to annotate directly from the canvas tracks.   You could probably patch this directly if you didn't want to upgrade.    

https://github.com/GMOD/Apollo/pull/1789
