### ISSUE TITLE
update AWS images and directions

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1292]
- [ ] update to ubuntu 16? 
  - [x] websocket working (include tomcat8 and possible upgrade to version 16)
- [ ] add documentation (and how to add apache / nginx) and how to start tomcat specifically
  - [ ] document directory /opt/tomcat/webapps 
  - [ ] document commands (sudo initctl stop tomcat)
  - [ ] add apache or nginx with proxy support
- [x] remove honeybee data (we do not need to do this)
- [ ] remove tons of extra files including laptop pem files, etc. 
  - [ ] google what else should be done

**Comment by nathandunn** [comment]
upgrading to tomcat8 seems to fix everything

**Comment by nathandunn** [comment]
looks like apache / nginx is not enabled, but the XHR fallback is still working fine

**Comment by monicacecilia** [comment]
uh-oh... I was just going to send out the message including the Apache / NGIX instructions from the one you sent to the list. ... so, non plus? XHR instead?

**Comment by nathandunn** [comment]
Let me check on those images . . . one sec.

Nathan

**Comment by nathandunn** [comment]
Yeah, the apache / nginx instructions are good.   I don’t install those as it always seems like groups have their own preferences, but maybe we can make these something different.   You told him to go to 8080, which is correct, and I think the rest of the instructions were spot on so longs he remembers to open the 8080 security port when creating the instance.   

The XHR (long-polling as of old) should and does work perfectly fine (was great to see it fall back so elegantly I didn’t even notice), however if it fails, web sockets is usually a bit more robust when going through a firewall. 

I’ll update this as I’m able, but I don’t think that anything is on fire yet.  

Nathan

**Comment by nathandunn** [comment]
Following these instructions because you have to do it manually:  https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-8-on-ubuntu-14-04

**Comment by monicacecilia** [comment]
Thank you!

**Comment by nathandunn** [comment]
This is done
