### ISSUE TITLE
Can't proxy to a subpath

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#130]
If you setup an apache proxy such as

ProxyPass /subpath tomcat:8080/
ProxyPassReverse /subpath tomcat:8080/

And then tomcat:8080/WebApollo is a deployed instance, then if you access it, e.g. http://mysite/subpath/WebApollo/sequences:

Then the login button tries to fetch the following with AJAX

POST http://mysite/subpath/Login?operation=login

Which fails -- it should be requesting http://mysite/subpath/WebApollo/Login?operation=login

This misses the fact that WebApollo is in the URL. There are several odd things going on inside the login code that enables this to happen, but some of it is sensible in order to allow the same login panel to be used from both jsps and the jbrowse.

**Comment by nathandunn** [comment]
@cmdcolin   Is this in 1.0.3?

**Comment by cmdcolin** [comment]
Yep forgot to mention that. I actually ported all our instances to 1.0.3 today. it was quite nice actually :)

**Comment by nathandunn** [comment]
@cmdcolin  That is great.   Do you want to take a stab at this one?

**Comment by nathandunn** [comment]
So in login.html . . . 

var pathname = location.pathname;
context = /^\/([^\/]+)\//.exec(pathname)[1];
. . .and is posted via:
url: "/" + context + "/Login?operation=login",

Have to fix this for *each* login strategy.  Possibly changing to jsp might make more sense (and more accurately grab the context) .

**Comment by nathandunn** [comment]
Actually I don't think that the login property is the problem.  1) the subpath between the tomcat and apache proxies must match.  pathA and pathB must be identical (currently).   2) The login post appears to be fine.   However, when a "post" is sent, the session is not authenticated when it comes back.  It knows how to handle bad passwords, etc.

ProxyPass /pathA tomcat:8080/pathB
ProxyPassReverse /pathA tomcat:8080/pathB

**Comment by nathandunn** [comment]
This is correct as it is mapped to the Web Apollo context on port 8080.  
"http://mysite/subpath/Login?operation=login" 

This should fails.
"Which fails -- it should be requesting http://mysite/subpath/WebApollo/Login?operation=login"

**Comment by nathandunn** [comment]
The problem is that even though the login is successfully the username is not being set within the session.  Trying to fix that here with this:

https://rvdb.wordpress.com/2012/04/26/reverse-proxying-tomcat-webapps-behind-apache/

**Comment by nathandunn** [comment]
@cmdcolin   Having done this often using both using Shiro and Spring in Grails, I think that the easiest answer is to move this to 2.0 where this should be taken care of automatically.  

In the interim, the Apache setting that I got to work is the following (note the reverse cook path):

ProxyRequests     off
<Location /apollo-proxy/ >
    ProxyHTMLEnable On
    ProxyPass  http://localhost:8080/apollo/
    ProxyPassReverse  http://localhost:8080/apollo/
    ProxyPassReverseCookiePath  / http://localhost:8080/apollo/
</Location>

**Comment by nathandunn** [comment]
@cmdcolin  I take that back . . . it fails for jbrowse / annotation portion . . . 

So, my suggestion is that you pick the same subpath but use a different virtual name for the host (if you need that).

**Comment by erasche** [comment]
As mentioned in #200, the regex for capturing context/path has some small issues whereby Apollo can't be deployed at tomcat's root.

```javascript
$(document).ready(function() {
  var pathname = location.pathname;
  context = /^\/([^\/]+)\//.exec(pathname)[1];
  //snip
});
```

**Comment by nathandunn** [comment]
@cmdcolin   Can you test for 2.0 when you have a chance?

**Comment by nathandunn** [comment]
tested it on a locally deployed tomcat and works

**Comment by cmdcolin** [comment]
neither of these configs works for me


ProxyPass /subpath http://localhost:8080
ProxyPassReverse /subpath http://localhost:8080


ProxyPass /subpath2/apollo http://localhost:8080/apollo
ProxyPassReverse /subpath2/apollo http://localhost:8080/apollo


Regular proxying without a subpath does work this is low priority


ProxyPass /apollo http://localhost:8080/apollo
ProxyPassReverse /apollo http://localhost:8080/apollo

**Comment by nathandunn** [comment]
This sort of works:

<Location /app/apollo1 >
    ProxyHTMLEnable On
    ProxyPass http://localhost:8080/apollo
    ProxyPassReverse http://localhost:8080/apollo
    ProxyPassReverseCookiePath  / http://localhost:8080/apollo
</Location>

However, the proxied subpath is using the /apollo/  

However, I'm getting FileNot Found . . . 

I think the key is to use GWT.GWT.getHostPageBaseURL() instead of using the passed in rootUrl

**Comment by nathandunn** [comment]
This is a semi-important fix and easy fix.

**Comment by nathandunn** [comment]
String url = GWT.getModuleBaseURL().replace("annotator/","") + "user/checkLogin";

. . but we have to make sure everything is setup like this.   Easiest solution would be to make sure that everything goes through RestService .

**Comment by nathandunn** [comment]
Some example fixes:

 private void loginUser() {
-        String url = rootUrl + "/user/checkLogin";
+        String url = GWT.getModuleBaseURL().replace("annotator/","") + "user/checkLogin";
+        Window.alert("user login: "+url);
         RequestBuilder builder = new RequestBuilder(RequestBuilder.GET, URL.encode(url));
         builder.setHeader("Content-type", "application/x-www-form-urlencoded");
         RequestCallback requestCallback = new RequestCallback() {
diff --git a/src/gwt/org/bbop/apollo/gwt/client/rest/GroupRestService.java b/s


--- a/src/gwt/org/bbop/apollo/gwt/client/rest/RestService.java
+++ b/src/gwt/org/bbop/apollo/gwt/client/rest/RestService.java
@@ -36,11 +36,15 @@ public class RestService {
     }
 
     public static void sendRequest(RequestCallback requestCallback,String url,String data){
-        Dictionary dictionary = Dictionary.getDictionary("Options");
-        String rootUrl = dictionary.get("rootUrl");
-        if(!url.startsWith(rootUrl)){
-            url = rootUrl+url;
-        }
+        url = GWT.getHostPageBaseURL() + url.substring(1) ;

**Comment by nathandunn** [comment]
Related to #219

**Comment by nathandunn** [comment]
@cmdcolin   When you have a chance you can take a look at this . .  the only issue I'm getting is that assets isn't using the reverse proxy properly  .  . .  anyway, you can let me know (when you have a chance) if it works for you properly.

**Comment by cmdcolin** [comment]
This one was a little tricky but it appears that the correct Proxy settings that are needed to forward the session cookies correctly are as follows:


    ProxyPass  /testing http://localhost:8080
    ProxyPassReverse  /testing http://localhost:8080
    ProxyPassReverseCookiePath / /testing


After doing this, I can access apps like http://localhost/testing/apollo/ and logins work

The ProxyPassReverseCookiePath is very importatn for this scenario in order to rewrite the session cookie properly so I might add this to the docs.

As you mentioned, some assets are not loaded under this config but it doesn't seem too consequential
