### ISSUE TITLE
The longest possible ORF must be calculated for genomic fragments 

### ISSUE THREAD

**Issue by selewis** [GMOD/Apollo#1302]
If either the 5' or 3' end of the transcripts is missing from the contig the entirety of the gene may not be present. Nathan and I checked the code and it is simply wrong. Nathan is putting the older (correct) version into gist, but here is the snippet below. Should be an easy fix. Needs flags if either 5' end or 3' end is missing so that the UI can indicate the fragmentary nature to the user.

(p.s. missing 3' is set deeper into the subroutines that follow after setting optimal 5' end)

    String longest_peptide = "";
    int best_start_index = -1;
    logger.debug("setTranslationStartAtFirstCodon: the_mRNA.length() = " + the_mRNA.length());

    // to handle very short features (e.g. insertions)
    // these shouldn't be translated, but in case they are...
    if (the_mRNA.length() > 3) {
      // Find the first start codon
      int start_index = the_mRNA.indexOf(standard_start_codon);
      while (start_index >= 0) {
        String aa = getTrimmedAA(get_ORF(the_mRNA, start_index, -1), 
                                 start_index);
        if (aa.length() > longest_peptide.length()) {
          longest_peptide = aa;
          best_start_index = start_index;
        }
        start_index = the_mRNA.indexOf(standard_start_codon, start_index + 1);
      }
      /* just in case the 5 prime end is missing see if
         a longer translation can be obtained without looking
         for the ATG */
      start_index = 0;
      while (start_index < 3) {
        String orf = get_ORF(the_mRNA, start_index, -1);
        String aa = getTrimmedAA(orf, start_index);
        if (aa.length() > longest_peptide.length()) {
          setMissing5prime(true);
          longest_peptide = aa;
          best_start_index = start_index;
        }
        start_index++;
      }
    }
    
    if (best_start_index >= 0) {
      boolean setEnd = true;
      initTranslationStart (getGenomicPosition(best_start_index + 1), setEnd);
    } else {
      translation_start = 0;
      setMissing5prime(true);
      setMissing3prime(true);
    }

**Comment by nathandunn** [comment]
https://gist.github.com/nathandunn/abc134d5756d2c9183c6104c534b4dcc

https://gist.github.com/nathandunn/246de8315fea22217b3d06e98a435d47

**Comment by selewis** [comment]
Also please ensure that each time (i.e. both loops) that all three reading frames are being checked.

**Comment by nathandunn** [comment]
I think when we'd talked earlier, it ended up being a test suite of 6 total.  Three reading-frames with start codons, three reading-frames without start codons (but with stops?), and three without either, and three with starts and no stops?  (12 total).   

I am unsure if the calculation of the coding takes care of this (probably  not).

**Comment by nathandunn** [comment]
@selewis  Added this to help in creating tests for this issue:

https://gist.github.com/nathandunn/3cc00bdae00635b4733e7b4566610489

**Comment by nathandunn** [comment]
Closed by #1307 but tagged for review for 2.0.5.
