### ISSUE TITLE
projection: add boundary track

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1304]
from #1263 (I think) and for #1301.  

Copy LegendTrack, but pick off values from the renderFeature only, and use the RefSeq itself instead of the XHR input.

**Comment by nathandunn** [comment]
Done sort of.  Will have to continue to refine this.

**Comment by monicacecilia** [comment]
#1263 is closed but #1301 is still open; is it _done_ done or _sort of_ done and still in progress for the latter issue?

**Comment by nathandunn** [comment]
@monicacecilia  It was mostly done (there was one checkbox left).  I moved the last issue to #1268.  For the most-part you can ignore most issues with the 2.1.0-alpha as its mostly internal tracking.
