### ISSUE TITLE
Export of introns only

### ISSUE THREAD

**Issue by selewis** [GMOD/Apollo#131]
Based on the recent article in Science where the bird genome evolutionary tree people ended up using introns to determine the phylogenetic trees.

All the introns for the ref. sequence. Named by transcript + indication it's an intron, and then sequentially numbered 5' to 3'

Might be useful to have this for exons too.

**Comment by nathandunn** [comment]
should work like the "get sequence" function for individual features

**Comment by nathandunn** [comment]
@deepakunni3   . . . if you don't think that this is reasonable to get this done by this week, move it to 2.0.1 (May) or 2.1 (Summer)

**Comment by nathandunn** [comment]
@deepakunni3  You're still welcome to do this, just wanted to plan out the 2.0.0 release, though.

**Comment by deepakunni3** [comment]
@nathandunn  I can start on this after I finish the export feature.

**Comment by nathandunn** [comment]
Okay.  If you think that it will take more than a day (roughly), then leave it for 2.1.    

I have some other stuff for the 2.0.0 release for you to do, as well.  

Thanks!

Nathan

**Comment by selewis** [comment]
Right, low priority.

Reverse complement - now that's a high priority.
