### ISSUE TITLE
Feature request: Framework for annotation 'bots' that can assist human curators

### ISSUE THREAD

**Issue by robsyme** [GMOD/Apollo#1315]
It would be great if an API-consuming script was able to "watch" human edits via a websocket connection. This would open up the possibility for users to write 'bots' that add helpful information to in-progress annotation edits, giving a really tight feedback loop. The sort of things I'm thinking of are:

1) Run the protein translation of every new annotation proposal through something like Interproscan so that the user can see if their proposal contains new conserved domains (which may increase their confidence in the edit).
2) Run the protein translation through some (quick) computational pipeline. Our group is interested in fungal effector prediction, so I'd like to run each annotation through something like [EffectorP](https://www.ncbi.nlm.nih.gov/pubmed/26680733) or similar to assign a score to each transcript.

**Comment by nathandunn** [comment]
@robsyme   I really like this idea.  It wouldn't too horrible to publish events as they come through.    Connecting and authentication are a bit more tricky, but not too bad.   We use SockJS + STOMP to return heavily stringified JSON with our clients. 

What client were you thinking to connect to (what client lib would you use)?    

Conversely you could periodically poll / update annotations to issue a report and write back metadata.

**Comment by robsyme** [comment]
Great.

STOMP seems like a fine protocol to expose, and wouldn't require a huge amount from somebody looking to listen in.

I was hoping that the language of the client wouldn't matter too much. If the realtime user events were exposed, then the 'helper bot' could just make [Apollo API](http://chopsticks.lbl.gov/apollo_web/web_service_api.html) calls to add in new annotations when it was ready. Ideally, it would be as easy as possible for people to write these helper bots to encourage new ideas.

I suppose a poll/update would work ok via the existing API. I should probably just start there. Running interpro scans, for example, would be a much larger component of the total wait time than any polling interval.

**Comment by nathandunn** [comment]
I was wondering about the timing.   Let me know if you need a new function to support this (e.g., getFeaturesNewerThan .  .  ).

**Comment by nathandunn** [comment]
It would return unique_name of transcripts (a hash) or JSON.

**Comment by robsyme** [comment]
That would certainly make things a lot easier...

**Comment by nathandunn** [comment]
@robsyme  I created a PR here:  https://github.com/GMOD/Apollo/pull/1316

Feel free to fork / edit / make recommendations, but the general idea is you can run a script [for example](https://github.com/nathandunn/Apollo/blob/add_last_changed_call_1315/docs/web_services/examples/groovy/get_new_features.groovy) and it will return the "current" JSON representation, but it would be easy to change.  

I can merge this into master or keep it in the branch for you to comment / edit.  Let me know.

**Comment by nathandunn** [comment]
@robsyme  I pull the PR into master.

**Comment by monicacecilia** [comment]
This is done. Re-open if you find any issues. Thanks!
