### ISSUE TITLE
add better documentation for AWS / docker in Readme.md

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1317]
- [x] add a "supported platforms" section in the Readme.md with local, production, AWS, galaxy, and  docker (and hopefuly dockerstore.org)
- [x] add really specific instructions for npm on ubuntu 14 and 16 
- [x] and a minimum npm check to install script

**Comment by nathandunn** [comment]
- [ ] add a "supported platforms" section in the Readme.md with local, production, AWS, docker (and hopefuly dockerstore.org)

**Comment by nathandunn** [comment]
The reasons are:

1 - some user's just want to try it out with their own data (as opposed to the demo)
2 - some user's have difficult doing the full configuration locally with postgresql + tomcat
3 - some user's have to deal with a restricted IT infrastructure and tools like AWS and docker get around that.
4 - integration within a workflow is made a lot easier if already dockerized
5 - we should advertise every workflow environment we are in

**Comment by erasche** [comment]
@nathandunn I could build an all-in-one container for apollo with postgres included, if that'd be useful.

**Comment by nathandunn** [comment]
@erasche   Would it be any different than this?

https://github.com/GMOD/docker-apollo

**Comment by erasche** [comment]
@nathandunn yeah, we can bake postgres into the container. It would be a "please don't run this in prod, but if you want to test...", you could launch it with a single docker run command, would be usable in kitematic which people seem to like, etc.

**Comment by nathandunn** [comment]
@erasche  In that case, yes, that would be awesome.   So, would they use the docker-compose script for a production environment and the single run docker command above for evaluation?

**Comment by nathandunn** [comment]
@erasche  or would you not recommend either for production?

**Comment by erasche** [comment]
@nathandunn essentially.

The all-in-one is great for testing but it isn't advisable to put in prod, harder to deal with down the road if you realise you need to scale one or another component, etc.

The docker-compose is great as documentation of how to link things up, but most people don't use docker compose in prod, they use another system (e.g. kubernetes, rancher, etc.) However the docker-compose is great for development.

**Comment by erasche** [comment]
I'll ping you when I get the image built, shouldn't be too hard to do.

**Comment by nathandunn** [comment]
@erasche   I see.  Thanks for the explanation.

**Comment by nathandunn** [comment]
Noticed that I also had this note:  

<img width="557" alt="screen shot 2016-11-01 at 2 36 20 pm" src="https://cloud.githubusercontent.com/assets/751274/19908468/b7c8d05e-a040-11e6-80c8-9409f287b89a.png">

**Comment by nathandunn** [comment]
@erasche Any progress on this?  No worries if not.   Creating a separate PR would work as well.

**Comment by erasche** [comment]
Will work on it this weekend, sorry, been a busy week on other work
projects.

fre. 4. nov. 2016 kl. 14.55 skrev Nathan Dunn <notifications@github.com>:

**Comment by nathandunn** [comment]
No worries.  I appreciate you doing this.

**Comment by nathandunn** [comment]
Closed by #1321
