### ISSUE TITLE
Link-outs for features not working

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#132]
One of our project coordinators generated and configured tracks for their browser using the linkTemplate option to handle linking out to their external resources. See (https://github.com/GMOD/jbrowse/issues/120) for more information.  This worked for them when it was a JBrowse-only instance, but not once we migrated their data and configuration to a Web Apollo instance.

The left click behavior needs to be overwritten to allow the Web Apollo click to select functionality for features. While necessary, this behavior does not seem to be documented, and persists when a user is not logged in for annotation.

The only workaround I see is to adjust trackList.json so the links out are part of a new right-click menu option. In the future, would be possible to re-engineer the linkTemplate tag to auto-generate a generic "link out" right click menu option? Or should linkTemplate be considered deprecated in Web Apollo?

I could not find a section in the manuals that would hold these types of caveats.  Is this something we could add ( a section for known issues between JBrowse and Web Apollo)?

**Comment by nathandunn** [comment]
@cmdcolin   Colin, is this something you know about directly?  If not, I'll take a look (just assign it back to me).

**Comment by cmdcolin** [comment]
It's true that the click handler is hijacked by webapollo making linkTemplate unusable. It is also true that the click event is hijacked whether or not the user is logged in or not. 

I would probably use the right-click menu (i.e. menuTemplate) instead. You could also use the onClick function which does work for adding a click event.

**Comment by childers** [comment]
That's the same conclusion I had come to in terms of bringing this functionality back for them.  

It would be nice if there was a graceful transition of functionality so features aren't totally lost, but I imagine there are too many potential gotchas for that to be feasible.

**Comment by cmdcolin** [comment]
I started a section in the configuration guide for this. For this particular instance, I would avoid the click actions, so I think just documenting it is better than the graceful degradation into a right-click option. Also, linkTemplate isn't documented in jbrowse either...so that needs updating as well

**Comment by nathandunn** [comment]
@cmdcolin  @childers   IS there a JBrowse bug for documenting linkTemplate?
