### ISSUE TITLE
Mixed Content error when adding GO terms on an https instance

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#133]
Adding GO annotations in the information editor is failing on our instances due to a mixed content error.  Our instances are all running over ssl, and the call back to the GO lookup resource (golr.berkeleybop.org) is running over http.  I tried navigating to is as an https link, https://golr.berkeleybop.org and it timed out.  Is that server not accepting ssl requests at all?

![mixed_content_go-terms](https://cloud.githubusercontent.com/assets/421248/5617066/9e8fd738-94d8-11e4-97dc-e3374affedbc.png)

**Comment by nathandunn** [comment]
Chris, 

I think long-term we’ll want to allow GOLR over https or have it run locally.  

In the interim, I think you can allow mixed content, so it should work:

http://247support.custhelp.com/app/answers/detail/a_id/11736/~/chrome-and-firefox%3A-blank-page-or-blocked-mixed-content <http://247support.custhelp.com/app/answers/detail/a_id/11736/~/chrome-and-firefox:-blank-page-or-blocked-mixed-content>

Nathan

**Comment by childers** [comment]
Nathan,
I had thought about that first, but was hoping for a solution that didn't involve coordinating each user to help them relax their security settings.  
Chris

**Comment by nathandunn** [comment]
I sent a message to our GOLR providers here at BBOP.   If they can provide an https service, we can link to that instead.   I’m hopeful that we can do that.

Nathan

**Comment by childers** [comment]
Great, thanks!

**Comment by nathandunn** [comment]
@selewis  @monicacecilia   Note: I asked GBOL group about adding https support so that we don't get the mixed-content error.

**Comment by nathandunn** [comment]
related to #148 . . . no available yet

**Comment by cmdcolin** [comment]
I had the idea that Apollo could proxy requests to the GOLR server to avoid this issue

**Comment by nathandunn** [comment]
That's not a bad idea.  @childers  If this is a show-stopper, we can do *probably* do this.   Not a great solution, but a sufficient work-around.

**Comment by childers** [comment]
We had the idea of a local proxy to the GOLR resources too.  I don't mean
to be dense, but when you mention proxy requests through Apollo, do you
mean through the service locally, through an additional proxy on our side,
or through your servers at the LBL?

**Comment by nathandunn** [comment]
I *think* the idea is that instead of querying remotely to a remote server on the client that instead you just query locally using the current protocol and the server connects to the http server.   It will be a bit slower (probably twice), but would work. 

Nathan

**Comment by nathandunn** [comment]
This is fixed as part of a proxy fix in 2.0.1.
