### ISSUE TITLE
showing annotator panel with addStore duplicates "addStore" in the URL

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1330]

**Comment by nathandunn** [comment]
This loads correctly (AFAIK).  

http://localhost:8080/apollo/Honeybee/jbrowse/?loc=Group1.1%3A1..185600&addStores=%7B%22url%22%3A%7B%22type%22%3A%22JBrowse%2FStore%2FSeqFeature%2FGFF3%22%2C%22urlTemplate%22%3A%22https%3A%2F%2Fgmod-mycorp.bigcomp.gov%2Fwebapp%2Fmedia%2Fblast%2Ftask%2F9b2ef899fa1042b081c37190d1be07f1%2FAgla_Btl03082013.genome_new_ids.fa.gff%22%7D%7D&addTracks=%5B%7B%22label%22%3A%22BLAST%2B%20Results%22%2C%22category%22%3A%220.%20Reference%20Assembly%22%2C%22type%22%3A%22WebApollo%2FView%2FTrack%2FDraggableBLASTFeatures%22%2C%22store%22%3A%22url%22%2C%22style%22%3A%7B%22renderClassName%22%3A%22gray-center-10pct%22%2C%22subfeatureClasses%22%3A%7B%22match_part%22%3A%22blast-match_part%22%7D%7D%7D%5D&tracks=DNA%2CAnnotations%2CBLAST%2B%20Results&highlight=

When we login we get the following (which loads correctly):

http://localhost:8080/apollo/583104200705403240675545570/jbrowse/index.html?loc=Group1.1%3A1..185600&highlight=&addTracks=%5B%7B%22label%22%3A%22BLAST%2B%20Results%22%2C%22category%22%3A%220.%20Reference%20Assembly%22%2C%22type%22%3A%22WebApollo%2FView%2FTrack%2FDraggableBLASTFeatures%22%2C%22store%22%3A%22url%22%2C%22style%22%3A%7B%22renderClassName%22%3A%22gray-center-10pct%22%2C%22subfeatureClasses%22%3A%7B%22match_part%22%3A%22blast-match_part%22%7D%7D%7D%5D&addStores%3D%7B%22url%22%3A%7B%22type%22%3A%22JBrowse%2FStore%2FSeqFeature%2FGFF3%22%2C%22urlTemplate%22%3A%22https%3A%2F%2Fgmod-mycorp.bigcomp.gov%2Fwebapp%2Fmedia%2Fblast%2Ftask%2F9b2ef899fa1042b081c37190d1be07f1%2FAgla_Btl03082013.genome_new_ids.fa.gff%22%7D%7D=&tracks=DNA%2CAnnotations%2CBLAST%2B%20Results


When we click on "Annotator Panel" we get the following, which duplicates addStores (perfectly):

http://localhost:8080/apollo/annotator/index?clientToken=7948544358522114358495&highlight=&addStores={%22url%22:{%22type%22:%22JBrowse/Store/SeqFeature/GFF3%22,%22urlTemplate%22:%22https://gmod-mycorp.bigcomp.gov/webapp/media/blast/task/9b2ef899fa1042b081c37190d1be07f1/Agla_Btl03082013.genome_new_ids.fa.gff%22}}=&addStores={%22url%22:{%22type%22:%22JBrowse/Store/SeqFeature/GFF3%22,%22urlTemplate%22:%22https://gmod-dev=[nal.bigcomp.gov/webapp/media/blast/task/9b2ef899fa1042b081c37190d1be07f1/Agla_Btl03082013.genome_new_ids.fa.gff%22}}:,%20nal:[bigcomp.gov/webapp/media/blast/task/9b2ef899fa1042b081c37190d1be07f1/Agla_Btl03082013.genome_new_ids.fa.gff%22}}:,%20bigcomp:[gov/webapp/media/blast/task/9b2ef899fa1042b081c37190d1be07f1/Agla_Btl03082013.genome_new_ids.fa.gff%22}}:,%20gov/webapp/media/blast/task/9b2ef899fa1042b081c37190d1be07f1/Agla_Btl03082013:[genome_new_ids.fa.gff%22}}:,%20genome_new_ids:[fa.gff%22}}:,%20fa:[gff%22}}:]]]]]]&addTracks=[{%22label%22:%22BLAST+%20Results%22,%22category%22:%220.%20Reference%20Assembly%22,%22type%22:%22WebApollo/View/Track/DraggableBLASTFeatures%22,%22store%22:%22url%22,%22style%22:{%22renderClassName%22:%22gray-center-10pct%22,%22subfeatureClasses%22:{%22match_part%22:%22blast-match_part%22}}}]&tracks=DNA,Annotations,BLAST+%20Results

**Comment by nathandunn** [comment]
So, a couple problems . . mostly because we have two addStores it tries to combine components in arrays.  This also leads to inconsistent encoding.  The encoding that comes into loadLink is fine.   The combined encoding is incorrect.

**Comment by nathandunn** [comment]
@childers  Do you want to test this latest push?

**Comment by nathandunn** [comment]
We can re-open it if it continues to cause problems.

**Comment by childers** [comment]
I'll pull down this code and check it out

**Comment by childers** [comment]
FYI one new error when running clean-all:
```shell
./apollo clean-all
javac 1.8.0_112 found
javac installed
| Resolving Dependencies. Please wait...
final JBrowse settings [git:[url:https://github.com/gmod/jbrowse, tag:1.12.2-apollo, alwaysPull:false, alwaysRecheck:false], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
final plugins [WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]
Copying apollo plugin
handling jbrowse release [git:[url:https://github.com/gmod/jbrowse, tag:1.12.2-apollo, alwaysPull:false, alwaysRecheck:false], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
handling jbrowse [git:[url:https://github.com/gmod/jbrowse, tag:1.12.2-apollo, alwaysPull:false, alwaysRecheck:false], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]

CONFIGURE SUCCESSFUL

Total time: 6.01 secs
| Error Error initializing classpath: No builders are available to build a model of type 'org.grails.gradle.plugin.model.GrailsClasspath'. (Use --stacktrace to see the full trace)
final JBrowse settings [git:[url:https://github.com/gmod/jbrowse, tag:1.12.2-apollo, alwaysPull:false, alwaysRecheck:false], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
final plugins [WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]
Copying apollo plugin
handling jbrowse release [git:[url:https://github.com/gmod/jbrowse, tag:1.12.2-apollo, alwaysPull:false, alwaysRecheck:false], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
handling jbrowse [git:[url:https://github.com/gmod/jbrowse, tag:1.12.2-apollo, alwaysPull:false, alwaysRecheck:false], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
:cleanAll

BUILD SUCCESSFUL

Total time: 1.488 secs

```

**Comment by nathandunn** [comment]
Try removing grade unless you use it elsewhere.  It will download the correct version.  

Nathan

**Comment by nathandunn** [comment]
But I'll test it with gradle 3.1 as well and put in a separate fix for that. 

Nathan

**Comment by childers** [comment]
same error?
```shell
Total time: 4.663 secs
| Error Error initializing classpath: No builders are available to build a model of type 'org.grails.gradle.plugin.model.GrailsClasspath'. (Use --stacktrace to see the full trace)
final JBrowse settings [git:[url:https://github.com/gmod/jbrowse, tag:1.12.2-apollo, alwaysPull:false, alwaysRecheck:false], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
final plugins [WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]
Copying apollo plugin
handling jbrowse release [git:[url:https://github.com/gmod/jbrowse, tag:1.12.2-apollo, alwaysPull:false, alwaysRecheck:false], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
handling jbrowse [git:[url:https://github.com/gmod/jbrowse, tag:1.12.2-apollo, alwaysPull:false, alwaysRecheck:false], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
:cleanAll

BUILD SUCCESSFUL

Total time: 3.693 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.11/userguide/gradle_daemon.html
C2QM90EBFTPM:wa2_daily cchilders$ gradle -version
-bash: /usr/local/bin/gradle: No such file or directory```

**Comment by childers** [comment]
```shell
BUILD SUCCESSFUL

Total time: 5.411 secs
| Error Error initializing classpath: No builders are available to build a model of type 'org.grails.gradle.plugin.model.GrailsClasspath'. (Use --stacktrace to see the full trace)
***************************************
NOTE: Please set the memory for your servlet container (tomcat, jetty, etc.) or Apollo may not start correctly: http://genomearchitect.readthedocs.io/en/latest/Troubleshooting/#tomcat-memory
***************************************
```

**Comment by childers** [comment]
Looks like that fixed the issue and it is building now.

**Comment by nathandunn** [comment]
I installed gradle 3.1 using sdkman and it worked fine.  Must have been a weird gradle install?!?

**Comment by childers** [comment]
Run into a java version error after updating Java to 1.8 


```shell
:copy-resources
:javac
javac: invalid target release: 1.8
Usage: javac <options> <source files>
use -help for a list of possible options
:javac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':javac'.
> Compile failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 27.623 secs
***************************************
NOTE: Please set the memory for your servlet container (tomcat, jetty, etc.) or Apollo may not start correctly: http://genomearchitect.readthedocs.io/en/latest/Troubleshooting/#tomcat-memory
***************************************
$ java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
 $ javac -version
javac 1.8.0_112

```

**Comment by nathandunn** [comment]
Note for other users.  Javac was specified incorrectly.  In the bash profile shoudl be:

JAVA_HOME=/usr/jvm/openjdk8_011.2/

or something like that.   And confirm that it is the same version by typing javac -version and java -version.

**Comment by childers** [comment]
@nathandunn helped me figure out the configuration issued on this. Many thanks!
