### ISSUE TITLE
2.0.5 finalization

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1338]
- ~~[update Docker images](https://github.com/GMOD/docker-apollo)~~
  - ~~tag and push to docker-hub~~
  - ~~create a release on docker-apollo~~
- ~~update AWS images (and to use Ubuntu 16 + tomcat8)~~
- [x] review all 2.0.5 tickets
- [x] update JBrowse version for a specific commit / 1.12.2-apollo2.0.5? 
- [x] update Changelog for closed 2.0.5 tickets
- [x] review doc for version numbers
- [x] tag 
- [x] update icebox servers
- [x] update readthedocs to this stable version
- [x] announce
- [x] added /updated zenodo release: https://zenodo.org/record/198778#.WEr6zsMrJhF

**Comment by monicacecilia** [comment]
@deepakunni3 or @nathandunn please be sure to test #1302 thoroughly before we close this issue.

**Comment by nathandunn** [comment]
Moved AWS and Docker stuff to my trello board.  Fin
