### ISSUE TITLE
server reporting option

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1339]
calls to a home server to report 

- version,
- IP (geo-location)
- a unique server ID 
- server-type?
- possibly volume / usage

report at semi-regular intervals (daily if used). 

Can be configured to be turned off, as well, but default should be one.

**Comment by nathandunn** [comment]
FYI @kltm

**Comment by kltm** [comment]
Note #194 .

**Comment by nathandunn** [comment]
Dupe of #194.
