### ISSUE TITLE
invalidate user if too many attempts

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#134]

**Comment by erasche** [comment]
I may be poking my nose into things, but has something like [Apache Shiro](http://shiro.apache.org/) been considered for this, since they have *lots* of auth features?

**Comment by erasche** [comment]
Edit: Ah, I see this now in #115

**Comment by nathandunn** [comment]
Eric, 

The 2.0 roadmap contains a lot of this stuff.  We are using Shiro over grails for authentication.  I’ve had pretty good luck with it thus far. 

Nathan
