### ISSUE TITLE
annotator tab ui improvements

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1343]
- [x] double-click should take you to annotation
- [x] should not switch back to "detail" tab when going between gene and transcript "coding" tab 
- [x] clicking on gene should not open-close, but should show detail.  Add other icon for opening / closing

**Comment by nathandunn** [comment]
double-click opens and closes a gene / pseudogene. . double-click navigates for a transcript

**Comment by monicacecilia** [comment]
#1357 shows this still needs work. -- leaving this closed in favor of that.
