### ISSUE TITLE
Character decoding fails => password logged in plaintext

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1355]
on f49142187db46d816a9f874984bee261389756b2

I saw this whilst scrolling through the logs:

```
12/2/2016 12:19:46 AM02-Dec-2016 00:19:46.462 INFO [http-apr-8080-exec-5]
org.apache.tomcat.util.http.Parameters.processParameters Character decoding failed.
 Parameter [{"operation":"login", "username":"bob@bob.com", 
"password":"THIS_WAS_IN_CLEAR_TEXT", "rememberMe":false}] 
with value [] has been ignored. Note that the name and value quoted here may be 
corrupted due to the failed decoding. Use debug level logging to see the original,
 non-corrupted values.
```

Not sure this is still an issue, but wanted to report just in case. Also, not sure how to repro I'm afraid.

**Comment by nathandunn** [comment]
It is still an issue, I think.  Is this via REST services or just regular operations?   Either way, we don't want these in the logs.  Thanks for reporting.

**Comment by erasche** [comment]
This was via a regular browser based login.

**Comment by nathandunn** [comment]
Looking more into it, I don't know if there is much to do, other than fix some of the underlying debugging.   The server will have access to passwords before its resalted into the database.   Of course, we could use github (there is a bug for that somewhere), etc. so we are never transmitting / storing locally, but so long as the server and client are secure, everything else should be secure in-transit.

**Comment by erasche** [comment]
@nathandunn perhaps:

- capture and sanitize exceptions during deserialization that might contain passwords
- capture and sanitize exceptions through any code paths that go to password checking

but I know this is a lot of changes. I was just a bit saddened to have to report to a user that I'd seen their password and that they should change any place they use that password.

**Comment by nathandunn** [comment]
No, its a good sadness.  We definitely want to avoid this.   Why Oauth might be nice.
