### ISSUE TITLE
Change canned "keys" to canned "tags"

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1365]
Let's remember to update this bit after we are done with transformation of coordinates.

**Comment by nathandunn** [comment]
@monicacecilia  It means canned comments will only show up for that feature type.  So, if you have a repeat_region specific comment or key, you won't see it for genes, transcripts etc.

**Comment by monicacecilia** [comment]
@nathandunn I think you are responding to a question I made in #1194 - right?

**Comment by nathandunn** [comment]
Yes

**Comment by nathandunn** [comment]
I think this can be closed if we merged in the relevant pr

**Comment by monicacecilia** [comment]
No yet. We have not yet made this change.

**Comment by nathandunn** [comment]
Agreed.   Sorry, misread the title.
