### ISSUE TITLE
(2d) stress test / bootstrap large data

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#137]
- [x] evaluate that we are meeting overall load performance, we are doing 2 actions (write only) / want about 3 / sec: should still be fine, since they were 100% write operations and we are going to 20% write.
- [x] redo tests for more users, reasonable frequency of events as below in typical numbers
  - [x] fix memory for a longer time:
    - [x] [turn off GUI listeners] (http://www.ubik-ingenierie.com/blog/jmeter_performance_tuning_tips/)
    - [x]  [set HEAP=-Xms256m -Xmx2048m]  (http://wiki.apache.org/jmeter/JMeterFAQ#JMeter_keeps_getting_.22Out_of_Memory.22_errors.__What_can_I_do.3F)
  - [x] get all 17 users to be active
  - [x] do a long (10-24 hour test) -> (3.4 ops / sec, 0.01% error overall), 30-50% CPU laptop usage (one thread 175-215%) with almost the same YourKit results (50% convertFeatureToJson, FeatureLocation 10%, Parent / Child 10%)
- [x] optimize
   - [x] pull transcripts via a child join (100% improvement, for max samples)
   - [x] optimize getAllSequenceAlterationsForFeature (194 ms)  . .. . fixed (now back down to ~10 ms)
   - [x] pull parent of transcript via the same join (10% cost) (no real performance gain / slight loss)
   - [x] separate query for feature locations (28 ops / sec)
   - [x] fix generateUniqueNames (8%)  -> up to 35 ops / sec after 1 min
   - [x] change feature location to "join" from sub-select (http://grails.github.io/grails-doc/2.1.0/ref/Domain%20Classes/fetchMode.html) ->  22.6 ops / sec vs 21 for previous (1 min timing)
   - [x] compare to master (18 ops / sec after 1 min)
   - [x] create pull request 
     - [x] comments 
   - [x] stress test again . . . validate errors
   - [x] merge into master 

Moved to #507 
~~- [ ] pre-fill database with annotations to observe differences~~
~~- [ ] do a network latency test (off of icebox) to observe differences~~

NAL / i5K can have:
- 100 organisms per server( ? . . not sure what that limit is) 
- 5K annotations per organism
- up to 100K sequences per organism
- so maybe 1Mil annotations per server

Typically numbers:
- 6/7 users, peak 30
- create 1 feature / user / minute . . and 5 views
- databases are prefilled 
- reasonable test:  15 users, 2 features / added / user / minute , 10 views, 1 GFF3 export every 10 minutes.

Potential important Optimizations for write / delete:
- [x] !!org.bbop.apollo.NameService.$tt__makeUniqueFeatureName(Organism, String, PaddingStrategy, boolean, TransactionStatus) NameService.groovy:78 1244819
- [x] org.bbop.apollo.FeatureRelationshipService.$tt__getParentsForFeature(Feature, String[], TransactionStatus) FeatureRelationshipService.groovy:56 263521
- [x] org.bbop.apollo.Feature.getFeatureLocation() Feature.groovy:154 336966

**Comment by selewis** [comment]
I still am strongly against relational. It just isn't suited to genomic
feature data. I think it will waste time going in this direction.

**Comment by nathandunn** [comment]
Can you provide some examples / reasoning?   I think that are many examples of this working, but I might be missing something.  I’m not wedded to one or the other either way, just want good reasoning either way.   Going non-relational won’t necessarily give us a speed-up if done for the wrong reasons.    

Nathan

**Comment by selewis** [comment]
When you have a chance to skype, or you're back (no rush)

**Comment by nathandunn** [comment]
Let’s chat when I’m down next.   I’ve got quite a bit of work to do before we have to make that decision.  Most of the grails code is pretty database neutral thus far.  

Nathan

**Comment by cmdcolin** [comment]
I was going to propose bulk importing an existing GFF with known protein sequences and then checking the output of our fasta export against the known protein sequences.

**Comment by cmdcolin** [comment]
I started doing the bulk import but the memory gets out of hand. Need to see what's goin on

**Comment by nathandunn** [comment]
Try attaching yourkit to the running instance.   How are you doing the imports?

**Comment by cmdcolin** [comment]
I was using the add_transcripts_from_gff3_to_annotations.pl script

I think I recall another user had similar memory issues with this script but I just wanted to investigate it further if we are to continue supporting this

Anyways, I got yourkit initialized so I'll see what i can do

**Comment by nathandunn** [comment]
So, is the issue the memory, though?  Hibernate will use all available memory for cache, but it is typically pretty smart about it.   I would be more willing to bet that the IO is a problem.  If you look into the SQL section (especially when running in tomcat) you can see the # of queries, and average query time per each.   Very curious where inserts come into this.

**Comment by cmdcolin** [comment]
It has been a little tricky to figure out exactly what it taking up time, and indeed sometimes the garbage collector is quite good. The YourKit software is also very good though at tracing these garbage collections.

Maybe this is random but I think one operation that gets pretty heavy is the annotator panel. It takes a very long time to find all annotations on all sequences. It starts up a lot of different queries

**Comment by nathandunn** [comment]
See #389.   I had already done some of this work on the sequence panel page.

**Comment by nathandunn** [comment]
@cmdcolin  Let me know what your test script was when you have moment.  I can also take a look at this.

**Comment by nathandunn** [comment]
@cmdcolin   Not that this is an actual performance bottleneck, but I saw this:

select this_.id as id1_63_0_, this_.version as version2_63_0_, this_.chunk_number as chunk_nu3_63_0_, this_.residue as residue4_63_0_, this_.sequence_id as sequence5_63_0_ from sequence_chunk this_ where this_.sequence_id=? and this_.chunk_number=? limit ? 82 0 90

That is 82 ms total time  (I was updating a exon boundary), avg of 0 ms each and 90 total invocations.   Of course this could be quicker than going to the filesystem, as well.

**Comment by nathandunn** [comment]
Using jmeter for evaluation / script development. .

**Comment by cmdcolin** [comment]
This is indeed called under many different circumstances. It boils down to getResiduesFromSequence for doing that query.

I thought that i could optimize that with the filesystem and that actually is available on this branch: https://github.com/GMOD/Apollo/tree/seq_chunk_remove

However, it really just needs to better optimize the use of that function. 

Here's an example of poor use: when we add a transcript, the NonCanonicalSplitSiteService calls the getResiduesWithAlterations which in turn calls getResiduesFromSequence repeatedly for each tiny little two-base splice site. It should ideally just get the whole sequence region, and check for the splice sites in that larger sequence.

**Comment by nathandunn** [comment]
I think that there are probably quite a few things like that (see my fixes for FlankingRegion).   We have the backing regression tests, so it wouldn’t hurt to try and fix these.   

That being said, I think we need a good baseline for performance.  The most expensive operations are going to continue to be transcript addition.  Trying to setup a WA1 -> WA2 migration while running YourKit is likely the best way to do this. 

Nathan

**Comment by nathandunn** [comment]
@cmdcolin   FYI, I opened a new issue #452.   Feel free to look at this or the other one.   I added your note and hope to catch a few other things of that type here.   Also to note, we don't really take advantage of using queries with fmin / fmax, and instead iterate through objects in order to check on them.

**Comment by nathandunn** [comment]
@childers @mpoelchau . . . I wonder if it would be a good time to evaluate starting an evaluation script so as to evaluate some of these numbers (and if we can have fewer servers).

**Comment by cmdcolin** [comment]
can you restate that please :)

**Comment by nathandunn** [comment]
@cmdcolin  Thanks.   Should be fixed @childers @mpoelchau . . . maybe we can chat about next week.

**Comment by childers** [comment]
@nathandunn Sure, lets talk more about it next week.  The data and user migration is certainly something that has been on our minds over here.

**Comment by nathandunn** [comment]
Sounds good.   I may or may not be available that week.   We’ll see.    If not, the following week then.  

That being said, we do have scripts available migrating apollo 2 to 1, users, and organisms.  The last two, you’ll need to generate the data out of your databases / instances.  

Nathan

**Comment by nathandunn** [comment]
To test, will use ```add_transcripts_from_gff3_to_annotations.pl``` to load a ref seq onto the organism.  

But I need to get only a few ref sequences first. 

@cmdcolin  reports really high CPU spiking not only for the load (which I might expect), but also for simply viewing them, possibly implicating #389 and exposing other inefficiencies, which is good.

**Comment by nathandunn** [comment]
Grepped 1.1 and 1.10 from this. 

```./add_transcripts_from_gff3_to_annotations.pl --user http://localhost:8080/apollo -u ndunn@me.com -p demo -i amel_OGSv3.2_small.gff3```

**Comment by nathandunn** [comment]
@cmdcolin  Just a note.  I think you want to setup the agent directly on the java binary.  Top is maxing out (as you experienced), but yourkit is showing a pretty low percentage.

**Comment by nathandunn** [comment]
@cmdcolin   So, if we are bulk loading databases, it probably makes sense to setup the database for bulk loading (e.g., removing indexes):

http://www.postgresql.org/docs/9.2/static/populate.html

Of course, this isn't the get_features problem.  

As a timing: 

./add_transcripts_from_gff3_to_annotations.pl --url  -u ndunn@me.com -p demo   0.20s user 0.04s system 0% cpu 45.937 total

To add just group 1.10 (143 genes) it takes 45 seconds. 

It takes 4 seconds to return all of these, is the bigger concern.   Should be under <1 second (like SequencePanel).  Part of #389 to fix that.

**Comment by nathandunn** [comment]
Either way, we'll need to explore doing bulk loads.   5K annotations is a bit rough.

**Comment by cmdcolin** [comment]
>It takes 4 seconds to return all of these, is the bigger concern.

that is my concern more as well. the browsing should feel snappy.

**Comment by cmdcolin** [comment]
will try and address some issues in #460 or some cherry picked version of it

**Comment by nathandunn** [comment]
I'm also wondering if that script if is not releasing memory, either.

**Comment by nathandunn** [comment]
I know hibernate maxes out, but it doesn't seem to scale linearly, which indicates an issue with memory, or a VERY large transaction.

**Comment by nathandunn** [comment]
Going to have to go with not linear:

./add_transcripts_from_gff3_to_annotations.pl --url  -u ndunn@me.com -p demo   0.44s user 0.03s system 0% cpu 6:12.35 total

7 * more lines - 412 genes vs 143 (maybe its slow with exons . . . ??),   

Note that get_features is only 425 ms (to display genomics), whereas loading annotations is 34 seconds.   Most of that is data transferred, but never shown, which is an obvious reason to have the database.  May just need to role my own pagination scheme.  Shouldn't be too bad.

**Comment by cmdcolin** [comment]
Ya it's probably more linear with the number of child features, so not exactly exponential, but I think ideally we can make a solution for the "n+1 query problem" that i see mentioned a lot and instead minimize number of queries

**Comment by nathandunn** [comment]
From talk with @childers during dev meeting:

Stress test should be over 10 hours, with 5-10 users per organism with multiple organisms adding and removing genes.

**Comment by childers** [comment]
@jwlin built our stress test script so that those options were configurable parameters, so we could vary number of users, number of instances and time/number of operations.  We shared that with you, right?

**Comment by nathandunn** [comment]
Yep .. we have it here:  https://github.com/GMOD/Apollo/tree/master/docs/apollo-stress-template

I should be able to get it to work with only minor changes.

**Comment by nathandunn** [comment]
@deepakunni3   Here you go.  @jwlin wrote the original JMX / Jmeter scripts and doc and am sure would be happy to help if that route makes the most sense.

**Comment by deepakunni3** [comment]
@nathandunn I updated the JMX script for Apollo 2.0 and tried running it with the following thread properties:
```
Number of Threads (users): 3
Ramp-Up Period (in seconds): 5
Loop Count: 8
```

There were couple of issues observed:
1. StaleObjectStateException while processing request addTranscript
2. StaleObjectStateException while processing request deleteFeature
3. deadlock detected (when the number of users are increased to 10)

**Comment by nathandunn** [comment]
@deepakunni3   Thanks.  Do you have the updated script (or a template for the script) checked in?   Also, is this reading / writing to the same gene / isoform?   I'm more concerned with these exceptions occurring when users are working on different genes, which is a more normal workflow . . . not that these errors shouldn't be attended to.

**Comment by nathandunn** [comment]
@deepakunni3   So, I guess what I am saying is, can we run the test with 10 users working on 10 different genes (and preferably on different organisms?).  Just 10 user and 10 genes would be helpful.  I think that the 10 organisms would not matter (knock on wood).  They could all be on the same sequence.

**Comment by deepakunni3** [comment]
@nathandunn The updated script is on master branch.

Yes, you are right. Multiple users working on the same transcript is rare.
I can definitely improve the script to test with different users working on different genes.

**Comment by nathandunn** [comment]
Yeah, if you could do that separation that would be great.  I know that Moni said that is rare, but also I think we might end up auto-locking these at some point. 

Nathan

**Comment by nathandunn** [comment]
```
RequestHandlingService	addTranscript	30.93%	280	320	0.88	2.07	0.24	0.36
FeatureService	generateTranscript	26.24%	238	320	0.74	1.83	0.17	0.32
FeatureService	convertFeatureToJSON	13.28%	120	13865	0.01	0.06	0.00	0.01
RequestHandlingService	deleteFeature	12%	109	320	0.34	8.15	0.04	0.50
NonCanonicalSplitSiteService	findNonCanonicalAcceptorDonorSpliceSites	8.37%	76	595	0.13	0.47	0.01	0.09
FeatureService	convertJSONToFeature	5.41%	49	16136	0.00	0.03	0.00	0.01
FeatureService	calculateCDS	1.65%	15	275	0.05	0.24	0.02	0.03
FeatureService	setLongestORF	1.63%	15	275	0.05	0.20	0.02	0.03
RequestHandlingService	getFeatures	0.22%	2	4	0.51	1.49	0.06	0.67
FeatureService	addFeature	0.14%	1	57	0.02	0.07	0.00	0.03
FeatureService	convertJSONToFeatureLocation	0.04%	0	16456	0.00	0.00	0.00	0.00
FeatureService	convertFeatureLocationToJSON	0.04%	0	13865	0.00	0.00	0.00	0.00
FeatureService	getTopLevelFeature	0.03%	0	135	0.00	0.01	0.00	0.00
AnnotationEditorController	getUserPermission	0%	0	4	0.01	0.02	0.00	0.01
RequestHandlingService	createJSONFeatureContainer	0%	0	960	0.00	0.00	0.00	0.00
```

**Comment by nathandunn** [comment]
I think that these error rates are far too high. 

<img width="952" alt="screen shot 2015-07-22 at 5 21 53 pm" src="https://cloud.githubusercontent.com/assets/751274/8840453/2dbbe1f0-3096-11e5-9a03-2cb29717afe7.png">

**Comment by nathandunn** [comment]
Rerun for about an hour . . . and now am not getting any errors:

<img width="951" alt="screen shot 2015-07-22 at 6 37 32 pm" src="https://cloud.githubusercontent.com/assets/751274/8841298/ce6aac9e-30a0-11e5-8f58-14eff50d010f.png">

Though the server is very much lagging to keep up and the database is floored:

<img width="721" alt="screen shot 2015-07-22 at 6 38 42 pm" src="https://cloud.githubusercontent.com/assets/751274/8841323/fe0d6aa4-30a0-11e5-9c49-d38507381f84.png">

**Comment by nathandunn** [comment]
Clearly over time it is getting worse with the throughput of adds / deletes fired off to the database.

**Comment by nathandunn** [comment]
Last snapshot Last snapshot: 

<img width="1166" alt="screen shot 2015-07-22 at 7 34 34 pm" src="https://cloud.githubusercontent.com/assets/751274/8841923/cd87ef8c-30a8-11e5-8c98-6f9d2e0046b5.png">

**Comment by nathandunn** [comment]
The snapshot from yourkit is as follows from SQL:

<img width="937" alt="screen shot 2015-07-22 at 8 36 08 pm" src="https://cloud.githubusercontent.com/assets/751274/8842646/9442ad62-30b1-11e5-97c7-84ef139d5ce4.png">

```
select feature0_.id as id1_19_0_, feature0_.version as version2_19_0_, feature0_.date_created as date_cre3_19_0_, feature0_.dbxref_id as dbxref_i4_19_0_, feature0_.description as descript5_19_0_, feature0_.is_analysis as is_analy6_19_0_, feature0_.is_obsolete as is_obsol7_19_0_, feature0_.last_updated as last_upd8_19_0_, feature0_.md5checksum as md9_19_0_, feature0_.name as name10_19_0_, feature0_.sequence_length as sequenc11_19_0_, feature0_.status_id as status_12_19_0_, feature0_.symbol as symbol13_19_0_, feature0_.unique_name as unique_14_19_0_, feature0_.alteration_residue as alterat16_19_0_, feature0_.deletion_length as deletio17_19_0_, feature0_.analysis_feature_id as analysi18_19_0_, feature0_.alternate_cv_term as alterna19_19_0_, feature0_.class_name as class_n20_19_0_, feature0_.custom_alternate_cv_term as custom_21_19_0_, feature0_.custom_class_name as custom_22_19_0_, feature0_.custom_cv_term as custom_23_19_0_, feature0_.custom_ontology_id as custom_24_19_0_, feature0_.cv_term as cv_term25_19_0_, feature0_.meta_data as meta_da26_19_0_, feature0_.ontology_id as ontolog27_19_0_, feature0_.class as class15_19_0_ from feature feature0_ where feature0_.id=? 5149 0 6864
```

```
select featureloc0_.feature_id as feature_3_19_0_, featureloc0_.id as id1_25_0_, featureloc0_.id as id1_25_1_, featureloc0_.version as version2_25_1_, featureloc0_.feature_id as feature_3_25_1_, featureloc0_.fmax as fmax4_25_1_, featureloc0_.fmin as fmin5_25_1_, featureloc0_.is_fmax_partial as is_fmax_6_25_1_, featureloc0_.is_fmin_partial as is_fmin_7_25_1_, featureloc0_.locgroup as locgroup8_25_1_, featureloc0_.phase as phase9_25_1_, featureloc0_.rank as rank10_25_1_, featureloc0_.residue_info as residue11_25_1_, featureloc0_.sequence_id as sequenc12_25_1_, featureloc0_.strand as strand13_25_1_ from feature_location featureloc0_ where featureloc0_.feature_id=? 4076 1 3786
```

```
update feature set version=?, date_created=?, dbxref_id=?, description=?, is_analysis=?, is_obsolete=?, last_updated=?, md5checksum=?, name=?, sequence_length=?, status_id=?, symbol=?, unique_name=? where id=? and version=? 3291 0 4222
```

**Comment by nathandunn** [comment]
<img width="928" alt="screen shot 2015-07-22 at 8 41 02 pm" src="https://cloud.githubusercontent.com/assets/751274/8842670/fd9e5a86-30b1-11e5-944c-75f2fcf03f2d.png">

**Comment by nathandunn** [comment]
Database results:

Summary . . worst offendors:
- 50% - org.bbop.apollo.NameService.$tt__makeUniqueFeatureName(Organism, String, PaddingStrategy, boolean, TransactionStatus) NameService.groovy:78 1244819
- 15% - - org.bbop.apollo.FeatureRelationshipService.$tt__getParentsForFeature(Feature, String[], TransactionStatus) FeatureRelationshipService.groovy:56 248897
-  15% - org.bbop.apollo.Feature.getFeatureLocation() Feature.groovy:154 336966
- ~5% - org.bbop.apollo.FeatureService.$tt__getAllSequenceAlterationsForFeature(Feature, TransactionStatus) FeatureService.groovy:883 129921
- ~5% - org.bbop.apollo.FeaturePositionComparator.compare(Feature, Feature) FeaturePositionComparator.groovy:24 214847
- 1% - org.bbop.apollo.OverlapperService.$tt__overlaps(Feature, Feature, boolean, TransactionStatus) OverlapperService.groovy:98 43078






<img width="935" alt="screen shot 2015-07-22 at 8 43 13 pm" src="https://cloud.githubusercontent.com/assets/751274/8842698/4e08f030-30b2-11e5-8460-1b1e1d6395c1.png">

== X 50%==
- 44% - org.bbop.apollo.NameService.$tt__makeUniqueFeatureName(Organism, String, PaddingStrategy, boolean, TransactionStatus) NameService.groovy:78 1244819
- 7% - org.bbop.apollo.FeatureRelationshipService.$tt__getParentsForFeature(Feature, String[], TransactionStatus) FeatureRelationshipService.groovy:56 248897
- 3% - org.bbop.apollo.FeatureService.$tt__getAllSequenceAlterationsForFeature(Feature, TransactionStatus) FeatureService.groovy:883 129921
- 9% - org.bbop.apollo.Feature.getFeatureLocation() Feature.groovy:154 336966
- 3% - org.bbop.apollo.FeatureRelationshipService.getChildrenForFeatureAndTypes(Feature, String[]) FeatureRelationshipService.groovy 
- 8-15% the various saves (where I would expect it to be)

== X 25% ==
- 13% - org.bbop.apollo.FeatureRelationshipService.$tt__getParentsForFeature(Feature, String[], TransactionStatus) FeatureRelationshipService.groovy:56 263521
- 7% - org.bbop.apollo.FeatureService.$tt__getAllSequenceAlterationsForFeature(Feature, TransactionStatus) FeatureService.groovy:883 134871
- 3% - org.bbop.apollo.PermissionService.$tt__getCurrentUser(JSONObject, TransactionStatus) PermissionService.groovy:259 58096
- 18% - org.bbop.apollo.Feature.getFeatureLocation() Feature.groovy:154 354802
- 21% - org.bbop.apollo.NameService.$tt__makeUniqueFeatureName(Organism, String, PaddingStrategy, boolean, TransactionStatus) NameService.groovy:78 411533
- 7% - org.bbop.apollo.SequenceAlteration.getAll() SequenceAlteration.groovy 135056
- 4% - org.bbop.apollo.FeatureRelationship.hashCode() FeatureRelationship.groovy:37 85389

== X 24% ==
- 67 % - org.bbop.apollo.NameService.$tt__makeUniqueFeatureName(Organism, String, PaddingStrategy, boolean, TransactionStatus) NameService.groovy:78 1316536
- 25% - saves  .  what you would expect

**Comment by nathandunn** [comment]
Notes for running this test are here:

https://github.com/GMOD/Apollo/blob/master/docs/jmeter-dev-stress-test-notes.md

**Comment by nathandunn** [comment]
results included.  5/1 getFeatures vs add/delete, which is reflected.  Still 0 errors, though jmeter keeps running out of memory.   Need to fix when setting options: http://stackoverflow.com/questions/20647651/jmeter-test-failed-with-out-of-memory-error

A couple of other areas to optimize / RHS::539 getFeatures (iterating over instead of getting directly).   Not sure where in method this is slowing down other than the best method would be to optimize it for transcripts (3 levels). 

![screen shot 2015-07-25 at 10 17 40 am](https://cloud.githubusercontent.com/assets/751274/8890454/6d6707f4-32b6-11e5-9928-f466ea34a3cb.png)

**Comment by nathandunn** [comment]
SQL methods . . . these are all fast, but each take 7 seconds with 3K invocations . .. getChildrenForFeatureAndTypes are 2 of 7, 1 of 7 is for getParentsForFeature, the rest (4) is convert JSONToFeature:

    select this_.id as id1_30_0_, this_.version as version2_30_0_, this_.child_feature_id as child_fe3_30_0_, this_.parent_feature_id as parent_f4_30_0_, this_.rank as rank5_30_0_, this_.value as value6_30_0_ from feature_relationship this_ where this_.child_feature_id=? 8568 2 3233

    select parentfeat0_.parent_feature_id as parent_f4_19_0_, parentfeat0_.id as id1_30_0_, parentfeat0_.id as id1_30_1_, parentfeat0_.version as version2_30_1_, parentfeat0_.child_feature_id as child_fe3_30_1_, parentfeat0_.parent_feature_id as parent_f4_30_1_, parentfeat0_.rank as rank5_30_1_, parentfeat0_.value as value6_30_1_ from feature_relationship parentfeat0_ where parentfeat0_.parent_feature_id=? 8462 2 3220

    select featureloc0_.feature_id as feature_3_19_0_, featureloc0_.id as id1_25_0_, featureloc0_.id as id1_25_1_, featureloc0_.version as version2_25_1_, featureloc0_.feature_id as feature_3_25_1_, featureloc0_.fmax as fmax4_25_1_, featureloc0_.fmin as fmin5_25_1_, featureloc0_.is_fmax_partial as is_fmax_6_25_1_, featureloc0_.is_fmin_partial as is_fmin_7_25_1_, featureloc0_.locgroup as locgroup8_25_1_, featureloc0_.phase as phase9_25_1_, featureloc0_.rank as rank10_25_1_, featureloc0_.residue_info as residue11_25_1_, featureloc0_.sequence_id as sequenc12_25_1_, featureloc0_.strand as strand13_25_1_ from feature_location featureloc0_ where featureloc0_.feature_id=? 7505 2 3180

    select feature0_.id as id1_19_0_, feature0_.version as version2_19_0_, feature0_.date_created as date_cre3_19_0_, feature0_.dbxref_id as dbxref_i4_19_0_, feature0_.description as descript5_19_0_, feature0_.is_analysis as is_analy6_19_0_, feature0_.is_obsolete as is_obsol7_19_0_, feature0_.last_updated as last_upd8_19_0_, feature0_.md5checksum as md9_19_0_, feature0_.name as name10_19_0_, feature0_.sequence_length as sequenc11_19_0_, feature0_.status_id as status_12_19_0_, feature0_.symbol as symbol13_19_0_, feature0_.unique_name as unique_14_19_0_, feature0_.alternate_cv_term as alterna16_19_0_, feature0_.class_name as class_n17_19_0_, feature0_.custom_alternate_cv_term as custom_18_19_0_, feature0_.custom_class_name as custom_19_19_0_, feature0_.custom_cv_term as custom_20_19_0_, feature0_.custom_ontology_id as custom_21_19_0_, feature0_.cv_term as cv_term22_19_0_, feature0_.meta_data as meta_da23_19_0_, feature0_.ontology_id as ontolog24_19_0_, feature0_.alteration_residue as alterat25_19_0_, feature0_.deletion_length as deletio26_19_0_, feature0_.analysis_feature_id as analysi27_19_0_, feature0_.class as class15_19_0_ from feature feature0_ where feature0_.id=? 7458 2 3151

    select owners0_.feature_owners_id as feature_1_19_0_, owners0_.user_id as user_id2_24_0_, user1_.id as id1_40_1_, user1_.version as version2_40_1_, user1_.first_name as first_na3_40_1_, user1_.last_name as last_nam4_40_1_, user1_.password_hash as password5_40_1_, user1_.username as username6_40_1_ from feature_grails_user owners0_ inner join grails_user user1_ on owners0_.user_id=user1_.id where owners0_.feature_owners_id=? 7064 2 3069

    select featurepro0_.feature_id as feature_3_19_0_, featurepro0_.id as id1_27_0_, featurepro0_.id as id1_27_1_, featurepro0_.version as version2_27_1_, featurepro0_.feature_id as feature_3_27_1_, featurepro0_.rank as rank4_27_1_, featurepro0_.tag as tag5_27_1_, featurepro0_.type_id as type_id6_27_1_, featurepro0_.value as value7_27_1_, featurepro0_.class as class8_27_1_ from feature_property featurepro0_ where featurepro0_.feature_id=? 7007 2 3097

    select featuredbx0_.feature_featuredbxrefs_id as feature_1_19_0_, featuredbx0_.dbxref_id as dbxref_i2_20_0_, dbxref1_.id as id1_15_1_, dbxref1_.accession as accessio3_15_1_, dbxref1_.db_id as db_id4_15_1_, dbxref1_.description as descript5_15_1_ from feature_dbxref featuredbx0_ inner join dbxref dbxref1_ on featuredbx0_.dbxref_id=dbxref1_.id where featuredbx0_.feature_featuredbxrefs_id=? 6943 2 3059

**Comment by nathandunn** [comment]
Also should get rid of ".each" in those methods for getting other tpyes

**Comment by nathandunn** [comment]
after 3 hours . . it looks like PostgreSQL is lagging . . :

```
ID    COMMAND      %CPU      TIME     #TH    #WQ   #PORT MEM    PURG   CMPRS  PGRP  PPID  STATE    BOOSTS
40266  java         242.7     06:46:04 82/2   0     200   1721M  0B     0B     40258 1     running  *0[6]
41876  postgres     52.8      01:57.94 1      0     7     43M    0B     0B     41876 1158  sleeping *0[1]
41932  postgres     51.9      00:09.13 1/1    0     7     37M+   0B     0B     41932 1158  running  *0[1]
41933  postgres     51.5      00:05.51 1      0     7     15M+   0B     0B     41933 1158  sleeping *0[1]
41917  postgres     51.2      00:58.72 1/1    0     7     40M+   0B     0B     41917 1158  running  *0[1]
41868  postgres     50.7      02:12.30 1/1    0     7     43M    0B     0B     41868 1158  running  *0[1]
41928  postgres     50.6      00:24.52 1/1    0     7     15M+   0B     0B     41928 1158  running  *0[1]
41880  postgres     49.6      01:59.78 1/1    0     7     42M+   0B     0B     41880 1158  running  *0[1]
41866  postgres     36.3      02:37.57 1/1    0     7     44M+   0B     0B     41866 1158  running  *0[1]
41915  postgres     36.1      00:53.40 1/1    0     7     40M+   0B     0B     41915 1158  running  *0[1]
0      kernel_task  22.4      05:36:41 128/8  0     2     1401M  0B     0B     0     0     running   0[0]
41882  postgres     21.1      01:44.07 1/1    0     7     42M+   0B     0B     41882 1158  running  *0[1]
4
```

**Comment by nathandunn** [comment]
After almost 8 hours, still working fine.  Error rate overall is 0.01%, with 2.4 operations / sec with an overall target of 2 / sec.   A off of the adds / deletes (L11, L6, L7, L14) had ~0.14% error.    I had turned L5 off (so only running 15 threads, but mostly I think that it was just some initial bumps). 

Top looks identical to the above, but rarely dropping two below 200%.

**Comment by nathandunn** [comment]
Doing 4 threads jmeter-dev-blast-test-4.jmx, with a 1/5 get features over read features we get:

**Comment by nathandunn** [comment]
The optimized results are 2.7 ops / sec (twice) with one error.   That is 16 threads, and almost double the 1.4 ops / sec.

**Comment by nathandunn** [comment]
Other optimization target:  

Called at 12 X the amount (not sure if eager fetch is the same as a join, maybe do join to feature location on initial select? or not at all?):
```
select featureloc0_.feature_id as feature_3_19_0_, featureloc0_.id as id1_25_0_, featureloc0_.id as id1_25_1_, featureloc0_.version as version2_25_1_, featureloc0_.feature_id as feature_3_25_1_, featureloc0_.fmax as fmax4_25_1_, featureloc0_.fmin as fmin5_25_1_, featureloc0_.is_fmax_partial as is_fmax_6_25_1_, featureloc0_.is_fmin_partial as is_fmin_7_25_1_, featureloc0_.locgroup as locgroup8_25_1_, featureloc0_.phase as phase9_25_1_, featureloc0_.rank as rank10_25_1_, featureloc0_.residue_info as residue11_25_1_, featureloc0_.sequence_id as sequenc12_25_1_, featureloc0_.strand as strand13_25_1_ from feature_location featureloc0_ where featureloc0_.feature_id=? 189521 15 12117
```

getAllSequenceAlterationsForFeatures is a slow query when it call  . . NonCanonicalnSliptSiteService::findNonCanoncialAppectorDonorSplitSites(Transcrtipt)

**Comment by nathandunn** [comment]
The majority of the data usage is still grabbing the transcripts from the database, which should not be a surprise.   This is multiple joins . . which by necessity includes feature_location, so it might be worth it to include that.

**Comment by nathandunn** [comment]
after 4 hours of stress test, at a steady 3.5 ops / sec, with a CPU that is not constantly pegged.  Memory is stable at around 1.4 G.  CPU is REALLY spiky ,but it doesn't hang at ~200% as it did before and postgres is not constantly maxes.

**Comment by nathandunn** [comment]
![screen shot 2015-07-28 at 10 46 53 pm](https://cloud.githubusercontent.com/assets/751274/8950765/d6846c06-357a-11e5-9de3-fab742bf8e08.png)
![screen shot 2015-07-28 at 10 46 46 pm](https://cloud.githubusercontent.com/assets/751274/8950764/d683c062-357a-11e5-8919-207478349d7a.png)

**Comment by nathandunn** [comment]
After running it for 15 hours we have 9 total errors.  8 on L7, one on 6.   It should be noted that additions are done via a "burst" (at least initially), which might account for some of these issues.   The averages for adding transcript was close to a second.   However, 3 were above 3 seconds, but largely due to variability. 
![screen shot 2015-07-29 at 7 49 41 am](https://cloud.githubusercontent.com/assets/751274/8960788/84515222-35c6-11e5-9a67-01cd81ca9781.png)
![screen shot 2015-07-29 at 7 49 22 am](https://cloud.githubusercontent.com/assets/751274/8960787/84508cfc-35c6-11e5-9260-901dc81a243c.png)

**Comment by nathandunn** [comment]
Using jmeter-dev-stress-2 (adds and deltes only): 22% of processing is (56% is generateTranscript):

    List results = (Feature.executeQuery("select f.name from Feature f join f.featureLocations fl join fl.sequence s join s.organism org where org = :org and f.name like :name ",[org:organism,name:name+'%']))

The next highest call (convertJSONToFeature) is 7%, but should have dominated.  

With regards to SQL it is pretty evenly balanced, but hash calls on ```FeatureRelationship``` and ```Feature``` are calling SQL feature which is probably un-necessary.  Also un-necassary to getParents / Children, which could otherwise come back in a join.

Data is roughly 2.0 / sec for this.

**Comment by nathandunn** [comment]
Removed data (and some other un-necessary code) . . . results overall are MUCH better.   7.8 ops / sec for jmeter-dev-stress-2 (4 threads going AFAP).  All averages are <500 ms and all maxes are below 3.

**Comment by nathandunn** [comment]
For a longer stretch, we got 4 samples / sec for jmeter-dev-stress-2 (4 threads going AFAP) with no errors for an hour.  


- [ ] This probably needs to be a join.   
    FS::getOverlappingFeatures() . .
       . . .  criteraQuery . . makes this un-necessary call 
       return results*.feature.unique()

- [ ] Also, the hash function on FeatureRelationship calls hash onparent and child features Features, which is also un-necessary. 
- [ ] Also, FRS::getParentsForFeature() . . . especially from FS::convertFeatureToJSON()

- [ ] DeleteFeature can do a convertFeatureToJSON using the transcript code.

**Comment by nathandunn** [comment]
I get about 40 samples / sec after 1 minutes for the blast test . . . after the add /delete fixes.

**Comment by nathandunn** [comment]
Nothing to test.
