### ISSUE TITLE
set to upstream donor seems to be failing

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1379]
It almost completely mirrors the code from Apollo 1.

**Comment by nathandunn** [comment]
Looks like its finding itself (well, at least that works) and then setting itself.

**Comment by deepakunni3** [comment]
Ah, that explains why there was no errors.

**Comment by nathandunn** [comment]
I merged but reopen if a problem

**Comment by nathandunn** [comment]
@monicacecilia  @deepakunni3   this is fixed in RC4 and is on staging.  I mis-copied WA1 code.   Uggh.

**Comment by monicacecilia** [comment]
I don't see an emoji for 'thank goodness'...
