### ISSUE TITLE
Incorrect genomic sequence is exported for features with overlapping sequence alterations

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1381]
When a transcript, specifically on the reverse strand, has overlapping sequence alterations (especially more than one) the genomic sequence which is exported contains these overlapping sequence alterations incorporated incorrectly. 
However, the CDNA and CDS (and by extension PEPTIDE) export remains intact.

**Comment by deepakunni3** [comment]
Working on a fix for this issue.

**Comment by monicacecilia** [comment]
💃
