### ISSUE TITLE
enable oauth login to enable drupal authentication

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#139]
related to pull request #117   . . .

**Comment by nathandunn** [comment]
@cmdcolin   Here is the original one.  The oauth should be in there.  Just isn't doing anything.

**Comment by cmdcolin** [comment]
Thanks for pointing me to it. I'll see what I can do.

**Comment by cmdcolin** [comment]
The OAuth api is fairly complex and I don't have time to review all the intricacies right now. I almost got it to authenticate using the existing code, but it I had to change lines 222-225 to a get request instead of a post and then i still didn't end up with an ID token after that.

So, deferred for now.

I will probably review this later when time is available http://oauthbible.com

For now I'll just remove it from the change log

**Comment by nathandunn** [comment]
I think that is a good call.  I moved it.

**Comment by vivekkrish** [comment]
Just wanted to chime in on this.

Have you all come across `jso` (OAuth 2.0 Client with Javascript, https://github.com/andreassolberg/jso)?
It implements the complete OAuth2.0 implicit flow, and is AMD-loading compatible.

Just with about 5-10 lines of javascript (see the [Getting Started](https://github.com/andreassolberg/jso/blob/master/README-getting-started.md#getting-started-1) section), it is possible to make an client side app like JBrowse support an OAuth2.0 based login flow.

And, according to their documentation, a new version of `jso` is available for testing, which supports authentication with OpenID as well, see: http://oauth.no/jso/)

Hope this helps!

**Comment by nathandunn** [comment]
Thanks . . . we might be able to use this.  I've heard that figuring out OAuth flavors can be interesting.

**Comment by vivekkrish** [comment]
You're welcome! I was alerted to the presence of this module by one of our collaborators at UT Austin.  

We've explored the possible integration of this into our applications to utilize our own OAuth2 login flow (within the Araport project, https://www.araport.org), giving such apps access to an Araport `token` which could be utilized to make calls to authenticated Araport APIs (https://www.araport.org/api-explorer/).

**Comment by nathandunn** [comment]
@laceysanderson Suggested that drupal / tripal might get an automatic oauth module and we would connect to that.

**Comment by nathandunn** [comment]
Dupe of #938
