### ISSUE TITLE
Changes to canvasfeatures color / css?

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1393]
I noticed that on more recent builds of apollo (admittedly this hasn't been tested in a while), colors are not rendered quite properly for my canvas features (and completely disabled with HTML features due to style overrides...)

Correct output (as seen in JBrowse by itself):
![utvalg_057](https://cloud.githubusercontent.com/assets/458683/21399700/8bfdf414-c7a4-11e6-8be8-f921b1019cb3.png)

With a hard-coded color in Apollo:
![utvalg_055](https://cloud.githubusercontent.com/assets/458683/21399706/93b2cab8-c7a4-11e6-883d-72f95d2e7d90.png)

Hovering over them causes them to go blue and then grey
![utvalg_056](https://cloud.githubusercontent.com/assets/458683/21399728/b20d3174-c7a4-11e6-87ec-cffff05a2e16.png)

With the proper color function that works fine in JBrowse:
![utvalg_058](https://cloud.githubusercontent.com/assets/458683/21399727/af4f188a-c7a4-11e6-886a-06ef8e233cac.png)

Here's my trackList.json

```json
      {
         "urlTemplate" : "tracks/7546be86a2de96546f3df84dbfb49bb4_0/{refseq}/trackData.json",
         "glyph" : "JBrowse/View/FeatureGlyph/Segments",
         "type" : "JBrowse/View/Track/CanvasFeatures",
         "key" : "Canonical Phages",
         "style" : {
            "description" : "Hit_titles",
            "label" : "description",
            "color" : "    function(feature, variableName, glyphObject, track) {        var score = feature._parent.get('score');                    var opacity = 0;            if(score == 0.0) {{                opacity = 1;            }} else {{                opacity = (20 - Math.log10(score)) / 180;            }}  return 'rgba(227, 26, 28, ' + opacity + ')';    }    ",
            "className" : "feature"
         },
         "compress" : 0,
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "trackType" : "JBrowse/View/Track/CanvasFeatures",
         "category" : "Blast / Protein",
         "label" : "7546be86a2de96546f3df84dbfb49bb4_0"
      }
```

Tarball of data directory: https://cpt.tamu.edu/dot/blast-color-issue.tar.bz2

Is there any way we can just... completely disable Apollo styling on our own tracks? Especially for blast results, where the old "single-line-through-the-hit" was very clear. The new 
![utvalg_059](https://cloud.githubusercontent.com/assets/458683/21399885/73e0d396-c7a5-11e6-8d90-13193beec590.png)
 has people asking us questions they didn't before, misunderstanding how we're rendering the evidence.

**Comment by nathandunn** [comment]
@erasche  You can disable the definitely neat plugin(s), which shouldn't be on by default.   The up versus down is just strand info, but it may interfere with other stuff.  I added "Neat" plugins to master (though they are not in 2.0.5 I think).  

In you go into the apollo-config.groovy file you would comment out this section:

https://github.com/GMOD/Apollo/blob/master/grails-app/conf/Config.groovy#L406-L412

You may want / need to make sure if you do a clean-all that the plugins aren't included.  

I updated the JBrowse version as well, but we shouldn't be forcing anything out, though I noticed there were some fixes to Canvas in there (hopefully those are still working).

**Comment by nathandunn** [comment]
@erasche  If its still over-writing the colors even after you've removed the Neat Plugin, let me know.   I'm not seeing those blues / blacks that you are off of master.

**Comment by erasche** [comment]
Rebuilding my apollo image now, thanks for the tip. That sounds like it's exactly what I need. I haven't made the update to 2.0.5 yet, hopefully will get to that in january.

**Comment by erasche** [comment]
That change was introduced in https://github.com/GMOD/Apollo/commit/17558740, looks like I haven't checked my apollo-config.groovy against the reference in a long time. Thanks!

**Comment by erasche** [comment]
Yep, confirmed. Thank you!
