### ISSUE TITLE
issue when logging out, then trying to log in again

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1394]
I was testing the latest code for our workflow, and ran into an issue when trying to reset my test by logging out.

On logout, I get a strange warning that the organism was not found, and the organism is a long stream of numbers:
<img width="617" alt="warning message when signing out" src="https://cloud.githubusercontent.com/assets/421248/21440492/3a83afda-c861-11e6-863f-d62343ebbd8e.png">

When I sign back in and click on one of my organisms, I get another message:
<img width="538" alt="error message when trying to sign back in" src="https://cloud.githubusercontent.com/assets/421248/21440493/3a83dc8a-c861-11e6-94c5-ae6fbbd18a50.png">

**Comment by childers** [comment]
This might be an issue with my browser.  I tried repeating it, and can't replicate this behavior.

**Comment by nathandunn** [comment]
Go ahed and close it fi you can’t duplicate it.  

Those strings are the client token it is trying to find an organism for. 

Nathan
