### ISSUE TITLE
Problem when browsing to multiple tabs when logged in

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1395]
I currently see a navigation issue in master.

1. I go BLAST-Jbrowse,
2. Log in,
3. Click to enable native tracks
4. Click to close panel
5. Make great annotations
6. Close and go to my next BLAST hit.
7. Click to go to the browser and it is apollo1 style (mostly) there is the modern organism selector, but no chevron to enable the Apollo2 right-side panel.

Here is the URL:
https://myserver.orgnet/apollo/9181426326681843991119596663/jbrowse/index.html?loc=Scaffold66%3A414756..1116791&addTracks=%5B%7B%22label%22%3A%22BLAST%20%20Results%22%2C%22category%22%3A%220.%20Reference%20Assembly%22%2C%22type%22%3A%22WebApollo%2FView%2FTrack%2FDraggableBLASTFeatures%22%2C%22store%22%3A%22url%22%2C%22style%22%3A%7B%22renderClassName%22%3A%22gray-center-10pct%22%2C%22subfeatureClasses%22%3A%7B%22match_part%22%3A%22blast-match_part%22%7D%7D%7D%5D&addStores%3D%7B%22url%22%3A%7B%22type%22%3A%22JBrowse%2FStore%2FSeqFeature%2FGFF3%22%2C%22urlTemplate%22%3A%22https%3A%2F%2Fmyotherserver.orgnet%2Fwebapp%2Fmedia%2Fblast%2Ftask%2F1bfc16f0ffe549619bce4fd12cdf2484%2FAgla_Btl03082013.genome_new_ids.fa.gff%22%7D%7D=&tracks=DNA%2CAnnotations%2CBLAST%20%20Results&highlight=
 
Version: 2.0.6-SNAPSHOT
Grails version: 2.5.5
Groovy version: 2.4.4
JVM version: 1.8.0_112

![apollo2 0 6-logged-in-no-apollo2-features](https://cloud.githubusercontent.com/assets/421248/21441213/d6a0f6cc-c864-11e6-9f58-a8fee7efe2ae.png)

**Comment by childers** [comment]
Can replicate this on Chrome and Opera.  Additionally, I don't have to collapse anything. If I'm logged in and open another link, it takes me to an apollo1 looking interface with no options to go to apollo2.  

Could it be that subsequent links are redirecting to the view you removed the Open Annotator Panel and Show Fullscreen buttons from?

**Comment by nathandunn** [comment]
That is exactly it.  

Nathan

**Comment by nathandunn** [comment]
- [ ] if logged in go straight to the annotator panel if a public link
- [ ] provide a "View Native Track Panel" link?

**Comment by nathandunn** [comment]
In JBrowse Controller, call loadPublicLink, but if there is already a login, but forward to the loadLink call instead with the same data. 

I'm not sure if we can open / close the native track div without refreshing (which might be okay).   However, we can probably add a button that is always in view to do the same thing.

**Comment by nathandunn** [comment]
Reopen if still problematic.

**Comment by childers** [comment]
Ok, just pulled from master, rebuilt and deployed.

When I get redirected from BLAST to Jbrowse everything looks fine. I log in and it redirects me to a blank white screen. Here is the URL post login:

Which is strange in that I' was testing on firefox and not chrome. 


**UPDATE**: When testing in Chrome, it works fine in an incognito window.  Shift + reload in firefox to clear cache reloads the page and maintains my logged in state, dropping me to the normal Apollo2 interface.

**Comment by nathandunn** [comment]
@childers  Are you saying that it works now?

**Comment by childers** [comment]
It seems to work now, yes.  I need to test it out a few more times, but it looks like it was caching an older version of the client code that was causing problems.

**Comment by nathandunn** [comment]
Awesome.  Yeah, the caching is a never-ending problem for development ;)
