### ISSUE TITLE
DraggableBLASTFeatures fails to hide intron when NeatFeatures added

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1415]
Testing 2.0.6 pull from Jan-5-2017 (commit 0f7cd21d4d351e6c5b8ea5ad78d76bf77c88bc7e), now the HTML draggable

 features are not displaying the same way.  Was there a change in the underlying render engine?

All the html based features are looking different than before, and I think it might be CSS related. 

(Edited as I mistakenly thought it was not displaying color properly. Colors  based on score still work fine)

Here is our track config (taken from the edit track feature)
```shell
{
  "maxFeatureSizeForUnderlyingRefSeq": 250000,
  "maxFeatureScreenDensity": 0.5,
  "maxHeight": 1000,
  "style": {
    "arrowheadClass": "webapollo-arrowhead",
    "className": "container-16px",
    "_defaultHistScale": 4,
    "_defaultLabelScale": 30,
    "_defaultDescriptionScale": 120,
    "minSubfeatureWidth": 1,
    "maxDescriptionLength": 70,
    "showLabels": true,
    "label": "name,id",
    "description": "note, description",
    "centerChildrenVertically": false,
    "renderClassName": "gray-center-10pct",
    "subfeatureClasses": {
      "UTR": "webapollo-UTR",
      "CDS": "webapollo-CDS",
      "exon": "container-100pct",
      "intron": null,
      "wholeCDS": null,
      "start_codon": null,
      "stop_codon": null,
      "match_part": "blast-match_part"
    }
  },
  "hooks": {},
  "events": {},
  "menuTemplate": [
    {
      "label": "View details",
      "title": "{type} {name}",
      "action": "contentDialog",
      "iconClass": "dijitIconTask"
    },
    {
      "iconClass": "dijitIconFilter"
    }
  ],
  "label": "BLAST+ Results",
  "category": "0. Reference Assembly",
  "type": "WebApollo/View/Track/DraggableBLASTFeatures",
  "index": 0,
  "metadata": {}
}

```
![apollo-new-look](https://cloud.githubusercontent.com/assets/421248/21723717/84cfbb02-d3ff-11e6-9bce-388d4f84d3e8.png)

**Comment by childers** [comment]
Let me know if this should be a Jbrowse issue instead.

**Comment by nathandunn** [comment]
Looks like its not hiding the correct intron class.   Not sure what issue this would be.  I'll take a quick look.

**Comment by nathandunn** [comment]
Conversely, you can easily remove the NeatFeatures plugin in the apollo-config.groovy file by over-riding that portion of the Config.  

You can configure it to go off I think in your trackList config:

https://github.com/GMOD/jbrowse/tree/master/plugins/NeatHTMLFeatures#config-options

You can also turn it all off by putting this in your ```apollo-config.groovy```, but hopefully that won't be necessary:

```
jbrowse {
    git {
        url= "https://github.com/gmod/jbrowse"
        tag = "1f4e39e611eca23d3197c4035b762b61d4812ae6"
        alwaysPull = false
        alwaysRecheck = false
    }
    plugins {
        WebApollo{
            included = true
        }
//        NeatHTMLFeatures{
//            included = true
//            linearGradient = 0
//        }
        NeatCanvasFeatures{
            included = true
        }
        RegexSequenceSearch{
            included = true
        }
        HideTrackLabels{
            included = true
        }

    }
```

**Comment by nathandunn** [comment]
@childers  You can try messing with the CSS and see.   The DraggableFeatures inherit directly from the DraggableHTMLFeatures.  Maybe the z-index is higher for the inner-css?   Don't know.

**Comment by nathandunn** [comment]
Pulled comment from https://github.com/GMOD/jbrowse/pull/834#issuecomment-270958322

> Oh, to make matters more confusing, I enabled one of the other htmlDragableFeature tracks, and it only has one intron line.  At certain zoom levels it disappeared, but I could not replicate the behavior.

<img width="1402" alt="apollo-new-look2" src="https://cloud.githubusercontent.com/assets/421248/21726925/db32054c-d40c-11e6-84e3-1ce61036186c.png">

**Comment by nathandunn** [comment]
@childers  Can you try changing the CSS and see what happens?   Also, if you can figure out what CSS is in the introns, that would be helpful.

**Comment by childers** [comment]
I see two element for the intron region:

```shell
<svg class="jb-intron" viewBox="0 0 100 100" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="position:absolute;z-index: 15;left: 2318.317px;width: 86.86299999999983px;height: 100%"><polyline points="0,50 50,5 100,50" style="fill:none;stroke:black;stroke-width:5" shape-rendering="optimizeQuality"></polyline></svg>

element {
    position: absolute;
    z-index: 15;
    left: 2318.317px;
    width: 86.86299999999983px;
    height: 100%;
}
.jb-intron {
    position: absolute;
}
.draggable {
    cursor: move;
}
html, body {
    font-size: 12px;
    font-family: Univers,Trebuchet MS,Helvetica,Arial,sans-serif;
}
body {
    font: 12px Myriad,Helvetica,Tahoma,Arial,clean,sans-serif;
}

```


```shell
<polyline points="0,50 50,5 100,50" style="fill:none;stroke:black;stroke-width:5" shape-rendering="optimizeQuality"></polyline>
```

```shell
element {
    fill: none;
    stroke: black;
    stroke-width: 5;
}
.draggable {
    cursor: move;
}
html, body {
    font-size: 12px;
    font-family: Univers,Trebuchet MS,Helvetica,Arial,sans-serif;
}
body {
    font: 12px Myriad,Helvetica,Tahoma,Arial,clean,sans-serif;
}
```

**Comment by nathandunn** [comment]
Something is wrong with the second one (if its the second one that starts with <polyline.  Are you sure its not wrapped its not also wrapped with an svg tag as well? 

Also, does the workaround I suggested work (setting neat:0 in trackList.json)? 

Nathan

**Comment by childers** [comment]
looking at this more, it looks like the polyline element is a subfeature of the jbintron feature, and I think you're right that it is somehow inheriting the neat feature attributes without overriding the original HTML feature attributes (at least for intron). Looking at the edit config panel, intron is set to null, and it looks like it is an issue of the renderClassName : "gray-center-10pct", that is getting us.  setting that to null fixes this issue.

So where is the best case to fix this? In how it is passed to Apollo, or should Apollo overrode the renderClassName in these features too?  

Our other tracks use    "renderClassName": "gray-center-30pct", and these get rendered ok.  Changing the BLAST track to that renderclass makes the features look ok (and conversely changing a normal html track to grey-center-10pct causes double introns. What's going on here?
![apollo206-wierdness](https://cloud.githubusercontent.com/assets/421248/21727823/1c78e184-d411-11e6-93b3-2af7cb1e5cf8.png)

 




```shell
...
...
   "renderClassName": "gray-center-10pct",
    "subfeatureClasses": {
      "UTR": "webapollo-UTR",
      "CDS": "webapollo-CDS",
      "exon": "container-100pct",
      "intron": null,
      "wholeCDS": null,
      "start_codon": null,
      "stop_codon": null,
      "match_part": "blast-match_part"
    }
...
...
```

**Comment by childers** [comment]
Will try setting neat:0 now

**Comment by childers** [comment]
ok, BLASTDraggableFeatures look like before, but not the other htmlDraggableFeatures?
![apollo206-weirdness2](https://cloud.githubusercontent.com/assets/421248/21727919/9a4ef5b2-d411-11e6-91fc-b29c94612fea.png)

**Comment by childers** [comment]
Even more strange, zooming out causes the neat intron to reappear.

**Comment by nathandunn** [comment]
Wait, they re-appear on the BLAST results?

**Comment by nathandunn** [comment]
> Our other tracks use "renderClassName": "gray-center-30pct", and these get rendered ok. Changing the BLAST track to that renderclass makes the features look ok (and conversely changing a normal html track to grey-center-10pct causes double introns. What's going on here?

Does setting the renderClassName for all to "gray-center-30pct" fix your problem without having to set it to ```neat:0``` ?   

If that is the case, we can call this a workaround and we can open an issue in JBrowse.

**Comment by childers** [comment]
Even in a private window there must have been some artifactual caching.  It is still there in the BLAST track, adn I have neat introns on my htmlFeatures.

I'll need to update the URL in my addStores call, and will update again. I'm ok with this as a workaround for now. 

Do you know why 30pct works and 10pct doesn't

**Comment by childers** [comment]
changing the URL to 30pct removed the straightline intron, but the neat introns sometimes won't show up until I change the view.  Is it waiting for a change before drawing (or redrawing)?

**Comment by childers** [comment]
Oh, this is with "neat" : 0,  in various parts of my trackList.json.  Where does it need to go to work?

**Comment by childers** [comment]
And it does not have this behavior in Chrome, just Firefox.

**Comment by nathandunn** [comment]
Ohh . . interesting WRT to FF.  Private windows can still cache.  I just know in the network tab of the dev mode, there is a "disable cache" selection that if I'm on the network tab is selected does not use the cache.   Maybe something the same in FireFox?   

Overall, though, not sure why it would be different.    

I guess, I would open up a JBrowse issue referencing this issue and explaining the issue to do with the styling (and it occurring on FF and not Chrome).

**Comment by childers** [comment]
Updated the django app to write the addTrack renderclass as 30pct, and built it on dev. 

I bet you are right about there being some type of local caching on the private FireFox window. I closed and opened a fresh private window, then ran a search and checked the links. In both FireFox and Chrome, the neat features rendered a strange artifact in intronless genes. I will post that to JBrowse.
