### ISSUE TITLE
Intron persists in UcA track if a single exon

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#1417]
Possibly related to https://github.com/GMOD/jbrowse/pull/834 and https://github.com/GMOD/Apollo/issues/1415. Creating this issue in Apollo rather than Jbrowse since it seems to be Apollo-specific. 

I drag a model into the UcA:
![set-up-model](https://cloud.githubusercontent.com/assets/5487172/21728790/3637b516-d405-11e6-97e7-ff168f7926ab.png)

Remove 5' exons. The remaining 5' intron persists (but it's longer than it was before).
![deleted_exons](https://cloud.githubusercontent.com/assets/5487172/21728797/3f27b9aa-d405-11e6-8ccb-799684d6fa8c.png)

If you create another model that overlaps with the spurious intron, the model appears to be connected (which it shouldn't), but Apollo still treats them as separate models (as it should). Also, there's an intron line going all the way through the 5' model.

![added-exon](https://cloud.githubusercontent.com/assets/5487172/21728809/50457dda-d405-11e6-8ea2-3a844350f1a9.png)

If you zoom out, the two models look separate again (good).
![zoomed-out](https://cloud.githubusercontent.com/assets/5487172/21728814/584c6a66-d405-11e6-90db-894366f3fb67.png)

The gffs of these models look fine, btw.

**Comment by nathandunn** [comment]
Confirmed that we get this if we just add a single exon as part of a transcript.  It is triggering this code in NeatHTMLFeatures, which is usually correct:

```
 if(subNodes.length<2){
                // apply introns to all feature tracks
                var subFeatureIntron = query('div.feature-render',featureNode);
                if(subFeatureIntron){
```

The problem seems to be that it renders this for ALL subFeature types, which is probably the error.

**Comment by nathandunn** [comment]
This is a JBrowse error, but is hopefully pretty fixable.

**Comment by childers** [comment]
I saw this in the evidence pane, and opened an issue 
https://github.com/GMOD/jbrowse/issues/837

**Comment by nathandunn** [comment]
I'll take a look.  I see the problem . . . now if I can just find a solution ;)

**Comment by nathandunn** [comment]
weird, in JBrowse, when I do this query:

                var subFeatureIntron = query('div.feature-render',featureNode);

I get nothing. 

In Apollo I get this:

    the subFeatureIntron is:  ```feature-render gray-center-30pct```

**Comment by nathandunn** [comment]
- [ ] fix in Apollo case (jbrowse or apollo fix)
- [ ] bump jbrowse / apollo version 
   - [ ] merge / bump projection downstream

**Comment by nathandunn** [comment]
This garbage code fixes it badly in Apollo:

                if(subFeatureIntron && subFeatureIntron.length>0){
                    if(subFeatureIntron.length==0 || (subFeatureIntron.length==1 &&  subFeatureIntron[0].className.indexOf("gray-center-30pct")<0 && subFeatureIntron[0].className.indexOf("annot-render")<0)){

We could leave the ```annot-render``` in there, as its very specific.  ```gray-center-30pct``` is both specific and problematic.

**Comment by nathandunn** [comment]
Adding an "annot-apollo" class:

                if(subFeatureIntron.length==0 || (subFeatureIntron.length==1 &&  subFeatureIntron[0].className.indexOf("annot-apollo")<0 && subFeatureIntron[0].className.indexOf("annot-render")<0)){

**Comment by nathandunn** [comment]
@mpoelchau  / @childers  This should be working now.  Thanks for catching it.  Hard to believe we hadn't found it earlier.   You can check our staging server (I'll send it in an email).

**Comment by nathandunn** [comment]
You'll have to do a clean-all as I updated the jbrowse version.  It looked like it wasn't an issue with JBrowse, just some apollo weirdness.

**Comment by childers** [comment]
@nathandunn Thanks! I'll take a look at this now.
