### ISSUE TITLE
Authentication error with galaxy tools + remote_user

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#1423]
Hello,
I'm playing with apollo 2.0.5 in docker, with the galaxy tools, and also the remote_user auth (2017 is fun!) and I get this error in the logs of some galaxy tools (namely, list organisms for example):

`{u'error': u'No signature of method: org.apache.shiro.authc.UsernamePasswordToken.call() is applicable for argument types: (org.apache.shiro.web.servlet.ShiroHttpServletRequest) values: [org.apache.shiro.web.servlet.ShiroHttpServletRequest@6118aeb8]\nPossible solutions: wait(), any(), wait(long), any(groovy.lang.Closure), each(groovy.lang.Closure), clear()'}`

By chance do you see what could be the cause?

**Comment by nathandunn** [comment]
@abretaud  Thanks for catching and fixing!
