### ISSUE TITLE
setting exon details in details panel fails to set transcript boundaries

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1428]
<img width="1048" alt="screen shot 2017-01-11 at 11 50 33 am" src="https://cloud.githubusercontent.com/assets/751274/21863932/403b6786-d7f4-11e6-80ae-9604b2eab7a9.png">

**Comment by nathandunn** [comment]
This would have been in 2.0.5 originally.

**Comment by nathandunn** [comment]
Oddly this DOES sometimes work, so not sure what exactly the problem might  be for this specifically.  Should always call the same method as set exon boundary.

**Comment by nathandunn** [comment]
I think that this is a visualization artifact of neat features, but it does work.

**Comment by nathandunn** [comment]
W/o neat features we see this:

<img width="246" alt="screen shot 2017-01-14 at 12 01 33 pm" src="https://cloud.githubusercontent.com/assets/751274/21957693/3b6b612a-da51-11e6-84a0-5e84f74d21cf.png">

This is correct I believe, unless we should alter the transcript location as well.  

@monicacecilia ??

**Comment by nathandunn** [comment]
@monicacecilia  So its explicitly just setting the feature location, but not calling setExonBoundary (so, no history or re-calculation of anything).  I think this was by design, but I wanted to confer.   I feel as though its not earth-shattering, but not sure if we should leave it open to think about the specific behavior.

**Comment by nathandunn** [comment]
We chatted and agreed that the current behavior is wrong.  We should simply use the current "setExonBoundary" code in RHS.

**Comment by nathandunn** [comment]
@deepakunni3  Is it possible for you to take a look at this?  We just need to change the call to use "setExonBoundary".    If you're deep in variant annotation, though, I can do it instead.   It shouldn't be too bad, but I was going to try and finish up #1433.

**Comment by deepakunni3** [comment]
@nathandunn I'll look into it.
