### ISSUE TITLE
TestScript updates need clarification

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1435]
@nathandunn some of your updates to the [TestScript](https://github.com/GMOD/Apollo/blob/master/docs/TestScript.md) need clarification. 

In docs/TestScript.md

- <code>1.3) Check that the organism preference is preserved only on a single browser tab.</code>
Why should the preference only be preserved on a single browser tab? If I open five tabs to look at five different _Reference Sequence_ from the same organism, I want to keep the organism preserved and not have to change it every time. This is incorrect. 

- <code>1.4) If two organisms have the same scaffold name, switch between those organisms after providing annotations (if they are the same).</code>: this may be a colloquialism of yours that I simply don't understand. I cannot really discern what is the condition here: "if two organisms have the same scaffold name". Are you missing a plural somewhere? Do you mean to say "if the naming conventions for _Reference Sequence_ are the same for two different organisms, and as a result two different organisms have separate _Reference Sequences_ with the same name"?

- <code>1.4.2) Use the Sequence Panel to confirm that scaffolds on a particular organism only belong to that organism.</code>: this needs more details. 

- <code>1.4.4) Use the Annotator Panel navigate to, to confirm that scaffolds on a particular organism only belong to that organism.</code>: There is a typo here. "navigate to" what?

-

**Comment by nathandunn** [comment]
Okay.  Ill take a look.  Things make so much more sense in my head.  I'll probably create a PR for this for you to approve.

**Comment by monicacecilia** [comment]
@nathandunn Also, in _13.1.2.1)_, there are two issues: 
- "explicity" should be "explicitly". 
- The text reads: "On _blur_ confirm that a change was made for a legitimate value". "_blur_"?

**Comment by monicacecilia** [comment]
@nathandunn Also, in _13.1.2.2)_: 
- "Repeat for a non-coding transcript and pseudogene."  Should be reworded, e.g.: "Repeat for pseudogenes and non-coding RNAs".

**Comment by monicacecilia** [comment]
In _13.2.1)_:
- "fromthe" typo.

**Comment by monicacecilia** [comment]
In _13.2.3)_:
- "Check that clicking on the show native tracks icon properly toggles the native tracks". Should be updated to: "Check that you can toggle the visualization of JBrowse ("native") Tracks using the "Show JBrowse Track Selector" button. 
- See also #1452

**Comment by nathandunn** [comment]
I'll fix the 13.2.3 in #1452.
