### ISSUE TITLE
NeatFeatures creates hiccups when displaying RNAseq reads

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1436]
The regions connecting two fragments of the same read in the _Evidence Tracks_ region of the browser is having difficulties coping with the change when trying to display RNAseq reads aligned to a gene model. 

At first, the usual 'lighter blue' connections are displayed, after scrolling or zooming, the new thin, black lines representing the 'introns' are displayed. 

I don't like this modification, and in my opinion, it loses some of the usefulness of the display of RNAseq reads. It is not a show stopper, but we should talk more about how this is being visualized. 

 Before (and when first loaded):
<img width="850" alt="screen shot 2017-01-13 at 3 47 40 am" src="https://cloud.githubusercontent.com/assets/1714621/21929158/d4e3060a-d943-11e6-81a9-ffb618beb3a2.png">

Now:
<img width="871" alt="screen shot 2017-01-13 at 3 48 00 am" src="https://cloud.githubusercontent.com/assets/1714621/21929164/d9a4149a-d943-11e6-8931-08e82331a823.png">

**Comment by nathandunn** [comment]
This will be urgent if NeatFeatures becomes default.

**Comment by nathandunn** [comment]
Removing from 2.0.7 as neat features is not the default.
