### ISSUE TITLE
UTR regions in NeatFeatures should be clear, not white.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1437]
@nathandunn @enuggetry  

The current representation of UTRs is not yet optimal, neither on the evidence tracks nor on the User-created Annotations area. It is specially bad when working on the 'dark' color scheme. They should either be clear boxes with outline in the color of the rest of the feature , or conserve the 'lighter color, thinner box' that we had before. 

This looks quite bad: 
<img width="903" alt="screen shot 2017-01-13 at 9 40 49 am" src="https://cloud.githubusercontent.com/assets/1714621/21940453/4cc9aebe-d979-11e6-985b-bdd9f5484161.png">

This was better (current features):
<img width="901" alt="screen shot 2017-01-13 at 10 00 11 am" src="https://cloud.githubusercontent.com/assets/1714621/21940506/837bc730-d979-11e6-8555-28b88ed05aea.png">

We need to fix this before releasing. This _is_ a show-stopper.

**Comment by monicacecilia** [comment]
Also, the new introns are very difficult to see in the 'Dark' schema.

**Comment by monicacecilia** [comment]
Sometimes these new introns are not displayed at all (see gene model in OGS), and only appear after refresh, at times just after dragging the _Evidence Panel_:
<img width="764" alt="screen shot 2017-01-13 at 2 04 55 pm" src="https://cloud.githubusercontent.com/assets/1714621/21947308/5b2f84cc-d999-11e6-8839-a044409ae5d2.png">

**Comment by enuggetry** [comment]
I think I was originally trying to model it after this:
![introns](https://cloud.githubusercontent.com/assets/10053377/22217080/7a8bcbcc-e156-11e6-96fd-ccde6980fc28.png)

**Comment by enuggetry** [comment]
After updating NeatHTMLFeatures from here:
https://github.com/GMOD/jbrowse/commit/29795a1bbb8da4706eba2b0f73724ac1b3e1e4e6

And using this
https://github.com/enuggetry/Apollo/blob/master/client/apollo/css/maker_darkbackground.css

**Comment by monicacecilia** [comment]
This is still NOT being displayed correctly. I see that NeatFeatures made it back into 'default' and the problem with the introns has been solved. 
HOWEVER, the UTRs are still white and they should be clear. This is NOT optimal.

**Comment by nathandunn** [comment]
I think this is just the demo server for a particular set of tracks I was no doubt playing with.  The default is still *not* to have the neat features on, so it should probably be closed.  I added the requirement of removing this from the demo server for #1662.    That being said, this bug should still stay.   I removed the 2.0.7 milestone, which I think is the correct thing to do.
