### ISSUE TITLE
Blat search tool caused track features to disappear, then did not return any results.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1438]
There are two errors here: 
- First, after using the Blat tool from the 'Search sequence' option in the 'Tools' top-level menu, the genomic elements in the 'OGS  v3.2' track disappeared when navigating to the different _Reference Sequences' listed in the results.

This is what the tracks looked like after navigating to one of the results in the original list of hits (note that the genes in the OGSv3.2 track were still loading. The reads on the XY coverage plot track also disappeared. They actually disappeared from this and all other _Reference Sequences_):
<img width="1440" alt="screen shot 2017-01-13 at 10 26 10 am" src="https://cloud.githubusercontent.com/assets/1714621/21941485/cf49aa02-d97d-11e6-8c12-eeda91e019bf.png">

For comparison, this is what that region looks like (without Blat search results table, and after refreshing): 
<img width="1084" alt="screen shot 2017-01-13 at 10 53 21 am" src="https://cloud.githubusercontent.com/assets/1714621/21941624/8a6faae8-d97e-11e6-95a2-ef423ff77abb.png">

- Second, the Blat tool stopped working and none of the sequences I used returned any matches. 
This is the 'list of results' after I repeated the search. This is incorrect, as I know there are gene models predicted in this region: 
<img width="985" alt="screen shot 2017-01-13 at 10 27 25 am" src="https://cloud.githubusercontent.com/assets/1714621/21941514/ea211da6-d97d-11e6-96cd-aa83ef36d7f2.png">

**Comment by nathandunn** [comment]
@monicacecilia  Shoot, do you have the screen shots.  They didn't seem to have uploaded.

I retested the BLAT a bit and I wasn't getting any errors.   If you have regions or sequences I can retry it as well.

**Comment by nathandunn** [comment]
If you are seeing the images, could just be CDN problems that will resolve.

**Comment by nathandunn** [comment]
CDS problem resolved.

**Comment by nathandunn** [comment]
I wasn't able to reproduce.  I know if you are on a slower connection, returning the heatmap data can be slow and slightly blocking.

**Comment by nathandunn** [comment]
My theory is that BAM files do this correctly with indication of loading and not blocking and BW files do not.   If that is true, it would be possible to copy this behavior.  However, I don't think that this behavior is new from even WA1.

**Comment by nathandunn** [comment]
Talked with @monicacecilia   She is going to retest on staging and add brand-new URL's if there is anything wrong.

**Comment by nathandunn** [comment]
@monicacecilia  Just as an FYI, I was on icebox the other day and there was an errant BLAT job just spinning at 100%.

**Comment by nathandunn** [comment]
@monicacecilia  if you have a chance to retest this, this morning, that would be great.  Thanks.

**Comment by monicacecilia** [comment]
Re-tested. All working as expected now. Yay! 💃
