### ISSUE TITLE
Description for documentation page in readthedocs is out of date.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1439]
When you hover over the name of the tab while looking at documentation pages in readthedocs, the mouse displays a name with the wrong version. It reads "2.0.4", but it is indeed the one for the latest version:

<img width="624" alt="screen shot 2017-01-13 at 11 00 38 am" src="https://cloud.githubusercontent.com/assets/1714621/21941919/d48d4210-d97f-11e6-8f4b-0c391ea30346.png">

Low priority, but good to have on our radar.

**Comment by nathandunn** [comment]
Looks like it is some sort of bug on there end as I was positive I'd fixed this already:

<img width="857" alt="screen shot 2017-01-14 at 8 48 35 am" src="https://cloud.githubusercontent.com/assets/751274/21956466/48778292-da36-11e6-943f-34078585502a.png">

**Comment by nathandunn** [comment]
Let me try rebuilding it and see.

**Comment by nathandunn** [comment]
So, the fix is that (from the commit) is that docs/setup.py needs to be fixed.
