### ISSUE TITLE
put admin panel in an iframe

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1443]
Putting the admin panel in an iframe would do a couple of things:

1 - simplify the admin panel integration on that page
2 - make it easier to add more panels
3 - eliminate problems with library  / css inclusion that we seem to get when we decide to include / not-include that panel

Everything appears to be working now, but it will be a nice (and relatively painless) change in the future.

**Comment by monicacecilia** [comment]
"relatively painless" --> famous last words.
