### ISSUE TITLE
Username still constrained to email in registration screen

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1444]
<img width="378" alt="screen shot 2017-01-17 at 3 13 46 pm" src="https://cloud.githubusercontent.com/assets/421248/22038495/652b770a-dcc9-11e6-951b-f96e11d52c60.png">

**Comment by childers** [comment]
Also see the current API tagging it as type email
http://icebox.lbl.gov/Apollo2/17314266821869142146/jbrowse/web_services/api
<img width="820" alt="screen shot 2017-01-23 at 11 07 36 am" src="https://cloud.githubusercontent.com/assets/421248/22211799/494ee7f0-e15c-11e6-838f-396b014cf0b1.png">

**Comment by nathandunn** [comment]
Yeah.  Email is still the preference, but there are no email constraints.  I'll clarify this later.  If you want to issue a PR with any of the fixes, that would be great, otherwise it will come in with 2.0.7 or the tail-end of 2.0.6.

**Comment by nathandunn** [comment]
@childers  I'll update the TODO:

- [ ] remove email constraint on register panel
- [ ] update constraints to allow for the username to be an email or string username (or just mention as "username")
- [ ] re-run api rest-doc

**Comment by nathandunn** [comment]
I believe that this is fixed
