### ISSUE TITLE
Edition restricted to the annotations owned by the annotator OR inform the owner when an annotation is modified

### ISSUE THREAD

**Issue by loraine-gueguen** [GMOD/Apollo#1447]
This is a need from one of my users: she would like that the annotators could not edit the annotations created by someone else, to prevent conflict. 

Another way to handle this, in my opinion, would be to inform the owner (by email or notification inside Apollo) when one of his annotation is modified. This way, it would leave the full collaborative perspective (any annotator can edit any annotation). Moreover, we can imagine that any annotator would have the opportunity to subscribe to the annotations he is interested in to receive notifications when these annotations are modified.

**Comment by nathandunn** [comment]
@loraine-gueguen  I'm going to close this in favor of #1260 as I think its the same issue.  I'll reply in more detail in those threads and copy this valuable discussion there.   Thank you for raising it.
