### ISSUE TITLE
chado export plugin

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#145]
need to write a plugin to export chado
- need to check the version to double-check and otherwise annotate
. . this is a table in chado_props

**Comment by nathandunn** [comment]
From #50 - @erasche 

If there's any way to support multiple organisms from a single chado database with as little webapollo configuration required as possible, that would be extremely useful to us.

We stuff many viruses in a single chado instance (the overhead would be silly for <100kb genomes to have multiple chados).
We plan to add more organisms to a chado instance
So if we can do that without reconfiguring webapollo, that would be ideal. I understand this isn't everyone's use case, so can be filed under "feature requests" :)

**Comment by nathandunn** [comment]
- [ ] create a default "config" (optional) . .  on/off . . and default username, database, url params (w/ test)
- [ ] added per organism export 
- [ ] add export service:
   - [ ] export existing features and modify to existing schema (Sequence -> SourceFeature) . . etc.

**Comment by nathandunn** [comment]
Look at using schema spy or similar to handle schema alterations . . esp. between chado versions

**Comment by nathandunn** [comment]
FYI @scottcain 

Steps:
- dump
- load into new DB
- run schema Diff
- data map between two (and before diff?)

Other considerations:

*FEATURE*
- className -> cvTerm
- sequence alteration, do we handle it differently?
- map symbol to synonym (Scott says this) or Feature Property (Nathan thinks this was the historical)
- description -> FeatureProperty 

*FEATURE_LOCATION*
- sequence_id -> source_feature

*SEQUENCE*
- add to feature table, set "organism" foreign key there
- add SO

**Comment by nathandunn** [comment]
http://www.liquibase.org/documentation/diff.html

https://www.jetbrains.com/datagrip/

**Comment by scottcain** [comment]
The rtree indexes that can be removed from Chado are:

ALTER TABLE featureloc DROP INDEX binloc_boxrange;
ALTER TABLE featureloc DROP INDEX binloc_boxrange_src;

(Generally, you'd want these indexes in Chado as it will make range queries faster on large featureloc tables, but if rather than fixing the missing functions for a test database, you can do this.)

**Comment by nathandunn** [comment]
Note to self ..  need to do 'grails maven-install' from plugin and the use the local to point

**Comment by nathandunn** [comment]
- [ ] fix relationships from autogeneration
- [ ] create a way to map remote data 
- [ ] double-check metadata
- [ ] stub "moving" code in service class
- [ ] add integration tests

**Comment by nathandunn** [comment]
Add multi-tenant . . . . for multiple schema:

compile "org.grails.plugins:multi-tenant-single-db:0.8.3"
 Documentation

**Comment by nathandunn** [comment]
- [multiple datasources](http://grails.github.io/grails-doc/2.4.5/guide/conf.html#multipleDatasources).  The hard part with this is that they may be configured to the same place . . . esp if grails.   
- Namespace would be a better option.  Everything goes to the same place.   However, they *could* go to a separate place.    

So, let's do both.    Add namespace and add have them go to separate databases so that configuration can be "simple"?!?  Will probably need some feedback on the best strategy for this.

**Comment by nathandunn** [comment]
Getting this bug on successful import:
  
```Caused by CacheException: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: DefaultConfigurationSource [ ehcache.xml or ehcache-failsafe.xml ]
```

**Comment by nathandunn** [comment]
Review audit-log plugin (and others) to see how they deal with this . . . or just bring in Chado separately.

**Comment by nathandunn** [comment]
Related to #841 (staging)

**Comment by nathandunn** [comment]
Note can use chado exports from different organisms (pom, flybase, etc.)

**Comment by nathandunn** [comment]
http://gmod.org/wiki/Chado_Tables

. . note that a lot of tables included are just not there

**Comment by nathandunn** [comment]
The best official reference is the github repository and combing through the SQL :-(
Chado v1.31 (most recent): https://raw.githubusercontent.com/GMOD/Chado/master/chado/schemas/1.31/default_schema.sql

The Chado tables documentation has not yet been updated so there are some linking tables and what-not in the the SQL that is not on the page you indicated… Personally I would use the Chado Tables page as your first step and then before ruling anything out, I would check the SQL.

**Comment by nathandunn** [comment]
Meeting notes from Tripal meeting for @monicacecilia :

- a lot of people want Apollo integration with Tripal/Chado
- we need some way to do “checks” / staging on the Tripal or the Chado side

- Tripal 3 might be able to build an Apollo module . . . conversely we can export from Apollo into any arbitrary database

Maybe we can review on Thursday . . . but I think we have other stuff in the queue.  I won’t forget either way. 

Related issues:
- https://github.com/GMOD/Apollo/issues/145
- https://github.com/GMOD/Apollo/issues/841

**Comment by nathandunn** [comment]
@deepakunni3   We can review this (with 2.0.3) when you're ready.   I talked with @monicacecilia  and some of our other users and this is definitely a priority.    I've already started on it here:  

https://github.com/GMOD/Apollo/tree/chado_export_v1

but there is definitely more to do.

**Comment by nathandunn** [comment]
Fixed in #932

**Comment by nathandunn** [comment]
@monicacecilia  Not sure how you want to test this, or if we should just close this.

**Comment by monicacecilia** [comment]
@nathandunn will check when you push to icebox. So excited this is making such good progress. Thanks @deepakunni3!

**Comment by nathandunn** [comment]
Nothing to test (not configured on icebox and nothing to see).
