### ISSUE TITLE
Transcripts of pseudogenes should NOT have the word 'transcript' in name.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1451]
Why is the word 'transcript' appearing automatically as part of the name for the transcript of a pseudogene? (see figure below). This should not be the case. Numbering / IDs should be generated in the same way IDs are generated for transcripts of coding-genes. 

![screen shot 2017-01-24 at 3 33 04 pm](https://cloud.githubusercontent.com/assets/1714621/22271685/be5ec90e-e24a-11e6-88a6-58052af5dbd3.png)

**Comment by monicacecilia** [comment]
Actually, the same seems is true for all other annotated genomic elements. 
I don't recall when this change was introduced. Refreshers? Why? It should not be the case.

**Comment by nathandunn** [comment]
@monicacecilia   To clarify:

- gene and mRNA naming is correct 
- [ ]  all non-coding transcripts should be named as mRNA's with their corresponding pseudogenes being names similar to a regular gene
- transposable_elements and repeat_region should continue to be named as they are currently (basically just getting a hash)

Not sure that any of this is new, but I agree that the "transcript" suffix is weird and should be fixed.

**Comment by deepakunni3** [comment]
@nathandunn I agree. I can work on this and probably add some tests as well to make sure our naming service generates the proper name formats.

**Comment by nathandunn** [comment]
Awesome thanks @deepakunni3
