### ISSUE TITLE
'Show JBrowse Tracks' or 'Show native tracks' option not visible.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1452]
The option to toggle viz of JBrowse tracks has disappeared. 
Is it a button now? (since when?!) 
![screen shot 2017-01-24 at 3 42 58 pm](https://cloud.githubusercontent.com/assets/1714621/22271884/cfea944a-e24b-11e6-8c38-fd1bbcb70396.png)

**Comment by monicacecilia** [comment]
I don't think this button on its own is a good way to display this information. At least during a transition period, we should also preserve the 'toggle' option from the check box with the title that was visible on the 'Tracks' tab in the _Annotator Panel_.

**Comment by nathandunn** [comment]
Thanks.  I left the hooks in there for that reason (wanted to clarify the UI-change) with you.  I'll put it in the same area with the same text, but the associated icon (to guide the eye).

**Comment by nathandunn** [comment]
- [ ] put checkbox-back button on the track panel
- [ ] update test-script to reflect both buttons are possible

**Comment by nathandunn** [comment]
> In 13.2.3):

> "Check that clicking on the show native tracks icon properly toggles the native tracks". Should be updated to: "Check that you can toggle the visualization of JBrowse ("native") Tracks using the "Show JBrowse Track Selector" button.

**Comment by nathandunn** [comment]
Now we have: 

<img width="626" alt="screen shot 2017-01-25 at 11 54 36 am" src="https://cloud.githubusercontent.com/assets/751274/22306711/12e1cd46-e2f5-11e6-9d4c-2d1fa31ac8ec.png">
<img width="604" alt="screen shot 2017-01-25 at 11 54 32 am" src="https://cloud.githubusercontent.com/assets/751274/22306710/12e0c996-e2f5-11e6-8736-b2d6c4716df7.png">
