### ISSUE TITLE
Improve display of list of Users that belong to a group 

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1454]
An esthetic preference: instead of a drop-down list as the only way to select and display users that belong to a group (see image), it would be better to list current users in a table display. Include also the option to remove them from the group.
![screen shot 2017-01-24 at 4 14 35 pm](https://cloud.githubusercontent.com/assets/1714621/22272682/6d5d9b24-e250-11e6-8c1f-71bc4f251921.png)
This is not urgent.

**Comment by nathandunn** [comment]
Agreed.
