### ISSUE TITLE
Permission boxes should only ever be single-selection

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1455]
To follow the style of the other boxes in the table, the selection boxes under the 'Read' column in the User details table should also be aligned left. It currently is aligned right. 

![screen shot 2017-01-24 at 4 13 11 pm](https://cloud.githubusercontent.com/assets/1714621/22272729/cf554c00-e250-11e6-9016-dd8265f18458.png)

**Comment by nathandunn** [comment]
From this: https://gwtbootstrap3.github.io/gwtbootstrap3-demo/#buttonGroups

<img width="403" alt="screen shot 2017-01-25 at 9 49 57 am" src="https://cloud.githubusercontent.com/assets/751274/22302443/aec67b74-e2e3-11e6-90f3-b1c2728f3a00.png">

**Comment by monicacecilia** [comment]
Ah. That. Yes.
