### ISSUE TITLE
New 'Statuses' do not appear in 'Information Editor' box without refresh.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1456]
Another surprise. 

Creating new 'Statuses' seems to create conflicts in the main annotation window. 

The first time I created a new status, the _Information Editor_ was not able to retrieve information about the genomic element I was annotating, and all other functions in the _Information Editor_ were lost. I was unable to add PubMed IDs, for example. Also, all identifiers were emptied from the window.

![screen shot 2017-01-24 at 4 21 27 pm](https://cloud.githubusercontent.com/assets/1714621/22272881/e5eba22e-e251-11e6-9cde-ed541e618c74.png)

The second time I created a new status, the _Information Editor_ did not get updated with the new option in any of the already existent annotations. Creating a new annotation did not help either. 

The problem is only resolved after 'refreshing' the page. 

Possible solutions: 
- push refresh on main annotation window after adding a new 'Status'. 
- better documentation for the new feature. This needs to be added, perhaps under descriptions for [Canned Elements](https://github.com/GMOD/Apollo/blob/master/docs/CannedElements.md) or elsewhere appropriate in documentation.

**Comment by nathandunn** [comment]
I think that it might need better documentation.    The statuses (like the Canned Elements) are meant to be somewhat non-dynamic as they shouldn't change that often.

**Comment by monicacecilia** [comment]
So no intention to push a refresh?

**Comment by nathandunn** [comment]
I wouldn't.  For something that might change 3 times in a year, I don't think it makes much sense.

**Comment by monicacecilia** [comment]
Sent email. 
need to document. need to update name to 'Canned Statuses' if it is to go under 'Canned Elements'.

**Comment by nathandunn** [comment]
@monicacecilia  Saw email.  I can do that, though I'm not sure its necessary.  If you feel its necessary, let me know which places you would want it changed.

**Comment by monicacecilia** [comment]
Updated doc with information on Statuses.
