### ISSUE TITLE
Cannot escape 'right click menu' if pulled with keyboard + mouse command

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1465]
Cannot escape 'right click menu' if pulled with keyboard + mouse command

Tested on Chrome, Firefox, and Safari. 

To reproduce: 
1. Use 'Control' key (on Mac) or corresponding key for pulling 'right click' menu, using a combination of mouse + keyboard gestures. 
2. Results: a) None of the functionality in the menu is executable. 
3. Results: b) Right click menu does not go away after clicking outside or using 'esc' key. Curator must either refresh page / or pull right click menu elsewhere using only the mouse.  

Error on Console: 

```
Uncaught TypeError: Cannot read property 'feature' of undefined
    at Object.updateSetTranslationStartMenuItem (AnnotTrack.js:5102)
    at Object.updateMenu (AnnotTrack.js:5000)
    at Object.annot_context_menu.onOpen (AnnotTrack.js:4807)
    at Object.open (popup.js:362)
    at Object._openMyself (Menu.js:349)
    at Object.<anonymous> (Menu.js:278)
    at lang.js:375
    at Object.<anonymous> (_WidgetBase.js:1174)
    at lang.js:375
```

**Comment by nathandunn** [comment]
@monicacecilia  Are you saying when you get the popup menu it fails to function or close?  I'm not seeing this [here](http://icebox.lbl.gov/Apollo-staging/annotator/loadLink?loc=Group9.10:4309208..4368951&organism=3836&tracks=Official%20Gene%20Set%20v3.2,Augustus%20Set%2012).  

<img width="379" alt="screen shot 2017-01-31 at 3 49 36 pm" src="https://cloud.githubusercontent.com/assets/751274/22489547/eae28ff6-e7cc-11e6-8c6a-4c4a4280953c.png">

Perhaps you have another link to share that would reproduce this?  Thanks.

**Comment by monicacecilia** [comment]
@nathandunn When you get the popup menu as a result of combining keyboard + mouse gestures. NOT when using only mouse gestures.

**Comment by monicacecilia** [comment]
@nathandunn and yes, I am testing on staging.

**Comment by nathandunn** [comment]
@monicacecilia  Hmm . . I've tried a few things with no results.  Could you give me a combo of things to try to reproduce?

**Comment by monicacecilia** [comment]
@nathandunn See 'To reproduce' above.

**Comment by deepakunni3** [comment]
@monicacecilia Thanks for the steps to reproduce.

I can confirm that this is reproducible. 

The main issue is when using 'CTRL + mouse click' to trigger a right-click behavior, the annotation is never selected and yet the menu opens up. Hence, clicking on any of the operations from the menu yields no response because the selection manager is empty.
