### ISSUE TITLE
double-click on transcript should navigate but NOT close the transcript / gene

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1467]
There is one unwanted behaviour here, though. When double-clicking on the child object (e.g. transcript) of the annotation listed in the 'Annotations' tab, under 'Name', the expanded annotation collapses back. Of course, this is not the case for those genomic elements without children annotations (e.g. repetitive regions, TEs).

It only happens to the annotation that the curator is navigating to. The other children annotations remain expanded.

To reproduce:

Double click on the 'Name' of an annotation from the list in the 'Annotations' tab.
Double click on the the child annotation (e.g. transcript)
Result: Apollo will navigate to the location of that child annotation, but the child annotation will be collapsed back and only parent annotation is visible.

**Comment by nathandunn** [comment]
Some ideas to mitigate:

- toggle only open on double-click? 

- can we use the “selected”? from the HTML to do the same analysis?
  - add an extra HTML element for close (if toggle only open on double-click)?

- change the open-close icons to look like open-close icons (or left and down)

**Comment by nathandunn** [comment]
If I can't get it to work as desired.  Talking with @monicacecilia we decided:

- remove double-click navigation
-  add a "goto" icon

and either way:
- change the open-close icons to look like open-close icons (or left and down)

**Comment by nathandunn** [comment]
<img width="626" alt="screen shot 2017-02-01 at 12 08 53 pm" src="https://cloud.githubusercontent.com/assets/751274/22524313/906e31a0-e877-11e6-9121-1435370463fe.png">

Using this:

It occurs to me, though, that we could just use the font-awesome calls from GWT.  

https://en.wikipedia.org/wiki/List_of_Unicode_characters#Arrows

**Comment by nathandunn** [comment]
<img width="447" alt="screen shot 2017-02-01 at 12 14 57 pm" src="https://cloud.githubusercontent.com/assets/751274/22524439/1e7a0884-e878-11e6-86f2-e2535b33550e.png">

**Comment by nathandunn** [comment]
So pretty:

<img width="402" alt="screen shot 2017-02-01 at 12 22 09 pm" src="https://cloud.githubusercontent.com/assets/751274/22524693/1b425d5a-e879-11e6-81e7-cb1313cc62f8.png">

**Comment by monicacecilia** [comment]
@nathandunn brilliant. thanks!

**Comment by monicacecilia** [comment]
The current behaviour of closing the transcript on double-click is still not optimal. But it will do. 
It's a good thing that double click no longer navigates.
