### ISSUE TITLE
Remote_user not catched everywhere

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#1468]
I have a small problem with remote_user auth. On a freshly opened browser (no cache), if I go first to 
apollo homepage (http://fqdn/apollo/), I get logged in correctly.

If I go first to other pages like this:
http://fqdn/apollo/annotator/loadLink?loc=scaffold2%3A172393..195794
http://fqdn/apollo/annotator/loadLink?organism=xxx
I get redirected to http://fqdn/apollo/auth/login, even though I entered my login/password in the browser login box

The workaround is to go first to the homepage before going to other pages.
In the apollo log I get only this when redirected to auth page:

```
2017-02-01 16:54:02,196 [http-apr-8080-exec-2] WARN  apollo.SecurityFilters  - Authentication failed
```

Do you have an idea why?

**Comment by nathandunn** [comment]
@abretaud  Thanks for letting me know.  I'll take a look.  It uses a slightly different mechanism.  However, once its set in session it should just work and  you should NEVER have to use your login.

**Comment by nathandunn** [comment]
@abretaud  Do you have a setup I could test this against?   

Is it one of these:

https://github.com/galaxy-genome-annotation/dockerized-gmod-deployment

https://github.com/galaxy-genome-annotation/docker-galaxy-annotation

**Comment by nathandunn** [comment]
Confirming that I've seen both behaviors (login on the main site, login required on the other one).

**Comment by nathandunn** [comment]
http://localhost/apollo/annotator/loadLink?loc=Group1.1:692422..771700&organism=Honeybee&tracks=

**Comment by nathandunn** [comment]
In SecurityFilters ```req``` has nothing on it so ```authToken``` is null.  

```                            
def req = request.JSON
def authToken = req.username ? new UsernamePasswordToken(req.username, req.password) : null
if (authToken && permissionService.authenticateWithToken(authToken, request)) {
```

Places to test:
- [x] http://localhost/apollo/annotator/index (works)
- [ ] http://localhost/apollo/annotator/loadLink?loc=Group1.1:692422..771700&organism=Honeybee&tracks=
- [ ] reports links
- [ ] other admin links (annotators, etc.)
- [ ] other operations (can I edit, etc).

**Comment by nathandunn** [comment]
Testing note for apache config:    ```RequestHeader append REMOTE_USER "JimBob"```

**Comment by abretaud** [comment]
I think there could be the same kind of problem for the `ping` page: every minute I see a POST query being done on apollo/ping, and it gets redirected (302) to the Login page. In Apollo logs I get `ERROR apollo.AnnotatorController  - User does not have permissions for the site`

I guess there is also the same problem when querying the api (fro example write/dowload), but I managed to get it working with the no-remote_user created on docker startup
