### ISSUE TITLE
encrypted database passwords should be the default + more doc (if not there)

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#147]

**Comment by nathandunn** [comment]
I created EncryptedLocalDbAuthentication. This can be enabled by turning on <authentication_class>org.bbop.apollo.web.user.encryptedlocaldb.EncryptedLocalDbUserAuthentication</authentication_class> and can be used with command line scripts like add_user.pl with the -e option
- Colin

**Comment by nathandunn** [comment]
@cmdcolin   
1 - upgrade the default in the XML file to use 		<authentication_class>org.bbop.apollo.web.user.localdb.EncryptedLocalDbUserAuthentication</authentication_class>
2 - set the direction to reflect the encryption
3 - mention using encrypt_user_passwords.pl for upgrading the databse if desired
4 - leave that in there commented out: <authentication_class>org.bbop.apollo.web.user.localdb.LocalDbUserAuthentication</authentication_class>

**Comment by cmdcolin** [comment]
Another change for this was added here 1c34a587a8e3d167

**Comment by monicacecilia** [comment]
Thank you.
