### ISSUE TITLE
Add function to export VCF files from UI/API

### ISSUE THREAD

**Issue by selewis** [GMOD/Apollo#1477]
This option would also need to separately export biological variations from artifactual variations (i.e. base calling assembly errors) into two separate files. Perhaps default should be to automatically generate associated VCFs whenever genomic fasta is exported.

**Comment by nathandunn** [comment]
After talking with @selewis, we thought that maybe we should in total have the following capabilities:

1. export assembly errors  in GFF col nine (currently done in column 9), @malcook has started to address this already
  - I think we need to apply the error correction when importing a GFF as well and imply that we have the same reference (or check on the incoming reference) if it comes in.
2. add a pointer to associated VCF in GFF header
3. add the ability to specifically export VCF from menu for both biological and artifactual (never mixed)
4. always export VCF with either form of the reference genome

FYI @monicacecilia  as well.

**Comment by nathandunn** [comment]
This is done already for variant annotations and sequence assembly errors
