### ISSUE TITLE
double clicking on a Name in the Ref Sequence table should not reset the table to page 1 

### ISSUE THREAD

**Issue by malcook** [GMOD/Apollo#1478]
but it does, in addition to  navigating to the click-on refseq (which is expected and desirable).

Version: 2.0.6
Grails version: 2.5.5
Groovy version: 2.4.4
JVM version: 1.8.0_111

**Comment by monicacecilia** [comment]
Hi @malcook. Thanks for the report.

@nathandunn if the name of any _Reference Sequence_ has been typed on the search box, the list does not reset. It is only resetting if navigating from pagination.

**Comment by monicacecilia** [comment]
Also, wrt there being a "loss of the Go To" button in the _Ref Sequence_ tab, @malcook perhaps you are talking about a customization you guys made? I don't recall using one in that tab before.
We have Go To buttons on the _Annotations_ tab, but not on the _Ref Sequence_ tab. 

Could you please clarify?

**Comment by malcook** [comment]
Hi @monicacecilia  - my mistake - I've re-edited the report to remove mention of goto button.  THx

**Comment by monicacecilia** [comment]
@malcook brilliant. Thanks for clarifying!

**Comment by nathandunn** [comment]
I'm not seeing this on master now, though I do remember it being a problem earlier.  Please let us know if it re-occurs.
