### ISSUE TITLE
Sequence Alteration Genomic insertion|deletion|substitution UI oddities

### ISSUE THREAD

**Issue by malcook** [GMOD/Apollo#1479]
A few remarks that might improve user experience with this activity:

- ~~TAB key does not consistently shift focus between form fields.  For example: "Add Deletion" - can not tab out of Length.~~

- [x] The value entered in the form field label "Comment" winds up appearing with the label "Justification" in the "Information" dialog.   This inconsistency should be fixed.

- ~~Once entered, it is not possible to modify them.  Possibly double clicking should allow user to modify values, including deletion length, inserted sequence, etc.~~ will fix as part of #2037 

- ~~These dialogs do not display the coordinate to which the edit is being attached and arguably should; at least _some_ visual indicate should be provided.~~

- [x] At a minimum (IMO), display of annotation Information should arguable display coordinates
![image](https://cloud.githubusercontent.com/assets/484282/22670709/0ffcaa20-ec90-11e6-8319-ffcc404706cc.png)

As it is, there is no way users can see or confirm coordinates of entered variants, either during or after data entry.

**Comment by nathandunn** [comment]
> TAB key does not consistently shift focus between form fields.  For example: "Add Deletion" - can not tab out of Length

This is a weird dojo-ism.  I've messed with the tabindex but to no avail.  Eventually this is going to go away.  However, if you find a fix, would be happy to incorporate it.

**Comment by nathandunn** [comment]
> Once entered, it is not possible to modify them.  Possibly double clicking should allow user to modify values, including deletion length, inserted sequence, etc

Will fix as part of #2037

**Comment by nathandunn** [comment]
> These dialogs do not display the coordinate to which the edit is being attached and arguably should; at least _some_ visual indicate should be provided

I'm not sure that that is entirely true (or it at least not on master as of this writing):

<img width="496" alt="screen shot 2019-02-14 at 1 03 23 pm" src="https://user-images.githubusercontent.com/751274/52817544-083dc800-3059-11e9-8cb9-6bff4f894e1c.png">


Please note #2049  though.  I'll make sure that this doesn't fail when that gets fixed, though.

**Comment by nathandunn** [comment]
Note that after the fix for #2049 . . . you can still see the appropriate red highlighting:

<img width="517" alt="screen shot 2019-02-14 at 1 16 22 pm" src="https://user-images.githubusercontent.com/751274/52818160-d168b180-305a-11e9-9b80-46dd87747613.png">
