### ISSUE TITLE
Feature Request: Route for Feature UUID -> Organism at correct location

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1481]
We're starting to use the feature UUIDs in a couple places, it would be incredibly useful to have a URL route we could construct, e.g. `https://fqdn/apollo/featureLocation/<my-uuid>` that would redirect the user's browser to the correct organism, refseq, and feature location.

**Comment by nathandunn** [comment]
@erasche  You could just overload AnnotatorController::loadLink to take a uuid instead of a location.  I haven't tested it, but something like this should work:

```
diff --git a/grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy b/grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
index 660fc45..7ad0e02 100644
--- a/grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
+++ b/grails-app/controllers/org/bbop/apollo/AnnotatorController.groovy
@@ -66,6 +66,12 @@ class AnnotatorController {
                 throw new RuntimeException("User does have permissions to access any organisms.")
             }
 
+            if(params.uuid){
+                Feature feature = Feature.findByUniqueName(params.uuid)
+                FeatureLocation featureLocation = feature.featureLocation
+                params.loc = featureLocation.sequence.name + ":" + featureLocation.fmin +".." + featureLocation.fmax
+                organism = featureLocation.sequence.organism
+            }
 
             if (!allowedOrganisms.contains(organism)) {
                 log.error("Can not load organism ${organism?.commonName} so loading ${allowedOrganisms.first().commonName} instead.")
```

**Comment by nathandunn** [comment]
I mean, if it works, definitely create a PR and we'll incorporate it.  Have to work on other stuff right now, otherwise would do myself.

**Comment by erasche** [comment]
Thanks, will pr tonigt. You rock.

Den tir. 7. feb. 2017, 22.10 skrev Nathan Dunn <notifications@github.com>:

**Comment by erasche** [comment]
Oh gosh this works flawlessly. Opening a PR.

**Comment by nathandunn** [comment]
That's hilarious.  I feel like a cowboy.
