### ISSUE TITLE
REMOTE_USER ignored on ping request

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1487]
From #1468.

https://github.com/GMOD/Apollo/issues/1468#issuecomment-278640407

> I think there could be the same kind of problem for the ping page: every minute I see a POST query being done on apollo/ping, and it gets redirected (302) to the Login page. In Apollo logs I get ERROR apollo.AnnotatorController - User does not have permissions for the site

> I guess there is also the same problem when querying the api (from example write/download), but I managed to get it working with the non-remote_user created on docker startup

**Comment by nathandunn** [comment]
FYI @abretaud

**Comment by nathandunn** [comment]
@abretaud  Were you able to test the fix in the #1492 PR?   

No worries if not.  Just wanted to know if you had were still having the same problems.

**Comment by abretaud** [comment]
Sorry, I hadn't had the time to test it, I'll get back to it soon hopefully!

**Comment by abretaud** [comment]
Finally I tested it! It seems to work as expected now, thanks!
I had another problem with multiple apollo instances with the same cookie_path, I think it could be another reason why I got this problem at first. I also fixed this on my setup now.

**Comment by nathandunn** [comment]
@abretaud  Excellent.  Thanks for finding this bug.
