### ISSUE TITLE
Gene name incrementing should use safer logic

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1491]
It appears that you suffix the name with an ascii character, and then proceed to increment that character outside of the printable character range. You might want to switch to numerical IDs.

![apollo-incrementing-bug](https://cloud.githubusercontent.com/assets/458683/22840325/f72859d0-efc4-11e6-857e-07ff1b302404.png)

This bug was discovered because for some unknown reason calls to addFeature were failing on some of our names.

- we could create gene_000
- gene_001 - gene_025 could not be created
- gene_026+ could be created

So we settled for creating them all as gene_000 and then re-naming after the fact.

**Comment by nathandunn** [comment]
This is a good point and has been driving me nuts for a long time with our large feature test loads, but typically you have to have >30 similarly named features to produce this, which is typically indicative of something else being wrong. 

Is there a normal use-case where you would have that and if so, how many similarly named features would you have? 

 You could also for the naming algorithm fairly easily (but, would rather have a sane default for doing this).

**Comment by erasche** [comment]
(busy today, hence only filing/replying quickly to this one)

> Is there a normal use-case where you would have that and if so, how many similarly named features would you have?

nope, no normal use case whatsoever. This was only noticed as part of a dirty hack.

**Comment by nathandunn** [comment]
Closing this for now
