### ISSUE TITLE
Support for track hubs?

### ISSUE THREAD

**Issue by cghiban** [GMOD/Apollo#1493]
I've tried to add a new track from a hub ( https://genome.ucsc.edu/goldenpath/help/trackDb/trackDbHub.html ) but I'm not sure this feature is supported. If not, do you have any plans on adding it?

Thank you,
Cornel

**Comment by nathandunn** [comment]
@cghiban  We don't currently support this for track hubs, though we are actively writing a grant to include this explicitly (if you have a PI looking to submit a letter of support, please contact us directly).  

Your options right now are to download and use the [ucsc-to-json.pl script](https://github.com/GMOD/jbrowse/blob/master/bin/ucsc-to-json.pl) or write your own REST wrapper.

**Comment by nathandunn** [comment]
@enuggetry  Let me know if you have anything additional to add to this.

**Comment by erasche** [comment]
Btw https://github.com/GMOD/jbrowse/issues/728

**Comment by nathandunn** [comment]
This is a JBrowse-level feature I believe
