### ISSUE TITLE
Organism list dropdown sorting bug

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1497]
Admin user (sorted):

![utvalg_012](https://cloud.githubusercontent.com/assets/458683/23033265/4d08c4bc-f46f-11e6-8fef-2f50d978ba09.png)

Regular user (unsorted):

![utvalg_013](https://cloud.githubusercontent.com/assets/458683/23033270/50a8a484-f46f-11e6-9f49-534e118a4e55.png)

I realised I wasn't ever testing things as a non-admin, so I dropped my primary user to non-admin status. Just noticed this one. We're on 2.0.6+

**Comment by nathandunn** [comment]
I think we almost need a typeahead for you with this list of organisms ;)

Good catch.

**Comment by erasche** [comment]
:tada:
