### ISSUE TITLE
Missing annotator track (sometimes)

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1498]
Reporting this in case anyone else sees it, or in case I can eventually hopefully track down and fix this.

Sometimes when loading apollo, our students are missing the annotator track. Various combinations of refreshes will generally have the track show up again. Today it happened to me for the first time so I can be sure something is actually wrong and not just normal student issues.

![utvalg_024](https://cloud.githubusercontent.com/assets/458683/23171936/07275770-f84c-11e6-8b45-36d7d277bdec.png)

As you can see, I'm logged in and accessing an organism. The track list is empty, the organism has no visible data on top of it.

![utvalg_025](https://cloud.githubusercontent.com/assets/458683/23172018/45d0d604-f84c-11e6-8f00-a8df28bb50d3.png)

This points us to a specific line of [JBrowse](https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/Browser.js#L187) where the code crashes. "Split is not a function" generally sounds to me like `thisB.config.defaultTracks`, which it is being called upon is null/undefined, but the `if` case on that same line should've prevented it.

More details as I proceed / experience the issue. No need to /do/ anything about this bug report though.

**Comment by erasche** [comment]
Update: Aha! Got you, Jbrowse!

![utvalg_027](https://cloud.githubusercontent.com/assets/458683/23174056/11a376be-f853-11e6-85e5-dc4195640b5a.png)

Well, I sure didn't see that one coming. I can PR JBrowse with an extra bit of defensive code to handle if it's already a split list.

**Comment by nathandunn** [comment]
@erasche  Merged.  I updated the default jbrowse version to reflect if you are configuring it as such.    Let me know if it can be closed.

**Comment by erasche** [comment]
thanks! Yeah, let's close this for now. I'll switch over to the new version in prod something this evening and re-open if we see it again.
