### ISSUE TITLE
gene imported as "parentgene" when opening track

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1501]
An annotated tRNA

![utvalg_039](https://cloud.githubusercontent.com/assets/458683/23236674/02767e70-f952-11e6-9159-75d215c54eba.png)

Outputs gff3 (when viewed) that contains a gene feature with a tRNA feature below:

```
##gff-version 3
##sequence-region Mijalis 1 30133
Mijalis	CPT	gene	25390	25466	.	+	.	owner=;ID=ee284a79-9ec8-47b1-9e2d-056bcd3454af;date_last_modified=2017-02-20;Name=Mijalis;date_creation=2017-02-20
Mijalis	CPT	tRNA	25390	25466	.	+	.	owner=;Parent=ee284a79-9ec8-47b1-9e2d-056bcd3454af;ID=q8bf081f-0597-44d5-8109-90ed976221e4;date_last_modified=2017-02-20;Name=Mijalis-00001;date_creation=2017-02-20
```

We copied that format when constructing the gff3 output to feed to apollo. But for now, let us look at the case of exactly copying the above gff3 (well, feature IDs were changed, just in case). So, uploading that track for visualization (File → Open track File, select "WebApollo Features", with everything left to defaults)

![utvalg_042](https://cloud.githubusercontent.com/assets/458683/23236730/4a7cec40-f952-11e6-9b2a-a94c6c34ef46.png)

Completely screws up the rendering of the feature. As you can see, it's a thin grey bar where a fat coloured one was expected. The feature info panel shows *only* the tRNA feature, the gene feature seems to have been "eaten". Most noticeably, we see a "parentgene" attribute which never existed. That should be "Parent=..."

![utvalg_041](https://cloud.githubusercontent.com/assets/458683/23236737/511bce04-f952-11e6-9966-fe743cc68c83.png)

**Comment by nathandunn** [comment]
@erasche  What are your styling options?    We usually use style -> alternateClasses -> tRNA -> className / renderClassName  

I repeated your experiment (I think) and got this:

<img width="295" alt="screen shot 2017-02-22 at 3 24 26 pm" src="https://cloud.githubusercontent.com/assets/751274/23237628/1420c5b6-f913-11e6-9790-44f45fa6e543.png">

**Comment by nathandunn** [comment]
@erasche  I removed my previous comment, which was wrong (I was changing the annotation type from an mRNA, not really applicable).    

Only the "UTR" is being rendered, so its however that is being styled.     When I perform the same operation I get the same thing, but with a purple back-bone. 

<img width="249" alt="screen shot 2017-02-22 at 3 55 16 pm" src="https://cloud.githubusercontent.com/assets/751274/23238554/5539f9f6-f917-11e6-8848-b0b6d8fd4e96.png">


You can see that if I do an mRNA with a single exon, it is definitely larger, just the UTR's are larger in the Annotation track than they are in the evidence track by default.   Or are you just wanting the purple backbone instead of gray?

**Comment by nathandunn** [comment]
The back-bone coloring for the YAL002W-00001 I re-imported from the exported GFF is from the webapollo-UTR in ```webapollo_track_styles.css```.

**Comment by erasche** [comment]
> Or are you just wanting the purple backbone instead of gray?

I'm expecting that if I copy a feature from apollo, and upload it with class "WebApollo Features", that it will be rendered identically to how apollo renders the track.

It seems like apollo fails to roundtrip data properly here, i.e. data coming from apollo cannot be visualized in apollo.

**Comment by nathandunn** [comment]
Hmm . . I think its round-tripping correctly.   The data is identical, right? 

What seems to be "failing" is that the default visualization is different between the evidence and the annotation.   Obviously, you could customize it to make it identical by default.   Is that what you are proposing? 

Would probably be editing these defaults: 

https://github.com/GMOD/Apollo/blob/master/client/apollo/css/webapollo_track_styles.css

to better correlate with this:

https://github.com/GMOD/Apollo/blob/master/client/apollo/json/annot.json

**Comment by erasche** [comment]
The data is not identical, according to the view data window in JBrowse.

See the following picture, there is *no gene feature*, only a tRNA feature shown. The "Parent" attribute has been mis-consumed as "parentgene" (or some other thing has happened).

![](https://cloud.githubusercontent.com/assets/458683/23236737/511bce04-f952-11e6-9966-fe743cc68c83.png)

**Comment by nathandunn** [comment]
@erasche  I get the same issue for mRNA's as well.  Can you confirm?    I changed the title to reflect this.  

<img width="530" alt="screen shot 2017-02-22 at 4 35 39 pm" src="https://cloud.githubusercontent.com/assets/751274/23239578/f8cbf092-f91c-11e6-9a99-b0fb5578fea7.png">


@deepakunni3  Any idea?   We can take a more in-depth look at it next week, but was wondering if you had could think of anything off the top of your head.

**Comment by erasche** [comment]
Can confirm with mRNA as well.

**Comment by deepakunni3** [comment]
@erasche Could you share the complete GFF3 for the tRNA annotation where you saw this behavior?

**Comment by erasche** [comment]
@deepakunni3 the snippet in the first post is the complete one (as given to me by the view gff3 button on the feature in apollo)

No, never had exons. parentgene definitely wasn't the cause, it seemed like a highly visible symptom

**Comment by deepakunni3** [comment]
Thats odd. Apollo (and JBrowse) expects all forms of RNA to have *at least* one exon. (unless I am missing something @nathandunn @monicacecilia )

The fact that 'View GFF3' on a tRNA annotation gave a GFF3 with records only for gene and tRNA is indicative of some issue upstream, during the process of manual annotation or perhaps the GFF3 export itself.

**Comment by monicacecilia** [comment]
- Correct, Apollo expects all forms of RNA to have at least one exon. GFF3 for tRNAs *should* include coordinates for one or more exons; keep in mind that not all precursors of tRNA have introns but some do have that one in the arm. 
- For the panels found in the 'Information Editor', tRNA *is* the 'transcript'.
- I am pulling GFF3 for a tRNA using Apollo (v2.0.6) and it looks correct to me, as it correctly displays the two expected exons in the file. Please note this is a fake tRNA, and it does not include the sequence for an anticodon arm - it's just for demonstration and it does not influence whether or not there is an exon in the file.

```
##gff-version 3
##sequence-region Group11.18 1 4736299
Group11.18	.	gene	2318880	2322497	.	-	.	owner=email@domain.com;ID=67c14ebc-a4b0-4bcd-bbc2-950363693c5e;date_last_modified=2017-02-22;Name=tRNA-test;date_creation=2017-02-22
Group11.18	.	tRNA	2318880	2322497	.	-	.	owner=email@domain.com;Parent=67c14ebc-a4b0-4bcd-bbc2-950363693c5e;ID=a25372ba-9c6a-4cac-bd17-5857a23fb77e;date_last_modified=2017-02-22;Name=tRNA-test-00001;date_creation=2017-02-22
Group11.18	.	exon	2318880	2321805	.	-	.	Parent=a25372ba-9c6a-4cac-bd17-5857a23fb77e;ID=e315b08e-4225-46c1-b09a-180120a5a5fb;Name=e315b08e-4225-46c1-b09a-180120a5a5fb
Group11.18	.	exon	2322282	2322497	.	-	.	Parent=a25372ba-9c6a-4cac-bd17-5857a23fb77e;ID=096b08db-f222-4dd1-be64-b27b32efd7b9;Name=096b08db-f222-4dd1-be64-b27b32efd7b9
###
```

- This is what the GFF3 file looks like when I annotate a tRNA without introns. 
```##gff-version 3
##sequence-region Group11.18 1 4736299
Group11.18	.	gene	2344445	2344843	.	+	.	owner=email@domain.com;ID=92b24747-8286-4dd3-9b3f-9a70ed278514;date_last_modified=2017-02-22;Name=othertRNA;date_creation=2017-02-22
Group11.18	.	tRNA	2344445	2344843	.	+	.	owner=email@domain.com;Parent=92b24747-8286-4dd3-9b3f-9a70ed278514;ID=11a60f6f-857b-4669-8419-82ca1b091d88;date_last_modified=2017-02-22;Name=othertRNA-00001;date_creation=2017-02-22
Group11.18	.	exon	2344445	2344843	.	+	.	Parent=11a60f6f-857b-4669-8419-82ca1b091d88;ID=44c8e1f4-973d-451b-b4cd-bf5e2e70eea7;Name=44c8e1f4-973d-451b-b4cd-bf5e2e70eea7
###
```

- Lastly, saving GFF3 both directly from the User-created annotations area and using the GFF3 Export button, and then round-tripping to load them as files for new tracks is working as expected. In the image, I've loaded the saved GFF3 into a track labeled as *GFF3 tRNAtest*.
<img width="1310" alt="screen shot 2017-02-22 at 10 16 50 pm" src="https://cloud.githubusercontent.com/assets/1714621/23247064/ba4f7d5e-f94c-11e6-864a-d814ab157f0e.png">

- So, things look good from our end. Let's find out what's the mystery with your installation @erasche. Perhaps it would be worth looking into your config files again?  Is there something that you may have changed? Did we do something else somewhere??

**Comment by monicacecilia** [comment]
- And, if I delete the exons from the GFF3 file on purpose, then I get the same suspect elements in the new track as you are getting, Erich. See the *GFF3 Annotations (1)* track below. To clarify, this is not the GFF3 Apollo is exporting but the one I made up with the incorrect contents. 
<img width="405" alt="screen shot 2017-02-22 at 10 32 09 pm" src="https://cloud.githubusercontent.com/assets/1714621/23247457/0c107664-f94f-11e6-9ef0-d51a6fe3068d.png">

**Comment by erasche** [comment]
> So, things look good from our end.

Except @nathandunn can reproduce the issue, and I'm assuming he's working from `:master` vs you on 2.0.6. So that gives us a starting point for a bisect, awesome.

Sorry, I should be better about including the precise version that I'm working on (2e7d897b6347a0fccde8c3a4cb1a4175a4928963). (Yes, I remember the previous discussions about running on master, but that's where I do my new features development / hacks I'm building for my org's needs, so that's where I hit this regression.)

**Comment by nathandunn** [comment]
@erasche  I think the only weirdness (which is the same on 2.0.6 and master, though I only tested on 2.0.6 like @monicacecilia) is that it lists "parentgene" as an attributed instead of "ID".   

My intuition was that it was done that way so that we would preserve the gene value if we do a round-trip (does this sound right @deepakunni3 ).  By round-trip I mean:

1. create evidence
1. create manualAnnotation
1. export manualAnnotation as GFF3
1. import GFF3 as evidence (open GFF3)
1. delete original manual Annotation
1. create manual Annotation with new evidence
1. confirm that both manual Annotations were identical

The lack of an exon is problematic for the missing backbone, but it is correct.

Perhaps the fix is that on import / add "parentgene" is added as "ID" as well.   We'll discuss it today.

**Comment by deepakunni3** [comment]
The `parentgene`instead of `parent` is a peculiarity of `client/apollo/js/Store/SeqFeature/ApolloGFF3.js`. That doesn't mean that the parent gene is not handled properly. We can modify `ApolloGFF3.js` to rename `parentgene` to be just `parent` and still have this bug. 

The JSON Object is prepared as expected. The fact that the GFF3 itself has no exon is what is leading to the visual oddity observed when importing the GFF3.

@erasche If you use the following GFF3, I am sure (and as @monicacecilia tested) that your tRNA would render properly:
```
##gff-version 3
##sequence-region Mijalis 1 30133
Mijalis	CPT	gene	25390	25466	.	+	.	owner=;ID=ee284a79-9ec8-47b1-9e2d-056bcd3454af;date_last_modified=2017-02-20;Name=Mijalis;date_creation=2017-02-20
Mijalis	CPT	tRNA	25390	25466	.	+	.	owner=;Parent=ee284a79-9ec8-47b1-9e2d-056bcd3454af;ID=q8bf081f-0597-44d5-8109-90ed976221e4;date_last_modified=2017-02-20;Name=Mijalis-00001;date_creation=2017-02-20
Mijalis	CPT	exon	25390	25466	.	+	.	owner=;Parent=q8bf081f-0597-44d5-8109-90ed976221e4;ID=exon1;date_last_modified=2017-02-20;date_creation=2017-02-20
```

**Comment by erasche** [comment]
Works for me and increasingly looks like a problem on my end. Thanks for the help isolating the issue!
