### ISSUE TITLE
addTracks/addStores and URL encoding

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#1502]
Hi,
I'm trying to create links to apollo with addTracks and addStores as described in #1140 
I think there is a problem with url encoding of this json content: the link goes to loadLink, and the apollo pannel appear, but *not* the jbrowse window. Looking at the http requests, I get a 400 error when apollo tries to load an url like this:
```
http://bipaa.genouest.org/blablabla/apollo/17739212431914997359/jbrowse/index.html?loc=scaffoldxxx%3A0..179470&clientToken=17739212431914997359&addStores={%22url%22:{%22type%22:%22JBrowse/Store/SeqFeature/GFF3%22,%22urlTemplate%22:%22http://url.to/some.gff3%22}}&addTracks=[{%22label%22:%22Blast%20results%22,%22type%22:%22JBrowse/View/Track/CanvasFeatures%22,%22store%22:%22url%22}]&tracklist=0
```

Looking at the logs Apollo tells me:
```
apollo_1         | 23-Feb-2017 14:23:16.553 INFO [http-apr-8080-exec-10] org.apache.coyote.http11.AbstractHttp11Processor.process Error parsing HTTP request header
apollo_1         |  Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
apollo_1         |  java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
apollo_1         | 	at org.apache.coyote.http11.InternalAprInputBuffer.parseRequestLine(InternalAprInputBuffer.java:239)
apollo_1         | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1017)
apollo_1         | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
apollo_1         | 	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2445)
apollo_1         | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
apollo_1         | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
apollo_1         | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
apollo_1         | 	at java.lang.Thread.run(Thread.java:745)
```

My proxy setup is like this (yes, a bit crazy looking...):
apache --> nginx 1 --> nginx 2 --> tomcat

The 400 error comes from nginx 1.

If I url encode all {,},[,] chars the http query works.

So my guess is that apache is more tolerant to unsafe characters than nginx, and that apollo should url encode a little more the json (if it's not already done!?)? What do you think?

**Comment by nathandunn** [comment]
Yeah, the encoding is tricky.   If it is fixed in one place, it will often fail in others. 
For this reason and a few others I want to long-term get them out of the URL's and into JSON posts associated with unique hash keys / bookmarks as I these URL's are only going to get more and more complicated and really shouldn't depend on a user's proxy setup.   

I'm also hoping to improve the integration with Apollo as well, so hopefully it will minimize these types of problems. 

In the interim, is it possible for you to URL-encode the nginx / apache stuff coming in?

@ihh  / @enuggetry   Just an FYI.

**Comment by nathandunn** [comment]
Of course, I also like the idea of converting JSON to legitimate URL parameters (and vice versa), but I haven't seen a universal way to do that as of yet.

**Comment by abretaud** [comment]
Nevermind, in fact the 400 error comes from tomcat.
I agree that this encoding stuff will always be a problem at some point, if it can be passed by posts it would be much easier!

For my setup, I came up with this ugly wordaround in the conf of the last nginx:

```
            if ($args ~* addStores=(.*)) {
                set_unescape_uri $addStores $1;
                set_escape_uri $addStores_fixed $addStores;
                set $args addStores=$addStores_fixed;
            }

            if ($args ~* addTracks=(.*)) {
                set_unescape_uri $addTracks $1;
                set_escape_uri $addTracks_fixed $addTracks;
                set $args addTracks=$addTracks_fixed;
            }
```

It decodes then reencodes the addStores and addTracks parameters before passing it to tomcat. It seems to work, I just hope it won't have some strange side effect!

**Comment by nathandunn** [comment]
Perfect.  Glad you found a workaround.  I'm going to leave it open as a reminder.

**Comment by erasche** [comment]
@abretaud should we add nginx to the default docker-compose.yml with this configuration?

**Comment by abretaud** [comment]
Hum, which one do you mean?

**Comment by erasche** [comment]
hmm, the apollo image, maybe the gmod stacks, etc?

**Comment by abretaud** [comment]
Hey!
A little update of the workaround:
```
            if ($args ~* (.*)addStores=(.*)) {
                set_unescape_uri $addStores $2;
                set_escape_uri $addStores_fixed $addStores;
                set $args $1addStores=$addStores_fixed;
            }

            if ($args ~* (.*)addTracks=(.*)) {
                set_unescape_uri $addTracks $2;
                set_escape_uri $addTracks_fixed $addTracks;
                set $args $1addTracks=$addTracks_fixed;
            }
```
Without this, some params (like loc) were lost. I had a hard time understanding why :)

I've been busy fixing bugs/preparing training sessions lately, I have a few fixes like this I hope to finally push in the official images soon
Cheers

**Comment by nathandunn** [comment]
Nice.  Yeah, I’m definitely interested in seeing the compilation of fixes!

**Comment by nathandunn** [comment]
I'm closing for now.  If you have any fixes @abretaud that would be great
