### ISSUE TITLE
Error when listing group when no organism

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#1503]
Just a little problem with the latest version of https://github.com/TAMU-CPT/galaxy-apollo/blob/master/create_or_update_organism.xml
The galaxy tool displays a list of user groups from apollo using the API.
When there is no organism yet in apollo, there is this error: `ERROR apollo.GroupController  - {error=User does not have permission for any organisms.}` and the list remains empty, even if there is group in apollo (auto created with remote_user auth)
ping @erasche

**Comment by erasche** [comment]
Ah! Ok, nice catch.

**Comment by nathandunn** [comment]
@abretaud   Is this off of master?    I thought we had fixed that in #1388.   Had we missed a spot?

**Comment by nathandunn** [comment]
@erasche  / @abretaud  Yes, if the tool is using an older version than an update to master should fix this (and you can post the issue there).

**Comment by abretaud** [comment]
Hum, yes I see this problem with 2.0.6
Do you think it's because we add a token to api calls there? https://github.com/TAMU-CPT/galaxy-apollo/blob/master/webapollo.py#L473
I think this is no longer necessary with 2.0.6 now?

**Comment by nathandunn** [comment]
You should not need a token in 2.0.6+.     This works for me by the way (and should be easy to emulate) with an admin user.  

https://github.com/GMOD/Apollo/blob/master/docs/web_services/examples/shell/loadGroups.sh

It was requiring an organism before, which made no sense) and now it does not.    Hopefully #1504 fixes this.   Let me know.
