### ISSUE TITLE
demo instance not working

### ISSUE THREAD

**Issue by beedatadriven** [GMOD/Apollo#1505]
Link to Apollo2 demo instance not working. 502 Bad Gateway Error
Relevant link:
http://icebox.lbl.gov/Apollo2/annotator/index

Found on this page:
http://genomearchitect.org/demo/

**Comment by nathandunn** [comment]
I am bouncing the server to create another installation.   Apologies.  Will have it up within the hour I hope. 

Thanks,

Nathan

**Comment by nathandunn** [comment]
@beedatadriven   Seems to be back up now.   Let us know if you have any additional issues.

**Comment by beedatadriven** [comment]
Yes thank you, the main honey bee demo site is back up.  All other demo species appear to begin to load an older version of the interface then redirect to the honey bee demo.

**Comment by monicacecilia** [comment]
Try again.

**Comment by beedatadriven** [comment]
Once signed into the demo, I am able to switch between species.  

However, when signing in there is the option to "Browse public genomes".  That link goes to this page:
http://icebox.lbl.gov/Apollo2/jbrowse/

Several of those species appear to no longer be options as they redirect to another species upon logging in.  Looks like that site just needs to be updated to the currently available species list, not a big issue.

Just wanted to take a peek at Apollo2...all the best.

**Comment by nathandunn** [comment]
It redirects to a known species by design.  

The public genomes for viewing are different than the ones available to a user to annotate once logged in.  

We’ve been trying to refine some of these permissions to reflect some of this ambiguity.  

Thanks for the feedback,

Nathan

**Comment by beedatadriven** [comment]
OK, I would expect some warning to suggest that I have not been granted permission to annotate on the public genome through which I am attempting to log in.  Perhaps then an option to select to continue to log in and be directed to only those genomes to which I have annotation permissions.  Otherwise simply being silently directed to other genomes that I have permissions to is confusing.

Changing the current behavior to add such a warning would be another issue for another time.

Thanks.
