### ISSUE TITLE
REST API for statuses and canned things

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#1507]
Hey,
When deploying a new apollo instance using docker, I'd like to automatically create new statuses and canned keys/values at startup.
I'm thinking about adding some methods to https://github.com/TAMU-CPT/galaxy-apollo/blob/master/webapollo.py
I couldn't find some rest api that I could use from the python code, is there one?

**Comment by erasche** [comment]
@abretaud nope, have/missing the following:

- [ ] getStatus
- [ ] addStatus
- [ ] deleteStatus
- [x] getCannedComments
- [ ] addCannedComments
- [ ] deleteCannedComment

**Comment by nathandunn** [comment]
So, we do support some of these: 

If you look at the web services under [Annotation Services](http://icebox.lbl.gov/Apollo2/WebServices/), we support anything you can do with the info editor, so its not quite that bleak ;)  

We can probably just extend AnnotationEditorController (where the others are written), or add it do StatusController, though you will need to remove the "beforeInterceptor contents".    

Note that there is a "setStatus" web-service example here: https://github.com/GMOD/Apollo/blob/master/docs/web_services/examples/shell/setStatus.sh  

I think that this is the same thing as "addStatus" above.

**Comment by abretaud** [comment]
Ok, thanks you 2!
Looking at the code I think setStatus set the status (!) for a gene, while addStatus would be to create a new status option (what I need).
I hacked a bit and managed to add statuses, but couldn't list them though (and I *think* I had some auth problems too)...
I'll see if I have time to hack more (but j-1 before vacations!)
I will need cannedKeys and cannedValues too at some point (add and listing mainly)

**Comment by nathandunn** [comment]
Yes.  The CannedKeys / CannedValues should be needed as well. 

If you want to create a PR with the words “DO NOT MERGE” in the title, I may be able to help prod you in the right place.  

You may want to simply add additional methods to those specific controllers (e.g., StatusController) that emulate what is done in OrganismControllers.   

Wish I had more time to do it myself, but I don’t think it will be all too hard. 

Nathan

**Comment by abretaud** [comment]
Done in #1538 and https://github.com/galaxy-genome-annotation/galaxy-apollo/pull/11
