### ISSUE TITLE
Need to fix the log4j2 file output

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#151]
Maybe it is my setup, but I can't get the rolling file appender to work, even after uncommenting the lines for it. 

I realized a potential root of the cause while debugging it.

For example, before uncommenting the FileName property, it was outputting to
~/logs/${FileName}
After uncommenting the FileName property, it was outputting to
~/${Directory}/test.log
Note that these are literal filenames, so it clearly had problems interpolating the properties

But, by putting two and two together, I realized the main problem was that it wasn't processing both FileName and Directory at once.

**Comment by cmdcolin** [comment]
To fix it, I made the properties sections look like this

        "properties": {
            "property": [{
                "name":"Directory",
                "value":"${sys:user.home}/logs"
            },
            {
                "name":"FileName",
                "value":"test.log"
            }]
        },

Note that I changed the two instances of "property" under the "properties" section to a json array. I'm pretty sure this is the right approach, so it is probably not just my setup

**Comment by cmdcolin** [comment]
Also, we might want to also allow the option to output to the catalina.home/logs directory instead of sys.user_home/logs since sometimes tomcat doesn't have a home directory

**Comment by cmdcolin** [comment]
I pushed the changes that I mentioned and added new catalina sample logger. I also changed test.log to webapollo.log.

**Comment by nathandunn** [comment]
"Also, we might want to also allow the option to output to the catalina.home/logs directory instead of sys.user_home/logs since sometimes tomcat doesn't have a home directory"

catalina.home/logs should be the default for an installed tomcat instance.  For a dev instance it should be local (I think it puts the catalina.home directory in the current directory), so we just need to make sure that a "logs" directory is present.     Anyway, I'm sure that this will work.

**Comment by cmdcolin** [comment]
I tried to summarize here

http://webapollo.readthedocs.org/en/latest/Configure/#logging-configuration

Copy/paste

**Comment by nathandunn** [comment]
Great.  Thanks,

Nathan

**Comment by nathandunn** [comment]
I will test and close.

**Comment by nathandunn** [comment]
seems to be working as required
