### ISSUE TITLE
Tracks not showing up in 2.0.7 snapshot

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1529]
version:
```shell
Version: 2.0.7-snapshot
Grails version: 2.5.5
Groovy version: 2.4.4
JVM version: 1.8.0_112
```

I just deployed the latest updates for testing, and the tracks section isn't showing up.  In firefox it just keep showing a 'loading' message, and in chrome it does show some fields with no information.  Is this the expected behavior now?

I like the new slider for showing and hiding the JBrowse tracks.

<img width="1342" alt="screen shot 2017-03-16 at 12 15 59 pm" src="https://cloud.githubusercontent.com/assets/421248/24006756/ff6e7672-0a42-11e7-9367-e922d57707a5.png">

**Comment by nathandunn** [comment]
Tripping up on this code: https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/AnnotTrack.js#L381

Preventing user from attacking themselves !   FYI @deepakunni3  / @enuggetry 

Curious what the difference might be.

**Comment by nathandunn** [comment]
I think this is because we are enforcing adding a port to the check, even when 80 (which most systems will on).

**Comment by nathandunn** [comment]
@childers   Going to close this for now as I think / hope its fixed, but let me know if it is still a problem.  I tested on both firefox and chrome.

**Comment by childers** [comment]
Thanks for the fast reply! I've pulled, deployed and am looking at it now.  The new build has what look like collapsed accordions that I can't expand, both on firefox and chrome.


<img width="1341" alt="screen shot 2017-03-16 at 1 46 31 pm" src="https://cloud.githubusercontent.com/assets/421248/24010918/9d3dfcf4-0a4f-11e7-9bf9-f39ed3a0322f.png">

**Comment by nathandunn** [comment]
Interesting.  What does your trackList.json look like?   Wondering if there is an edge-case I haven’t looked at.

**Comment by childers** [comment]
We use the hierarchical categories in our track listings. Could that be what's throwing things off? I just checked out the demo up on icebox and it appears to be working fine.  Looking at one of the example instances with track categories (Human-Hg38), it looks like it is behaving the same way it is on our dev server.

It looks like the issue is with displaying tracks that are binned into categories.

<img width="1382" alt="screen shot 2017-03-16 at 2 02 52 pm" src="https://cloud.githubusercontent.com/assets/421248/24011517/656907ea-0a51-11e7-9e5f-960fa21390a8.png">

**Comment by nathandunn** [comment]
No I specifically designed it to work with the hierarchical categories, but possibly I didn’t do something correctly.  I’ll use human-hg38 as a test-case.    

Weirdly, volvox was working perfectly earlier, so I’m a bit surprised its having issues now.

**Comment by nathandunn** [comment]
@childers   Should be working now

**Comment by childers** [comment]
Building and deploying now...
...
...
This is a side note, but today's builds don't seem to update when I click the login button.  I reload the page and am logged in, but the status never changes otherwise.

The new interface works, and is quick too!

![screen shot 2017-03-16 at 3 56 16 pm](https://cloud.githubusercontent.com/assets/421248/24016081/28435248-0a61-11e7-8613-378286c9a9cf.png)

**Comment by nathandunn** [comment]
@childers   Closing this issue. I have noticed this in the past (WRT to the login issue).   I know kind of what its doing, but I am unsure if its an artifact of development, or a legitimate issue.   When I reload it also fixes the issue (not a great solution, but a solution nonetheless).     I'll open a bug describing it.
