### ISSUE TITLE
Create Help Page

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#153]
Provide users with a cheat sheet that is available from the UI.  - include keyboard commands and usage.

**Comment by nathandunn** [comment]
add the jbrowse + any other doc and then assign it back to me or Colin.

**Comment by nathandunn** [comment]
@monicacecilia  should be under jbrowse/docs

**Comment by cmdcolin** [comment]
The actual source for the help popup box is in JBrowse's QuickHelp.js but it is also quite configurable via the config. 

    quickHelp→content 	Sets the content of the help dialog.
    quickHelp→href 	    Sets the content of the help dialog using and XHR to retrieve content.
    quickHelp→title     	Sets the title of the help dialog.

This was previously undocumented (along with a bunch of other things) so I added it to the jbrowse configuration guide

**Comment by nathandunn** [comment]
![screen shot 2015-02-05 at 11 13 52 am](https://cloud.githubusercontent.com/assets/751274/6067348/9f16d5cc-ad28-11e4-9d58-60512a5ba016.png)
![screen shot 2015-02-05 at 11 13 59 am](https://cloud.githubusercontent.com/assets/751274/6067349/9f1830de-ad28-11e4-9ecc-5de4f08cde73.png)

**Comment by monicacecilia** [comment]
@nathandunn Please review the following:
* The Web Apollo general info menu item should appear first in the list, and should be labeled differently. For now, change to "General" without the question mark.
* I updated the contents of the Web Apollo Help page for better wording, correction of typos, and clarification on "Information Editor". Help File available at:  https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Dialog/Help.js
Thank you!

**Comment by nathandunn** [comment]
@cmdcolin   Not sure what the best way to do this is.   I thought I had added this, but the "General" label still shows up on the bottom.  Not sure what the easiest way to update this in the plugin is.    Either remove and add manually like I had started to do or there is a way to do the config differently then I see.

**Comment by cmdcolin** [comment]
I fixed most of the things that were mentioned. I didn't use nathans url at help/apollo_quick_help.html yet because the icons are broken and because it uses css sprites so it's annoying to recreate the icons

**Comment by nathandunn** [comment]
@cmdcolin   Looks great.  Thanks.

**Comment by monicacecilia** [comment]
Brilliant!

-- updated a word on the document at https://github.com/GMOD/Apollo/blob/1efa27115ba77e9ffb3170602d836d6f69c95ae0/client/apollo/js/View/Dialog/Help.js
