### ISSUE TITLE
Extracting Annotations 

### ISSUE THREAD

**Issue by mastiles** [GMOD/Apollo#1531]
Hi there,

Is a way to programmatically access/extract our User-created annotations from the underlying database? Ultimately we envision having hundreds of organisms in the database, and being able to programmatically extract annotations from all to run, e.g., phylogenetic analyses. Can you point me in the direction of how best to achieve this...?

Thanks!

**Comment by erasche** [comment]
My organisation maintains some python scripts we use for this. [These tools](https://github.com/TAMU-CPT/galaxy-apollo) are specifically galaxy tools, but the python scripts are completely usable on their own.

We automatically extract annotations from apollo, run analysis workflows on them, and then push them back to Apollo with hundreds of phage genomes, so this is definitely possible!

**Comment by nathandunn** [comment]
@erasche  's tools are great.  They rely on the webservices we provide.  If you go to the admin panel you'll see them documented there, but they are these ones:  http://icebox.lbl.gov/Apollo2/WebServices/

Some examples are here:  

https://github.com/GMOD/Apollo/tree/master/docs/web_services/examples/shell

The exportFeatures and getFeatures in the shell directory might be what you want, or you can modify to what you need.

 If you want just the GFF3, you could use this script directly:

https://github.com/GMOD/Apollo/blob/master/docs/web_services/examples/groovy/get_gff3.groovy

**Comment by mastiles** [comment]
Fabulous, thank you very much - that should make life a lot easier!
