### ISSUE TITLE
add evidence code to GO Attributions

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#154]
Business logic for handling attributes + reference required for each evidence code. 

http://geneontology.org/page/go-annotation-file-formats
http://geneontology.org/page/guide-go-evidence-codes

Need to restrict for type (Gene, mRNA, ncRNA, etc. etc.)

Possibilities:
- organism specific genome publication  
- canned pseudopublication for Apollo as a default 
- inferred sequence similarity based on the published paper

**Comment by nathandunn** [comment]
@monicacecilia  @selewis   FYI

**Comment by nathandunn** [comment]
use IC in the meantime as boiler-plate . . . with the idea that we will be exporting to GAF at some point

**Comment by monicacecilia** [comment]
- publication of individual gene from evidence (before there is a genome sequence)

**Comment by cmungall** [comment]
Do you plan to support all of GAF 2.0?

**Comment by nathandunn** [comment]
@cmungall  I haven't gotten that far other than we don't necessarily want a simple DBXref anymore. 

@khowe  and his group may have some additional input on what they would like to see here.    This isn't immediate, so we have some time to think about it.

**Comment by nathandunn** [comment]
@khowe / @epaule  How were you planning on handling the richer output for these annotations from Apollo?    As a separate GAF2 file (http://www.geneontology.org/page/go-annotation-file-gaf-format-21), kludged somehow GFF3 spec, or both?

**Comment by kltm** [comment]
For a richer format, one might want to check out a newer tabular standard with GPAD.
(Older version here (http://geneontology.org/page/gene-product-association-data-gpad-format), @cmungall may have a link to the newer version.)

**Comment by nathandunn** [comment]
(note to self), the interface should be part of the side-panel and not part of the dojo interface.

**Comment by epaule** [comment]
Currently we use GAF2 at WormBase, but on special request overload also the GFF3 with the information.
I do admit, I haven't spent too much thought on how Apollo should do it, but I think both are an option.

* GAF2 is philosophically cleaner
* GFF3 overloading more universally used

**Comment by nathandunn** [comment]
@epaule  Do you have a suggestion on how you would overload the GFF3?   We have to export it, so it would be good to do it for GFF3 as a minimum and then extend that to GAF2 as a separate export.

**Comment by cmungall** [comment]
I have seem additional syntax smuggled into the value slot in column 9
property-value sets

>

**Comment by nathandunn** [comment]
@cmungall  Will have to think about this.  There are inherently some serveral one-to-many relationships in there (genes with multiple annotations, annotations with multiple references, etc.).   Encoding JSON seems like the most natural way to do this, but example are welcome.

**Comment by nathandunn** [comment]
@epaule if you have examples (when convenient) that would be great.  Thanks.

**Comment by nathandunn** [comment]
Done as part of #2137
