### ISSUE TITLE
Debugging Help: Cannot export *RNA in prod.

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1542]
Ok, I've been banging my head against the wall for multiple days with this, and wanted to know if you've ever seen anything like it. if not, that's fine, I'll keep banging my head and hopefully figure something out:

we cannot export gff3 of *RNA features in production (tRNA, ncRNA, ...)

- Everything exports fine when running locally (and I've done my best to mirror any and all customisations that are made to the docker image / in my source-code copy).
- When running inside the container, RNA features are just missing from the exported gff3
- In prod, I can right click them and "Get GFF3" and that works perfectly fine.
- But calling the IOService write controller just returns empty string.

As far as I can tell this is because the SQL query for features is empty when there are only *RNA featuers annotated. I can't compare the local vs prod since I haven't figured out how to tell h2 to log SQL statements. This clearly works fine for you all, the demo apollo instance has no issues.

The relevant code is IOServiceController.groovy. https://github.com/GMOD/Apollo/blob/master/grails-app/controllers/org/bbop/apollo/IOServiceController.groovy#L98 There's a debugging statement there that prints out features. For me, in prod (with debugging turned all the way on), and only tRNAs annotated, I see an empty feature array. 

- I can right-click these features and click "Get GFF3" and the gff3 shows up fine
- But calling either the write controller OR the getGff3 with a specific tRNA's uniquename, both return empty strings.

## diff from master

We've forked slightly from master. This is the most likely culprit but I've gone through all the changes and I cannot explain my issue with anything in the diff. https://github.com/GMOD/Apollo/compare/master...erasche:viral-debugging the changes we've made fall into three major categories: 1) terminator/phage plugin support, 2) disabling the mRNA panel on genes, 3) reverting to an older version of the setLongestORF which works better for us.

None of these changes should be affecting the functionality of export, as far as I can tell.

## configuration changes

Here's our [apollo-config](https://github.com/erasche/docker-apollo/blob/master/apollo-config.groovy) but we pretty much leave everything as default, and the defaults are pretty much what they are in the base config provided by apollo.

## Docker? Postgres? Production environment?

Environment | Source | Other Env | Can Export tRNAs | Conclusion
--- | --- | --- | --- | ---
Docker | master |  |  fail | Changes made in our branch are not causing this
Source | master or mine | h2 | success | 
Source | master or mine | postgres:9.5 container | success | Not postgres specific.
Source | master or mine | erasche/chado-pg9.5 container | success | Not postgres container specific.
Source | master or mine | `-Dgrails.env=production` | success | Not specific to production environment variable
Docker-built war file | mine | | untested | Will test later necessary. Can provide war if adventurous.

This seems to suggest it is something different between the docker environment and the local environment (environment here meaning more than just env vars), but I cannot fathom what that would be.

Pausing for now in my testing due to a long meeting. Posting anyway.

## Testing / reproduction

Currently reproducible (as far as I can tell) from my org's docker image:
https://github.com/erasche/docker-apollo/tree/cpt

- docker-compose up
- login through :8080/ first to create admin user (if you go through :9998 a non-admin user is autocreated and you're stuck)
- create organism
- add tRNA feature
- export → all → gff3

**Comment by nathandunn** [comment]
@erasche  Is it using https://github.com/TAMU-CPT/galaxy-apollo/blob/master/export.py#L15 to do the export in the case of Docker?   If so, can you intercept what you send to the server, or provide the Dictionary sent?    I feel like this might be the issue if so.  

Also, its everything but mRNA, right?  Just wanted to make sure I interpreted it correctly. 

Also, I'm assuming you're using 2.0.6 or master.   I doubt there is a problem, but wanted to make sure I was looking at the same code you were, roughly. 

So, I did test it.  . . and it worked flawlessly. 

For the mRNA: 
```
##gff-version 3
##sequence-region chrI 1 230208
chrI	CPT	gene	147596	151008	.	-	.	owner=ndunn@me.com;ID=6648979c-4609-4ec0-a853-83cbee3d7860;date_last_modified=2017-04-06;Name=YAL001C;date_creation=2017-04-06
chrI	CPT	mRNA	147596	151008	.	-	.	owner=ndunn@me.com;Parent=6648979c-4609-4ec0-a853-83cbee3d7860;ID=de60b729-77dd-4b54-ad38-343c94701e85;date_last_modified=2017-04-06;Name=YAL001C-00001;date_creation=2017-04-06
chrI	CPT	CDS	147596	151006	.	-	0	Parent=de60b729-77dd-4b54-ad38-343c94701e85;ID=de60b729-77dd-4b54-ad38-343c94701e85-CDS;date_last_modified=2017-04-06;Name=de60b729-77dd-4b54-ad38-343c94701e85-CDS;date_creation=2017-04-06
chrI	CPT	exon	147596	151008	.	-	.	Parent=de60b729-77dd-4b54-ad38-343c94701e85;ID=64e6b411-5efa-4d2c-b82d-6cf90aa31e89;date_last_modified=2017-04-06;Name=64e6b411-5efa-4d2c-b82d-6cf90aa31e89;date_creation=2017-04-06
###
```

when I changed the Annotation type - OR - created a new Annotation of type tRNA:

```
##gff-version 3
##sequence-region chrI 1 230208
chrI	CPT	gene	147596	151008	.	-	.	owner=ndunn@me.com;ID=8dbe9255-2b22-4cce-bc01-41f46d02d4c3;date_last_modified=2017-04-06;Name=YAL001C;date_creation=2017-04-06
chrI	CPT	tRNA	147596	151008	.	-	.	owner=ndunn@me.com;Parent=8dbe9255-2b22-4cce-bc01-41f46d02d4c3;ID=dc9713df-932e-4320-8c99-e16a86cda8f7;date_last_modified=2017-04-06;Name=YAL001C-00001;date_creation=2017-04-06
chrI	CPT	exon	147596	151008	.	-	.	Parent=dc9713df-932e-4320-8c99-e16a86cda8f7;ID=5fb0a53f-f50c-43ff-aa55-4a432fc60c27;date_last_modified=2017-04-06;Name=5fb0a53f-f50c-43ff-aa55-4a432fc60c27;date_creation=2017-04-06
###
```

I exported both from the track, itself, and from the side-panel.  I used Yeast as an example:

<img width="1887" alt="screen shot 2017-04-06 at 11 15 26 am" src="https://cloud.githubusercontent.com/assets/751274/24769246/a6223788-1aba-11e7-9e23-7b00139cc38d.png">

**Comment by erasche** [comment]
> @erasche Is it using https://github.com/TAMU-CPT/galaxy-apollo/blob/master/export.py#L15 to do the export in the case of Docker? If so, can you intercept what you send to the server, or provide the Dictionary sent? I feel like this might be the issue if so.

No, it's using the built-in export buttons.

> Also, its everything but mRNA, right? Just wanted to make sure I interpreted it correctly.

genes (and their mRNA subfeatures) export fine. repeat_regions export fine. tRNA, snoRNA, ncRNA, etc do not.

> Also, I'm assuming you're using 2.0.6 or master. I doubt there is a problem, but wanted to make sure I was looking at the same code you were, roughly.

The different test cases specified in the table in the issue mention branch in the second column. Off of master (or against branch in some cases but there were no differences,)

> So, I did test it. . . and it worked flawlessly.

yep, on everyone else's instance it works fine. Inside my docker container, it fails. I'm incredibly confused.

**Comment by nathandunn** [comment]
@erasche  I *think* I used your docker container off of your cpt docker-appollo branch, so presumably it was off of your Apollo branch? 

I definitely see your Terminator class in the exploded webapp.

**Comment by nathandunn** [comment]
@erasche  Do you have some GFF3 files / JSON that you know fail?

**Comment by nathandunn** [comment]
I'm also if this is related to #1543 and somehow something is screwy with your database.

**Comment by erasche** [comment]
Oh, I didn't realise your screenshots were from my image (`erasche/apollo:cpt`, that one is from our branch indeed, the most visible difference is it read "phage annotator" in the browser title just to help me differentiate).

I do not believe this is related to #1543, but who knows.

Sure, https://cpt.tamu.edu/dot/8.tar.gz is a directory I've been using in my testing. I just randomly choose one of the features of the metageneannotator track and create a tRNA from it. We experience the same problem whether or not the gff3 comes from a real tRNA prediction tool or just any old gff3 feature.

**UPDATE**: It looks like my tRNAs are being created without an exon associated. Well this is absolutely fascinating. I created three tRNAs from there different tracks and they all look different.

The green in the middle lacks an exon, which I know I can now recognise by the missing box around it. The right one looks 100% correct. The left one (which is brought up in the box) is blue for some reason?

![utvalg_116](https://cloud.githubusercontent.com/assets/458683/24809872/c821ddca-1baf-11e7-98f1-5fd4b631874a.png)

Here's some failing gff3:

```
##gff-version-3
Miro	aragorn	tRNA	49904	49980	.	.	.	Anticodon="cat";Codon="Met"
```

We can change our tRNA tool's output and just re-run for everyone. Painful but not too bad (compared to the days of staring at the DB wondering what the heck is going on). Thanks for rubbery duckying this with me and helping me notice the issue.

It looks like modifying that gff3 to include a parent gene *plus* an exon, will fix the issue.

**Comment by nathandunn** [comment]
*whew* you had me worried there.

**Comment by erasche** [comment]
Me too. This was slowly driving me crazy.
