### ISSUE TITLE
error deleting user

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1550]
I was trying to reset my user list and reload them all fresh and started getting errors on delete. I was able to loop through and rerun the user delete commands until I got to my last regular user, at which point I got a different type of error (see below).  

This is using a fork I updated from the main code base on Thursday.

<img width="675" alt="screen shot 2017-04-17 at 2 33 43 pm" src="https://cloud.githubusercontent.com/assets/421248/25099635/264b32f2-237b-11e7-814a-fddd3ce96fb6.png">

Is this expected behavior? Also I got the same errors regardless of whether it was a web service call or a deletion through the Apollo2 admin interface.

Example command that fails:
```shell
$ curl -i -X POST -H 'Content-Type: application/json' -d '{"username": "Admin@server.net", "password": "SuperSecret", "userToDelete": "user@user.com", "client_token": "ignore"}' https://<server>/apollo/user/deleteUser
HTTP/1.1 200 OK
Server: nginx/1.12.0
Date: Mon, 17 Apr 2017 18:37:25 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: JSESSIONID=8928B2E749732DDA3FA6EB13D600F397; Path=/apollo/; HttpOnly
Set-Cookie: rememberMe=deleteMe; Path=/apollo; Max-Age=0; Expires=Sun, 16-Apr-2017 18:37:25 GMT
Front-End-Https: on

{"error":"Failed to delete the user Hibernate operation: could not execute statement; SQL [n/a]; ERROR: update or delete on table \"grails_user\" violates foreign key constraint \"fk_lflwbgxduee8ljjwe5rfbdil2\" on table \"feature_grails_user\"\n  Detail: Key (id)=(1253590) is still referenced from table \"feature_grails_user\".; nested exception is org.postgresql.util.PSQLException: ERROR: update or delete on table \"grails_user\" violates foreign key constraint \"fk_lflwbgxduee8ljjwe5rfbdil2\" on table \"feature_grails_user\"\n  Detail: Key (id)=(1253590) is still referenced from table \"feature_grails_user\"."}

```

**Comment by childers** [comment]
Also, I've been testing on adding and deleting users a lot, so my ID is a little high:

```shell
webapollo_2=> select id, version, username from grails_user;
   id    | version |     username     
---------+---------+------------------
      19 |       1 | Admin@server.net
 1253590 |      68 | user@user.com
(2 rows)
```

**Comment by nathandunn** [comment]
@childers  The ```feature_grails_user``` table references the features the user has annotated.   You would have to delete all of their features first.   You should be able to find those in the annotator report admin panel.

Conversely you could add a flag (or set metadata) to the User and set them as inactive in a web service (or in the database directly).  

In addition to removing the login (easy to change the password), do you also want to hide them from some reports, as well?

**Comment by childers** [comment]
I'm just clearing the decks of sample users before adding in staging users.  I am working on some bulk processing to get everyone loaded. So far the creation is good, but resetting it is less so.  I know an option is to just wipe the db and restart, but then I'd also need to reload all organisms,  groups and permissions, and I'd lose the data from other users we're testing with

**Comment by nathandunn** [comment]
Oh, for that purpose, I have some scripts ```scripts```.  E.g., 

   ./scripts/delete_all_features.sh

You can look through that.  If you want to add another script that also has users that would be fine, as well.

**Comment by nathandunn** [comment]
Just an FYI, users are stored as ```grails_user```, so you'll want to delete from that one.  (```users``` I believe is a postgresql or mysql syste table).

**Comment by childers** [comment]
@nathandunn I can't reliably see which organism that user made annotations on. I see there are 4 annotations in there, but not where they are, and I can't find a web service for "give me a list of user X's annotations" that is user-centric.  

UPDATE:

I was able to find it by logging in as an admin and viewing the organisms level reports and luckily this was the only user that had annotations on that organism.  If going through raw SQL, would this best be done by joining on several tables (I think: grails_user, feature, feature_location, sequence and organism) to see what organism a user had annotations on?

I had forgotten that the user table was even in this schema.  I had been rooting through grails_user, but appreciate the heads up.

**Comment by childers** [comment]
Also, I didn't list out the other error I was getting:

```shell
<long curl command...> https://apollo-dev.nal.usda.gov/apollo/user/deleteUser
HTTP/1.1 200 OK
Server: nginx/1.12.0
Date: Mon, 17 Apr 2017 19:19:56 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: JSESSIONID=C266BC0B2541EEA7A233613A5B6359E9; Path=/apollo/; HttpOnly
Set-Cookie: rememberMe=deleteMe; Path=/apollo; Max-Age=0; Expires=Sun, 16-Apr-2017 19:19:56 GMT
Front-End-Https: on

{"error":"Failed to delete the user null"}
```

**Comment by childers** [comment]
Ok, I had annotations with a separate organism that I found through SQL queries, and got that last temp user deleted.

**Comment by nathandunn** [comment]
Mr. null seems to be on every machine I work with. 

Nathan
