### ISSUE TITLE
incompatibility between gff3 and add_features_from_gff3_to_annotations.pl

### ISSUE THREAD

**Issue by lassancejm** [GMOD/Apollo#1553]
I have an annotation of several thousand genes that I would like to load as user-created annotation in order to keep all the associated metadata and limit the amount of dragging. However, the process fails with an _500 Internal Server Error_

```
Processing chr1
Processing chunk 1: https://beast.rc.fas.harvard.edu/apollo/annotationEditor/addFeature 
error: 500 Internal Server Error
Processing individual features for failed chunks
Processing BEAST_G0000001: 
[...] 
error: 500 Internal Server Error
```

I am using Apollo-2.0.3 together with add_features_from_gff3_to_annotations.pl script (downloaded today=042017). Note that I had no success with the now deprecated add_transcripts_from_gff3_to_annotations.pl. 

I am wondering whether this has to do with some of the attributes in the gff or at least incompatibilities between the attributes and the versionof Apollo that I am using. Here are a few lines of the gff:

```
##gff-version 3
###sequence-region chr1
chr1	CAT	gene	174835	177972	.	+	.	ID=BEAST_G0000001;gene_biotype=unknown_likely_coding;transcript_modes=augCGP
chr1	CAT	transcript	174835	177972	.	+	.	ID=augCGP-11712.t1;Parent=BEAST_G0000001;alignment_id=augCGP-11712.t1;gene_biotype=unknown_likely_coding;gene_id=BEAST_G0000001;transcript_biotype=unknown_likely_coding;transcript_class=possible_paralog;transcript_id=BEAST_T0000001;transcript_modes=augCGP
chr1	CAT	exon	174835	174961	.	+	.	ID=exon:augCGP-11712.t1:0;Parent=augCGP-11712.t1;alignment_id=augCGP-11712.t1;gene_biotype=unknown_likely_coding;gene_id=BEAST_G0000001;transcript_biotype=unknown_likely_coding;transcript_class=possible_paralog;transcript_id=BEAST_T0000001;transcript_modes=augCGP
chr1	CAT	CDS	174835	174961	.	+	0	ID=CDS:augCGP-11712.t1:0;Parent=augCGP-11712.t1;alignment_id=augCGP-11712.t1;gene_biotype=unknown_likely_coding;gene_id=BEAST_G0000001;transcript_biotype=unknown_likely_coding;transcript_class=possible_paralog;transcript_id=BEAST_T0000001;transcript_modes=augCGP
chr1	CAT	exon	176507	177972	.	+	.	ID=exon:augCGP-11712.t1:1;Parent=augCGP-11712.t1;alignment_id=augCGP-11712.t1;gene_biotype=unknown_likely_coding;gene_id=BEAST_G0000001;transcript_biotype=unknown_likely_coding;transcript_class=possible_paralog;transcript_id=BEAST_T0000001;transcript_modes=augCGP
chr1	CAT	CDS	176507	177969	.	+	2	ID=CDS:augCGP-11712.t1:1;Parent=augCGP-11712.t1;alignment_id=augCGP-11712.t1;gene_biotype=unknown_likely_coding;gene_id=BEAST_G0000001;transcript_biotype=unknown_likely_coding;transcript_class=possible_paralog;transcript_id=BEAST_T0000001;transcript_modes=augCGP
```

Thanks!

**Comment by nathandunn** [comment]
You should use the load scripts from the same version of Apollo as the server.   

The original source for 2.0.3 is here:

https://github.com/GMOD/Apollo/archive/2.0.3.zip 

Hopefully that fixes it. 

Nathan

**Comment by lassancejm** [comment]
Sorry, I should have mentioned that this is what I tried at first (= using the script add_transcripts_from_gff3_to_annotations.pl  from that distro). That prompted me to explore other possibilities.

This is the command I am using (which I am assuming is not the source of the error).

```cat test.gff3 | perl /Apollo-2.0.3/tools/data/add_transcripts_from_gff3_to_annotations.pl --url https://beast.rc.fas.harvard.edu/apollo --username _me_ --password _pwd_ -o "BEAST" -e exon -t transcript -g gene ```

JML

**Comment by nathandunn** [comment]
Thanks.   In both cases, what server error are you getting.  The tomcat server logs should be in a file called catalina.out.  

Nathan

**Comment by lassancejm** [comment]
Unfortunately, I don't have access to the log at present (permission issue that should be fixed shortly by the system admin). 
Will get back to you as soon as I have the logs. Thanks

**Comment by deepakunni3** [comment]
@lassancejm I did test out the command with the small snippet of GFF3 you shared earlier, and it seemed to have worked.

I am sure the logs will give more details on what is going on.

**Comment by lassancejm** [comment]
I finally got access to the log files. The file catalina.out appears empty (size zero), but the stacktrace.log contains info associated with the error I believe. I copied the relevant sections, which I hope will point you to the source of the error. 

Thanks!

[stacktrace.log.zip](https://github.com/GMOD/Apollo/files/965317/stacktrace.log.zip)

**Comment by nathandunn** [comment]
So, the good news is that I isolated there error using your log files:  
 https://github.com/GMOD/Apollo/blob/2.0.3/grails-app/services/org/bbop/apollo/FeatureService.groovy#L2675

The bad news is that it looks like your transcripts are not associating with the genes correctly.   

I have two suggestions:
1 - see if adding a name to the GFF3 fixes anything
2 - upgrade the server to 2.0.6
3 - upgrade the server to master  

If none of these work, then paste the log file from master and we can fix it there.   My intuition is that 2 will work, since it seemed to work for @deepakunni3.    

Upgrade instructions here: http://genomearchitect.readthedocs.io/en/stable/Migration.html#migration-from-2-0-x-to-2-0-y-on-production

Good luck.

**Comment by nathandunn** [comment]
Please re-open if still a problem.
