### ISSUE TITLE
Create the "public" permission level for organisms so that some organism annotations are publicly available

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#156]
I think we should have some option to allow non-logged in users to view annotations on the User-created annotation track. The feature has been requested by Chris and maybe other users as well (see recent mailing list threads).

I don't think there was an issue open on trello -or- github, so I am just creating this for now.

**Comment by nathandunn** [comment]
This is kind of a big piece for the 2.0 version (public annotations and tracks).    We can move it there unless she needs it sooner.

**Comment by cmdcolin** [comment]
I'll set the 2.0 milestone on it.

**Comment by nathandunn** [comment]
I need to set a "public" flag for viewing organisms via a group.

**Comment by nathandunn** [comment]
I think this was done in 2.0.1 . .

**Comment by cmdcolin** [comment]
It is still not possible for non-logged-in/public users to view the user-created annotations

**Comment by nathandunn** [comment]
Right, I read the title wrong.  Thanks.

**Comment by nathandunn** [comment]
this is done 👍
