### ISSUE TITLE
Move Information Editor to the Annotator Panel

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1564]
The Information Editor will be now inside the ‘Details’ portion of the Annotator Panel, and it will display the information across different tabs instead of the collection of tables in the current Information Editor. When the curator calls the ‘Information Editor’ from the right-click menu, or from the details of a transcript in the Annotator panel, the ‘Details’ panel will expand to take over the Annotator panel and will include more tabs – which can be closed.

**Comment by nathandunn** [comment]
Waiting to do this in JBrowse 2 version
