### ISSUE TITLE
error retrieving sequence

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#157]
https://trello.com/c/Q3vS3uLx

I stumbled on a server crash with retrieving peptide sequence for a certain feature

Select the rightmost exon on ERROR1 or ERROR2 here and select "Get sequence"

http://icebox.lbl.gov/WebApolloDemo/jbrowse/?loc=Group1.1%3A512371..517585&tracks=DNA%2CAnnotations%2COfficial%20Gene%20Set%20v3.2%2CGFF3_Annotations-Group1.1_0&highlight=

Error: Feb 02, 2015 8:22:17 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [org.bbop.apollo.web.AnnotationEditorService] in context with path [/apollo] threw exception
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.charAt(String.java:658)
at org.bbop.apollo.web.AnnotationEditorService.getSequence(AnnotationEditorService.java:3719)
at org.bbop.apollo.web.AnnotationEditorService.doPost(AnnotationEditorService.java:614)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)

**Comment by nathandunn** [comment]
@cmdcolin  The error is the charAt (and probably the substring call, as well)  . . . the CDS sequence is empty I would expect the Peptide sequence to also be empty.  Proposed fix (hopefully readable)  :

Would propose 

                } else if (gbolFeature instanceof Exon && ((Exon) gbolFeature).getTranscript().isProteinCoding()) {
                    String rawSequence = getCodingSequenceInPhase(editor, (Exon) gbolFeature, true);
                    sequence = SequenceUtil.translateSequence(rawSequence, editor.getConfiguration().getTranslationTable(), true, ((Exon) gbolFeature).getTranscript().getCDS().getStopCodonReadThrough() != null);
-                    if (sequence.charAt(sequence.length() - 1) == TranslationTable.STOP.charAt(0)) {
+                    if (sequence.length()>0 && sequence.charAt(sequence.length() - 1) == TranslationTable.STOP.charAt(0)) {

                        sequence = sequence.substring(0, sequence.length() - 1);
                    }

**Comment by nathandunn** [comment]
@cmdcolin  let me know if you have any thoughts on this, as I think it will make sense to merge it in . . .

**Comment by cmdcolin** [comment]
@nathandunn sorry I forgot about this issue. I think this patch is good, and I understand it now. If we want to add that it would be fine with me.

**Comment by nathandunn** [comment]
@cmdcolin   Yeah, go ahead and merge it in and add it to the changelog .  Moni will test them tomorrow.

**Comment by nathandunn** [comment]
@cmdcolin   Assign it to me when you're done.

**Comment by nathandunn** [comment]
@monicacecilia   on staging and ready for fun!

**Comment by monicacecilia** [comment]
fixed. thank you!!
