### ISSUE TITLE
Multiple reference sequences for an organism (adding plasmids)

### ISSUE THREAD

**Issue by mastiles** [GMOD/Apollo#1574]
Not a setup question, but is there a way to add plasmids to the reference sequence in a way that these can all be accessed from the central organism (rather than adding them as separate entities?)

**Comment by deepakunni3** [comment]
@mastiles So you have two separate fasta files - one for the genome and the other for plasmid?

And are you running `prepare-refseqs.pl` on both these files individually?

**Comment by deepakunni3** [comment]
@mastiles If they are two separate files then concatenate them into a single fasta and then run `prepare-refseqs.pl`.

Let me know if I am going off a tangent here.

**Comment by mastiles** [comment]
Perfect, thank you so much - I think I was trying to overcomplicate matters!

On 2 May 2017, at 23:08, Deepak <notifications@github.com<mailto:notifications@github.com>> wrote:


@mastiles<https://github.com/mastiles> If they are two separate files then concatenate them into a single fasta and then run prepare-refseqs.pl.

Let me know if I am going off a tangent here.

**Comment by deepakunni3** [comment]
@mastiles Glad to help!
