### ISSUE TITLE
'Duplicate' from the client calls addTranscript when it should be calling duplicateTranscript

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1578]
The 'Duplicate' operation from the client sends request to `addTranscript` instead of `duplicateTranscript`. This hasn't given us any problems so far but this is clearly a bug.

**Comment by nathandunn** [comment]
@deepakunni3  I think that it is correct, from looking at the client code, which handles any type of feature (in theory) and the server-side code only handles transcripts and looks like its never used.   Yeah, low priority.    Would be good to get that moved to the server to expose a better API, but not critical.

**Comment by deepakunni3** [comment]
@nathandunn Right. Not a priority. Saw this while working on coordinate transformation.

**Comment by nathandunn** [comment]
As there are no harmful side-effects, I'm going to close this.
