### ISSUE TITLE
UI request for 'sequences' view

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#158]
I like the new sequences interface, but was not clear how the Search button interacts with the two sets of textboxes below.  Right now, the location of the Go Button is clearly connected to the number of sequences in the view, but the Search  button looks like it got wedged in above everything else.  
![new_wa_ui_filters](https://cloud.githubusercontent.com/assets/421248/6024688/0d4c68c0-ab9b-11e4-8283-4e8dd99a51f4.png)
Are there plans to add some visual grouping for the elements or text to explain each field?
![new_wa_ui_filters_option](https://cloud.githubusercontent.com/assets/421248/6026258/5e3a56a0-aba7-11e4-969f-4a1e6acea55d.png)

**Comment by nathandunn** [comment]
Should be pretty easy:

http://getbootstrap.com/css/#forms-example

**Comment by monicacecilia** [comment]
@nathandunn The visual aid on "what to type" helps. It looks good. 

Both the "Go" and "Search" buttons perform the same function. That is, I tried "Search" for a group name or "Search" for the scaffolds/groups with the specified length, and I also tried "Go" for a scaffold/group or a page displaying results.  In my opinion,Chris' suggestion about lowering the "Search" button would work. But I'll leave it up to you.

Also, there is a 505 error when no integer is entered in the pagination search box. An automatic "NaN" is filled out in the box when clicking "Next -->", although the same error does not occur when clicking "<-- Previous".

This is the text that appears automatically: 

![screen shot 2015-02-18 at 5 42 40 pm](https://cloud.githubusercontent.com/assets/1714621/6260598/2178a014-b796-11e4-9b8d-5846e376c327.png)

And this is the error that is displayed after clicking the "Next -->" button.

![screen shot 2015-02-18 at 5 42 31 pm](https://cloud.githubusercontent.com/assets/1714621/6260578/e048e8ba-b795-11e4-813e-325c408293e4.png)

**Comment by nathandunn** [comment]
@monicacecilia  @childers   I fixed the above error (will be in RC3).  While the points about the Go and Search are true, I'm trying to avoid spending too much time on this interface.   

That being said, since they are the same function, I could just call the "Go" button "Search" and get rid of the other awkward search button.

**Comment by monicacecilia** [comment]
:+1:  @nathandunn if it's easy, let's make the switch. Thanks!

**Comment by nathandunn** [comment]
You mean moving the buttons around? 

Nathan
