### ISSUE TITLE
bug with 'View only Features' operation

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1587]
Two new assemblage are created after doing a ’View only features’ operation.

But removing this assemblage from the Assemblage panel removes only one of the assemblage while leaving the other behind as an artefact (and this doesn’t even show up on the Assemblage data grid).

**Comment by nathandunn** [comment]
- [ ] should only create one new assemblage when clicking on 'view only features'
- [ ] deleting the assemblage when not current should be supported.
