### ISSUE TITLE
Expected Sequence vs. Observed Sequence after a ‘Fold between Exons’ operation

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1591]
The observed sequence seen on the reference sequence track is different from the expected sequence for that region.

<img width="1333" alt="screen shot 2017-05-08 at 9 47 09 am" src="https://cloud.githubusercontent.com/assets/4530272/25809679/5ed7f80e-33d3-11e7-8e44-6cba3e9958c0.png">

**Comment by nathandunn** [comment]
I think that this will be related to #1284.
