### ISSUE TITLE
track data is shared user windows on the same organism

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1605]
To reproduce:
- open up one window with organism A and tracks 1,2,3
- open up another window with organism A (same user).  You should notice that the tracks 1,2,3 are selected.
- if you add or subtract a track in either window and then refresh the other one, you'll observe that it reflected the last change to the other window

I've yet to hear anyone complain about this, as I imagine in a lot of ways this would be desired behavior, but I wanted to document it.

**Comment by monicacecilia** [comment]
This is not an error. This is expected behavior.

**Comment by nathandunn** [comment]
Perfect.  Then we shall close it.  Thanks for clarifying.
