### ISSUE TITLE
Pipes in URL are not encoded

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1606]
From Tom Harrop at University of Otago, NZ:

>When users try to load one particular organism, the main (jbrowse) window remains blank and the >track list doesn't load. Sometimes "Loading..." appears in the "Tracks" tab and sometimes the tab >remains blank. The strange thing is that apollo was running fine for this organism, and it appears to >have stopped working without any changes on our part.
>
>When I look in the browser console I see an HTTP 400 error (bad request) for the following url:
>
>http://[OUR SERVER ADDRESS]/16630218091458342262/jbrowse/index.html?loc=scaffold100|size496982%3A0..496982&tracklist=0

Turns out the the HTTP error is due to a pipe (`|`) in the URL. Ideally, this should be escaped to its URL encoded equivalent `%7C`.

Tomcat 7 had no issues with pipes in URL and same with Tomcat 8, until v8.5.8 when this behavior was changed due to a security related bug report (https://bugzilla.redhat.com/show_bug.cgi?id=1397484).

**Comment by nathandunn** [comment]
The weird thing is that it should have encoded it here:

   trackListString += selectedSequence;
   trackListString += URL.encodeQueryString(":") + minRegion + ".." + maxRegion;

But doing it explicitly instead.

**Comment by deepakunni3** [comment]
Shouldn't it be:
```
trackListString += selectedSequence;
trackListString += ":" + minRegion + ".." + maxRegion;
String encodedTrackListString = URL.encodeQueryString(trackListString);
```

**Comment by nathandunn** [comment]
That would be more concise ;)    

Let me take a look.   I think there are some issues with over-encoding.  Also, I'm not sure if we want the ```..``` encoded.  At a minimum, I can encoded the ":" and the sequence.

**Comment by deepakunni3** [comment]
Ohh right. My bad. 
We definitely need `..` in the URL, untouched.

**Comment by nathandunn** [comment]
Okay.  I fixed that.  I'm going to test it quickly to make sure its working.
