### ISSUE TITLE
Apollo error

### ISSUE THREAD

**Issue by shashankx** [GMOD/Apollo#161]
i have downloaded the Apollo software for windows, after successful installation, when i open the Apollo , it shows an error:
The JVM could not be started. The main method may have thrown an exception.

How to resolve this problem

**Comment by nathandunn** [comment]
We need some more information:
1 - what version did you install (URL?)
2 - how did you install (just using maven?)
3 - do you have any log files I could see? 

I would highly recommend install Cygwin or better yet VirtualBox / Linux as we don't do a lot of windows support, though it should work in theory being Java.

**Comment by nathandunn** [comment]
We need some more information:
1 - what version did you install (URL?)
2 - how did you install (just using maven?)
3 - do you have any log files I could see? 

I would highly recommend install Cygwin or better yet VirtualBox / Linux as we don't do a lot of windows support, though it should work in theory being Java.

**Comment by cmdcolin** [comment]
@nathandunn  I think this is referring to the old Desktop Apollo

**Comment by shashankx** [comment]
url -http://apollo.berkeleybop.org/current/install.html

there is option name with JAVA VM or Without JAVA VM for windows, i tried both and got same error.

the file looks something like this:
Apollo_windows_with_jre.exe

I am not a programmer, so i prefer to use window over Linux.

**Comment by monicacecilia** [comment]
@shashankx, like Colin, I think you have downloaded the desktop version of Apollo. As seen in our website at http://genomearchitect.org/desktop-apollo we are no longer developing the desktop version of Apollo and that support for its use has been discontinued.

With that said, it sounds like your Java VM is having memory issues. For suggestions on how to fix this problem you could try reading through Help info on the subject, e.g: https://intellij-support.jetbrains.com/entries/23393413-The-JVM-could-not-be-started-The-main-method-may-have-thrown-an-exception

**Comment by shashankx** [comment]
can u guide me how to install this software on Linux, i appreciate it

**Comment by nathandunn** [comment]
@shashankx   Like Moni and Colin said, I would recommend installing the Web Apollo version (which is what I thought you had):

https://github.com/GMOD/Apollo/releases

To install Linux on Windows, you could virtualbox with Ubuntu (or your favorite flavor of Linux):

https://www.virtualbox.org/wiki/Downloads

**Comment by shashankx** [comment]
So, i need to type command:
Setup environment:
export PGUSER=web_apollo_users_admin
export PGPASSWORD=password
export WEBAPOLLO_USER=web_apollo_admin
export WEBAPOLLO_PASSWORD=web_apollo_admin
export WEBAPOLLO_DATABASE=web_apollo_users
export ORGANISM="Pythium ultimum"
export JBROWSE_DATA_DIR=`pwd`/data
export WEBAPOLLO_DATA_DIR=`pwd`/annotations

than download the webApollo
unzip it

then, 
sudo yum install postgresql postgresql-server postgresql-devel maven expat-devel tomcat git

till than everything is fine.
when i used command i got an error- 
sudo su -c "PGSETUP_INITDB_OPTIONS='--auth-host=md5' postgresql-setup initdb"

bash: postgresql-setup: command not found

how to resolve this

**Comment by nathandunn** [comment]
I typically just use “initdb”

It also might be like this:

http://serverfault.com/questions/350045/postgresql-service-initdb-doesnt-work <http://serverfault.com/questions/350045/postgresql-service-initdb-doesnt-work>

e.g., postgresql93-setup 

Nathan

**Comment by shashankx** [comment]
Again error- 
[root@root Apollo-1.0.3]# sudo su -c "PGSETUP_INITDB_OPTIONS='--auth-host=md5' initdb"
initdb: no data directory specified
You must identify the directory where the data for this database system
will reside.  Do this with either the invocation option -D or the
environment variable PGDATA.
[root@root Apollo-1.0.3]# sudo su -c "PGSETUP_INITDB_OPTIONS='--auth-host=md5' postgresql93-setup initdb"
bash: postgresql93-setup: command not found

**Comment by cmdcolin** [comment]
@shashankx can you please post the OS that you are using? if you are using redhat or centos, you might review the setup guide here https://wiki.postgresql.org/wiki/YUM_Installation

just add the environment variable

    export PGSETUP_INITDB_OPTIONS='--auth-host=md5'

in addition to the instructions in the guide since we want to ensure password based authentication

**Comment by nathandunn** [comment]
The instructions given below with the first error are correct:

> will reside. Do this with either the invocation option -D or the
> environment variable PGDATA.
> 

Though I find it a bit odd, as usually it will use a default directory.  But I would also recommend following Colin’s advice and look how to do it for your specific instance.   It should save you quite a bit of time. 

Nathan

**Comment by shashankx** [comment]
I believe Colin's advice works pretty good.

Shashank
