### ISSUE TITLE
Admin account for one organism can remove permissions of users on other organisms

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1611]
Testing the use case of organism level admin users, and have found that the privileges are not encapsulated to administer issues for that organism.  It looks like the Admin permission contains privileges for a mix of organism level and global level functions.  

What I was expecting to see:
- A list of users that have permissions on that organism
- A list of the groups that have permissions on that organism
- Optionally a list of all users
- Editable permissions for only the organisms I have admin rights over

What I see is:

- A list of all users, which is fully editable (I can add or remove groups for users on organisms I don't have admin permissions on).
- An editable list of all groups, including groups, so that I can remove groups with permissions on organisms I don't have admin for.
- The admin reports show several global features that the organism admin cannot access.  Is there a way to hide options the user is not authorized to access (see image below)?

<img width="410" alt="screen shot 2017-05-24 at 11 39 54 am" src="https://cloud.githubusercontent.com/assets/421248/26413364/ccd0be42-4079-11e7-8adf-8c54ce19f1ca.png">

**Comment by monicacecilia** [comment]
@childers: what version are you using to test your case?

**Comment by nathandunn** [comment]
@childers  Rolls with master.  

I think we limit those to full admin because of the web services.    However, I have a quick fix to make them internally consistent.

**Comment by nathandunn** [comment]
BTW, Good catch.

**Comment by childers** [comment]
@monicacecilia @nathandunn Thanks!
