### ISSUE TITLE
Split operation yields odd result when in reverse complement view

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1622]
Performing a split operation on a transcript,
<img width="1040" alt="screen shot 2017-05-30 at 9 22 08 pm" src="https://cloud.githubusercontent.com/assets/4530272/26613042/56459414-457e-11e7-864f-e106b76cc0d3.png">

yields the following:
<img width="1040" alt="screen shot 2017-05-30 at 9 21 42 pm" src="https://cloud.githubusercontent.com/assets/4530272/26613047/609e20ca-457e-11e7-98bc-56437d13c736.png">

This happens only in reverse complement view.

**Comment by nathandunn** [comment]
Fixed by #1628.
