### ISSUE TITLE
Frame calculation for negative strand should start on its 5' end

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1629]
Normal orientation:
![screen shot 2017-06-01 at 12 04 43 pm](https://cloud.githubusercontent.com/assets/4530272/26691441/b2262d6c-46c2-11e7-9cea-8463100357ea.png)

Reverse orientation:
![screen shot 2017-06-01 at 12 04 59 pm](https://cloud.githubusercontent.com/assets/4530272/26691446/b683d6ca-46c2-11e7-84b0-7c96341daa26.png)

Notice how the last exon changes color from red to purple.

**Comment by deepakunni3** [comment]
@nathandunn Closing this issue in light of our discussion yesterday, since the change in color is not an issue if the protein translation matches the feature's protein sequence (which it does).

**Comment by monicacecilia** [comment]
Not so fast.

**Comment by nathandunn** [comment]
So we had discussed this.  The protein and sequence are the same.  The color difference is due to the way that the start is chosen from the lhs, which is arbitrary.  However the coding should be consistent.  I can upgrade the server tomorrow once it has been cleaned out and we can take another look.

**Comment by monicacecilia** [comment]
To be clear (and as I mentioned in lab meeting), the "color" here is only a representation of the reading frame, and it should not be arbitrary. We also discussed possible roots for this problem. I'll look more closely at this next week and try to find a better way to both explain and draw a path for a technical solution.

**Comment by nathandunn** [comment]
Initially the problem observed was that the frame would change when switching to reverse complement view.   However, the issue is that the frame calculated on the CDS is set arbitrarily from the LHS instead of the RHS so that annotations on the reverse complement are correct (for annotations).

**Comment by selewis** [comment]
The above isn't quite accurate.

The frame calculated for the minus strand is always wrong currently (regardless of CDS, just look at the sequence). It is wrong whether the Apollo has just started up or whether the user has carried out rev-comp. Whatever genome sequence is currently on the minus strand it is miscalculated (although sometimes we'll be lucky and the overall double strand is modulo 3)

Frame always applies to only a single strand (not the double strand). And further counting must always start at the 5' end (i.e. opposite ends for the plus&minus strands). If the 'double strand' is not modulo 3 then the frames of the plus&minus strands will not be the same. The two complementary bases at the same position on opposite strands will not necessarily be in the same frames.

(and never use RHS/LHS - always think of it as 5' and 3' relative to each strand)

**Comment by nathandunn** [comment]
@selewis  Changed it.  I think I'd just stopped typing.

**Comment by deepakunni3** [comment]
Since the bug is in `SequenceTrack.js` (Apollo client code), I decided to see how native JBrowse renders the protein translation frame and following is my observation:

Apollo's `SequenceTrack.js`:
![screen shot 2017-07-10 at 4 55 11 pm](https://user-images.githubusercontent.com/4530272/28042239-11333d48-6592-11e7-836d-404ba6dcb491.png)


JBrowse's very own `Sequence.js`:
![screen shot 2017-07-10 at 4 56 55 pm](https://user-images.githubusercontent.com/4530272/28042301-47f4d18e-6592-11e7-86fe-57429579c86c.png)


From this it is clear that the bug we see in Apollo's `SequenceTrack.js` doesn't exist in the JBrowse implementation. Thus, the fix we are looking for is in JBrowse `Sequence.js`. We just have to implement the same algorithm used in JBrowse for calculating the protein translation frames.

**Comment by deepakunni3** [comment]
And by extension, `DraggableHTMLFeatures` should also implement the same logic to calculate protein translation for CDS features.

**Comment by nathandunn** [comment]
To match JBrowse, it seems like we are calculating the reverse frame incorrectly and maybe this should just be 0:

https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/SequenceTrack.js#L483-L485

**Comment by deepakunni3** [comment]
@nathandunn Not sure what that means but L483-L485 is definitely the block of code that is causing the issue.
