### ISSUE TITLE
specify URL parameter to hide entire navbar 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#163]
@cmdcolin Was wondering if you had any ideas on how to hide the menuBar programmatically. I put the hooks in and they seem to work. I would assume that this (where query=dojo/query) would do the trick, but not seeing it (note that it is on a branch): query('.menuBar').style('display','none');

**Comment by nathandunn** [comment]
@cmdcolin   Was wondering if you had any ideas on how to hide the menuBar programmatically.  I put the hooks in and they seem to work.   I would assume that this (where query=dojo/query) would do the trick, but not seeing it (note that it is on a branch):             query('.menuBar').style('display','none');

https://github.com/GMOD/Apollo/commit/bca5af6c807331a6ad1fd61dd0c2845166f1dd14

**Comment by cmdcolin** [comment]
I'm not sure exactly what you mean but it looks like this when i use your method

![screenshot-jbrowse org 2015-02-09 11-40-52](https://cloud.githubusercontent.com/assets/6511937/6111703/86de2bec-b050-11e4-9a72-bdf213ec1288.png)

**Comment by nathandunn** [comment]
My theory is that I’m calling the “hide” method in the wrong place. 

Nathan

**Comment by cmdcolin** [comment]
Yes, it probably needs to be called after some milestone is passed because the DOM is not necessarily constructed when the plugin is initialized. Even still, the hide method has problems, as in my screenshot, there's a large gap.

I would look into JBrowse's Browser.js to see how the "show_nav" option functions, and see if a new option can be added to it

**Comment by nathandunn** [comment]
Ahh . . . that makes more sense ..  I'll take a look.

**Comment by cmdcolin** [comment]
Added here 

https://github.com/GMOD/jbrowse/commit/a4fbb03d9d8f81e7390418e6752a4ffdea59b43a
https://github.com/GMOD/jbrowse/commit/398b56f537e5a09916b7864ebd671c473a525b0c

**Comment by nathandunn** [comment]
@cmdcolin   Sorry to be ignorant, but how would I hide the navbar?   Is it something I can call from trackList.json?

**Comment by cmdcolin** [comment]
Ya you can set "show_menu" in the trackList.json outside of the "tracks" section

Additionally, you could add it to jbrowse_config.json or jbrowse.conf, but I tested and trackList.json works too

**Comment by nathandunn** [comment]
Great.  Will give it a shot. 

Nathan

**Comment by cmdcolin** [comment]
For reference, a screenshot using show_menu=false

![screenshot-localhost 2015-02-10 20-27-32](https://cloud.githubusercontent.com/assets/6511937/6141115/e19c6ff0-b166-11e4-877e-2972deb3b5f6.png)

**Comment by cmdcolin** [comment]
@nathandunn to be clear, do you want to hide the navbar (which includes the zoom button, etc) or just the menu (which is just the option that I added?)

**Comment by nathandunn** [comment]
@cmdcolin  Just the menu.  What you have is perfect.  Thanks!

**Comment by nathandunn** [comment]
@cmdcolin   Works great.  Thanks!

http://icebox.lbl.gov/WebApolloHuman/jbrowse/?loc=chr20%3A324640..331161&tracks=DNA%2CAnnotations%2COGS-GRCh38%2COGS-GRCh38-gene&highlight=
