### ISSUE TITLE
Pin to top option should also be enabled for DraggableHTMLFeatures tracks

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1632]
We have lost the ability to 'Pin to top' some tracks from the evidence panel. If the track type is DraggableHTMLFeatures, the option is no longer available. However, the option is still available for CanvasFeatures. 
These are the available options in the menu right now: 
<img width="316" alt="screen shot 2017-06-01 at 11 28 13 am" src="https://cloud.githubusercontent.com/assets/1714621/26695159/aa7709be-46be-11e7-9160-3a62bb2cf913.png">

@deepakunni3 thinks the menu rendering code for DraggableHTMLFeatures is suspect.

**Comment by deepakunni3** [comment]
Okay, the bug is due to https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/DraggableHTMLFeatures.js#L1311

It was probably introduced when adding the ability to collapse elements in an HTMLFeatures track.

I have a PR for fixing this.
