### ISSUE TITLE
generating feature not using gene name

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1635]
If I create a Repeat Region or a Transcript Element it uses the UUID instead of the Original Gene.  This works on the master branch (or did).

**Comment by nathandunn** [comment]
@deepakunni3   Do you have time to take a look at this?   I've done a bit of testing on it.  It seems to fail on master as well, but not 2.0.6.    Works on staging (https://github.com/GMOD/Apollo/commit/7db3c908dc8dc331fe81f3a633de0164c3207855) but not in master).

**Comment by deepakunni3** [comment]
So this is a bug only on those tracks that don't have `Name` attribute for features in the GFF3 (and by extension, the JSON generated via `flatfile-to-json.pl`).

For example,

Here is a blurb from the OGSv3.2 GFF3:
```
Group1.1        amel_OGSv3.2    gene    507599  515039  1       -       .       ID=GB42155
Group1.1        amel_OGSv3.2    mRNA    507599  515039  1       -       .       ID=GB42155-RA;Parent=GB42155
Group1.1        amel_OGSv3.2    CDS     514009  514378  .       -       0       Parent=GB42155-RA
Group1.1        amel_OGSv3.2    CDS     513392  513906  .       -       2       Parent=GB42155-RA
Group1.1        amel_OGSv3.2    five_prime_UTR  514761  515039  1       -       .       Parent=GB42155-RA
Group1.1        amel_OGSv3.2    five_prime_UTR  514379  514408  1       -       .       Parent=GB42155-RA
Group1.1        amel_OGSv3.2    three_prime_UTR 512910  513391  1       -       .       Parent=GB42155-RA
Group1.1        amel_OGSv3.2    three_prime_UTR 507599  509541  1       -       .       Parent=GB42155-RA
Group1.1        amel_OGSv3.2    exon    507599  509541  1       -       .       Parent=GB42155-RA
Group1.1        amel_OGSv3.2    exon    512910  513906  1       -       .       Parent=GB42155-RA
Group1.1        amel_OGSv3.2    exon    514009  514408  1       -       .       Parent=GB42155-RA
Group1.1        amel_OGSv3.2    exon    514761  515039  1       -       .       Parent=GB42155-RA
```

Note that neither the gene nor the mRNA feature has an attribute called `Name`

Here is a blurb from the maker GFF3:
```
GroupUn4834     maker   gene    332     830     .       +       .       ID=maker-GroupUn4834-pred_gff_GNOMON-gene-0.0;Name=maker-GroupUn4834-pred_gff_GNOMON-gene-0.0;
GroupUn4834     maker   mRNA    332     830     .       +       .       ID=1:gnomon_95134_mRNA;Parent=maker-GroupUn4834-pred_gff_GNOMON-gene-0.0;Name=gnomon_95134_mRNA;_AED=0.20;_eAED=0.33;_QI=19|0|0.5|1|0|0.5|2|256|25;
GroupUn4834     maker   exon    332     627     .       +       .       Parent=1:gnomon_95134_mRNA;
GroupUn4834     maker   exon    774     830     .       +       .       Parent=1:gnomon_95134_mRNA;
GroupUn4834     maker   five_prime_UTR  332     350     .       +       .       Parent=1:gnomon_95134_mRNA;
GroupUn4834     maker   CDS     351     428     .       +       0       Parent=1:gnomon_95134_mRNA;
GroupUn4834     maker   three_prime_UTR 429     627     .       +       .       Parent=1:gnomon_95134_mRNA;
GroupUn4834     maker   three_prime_UTR 774     830     .       +       .       Parent=1:gnomon_95134_mRNA;
```

You can see that both the gene and the mRNA feature has an attribute called `Name`.

So it looks like our client side code doesn't default to the `ID` attribute in the absence of a `Name` attribute.

**Comment by nathandunn** [comment]
If it's just a difference in the gff then we can remove the milestone and call it a feature enhancement to infer the name from the id (and we can consider it later).

Just to clarify, with the correct gff it produces the correct name for a non-transcript feature in 2.1.0-snapshot? 

Nathan

**Comment by deepakunni3** [comment]
@nathandunn Do you mean `2.0.7-snapshot`? Yes, it works on the snapshot with the correct GFF3.

Yes, this can be considered as a feature enhancement. The fix was 3 lines of code in `JSONUtils.js`
