### ISSUE TITLE
Reverse complement view is incorrect

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1649]
When we do a reverse complement, the forward strand should be reversed and its complement should be calculated. i.e. The forward strand now becomes the reverse strand and vice versa.

But instead, we only see the forward strand reversed (but not its complement):
![screen shot 2017-06-15 at 2 25 06 pm](https://user-images.githubusercontent.com/4530272/27198157-aafd0820-51d6-11e7-811c-26a5d5e3b12d.png)

Visually what is expected:
After reverse complement, forward strand should be below and reverse strand should be at the top.

Related to #1629

**Comment by deepakunni3** [comment]
@nathandunn @monicacecilia This might need some discussion on what the expected behavior is supposed to be. 
Maybe I am confusing myself.

**Comment by nathandunn** [comment]
I *think* the sequences are okay (but yes, let's discuss).    However, the protein's are not being flipped at all, and that is definitely wrong.
