### ISSUE TITLE
Bring back square and curly bracket navigation gestures.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1659]
Testing in 2.0.1-snapshot, curly and square bracket gestures to navigate between exons and between gene models are no longer functional. We need to bring these back.

**Comment by erasche** [comment]
Dear goodness this exists? This is like christmas in june. (Btw, it's functional on 2.0.5 / the branch off of that that we're on). Is there a user quick-start or similar document where this feature is described? (I.e. somewhere I can find out if I'm missing any other super useful shortcuts)

**Comment by nathandunn** [comment]
@erasche  I think @monicacecilia  was testing on a broken version of our code.  I just confirmed that it works on 2.1.0 and master. 

![screen shot 2017-06-22 at 9 08 37 am](https://user-images.githubusercontent.com/751274/27444177-66379648-572a-11e7-89ce-454a81bbe55b.png)
![screen shot 2017-06-22 at 9 08 06 am](https://user-images.githubusercontent.com/751274/27444181-6a395e34-572a-11e7-9c3b-0da5918139a4.png)

**Comment by monicacecilia** [comment]
@erasche hahaha, yaaay, it's Christmas in June! :) 🎆 

Yes, it does exist, and the Help guide on the main window includes that little blurb on 'Annotation shortcuts'. You can also visit the updated [Apollo User Guide](http://genomearchitect.github.io/users-guide/), which includes these (under 'Exon Structure Integrity') and other useful tips. :bowtie:
