### ISSUE TITLE
Remember location after 'reverse complementing' a Reference Sequence.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1660]
Testing in 2.0.1-snapshot, after 'reverse complementing' a Reference Sequence, it would be good to have the annotation window to be focused on the coordinates where the user was before the change occurred. It is a bit disorienting trying to find the same place / genomic element, etc.

**Comment by monicacecilia** [comment]
@nathandunn ok, if not you, then who?

**Comment by nathandunn** [comment]
I think this is fixed in the up-to-date version.    I'm going to close this for now and you can re-open it if its still a problem.

**Comment by monicacecilia** [comment]
No. Let's keep it open until we have tested and corroborated that it was solved.

**Comment by nathandunn** [comment]
I've already done this.  We can do a larger testing sweep once we have stable software up.   We have a large number of these we've already closed and I don't want to make an exception for this one.
