### ISSUE TITLE
Uncategorized tracks should be separated instead of bulked together

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1661]
I am still a little intrigued by the new categorization of tracks. 

It is not intuitive to the user to have to explore under a bulk of 'Uncategorized' tracks to find things such as predicted gene structures ... which are probably what most are looking for in the first place. 

Let us set 'uncategorized' tracks as individual tracks, visible without the need to go into an additional menu and expand them.

**Comment by nathandunn** [comment]
@monicacecilia  Is this what you were thinking? 

<img width="588" alt="screen shot 2017-06-27 at 4 53 33 pm" src="https://user-images.githubusercontent.com/751274/27594150-5ee14046-5b59-11e7-8838-7bd94cfb30b4.png">

**Comment by monicacecilia** [comment]
This is better, yes.
