### ISSUE TITLE
Required updates to the demo server

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1662]
The following modifications are required for the demo installation:

- [x] Remove __Cat__ genome. It does not have any tracks with data. 
- [x] Update data for __Yeast 1__ so the Exonerate predictions can be displayed, or remove the data track all together; it currently serves no purpose. 
- [x] Remove __Yeast 2__.
- [x] Remove __Yeast 3__.
- [x] __Human__ does not have a track with genes - these are all experimental data tracks from various experiments but no gene predictions. Where did all the NCBI predictions go? Also, see https://github.com/GMOD/Apollo/issues/1661
- [x] Either add tracks of data to ___C. elegans___, or remove from demo. It is useless to have this in the demo right now. 
- [x] Either add tracks of data to __dog__, or remove from demo. It is useless to have this in the demo right now. 
- [x] Remove the __pig__ genome; at the moment there are no data tracks being displayed and it is useless that way. 
- [x] Remove the __sheep__ genome; at the moment there are no data tracks being displayed and it is useless that way. 
- [x] Remove the __zebrafish__ genome; at the moment we only have a track of gene models and two tracks with conservation scores, but no additional data, nor aligned gene models from the 'other six' genomes referred to in those conservation tracks. Do we know where those zebrafish tracks came from, by the way? Any chance we can get tracks with conservation scores for human? That would be far more useful - and more pressing. --- and this is at least the third time I've requested them. :bowtie: 
- [x] Also, see https://github.com/GMOD/Apollo/issues/1437
- [x] Remove the nondescript __Fish__ genome.
- [x] Remove the additional two __Mouse__ genomes.
- [ ] Either remove or re-label __'Volvox'__ to __'Volvox mithicus'__, because this is not a real organism. We need to offer information about the artificial nature of these data. 
- [x] remove "Neat" plugins

**Comment by nathandunn** [comment]
Thanks.  This is perfect.

**Comment by nathandunn** [comment]
I think that this is done.  Human data at least should be done in a couple of hours from now.   In general, I just removed data unless we explicitly want something later.

**Comment by nathandunn** [comment]
I'll send the URL

**Comment by nathandunn** [comment]
@monicacecilia   Everything should be done on this.  Please verify and close.

**Comment by monicacecilia** [comment]
@nathandunn, 

By accident, I ran into this: __Nurse RNA-seq reads track is failing__.

![screen shot 2017-07-05 at 3 27 51 pm](https://user-images.githubusercontent.com/1714621/27887630-9902822e-6196-11e7-9f1b-a5367be5364a.png)

It is happening in GroupUn4278, GroupUn1, GroupUn14, GroupUn19, GroupUn193, GroupUn18, and I believe in all other GroupUnxxxx...

It is not happening in all other groups I checked - 1.1, 1.2, 16.4, 1.33. 

Forager RNA-Seq reads track seems ok everywhere I checked.

**Comment by monicacecilia** [comment]
@nathandunn, 
Wrt human data: only mRNA models from GenBank are available now. Please see previous requests from @selewis, including #499, to ensure we have all data we have previously agreed upon. For example, GenBank data only includes something called 'top level mRNA', but no NCBI Reference Sequences (RefSeq) collection from, or 1,000 genomes, clinvar data and dbsnps data also went away (they were ticked as ok on #499). Lastly, still need to get a better understanding and effective ways to display data with conservation scores.

**Comment by monicacecilia** [comment]
@nathandunn,
'Volvox' is still labeled just that. It needs to be relabeled to indicate that the data are simulated, and not real Volvox data. - call it 'imaginary', or 'example', or 'Volvox mithicus'. Please remove the 'Volvox' label.

**Comment by monicacecilia** [comment]
@nathandunn - also, what coding table do you have for 'Volvox'? Or were these data generated? All first and last exons are exhibiting a warning for offensive, non-cannonical splice sites, where Apollo should realize that a CDS is beginning or ending... this seems even more confusing for the mythical creature.

**Comment by nathandunn** [comment]
@monicacecilia  WRT to https://github.com/GMOD/Apollo/issues/1662#issuecomment-313245591 , this is scheduled for https://github.com/GMOD/Apollo/issues/686

**Comment by nathandunn** [comment]
@monicacecilia  WRT to https://github.com/GMOD/Apollo/issues/1662#issuecomment-313250159 its the same as every other organism, i.e., 1.  Its just the sample JBrowse data, which has not changed for awhile.   Is this an error in the data or the interpretation?

**Comment by nathandunn** [comment]
WRT to Volvox and https://github.com/GMOD/Apollo/issues/1662#issuecomment-313249233  Volvox is set as the common name with the Genus and Species set to what you had so that its similar to other organisms.   Feel free to change any part of it further in the admin tab:

https://github.com/GMOD/Apollo/issues/1662#issuecomment-313249233

I'm closing this issue in favor of #499 for the remaining work to to be done on the human server. 

(for clarification, this is work being done on this server: http://34.227.0.63/Apollo2/annotator/index)

**Comment by monicacecilia** [comment]
@nathandunn why would this https://github.com/GMOD/Apollo/issues/1662#issuecomment-313245591 be scheduled for #686? It was working before, and the demo server on the URL you sent is running 2.0.6. Additionally, the Forager reads are working properly, so why would one track work and the other not?

**Comment by monicacecilia** [comment]
@nathandunn wrt https://github.com/GMOD/Apollo/issues/1662#issuecomment-313249233 then it needs to be relabeled to 'fictitious' and be done with it. This is not a real organism and we should not have anything in the label that suggest so.

**Comment by monicacecilia** [comment]
And yes, that's the URL I am currently using. It says current version is 2.0.6. See http://34.227.0.63/Apollo2/1207303521471044981807651805/version.jsp and see below:

![screen shot 2017-07-05 at 4 36 00 pm](https://user-images.githubusercontent.com/1714621/27889266-0dad9b6e-61a0-11e7-9d4a-0ddec16b14df.png)

**Comment by nathandunn** [comment]
@monicacecilia  That was a mistake on my part.    WRT to why, my best guess is that it has no data in that region for that track, but we'll have to investigate (I opened https://github.com/GMOD/Apollo/issues/1677, but forgot to reference it). 

Sorry, I'm going to close this in favor of #499, but forgot to actually do that.
