### ISSUE TITLE
Apollo does not always remember last location

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1663]
Testing 2.0.7: 
- Switching back between organisms, some organisms preserve the last location, others do not. Specifically, Honey bee does not remember the last location, even if editing functions were conducted. It violates 1.3.1, 1.3.3, and 1.3.4 from [Testing Script](https://github.com/GMOD/Apollo/blob/master/docs/TestScript.md).

**Comment by nathandunn** [comment]
I think that this is an artifact of me making the code less aggressive when remembering location (so if you move a LONG way it will remember — or wait a short time).  However, it should store the preference when changing organisms , sequences, logging out, or performing a standard operation as well.  Closing a screen will be a bit harder to manage.

**Comment by nathandunn** [comment]
The workaround for this is that if you actually do annotations (or navigate) it will remember.  The remembering is triggered by movement.    We should improve this though.

**Comment by monicacecilia** [comment]
@nathandunn this is not true. During testing, the actions conducted during annotation did not always trigger the "remembering" part.

**Comment by nathandunn** [comment]
@monicacecilia  I retested it.  It actually always the wrong one even when the right one is in the database.  

Sorry you ran into this.  It *was* working.

**Comment by nathandunn** [comment]
For some reason:

     preferenceService.UserOrganismPreference getCurrentOrganismPreferenceInDB(User user, String sequenceName, String clientToken) {

updates the wrong preference in the database and returns it.
