### ISSUE TITLE
Unable to create sequence alterations.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1665]
### Unable to create a genomic insertion: 

<img width="540" alt="screen shot 2017-06-23 at 2 20 27 pm" src="https://user-images.githubusercontent.com/1714621/27500869-2af131f2-581f-11e7-8831-6334565806eb.png">

### Unable to create a genomic deletion: 
<img width="481" alt="screen shot 2017-06-23 at 2 21 30 pm" src="https://user-images.githubusercontent.com/1714621/27500911-56573c42-581f-11e7-8bd4-4a9f427d64c9.png">

### Unable to create a genomic substitution: 
<img width="505" alt="screen shot 2017-06-23 at 2 22 25 pm" src="https://user-images.githubusercontent.com/1714621/27500925-691d88cc-581f-11e7-9051-ee6e90fcd194.png">

**Comment by nathandunn** [comment]
I'll take a look at that.  Was just working.

**Comment by monicacecilia** [comment]
I've disconnected, and logged back in a few times, refreshed, re-refreshed.... not doing it.

**Comment by deepakunni3** [comment]
@nathandunn This is odd. `getUniqueTrack` was a method added to `SequenceTrack.js` on the 2.1.0 branch. Its not supposed to exist on the master branch.

So its just a typo. `getUniqueTrack` call should actually be `getUniqueTrackName`.

**Comment by monicacecilia** [comment]
Note to self, when fixed, retest: 
- [ ] recalculated ORFs
- [ ] results of sequence alterations
- [ ] ‘Get Sequence’

**Comment by monicacecilia** [comment]
Apparently now I am testing 'closed' tickets, so issuing a reminder to self to test this again next week.

**Comment by monicacecilia** [comment]
Not. so. fast.

``` 
Error Performing Operation
Object of class [org.bbop.apollo.MRNA] with identifier [249090]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.MRNA#249090]
```

![screen shot 2017-06-26 at 1 52 59 pm](https://user-images.githubusercontent.com/1714621/27559830-d5cc0fda-5a76-11e7-9c9f-f693039bbccb.png)

**Comment by monicacecilia** [comment]
@deepakunni3 - did you see this when pushing #1664? If so, did your testing clear this?

**Comment by nathandunn** [comment]
Moni,

This is unrelated.  It is intermittent, but not good.  Can you reopen with another bug and copy that stack trace.  I would say it's 2.0.7.  This can be closed, though you may want to reflag for testing in 2.1.0 if not already covered in the test script. 

Nathan

**Comment by deepakunni3** [comment]
@nathandunn Either way, a PR for the reported issue is ready for test (a simple one-liner).

**Comment by monicacecilia** [comment]
It is not intermittent here;  the error consistently appears. it may be a different 'origin' but it is still an error that hinders the creation of sequence alterations.

**Comment by monicacecilia** [comment]
Updated at #1667.
