### ISSUE TITLE
Still unable to create sequence alterations. 

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1667]
A different issue for the same issue: the inability to create sequence alterations. (Started at #1665)

### From @monicacecilia: 

``` 
Error Performing Operation
Object of class [org.bbop.apollo.MRNA] with identifier [249090]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.bbop.apollo.MRNA#249090]
```

![screen shot 2017-06-26 at 1 52 59 pm](https://user-images.githubusercontent.com/1714621/27559830-d5cc0fda-5a76-11e7-9c9f-f693039bbccb.png)

### From @monicacecilia: 
@deepakunni3 - did you see this when pushing #1664? If so, did your testing clear this?

### From @deepakunni3 
A PR for the reported issue is ready for test (a simple one-liner).

**Comment by nathandunn** [comment]
Confirmed on staging that this was fixed as well as part of #1664.
