### ISSUE TITLE
Implement Functional Testing 

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1668]
Functional testing should be incorporated in the development process. 

The [TestScript.md](https://github.com/GMOD/Apollo/blob/master/docs/TestScript.md) file should be 'translated' for behavior-driven development, for example, using Python libraries and [_behave_](http://pythonhosted.org/behave/).

Some attempt was made at Python libraries for [Selenium](http://www.seleniumhq.org/) in 2015, [as seen here](https://github.com/GMOD/Apollo/tree/master/test/client/selenium_tests). Selenium could be used for implementation.

For an example of successful functional testing using _behave_ for other projects at BBOP, see the overview for [AmiGO testing pages](https://github.com/geneontology/amigo/tree/master/test-app/behave). This is an example of a _behave_ test for the [autocomplete function in AmiGO](https://github.com/geneontology/amigo/blob/master/test-app/behave/05_autocomplete_basic.feature).

![screen shot 2017-06-26 at 3 05 03 pm](https://user-images.githubusercontent.com/1714621/27562311-e0969282-5a80-11e7-85c0-7c781ea0de3e.png)

**Comment by nathandunn** [comment]
Grails has a really nice functional in-house testing schema for this:

https://docs.grails.org/2.5.0/guide/testing.html#functionalTesting

I think 2.1.1 is a good target.  May coincide with Grails 3, but we'll see.   Should also be able to do iFrame work with this as well.

**Comment by monicacecilia** [comment]
@eric is already working on a Selenium-based testing environment for JBrowse. 
@kltm, @cmungall, and I met with @enuggetry today regarding functional testing after I brought it up in lab meeting.

**Comment by nathandunn** [comment]
Yeah, they already in JBrowse and Apollo / client.   Just a matter of where you want to put time into the rest of it.  This is important, but I think that testing (e.g., multiple users) I think is still a higher priority.

**Comment by monicacecilia** [comment]
@nathandunn . How does one create functional tests using Grails? Do you have documentation on this? 
For now I am defining the testing to be done with the _behave_ / Selenium options since this is something already in progress with BBOP, it is well documented, it is demonstrated to be relatively easy to build, and it is also being developed at JBrowse. Pragmatically, these options for functional testing allow for natural language to guide the tests, and I find that convenient for the test writer.

**Comment by monicacecilia** [comment]
I think this is of the utmost importance, for two reasons of immediate importance: 
1. it requires a lot of time from the only tester we have (yours truly)
2. Most importantly, the lack of these functional tests is hindering the advancement of development, as it is only until I get into the functional testing that many errors are discovered. I think it is good practice and I think it will be of tremendous use going forward. We cannot afford the numerous errors we see from code that is 'supposed to have fixed function _x_'.

**Comment by nathandunn** [comment]
Please see the [Geb link I posted](https://github.com/GMOD/Apollo/issues/1668#issuecomment-311201802).   That's how you do them in Grails.  It also uses Selenium, but within the Grails framework and is the best-practice solution for doing it.  

Not disagreeing with you, but we don't have a lot of dev time either, so we have to be careful with how we allocate time.   These tests tend to be the most expensive to write and run, so just have to be sure that we cover a lot of ground not covered by other tests when we do write them.

**Comment by monicacecilia** [comment]
I am very well aware of the shortage of time from developers. I believe adding functional testing will actually also allow us to optimize testing to reduce the load on developers' time.

**Comment by cmungall** [comment]
it's always worth spending time on unit tests.

@kltm demonstrated the behave test system we use in all our other projects, should be straightforward to use for jbrowse/apollo

**Comment by nathandunn** [comment]
@cmungall  We have plenty of unit and integration tests.   https://travis-ci.org/GMOD/Apollo/builds/247304224 

I think roughly: 81 unit tests, 89 integration tests X 3 databases + whatever JBrowse runs.  Would love to write more.  Just have to measure time against writing another type of test suite.

**Comment by monicacecilia** [comment]
@nathandunn - I can see that http://gebish.org/ is likely a very practical solution for the developer. 

In the spirit of what other BBOP projects have already accomplished, and the parameters we discussed as far back as 2 years ago, I think that one positive thing _behave_ offers is the ability to bring natural language to preparing the instructions for the test (say, a biologist like me can write something like the TestingScript),  and then, putting some additional time, developers and expert curators can combine forces to prepare a functional test that is both human readable and useful to test the software in a more automated way. It would be a combined effort, which I think would also optimize the use of time. 

--

Correct, we do have unit tests and integration tests. @cmungall is referring to functional tests here, specifically giving as examples some of those I pointed out at the beginning of the issue, from the AmiGO repository.

**Comment by nathandunn** [comment]
I think that writing the tests out is a really great idea and should absolutely be done.  If you look at a lot (but not all) of our tests, we follow the spock format and do just that.  In general this is a great way to start tests and these get turned into requirements. 

Unfortunately, I just don’t think that NLP really works that well in practice, as all of those NLP terms have to get turned into code (by the developer) in a process that may or may not work seamlessly.  Running / writing tests also requires a fair bit of iteration on the setup, which makes it easier for devs to run and interpret except in very simple cases.  

If you want to explore writing and running tests in Amigo / Behave first, that is fine, I’ve just never seen it be especially efficient in practice and I don’t see a lot of groups I’ve worked with using them actively.  

Functional / Behavioral Tests, however are great and I think we should definitely keep this on our radar.   If you could write a few NLP statement tests for this, I can take a look at converting them to geb.

**Comment by kltm** [comment]
Just stepping here. I don't think anybody is proposing NLP, as awesome as that would be.

Geb and Spock are nice, but not really abstracted functional behavior testing--the abstracted being the important part here. See the fork for an almost working example for Apollo against icebox, plus documentation:

https://github.com/kltm/Apollo/tree/master/test/behave

(you have to have a modern working phantomjs in your path for that to get very far)

The idea is to have the application-level functional tests written in a slightly stilted "natural language" that is clear to users and programmers. The users write the tests using this language and the programmers make the implementation. See: http://pythonhosted.org/behave/

We are using this widely in Monarch, GO, and I'm selling it to JBrowse now. They are lovely in practice and very effective.

**Comment by kltm** [comment]
As a more concrete example, here's one from Monarch (https://github.com/monarch-initiative/monarch-app/blob/master/tests/behave/maui_analyze.feature)

```
 Scenario: adding "allergy" and "asthma" to analyze phenotype results in "Ichthyosis Vulgaris"
    Given I go to page "/analyze/phenotypes"
     and I type "aller" into the phenotype analyze search
     and I wait until "Allergy" appears in the autocomplete
     and I click the autocomplete item "Allergy"
     and I type "asth" into the phenotype analyze search
     and I wait until "Bronchial asthma" appears in the autocomplete
     and I click the autocomplete item "Bronchial asthma"
     when I submit analyze phenotype
     then the document should contain "Asthma, Susceptibility to"
```

Very readable by developers and users. Each statement directly maps to an implementation under the hood written by the developers for the purpose of creating this test suite. Example implementations are like (https://github.com/monarch-initiative/monarch-app/blob/master/tests/behave/steps/selenium-basic.py):
```python
@given('I go to page "{page}"')
def step_impl(context, page):
    #print(context.browser.title)
    context.browser.get(context.target + page)
```

**Comment by nathandunn** [comment]
I get it.  It basically mirrors spock (given, when, where, etc.), but there are "human readable" abstractions.   I'm glad it works for you.  I'm not going to happen for a few reasons:

1 - it introduces a python framework into a non-python stack.  There are many JVM tools that do exactly the same thing and work readily within the Grails / JVM stack.
2 - I think that making the code and the English sentences the same hurts the effectiveness of both.  In general we comment each given /when / then in English so you have an idea of what is happening at each step.   As such, I just don't feel as the cost-benefit is there, especially if you have to write your own DSL. 
3 - Gebish + Grails is a well-supported stack and I what I see used as part of best-practices within the framework.  

Anyway, I appreciate the input, but its not going to happen outside of Geb with everything I got going on.

**Comment by nathandunn** [comment]
Function testing will be completely different (and easier) with react in JBrowse 2.  closing this for now.
