### ISSUE TITLE
Tracks "ProjectionGrid" and "ProjectionBoundary" should be relabeled. 

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1673]
Instead, label as 'Coordinates' and 'Boundaries', or 'Assembly Coordinates' and 'Assembly Boundaries.'

**Comment by nathandunn** [comment]
- [ ] remove these from honeybee on icebox and the demo server

When these are added manually, they should be in annot.json and hidden, but that will be for later versions.

**Comment by nathandunn** [comment]
Noted, was looking at the wrong server.   This will be applicable to the 2.1.2 milestone.
