### ISSUE TITLE
Track with grid (coordinates) for scaffold should re-appear at the top after 'Hide / Show' action.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1674]
The track currently labeled as 'ProjectionGrid' (see #1673), should re-appear in the same place after hiding and revealing again. 

Before hiding: 
<img width="542" alt="screen shot 2017-06-27 at 3 51 17 pm" src="https://user-images.githubusercontent.com/1714621/27613561-15c866ee-5b51-11e7-8bf8-bc020fe6f89e.png">

After hiding and revealing again, coordinates appear under the _User-created Annotations_ area: 
<img width="508" alt="screen shot 2017-06-27 at 3 51 00 pm" src="https://user-images.githubusercontent.com/1714621/27613571-1e1c33fc-5b51-11e7-847e-f284d5762609.png">

**Comment by nathandunn** [comment]
@monicacecilia  I see what is wrong.  Should be testing the server 2-1-0 (not 2-1):

http://34.227.0.63/Apollo2-1-0/annotator/index

Those tracks don't show up for 2-1-0 (i.e. 2.1.0 milestone).  I removed that server from icebox to avoid any future further confusion.

**Comment by nathandunn** [comment]
This will be applicable to 2.1.2, but not 2.1.0.
