### ISSUE TITLE
Problem with naming new annotations after dragging them into User-created annotations region

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1679]
This is very confusing. I am finding that Apollo is incorrectly naming New gene models when I drag them into User created Annotations area, And they are being labeled as consecutive even though Not all of them belong to the same gene model. see image for coordinates Group16.4:1818581..1848360 (29.78 Kb) (honey bee). [See logged in URL here](http://34.227.0.63/Apollo2/annotator/loadLink?loc=Group16.4:1818580..1838740&organism=3836&tracks=Official%20Gene%20Set%20v3.2).

![screen shot 2017-07-06 at 4 45 46 pm](https://user-images.githubusercontent.com/1714621/27937457-0391f298-626c-11e7-9f02-2b1c61c32a13.png)

Notice also that the names are not corresponding to the original evidence used to start them, but rather they are being added as group 16.4 a, b, c, d, etc.

And then, the other gene model is being labeled correctly. Can you look into this?

**Comment by monicacecilia** [comment]
PS: I am dictating this to the computer so please forgive the typos.

**Comment by monicacecilia** [comment]
By the way, after deleting all gene models and re-dragging them back, it actually corrected the names. This maybe something about connectivity?

**Comment by nathandunn** [comment]
I couldn't reproduce this.  Might be due to connectivity (e.g., an overlapping gene that you couldn't see?).
