### ISSUE TITLE
Add sequence search track function is not retrieving amino acid strings

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#168]
Unable to locate an amino acid sequence using the File --> Add sequence search track function. 
I was able to visualize results from nucleotide strings, but the function is not retrieving amino acid strings in any direction. I tried copying a string of at least 100 aa, typing strings of shorter length, in both directions. I was not able to retrieve the strings I was able to see in the sequence above. 

Not sure if related, but while conducting the searchers, *SOMETIMES* the following errors would appear

Refused to get unsafe header "Content-Range"	dojo.js:977 
(anonymous function)	dojo.js:977 
Refused to get unsafe header "Content-Range"	dojo.js:977 
(anonymous function)	dojo.js:977 
(anonymous function)	dojo.js:121 

In the figure, the last two amino acid strings on the newly created tracks are also visible above on the reference sequence. The nucleotide strings are visible and also found on the newly created tracks using the "Add sequence search track" function.
![screen shot 2015-02-18 at 3 23 38 pm](https://cloud.githubusercontent.com/assets/1714621/6259266/7a26410a-b785-11e4-9a36-129414663b93.png)

**Comment by cmdcolin** [comment]
Weird, I can look into it. Seems to not affect 1.0.3 and is new

**Comment by monicacecilia** [comment]
Yeah, it was not there in the last release. I checked and it worked then.

**Comment by cmdcolin** [comment]
this is technically a jbrowse bug introduced in 1.11.6. my bad. if you want to cross post it there feel free

**Comment by cmdcolin** [comment]
the issue should be limited to the described function (not able to search amino acids due to codontable implementation change in 1.11.6)

**Comment by cmdcolin** [comment]
in case there is interest in fixing this in the new webapollo we could add a "hotfix" to the jbrowse repo during build...

**Comment by monicacecilia** [comment]
Yes, this must be fixed before 1.0.4 can be officially released, so we need a patch on JBrowse.

**Comment by cmdcolin** [comment]
I can add a patch inside apollo to fix this using the "monkey patching" technique, commonly used for fixing "bugs" in dependencies...

    +    monkeyPatchRegexPlugin: function() {
    +        require(['RegexSequenceSearch/Store/SeqFeature/RegexSearch'], function(RegexSearch) {
    +            RegexSearch.prototype.translateSequence=function( sequence, frameOffset ) {
    +                var slicedSeq = sequence.slice( frameOffset );
    +                slicedSeq = slicedSeq.slice( 0, Math.floor( slicedSeq.length / 3 ) * 3);
    +
    +                var translated = "";
    +                var codontable=new CodonTable();
    +                var codons=codontable.generateCodonTable(codontable.defaultCodonTable);
    +                for(var i = 0; i < slicedSeq.length; i += 3) {
    +                    var nextCodon = slicedSeq.slice(i, i + 3);
    +                    translated = translated + codons[nextCodon];
    +                }
    +
    +                return translated;
    +            }
    +        });
    +     }

Otherwise I can just release a whole new jbrowse version...

**Comment by cmdcolin** [comment]
It'll be monkey patched for now since 1.0.4 should be out the door. patch committed.

**Comment by nathandunn** [comment]
I confirmed it is working, but will send it back to moni when we do RC3

**Comment by monicacecilia** [comment]
Good. It is working again. 
@cmdcolin did you already create an issue on the JB repo? or a reminder? should I?

**Comment by cmdcolin** [comment]
Ah I'll do that.

**Comment by monicacecilia** [comment]
Thank you.

**Comment by nathandunn** [comment]
@cmdcolin   Can you re-review this monkey-patch and send it back as ready with a patch if needed.  

Thanks.

**Comment by cmdcolin** [comment]
Looks good to me

![screenshot-localhost 8080 2015-04-12 12-37-16](https://cloud.githubusercontent.com/assets/6511937/7106723/cd6f264c-e110-11e4-82ca-b482d450d447.png)

**Comment by monicacecilia** [comment]
This operation is working as expected in "2.0.0". Thanks! :heavy_check_mark:
