### ISSUE TITLE
Unable to revert name after changing annotation type AND changing overlapping model

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1680]
To reproduce:

- Drag an annotation to Uc-A area (e.g GB51360-RA)
- Split annotation somewhere in the middle, separating it into two resulting gene models. 
- Change annotation type for half of the annotation to a revertible type, e.g. ncRNA, tRNA, etc. 
- Drag a second copy of the original gene model you dragged up, making sure the CDS overlaps with the annotation for which you changed the type. 
- Revert the change of annotation type for the part of the model that you changed. 
- Result: both halves of the split annotation now have a longer version of the unique ID instead of the name they had when they were originally dragged. For example: 
![screen shot 2017-07-06 at 5 14 32 pm](https://user-images.githubusercontent.com/1714621/27937796-98b57fbe-626e-11e7-8399-4e404897253a.png)

**Comment by nathandunn** [comment]
This has more to do with the way history handles naming.   I think this will have to wait until a later release, though.
