### ISSUE TITLE
Unable to change coordinates using 'Coding' tab for exons with non canonical splice site

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1683]
Why am I not able to change the boundaries of an exon with a non canonical splice site using the 'Coding' tab? I did not know this was a 'rule' - where does this come from? 

Note that the arrows to move the boundaries for this exon are disabled:

![screen shot 2017-07-06 at 5 47 25 pm](https://user-images.githubusercontent.com/1714621/27938510-43c3626e-6273-11e7-8b90-e5c0cbafbf36.png)

**Comment by monicacecilia** [comment]
This places an exception on  13. 1. 2. 2) from Testing Script. See https://github.com/GMOD/Apollo/issues/1669

**Comment by nathandunn** [comment]
Non-canocical splice sites and CDS's are not editable in the interface by design.   Maybe we can do a UI-change later.  

Confirmed that we can change the exon on either end whether or not a splice site is present.
