### ISSUE TITLE
Unable to change boundaries for TE and RR using 'Details' panel.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1684]
Transposable Elements (TE) and Repeat Regions (RE) do not have 'exons', and thus no child elements for those annotations; is this the reason why the 'Details' panel in the bottom half of the 'Annotator Panel' does not have a 'Coding' tab where curators can change the coordinates on a base pair by base pair manner? 

Note that it is not possible to select a child element (sub-type annotation?) in the list of 'Annotations' for these annotation types. 

![screen shot 2017-07-06 at 5 53 31 pm](https://user-images.githubusercontent.com/1714621/27938621-0d02dbdc-6274-11e7-868b-f15de801fd70.png)

If so, we should remove the note "13.1.2.3) Repeat for Repeat Region and Transposable Element" from the Testing Script.

**Comment by deepakunni3** [comment]
@monicacecilia Yes, that is correct.

Coding tab is only for gene features.

**Comment by monicacecilia** [comment]
Brilliant. Thanks! I updated the testing script accordingly.
