### ISSUE TITLE
readthedocs link

### ISSUE THREAD

**Issue by alpapan** [GMOD/Apollo#1687]
This link works
http://genomearchitect.readthedocs.io/en/latest

but this one does not
http://genomearchitect.readthedocs.io/en/stable
[permission denied]

the second link is the one advertised in some places 

thanks!
a

**Comment by nathandunn** [comment]
Thanks @alpapan .   We were having some readthedocs trouble and missed this.  

I think I fixed them here and in the codebase: http://genomearchitect.org/

Was there another place they were?   Re-open or mention and I'll fix those as well.  Thanks.
