### ISSUE TITLE
Mislabeled column in page with Changes log

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#169]
In the "changes" page there is a column header labeled as "Group" where the identifiers of the gene and mRNA features appears (if assigned). Also, the group/scaffold/chromosome appears listed under the "Track" column. I don't understand why has the name of the gene/mRNA been labeled as "Group".

http://icebox.lbl.gov/WebApolloDemoStaging/changes

![screen shot 2015-02-18 at 4 50 17 pm](https://cloud.githubusercontent.com/assets/1714621/6260081/b12fb632-b78e-11e4-9788-0155c20201fa.png)

**Comment by nathandunn** [comment]
@monicacecilia   I think that the column Track should be "Sequence" and the column Group should be "Annotation".  Agree?

**Comment by monicacecilia** [comment]
@nathandunn agreed. :+1:

**Comment by monicacecilia** [comment]
brrrrrrilliant! 
Thanks!
