### ISSUE TITLE
Compiling error /  [groovyc] Invalid commandline usage for javac

### ISSUE THREAD

**Issue by cgandini** [GMOD/Apollo#1692]
Hi, I am trying to install Apollo (latest version) in my Mac OS Sierra. After checking that all pre-requisitis were installed, I run ./apollo run-local, however the compilation failed (some folder were created like web-app and bin). My Java version is 1.8 so I do not understand the error. Also the setup.log file is empty.

Can you help me?

Thanks in advance!

Carolinas-MacBook-Pro:Apollo-2.0.6 carolinagandini$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Carolinas-MacBook-Pro:Apollo-2.0.6 carolinagandini$ javac -version
javac 1.8.0_121

**Apollo Bash Output**
_...
BUILD SUCCESSFUL

Total time: 4 mins 17.756 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.11/userguide/gradle_daemon.html
Jul 14, 2017 12:08:39 AM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
WARNING: Module [groovy-all] - Unable to load extension class [org.codehaus.groovy.runtime.NioGroovyMethods]
Jul 14, 2017 12:08:39 AM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
| Compiling 15 source files
  [groovyc] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  [groovyc] Invalid commandline usage for javac.
  [groovyc] javac: invalid source release: 1.8
  [groovyc] Usage: javac <options> <source files>
  [groovyc] use -help for a list of possible options
  [groovyc] 
  [groovyc] 
| Compiling 15 source files.
| Error Compilation error: startup failed:
Invalid commandline usage for javac.
javac: invalid source release: 1.8
U_sage: javac <options> <source files>
use -help for a list of possible options_

1 error_

**Comment by nathandunn** [comment]
What do you get when you do:

% echo JAVA_HOME

?

**Comment by cgandini** [comment]
If I put echo JAVA_HOME I get JAVA_HOME instead of the location of the jdk. If I put echo $JAVA_HOME I get nothing.

**Comment by cgandini** [comment]
which java gives: 
/Users/carolinagandini/.jenv/shims/java

**Comment by cgandini** [comment]
I set JAVA_HOME by "export JAVA_HOME=$(/usr/libexec/java_home)" and now is running! thanks!

Carolina

**Comment by nathandunn** [comment]
Glad it worked out.
