### ISSUE TITLE
evaluate local track addition for reverse complement

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1695]
when using "file -> open" evaluate how tracks behave in reverse complement view

- [ ] bigwig
- [ ] BAM 
- [ ] VCF
- [ ] GFF
- [ ] JSON?

**Comment by nathandunn** [comment]
I don't think we want to handle this in 2.1.0.

**Comment by monicacecilia** [comment]
@nathandunn do you mean to say that we will remove the ability to open files to display when the user has reverse complemented a scaffold?

**Comment by nathandunn** [comment]
We haven't tested it. I think this is related to the in-memory adapter as well, but I haven't looked at the implementation.  

I'm not sure how common this functionality is used in the wild.   

If its used more often then I suspect, then we can test it for 2.1.0.

**Comment by monicacecilia** [comment]
> I'm not sure how common this functionality is used in the wild.

I am aware of many curators who use sequencing reads to be aligned locally when none has been made available for the project.

**Comment by nathandunn** [comment]
okay.  We'll take a look at it then.

**Comment by nathandunn** [comment]
Can confirm that these do not work.    At least not the bigwig tracks.

**Comment by nathandunn** [comment]
I'm not sure if the issues are identical to #1703, but I sense they are.    Will have to do some more digging to see.  Will make comments over there.
