### ISSUE TITLE
BAM file not displaying reads

### ISSUE THREAD

**Issue by cgandini** [GMOD/Apollo#1698]
Hi! I loaded the fasta and bam files as it is described in the "data generation pipeline". However I can not see the reads nor coverage of my reference sequence. 

<img width="855" alt="screen shot 2017-07-14 at 2 24 38 pm" src="https://user-images.githubusercontent.com/25402201/28223131-9039d3fc-68a0-11e7-9812-e827679c9a66.png">

Also the search tool is not working. Which database I have to set as blast database? Do I have to add path to the makeblastdb output of my reference sequence?

Thanks in advance!

Carolina

**Comment by nathandunn** [comment]
Hey, I think this is a great question.   Can you subscribe to the mailing list (see instructions about "this email to our server") and send this exact question to the "apollo@lists.lbl.gov".   I will make sure to reply there.   

Thanks.
