### ISSUE TITLE
Support of community level private evidence tracks

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#17]
Some of our annotation communities have private data they would like to make available to the annotators but not the public.  Could you implement a category of track that is only visible if you are logged in and have read permissions?

**Comment by nathandunn** [comment]
@childers  @littlebunch  FYI . .

**Comment by nathandunn** [comment]
Need to also restrict access to the tracks if not in the permissions area.

**Comment by erasche** [comment]
maybe xref https://github.com/GMOD/Apollo/issues/1499#issuecomment-331816493 I bet my previous users would love this feature and my future users (once we get this other bureacratic type crap handled) will also.
