### ISSUE TITLE
export CDS fails

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#171]
from nicolas.francillonne@versailles.inra.fr:

I'm working on an instance of WebApollo-2014-04-03 and I wish to export for each annotation CDS fasta sequence.

On my "selectTrack.jsp" I select all my track then in file ==> export ==> Fasta I download my CDS.
Then I get "Error writing CDS"

I can download all my Gff3, cDNA without issue and when I select some of my reference sequence instead of all of them it works.

Here the error I get when trying to download all CDS (same error happen when I try to download "peptide".

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
   at java.lang.String.substring(String.java:1904)
   at org.gmod.gbol.bioObject.CDS.getResidues(CDS.java:158)
   at org.bbop.apollo.editor.session.AnnotationSession.getResiduesWithAlterations(AnnotationSession.java:253)
   at org.bbop.apollo.editor.session.AnnotationSession.getResiduesWithAlterationsAndFrameshifts(AnnotationSession.java:226)
   at org.bbop.apollo.web.dataadapter.fasta.FastaIO.getUpdatedSequence(FastaIO.java:112)
   at org.bbop.apollo.web.dataadapter.fasta.FastaIO.writeFeatures(FastaIO.java:53)
   at org.bbop.apollo.web.dataadapter.fasta.FastaJEDatabaseIO.writeFeatures(FastaJEDatabaseIO.java:48)
   at org.bbop.apollo.web.dataadapter.fasta.FastaDataAdapter.write(FastaDataAdapter.java:207)
   at org.bbop.apollo.web.dataadapter.IOService.doPost(IOService.java:191)

Have you got any ideas  ?

**Comment by nathandunn** [comment]
Transcript transcript = getTranscript();
String residues = transcript.getResidues();
int begin;
int end;
transcript.convertSourceCoordinateToLocalCoordinate(getFeatureLocation().getFmax());
if (getFeatureLocation().getStrand() == -1) {
    end = transcript.convertSourceCoordinateToLocalCoordinate(getFeatureLocation().getFmin()) + 1;
    begin = transcript.convertSourceCoordinateToLocalCoordinate(getFeatureLocation().getFmax()) + 1;
}
else {
    begin = transcript.convertSourceCoordinateToLocalCoordinate(getFeatureLocation().getFmin());
    end = transcript.convertSourceCoordinateToLocalCoordinate(getFeatureLocation().getFmax());

}
return residues.substring(begin, end);

**Comment by nathandunn** [comment]
gist: https://gist.github.com/nathandunn/3f83511fbf6060bba700

**Comment by nathandunn** [comment]
FYI @cmdcolin

**Comment by cmdcolin** [comment]
A place where it would get to simply returning -1 would be in convertSourceCoordinateToLocalCoordinate in AbstractSingleLocationBioFeature but  CDS.getTranscript()==null in the stack trace to even go to this location. I tried loading the given GFF myself to see what the deal was but couldn't reproduce the error. Maybe I would ask what the "history" on the given feature is to see if a strange operation happened

**Comment by cmdcolin** [comment]
Actually there are definitely multiple paths to just getting -1 there, but it's not clear from the stack trace. Perhaps we need to check for -1 and throw a better error, because it seems like some code is returning -1 as an error code and it's not being caught

**Comment by nathandunn** [comment]
I think that it is probably an orphaned CDS being exported.   

Nathan

**Comment by nathandunn** [comment]
@monicacecilia  @cmdcolin   I am clearing this from the release schedule for now.  I doubt it will involve a bug-fix, but we can cross that bridge when we get it it.

**Comment by monicacecilia** [comment]
:+1:

**Comment by nathandunn** [comment]
@monicacecilia   Can we close this for now?
