### ISSUE TITLE
remove unnecessary printlns

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1714]
Remove all of the code warnings.  Mostly fixing types and removing semicolons.

**Comment by deepakunni3** [comment]
@nathandunn Perhaps a better exception handling mechanism too? A service that handles exceptions and just sends out Enums (that abstract the exception) to the client instead of the entire stack trace.

**Comment by nathandunn** [comment]
@deepakunni3  Agreed, but I haven't run into this.  Could you create a separate issue for this with how you reproduced it? 

It should propagate the error message only, but no stack trace (which is what I usually see).

**Comment by deepakunni3** [comment]
@nathandunn Oh no. I am not saying that I saw it in 2.0.7. 
I am proposing to develop a better way of handling errors and exception.

**Comment by nathandunn** [comment]
@deepakunni3  Oh, I see.  Yeah, that's not a bad way to do it (i.e., error codes), but it will have to wait until another release.  Even with error codes, though, you'll still want to create custom messages on the backend as well.   Either way, we should never see a stack trace on the front-end.  

If you want to put the proposal in another GH issue that would be great.

**Comment by deepakunni3** [comment]
@nathandunn Okay, I'll come up with a proposal and create an issue with ways we can go about handing this. And yes, it needn't be part of this release :)

**Comment by monicacecilia** [comment]
Dear @deepakunni3 - did that proposal materialize? And if so, is there an issue?

**Comment by deepakunni3** [comment]
@monicacecilia No, I haven't thought about it much. But it doesn't block the current issue in any way.

**Comment by monicacecilia** [comment]
hooray! 🎆
