### ISSUE TITLE
Rename "Edit Annotation" menu item back to "Information Editor"

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#172]
Don @nathandunn 

The "Edit Annotation" item from the right-click menu (of an annotation) needs to be renamed back to "Information Editor". 

The item does not allow annotators to modify the structural annotation per se, but to add metadata to the annotation (such as DBXRefs, PubMedIDs, comments, GO terms, etc) so "Information Editor" as it appears in the title of the dialog box is more appropriate.

Thanks! 

![screen shot 2015-02-19 at 1 29 51 pm](https://cloud.githubusercontent.com/assets/1714621/6276513/4e6528c6-b83c-11e4-9f73-17309cd3230d.png)

**Comment by nathandunn** [comment]
How about “Edit Information” or preferably “Edit Metadata”.  

I don’t think that its exactly wrong as “Edit Annotation” as we only show what you can edit.   

I just don’t want to have a “noun” there.  

Nathan

**Comment by monicacecilia** [comment]
"Edit Information"

"Show History"

**Comment by nathandunn** [comment]
ready for testing

**Comment by monicacecilia** [comment]
Looks faaaabulous. :+1:

**Comment by nathandunn** [comment]
Will have to have @monicacecilia  retest now that I've refixed.

**Comment by cmdcolin** [comment]
Updated the text to match 1.0.4  so it says "Edit Information (alt-click)"

**Comment by monicacecilia** [comment]
Still faaaaaabulous. Thanks! :+1:
