### ISSUE TITLE
Most data types in 'Volvox' are not being displayed correctly in demo server

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#1720]
@nathandunn 

Testing on http://apollo.berkeleybop.io/Apollo-staging/annotator/index I am getting 404 errors for most data types. 

![screen shot 2017-08-01 at 4 53 15 pm](https://user-images.githubusercontent.com/1714621/28851888-5c1bd820-76da-11e7-9da0-83bc0175334d.png)

The list of tracks that are not being displayed correctly is shown in the figure - see those with the blue 'Hide' button on the left. 
![screen shot 2017-08-01 at 4 56 31 pm](https://user-images.githubusercontent.com/1714621/28851923-889b0dda-76da-11e7-9498-ed496096296d.png)

**Comment by nathandunn** [comment]
@monicacecilia   These should be working now.  The data was just missing on that server.  I also removed most of the organisms with bad data (I will remove mouse shortly)

**Comment by monicacecilia** [comment]
@nathandunn brilliant! I will test again when the serves have been updated. Thanks!

**Comment by nathandunn** [comment]
I have a feeling you're not retesting this, but if you are, feel free to re-open.
