### ISSUE TITLE
Add date created field to Changes report

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1727]
* Search [mailing list](http://gmod.827538.n3.nabble.com/Apollo-f815553.html) or email list ```apollo@lists.lbl.gov``` if a general setup question. 

* Provide what you were doing and what you expected to see.  Screenshots, directory, config files are a plus if relevant.
 I was trying to determine which and how many annotations were created within a date range.  The current changes report shows the last updated date.
* Provide the javascript console log output generated from the action. 
 N/A
* Provide the server log output generated from the action (typically ```catalina.out```).
 N/A

**Comment by nathandunn** [comment]
@childers  See if this does what you want it to do.
