### ISSUE TITLE
'Cannot get property featureLocation' error upon undo operation

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1748]
Encountering the following error: `Cannot get property ‘featureLocation’ on null object`.

To reproduce, Add GB42168-RA
![screen shot 2017-09-01 at 2 34 28 pm](https://user-images.githubusercontent.com/4530272/29985089-1fb3a474-8f23-11e7-86b9-64d45c19a1f8.png)

Split the transcript between its 2nd and 3rd exon
![screen shot 2017-09-01 at 2 34 41 pm](https://user-images.githubusercontent.com/4530272/29985106-2f5bf066-8f23-11e7-8e01-130e5ee2f5f7.png)

Delete the transcript fragment on the right and perform an undo operation on the left most transcript fragment
![screen shot 2017-09-01 at 2 35 43 pm](https://user-images.githubusercontent.com/4530272/29985117-3d5940c4-8f23-11e7-9044-3db7bde00e9d.png)

Undo operation works as intended
![screen shot 2017-09-01 at 2 35 52 pm](https://user-images.githubusercontent.com/4530272/29985135-4b05693c-8f23-11e7-8707-667c98ac7082.png)

Now, split the transcript again between its 2nd and 3rd exon
![screen shot 2017-09-01 at 2 36 09 pm](https://user-images.githubusercontent.com/4530272/29985166-665f1836-8f23-11e7-9b69-d2793b9228b9.png)

This time, delete the left transcript fragment and perform an undo operation on the right most transcript fragment
![screen shot 2017-09-01 at 2 36 33 pm](https://user-images.githubusercontent.com/4530272/29985200-8bfd1566-8f23-11e7-8d99-ca33446ac379.png)

End up with the an error.

**Comment by nathandunn** [comment]
Just a follow-up.  Sometimes these tests work and sometimes they fail as the history does not seem consistent for some reason:

|Running 15 integration tests... 99 of 99
 <>Failure:  |
 <>we should be able to do a split THEN merge and undo and then redo it(org.bbop.apollo.FeatureEventServiceIntegrationSpec)
 <> |
 <>Condition not satisfied:
 <>
 <>history788Array.size() == 2
 <>|               |      |
 <>|               3      false
 <>[[date:9/1/17 9:49 PM, editor:test@test.com, features:[[owner:test@test.com, parent_name:GB40788-RA, uniquename:b6a532f6-e518-49b4-b64d-9c696ee5651f, type:[cv:[name:sequence], name:mRNA], parent_type:[cv:[name:sequence], name:gene], date_creation:1504302548821, sequence:Group1.10, children:[[owner:None, parent_name:GB40788-RA-00001, uniquename:78bcd9c7-4534-4876-8186-b5d9f8cbb1a9, type:[cv:[name:sequence], name:exon], parent_type:[cv:[name:sequence], name:mRNA],

**Comment by nathandunn** [comment]
Just a follow-up.  Sometimes these tests work and sometimes they fail as the history does not seem consistent for some reason:

Worked for H2, but not the other ones (well, mysql npm choked), might have to do with ordering, will re-run:


```
Running 15 integration tests... 99 of 99
 Failure:  |
 we should be able to do a split THEN merge and undo and then redo it(org.bbop.apollo.FeatureEventServiceIntegrationSpec)
  |
 Condition not satisfied:
 
 history788Array.size() == 2
 |               |      |
 |               3      false
 [[date:9/1/17 9:49 PM, editor:test@test.com, features:[[owner:test@test.com, parent_name:GB40788-RA, uniquename:b6a532f6-e518-49b4-b64d-9c696ee5651f, type:[cv:[name:sequence], name:mRNA], parent_type:[cv:[name:sequence], name:gene], date_creation:1504302548821, sequence:Group1.10, children:[[owner:None, parent_name:GB40788-RA-00001, uniquename:78bcd9c7-4534-4876-8186-b5d9f8cbb1a9, type:[cv:[name:sequence], name:exon], parent_type:[cv:[name:sequence], name:mRNA], 

```
