### ISSUE TITLE
Auth problem with status/cannedX API

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#1759]
I'm making some Arrow tests with 2.0.7, and I have a problem when trying to list/add/update/delete statuses, or canned comments/keys/values (xref #1507).

My apollo server is configured to authenticate with REMOTE_USER

I get a "Not authorized" html page instead of getting the expected json content.

I think the problem comes from the `beforeInterceptor` in https://github.com/GMOD/Apollo/blob/master/grails-app/controllers/org/bbop/apollo/CannedCommentController.groovy#L25 (same for the other status/canned controllers)

When commenting it, I don't get auth problem anymore.

I guess the interceptor should be used only for not REST actions, but I have no clue how to do it

**Comment by abretaud** [comment]
By the way, if you're interested (and @erasche too!), I intend to use it [in this bootstrap script](https://github.com/abretaud/docker-apollo/commit/07420ac820eaa375ccb1df23a7178407b3e783d7) on my custom apollo image.

**Comment by erasche** [comment]
Excellent @abretaud, love arrow in the apollo image :) makes complete sense.

**Comment by erasche** [comment]
If you're using those APIs, could you document them for arrow? https://github.com/galaxy-genome-annotation/python-apollo/blob/master/apollo/status/__init__.py

**Comment by abretaud** [comment]
Sure, I'll document it!

**Comment by nathandunn** [comment]
@abretaud  Is that REMOTE_USER an admin user?   If not, and you set it as an admin user does it work?

**Comment by nathandunn** [comment]
My guess is that by default when creating the user it does "user" level permissions, which would give the error you suggest.     If not, let me know and I'll look into it further.

**Comment by abretaud** [comment]
Hum, no, I use the APOLLO_ADMIN_EMAIL and APOLLO_ADMIN_PASSWORD to run arrow, and it has the admin level permission

So my apollo is configured to use remote_user, but here I use the only user which is not remote (and maybe the `beforeInterceptor` doesn't like it?)

**Comment by nathandunn** [comment]
What does your config look like for authentication?      

What is *supposed* to happen is that if the REMOTE_USER fails, it should use the next authentication mechanism.  Completely possible that I didn't test this specific use-case, though.

**Comment by abretaud** [comment]
My conf looks like this:
```
    authentications = [
        [
            "name":"Remote User Authenticator",
            "className":"remoteUserAuthenticatorService",
            "active":true,
            "params":["default_group": "annotators"]
        ],
        [
            "name":"Username Password Authenticator",
            "className":"usernamePasswordAuthenticatorService",
            "active":true,
            "params":[]
        ]
    ]
```

The full conf is there: https://github.com/abretaud/docker-apollo/blob/bipaa/apollo-config.groovy

**Comment by nathandunn** [comment]
That looks perfect.  I'll take a look and thanks for providing the docker-apollo stuff.  I agree that arrow should be in there docker-apollo image, as well.
