### ISSUE TITLE
wishlist from testing of remote API

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1762]
- it would be great to have support for trackList2.json so we can add per-track metadata when we upload tracks. I.e. for support of hierarchical track selector at some point in the future.
- This feature is nice as an admin-only thing, but essentially uninteresting since in the overwhelming majority of cases apollo admins already have physical access to the server. I would argue that sites should be able to configure the required permission level for creating organisms and adding tracks.
  - it could be either a toggle, anyone can add organisms / anyone can add tracks to organisms they have permisisons for
  - or, more ideally, apollo overhauls permissions and includes more standard RBAC. We could have a role such as 'can-create-organisms' and grant this to users on an as-needed basis. Same for adding tracks. Permissions could really be much more granular here, c.f. #1611 https://github.com/GMOD/Apollo/issues/1499

If users could then control sharing, I could really leave apollo alone and be hands-off. The only possible concern then is that less trusted users inject some XSS into their feature's `color` field but I'll consider this an acceptable risk to have a really democratic apollo instance where users can bring + analyse their own data and self-organise, and I can always run static analysis and investigate "odd" javascript in their tracklists.

Thoughts on this? @childers @moffmade @abretaud

**Comment by abretaud** [comment]
That's cool ideas! 👍

**Comment by nathandunn** [comment]
I really like the second one (more granular permissions).   I support any endeavor in this direction.  It has also been on my wishlist for awhile.  

I'm confused about the first one, though.   Apollo (and JBrowse) both have an hierarchal track track selector (but maybe its not deep enough).   I think you can upload and update metadata pretty easily, as well, using the current routes.   However, maybe I'm missing something (and I'm not sure what ```trackList2.json``` is).

**Comment by erasche** [comment]
Sorry, I typo'd that, not the hierarchical track selector. My apologies. I meant the faceted track selector. http://gmod.org/wiki/JBrowse_Configuration_Guide#Faceted_Track_Selector

**Comment by erasche** [comment]
e.g. seen here with metadata automatically added by the galaxy tools. We can automatically cross link precisely which tool generated a dataset, when, what parameters were used to run the tool that generated the track. etc.

![](https://github.com/erasche/presentations/blob/master/2017-GCC-lightning/plugin-combo.png?raw=true)

**Comment by nathandunn** [comment]
Do you just need to upload the CSV metadata file in addition to the other stuff?

**Comment by erasche** [comment]
I didn't know the csv metadata option existed. That's way more convenient. And it looks like you can load multiple .csv files so we'd just write one per track.

```
    [trackMetadata]
    sources =
       + data/mymeta.csv
       + data/more_meta.csv
```

ok, awesome, that solves that desire.

**Comment by nathandunn** [comment]
Sweet.  Let us know if it doesn't allow those uploads.   I think the comments WRT permission can probably be added to #1499.
