### ISSUE TITLE
Gene and transcript on opposite strand after flipping

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#1769]
A first issue about problems I found while parsing a gff exported from apollo:
I have a gene that looks like this:

```
scaffold10	.	gene	265657	434794	.	-	.	owner=xxx;symbol=xxx;ID=2f57affb-4841-4a5a-8d96-6e821d27008b;date_last_modified=2017-09-24;Name=nephrin;status=Approved;date_creation=2017-09-24
scaffold10	.	mRNA	265657	434794	.	+	.	owner=xxx;Parent=2f57affb-4841-4a5a-8d96-6e821d27008b;ID=9e0e0251-f487-4741-a4d7-b397210595fc;date_last_modified=2017-09-24;date_creation=2017-09-24
```

So the gene is on `-` strand while its only transcript is on the `+` strand.

Looking at the history of the gene, I see that it was flipped at some point, from `-` to `+` strand, so I guess there is a bug somewhere that doesn't propagate the transcript's strand to its parent.

I feel like there can't be a gene with transcripts on different strand, right?

The gene was created on a 2.0.7 instance

**Comment by abretaud** [comment]
A little scary, I have this problem with 149 genes out of 2866 annotated genes

**Comment by abretaud** [comment]
(I don't know if all of them were flipped though)

**Comment by abretaud** [comment]
see #1770 too

**Comment by deepakunni3** [comment]
@abretaud This is definitely not what is desired. Thanks for reporting this issue.

**Comment by nathandunn** [comment]
@deepakunni3  Confirmed this as well.  I don't think that this is a commonly used function, but it should be working correctly regardless.
