### ISSUE TITLE
Handling empty fields in GFF3 export

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#177]
Found while testing Apollo 1.0.4 RC3

While exporting GFF3 from 'Select sequence' page or while getting a GFF3 for a single annotation in the user-created annotations track, column 6 and 8 of the GFF3 should have  a  '.' when it is empty. Currently it is a blank.

![screen shot 2015-02-24 at 11 02 33 am](https://cloud.githubusercontent.com/assets/4530272/6354376/af38ac64-bc14-11e4-9bff-812a30621547.png)

Not a major issue but can be confusing at times.

**Comment by cmdcolin** [comment]
I can reproduce in 1.0.4 RC3 and I also did the same action in the 2014-04-03 version and it did not have this problem.

**Comment by deepakunni3** [comment]
I can reproduce the same issue on Apollo 1.0.1 and Apollo 1.0.2.

**Comment by monicacecilia** [comment]
Good eye.

Le sigh. It is surprising to see this error introduced :( I missed it in my visual checks - more concerned with whether the file was produced and how coordinates added up to CDSs and exons. -- btw, I found an interesting pattern with CDS / exon coordinates organization but I am looking more into that before I create an issue.

We should have a GFF3 validation check.

**Comment by nathandunn** [comment]
I'll take a look (sorry I've been in the air). Thanks for catching.

**Comment by nathandunn** [comment]
Found bug.  Was part of initial refactor .. Very bizarre  .. Will check it in and update soon.

**Comment by nathandunn** [comment]
I think that the order is comes from recursing (depth-first) down:

Gene -> subfeatures (by location) -> subfeatures (by location)

This is the most efficient way of doing this for this architecture.  If there is a preferred ordering, create another github issue, set it to milestone 2 and give it to Deepak who is currently working on it. 

I’m going to keep checking for possible issues.  

Nathan

**Comment by monicacecilia** [comment]
Checked that (dots) for empty fields have been reestablished on GFF3 export.

Will check on follow up about oder in separate issue, if applicable.

Thank you!

**Comment by nathandunn** [comment]
@deepakunni3   Can you close this if it is working (pretty sure it is).

**Comment by deepakunni3** [comment]
Empty fields are now replaced with a period.
