### ISSUE TITLE
Inconsistent coloring of reads in DraggableAlignments

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1781]
In JBrowse, reads are colored red for reads aligned to the forward strand and blue for reads aligned to the reverse strand. This is observed in tracks of type `Alignments` and `Alignments2`.

In Apollo, reads are colored blue for reads aligned to the forward strand and red for reads aligned to the reverse strand. This is observed only in `DraggableAlignments`.

Here is a comparison of region in JBrowse:
![screen shot 2017-10-10 at 4 05 22 pm](https://user-images.githubusercontent.com/4530272/31410866-5ef012d2-add5-11e7-8365-53913aef2059.png)

and the same region in Apollo:
![screen shot 2017-10-10 at 4 05 15 pm](https://user-images.githubusercontent.com/4530272/31410868-620d9228-add5-11e7-8f12-42dead5e754a.png)

**Comment by nathandunn** [comment]
Seriously.  Ugh.  Alright, I'll fix this.  At least I was consistently wrong ;)
