### ISSUE TITLE
reads that are soft-clipped at the 5' end, alignments don't get drawn

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1786]
From:

http://gmod.827538.n3.nabble.com/Soft-clipped-reads-not-displaying-properly-td4058664.html

**Comment by nathandunn** [comment]
@deepakunni3  As you have time next week.

**Comment by deepakunni3** [comment]
@nathandunn  The alignments not getting drawn properly is because of NeatHTMLFeatures and NeatCanvasFeatures. If we remove those plugins, the reads should render properly.

**Comment by nathandunn** [comment]
But it also sounded like there was an issue with DraggableAligbments as well, right? 

Nathan

**Comment by nathandunn** [comment]
Or should this get closed in favor of 1788? 

Nathan

**Comment by deepakunni3** [comment]
@nathandunn Yes, we can go ahead and close this since the this issue has to do with NeatHTMLFeatures and NeatCanvasFeatures plugins.

#1788 is related but addresses the problem with DraggableAlignments.

**Comment by nathandunn** [comment]
I wonder if we should open a jbrowse issue for this (if there isn’t one already there). 

Nathan

**Comment by deepakunni3** [comment]
@nathandunn Looking into it

**Comment by nathandunn** [comment]
Related to #1788

**Comment by nathandunn** [comment]
Re-reading it sounds like this can be closed, but re-open if need be.
