### ISSUE TITLE
extracting annotations from a pre 1.x version of Appollo

### ISSUE THREAD

**Issue by cghiban** [GMOD/Apollo#1792]
Hi, I'm using an older version of Apollo and I was wondering if there is a way to retrieve the annotations from the *.jdb files..

```
# ls -1 
00000000.jdb
je.info.0
je.info.0.lck
je.lck
```

Thanks,
Cornel

**Comment by nathandunn** [comment]
I’m guessing this is Desktop Apollo?

I would export your annotations as GFF3 and then import them using the gff3 import method.

https://genomearchitect.readthedocs.io/en/latest/Data_loading.html#bulk-loading-annotations-to-the-user-annotation-track

Nathan

**Comment by cghiban** [comment]
No, it's an early version of webapollo. Is there a way to extract the annotations from the jdb files?
Thanks,
Cornel

**Comment by nathandunn** [comment]
If you are able to get the old server running I would start here:

https://genomearchitect.readthedocs.io/en/latest/Migration.html#migration-from-1-0-to-2-0 <https://genomearchitect.readthedocs.io/en/latest/Migration.html#migration-from-1-0-to-2-0>

This script should also work as well, though you would have to have both servers running (and create an organismic Apollo 2 ahead of time):

https://github.com/GMOD/Apollo/blob/master/docs/web_services/examples/groovy/migrate_annotations1to2.groovy <https://github.com/GMOD/Apollo/blob/master/docs/web_services/examples/groovy/migrate_annotations1to2.groovy>


Nathan

**Comment by nathandunn** [comment]
No longer supporting JBrowse 1
