### ISSUE TITLE
User-created Annotations track not functioning

### ISSUE THREAD

**Issue by Wozzerv** [GMOD/Apollo#1793]
Hello! I am trying to set up an instance of Apollo but I have come into some problems in regards to the display of the User-created annotation track. I have attached a screenshot of the attempted operation. The full console log from the browser when I recreated the issue. The catalina.out for the time frame this was attempted for and the configuration file used to proxy Apollo on the server. The other screenshot is attached as it came up with some error in regards to web-sockets after a refresh. 

Is anything else needed to try to pinpoint the issue? Thank you in advance for any help. 

![screenshot at 2017-10-27 11-25-37](https://user-images.githubusercontent.com/16587338/32099773-985cc1c8-bb09-11e7-8cb8-f7a11277fae6.png)

![screenshot at 2017-10-26 11-36-11](https://user-images.githubusercontent.com/16587338/32099555-ade45e30-bb08-11e7-90d4-de718af3aeba.png)

[www185.lamp.le.ac.uk-console.log](https://github.com/GMOD/Apollo/files/1421689/www185.lamp.le.ac.uk-console.log)

[apollo.conf.txt](https://github.com/GMOD/Apollo/files/1421692/apollo.conf.txt)

[catalina.out.txt](https://github.com/GMOD/Apollo/files/1421694/catalina.out.txt)

**Comment by nathandunn** [comment]
Thanks.  These are helpful.   

- Just to double-check, it looks like you are getting errors for dragging up simple exons (as opposed to the full BAM read)?

- are you able to connect to your server through 8080 (ignoring the proxy)? 

- How is your proxy setup?   Is it a working apache server (can you confirm that https works?), or the secure layer through tomcat?

- https://stackoverflow.com/a/38852630/1739366   Try updating your proxy to use `wss`:

```
ProxyPass			/apollo/stomp	wss://localhost:8080/apollo/stomp
ProxyPassReverse	/apollo/stomp	wss://localhost:8080/apollo/stomp
```

**Comment by Wozzerv** [comment]
We managed to fix it! 

It was the conf file in Apache2 which was the problem. Here is the conf file we use which causes it function as intended. 
[apollo.conf.txt](https://github.com/GMOD/Apollo/files/1440960/apollo.conf.txt)
