### ISSUE TITLE
/user/loadUsers REST end-point returning bad data for permissions

### ISSUE THREAD

**Issue by khowe** [GMOD/Apollo#1797]
In the JSON returned by the above API end-point, the per-organism permissions are encoded as strings rather than data structures. e.g. 

`{"organism":"trichuris_trichiura","permissions":"[]"},`
`{"organism":"trichuris_muris","permissions":"[\"WRITE\",\"READ\"]"},`

**Comment by nathandunn** [comment]
@khowe  I'm going to add a field called "permissionArray" that returns the correct version.   We (and others) use the other version, and I don't want to break it in 2.0.8, but I definitely agree that it is incorrect.

**Comment by nathandunn** [comment]
this is done
