### ISSUE TITLE
Bad layout on changes page

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#180]
![bad_layout2](https://cloud.githubusercontent.com/assets/6511937/6398481/8bcd6168-bdb1-11e4-8173-e44d126ca66c.jpg)

Screenshot in chrome on 1.0.3 pictured above with bad layout. The issue is a weird thing with "cleanup_logo" function being called prematurely.

**Comment by monicacecilia** [comment]
Checked. update looks fine. Thank you!
