### ISSUE TITLE
OrganismController.groovy fixes

### ISSUE THREAD

**Issue by Yating-L** [GMOD/Apollo#1804]
Hi folks,

There is a bug I found in [OrganismController.groovy](https://github.com/GMOD/Apollo/blob/2.0.7/grails-app/controllers/org/bbop/apollo/OrganismController.groovy), class deleteOrganism(). I saw it was fixed in branch 2.1.0

```
try {
            JSONObject requestObject = permissionService.handleInput(request, params)
            log.debug "deleteOrganism ${requestObject}"
            if (permissionService.isUserAdmin(permissionService.getCurrentUser(requestObject))) {
```

`requestObject` should be `organismJson` instead.

It causes the organisms cannot be deleted and get an error message in the log:

```
ERROR apollo.OrganismController  - problem deleting organism: groovy.lang.MissingPropertyException: No such property: organismJson for class: org.bbop.apollo.OrganismController
```

**Comment by nathandunn** [comment]
@Yating-L   I think this has also been fixed on the master branch (to be 2.0.8 eventually) as well.  Can you confirm either way?

https://github.com/GMOD/Apollo/blob/master/grails-app/controllers/org/bbop/apollo/OrganismController.groovy#L54

https://github.com/GMOD/Apollo/blob/master/grails-app/controllers/org/bbop/apollo/OrganismController.groovy#L92

**Comment by Yating-L** [comment]
Hi @nathandunn ,

Thank you for the quick response!

Yes, the delete function is fixed in both ways. However, I found a bug in the master branch of OrganismController.groovy. 

https://github.com/GMOD/Apollo/blob/master/grails-app/controllers/org/bbop/apollo/OrganismController.groovy#L918

I think it should be 

```
organism.publicMode = organismJson.publicMode ?: false
```

It causes IllegalArgumentException when updating the organism
```
Error 2017-11-10 10:19:05,986 [http-bio-8080-exec-14] ERROR apollo.OrganismController  - problem saving organism: java.lang.IllegalArgumentException
```

**Comment by nathandunn** [comment]
K.  Posted a PR fix.  It looked like it was correct in other areas.  Thanks for reporting.
