### ISSUE TITLE
gene positions are wrong for some operations

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1808]
From #1770 and https://github.com/GMOD/Apollo/issues/1770#issuecomment-344288889

For one gene, it was created as a big gene, then in the history there is a long list of delete exons/set exon boundaries/merge transcript (probably with an isoform, no significant change in gene length). I think the probem comes from a final "delete exon" that resulted in a much shorter gene.

For another one, it started as a small gene, then it got merged with another nearby transcript, then after some "set exon boundaries", there are a few "delete exon" that reduced it's size

The last gene is a single exon gene, with big changes in size due to "set exon boundaries", and then a final "flip strand" change. The wrong coordinate comes from an old start position before a "set exon boundaries" that moved the start position

So I guess there are some things to check on "delete exon" and "set exon boundaries" actions?

**Comment by nathandunn** [comment]
I reproduced this.  Add two isoforms.  Delete non-overlapping exons.   Expect mRNA and gene to be the same length for both genes / isoforms, but see that they are not.

![Screen Shot 2017-11-15 at 2.45.53 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226455f66b7191a37af1162e4f5a5c5ecc3c4a4356bcbbd671f3e57862804e0eea856f5c74906b17f8ba804cbf07ef208819d6e0edde48d2f42f67b6d5db1063474f4dcbed5727a19e41c95df74be64553a41b3e60e2732431.png)

**Comment by deepakunni3** [comment]
@nathandunn Looks good 👍
