### ISSUE TITLE
Ability to force assignment of a transcript to a parent

### ISSUE THREAD

**Issue by fayerodgers** [GMOD/Apollo#1816]
We would like to be able to assign transcripts to share a parent with other transcripts, even if they don't share CDS. For example here:

![screen shot 2017-11-24 at 17 04 22](https://user-images.githubusercontent.com/20802386/33219336-a1e38e2a-d139-11e7-838f-7293e64ccd6d.png)

Currently the exported GFF has transcripts 1 and 2 deriving from the same gene and transcript 3 as a separate gene. It would be useful to have a way to override this in the Apollo interface (maybe a right click menu option when all three transcripts are selected-> assign to same parent?).

**Comment by nathandunn** [comment]
http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000104731;r=16:87696485-87765992

**Comment by nathandunn** [comment]
Per our meeting with @deepakunni3 , @fayerodgers , @khowe, and @selewis 

- [ ] add a global configuration option for defining transcript overlap as exon-only (as opposed to CDS in-phase overlap, the current default)
- [ ] allow setting transcript to a new or existing gene (not sure if this should be sticky or not, or if it should just be done after the fact)
   - [ ] allow annotator panel to be "focused" on the current transcript to simplify visualization
   - [ ] add tooltips to genes for type?

**Comment by nathandunn** [comment]
From: http://gmod.827538.n3.nabble.com/Assigning-parent-features-to-transcripts-td4058870.html

**Comment by nathandunn** [comment]
I think this  is mostly done, but if there is a part to do yet, please create a new issue.
