### ISSUE TITLE
Problem when Pipe (|) in sequence name 

### ISSUE THREAD

**Issue by Juke34** [GMOD/Apollo#1819]
Dear Apollo team,

I don't know if it's related to the closed issue #1606, but I have noticed the following problem: I created a new webapollo instance (I tried on v2.0.7 v2.0.8-rc2) and added only one organism containing 1 sequence but I never succeeded to make it work (as for issue #1606 the main (jbrowse) window remains blank), until I remove the pipe within the sequence name.
So apparently the pipe character in header of the fasta sequence prevents webapollo to work properly.

**Comment by nathandunn** [comment]
What version of tomcat are you using?    We noticed some issues with more recent versions of tomcat:

http://genomearchitect.readthedocs.io/en/latest/Setup.html?highlight=recent#json-in-the-url-with-newer-versions-of-tomcat <http://genomearchitect.readthedocs.io/en/latest/Setup.html?highlight=recent#json-in-the-url-with-newer-versions-of-tomcat>

That said, it wasn’t for this specific problem.    I tried adding a FASTA sequence with a pipe in the sequence name running master (pretty close to the released Apollo 2.0.8), but I’m not seeing any issues with tomcat 8.5.23 without having to make any modifications.

Nathan

**Comment by nathandunn** [comment]
Feel free to post your header / FASTA file and I'll re-add it or email me directly for us to take a look if you are able to reproduce it on master.

**Comment by Juke34** [comment]
Here is the header:
>mit|quiver|pilon

**Comment by nathandunn** [comment]
Using similar settings, but off of master (or the official 2.0.8 release should be the same):

Grails version: 2.5.5
Groovy version: 2.4.12
JVM version: 1.8.0_144
Apache Tomcat: 7.0.82

![screen shot 2017-11-30 at 11 21 40 am](https://user-images.githubusercontent.com/751274/33450443-ad2b839c-d5c0-11e7-9b32-a1dbdf77c561.png)

I just did:

    ./prepare-refseqs.pl --fasta TEST.fa --out /apollo_dir/smallest_test

```
>mit|quiver|pilon
CCATAAACAAACGGTGGACCTTCTCAAGCTGGTTGACGCCTCAGCAACATAGGCTTCCTCCTCCACGCATCTCAGCATAAAAGGCTTATAAACTGCTTCTTTGTGCCAGAGCAACTCAATTAAGCCCTTGGTACCGTGGGCACGCATTCTGTCACGGTGACCAACTGTTCATCCTGAATCGCCGAATGGGACTATTTGGTACAGGAATCAAGCGGATGGCACTACTGCAGCTTATTTACGACGGTATTCTTAAAGTTTTTAAGACAATGTATTTCATGGGTAGTTCGGTTTGTTTTATTGCTACACAGGCTCTTGTAGACGACCTACTTAGCACTACGGCCGAGCGCAATAACCCCCGGAAAGCACTTGCTACTGGGAGGCGGGTTTATCCATCGGCAATAGG
```

Can you post your tomcat logs, and the browser console and network logs if it still doesn't work?

**Comment by Juke34** [comment]
As you suggested I have updated PostgreSQL.
Updating PostgreSQL from 8.4 to 10.1 fixed the problem !
Thanks for your help.

**Comment by Juke34** [comment]
To add more information about it, webapollo 2.0.7 and 2.0.8  was not working properly on postgres 8.4.
