### ISSUE TITLE
BioPerl's SeqFeatureLoadHelper make installation need more than 40GB on Mac High Sierra

### ISSUE THREAD

**Issue by hsiaoyi0504** [GMOD/Apollo#1820]
I am not sure it's a issue of Apollo or jbrowse, but it occurs during I install Apollo through
`./apollo run-local` and other similar commands. I have cleaned up more than 45 GB of disk space. However, it will consume more than 45GB during the installation. After using some software like this (DaisyDisk), I finally find during installation, some large files are created, and the folder name implies that it may cause by BioPerl > Bio::DB::SeqFeature::Store::LoadHelper (it's just a rough guess based on the result I got from google search).

<img width="972" alt="screen shot 2017-11-29 at 9 04 18 pm" src="https://user-images.githubusercontent.com/10943928/33409396-389f97ba-d549-11e7-8e91-5d6d957883ea.png">

**Comment by deepakunni3** [comment]
@nathandunn I can reproduce this issue when deploying Apollo for the first time after a clone from GitHub.

Whats interesting is that this bug is observable only on **macOS High Sierra**.
I tested with **Ubuntu 16.04** and it works just fine.

**Comment by nathandunn** [comment]
Also just tested it with macOS High Sierra, but I can’t find this.    Is this temporary only?

**Comment by deepakunni3** [comment]
Well, here is the fun part: it happens only the 1st time you setup apollo after a `git clone`. 
```
...
npm WARN jbrowse@1.12.4-SNAPSHOT No license field.

added 79 packages in 11.598s
done
Gathering system information ...done
Installing Perl prerequisites ... done.

Formatting Volvox example data ... done.
To see the volvox example data, browse to http://your.jbrowse.root/index.html?data=sample_data/json/volvox.

Formatting Yeast example data ...
> Building 10% > :installJBrowse
```
The build gets stuck at 9% or 10% and it remains stuck until your drive is filled up.

Subsequent tries don't run into this particular behavior, but you end up with an instance of Apollo that is missing a lot of JBrowse dependencies.

**Comment by hsiaoyi0504** [comment]
@nathandunn I think the folder is created only temporarily. If it finishes, the folder will be deleted. However, I tried many times, and only 1 or 2 times I can build the project. Therefore, I can’t develop under this circumstance.

**Comment by nathandunn** [comment]
I'm wondering why, once installed, it ever needs to create a temporary folder to re-install them.    It could be that your cpan is just corrupted.  

My suggestion is:

1)  test with just a simple JBrowse install and see if you run into the same problem: https://github.com/GMOD/jbrowse/
2) remove and re-install CPAN.  It shouldn't be trying to rebuild modules that are already there.
3) 2 doesn't fix it, the I would try installing the modules necessary (bioPerl mostly) manually and going from there.  Post the log file for that.    You can look in here for what is installed: https://github.com/GMOD/jbrowse/blob/master/Makefile.PL
4) if 3 doesn't fix it, make sure you have 50 GB's available.    My guess is that 2 will fix everything, but really, once bioperl is installed it should just work and you should not have to do anything else with JBrowse 

However, for Apollo development, you shouldn't be installing JBrowse constantly unless you are doing something very unusual.

**Comment by hsiaoyi0504** [comment]
@nathandunn Thank you for pointing me some directions. I will try.

**Comment by hsiaoyi0504** [comment]
I think you mean I should install through `npm`, right ?

**Comment by hsiaoyi0504** [comment]
To be more specific, I think the problem is happened when generating the example data.
In `setup.sh` of `jbrowse`,

https://github.com/GMOD/jbrowse/blob/d3827c4e81054ef65933ca792d228f786d849ba4/setup.sh#L73-L128

The log is here:
```
Installing Perl prerequisites ... done.

Formatting Volvox example data ... done.
To see the volvox example data, browse to http://your.jbrowse.root/index.html?data=sample_data/json/volvox.

Formatting Yeast example data ...
> Building 9% > :installJBrowse

```
It will stuck here and notify me that my disk space is almost full.
Thenm the build failed with a super large file at `/private/var/folders/69/vtjgy7mn3935dmrgnftm9jjr0000gn/T/SeqFeatureLoadHelper_HOQAB5`

I try the method you provide to me, and it doesn't work for me, and I don't think it's easy for me to clean up and have 50G. Only 120G on my machine and half of them is application and OS system.

**Comment by nathandunn** [comment]
If you think that is the error, you might just try commenting out the add sample data part of `setup.sh` and see if that works.  

We can just add an option to not install examples.  Probably something we should do anyway.

**Comment by deepakunni3** [comment]
@hsiaoyi0504 Thanks for narrowing it down.

It looks like `generate-names.pl` step in the `setup.sh` never finishes. 

https://github.com/GMOD/jbrowse/blob/d3827c4e81054ef65933ca792d228f786d849ba4/setup.sh#L96

Although I don't see why its getting stuck. If I run that exact same command, it works without any issue.

**Comment by deepakunni3** [comment]
**Update:**
Its `biodb-to-json.pl` that ends up creating those large files.
While it finishes quickly for Volvox, it seems to keep going on for Yeast. Not exactly sure why this is happening. 

Will look into it further.

**Comment by deepakunni3** [comment]
Tested running biodb-to-json.pl on different OS/machines:
* Mac OSX Yosemite - 👍 
* MacOS Sierra - 👍 
* MacOS High Sierra - ✖️ 
* Ubuntu 16.04 - 👍 
* Ubuntu 17.10 - 👍 

The only thing majorly different between MacOS Sierra and MacOS High Sierra is the introduction of a new file system called APFS.
I am not sure if this has any effect or there is something else thats causing problems.

**Comment by hsiaoyi0504** [comment]
@deepakunni3 Thanks for testing that. I think the opinion mentioned by @nathandunn that adding a option to not install examples is a good suggestion, and I don't have idea why we should install jbrowse with example if we just want to use Apollo.

**Comment by hsiaoyi0504** [comment]
@nathandunn @deepakunni3  After comment out those lines for building example, I can build Apollo correctly.

**Comment by deepakunni3** [comment]
@hsiaoyi0504 Good going. Yes, you shouldn't need the example data to work with Apollo. 

Since this bug is more upstream than JBrowse, we are currently implementing a workaround which pretty much based on the idea to avoid running `biodb-to-json.pl`.

**Comment by cjfields** [comment]
@deepakunni3 this appears to be a general issue with berkeley-db and DB_File:

https://discussions.apple.com/thread/8125401

see https://github.com/bioperl/bioperl-live/issues/267
