### ISSUE TITLE
problem using embedded mode nav option

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#183]
I was looking into the URL tags for doing an embedded mode, and ran across a problem.  Setting the 'nav' tag disables ability to resize tracklist panel. This is true whether nav=0 or nav=1.  The resize bar for the Available Tracks section can be dragged, but it is now independent from the Available Tracks panel. I reproduced this with multiple versions of Web Apollo, including the Genome Architect Web Apollo demo. I was not able to reproduce this behavior in standard JBrowse.

**Comment by cmdcolin** [comment]
I can confirm this is a problem is WebApollo specific. It seems to be due to adding menu options outside of the condition if(browser.config.show_nav) in the plugin which produces a "crash" (and then the "crash" prevents further things like resizing the track list)

**Comment by cmdcolin** [comment]
Should be ok now @nathandunn

**Comment by nathandunn** [comment]
When doing nav=0  , resizing of track is not correct.   Starts out okay and then the following occurs when I drag the right side of the track panel (this is chrome).  nav=1 seems to work fine:

![screen shot 2015-03-02 at 6 59 38 pm](https://cloud.githubusercontent.com/assets/751274/6455826/53ee941e-c10e-11e4-9e12-539c59fdcaaf.png)

http://icebox.lbl.gov/WebApolloDemoStaging/jbrowse/?loc=GroupUn4157%3A1..1412&tracks=DNA%2CAnnotations%2COfficial%20Gene%20Set%20v3.2&highlight=&nav=0&tracklist=1&overview=1

If you are not seeing this, I will take another look. 

If there is no easy fix, that is fine.   The workaround (though not good) is simply to set tracklist=0 as well unless there is a pressing need to see one and not the other.   I did not need to see the tracklist with the nav being set to 0.

**Comment by cmdcolin** [comment]
That's what it looked like before my bugfix, but I think I fixed that. Maybe you didn't deploy my bugfix to webapollo demo staging. I think I can tell from the source code even though it's minified that it doesn't include my change :)

**Comment by nathandunn** [comment]
@cmdcolin   I think I deployed the non-release version over the release version, so probably still seeing the later.   I will redeploy and check again.  Thanks.

**Comment by nathandunn** [comment]
that worked .. thanks.
