### ISSUE TITLE
Adding metadata to identify organisms with the same name

### ISSUE THREAD

**Issue by Yating-L** [GMOD/Apollo#1834]
Currently, Apollo allows adding an organism having the same name as an existing organism. However, there's no metadata that user can use to identify different organisms with the same name.  

A common use case: when a user adds an updated version of an organism to the Apollo instance but he or she wants to keep the old version. It needs some kind of identifier to differentiate the two versions. 

I am developing a Galaxy tool that creates an "organism" by assembling all evidence tracks generated by Galaxy tools and adds that organism to Apollo instance. Users can run the tool over and over to create a newer version each time, but Apollo lack of metadata to differ each version.

**Comment by erasche** [comment]
@Yating-L there is a metadata field but it isn't documented very well.
https://github.com/GMOD/Apollo/blob/master/grails-app/controllers/org/bbop/apollo/OrganismController.groovy#L767

> I am developing a Galaxy tool that creates an "organism" by assembling all evidence tracks generated by Galaxy tools and adds that organism to Apollo instance

This sounds a lot like my [existing JBrowse tool](https://github.com/galaxyproject/tools-iuc/tree/master/tools/jbrowse) + the tools I developed for creating the organism in apollo. We wrote a bunch of tools around these sort of workflows. https://github.com/galaxy-genome-annotation/galaxy-tools/tree/master/tools/apollo

If you're really developing a new set of tools, can you let me know what's missing in mine?

**Comment by Yating-L** [comment]
@erasche I should've asked this earlier. I'd like to take a look at the "suite_apollo" tool in Galaxy tool shed previously, but I couldn't install it and I tried to install a few individual tools and still failed. Do you have any ideas?

**Comment by erasche** [comment]
@Yating-L no problem! Always here if you have questions. We've had problems in the past with shed installation, but this *should* be working. We use it in a genome annotation docker flavour where it does install successfully. 

The suite_apollo is specified [here](https://github.com/galaxy-genome-annotation/docker-galaxy-genome-annotation/blob/master/genome_annotation_tools_3.yml#L112), installed [here](https://github.com/galaxy-genome-annotation/docker-galaxy-genome-annotation/blob/master/Dockerfile#L41), and available in [container form here](https://quay.io/repository/galaxy-genome-annotation/docker-galaxy-annotation).

I trust that you are seeing errors, I have no doubt of this, but could you provide some more information? What sort of error are you experiencing on installation? What does your galaxy setup look like (what version of galaxy? dockerized? do you have conda enabled?)

**Comment by Yating-L** [comment]
I use an Ubuntu 14.04 virtual machine. We don't use Docker at this point. The Apollo is running on the localhost. The problem I experienced is that the tools were kept installing but never finished. Here is  [deployment files](https://github.com/gonramp/ansible-gonramp/blob/dev/kickstart_gonramp.sh)

**Comment by nathandunn** [comment]
Do you have any log output in order to get an idea of where it might have gotten stuck at? 

Nathan

**Comment by nathandunn** [comment]
Talked with @Yating-L  and the resolution is that this is do-able, but it ended up being more reasonable for the client calling the API to rename explicitly by calling findAllOrganisms to check on the commonName's that exist, assign a unique name (if appropriate).  This way non-admin users will be able to see the other name easily, as well.
