### ISSUE TITLE
Improving the Apollo API and Python library

### ISSUE THREAD

**Issue by Yating-L** [GMOD/Apollo#1835]
The current Apollo API  doesn't support external calls from Python library very well. Example: when adding a user to a group, it will cause the server error if the user or the group doesn't exist. 

Additional, need some improvements to output messages. Example: detete an organism: when it succeeds, it returns {}. when it failed, it returns {"error": "....."}. It may be nice to have a unified or standard output for either error or successfully executes. For example: {"result": {"text": "deleted"}} 

And there's no test for Controllers / REST services.

**Comment by erasche** [comment]
@Yating-L does "from Python library very well" mean this library: https://github.com/galaxy-genome-annotation/python-apollo ? if so let me know which calls aren't working. I've tried to work around a number of the api issues in that library (e.g adding an organism returns the list of ALL organisms so that library already filters to just return the one you created.)

**Comment by nathandunn** [comment]
@erasche  that issue should be fixed (https://github.com/GMOD/Apollo/pull/1802) in 2.0.8.

**Comment by erasche** [comment]
@nathandunn oh awesome! We'll have to add that to py-apollo

**Comment by nathandunn** [comment]
From @erasche  https://github.com/galaxy-genome-annotation/python-apollo/pull/2/ may fix some of these.

**Comment by Yating-L** [comment]
@erasche I found a few calls that don't work well. Some of them may be fixed in Python library but some may need to mess with API, I think. I am working on fixing some of them through api, but not ready to send PR yet, aiming to do it this week. I am a little confused about the "standard" output for the calls. When it succeeds, it usually returns an empty JSON, {} (e.g. addUser/deleteUser) but sometimes it returns a list of items (e.g. addOrganism/deleteOrganism). Is there a way to check if the calls are successful? Right now, my workaround is to check if there's "error" in the returned JSON object. Let me know if there's any "standard" or desired output structure I should follow. 

Here is a list of calls that I found not working or need improving ( I may come up more later)
1. add_to_group / delete_from_group
   1. server error when user or group not exist
1. delete_organism
   1. when succeed, return all organisms including the deleted one
1. show_organism commonName
   1. not list all organisms with the commonName, as currenly Apollo allows multiple orgnisms with the same name
   1. if the organism not exist, it will try to find it by passing the organismName to findById(). Which will lead to type error. 
1. create_group
   1. will create a new group even a group with the same name already exist (I am not sure if Apollo should allow this)

- 

-

**Comment by erasche** [comment]
I have no way to check that those are successful. In the past (from frustration at returning empty json objects) I'd often request all features/orgs/whatever just to confirm that the user's object was created. But it is an ugly hack and apollo should really correct the API to be more how users expect (IMO.)

Everything you've mentioned is something I've encountered as well and failed to report, or privately worked around. Very excited for your patch!

**Comment by erasche** [comment]
I'd really love an api that behaved like more of the APIs that I'm familiar with. E.g.

- GET /organisms/ -> lists all organisms
- POST /organisms/ -> creates an organism
- GET /organisms/<id> -> details about one org
- PUT/DELETE
- /organisms/<id>/features -> lists features on an organism.

I took a stab at writing a second apollo API (in addition to the current one which could thus be retained as the legacy API) before deciding this was a monumental task and beyond my abilities at the time. (cc @moffmade)

**Comment by nathandunn** [comment]
@erasche  I would like that too ;)  These are largely just adapted APIs from the older version with a few new things tacked on.

I looked at moving to swagger and redefining the APIs, but I think it will be easing to do with Grails 3 and then rewrite the clients to use the better APIs. 

In the interim, however, any improvements folks make towards that end would be much appreciated.  

Mostly its just a matter of updating the doc on the controllers as you have done already and updating the [URLMappings](https://github.com/GMOD/Apollo/blob/master/grails-app/conf/UrlMappings.groovy).   Multiple methods can map to the same thing (as they already do).

**Comment by erasche** [comment]
@nathandunn oh yeah, *totally* understandable how these developed over time.

Very excited for swagger/grails 3/etc. That all sounds awesome :)

**Comment by nathandunn** [comment]
I think we've fixed a lot of these specific issues, but we should look to fix these with specific issues
