### ISSUE TITLE
show not allow setting translation start in the wrong direction of translation end

### ISSUE THREAD

**Issue by khowe** [GMOD/Apollo#1838]
Hi there, 

Apollo lets you create transcripts with "backwards" CDSs. That is, for a forward strand transcript, you can set the translation end to a position upstream of the translation start. I've created one of these on the demo server:

ctgA:13251..28300 (15.05 Kb)
(annotation Apple3a-00001)

If you use the UI to fetch the cds/peptide sequence for this transcript, you get nothing back. 

These annotations have a number of knock-on effects:

- CDS features in the GFF3 having start > end (illegal GFF3)
- REST IO/write method completely fails (for all sequences/transcripts) for cds and peptide FASTA dumps. 

The problem similar to the second occurs also if there is no CDS for a protein-coding transcript (peptide dump failure for *all* transcripts). Although we're still trying to work out how our curators created CDS-less mRNAs!

A couple of suggested improvements:

- Apollo could warn (or better, prevent) on attempt to create a CDS in the opposite orientation to the parent transcript
- An "ignorebad" (or similar) option for the IO/write end-point that will return data for all valid transcripts, ignoring invalid ones

**Comment by nathandunn** [comment]
@khowe  I think it should not just not allow you to create a negative translation region, ever. 

The strand is correct, but it has an impossible start / stop position:

```
ctgA	.	exon	18000	18800	.	+	.	Parent=8bcfd1c2-c4a6-4ca7-a41f-25e9aa5a1d9b;ID=2e542650-310e-42bf-9c9b-5182478826c8;Name=2e542650-310e-42bf-9c9b-5182478826c8
ctgA	.	CDS	18023	18013	.	+	0	Parent=8bcfd1c2-c4a6-4ca7-a41f-25e9aa5a1d9b;ID=eea9deba-b57b-4231-b727-a8c47427fe69;Name=eea9deba-b57b-4231-b727-a8c47427fe69
```
