### ISSUE TITLE
Merge pseudogene to a gene and delete the pseudogene

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#1847]
From #1816 

When merging a pseudogene (from generic transcript type in Apollo) and gene, merge the pseudogene INTO the gene and delete the pseudogene.

**Comment by nathandunn** [comment]
@deepakunni3  Sounded like you had a quick fix for this.  If not, I can take a look at it.

**Comment by deepakunni3** [comment]
Yes, I can work on this next 👍

**Comment by nathandunn** [comment]
Looks like this was fixed by #1856 but never got closed.
