### ISSUE TITLE
Warnings when building war file

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1849]
Just testing the most current master branch and saw these warnings.  Always happy to avoid a possible ```RegExp DoS issue```.

```shell
Installing javascript dependencies ...Dojo does not exist, installing
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

**Comment by nathandunn** [comment]
- [ ] should be minimatch 3.0.4
- [ ] should be coffeescript 2.1.1.

**Comment by nathandunn** [comment]
Thanks @childers  These are more JBrowse issues.   So they would need to be updated there, but no guarantee that they are backwards compatible.   Can you post it there and reference this?

**Comment by childers** [comment]
whoops! missed the context the warnings popped up in during the build process.

**Comment by nathandunn** [comment]
Closing this in favor of #955
