### ISSUE TITLE
Special characters in passwords

### ISSUE THREAD

**Issue by robinohm** [GMOD/Apollo#1859]
It looks like not all user passwords are possible. For example, when I try to create a user with the (example) password 'qwerty', then everything is fine. But in the case of 'qwerty%', I get the following error message:
Error Creating User. Failed to update the user null
In the case of 'qwerty&':
Error Creating User. Failed to update the user Error parsing JSON

Is this known behavior? It took me a while to figure out that this error was actually caused by a password that was created by my password manager, so a more helpful error message would be nice.
I'm using version 2.0.8.

**Comment by nathandunn** [comment]
@robinohm  I am seeing this as well, for only for some special characters and not others.   I'll take a look.

**Comment by nathandunn** [comment]
@robinohm I posted a fix for this.  Are you able to test the PR or should I just merge it directly into master for you to use there.

**Comment by robinohm** [comment]
@nathandunn Thanks, that was quick. I already picked a different password as a simple workaround, so I can wait until the 2.0.9 release
