### ISSUE TITLE
small issue with the User-created annotations track

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#186]
I thought that I'd just create a github issue for this, just to be thorough.

The 1.0.4-RC5 has the "delete track" and "pin to top" options available on the User-created annotations track
![screenshot-icebox lbl gov 2015-03-05 17-53-49](https://cloud.githubusercontent.com/assets/6511937/6518552/0a182592-c36d-11e4-962f-a2c274fa5194.png)

That is unintentional as these options are normally unavailable.

**Comment by cmdcolin** [comment]
Fixed here https://github.com/GMOD/Apollo/commit/86d9d89c776deecba60198c466e39121340fab75

**Comment by monicacecilia** [comment]
Fixed. Unexpected features are no longer on the U-cA. --

**Comment by nathandunn** [comment]
@monicacecilia   I don't *think* this is broken, but wanted you to verify.

**Comment by cmdcolin** [comment]
This is fixed but the "Save track data" is no longer available from the User-created annotations menu.

![screenshot-localhost 8080 2015-04-12 12-29-28](https://cloud.githubusercontent.com/assets/6511937/7106695/b3f72c88-e10f-11e4-9cb6-a2c0d4613864.png)


Maybe this was done around our whole re-working of the export features?

**Comment by nathandunn** [comment]
@cmdcolin  @deepakunni3   I don't think that we did anything explicitly for this . . can you add another issue for this?

**Comment by cmdcolin** [comment]
Sure I'll do that

**Comment by monicacecilia** [comment]
I checked and it is still working properly.
