### ISSUE TITLE
creating annotations should preserve track type

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1861]
From: http://gmod.827538.n3.nabble.com/trackable-tracks-conversion-td4059136.html

In theory, we could adapt this code:

https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/AnnotTrack.js#L1008

to pick out and render types according to:

https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/AnnotTrack.js#L1401

Any thoughts @selewis  / @deepakunni3 ?

**Comment by selewis** [comment]
I heard the request as "if the evidence (track) is for a particular biological type of feature" then the default behavior should be to retain that biological feature type.

In other words
--> if the analysis was HMMtRNA then the default feature type should be tRNA
--> if the analysis was a repeat search then the default feature type should be "repeat"

Generally speaking when a track is being defined/specified there should be the capability of defining what the feature type of elements from that track should be. That way the user doesn't have to do this repeatedly. If the feature type of a track is left empty then the default is mRNA.

**Comment by nathandunn** [comment]
To clarify, you’d want to be able to specify it in the track type, for instance, such that an entire track would automatically encode a particular biotype by default when dragging up.

e.g., specify the default biotype for a track (otherwise it is an mRNA):

```
{
    "key" : "Official Gene Set v3.2 Canvas",
        "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "trackType" : null,
         "urlTemplate" : "tracks/Official Gene Set v3.2/{refseq}/trackData.json”,
      “biotype”:”ncRNA"
}
```
