### ISSUE TITLE
request-type in the headers

### ISSUE THREAD

**Issue by epaule** [GMOD/Apollo#1865]
* Provide what you were doing and what you expected to see.  Screenshots, directory, config files are a plus if relevant.

I was clicking on the export as GFF thing, and hit a load balancer configuration bug.
While debugging that, I saw that the request header for teh IOService/write?clientToken=XXX call
is */* which probably should be application/json 
Actually it would be great if the request types would be set as far as possible.
This would help with configuring load balancers to behave different depending on request-type.
 
thanks,

M

**Comment by epaule** [comment]
yes, the form is fine. But the Accept (just replace the request_type above with Accept) is a bit very lenient: */* (considering it doesn't like pointy brackets)

POST /IOService/write?clientToken=19291192551956927864 HTTP/1.1
Host: apollo.wormbase.org
Connection: keep-alive
Content-Length: 179
Origin: http://apollo.wormbase.org
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
Content-type: application/x-www-form-urlencoded
Accept: */*

**Comment by nathandunn** [comment]
@epaule   Was this resolved (did you end up using the PR in #1866)?

**Comment by epaule** [comment]
Yes, I think i tested it at that time.
