### ISSUE TITLE
Deleted transcripts show up in information editor until page refresh

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#187]
Create 3 features...
![screenshot-icebox lbl gov 2015-03-06 16-57-28](https://cloud.githubusercontent.com/assets/6511937/6538012/1606c916-c422-11e4-8cb4-a36dfb07c3a3.png)

Then delete 2 and view the Information Editor...
![screenshot-icebox lbl gov 2015-03-06 16-57-50](https://cloud.githubusercontent.com/assets/6511937/6538013/184f161a-c422-11e4-822b-b117de235473.png)

A page refresh solves the problem but this was slightly confusing.

**Comment by monicacecilia** [comment]
Against my very strong thoughts about it ( :) ), @nathandunn and I have decided to punt this one over to 1.0.5 or later.
