### ISSUE TITLE
/users/updateUser rejects the username/password authentication in API requests

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#1871]
Am I making the request incorrectly?

```console
$ curl https://apollo.usegalaxy.eu/apollo_api/user/updateUser \
  -H 'Content-Type: application/json' \
  -d '{"role": "USER", "password": "redacted", "username": "admin@usegalaxy.eu", "organismPermissions": [], "newPassword": "", "firstName": "Test", "availableGroups": [], "groups": [], "userId": 24, "lastName": "User"}'
```

and here's the error message on the serve side:

`
Mar 14 15:54:14 apollo.usegalaxy.eu server[934]: 2018-03-14 15:54:14,031 [http-bio-8080-exec-9] ERROR apollo.UserController  - grails.validation.ValidationException: Validation Error(s) occurred during save():
Mar 14 15:54:14 apollo.usegalaxy.eu server[934]: - Field error in object 'org.bbop.apollo.User' on field 'username': rejected value [null]; codes [org.bbop.apollo.User.username.nullable.error.org.bbop.apollo.User.username,org.bbop.apollo.User.username.nullable.error.username,org.bbop.apollo.User.username.nullable.error.java.lang.String,org.bbop.apollo.User.username.nullable.error,user.username.nullable.error.org.bbop.apollo.User.username,user.username.nullable.error.username,user.username.nullable.error.java.lang.String,user.username.nullable.error,org.bbop.apollo.User.username.nullable.org.bbop.apollo.User.username,org.bbop.apollo.User.username.nullable.username,org.bbop.apollo.User.username.nullable.java.lang.String,org.bbop.apollo.User.username.nullable,user.username.nullable.org.bbop.apollo.User.username,user.username.nullable.username,user.username.nullable.java.lang.String,user.username.nullable,nullable.org.bbop.apollo.User.username,nullable.username,nullable.java.lang.String,nullable]; arguments [username,class org.bbop.apollo.User]; default message [Property [{0}] of class [{1}] cannot be null]
`

**Comment by nathandunn** [comment]
Oh, you need to supply the username as the `email` parameter.:

https://github.com/GMOD/Apollo/blob/master/grails-app/controllers/org/bbop/apollo/UserController.groovy#L485

Of course, maybe the should all use the exiting value if blank.
