### ISSUE TITLE
Can Apollo2 handle HTML tags?

### ISSUE THREAD

**Issue by dytk2134** [GMOD/Apollo#1882]
Dear all,

I'd like to hook the text in my track key and manipulate it with JavaScript. However it seems like the HTML tags only work on Jbrowse (red).  The text on the right site still be ` <span>some</span>` (orange).
Here is the screenshots:   
![image](https://user-images.githubusercontent.com/12807454/39146151-ed2bdec4-4703-11e8-8731-ad27c7afed96.png)

 
trackList.json  
```
{
   "formatVersion" : 1,
   "tracks" : [
      {
         "compress" : 0,
         "key" : "<span>some</span>",
         "label" : "test_model",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "style" : {
            "className" : "container-16px",
            "subfeatureClasses" : {
               "CDS" : "primary_gene_set-cds",
               "UTR" : "primary_gene_set-utr",
               "exon" : "container-100pct",
               "wholeCDS" : null
            }
         },
         "trackType" : null,
         "type" : "FeatureTrack",
         "urlTemplate" : "tracks/test_model/{refseq}/trackData.json"
      }
   ]
}
```

**Comment by nathandunn** [comment]
I fixed it here: https://github.com/GMOD/Apollo/commit/d0a49e5994601ae73dc90d204c9d53bb95116a4c

You can either patch it and redeploy or update to the most recent master. 

Thanks for reporting it.  Let us know if it doesn't work.
