### ISSUE TITLE
Unable to create deletion/substitution

### ISSUE THREAD

**Issue by selewis** [GMOD/Apollo#1883]
There's are bugs! I need to change CCC to CG.

But I can't do this with one edit, i.e. substitutions are always the same length, so that's the first bug. User's should be able to just paste in the before and after and be done.

Furthermore, I thought well, I'll just make one deletion (of a C) and one substitution of C->G. However that doesn't work either. "Cannot create overlapping sequence alterations". Adjacent is not overlapping. Clearly there is an off by one error because it should be possible to create adjacent alterations. That's the second bug.

**Comment by nathandunn** [comment]
Off by one error here: 

https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/SequenceTrack.js#L1098-L1110

Also need to change `==` to `===`

**Comment by nathandunn** [comment]
@deepakunni3  I can fix this on Friday or early next week unless you happen to be in apollo-land.  I have you test the PR either way.

**Comment by deepakunni3** [comment]
@nathandunn All yours :)

Let me know if you want to discuss about the fix for creating a substitution bug.
