### ISSUE TITLE
File descriptor leak running add_features_from_gff3_to_annotations.pl

### ISSUE THREAD

**Issue by wesleyemason** [GMOD/Apollo#1886]
While bulk loading annotations from GFF3 file, the webapollo java servlet will reach the open files ulimit.  Increasing the ulimit will allow for more annotations to be loaded at once, but the file handle leak will 
eventually result in the servlet becoming unresponsive with "too many open files" error.

Below is the output from ./apollo run-local:
...
2018-05-09 14:29:09,058 [http-nio-8080-exec-4] INFO  apollo.FeatureService  - calculateCDS
2018-05-09 14:29:09,058 [http-nio-8080-exec-4] DEBUG apollo.OrganismService  - using the default translation table
| Error java.io.FileNotFoundException: /home/<username>/.grails/2.5.5/.slcache/.index (Too many open files)
| Error 	at java.io.FileOutputStream.open0(Native Method)

The file descriptor leak appears to be in getRawResiduesFromSequenceFasta from SequenceService.groovy.   I had to add indexedFastaSequenceFile.close().

    String getRawResiduesFromSequenceFasta(Sequence sequence, int fmin, int fmax) {
        String sequenceString
        File genomeFastaFile = new File(sequence.organism.genomeFastaFileName)
        File genomeFastaIndexFile = new File(sequence.organism.genomeFastaIndexFileName)
        IndexedFastaSequenceFile indexedFastaSequenceFile = new IndexedFastaSequenceFile(genomeFastaFile, new FastaSequenceIndex(genomeFastaIndexFile))
        // using fmin + 1 since getSubsequenceAt uses 1-based start and ends
        sequenceString = indexedFastaSequenceFile.getSubsequenceAt(sequence.name, (long) fmin + 1, (long) fmax).getBaseString()
       +        indexedFastaSequenceFile.close()
        return sequenceString
    }

**Comment by nathandunn** [comment]
@wesleyemason   Is this your recommended fix? (adding the ```indexedFastaSequenceFile.close()```)? 

If that works, could you just create a PR and I'll get that merged in ASAP.  Thanks for finding it.

**Comment by wesleyemason** [comment]
Yes, that is the recommended fix.
