### ISSUE TITLE
plugin WebApollo not found, please ensure the plugin was included in this JBrowse build.

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1889]
* Search [mailing list](http://gmod.827538.n3.nabble.com/Apollo-f815553.html) or email list ```apollo@lists.lbl.gov``` if a general setup question. 

* Provide what you were doing and what you expected to see.  Screenshots, directory, config files are a plus if relevant.

Testing newest release, get an error "plugin WebApollo not found, please ensure the plugin was included in this JBrowse build."
 
* Provide the javascript console log output generated from the action. 
 
* Provide the server log output generated from the action (typically ```catalina.out```).
 No log errors in cataling.out or localhost access files

Screenshot
<img width="1406" alt="screen shot 2018-05-10 at 5 12 56 pm" src="https://user-images.githubusercontent.com/421248/39923297-13f71e9c-54f1-11e8-8319-e48cbc0be74a.png">

I'm still looking into this, but has anyone else seen this error?

**Comment by childers** [comment]
Confirmed that the plugins I specified in my apollo-config.groovy did not get loaded.

**Comment by childers** [comment]
I watched the logs as I ran ``` ./apollo deploy ```  and it did say it found and cloned the plugins, but when I tested it, it still shows no plugins.

**Comment by nathandunn** [comment]
What version of JBrowse are you using?   

It won’t work with the newest one(s).  Its on my list to fix, but its been a PITA. 

Nathan

**Comment by childers** [comment]
I had *just* worked out some internal issues and synced our local repo to the main JBrowse master.  Do you know what the last working commit was?

**Comment by nathandunn** [comment]
Should be this one:

15dfd2309f2d508d8bed782d0f68b38dd9927bb4

I need to get it working at some against master, but it won’t be today.  There were some UI bugs that I couldn’t work around.

**Comment by childers** [comment]
No worries, and thanks for the heads up!
