### ISSUE TITLE
List of changes is displayed different depending on drop down menu selection.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#189]
Failing item 17) at https://github.com/GMOD/Apollo/blob/master/docs/TestScript.md  "Check all filters, pagination, and number of results shown."

Depending on whether 10, 25, or 100 is selected from the drop down menu next to the word "Show", the list of changes is different. At times (with "100") well over 50 changes are visible, but when choosing "25" only one full page is visible, and only a few (4 in this case - ) after that. 
I don't know what is happening, it seems as if instead of going to the next page of results, it is going to the last page of the entire list.

**Comment by nathandunn** [comment]
ready to test on icebox staging

**Comment by monicacecilia** [comment]
Brilliant. Works well now. thank you!
