### ISSUE TITLE
user does not have permission for any organisms

### ISSUE THREAD

**Issue by clementmaz** [GMOD/Apollo#1908]
Hello,
I try to use the docker image `gmod/apollo:latest`. 
I can log in apollo as an admin user with `admin@local.host` but I can't add any organisms. Here is the logs when I click on `create organism`:
`java.lang.NullPointerException: Cannot get property 'storeClass' on null object`
`	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)`
`	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172)`
`	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:47)`
`	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)`
`	at org.bbop.apollo.SequenceService.$tt__loadRefSeqs(SequenceService.groovy:276)`
`	at org.bbop.apollo.SequenceService$_loadRefSeqs_closure11.doCall(SequenceService.groovy)`

...
...
`2018-06-22 12:45:03,902 [http-nio-8080-exec-8] ERROR apollo.OrganismController  - problem saving organism: java.lang.NullPointerException: Cannot get property 'storeClass' on null object`

`2018-06-22 12:45:05,784 [http-nio-8080-exec-10] ERROR apollo.UserController  - org.bbop.apollo.PermissionException: User does not have permission for any organisms.`

`2018-06-22 12:45:06,489 [http-nio-8080-exec-2] ERROR apollo.AnnotatorService  - Error: org.bbop.apollo.PermissionException: User does not have permission for any organisms.`

`2018-06-22 12:45:06,522 [http-nio-8080-exec-9] ERROR apollo.UserController  - User does not have permission for any organisms.`

Any idea what is the issue could be?
Thank you,
Clément

**Comment by nathandunn** [comment]
The most recent Apollo release worked great, but it had some issues translating to docker. 

Nathan

**Comment by nathandunn** [comment]
I am actively working on it.   In the meantime, the gmod/apollo:2.0.8 version should still work well.

**Comment by nathandunn** [comment]
This should be fixed here: https://github.com/GMOD/docker-apollo/releases/tag/2.1.0

The regular docker hub image is still building, but the quay.io one is built and working and I've run it successfully:

sudo docker run -it -p 8888:8080 quay.io/gmod/docker-apollo:latest

Re-open this if you run into any further trouble.

**Comment by clementmaz** [comment]
Thank you for your answer,
Unfortunately I am still having trouble with the command `sudo docker run -it -p 8888:8080 quay.io/gmod/docker-apollo:latest`:

`[....] Starting PostgreSQL 9.6 database server: main[....] The PostgreSQL server failed to start. Please check the log output: 2018-06-26 12:02:00.049 UTC [24] FATAL: could not access private key file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied 2018-06-26 12:02:00[FAILUTC [24] LOG: database system is shut down ... failed!
 failed!`
`WEBAPOLLO_HOST_FLAG: `
`CHADO_HOST_FLAG: `
`Waiting for DB`
`/var/run/postgresql:5432 - no response`

**Comment by nathandunn** [comment]
You may also want to remove all local images and containers:

https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes <https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes>

Looks pretty easy now that they have “docker system prune -a” added.   

I’m retesting now, but I expect the same result.  I’ll let you know if I find anything different. 

Nathan

**Comment by clementmaz** [comment]
I deleted the old containers/images but I have the same issue. The PostgreSQL server won't start:
`[....] Starting PostgreSQL 9.6 database server: main[....] The PostgreSQL server failed to start. Please check the log output: 2018-06-28 07:24:45.298 UTC [24] FATAL: could not access private key file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied 2018-06-28 07:24:45[FAILUTC [24] LOG: database system is shut down ... failed!`

**Comment by nathandunn** [comment]
1 - What version of docker are you using (system, version, etc.)?
2 - Have you tried it on a different machine / system? 

Are you launching this with a mounted server? 

Curious if it is related to this:

https://stackoverflow.com/questions/12087683/postgresql-wont-start-server-key-has-group-or-world-access <https://stackoverflow.com/questions/12087683/postgresql-wont-start-server-key-has-group-or-world-access>

**Comment by clementmaz** [comment]
1- It seems I am running an old version of docker (docker-engine) `Docker version 1.9.1, build a34a1d5` on an ubuntu server 16.04. 
2- I will try on a different system, I let you know whether it works or not.

**Comment by clementmaz** [comment]
2- I installed a recent version of docker `Docker version 18.03.1-ce, build 9ee9f40` on my laptop fedora 26.
The following command `docker run -it -v /var/lib/jbrowse/:/data -v /var/lib/jbrowse/postgres-data/:/var/lib/postgresql -p 7565:8080 quay.io/gmod/docker-apollo:latest` launches the apollo web server BUT I have the very first issue of this thread: I can't had any organisms.
Same problem with `docker run -it -v /var/lib/jbrowse/:/data -p 7565:8080 quay.io/gmod/docker-apollo:latest

**Comment by nathandunn** [comment]
- Can you send me a screen shot any error logs? 

For the postgresql version, you need to initialize a database in the specified directory (e.g., pg_init) and create the database in that directory (`/var/lib/jbrowse/postgres-data`) as well as make sure the jbrowse directory exists and is readable.

**Comment by clementmaz** [comment]
The following command `docker run --rm -it -v /var/lib/jbrowse/:/data -v /var/lib/jbrowse/postgres-data/:/var/lib/postgresql -p 7565:8080 quay.io/gmod/docker-apollo:latest` works on my laptop!

The issue seems to be the Storage Driver configuration of the docker deamon as explained here: https://github.com/puntonim/docker-postgresql93/issues/2
- fedora laptop:
`$ docker -D info`
`Server Version: 18.03.1-ce`
`Storage Driver: devicemapper`

- On my ubuntu server:
`$ docker -D info`
`Server Version: 18.03.1-ce`
`Storage Driver: aufs`

I will investigate further and I let you know if it works on my server.

**Comment by lijingbu** [comment]
Same issue here, the admin user doesn't have permission to add organism. 
I didn't user docker, but follow the instruction at https://genomearchitect.readthedocs.io/en/latest/ExampleBuild.html
I am on Ubuntu 18.04. Jave 1.8.0. 

Some related tomcat8 logs:

2018-09-10 17:37:20,859 [http-nio-8080-exec-6] ERROR apollo.UserController  - org.bbop.apollo.PermissionException: User does not have permission for any organisms.
2018-09-10 17:37:20,987 [http-nio-8080-exec-7] ERROR apollo.UserController  - User does not have permission for any organisms.
2018-09-10 17:37:20,995 [http-nio-8080-exec-2] ERROR apollo.AnnotatorService  - Error: org.bbop.apollo.PermissionException: User does not have permission for any organisms.

**Comment by nathandunn** [comment]
@lijingbu  I think yours is a separate issue.  Can you open a new issue and I will reply there.   If you provide screen shots that will also be helpful.  

I'm going to close this issue unless @clementmaz  has further feedback.
