### ISSUE TITLE
Removing status types error

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#1909]
I was adding feature types and ran into two issues:
First I clicked on a feature type and an organism, then realized that I could not unselect the feature type or organism.
Second, when I was ready to delete these problematic statuses, it threw an error.

It took me a bit to see that this is due to the fact that there is no cascading delete in the schema to handle deleting records in the secondary tables.  I ended up deleting the records from the linked tables first then the main table via SQL.  

```shell
# \d available_status;
       Table "public.available_status"
 Column  |          Type          | Modifiers 
---------+------------------------+-----------
 id      | bigint                 | not null
 version | bigint                 | not null
 value   | character varying(255) | not null
Indexes:
    "available_status_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "organism_filter" CONSTRAINT "fk_39svd38qq78gxs0idnu5yiorc" FOREIGN KEY (available_status_id) REFERENCES available_status(id)
    TABLE "available_status_feature_type" CONSTRAINT "fk_jcoeehgesgr9lc34aqsc0iubc" FOREIGN KEY (available_status_feature_types_id) REFERENCES available_status(id)

# \d organism_filter
              Table "public.organism_filter"
       Column        |          Type          | Modifiers 
---------------------+------------------------+-----------
 id                  | bigint                 | not null
 version             | bigint                 | not null
 organism_id         | bigint                 | not null
 class               | character varying(255) | not null
 available_status_id | bigint                 | 
 canned_key_id       | bigint                 | 
 canned_comment_id   | bigint                 | 
 canned_value_id     | bigint                 | 
Indexes:
    "organism_filter_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "fk_1ykkgglhecw7pina70hxhrhkf" FOREIGN KEY (canned_comment_id) REFERENCES canned_comment(id)
    "fk_39svd38qq78gxs0idnu5yiorc" FOREIGN KEY (available_status_id) REFERENCES available_status(id)
    "fk_k84f8qd6a80roie9yid9oa0gh" FOREIGN KEY (canned_value_id) REFERENCES canned_value(id)
    "fk_sd72dgaipyx0koibgt7wobga5" FOREIGN KEY (organism_id) REFERENCES organism(id)
    "fk_tjfmsb0nhnpda6dptagpcpbkp" FOREIGN KEY (canned_key_id) REFERENCES canned_key(id)

# \d available_status_feature_type;
      Table "public.available_status_feature_type"
              Column               |  Type  | Modifiers 
-----------------------------------+--------+-----------
 available_status_feature_types_id | bigint | 
 feature_type_id                   | bigint | 
Foreign-key constraints:
    "fk_dnofis69fbieijg6f562lv4f2" FOREIGN KEY (feature_type_id) REFERENCES feature_type(id)
    "fk_jcoeehgesgr9lc34aqsc0iubc" FOREIGN KEY (available_status_feature_types_id) REFERENCES available_status(id)

**Comment by childers** [comment]
Yes, it is. Built and tested yesterday.  Should it automatically update the schema if that changes?

**Comment by nathandunn** [comment]
Could you provide some screen shots of the interface while doing this?  

I just tried what I imagine you were doing on the demo site, but I didn’t have any problem. 

In theory it should automatically update the schema, but who knows.

**Comment by nathandunn** [comment]
Were you trying to delete a status / feature type after you’d annotated with? 

Also, is Feature Type organisms specific?   it could be configurable, but I’ not remembering, and I’m not seeing it by default.

**Comment by childers** [comment]
I had created a status, set a feature type and organism before realizing that leaving it blank would make it global.  When I went to delete it, I just got an error that was not informative (I think it said something along the lines of "there was an error"). 

I then went in to query the db directly and saw that I couldn't delete the records without first deleting the corresponding records in the feature and organism tables.

**Comment by childers** [comment]
Are there updated table definitions for those tables? 
```available_status```
```organism_filter```
```available_status_feature_type```

**Comment by nathandunn** [comment]
Each field is its a DB column, with a default ID (primary key) and version not shown:

- https://github.com/GMOD/Apollo/blob/master/grails-app/domain/org/bbop/apollo/AvailableStatus.groovy (value only)
   - automatically links to hasMany FeatureTypes https://github.com/GMOD/Apollo/blob/master/grails-app/domain/org/bbop/apollo/FeatureType.groovy which generates the table: `available_status_feature_type` 
- https://github.com/GMOD/Apollo/blob/master/grails-app/domain/org/bbop/apollo/AvailableStatusOrganismFilter.groovy and https://github.com/GMOD/Apollo/blob/master/grails-app/domain/org/bbop/apollo/OrganismFilter.groovy -> (AvailableStatus availableStatus, Organism organism)

**Comment by nathandunn** [comment]
@childers  This should be working now.   Let know if not.

**Comment by childers** [comment]
@nathandunn Thanks, it's working as expected now.
