### ISSUE TITLE
Honeybee with BAM - data-amel-demo.tgz: Permission denied

### ISSUE THREAD

**Issue by mictadlo** [GMOD/Apollo#1915]
Hi, 
I tried to download apollo's test dataset (Honeybee with BAM 17GB) as describe [here](http://genomearchitect.readthedocs.io/en/latest/Apollo2Build.html#adding-sample-data) but unfortunately, I got `data-amel-demo.tgz: Permission denied`.

What did I miss?

Thank in advance

Michal

**Comment by nathandunn** [comment]
That is weird.  I tried it myself and it seemed to work from the browser.  

Can you do this in terminal instead?

wget https://s3.amazonaws.com/apollo-data/data-amel-demo-nobam.tgz

wget https://s3.amazonaws.com/apollo-data/data-amel-demo.tgz


The ones with the BAM are about 17 GBs, so you may need to use an S3 client, but I’ve had it work prior without a hitch. 

Nathan

**Comment by mictadlo** [comment]
Sorry, my fault. I tried to download inside the volume folder from docker and it seems the permission has been changed.

**Comment by nathandunn** [comment]
No worries
