### ISSUE TITLE
Can add_features_from_gff3_to_annotations.pl load isoforms into Apollo2?

### ISSUE THREAD

**Issue by dytk2134** [GMOD/Apollo#1917]
Hi all,
I tried to load a gene model with two isoforms, but it seems like the model I loaded was split into two genes.

The command I used:  
```
add_features_from_gff3_to_annotations.pl -U http://localhost:8080/apollo \
 -u username -p password -i annotation.gff3 -o "Anoplophora glabripennis" -a -X
```
Part of annotation.gff3
```
NW_019416525.1  WebApollo       gene    1425325 1451176 .       -       .       ID=280F9C3E03B7E221B258FCB06DA8A08A;
NW_019416525.1  WebApollo       mRNA    1425325 1433787 .       -       .       Parent=280F9C3E03B7E221B258FCB06DA8A08A;ID=E90758558CD2C58A54AB34050E3B9F19;Name=Dual oxidase 2
NW_019416525.1  WebApollo       exon    1433581 1433787 .       -       .       Parent=E90758558CD2C58A54AB34050E3B9F19;ID=8A8A915BBDEA4341B743A92BB0CC3B08;
NW_019416525.1  WebApollo       CDS     1433581 1433635 .       -       0       Parent=E90758558CD2C58A54AB34050E3B9F19;ID=155E4EA3BD18AC43D11041D30C22E636;
NW_019416525.1  WebApollo       mRNA    1433860 1451176 .       -       .       Parent=280F9C3E03B7E221B258FCB06DA8A08A;ID=5BC9C3CA44A5CAA641BC79A5EC29D103;Name=very low-density lipoprotein receptor
NW_019416525.1  WebApollo       exon    1433860 1436853 .       -       .       Parent=5BC9C3CA44A5CAA641BC79A5EC29D103;ID=9E78031E2C8994C9BD897495CD8364F8;
NW_019416525.1  WebApollo       CDS     1436653 1436853 .       -       0       Parent=5BC9C3CA44A5CAA641BC79A5EC29D103;ID=5BC9C3CA44A5CAA641BC79A5EC29D103-CDS;
```
Annotations in Apollo2  
![image](https://user-images.githubusercontent.com/12807454/42336682-5f190d0e-8052-11e8-80ce-f2a7e37d6424.png)

Do you have any idea about this?

Thanks!

**Comment by nathandunn** [comment]
Can you download the annotation gff by right clicking and post that?  Also, can you take a screenshot of the annotations as well? 

Thank,

Nathan

**Comment by mpoelchau** [comment]
It turns out that the 2 isoforms in question don't overlap or share CDS (and therefore probably should be 2 different genes). Does add_features_from_gff3_to_annotations.pl automatically split isoforms into different genes in this case?

Not sure if this is a feature or a bug - probably depends on your perspective :).

**Comment by nathandunn** [comment]
Yes.  Apollo automatically splits them by default.  You can assign them manually if need be or have them calculate overlaps by exons instead.  

Nathan

**Comment by mpoelchau** [comment]
Okay, thanks!
