### ISSUE TITLE
deletions, insertions, substitutions not editable like SNV's

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1923]
@deepakunni3  Is this by design, or is it just not handling the types correctly? 

<img width="572" alt="screen shot 2018-07-22 at 4 33 00 pm" src="https://user-images.githubusercontent.com/751274/43051321-fe16fccc-8dcc-11e8-9466-c4304af6ab20.png">
<img width="583" alt="screen shot 2018-07-22 at 4 32 49 pm" src="https://user-images.githubusercontent.com/751274/43051322-fe35cd28-8dcc-11e8-81b7-14ff44d0d8ec.png">

**Comment by nathandunn** [comment]
The popup still seems to work fine, however.

**Comment by deepakunni3** [comment]
Thats a bug. Ideally it should show all the tabs for deletion and substitution.

**Comment by nathandunn** [comment]
Yeah, I was wondering if it should be create a type of SNP, or it was just a simple bug in detecting the appropriate biotype in GWT.

**Comment by nathandunn** [comment]
This was fixed as part of 2.2.1 (or whatever is in master)
