### ISSUE TITLE
add group -> StaleObjectStateException

### ISSUE THREAD

**Issue by luke-c-sargent** [GMOD/Apollo#1927]
When using the admin UI and adding a group (via group tab's `+ Add Group`), one of three things happens:
1. normal: group adds, list updates with new group
2. less normal: group is added (evidenced in `catalina.out`), but list does not update
3. worst-case: 
```ERROR apollo.GroupController  - org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect)``` 
-> list shows `1-0 of 0` and no entries

2  & 3 are resolvable with a refresh.

This seems to me like a race condition; does the query for the UI complete before, during or after the write to DB from the addition?

I seem to be able to avoid the issue in `3` if I place a `@Transactional` annotation above `def loadGroups()` in [grails-app/controllers/org/bbop/apollo/GroupController.groovy](https://github.com/GMOD/Apollo/blob/6189ff9e2973e1523ddcdbeee9d258c435c42a54/grails-app/controllers/org/bbop/apollo/GroupController.groovy#L55), though this will require more testing. This does not resolve issue `2`.

NOTE: using this commit...
https://github.com/GMOD/Apollo/commit/c0bdc58ba5b697a23c1bc059253bb9b7e1c91c4d
...for reasons; a cursory look through the commits since then do not seem to address this concern, though i'd be happy to be wrong!

**Comment by nathandunn** [comment]
@luke-c-sargent  adding Transactional makes sense as some times preferences get added (sigh).  

I think you are spot on that its a race condition. 

However, this might sound silly, but I would parse the response string.   My hope is that the transaction is complete and begins the return, but doesn't finish before its returned.  

```
 git diff
diff --git a/src/gwt/org/bbop/apollo/gwt/client/rest/GroupRestService.java b/src/gwt/org/bbop/apollo/gwt/client/rest/GroupRestService.java
index 34d92e584..0c5fb98ad 100644
--- a/src/gwt/org/bbop/apollo/gwt/client/rest/GroupRestService.java
+++ b/src/gwt/org/bbop/apollo/gwt/client/rest/GroupRestService.java
@@ -168,6 +168,7 @@ public class GroupRestService {
         RequestCallback requestCallback = new RequestCallback() {
             @Override
             public void onResponseReceived(Request request, Response response) {
+                JSONValue returnValue = JSONParser.parseStrict(response.getText());
                 Annotator.eventBus.fireEvent(new GroupChangeEvent(GroupChangeEvent.Action.ADD_GROUP));
             }
```

If that doesn't work, then the other solution is to load the group on update instead of triggering the update system.   I'm curious if this change would work for you, though.

**Comment by nathandunn** [comment]
@luke-c-sargent  is this still a problem?

**Comment by luke-c-sargent** [comment]
I'm not sure, I will revisit this soon as I look in to updating G-OnRamp's Apollo/JBrowse versions and keep you appraised

**Comment by nathandunn** [comment]
I'm going to close this for now, but let me know if it comes back.
