### ISSUE TITLE
Allow annotating single-level features

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#193]
For the 2014-04-03 release I made a code patch to prevent single-level features from being annotated because it caused a javascript crash (this is all documented in meeting notes e.g. here https://docs.google.com/presentation/d/1Ij5fz-TwJqshixYHD_sPlynm-rJpcuOE48T4OiyIPEc/edit?usp=sharing)

This was a cause for concern for some annotators
http://gmod.827538.n3.nabble.com/Error-trying-to-add-CDS-as-a-gene-to-user-annotation-td4047026.html#a4047041

This ability was not a limitation of the annotation engine though so it can be fixed

**Comment by cmdcolin** [comment]
Note: issue split #81

**Comment by cmdcolin** [comment]
See c86905b for patch

**Comment by cmdcolin** [comment]
Hi @nathandunn feel free to try this out. Basically, what you will see is if you take a feature like


    Group1.1    amel_OGSv3.2    match   514009  514378  .   -   0   ID=GB42155-RA

And then drag it to the annotation, the exported GFF will be


    ##gff-version 3
    Group1.1	.	gene	507599	515039	.	-	.	ID=E08C811759E39D9ED1047B2A60337AC7
    Group1.1	.	mRNA	514009	514378	.	-	.	Name=GB42155-RA;Parent=E08C811759E39D9ED1047B2A60337AC7;ID=488894B63F0BB56E9B5E2DBB51CF0F6C
    Group1.1	.	CDS	514009	514378	.	-	0	Parent=488894B63F0BB56E9B5E2DBB51CF0F6C;ID=488894B63F0BB56E9B5E2DBB51CF0F6C-CDS
    Group1.1	.	exon	514009	514378	.	-	.	Parent=488894B63F0BB56E9B5E2DBB51CF0F6C;ID=1E63F22874D4239AA873E3C37C94259C
    ###

**Comment by nathandunn** [comment]
too funny, was just about to do the same thing: 

    ##gff-version 3
    Group1.1    Prodigal:2.60   CDS 796 1557    .   -   0   ID=PROKKA_00001;inference=ab initio prediction:Prodigal:2.60;locus_tag=PROKKA_00001;Name=hypothetical protein
    Group1.1    Prodigal:2.60   CDS 1952    2398    .   +   0   ID=PROKKA_00002;inference=ab initio prediction:Prodigal:2.60;locus_tag=PROKKA_00002;Name=hypothetical protein
    Group1.1    Prodigal:2.60   CDS 2484    3998    .   -   0   ID=PROKKA_00003;eC_number=6.1.1.16;gene=cysS_1;inference=ab initio prediction:Prodigal:2.60,similar to AA sequence:UniProtKB:Q83BL7;locus_tag=PROKKA_00003;Name=Cysteine--tRNA ligase
    Group1.1    Prodigal:2.60   CDS 3952    4428    .   -   0   ID=PROKKA_00004;inference=ab initio prediction:Prodigal:2.60;locus_tag=PROKKA_00004;Name=hypothetical protein
    Group1.1    Prodigal:2.60   CDS 4719    5012    .   +   0   ID=PROKKA_00005;inference=ab initio prediction:Prodigal:2.60,protein motif:CLUSTERS:PRK02113;locus_tag=PROKKA_00005;Name=putative hydrolase
    Group1.1    Prodigal:2.60   CDS 5275    5775    .   -   0   ID=PROKKA_00006;inference=ab initio prediction:Prodigal:2.60;locus_tag=PROKKA_00006;Name=hypothetical protein
    Group1.1    Prodigal:2.60   CDS 6484    7215    .   -   0   ID=PROKKA_00007;eC_number=3.6.3.-;gene=lolD;inference=ab initio prediction:Prodigal:2.60,similar to AA sequence:UniProtKB:O66646;locus_tag=PROKKA_00007;Name=Lipoprotein-releasing system ATP-binding protein LolD

**Comment by nathandunn** [comment]
test procedure:
1 - create GFF3 file from above
2 - open Group1.1 for Honeybee
3 - annotate with evidence from that track

On Staging (1.0.4) this works.  On Demo (1.0.3) we get a warning saying that we can not annotate that type of feature.   The fix for 1.0.3 disallowed this as prior it just crashed without any type of warning.   

*IF* the annotation is correct then the 1.0.4 version is correct.  If it is not, then 1.0.3 is correct, and we need to have a more protracted discussion about how something like this is annotated. 

My only worry is that we have an exon type, which I suspect is incorrect.  Most likely we need to handle the back-end case for this better.  @monicacecilia  can confirm.

**Comment by nathandunn** [comment]
@monicacecilia   ready for your view

**Comment by monicacecilia** [comment]
Thanks for the explanation. Working now.

**Comment by nathandunn** [comment]
@cmdcolin   Can you verify that your patch is set.  If there is no patch needed just assign it to @monicacecilia  marked as Ready.   Otherwise assign it to me with the patch and I'll send it up.

**Comment by cmdcolin** [comment]
Should be ready now

**Comment by monicacecilia** [comment]
I am unable to open either of the GFF3 files you have on your examples above. Apollo simply leaves a message reading "Loading". See image:

![screen shot 2015-04-14 at 3 00 46 pm](https://cloud.githubusercontent.com/assets/1714621/7148346/03acb4ca-e2b7-11e4-8538-8d4ce97798aa.png)


However, I added a GFF3 of my own (created using Apollo2) and was able to open it to test whether it is possible to create an annotation from a GFF3 file. 
Although it is possible to create a new gene annotation using that file, it is only possible to do so when no other annotations have been created in the same area. --- and all the other details described in #263

**Comment by nathandunn** [comment]
@monicacecilia   Should this be closed or remain open until it can be tested properly?

**Comment by cmdcolin** [comment]
I think the "Loading" error may happen if you haven't converted tabs to spaces on the given input file. Expects them to be a tab separated file. I guess it should throw a better error but ya.

**Comment by cmdcolin** [comment]
If i works in other cases besides the #263 one then I'd say this is done.

**Comment by monicacecilia** [comment]
I re-tested with an updated GFF3 file. It works now. 

I agree that the failed GFF3 should send an error message. 

I suggest something like "Cannot load file. Please review format." or something along those lines.
