### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by kpepper** [GMOD/Apollo#1931]
Hi,

It seems that having write permission on an organism allows you to edit other peoples' annotations in the user-created annotations track (i.e. those owned by different users). Is there any way to prevent this behaviour?

Thanks.

**Comment by nathandunn** [comment]
There is!   https://genomearchitect.readthedocs.io/en/latest/Configure.html#only-owners-can-edit

You set this in the `apollo-config.groovy` file. 

The original case https://github.com/GMOD/Apollo/issues/1260

Let us know if you have any trouble with it.
