### ISSUE TITLE
Apollo Load Times and Login Failure - getAppState

### ISSUE THREAD

**Issue by MoffMade** [GMOD/Apollo#1939]
We have been facing an issue where administrators/users with access to large numbers of organisms cannot reliably log into Apollo, they just continuously get "Logged out or server failure. Attempt to reconnect?"

Some investigation shows that the web request to .../apollo/annotator/getAppState() takes an inordinate amount of time to respond, if at all.

![apollo-timeout](https://user-images.githubusercontent.com/5633348/45773423-e6f2c000-bc0f-11e8-9c2a-3e235818cdbf.png)

It seems to be related to the number of Organisms in the database, I'll be removing some extraneous organisms from the list and see how that affects our load times.

**Comment by nathandunn** [comment]
@MoffMade  That will definitely do it if large enough.    

- What version are you working at (we did fix some of this performance from earlier versions)? 
- How many organisms are you looking at?  
- And how many sequences  and how manyu features? 
- when it works, how large is the JSON?  

If you comment out these lines, I'm curious if it speeds it up:

https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/AnnotatorService.groovy#L29-L33 

Hopefully its just a matter of redoing the query.

**Comment by MoffMade** [comment]
- What version are you working at (we did fix some of this performance from earlier versions)?
the System Info page has "WEBAPOLLO_VERSION | d9894f2602029b0c2b461d5a33e5ecff8686d182", is this the version info you need?
- How many organisms are you looking at?
Currently at 561
- And how many sequences and how manyu features?
589 sequences, 47901 features
- when it works, how large is the JSON?
Just retrieved shows a 135kB in about 3.6 minutes (past tests had >5 minute response times when it worked, several attempts before it would properly work as well.)

![apollo-getappstate-worked](https://user-images.githubusercontent.com/5633348/45785080-a8213200-bc30-11e8-929e-363f902e15ee.png)

I can try commenting out those lines in the morning and see what happens

**Comment by nathandunn** [comment]
> On Sep 19, 2018, at 3:27 PM, Cory Maughmer <notifications@github.com> wrote:
> 
> What version are you working at (we did fix some of this performance from earlier versions)?
> the System Info page has "WEBAPOLLO_VERSION | d9894f2 <https://github.com/GMOD/Apollo/commit/d9894f2602029b0c2b461d5a33e5ecff8686d182>", is this the version info you need?

That’s about a year old.  The code in that version will be VERY slow for large numbers of organisms.  Its doing multiple expensive queries per organism.

https://github.com/GMOD/Apollo/blob/d9894f2602029b0c2b461d5a33e5ecff8686d182/grails-app/services/org/bbop/apollo/AnnotatorService.groovy#L26 <https://github.com/GMOD/Apollo/blob/d9894f2602029b0c2b461d5a33e5ecff8686d182/grails-app/services/org/bbop/apollo/AnnotatorService.groovy#L26>
> How many organisms are you looking at?
> Currently at 561

Yeah, not surprising with this version and that many users. 

I’m going to close this unless you have that problem in 2.1.0 (or you’re welcome to use master). 

Nathan

**Comment by nathandunn** [comment]
The current code-base will be MUCH faster.
