### ISSUE TITLE
Add Blast results to Apollo ?

### ISSUE THREAD

**Issue by agroppi** [GMOD/Apollo#1948]
I have blastp and blastx results formatted in GFF
I would like to add them as a track in my Apollo instance
What would be the procedure ?

Someting like this : 
`perl /home/apollo/jbrowse-master/bin/flatfile-to-json.pl \
--gff /home/apollo/rawdata/BlastP.gff \
--type  ???
--trackLabel BlastP
--out /home/apollo/jbrowse-data`

If yes, what type should I set ?

Thanks

**Comment by nathandunn** [comment]
I would have to see your GFF3 to be sure, but its usually the top-level view type, so for example mRNA or transcript (or both: mRNA|transcript).  

That being said, if you look at the JBrowse demo here:

https://jbrowse.org/demos.html <https://jbrowse.org/demos.html>

This uses in-memory:

https://jbrowse.org/code/JBrowse-1.15.4/?loc=ctgA%3A17248..17767&tracks=DNA%2CTranscript%2Cvolvox-sorted-vcf%2Cvolvox_gff3_tabix_html&data=sample_data%2Fjson%2Fvolvox&highlight= <https://jbrowse.org/code/JBrowse-1.15.4/?loc=ctgA:17248..17767&tracks=DNA,Transcript,volvox-sorted-vcf,volvox_gff3_tabix_html&data=sample_data/json/volvox&highlight=>

You can edit the track and see how it is configured directly with the store (might be easier than trying to format with perl).  But you have run it through a tabix indexer (https://www.biostars.org/p/92074/#92075 <https://www.biostars.org/p/92074/#92075>) :





Nathan

**Comment by agroppi** [comment]
Here is some lines from my BlastP.gff file

`GALM_BOVIN	blast_result	hit	14	195	.	+	.	ID=GALM_BOVIN_1;Parent=GALM_BOVIN;QueryID=g34449.t1.p1;QueryLength=194;QueryStart=26;QueryStop=183;SubjectFrame=1;Bitscore=91.3
YG31B_YEAST	blast_result	hit	560	1444	.	+	.	ID=YG31B_YEAST_2;Parent=YG31B_YEAST;QueryID=jg1.t1.p1;QueryLength=1474;QueryStart=552;QueryStop=1394;SubjectFrame=1;Bitscore=479
SD18_ARATH	blast_result	hit	103	220	.	+	.	ID=SD18_ARATH_3;Parent=SD18_ARATH;QueryID=jg10.t1.p1;QueryLength=129;QueryStart=7;QueryStop=118;SubjectFrame=1;Bitscore=105
YCF33_PYRYE	blast_result	hit	1	65	.	+	.	ID=YCF33_PYRYE_4;Parent=YCF33_PYRYE;QueryID=jg100.t1.p1;QueryLength=190;QueryStart=117;QueryStop=181;SubjectFrame=1;Bitscore=45.4
HMG14_ARATH	blast_result	hit	58	148	.	+	.	ID=HMG14_ARATH_5;Parent=HMG14_ARATH;QueryID=jg1000.t1.p1;QueryLength=193;QueryStart=97;QueryStop=187;SubjectFrame=1;Bitscore=138
MINP1_HUMAN	blast_result	hit	326	445	.	+	.	ID=MINP1_HUMAN_6;Parent=MINP1_HUMAN;QueryID=jg10004.t1.p1;QueryLength=393;QueryStart=203;QueryStop=338;SubjectFrame=1;Bitscore=60.1
`


For pfam_domains.gff : 

`chr1	hmmscan	PFAM	11416724	11416749	99.5	+	.	ID=g34449.t1.p1.Aldose_epim.1;Name=PF01263.Aldose_epim.1
chr1	hmmscan	PFAM	11416839	11416942	99.5	+	.	ID=g34449.t1.p1.Aldose_epim.1;Name=PF01263.Aldose_epim.1
chr4	hmmscan	PFAM	3455	3615	118.3	+	.	ID=jg1.t1.p1.RVT_1.1;Name=PF00078.RVT_1.1
chr4	hmmscan	PFAM	4970	5082	53.8	+	.	ID=jg1.t1.p1.rve.1;Name=PF00665.rve.1
chr4	hmmscan	PFAM	1979	2074	46.0	+	.	ID=jg1.t1.p1.Retrotrans_gag.1;Name=PF03732.Retrotrans_gag.1`

Thanks

**Comment by nathandunn** [comment]
@agroppi  I think you can set "PFAM" or "hit" as the type and it should work.   

So, once you get it initialized, you might try setting the type in trackList.json to:

    WebApollo/View/Track/DraggableBLASTFeatures . 

If that works, I think it recognizes hsps, etc. but it may not be any better or worse.

**Comment by nathandunn** [comment]
Sorry, @agroppi  is this still active or can I close?

**Comment by agroppi** [comment]
Solved :)
