### ISSUE TITLE
Show annotations by user

### ISSUE THREAD

**Issue by AgnesBaud** [GMOD/Apollo#1952]
Hello,

I'm sorry because I feel like my question is stupid, but I need to filter annotations by user/owner. But in the tab "Annotation", the window "All users", doesn't show any other propositions than "All users" even though several users have made annotations. I don't know if I should have uncommented some parameters in some files ?

Thank you in advance,

Agnès

![image](https://user-images.githubusercontent.com/22837825/47715618-8d36da00-dc40-11e8-99fc-424f5ffa30bb.png)

**Comment by nathandunn** [comment]
Wow.  That is definitely a bug.    I'll see if I can't find a fix for it. 

In the interim you can go into admin -> report -> changes to do this.   This should be an easy fix.  I'll try to get it in this week.

**Comment by AgnesBaud** [comment]
Thank you for your response and for the tip !

**Comment by nathandunn** [comment]
@AgnesBaud  This **should** be fixed on master, but let me know if its not.

**Comment by AgnesBaud** [comment]
Hello @nathandunn,
I can now see the names in addition of "All Users" but it doesn't filter the annotations. Also I only see the names as admin but not as a user (with read, write and export permissions).

**Comment by nathandunn** [comment]
Shoot ., I will take a look. 

Nathan

**Comment by nathandunn** [comment]
@AgnesBaud this should fix it.

**Comment by AgnesBaud** [comment]
Thank you very much @nathandunn. This works great for admin and instructor users, but lambda users don't have access to the names. Sorry to bother you again and again thank you.
Agnès

**Comment by nathandunn** [comment]
No worries.  These are important to get fixed. 

What do you mean by a lambda user? 

Nathan

**Comment by AgnesBaud** [comment]
Sorry I wasn't clear, I use the word "user" too much 😬
I meant someone with the role user and not an admin or an instructor. Even if they are given all the permissions on an organism (write, export, read and even admin), they don't see the names and only see "All users" in the box.
Agnès

**Comment by nathandunn** [comment]
I see.   I’ll take a look.  

Nathan

**Comment by nathandunn** [comment]
@AgnesBaud  that should be fixed now

**Comment by AgnesBaud** [comment]
Perfect. Thank you !
