### ISSUE TITLE
add  Shine Dalgarno sequence

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#1955]
- [x] add type for this: http://www.sequenceontology.org/browser/current_svn/term/SO:0000552
- [x] allow individual addition 
- [x] confirm `change_type` works
- [ ] add "associate" to gene activated by terminator and shine dalgarno
  - [x] add RHS methods (2)
  - [x] add FeatureService method (2) 
  - [x] add integration tests (2)
    - [x] add integration data
  - [x] add method to interface
  - [x] update interface to be highligted for only some things (add check for regulator vs transcript with gene)
- ~~ when dragged up together, automatically creates the relationship (mRNA + Shine)?  . . not sure about this~~

===

- [ ] confirm exportable associations to a Gene as Parent (or `part_of` ) (as opposed to transcript)

**Comment by MoffMade** [comment]
Here is a current example of our workaround for annotating the Shine Dalgarno sequences (SDs)

GFF3 Example used as input into an Evidence track:
![gff3-sd-evidence](https://user-images.githubusercontent.com/5633348/50027806-26cd0780-ffb3-11e8-96e9-b028915d6bc5.png)

Evidence elevated to an annotated feature:
![apollo-sd-sequences](https://user-images.githubusercontent.com/5633348/50027826-3c423180-ffb3-11e8-82ce-f6b58808d01d.png)

Exported GFF3 showing the SDs as exons:
![gff3-sd-sequence](https://user-images.githubusercontent.com/5633348/50027854-48c68a00-ffb3-11e8-8408-6dfacd305775.png)

**Comment by nathandunn** [comment]
When annotation is done, the entire Gene, with the Shine Dalgano and CDS / Exon is added at once, so we would need to infer these types.
