### ISSUE TITLE
Can't add an isoform after deleting gene name

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#1961]
Hi there!

It looks like Apollo2 assumes that a gene needs a name. (It would be nice, but you can't have everything!) If you delete a gene name, you can't add another isoform (get error 'Cannot get property 'name' on null object').

Deleted name:
![name](https://user-images.githubusercontent.com/5487172/48803198-8561d700-ecce-11e8-9b4d-874c66c6d445.png)

error: 
![error](https://user-images.githubusercontent.com/5487172/48803154-67947200-ecce-11e8-964f-a2c597f43ea5.png)

javascript console log:
![js](https://user-images.githubusercontent.com/5487172/48803261-b5a97580-ecce-11e8-952c-4f7cb37a8d84.png)

tomcat log:
```
2018-11-20 16:16:01,877 [Actor Thread 8] ERROR apollo.AnnotationEditorController  - CAUGHT ERROR through websocket call: java.lang.reflect.InvocationTargetException
2018-11-20 16:16:01,878 [Actor Thread 8] ERROR apollo.AnnotationEditorController  - THROWING PARENT ERROR instead through reflection: java.lang.NullPointerException: Cannot get property 'name' on null object
2018-11-20 16:16:01,878 [Actor Thread 8] ERROR apollo.AnnotationEditorController  - exception java.lang.NullPointerException: Cannot get property 'name' on null object
2018-11-20 16:16:01,878 [Actor Thread 8] ERROR apollo.AnnotationEditorController  - exception message Cannot get property 'name' on null object
2018-11-20 16:16:01,878 [Actor Thread 8] ERROR apollo.AnnotationEditorController  - username demo
2018-11-20 16:16:01,878 [Actor Thread 8] ERROR apollo.AnnotationEditorController  - error destination message: /topic/AnnotationNotification/user/demo
```

Version etc:
- Version: 2.1.1-SNAPSHOT
- Grails version: 2.5.5
- Groovy version: 2.4.4
- JVM version: 1.8.0_181
- Servlet Container Version: Apache Tomcat/8.5.23

Since a gene name isn't required for an annotation, it would be nice to not have this constraint.

Thank you!

**Comment by nathandunn** [comment]
@mpoelchau  Its definitely set to non-nullable per design.   Most other objects require a name field other than gene. 

That being said, will genes always have a symbol, or will the be symbol-less and name-less?

**Comment by mpoelchau** [comment]
Well, if we're going by the gff3 spec, a gene should have an ID (assuming it also has child features), but isn't required to have a name. If you're importing to chado, a name isn't required, either - but a uniquename is (http://gmod.org/wiki/Chado_Sequence_Module). I wouldn't assume that the gene has a symbol, either. 

So Apollo doesn't assign the gene object an internal, unique ID to use, instead (equivalent in function to the gff3 ID, or the chado feature table uniquename)? What if there are 2 genes in the same genome that have the same name? 

Many of our annotators only name at the mRNA level - we can change our requirements if need be. The Apollo auto-generated names can usually not be re-used as name attributes, so we will need to replace them with something conforming to the UniProt/INSDC naming guidelines. That said, if the onus is on the end-user to have a name for the gene (and also the mRNA?), and there are specific requirements for that name (e.g. it's unique), perhaps there could be a more user-friendly error that would let them know that a gene name is required.

**Comment by nathandunn** [comment]
@mpoelchau  Here is the base feature class: https://github.com/GMOD/Apollo/blob/master/grails-app/domain/org/bbop/apollo/Feature.groovy

Looks like we need to:
- [ ] set name to nullable: true
- [ ] uniqueName nullable: false, unique: true  (not sure why this wasn't set before)
- [ ] ensure that the outgoing Chado conforms to this, as well

My only trepidation is if there are requirements in the code that require a name, which there may be, making this a bad fix.   If there are, I'll add a better error suggesting that a user must provide a name, even if its a temporary one.
