### ISSUE TITLE
How do I change the way UTRs are displayed?

### ISSUE THREAD

**Issue by cghiban** [GMOD/Apollo#197]
Hi,

Some people don't like how WebApollo displays UTRs by default? They are displayed as shorter boxes than the exons. Is this something I can fix as a user? Is so, could you give me a few hints on where to start?

Thanks,
Cornel

**Comment by nathandunn** [comment]
You would customize it in your trackList.json or tracks.conf file (though there may be a more universal solution):

http://gmod.org/wiki/JBrowse_Configuration_Guide#HTMLFeatures_Configuration_Options <http://gmod.org/wiki/JBrowse_Configuration_Guide#HTMLFeatures_Configuration_Options>

I don’t see a direct hook for what you are trying to do, but worst-case you would have to dig into jbrowse itself.

Yeah may want to search here, first, though.    I’m not sure if someone has a good example of what you’re trying to do, so I’ll X-post onto the jbrowse list.

You may want 

Nathan

**Comment by cghiban** [comment]
Hi Nathan,

What if i change the CSS or UTR features? Seems easier this way..

**Comment by nathandunn** [comment]
Oh, that is exactly right, not sure why that didn't pop out at me at first:

style→subfeatureClasses	Key-value pairs of CSS classes for subfeatures, organized by feature type. Example: { "CDS" : "transcript-CDS","UTR" : "transcript-UTR" }

Let me know if you need me to keep this open.
