### ISSUE TITLE
WARN  apollo.AnnotatorController  - Permission exception: User does not have permission for any organisms.

### ISSUE THREAD

**Issue by zhangw0128** [GMOD/Apollo#1972]
Hi，I am trying to run Apollo locally to add the organisms. I run the command “bin/prepare-refseqs.pl --fasta pyu_data/scf1117875582023.fa --out /opt/apollo/data” and got the folder /opt/apollo/data which include names, seq, tracks, trackList.json and tracks.conf. However,i also can't create organism and it display "Organism directory must be an absolute path pointing to 'trackList.json'". The sever display "| Error 2018-12-04 14:19:42,341 [http-nio-8080-exec-12] ERROR apollo.UserController  - User does not have permission for any organisms.
| Error 2018-12-04 14:19:42,358 [http-nio-8080-exec-15] ERROR apollo.AnnotatorService  - Error: org.bbop.apollo.PermissionException: User does not have permission for any organisms.
2018-12-04 14:19:58,039 [http-nio-8080-exec-15] WARN  apollo.AnnotatorController  - Permission exception: User does not have permission for any organisms. " 
Any help you could provide would be appreciated,

Thanks,

Best,
zhangw

**Comment by nathandunn** [comment]
So, the display of "user does not have access to any organisms" is to be expected. 

However, you should be able to add organisms to the directory `/opt/apollo/data` if that is where you specified your jbrowse directory.   When you point to the directory here (Figure 2) https://genomearchitect.readthedocs.io/en/latest/Apollo2Build.html#login-to-the-web-interface 

What are the contents of the directory `/opt/apollo/data` ?

**Comment by zhangw0128** [comment]
Thank you for your reply. The apollo had installed by following the Quick-start Developer’s guide,so i don't know where is the specified directory.How should I use the command to view that where is my jbrowse specified directory? 

Thanks, 
best, 
zhangw

**Comment by zhangw0128** [comment]
> So, the display of "user does not have access to any organisms" is to be expected.
> 
> However, you should be able to add organisms to the directory `/opt/apollo/data` if that is where you specified your jbrowse directory. When you point to the directory here (Figure 2) https://genomearchitect.readthedocs.io/en/latest/Apollo2Build.html#login-to-the-web-interface
> 
> What are the contents of the directory `/opt/apollo/data` ?

Thank you for your reply. The apollo had installed by following the Quick-start Developer’s guide,so i don't know where is the specified directory.How should I use the command to view that where is my jbrowse specified directory?

**Comment by nathandunn** [comment]
What happens if you run:

    ls /opt/apollo/data

**Comment by zhangw0128** [comment]
> 如果您运行会发生什么：
> 
> ```
> ls /opt/apollo/data 
> ```

it display files contain "names  seq  trackList.json tracks  tracks.conf"

**Comment by nathandunn** [comment]
When you add organisms what directory do you enter?  

It should be `/opt/apollo/data/`

Can you send me a screenshot of your add organism screen (assuming it fails again)?

**Comment by zhangw0128** [comment]
> 当您添加有机体时，您输入的目录是什么？
> 
> 它应该是 `/opt/apollo/data/`
> 
> 你能给我发一个你的添加有机体屏幕的截图（假设它再次失败）吗？

![aq8 sw8uoq 001khqf jd9j](https://user-images.githubusercontent.com/45394221/49487623-44e18c00-f87e-11e8-85dc-12ebdbc5f763.png)
It hasn't changed.

**Comment by nathandunn** [comment]
<img width="658" alt="screen shot 2018-12-04 at 7 13 12 pm" src="https://user-images.githubusercontent.com/751274/49487754-b2e37000-f7f8-11e8-91ce-29553df30164.png">

**Comment by zhangw0128** [comment]
> When you add organisms what directory do you enter?
> 
> It should be `/opt/apollo/data/`
> 
> Can you send me a screenshot of your add organism screen (assuming it fails again)?

Thank you again，I found myself making a stupid mistake.Generally, how long does Creating Organism take?It stayed at this interface.
![zz24lj0kf qqofaf ap0snn](https://user-images.githubusercontent.com/45394221/49488614-4f9e2000-f882-11e8-8e56-efd020a06e31.png)
maybe the name is wrong？

**Comment by nathandunn** [comment]
It depends on the amount of scaffolds.    If you run the command `top` you should see java and/or postgresql at quite a bit.  

For about 5,000 scaffolds it takes about 20 seconds.

**Comment by zhangw0128** [comment]
> It depends on the amount of scaffolds. If you run the command `top` you should see java and/or postgresql at quite a bit.
> 
> For about 5,000 scaffolds it takes about 20 seconds.

Badly，I also cannot create the organism，and it stays in that interface. Processing......
How should i do?

**Comment by zhangw0128** [comment]
![zb2i g m b 6 u 84u 1m3](https://user-images.githubusercontent.com/45394221/49518762-65d7ca80-f8da-11e8-8f35-593b2d5e6af6.png)

**Comment by nathandunn** [comment]
Can you load the directory via jbrowse?

Also, how many sequences do you have in your fasta ?   

How large is your fasts file?

Can you send me the file?

Nathan

**Comment by zhangw0128** [comment]
> Can you load the directory via jbrowse? Also, how many sequences do you have in your fasta ? How large is your fasts file? Can you send me the file? Nathan
> […](#)
> On Dec 5, 2018, at 5:43 AM, zhangw0128 ***@***.***> wrote: It depends on the amount of scaffolds. If you run the command top you should see java and/or postgresql at quite a bit. For about 5,000 scaffolds it takes about 20 seconds. Badly，I also cannot create the organism，and it stays in that interface. Processing...... How should i do? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

The problem wassolved,because I used Google Chrome. 
Thank you very much! 
best,
zhangw

**Comment by nathandunn** [comment]
What was the failing browser?

Thanks,

Nathan

**Comment by nathandunn** [comment]
Thanks

**Comment by biofilos** [comment]
I am not sure if I missed it in the documentation, but I had the same problem.
When I created my admin account (the first account), I tried to add an organism that existed in the data directory, but saw the permission exception described in this post. However, when I logged out and logged in again, I was able to add organisms. I leave this here in case it is useful to someone else

Juan Felipe Ortiz

**Comment by nathandunn** [comment]
@biofilos  I'll take another look.  Are you building off of the develop branch or a specific version?

**Comment by biofilos** [comment]
I am using v2.4.1
I think this is more an issue with documentation than with Apollo itself. In the docs (I followed the [quicstart devs guide](https://genomearchitect.readthedocs.io/en/latest/Apollo2Build.html)). After the section "Verify install requirements", the documentation reads like suggestions, not as steps. for that reason it was not clear to me when in the process I had to add the data. For example, would I have to run run-local after adding data using the jbrowse scripts?, could I just copy/paste the data directory (with config files) from an existing jbrowse instance? I tried those things and they failed, but my guess is that it failed because the permissions issue (I got it running, so I don't want to mess around with it any more than necessary). On that note, it would be helpful if it was stated what version of Jbrowse was compatible with Apollo.  
Other than that, if the docs state that we have to log out after creating the first admin  user and then log in again, my guess is that a lot of people could avoid this problem.

Juan Felipe Ortiz

**Comment by nathandunn** [comment]
@biofilos  That guide is more geared towards developers, however it was the first one that appeared. 

I updated the instructions here so setup comes first in the doc: https://genomearchitect.readthedocs.io/en/latest

> Other than that, if the docs state that we have to log out after creating the first admin user and then log in again, my guess is that a lot of people could avoid this problem.

As the first admin user, you should be able to begin adding organisms immediately. 

> On that note, it would be helpful if it was stated what version of Jbrowse was compatible with Apollo.

Apollo installs its own JBrowse with its own JBrowse version. 

Feel free to edit / /add to the doc.  We had a user add this https://genomearchitect.readthedocs.io/en/latest/ExampleBuild.html#example-build-script-on-unix-with-mysql  which I think can be more helpful than a generic guide. 

I can merge anything in that you have into the doc.
