### ISSUE TITLE
updated gff3_config.xml not recognized.

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#198]
Our customized gff3_config.xml continues to get overwritten with the default version during the 
 ./apollo deploy phase. 
 Is this being treated differently than the other config files? The quick start guide doesn't mention copying it into the base directory before running deploy, and if I do copy it in, it uses a default version ( src/main/webapp/config/gff3_config.xml ). Should I just update the copy in the src directory before building the war?  If so, could you update the documentation to reflect this? 

Is there a reason why gff3_config.xml is treated differently from the other config files?

This is on 1.0.4

**Comment by childers** [comment]
Update, it looks like my updated gff3_config.xml in the base git directory was overwritten with the default. version.

**Comment by nathandunn** [comment]
I can make this another "sample_XX"_config.xml.   Looks like I need one for chado, one for fasta, one for gff3, one for mapping.   

By default these should all copy over.

**Comment by nathandunn** [comment]
I can make this change pretty quickly and get it out today if that sounds good.

**Comment by childers** [comment]
Will that cause it to behave the same way as the other configuration files?  

Updating the copy in < src/main/webapp/config/gff3_config.xml > did let me use my modified file, but just having it in the base git directory did not.

**Comment by nathandunn** [comment]
Short answer yes.  

Here are the explicit steps I would take:

1 - in git, move src/main/webapps/gff3_config.xml to ./sample_gff3_config.xml
2 - during the deploy step  if you had a gff3_config.xml in your base directory it would copy that.  Otherwise it would complain that you don’t have them specified . . . similar to other required files.    

Let me know if that sounds good. 

Nathan

**Comment by childers** [comment]
1. That is exactly what I ended up doing, and it worked just fine.
2. Before updating the file in src/main/webapps/config, it was silently overwriting my custom file with the default that came prepackaged in src/main/webapps/config.  I assume that it is still doing this, only now it is overwriting what I have with the updated copy.

**Comment by nathandunn** [comment]
Let me know if this works .. . .

**Comment by monicacecilia** [comment]
I believe you.
