### ISSUE TITLE
Problem finding JBlibs

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#199]
I was attempting to run add_transcripts_from_gff3_to_annotations.pl , and it died with the following error:

`$ perl add_transcripts_from_gff3_to_annotations.pl 
Can't locate JBlibs.pm in @INC (@INC contains: /app/data/WebApollo_deployment/1.0.4/tools/data/../../src/perl5 /opt/ActivePerl-5.16/site/lib /opt/ActivePerl-5.16/lib .) at add_transcripts_from_gff3_to_annotations.pl line 10.
BEGIN failed--compilation aborted at add_transcripts_from_gff3_to_annotations.pl line 10.`

I corrected this by manually pulling the library in:
`use lib "../../../Jbrowse_from_github/src/perl5";
use JBlibs;`

Most if not all of the tools scripts use JBlibs.  I guess I have two questions:
1. Is this caused by me having a separate JBrowse directory that I run make with?
2. Is there a better way I can set this up so that the other tools scripts will work without needing to edit them?

**Comment by cmdcolin** [comment]
I believe you first need to run "apollo deploy" or "install_jbrowse.sh" to get all the perl/jbrowse libraries initialized first, which is true of the Makefile based deployment strategy as well.


If you want to avoid this, you can run "cpanm ." or "cpan ." inside of your custom jbrowse directory and this will install the JBLibs to the system perl

**Comment by childers** [comment]
This release of JBrowse was one I had used and set up in the past with setup.sh.  To be safe, I reran the script, before navigating to the Web Apollo directory and running the make file.  

Previously, I had just run ./apollo deploy several times to build some instances for testing. The deploy command succeeds, and the instances seem to work fine. The scripts still fail unless I manually load the library.

**Comment by nathandunn** [comment]
Is this a JBrowse bug?   I also noticed I have to add libraries when setup.sh is missing them.   I’m happy to test any changes on a vanilla Ubuntu / RedHat instance.  

Nathan

**Comment by childers** [comment]
I think this is something with Web Apollo, but only because the issue is with me trying to run the accessory scripts. I know that it will make a jbrowse-download directory if you don't specify the JBrowse location with a make command, could that be part of the problem?

**Comment by nathandunn** [comment]
I see.  Yeah, we might need to add this into the apollo binary somehow, either as a “usage” or a direct install in the same way that jbrowse does its install magic.  

Nathan

**Comment by cmdcolin** [comment]
The perl scripts that had dependencies on jblibs are removed from 2.0. Suggest closure

**Comment by nathandunn** [comment]
@cmdcolin   I think that this is still there:

https://github.com/GMOD/Apollo/blob/master/tools/data/add_transcripts_from_gff3_to_annotations.pl

Do we just need to upgrade the installation piece?

**Comment by cmdcolin** [comment]
Yes there is still that script. That is not really a core script though, and it should not give the jblibs error anyways if everything is installed correctly (we have a note in the troubleshooting guide about the jblibs error noting the proper installation paths)

**Comment by nathandunn** [comment]
Is there another way to do this?    If not, I think we should leave this until there is. 

We could even a groovy version of this using BioJava (or anything really) to import the GFF3 (would need to create an issue for this). 

In the interim, we need to update the install script, or, like you said, it is in the doc.

**Comment by cmdcolin** [comment]
I think this can be closed, the install script doesn't need any updates for this to work

**Comment by ajulian0416** [comment]
I have encountered the same issue mentioned in this thread. I have tried the mentioned fixes, install_jbrowse.sh, apollo deploy, etc, but I am still getting this error. Has there been another way to resolve this issue?
