### ISSUE TITLE
Autosuggestion for Name field when editing info on an Annotation

### ISSUE THREAD

**Issue by MoffMade** [GMOD/Apollo#1991]
We'd like to be able to optionally provide a controlled vocabulary list that will be suggested as a user edits the Name field for an annotation. It'd be good to still allow free entry, but the suggestions would be useful to help enforce naming conventions.

Perhaps have an option in the configuration files for Apollo to point to a list of terms/names on deployment to use?

For clarification, this field is the one in question:
![autosuggest-apollo](https://user-images.githubusercontent.com/5633348/50029859-e755e980-ffb9-11e8-984e-193b5666ea37.png)

**Comment by MoffMade** [comment]
Would it be one method or the other, or both available? I can see both a controlled vocabulary as well as controlled formatting "rules" being useful

**Comment by nathandunn** [comment]
I would think both.

**Comment by jrr-cpt** [comment]
[phage protein names autosuggest list 190215.txt](https://github.com/GMOD/Apollo/files/2870885/phage.protein.names.autosuggest.list.190215.txt)

A list of phage protein names to autosuggest. Good list for getting it set up, though not a final list. We slightly modified from a list the Pittsburgh group uses for SEA-PHAGES. These names should all follow the NCBI/UniProt Naming Guidelines: [http://insideuniprot.blogspot.com/2018/07/new-guidelines-to-help-with-protein.html](http://insideuniprot.blogspot.com/2018/07/new-guidelines-to-help-with-protein.html )

**Comment by nathandunn** [comment]
As per today's meeting, suggestions would be just that (as part of lookup).   

Not sure if it would be just the text file, or the text file is loaded up into a databases.  It should really be treated as a "prefix" database for naming things
