### ISSUE TITLE
apollo-config.groovy best approach for docker 

### ISSUE THREAD

**Issue by likku3** [GMOD/Apollo#1995]
I wouldn't categorize this as an issue.What I am trying to do is.

I am deploying docker-apollo container with out DB using kubernetes/AWS ECS. While i am building the dockerfile I am giving my postgresql username and password for apolloDB in apollo-config.groovy file.While I build the docker image apollo-config.groovy file gets stored in the WAR file .This means the docker image is baked with the DB credentials which is not a recommended method. Can you please throw some light how can I put this apollo-config.groovy file during the spinning of container rather than baking with dockerfile.

Thanks in advance

**Comment by nathandunn** [comment]
@likku3  Hey, next time feel free to post to the apollo mailing list in the future. 

The way it is setup, it should read database username / password info via environment variables when running it.   From here https://github.com/GMOD/docker-apollo/blob/master/apollo-config.groovy#L9 you should be able to supply environment variables directly.  Someone smarter than me set it up, so I haven't tried it, yet (but please update the [README.md](https://github.com/GMOD/docker-apollo/blob/master/README.md) for the project if you think it would help others). 

However, looking at [this](https://docs.docker.com/engine/reference/run/#env-environment-variables) I think you would do something like:

    docker run -it -e "WEBAPOLLO_DB_USERNAME=db_user" -e -e "WEBAPOLLO_DB_PASSWORD=super-duper-secret" -p 8888:8080 quay.io/gmod/docker-apollo:2.2.0
