### ISSUE TITLE
Apollo expects to be run in a subdirectory

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#200]
I deployed Apollo in `$CATALINA_HOME/webapps/ROOT/`, overwriting everything in that folder.

```javascript
$(document).ready(function() {
  var pathname = location.pathname;
  context = /^\/([^\/]+)\//.exec(pathname)[1];
  //snip
});
```

That snippet on the /sequences route expects locations to be `/some_path/sequences`, and won't accept other options. I imagine that snippet will likewise have issues if deployed under paths like `/a/b/c/apollo/sequences`.

xref http://gmod.827538.n3.nabble.com/WebApollo-500-on-Login-Route-in-container-td4048805.html

**Comment by cmdcolin** [comment]
This is sort of a different manifestation of the same problem brought up here https://github.com/GMOD/Apollo/issues/130

**Comment by erasche** [comment]
So it is! I'll close this as a duplicate and cross post there. Thanks!
