### ISSUE TITLE
add orig_id as an attribute to our feature 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2002]
ID is lost because we use unique_names in order to support multiple tracks.   We should keep it that way, but add the original id as an attribute so that it can be replaced on export: `orig_id=XX11`

**Comment by nathandunn** [comment]
@juke34

**Comment by nathandunn** [comment]
@Juke34 this is done.  

Note you have to configure apollo-config.groovy so that `set_orig_id=true`

https://github.com/GMOD/Apollo/blob/master/grails-app/conf/Config.groovy#L218

It sets an attribute `orig_id` which shows up as a property (and exports in GFF3).

**Comment by stiobhan** [comment]
> @Juke34 this is done.
> 
> Note you have to configure apollo-config.groovy so that `set_orig_id=true`
> 
Just to clarify, it is `store_orig_id` as written in the config file you linked, and not `set_orig_id`, correct?

**Comment by nathandunn** [comment]
@stiobhan   / @Juke34   Yes, you are right . it should be `store_orig_id` . .  Apologize for that.    It should be correct here, but let me know if not:

https://genomearchitect.readthedocs.io/en/latest/Configure.html?highlight=store_orig_id
