### ISSUE TITLE
Apollo doesn't play nicely with proxies.

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#201]
Internally, the Login form seems to be accessed via a GET request (e.g. `http://localhost:8080/apollo/user_interfaces/encryptedlocaldb/login.html`), which seems a bit odd. 

Unfortunately, the URL that's constructed to do that is the one visible to the end user. If the user is accessing Apollo at a location that's not known or understood internally, then Apollo fails to load the login form. In my specific case, apollo tries to access `http://localhost:49153/apollo/user_interfaces/encryptedlocaldb/login.html` and finds nothing on that port.

Proxies come to mind here:

- if Apollo is proxied via a DNS name that's not known to the system running Apollo
- my use case of docker which does port-remappings, Apollo runs on 8080 internally but could be running on a completely different DNS name + port externally (externally being the URL the user uses to access Apollo)

This seems like a bad behaviour that could be corrected by:

- if Apollo is requesting a URL from itself, only to re-render that for the user, then it should construct those URLs based on the internal address, not data passed by the user.
- Alternatively, read the files off of disk, rather than using web requests.

I'm sure there are reasons behind why it was done this way; I'm just documenting my experiences.

xref http://gmod.827538.n3.nabble.com/WebApollo-500-on-Login-Route-in-container-td4048805.html

**Comment by erasche** [comment]
xref http://gmod.827538.n3.nabble.com/WebApollo-500-on-Login-Route-in-container-td4048805.html

**Comment by nathandunn** [comment]
Thanks @erasche   I didn't write this code originally (just migrated it).   I do think we need to be *very* aware of the DNS proxy issues going forward.  

The URL request to the file-system, I agree, is weird.  Typically it should be a compiled JSP (which would fix the other problems).    

This would be a fairly straight-forward fix if it would help you.  Let me know.

**Comment by erasche** [comment]
This would be incredibly useful for me to have; this issue limits us to one docker containers/one Apollo instance per host. 

(I don't know how much you use docker...) With docker we run 1 service per container. Multiple Apollos in a single container is discouraged in lieu of a single Apollo instance per container, running multiple times on different ports. If a fix can be produced for this, then I can spread Apollo instances across ports, which will be primarily useful for integrating with Galaxy for visualization+annotation of GFF3+blast/bigwig/etc data there.

I'd be happy to make the PR, but I'm afraid I don't even know where to start on this.

**Comment by nathandunn** [comment]
I'll try to make that happen in the next week or 2.

**Comment by erasche** [comment]
Sounds good. Again, if there's anything I can do to help, I'd be happy to, but I'm afraid it's probably outside the scope of my abilities currently.

**Comment by nathandunn** [comment]
It's not a hard fix (I hope).  Sharing any info about docker and integrating stuff into your pipeline would be a significant contribution to the community.  

Nathan

**Comment by erasche** [comment]
Absolutely, will do!

tor. 19. mar. 2015 kl. 17.28 skrev Nathan Dunn <notifications@github.com>:

**Comment by nathandunn** [comment]
@erasche  I merged this into mainline.

**Comment by erasche** [comment]
Thanks @nathandunn !

**Comment by nathandunn** [comment]
@erasche   We'll close it when it goes into 1.0.5.   Thanks.

**Comment by nathandunn** [comment]
@erasche   I take that back :)
