### ISSUE TITLE
ways to implement cross-species links? 

### ISSUE THREAD

**Issue by michaelp896** [GMOD/Apollo#2015]
I want to implement something with our apollo browser and was hoping that someone could point me in the right direction to get started. We have a browser loaded with closely related teleost species. I also have a table with orthologs in each of the species and their genomic locations that I want to use as the basis for a new feature, where I could right-click on an annotation and then be able to click through to orthologous sites in other species.

Any advice/suggestions would be appreciated. 

Thanks!

**Comment by nathandunn** [comment]
Hey, I think this is a great question.  I have a feeling that groups have done this a few different ways and I think its more JBrowse than Apollo related.  I know I've been involved in groups talking about this, but I've never done the implementation myself. 

My suggestion would be to signup for the JBrowse and Apollo mailing lists:
- http://jbrowse.org/contact.html 
- http://genomearchitect.github.io/

and mail it out directly:

- gmod-ajax@lists.sourceforge.net, apollo@lists.lbl.gov
