### ISSUE TITLE
Must java, but I have java

### ISSUE THREAD

**Issue by chibante** [GMOD/Apollo#2016]
Hi guys!

I tried run command `./apollo run-local` in Apollo folder, but this message appeared:`You must install JDK 1.8`, but the Java jdk 1.8 is installed and it is default. (see steps made below)
How can I solve this wrong?
Thanks!

carla@einstein:~/Apollo$ `./apollo run-local`
```
Gradle version: 2
Using system gradle 2.11
Node Version: 11
Npm Version: 6
Yarn Version: 1
javac 1.7.0_171 found
javac installed
You must install JDK 1.8
```

carla@einstein:~/Apollo$ `java -version`
```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-2~14.04-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

carla@einstein:~/Apollo$ `sudo update-alternatives --config java`
``` 
Existem 2 escolhas para a alternativa java (disponibiliza /usr/bin/java).

  Selecção   Caminho                                         Prioridade Estado
------------------------------------------------------------
  0            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      modo automático
  1            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      modo manual
* 2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1069      modo manual

Pressione enter para manter a escolha actual[*], ou digite o número da selecção: 2
```

**Comment by nathandunn** [comment]
To test your changes, open a new window and type:

   javac -version

If you get the correct version of Java than close your old windows and run with your new one.   

The other thing I do (especially since Java 7 is deprecated) is to remove all of your Java 7 installations. 

Hopefully one of those fixes it.

**Comment by chibante** [comment]
Thanks! I remove all java7 and the command `./apollo run-local` continue, but some steps next an error was found (at the end of this comment has all sequence of steps showed on terminal):
```
 | Error Error initializing classpath: No builders are available to build a model of type 'org.grails.gradle.plugin.model.GrailsClasspath'. (Use --stacktrace to see the full trace)
```
I check the status of grails on machine:
carla@einstein:~/Apollo$ `grails -version`
```
| Grails Version: 3.3.9
| JVM Version: 1.8.0_171
```
carla@einstein:~/Apollo$ `echo $GRAILS_HOME`
```
/home/carla/.sdkman/candidates/grails/current
```
**all sequence of steps**

carla@einstein:~/Apollo$ `./apollo run-local 8085`
```
No log file found in classpath.
From https://github.com/gmod/jbrowse
 * tag               1.15.4-release -> FETCH_HEAD
clean-webpack-plugin: /home/carla/Apollo/jbrowse/dist has been removed.
No log file found in classpath.
carla@einstein:~/Apollo$ cat saida.log 
Gradle version: 2
Using system gradle 2.11
Node Version: 11
Npm Version: 6
Yarn Version: 1
javac 1.8.0_171 found
javac installed
JDK 1.8 found: javac 1.8.0_171
Final JBrowse settings [git:[url:https://github.com/gmod/jbrowse, branch:1.15.4-release, alwaysPull:true, alwaysRecheck:true], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
Final plugins [WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]
:installJBrowseWebOnly
JBrowse already exists
Already up-to-date.
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.04s.
yarn install v1.13.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 1.57s.
Installing JBrowse plugins  [WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]
Evaluating plugin WebApollo=[included:true]
Plugin jbrowse/plugins/WebApollo exists and appears valid.
Evaluating plugin RegexSequenceSearch=[included:true]
Plugin jbrowse/plugins/RegexSequenceSearch exists and appears valid.
Evaluating plugin HideTrackLabels=[included:true]
Plugin jbrowse/plugins/HideTrackLabels exists and appears valid.

> @gmod/jbrowse@1.15.4 build /home/carla/Apollo/jbrowse
> webpack

jbrowse-glob-loader: building 203 JBrowse modules
jbrowse-glob-loader: adding plugin module WebApollo/View/TrackList/Hierarchical
jbrowse-glob-loader: adding plugin module WebApollo/View/TrackList/Faceted
jbrowse-glob-loader: adding plugin module WebApollo/View/Track/WebApolloCanvasVariants
jbrowse-glob-loader: adding plugin module WebApollo/View/Track/WebApolloCanvasFeatures
jbrowse-glob-loader: adding plugin module WebApollo/View/Track/WebApolloAlignments2
jbrowse-glob-loader: adding plugin module WebApollo/View/Track/SequenceTrack
jbrowse-glob-loader: adding plugin module WebApollo/View/Track/DraggableResultFeatures
jbrowse-glob-loader: adding plugin module WebApollo/View/Track/DraggableHTMLVariants
jbrowse-glob-loader: adding plugin module WebApollo/View/Track/DraggableHTMLFeatures
jbrowse-glob-loader: adding plugin module WebApollo/View/Track/DraggableBLASTFeatures
jbrowse-glob-loader: adding plugin module WebApollo/View/Track/DraggableAlignments
jbrowse-glob-loader: adding plugin module WebApollo/View/Track/AnnotTrack
jbrowse-glob-loader: adding plugin module WebApollo/View/Track/AnnotSequenceTrack
jbrowse-glob-loader: adding plugin module WebApollo/View/Dialog/Help
jbrowse-glob-loader: adding plugin module WebApollo/TrackConfigTransformer
jbrowse-glob-loader: adding plugin module WebApollo/Store/SeqFeature/ScratchPad
jbrowse-glob-loader: adding plugin module WebApollo/Store/SeqFeature/PseudoNCList
jbrowse-glob-loader: adding plugin module WebApollo/Store/SeqFeature/ApolloGFF3
jbrowse-glob-loader: adding plugin module WebApollo/SequenceSearch
jbrowse-glob-loader: adding plugin module WebApollo/SequenceOntologyUtils
jbrowse-glob-loader: adding plugin module WebApollo/SequenceFeatureDialog
jbrowse-glob-loader: adding plugin module WebApollo/Permission
jbrowse-glob-loader: adding plugin module WebApollo/main
jbrowse-glob-loader: adding plugin module WebApollo/JSONUtils
jbrowse-glob-loader: adding plugin module WebApollo/InformationEditor
jbrowse-glob-loader: adding plugin module WebApollo/FormatUtils
jbrowse-glob-loader: adding plugin module WebApollo/FeatureSelectionManager
jbrowse-glob-loader: adding plugin module WebApollo/FeatureEdgeMatchManager
jbrowse-glob-loader: adding plugin module WebApollo/EUtils
jbrowse-glob-loader: adding plugin module WebApollo/BioFeatureUtils
jbrowse-glob-loader: adding plugin module RegexSequenceSearch/View/SearchSeqDialog
jbrowse-glob-loader: adding plugin module RegexSequenceSearch/Store/SeqFeature/RegexSearch
jbrowse-glob-loader: adding plugin module RegexSequenceSearch/main
jbrowse-glob-loader: adding plugin module NeatHTMLFeatures/View/Track/NeatFeatures
jbrowse-glob-loader: adding plugin module NeatHTMLFeatures/main
jbrowse-glob-loader: adding plugin module NeatCanvasFeatures/View/Track/NeatFeatures
jbrowse-glob-loader: adding plugin module NeatCanvasFeatures/View/FeatureGlyph/Segments
jbrowse-glob-loader: adding plugin module NeatCanvasFeatures/View/FeatureGlyph/ProcessedTranscript
jbrowse-glob-loader: adding plugin module NeatCanvasFeatures/View/FeatureGlyph/Gene
jbrowse-glob-loader: adding plugin module NeatCanvasFeatures/View/FeatureGlyph/Box
jbrowse-glob-loader: adding plugin module NeatCanvasFeatures/main
jbrowse-glob-loader: adding plugin module HideTrackLabels/main
jbrowse-glob-loader: adding plugin module DebugEvents/main
jbrowse-glob-loader: adding plugin module CategoryUrl/main
jbrowse-glob-loader: discovered a total of 247 modules
jbrowse-glob-loader: skipping entry point module JBrowse/main
Hash: cae210c880f002820eae
Version: webpack 3.12.0
Time: 27060ms
                    Asset       Size         Chunks                    Chunk Names
              0.bundle.js    8.16 MB  0, 1, 2, 3, 4  [emitted]  [big]  
              1.bundle.js     456 kB              1  [emitted]  [big]  
              2.bundle.js     145 kB              2  [emitted]         
              3.bundle.js     531 kB              3  [emitted]  [big]  
              4.bundle.js     398 kB              4  [emitted]  [big]  
              5.bundle.js    1.68 kB              5  [emitted]         
              6.bundle.js  920 bytes              6  [emitted]         
    run_jasmine.bundle.js     571 kB              7  [emitted]  [big]  run_jasmine
        browser.bundle.js     364 kB              8  [emitted]  [big]  browser
           main.bundle.js     375 kB              9  [emitted]  [big]  main
          0.bundle.js.map    11.3 MB  0, 1, 2, 3, 4  [emitted]         
          1.bundle.js.map     611 kB              1  [emitted]         
          2.bundle.js.map     200 kB              2  [emitted]         
          3.bundle.js.map     691 kB              3  [emitted]         
          4.bundle.js.map     504 kB              4  [emitted]         
          5.bundle.js.map    1.87 kB              5  [emitted]         
          6.bundle.js.map    1.13 kB              6  [emitted]         
run_jasmine.bundle.js.map     854 kB              7  [emitted]         run_jasmine
    browser.bundle.js.map     517 kB              8  [emitted]         browser
       main.bundle.js.map     537 kB              9  [emitted]         main
 dojo/resources/blank.gif   43 bytes                 [emitted]         
  [46] ./src/JBrowse/Browser.js 142 kB {0} [built]
  [65] ./src/JBrowse/Model/XHRBlob.js 7.2 kB {0} {3} [built]
 [129] ./build/dojo-webpack-plugin-loader/dojo/dojo.js 70.7 kB {7} {8} {9} [built]
 [334] ./src/JBrowse/Util.js 22.3 kB {0} {1} {3} [built]
 [336] ./src/JBrowse/QueryParamConfigMapper.js 6.13 kB {0} {2} [built]
 [337] ./src/JBrowse/standalone.js 140 bytes {0} {8} [built]
 [338] ./src/JBrowse/Model/SimpleFeature.js 2.86 kB {0} {1} [built]
 [340] ./src/JBrowse/View/GranularRectLayout.js 16.8 kB {0} {2} [built]
 [341] ./src/JBrowse/FeatureFiltererMixin.js 3.19 kB {0} [built]
 [342] ./src/JBrowse/View/Track/_AlignmentsMixin.js 15.8 kB {0} [built]
 [343] ./src/JBrowse/Store/SeqFeature/_MismatchesMixin.js 12.6 kB {0} [built]
 [344] ./src/JBrowse/Model/NestedFrequencyTable.js 3.41 kB {0} {1} [built]
 [345] ./src/JBrowse/Store/TabixIndexedFile.js 3.01 kB {0} [built]
 [373] ./src/JBrowse/main.js 13 kB {9} [built]
 [374] ./tests/js_tests/main.js 1.58 kB {7} [built]
    + 1485 hidden modules
:javac
:gwtc

BUILD SUCCESSFUL

Total time: 2 mins 1.738 secs

This build could be faster, please consider using the Gradle Daemon: https://doc| Resolving Dependencies. Please wait...
Downloading https://services.gradle.org/distributions/gradle-2.11-all.zip
.
.
.
.
.
.
.
.
.
.
Unzipping /home/carla/.gradle/wrapper/dists/gradle-2.11-all/ace7yl0a7udokebb27mt9s3qr/gradle-2.11-all.zip to /home/carla/.gradle/wrapper/dists/gradle-2.11-all/ace7yl0a7udokebb27mt9s3qr
Set executable permissions for: /home/carla/.gradle/wrapper/dists/gradle-2.11-all/ace7yl0a7udokebb27mt9s3qr/gradle-2.11/bin/gradle
Final JBrowse settings [git:[url:https://github.com/gmod/jbrowse, branch:1.15.4-release, alwaysPull:true, alwaysRecheck:true], plugins:[WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]]
Final plugins [WebApollo:[included:true], RegexSequenceSearch:[included:true], HideTrackLabels:[included:true]]

BUILD SUCCESSFUL

Total time: 14.51 secs
| Error Error initializing classpath: No builders are available to build a model of type 'org.grails.gradle.plugin.model.GrailsClasspath'. (Use --stacktrace to see the full trace)
```

**Comment by nathandunn** [comment]
You need to install grails 2.5.5 or remove grails entirely (it will then install the correct version locally).

I use https://sdkman.io/  to install globally if I'm doing development.

**Comment by chibante** [comment]
Hi, Nathan!

I installed grails 2.5.5...
carla@einstein:~$ `grails -version`
```
Grails version: 2.5.5
```
And the link `http://localhost:8080/apollo` apparently to be working!
But when scrip running this message is showed:

carla@einstein:~/Apollo$ `./apollo run-local > saida.log`
```
No log file found in classpath.
From https://github.com/gmod/jbrowse
 * tag               1.15.4-release -> FETCH_HEAD
clean-webpack-plugin: /home/carla/Apollo/jbrowse/dist has been removed
```
This directory `/home/carla/Apollo/jbrowse/dist` exit and it has files below:
carla@einstein:~/Apollo/jbrowse/dist$ `ls -liah`
```
total 26M
8789246 drwxrwxr-x  3 carla carla 4,0K Jan 22 18:54 .
8790178 drwxrwxr-x 18 carla carla 4,0K Jan 22 18:54 ..
8789247 -rw-rw-r--  1 carla carla 7,8M Jan 22 18:54 0.bundle.js
8789257 -rw-rw-r--  1 carla carla  11M Jan 22 18:54 0.bundle.js.map
8789248 -rw-rw-r--  1 carla carla 446K Jan 22 18:54 1.bundle.js
8789258 -rw-rw-r--  1 carla carla 597K Jan 22 18:54 1.bundle.js.map
8789249 -rw-rw-r--  1 carla carla 142K Jan 22 18:54 2.bundle.js
8789259 -rw-rw-r--  1 carla carla 196K Jan 22 18:54 2.bundle.js.map
8789250 -rw-rw-r--  1 carla carla 519K Jan 22 18:54 3.bundle.js
8789260 -rw-rw-r--  1 carla carla 676K Jan 22 18:54 3.bundle.js.map
8789251 -rw-rw-r--  1 carla carla 389K Jan 22 18:54 4.bundle.js
8789261 -rw-rw-r--  1 carla carla 492K Jan 22 18:54 4.bundle.js.map
8789252 -rw-rw-r--  1 carla carla 1,7K Jan 22 18:54 5.bundle.js
8789262 -rw-rw-r--  1 carla carla 1,9K Jan 22 18:54 5.bundle.js.map
8789253 -rw-rw-r--  1 carla carla  920 Jan 22 18:54 6.bundle.js
8789263 -rw-rw-r--  1 carla carla 1,2K Jan 22 18:54 6.bundle.js.map
8789255 -rw-rw-r--  1 carla carla 356K Jan 22 18:54 browser.bundle.js
8789265 -rw-rw-r--  1 carla carla 506K Jan 22 18:54 browser.bundle.js.map
8789267 drwxrwxr-x  3 carla carla 4,0K Jan 22 18:54 dojo
8789256 -rw-rw-r--  1 carla carla 366K Jan 22 18:54 main.bundle.js
8789266 -rw-rw-r--  1 carla carla 525K Jan 22 18:54 main.bundle.js.map
8789254 -rw-rw-r--  1 carla carla 558K Jan 22 18:54 run_jasmine.bundle.js
8789264 -rw-rw-r--  1 carla carla 835K Jan 22 18:54 run_jasmine.bundle.js.map
```
Thanks!

**Comment by nathandunn** [comment]
Did it not work (can you connect to <http://localhost:8080/apollo>?   

If it doesn't work run do:

    ./apollo clean-all

    ./apollo run-local

**Comment by chibante** [comment]
Appearance of link: `http://localhost:8080/apollo`
![image](https://user-images.githubusercontent.com/46681974/51566058-c31fdf00-1e7a-11e9-9d49-58bc42964cb4.png)

**Comment by chibante** [comment]
Yes, I will contact the biologists to fill the form with the appropriate information to test after.

Thanks for your help!! ;)

**Comment by chibante** [comment]
Hi, Nathan!

When I make login on Apollo web, the Apollo console return:
```
...
| Server running. Browse to http://localhost:8080/apollo
2019-01-30 15:41:04,895 [http-nio-8080-exec-3] WARN  apollo.PreferenceService  - No user present, so using the client token
2019-01-30 15:41:05,078 [http-nio-8080-exec-2] WARN  apollo.PermissionService  - Failed to authenticate user
| Error 2019-01-30 15:41:51,925 [http-nio-8080-exec-9] ERROR apollo.UserController  - org.bbop.apollo.PermissionException: User does not have permission for any organisms.
| Error 2019-01-30 15:41:52,343 [http-nio-8080-exec-1] ERROR apollo.UserController  - User does not have permission for any organisms.
| Error 2019-01-30 15:41:52,417 [http-nio-8080-exec-5] ERROR apollo.AnnotatorService  - Error: org.bbop.apollo.PermissionException: User does not have permission for any organisms.
```
I tried on Chrome and Firefox. Is this related to browser version, database configuration or or because Apollo was not installed by `sudo`?
Do you have any idea what might be happening?

Thanks!

**Comment by nathandunn** [comment]
It just means you need to add an organism. 

Can you login and add an organism? 

Nathan

**Comment by chibante** [comment]
If I fill the blacks correctly....

![image](https://user-images.githubusercontent.com/46681974/52003812-b0299200-24ac-11e9-86ad-0cc1b0e85d53.png)

....I tried and the Apollo console return:
```
| Error 2019-01-30 16:29:17,587 [http-nio-8080-exec-6] ERROR apollo.OrganismController  - not authorized to add organism
| Error 2019-01-30 16:29:19,362 [http-nio-8080-exec-9] ERROR apollo.UserController  - org.bbop.apollo.PermissionException: User does not have permission for any organisms.
| Error 2019-01-30 16:29:19,704 [http-nio-8080-exec-4] ERROR apollo.UserController  - User does not have permission for any organisms.
| Error 2019-01-30 16:29:19,780 [http-nio-8080-exec-8] ERROR apollo.AnnotatorService  - Error: org.bbop.apollo.PermissionException: User does not have permission for any organisms.
```

**Comment by nathandunn** [comment]
I see . . 

It looks like your user now no longer has admin privileges?   

What do you see if you do this? 

select * from grails_user u join grails_user_roles gur on u.id = gur.user_id join role r on r.id = gur.role_id ;

(Maybe obscure the passwordhash)

-----+---------+------------+-----------+------------------+------------------------------------------------------------------+--------------+---------+---------+----+---------+-------+------
  20 |       6 | Bob        | Jones     |                  | xxx | nathandunn@lbl.gov |      18 |      20 | 18 |       4 | ADMIN |  100
 955 |       3 | Ted        | Smith     | {"creator":"20"} | xxx | a@b.com            |      16 |     955 | 16 |       2 | USER  |   10
(2 rows)



Nathan

**Comment by chibante** [comment]
Hi, Nathan!

    How can I access Apollo schema directly by Postgres?

Thanks!

**Comment by nathandunn** [comment]
Have you checked the Postgres documentation? 

Nathan

**Comment by chibante** [comment]
Yes, but a don't know the name of schema (database) to access:

carla@einstein:~$ `psql postgres`
```
WARNING: password file "/home/carla/.pgpass" has group or world access; permissions should be u=rw (0600) or less
psql (9.3.24)
Type "help" for help.

postgres=# \l
postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 GPDB      | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(4 rows)

postgres=# 
```
Thanks!

**Comment by nathandunn** [comment]
Have you looked through here (sorry, we probably have too much documentation)?   

https://genomearchitect.readthedocs.io/en/latest/PostgreSQLSetup.html?highlight=postgresql

**Comment by chibante** [comment]
I will see the documentation link.
Thanks for your help!

**Comment by nathandunn** [comment]
Sure.  Let me know if anything in there is unclear.

**Comment by chibante** [comment]
I follow the steps:

carla@einstein:~/Apollo$ `sudo su postgres -c "createuser -RDIElPS $PGUSER"`
```
Enter password for new role: 
Enter it again: 
createuser: creation of new role failed: ERROR:  role "postgres" already exists
```
carla@einstein:~/Apollo$ `sudo su postgres -c "createdb -E UTF-8 -O $PGUSER apollo-production"`
```
createdb: database creation failed: ERROR:  role "apollo-production" does not exist
```
I realized that files Annotation...db was generated in Apollo folder:

carla@einstein:~/Apollo$ `ls -liah *.db`
```
8793293 -rw-rw-r-- 1 carla carla 2,1M Jan 31 10:05 AnnotationDatabase:devDb.h2.db
8789268 -rw-rw-r-- 1 carla carla  100 Jan 31 10:05 AnnotationDatabase:devDb.lock.db
8793397 -rw-rw-r-- 1 carla carla  31M Jan 31 12:26 AnnotationDatabase:devDb.trace.db
```
How can I run this: **"select * from grails_user u join grails_user_roles gur on u.id = gur.user_id join role r on r.id = gur.role_id ;"** using the command line to access Postgres database: `psql mydatabase`? (like this https://www.postgresql.org/docs/8.1/tutorial-accessdb.html)

Or exist another way to run this **select** above?

Thanks!

**Comment by chibante** [comment]
Wow, I have a lot of questions now!
So we have to create the database? Is it not created when installing Apollo? So where is my login and password kept?

I'm very grateful!

**Comment by nathandunn** [comment]
If you start reading from here, this should be good:  https://genomearchitect.readthedocs.io/en/latest/Apollo2Build.html#setting-up-the-application

BTW, you don't have to use postgresql.  If you don't provide any postgresql conventions, it will create a database off of file.   The process will be largely the same either way.   However, if you are supporting a large number of users I would suggest using PostgreSQL.

**Comment by chibante** [comment]
Yes, I read this topic! And I did this steps... :)
![image](https://user-images.githubusercontent.com/46681974/52149050-c5d8bc00-2652-11e9-80ff-79bf39bf51c5.png)
But when I tried to add an organism I was denied permission, and I can't do next step:
![image](https://user-images.githubusercontent.com/46681974/52149330-7ba40a80-2653-11e9-9ed0-e0ca1f515ecc.png)
And I have permission to access the directory that I wrote.
I will read again.

Thanks!

**Comment by nathandunn** [comment]
So, a couple of things:
- Your password is correct, otherwise it wouldn't have allowed you to login, so that is fine. 
- based on that screen, it looks like you built with Grails 2.4.4?    That will definitely cause problems. 

Remove grails for your system or set grails to 2.5.5 and run:

    ./apollo clean-all 
    ./apollo run-local # or deploy 

There are a lot of things that can go wrong here using the wrong version of grails.

**Comment by chibante** [comment]
Uhm... I think it may have happened... I tried several times to put an incorrect username and password... Could this have blocked my user? 
Do you know why!? Because as soon as I logged in I did not see this message (see below) and now it's showing up!
```
| Error 2019-02-01 21:27:14,154 [http-nio-8080-exec-5] ERROR apollo.UserController  - org.bbop.apollo.PermissionException: User does not have permission for any organisms.
| Error 2019-02-01 21:27:14,498 [http-nio-8080-exec-7] ERROR apollo.UserController  - User does not have permission for any organisms.
| Error 2019-02-01 21:27:14,676 [http-nio-8080-exec-3] ERROR apollo.AnnotatorService  - Error: org.bbop.apollo.PermissionException: User does not have permission for any organisms.
```
Thanks!

**Comment by nathandunn** [comment]
It won't lock you out ever. 

You'll get that message normally if there are no organisms present.    But you should be able to add one now.   If not, send stack traces and screen shots of everything in the process.

**Comment by chibante** [comment]
Ok!! 
Folow below...

Image of my form:
![image](https://user-images.githubusercontent.com/46681974/52155754-794daa80-266b-11e9-9515-045141649f71.png)

Message generated in Apollo console:
```
| Error 2019-02-01 21:49:37,750 [http-nio-8080-exec-7] ERROR apollo.OrganismController  - not authorized to add organism
| Error 2019-02-01 21:49:39,396 [http-nio-8080-exec-1] ERROR apollo.UserController  - org.bbop.apollo.PermissionException: User does not have permission for any organisms.
| Error 2019-02-01 21:49:39,643 [http-nio-8080-exec-4] ERROR apollo.UserController  - User does not have permission for any organisms.
| Error 2019-02-01 21:49:39,699 [http-nio-8080-exec-5] ERROR apollo.AnnotatorService  - Error: org.bbop.apollo.PermissionException: User does not have permission for any organisms.
```

**Comment by nathandunn** [comment]
2 questions:

1. what happens when you hit "Create Organism"? 
2. What is in the directory you are referencing (1ls /home/carla/_PerlStudy/FASTA`)

**Comment by chibante** [comment]
1. what happens when you hit "Create Organism"?

Follow steps in gif video:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/46681974/52166699-bc555f80-26f7-11e9-9521-d75efc19dd5d.gif)
Error in Apollo console:
```
| Error 2019-02-02 14:23:15,148 [http-nio-8080-exec-7] ERROR apollo.OrganismController  - not authorized to add organism
| Error 2019-02-02 14:23:17,475 [http-nio-8080-exec-6] ERROR apollo.UserController  - org.bbop.apollo.PermissionException: User does not have permission for any organisms.
| Error 2019-02-02 14:23:18,006 [http-nio-8080-exec-7] ERROR apollo.AnnotatorService  - Error: org.bbop.apollo.PermissionException: User does not have permission for any organisms.
| Error 2019-02-02 14:23:18,015 [http-nio-8080-exec-8] ERROR apollo.UserController  - User does not have permission for any organisms.
```

2. What is in the directory you are referencing (1ls /home/carla/_PerlStudy/FASTA`)

Some `*.fasta` files.

**Comment by nathandunn** [comment]
1. This could be a problem here, but I doubt it is.  I think you're just getting a false error.  What version of the software are you running?

2. One of these days I'll have it work by just pointing to FASTA files, but not today ;)

You need to run this here to make it JBrowse readable:

https://genomearchitect.readthedocs.io/en/latest/Data_loading.html?highlight=prepare-ref#prepare-refseqs-pl

(also here)
https://jbrowse.org/docs/tutorial_classic.html 

If you look in the JBrowse sample directory after running setup it should look like that. 

You can run the binary out of JBrowse https://jbrowse.org/docs/installation.html or from within Apollo if its built via master.

**Comment by chibante** [comment]
Hi, Nathan!

1....What version of the software are you running?
I followed this link to install: `https://genomearchitect.readthedocs.io/en/latest/Apollo2Build.html#setting-up-the-application` ...I checked the `application.properties` file (version 2.2.0):
![image](https://user-images.githubusercontent.com/46681974/52185360-07f62f00-2806-11e9-899d-53632d9aada5.png)

2....You need to run this here to make it JBrowse readable...
Yes I did and generate this directory:
carla@einstein:~$ `perl ~/Apollo/jbrowse/bin/prepare-refseqs.pl --fasta /home/carla/_PerlStudy/FASTA/*.fasta --out ~/Apollo/data`

![image](https://user-images.githubusercontent.com/46681974/52213014-04e65780-2875-11e9-89c7-42336007b0d6.png)
![image](https://user-images.githubusercontent.com/46681974/52212852-9d300c80-2874-11e9-9c13-e2304d3b58ae.png)

And the same messagens happened:
![ezgif com-video-folder](https://user-images.githubusercontent.com/46681974/52219763-6c57d380-2884-11e9-8f2e-0f6d72e4afef.gif)
```
| Error 2019-02-04 13:44:45,174 [http-nio-8080-exec-8] ERROR apollo.OrganismController  - not authorized to add organism
| Error 2019-02-04 13:44:46,862 [http-nio-8080-exec-4] ERROR apollo.UserController  - org.bbop.apollo.PermissionException: User does not have permission for any organisms.
| Error 2019-02-04 13:44:47,224 [http-nio-8080-exec-1] ERROR apollo.UserController  - User does not have permission for any organisms.
| Error 2019-02-04 13:44:47,291 [http-nio-8080-exec-7] ERROR apollo.AnnotatorService  - Error: org.bbop.apollo.PermissionException: User does not have permission for any organisms.
```
### To test:
Additionally I installed the Apollo Docker (`sudo docker run -it -p 8888:8080 quay.io/gmod/docker-apollo:2.2.0`) the same version (2.2.0) according `https://github.com/GMOD/docker-apollo`  and obtained the message below to create organism:
```
2019-02-04 01:40:44,424 [http-nio-8080-exec-10] ERROR apollo.OrganismController  - problem saving organism: java.lang.Exception: Invalid directory specified: /data/yeast
2019-02-04 01:40:45,431 [http-nio-8080-exec-6] ERROR apollo.UserController  - org.bbop.apollo.PermissionException: User does not have permission for any organisms.
2019-02-04 01:40:45,637 [http-nio-8080-exec-3] ERROR apollo.UserController  - User does not have permission for any organisms.
2019-02-04 01:40:45,646 [http-nio-8080-exec-9] ERROR apollo.AnnotatorService  - Error: org.bbop.apollo.PermissionException: User does not have permission for any organisms.
```

**Comment by nathandunn** [comment]
I can't see anything obvious.    With docker you would do:

    docker run -it -p 8888:8080 -v /home/chibante/Apollo/data:/data  quay.io/gmod/docker-apollo:2.2.0

And then you would add the organism in the directory `/data`

I'll update the instructions to reflect this. 

Let me know if this works or not.

**Comment by chibante** [comment]
Hi, Nathan!!!

This worked out!!
The message that appeared was not directly related to the real problem. You was right! ;)

![image](https://user-images.githubusercontent.com/46681974/52355173-fd5fb380-2a18-11e9-823e-1dfa0274b439.png)

I had been able to include fictitious organisms names with real sequences but their bases (letters TCGA) do not appear on JBrowse (on the left side of the screen) and they have Annotations = 0 (on the right side of the screen)
![image](https://user-images.githubusercontent.com/46681974/52354319-54648900-2a17-11e9-9449-c233f0e5fdb5.png)

What can I do to see this bases on JBrowser?

Very grateful!! :)

**Comment by nathandunn** [comment]
To see the basis you have to zoom in all the way.  That is by design.    

You have to drag up evidence into the annotation section.  The user's guide is here:

http://genomearchitect.github.io/users-guide/

![image](https://user-images.githubusercontent.com/751274/52357081-549a5f80-29ea-11e9-9e7e-fdf8c5c773ec.png)

**Comment by chibante** [comment]
Yes!!!

![image](https://user-images.githubusercontent.com/46681974/52359869-e40f3500-2a21-11e9-8d1a-9db1854794aa.png)

Now I need to learn to use!

Very grateful for your help!!! :)

**Comment by nathandunn** [comment]
No problem.  Thanks for keeping at it.

**Comment by chibante** [comment]
Oh!!
Just to make it clear that the Apollo version that worked was Apollo 2.2.0 from Docker, because the user `admin@local.host` was already` admin` (https://github.com/GMOD/docker-apollo). 

![image](https://user-images.githubusercontent.com/46681974/52367142-859e8280-2a32-11e9-8cc1-831308c247b0.png)

The version 2.2.0 that I installed manually didn't work correctly. I could't get up the level of my user created at the time of the first login (below) to `admin`:

![image](https://user-images.githubusercontent.com/46681974/52366340-a49c1500-2a30-11e9-8b7d-c6e73d0172aa.png)
(source: https://genomearchitect.readthedocs.io/en/latest/Apollo2Build.html#login-to-the-web-interface)

Thanks for help!! :)
