### ISSUE TITLE
Reset password of admin from Apollo web

### ISSUE THREAD

**Issue by chibante** [GMOD/Apollo#2022]
Hi, guys!

I forgot the main password from Apollo web installed on desktop. I found this a suggestion `http://gmod.827538.n3.nabble.com/reset-first-admin-account-td4050097.html` to solve this:
```
If you’ve not added any organisms you can drop your database and re-create it.

If you have organisms (or other data you don’t want to lose), but you only have the one user, you can delete your use table (“delete from grails_user”) ;

You can also use the “add_user.groovy” script (docs/web_services/examples/groovy/) to add an admin user and change it back.

Nathan 
```
In my case I can drop my database and re-create, but I search for Apollo database and I can't see:

```
postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 GPDB      | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(4 rows)
```
How can I made this?

Thanks!

**Comment by nathandunn** [comment]
What commands did you use to drop and create it?

**Comment by chibante** [comment]
Hi, Nathan!

To remove database: `DROP DATABASE database_name`
To create database: `CREATE DATABASE database_name`
But I don't known the **user** and  the **database name** of Apollo database on Postgres.

...Or I can delete the table grails_user (“delete from grails_user”), anyway I need to know the name of database

Thanks!

**Comment by nathandunn** [comment]
Hey, would you mind posting this question to the mailing list?  I think it would be more to folks there. 

I will answer it there. 

Thanks,

Nathan

**Comment by nathandunn** [comment]
Hilarious .. glad it worked out 

Nathan
