### ISSUE TITLE
allow upload of FASTA file directly to create a new genome

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2023]
Allow the uploading of a FASTA file to create a new genome based on existing web services

**Comment by nathandunn** [comment]
![image](https://user-images.githubusercontent.com/751274/52087426-4d90ce80-255e-11e9-969b-4e576478fccd.png)

![image](https://user-images.githubusercontent.com/751274/52087443-5681a000-255e-11e9-8f01-9902cda8cc18.png)

**Comment by changjun-210095** [comment]
why I lord down JBrowse-1.16.4.zip, and when i open the files, but no tutorial files inJBrowse-1.16.3-desktop-win32-x64\resources\app\docsin? I appreciate you for the method to solve the problem.

**Comment by nathandunn** [comment]
Are you trying to get Apollo or JBrowse running? 

We provide some sample data here: https://genomearchitect.readthedocs.io/en/latest/Apollo2Build.html?highlight=yeast#adding-sample-data <https://genomearchitect.readthedocs.io/en/latest/Apollo2Build.html?highlight=yeast#adding-sample-data>

You can use any JBrowse data for Apollo. 


JBrowse problems can be addressed here: http://jbrowse.org/contact.html <http://jbrowse.org/contact.html>. 

Nathan
