### ISSUE TITLE
RemoteUser does not currently auto-add users to tracks

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#203]
Building upon the original PR I opened in #60, we use `REMOTE_USER` authentication because we'd rather offload authentication to our university. One of the major joys of it is not managing a user list, and having people automatically added to services on first login (c.f. gitlab/mediawikis which both auto-create users with default permissions).

I'd like to add a configurable option to support automatically creating the users (and setting default permissions). the easiest place to do that looks to be in `RemoteUserAuthentication.java`: https://github.com/GMOD/Apollo/blob/master/src/main/java/org/bbop/apollo/web/user/remoteuser/RemoteUserAuthentication.java#L48

That function looks to be called once, on login, in Login.java (and not on every request), so I imagine that I could add an `if (username == null){ ... }else { addUser() }` call of some sort, but I'm not sure how best to go about this. 

This is a bit specific to authentication types like RemoteUser/BrowserID/OAuth;  it's sort of the analogue for a "register" function for authentication methods which delegate authentication upstream. I would have imagined that Oauth/BrowserID auto-create read-only users but they don't seem to do that either.

Any suggestions or comments here?

**Comment by nathandunn** [comment]
I *think* I would edit the RemoteUserAuthentication.java class and quite probably the ServerConfiguration (and thus config.xml).   

I think what you are wanting is for it to automatically submit the JSON if it is not there locally if configured to auto_add, then just copy the JSON post from addUser.jsp.

**Comment by cmdcolin** [comment]
I think this is a good observation.  I had noted where even the BrowserId login requires you to have been added to the user list manually but didn't really have a plan to fix it, but it seems fairly reasonable to allow some users to be added automatically.

**Comment by erasche** [comment]
@nathandunn I considered doing that (and please forgive me if I'm misunderstanding your suggestion), but the JSON post for addUser requires it be posted from a session that's permitted to manage users. Unregistered users won't have that permission, and I figured the POST would be useless, I further figured the server wouldn't be able to submit some kind of "privileged" request to itself for managing users as that might get back into things like #201 if I'm trying to figure out how to get Apollo to talk to itself over HTTP.
My next guess was instantiating UserManager/accessing UserManagerService somehow, and thus my lack of familiarity with the codebase led to this question/issue :)

We'll want this feature, so I plan to implement it with:

- optional auto-registration for OAuth/BrowserID/RemoteUser
- configurable permissions for added users
- whitelisting of auto-reg for
  - email
  - domains? 
  - @cmdcolin is there another method you can envision people would want for whitelisting?

Any other features y'all want to add to the above list?

**Comment by nathandunn** [comment]
You’re right, not sure why I would do a post if you already have access to the API.   I would use:

UserManager.getInstance().addUser() in the RemoteAuthentiation method to add it locally.   

Nathan

**Comment by erasche** [comment]
- auto-creation of users implemented
- debugging issues with auto-track-permissions now.
- need to add unit tests for permissions code

Initial work here: https://github.com/erasche/Apollo/commit/6fc2e0f0c3e05525a0e9481a45329de6273c5baa in case anyone has comments/opinions on it. I plan to re-write the history to remove unnecessary changes/whitespace removal before making the PR.

Automatic user creation (for auth plugins which implement it):

```xml
<user>
  ...
  <authentication_class>org.bbop.apollo.web.user.remoteuser.RemoteUser</authentication_class>
  <auto_add_users>true</auto_add_users>
</user>
```

Automatic (per)track permission grants:

```xml
<default_permissions>
  <auto_grant>
    <users>
      <user>username@fqdn.edu</user>
      <user>username2@fqdn.edu</user>
    </users>
    <domains>
      <domain>university.edu</domain>
    </domains>
    <read />
    <publish />
  </auto_grant>
</default_permissions>
```

I tried to follow the example of the rest of `config.xml` and avoided using xml properties where possible.

**Comment by erasche** [comment]
@nathandunn @cmdcolin any feedback on this PR?

**Comment by nathandunn** [comment]
I think it looks good.  I really like the fact that you included domains for track permissions.   I think it can probably come directly into the 1.0 version.  Version 2.0 is going to be fairly different, but may borrow some of these concepts.  
Any thoughts @cmdcolin ?

**Comment by cmdcolin** [comment]
Merged #204 so this can be tested when ready. I tested browser id which had a small quirk of having to press the sign in button twice the first time you login

**Comment by monicacecilia** [comment]
Dear @cmdcolin, could you please confirm once again that PR #204 is working as expected? If so, we can close this issue. Thank you in advance!

**Comment by cmdcolin** [comment]
This isn't working yet actually. It needs a small fix

I noted in #204 after merging it that we found issues with it. The particular bug is prevents the user permissions dialog popping up

Probably a quick fix

**Comment by nathandunn** [comment]
Alright . . this only relates to 1.0.5 though, right?

**Comment by cmdcolin** [comment]
Yes

**Comment by erasche** [comment]
Sorry, I never got around to writing that fix!

**Comment by monicacecilia** [comment]
Ok. -- if there is still interest on that fix, please be sure to send the PR.

**Comment by erasche** [comment]
We've moved to WA2.0 completely (and were the only ones who used/needed REMOTE_USER so closing this ancient bug.)

**Comment by nathandunn** [comment]
:+1:

**Comment by monicacecilia** [comment]
:+1:
