### ISSUE TITLE
User-created features taken from split reads shoud create features with introns 

### ISSUE THREAD

**Issue by robsyme** [GMOD/Apollo#2036]
Following on from #2034, it would be hugely helpful if split reads would create features with introns.

Ideally, dragging a read spanning an (implied) intron to the User-created annotations track would create a new annotation (or add CDS features to an existing annotation) that did not include the gapped bases.

This is an example of the undesired behaviour as of 5a3cde3ee1232833c333186cbc0d7f997716e64a:

![webapollo-bug-report-2019-02-07_16 37 01](https://user-images.githubusercontent.com/31576/52446453-12614300-2afc-11e9-9607-00be8deb0181.gif)

**Comment by nathandunn** [comment]
I **think** this might be related to #1788  - but need to investigate further

**Comment by nathandunn** [comment]
closing in favor of #1788
