### ISSUE TITLE
strange NeatHTMLFeatures track rendering

### ISSUE THREAD

**Issue by trstickland** [GMOD/Apollo#2039]
I am seeing strange rendering of introns with apollo 2.3.0, which may be related to making NeatHTMLFeatures the new default.  A quick screen grab...

![screengrab of track rendering](https://user-images.githubusercontent.com/33544033/52574254-cc65f100-2e13-11e9-8a11-b16e663d83dd.png)

So the intron "hats" are there, but there's also the grey background with the blue arrows.  Does this indicate that the styling of NeatHTMLFeatures _and_ another styling (HTMLFeatures???) are applied?

We have the NeatHTMLFeatures plugin included in the apollo.groovy config file, but there's no track type config in the track config (trackList.json).   This is the same configuration that we were using with apollo 2.1.0 & jbrowse 1.12.5, which rendered introns as expected with (only) the "hats".

FWIW, I saw this previously with apollo 2.2.0, when explicitly setting NeatHTMLFeatures in the track type config in trackList.json files.   Removing the track type config (i.e. reverting to the default) resulted in the "grey with blue arrow" styling -- I wasn't sure if this was right, but the 2.30 release appeared before I could figure it out.

I also tried the latest master branch version (at time of writing, d36d5be) which behaves the same.

**Comment by nathandunn** [comment]
@trstickland  Its generally because the JBrowse CSS changes require a slight change in the definitions. 

Can you post the CSS for those transcript and I can suggest how to fix them?  

I'll try to update docs and make an announcement to help others with that. 

Basically, you'll want to remove a lot of the external styling.  I removed this (which was needed before):

        "style" : {
            "className" : "feature"
         },

And it worked for me.

**Comment by nathandunn** [comment]
@trstickland Were you able to confirm that this works?

**Comment by trstickland** [comment]
@nathandunn Sorry, I've been working on other things today, will have a go tomorrow hopefully.

**Comment by trstickland** [comment]
That's it -- just removing that in the `trackList.json` file fixes it.  

Thanks for pointing me in this direction:  I would never have spotted this, as that particular configuration hasn't changed since our previous build in which the rendering was fine :-/

**Comment by nathandunn** [comment]
Awesome.  I'll make a brief announcement.
