### ISSUE TITLE
Maintain CIGAR information when updating annotations

### ISSUE THREAD

**Issue by robsyme** [GMOD/Apollo#2052]
When dragging evidence that contains intron junctions to an existing annotation, the CIGAR information is not preserved. This requires an extension of the work done in #1788. An example of the behaviour is shown below: 

![webapollo-bug-report-2019-02-14_15 58 49](https://user-images.githubusercontent.com/31576/52885286-b0798c80-313e-11e9-8556-25a0790f9b9f.gif)

**Comment by nathandunn** [comment]
Awesome @robsyme   ! 

Ill get this in to get tested for 2.3.1 RC2   

Is it ready to go?

**Comment by robsyme** [comment]
I've only checked this by dragging evidence from BAM tracks. Just to be safe, I'll test it from ordinary features (gff, etc) and make sure nothing strange happens. 

I don't think it's related, but I'm also seeing a bug where adding four or more reads was causing problems (hanging the browser). I'll see if I can get to the bottom of that at the same time.

**Comment by robsyme** [comment]
I think this PR is good to go. Haven't quite sorted out the multiple-read problem, but that problem exists in commits before this one. Feel free to merge this and I'll give the other bug some thought tomorrow.

**Comment by robsyme** [comment]
I think that this is all done now, with #2053 and #2054. Thanks Nathan!

**Comment by nathandunn** [comment]
Thank you for your fix and pointing it out.    Cheers!
