### ISSUE TITLE
Ontology Attributes from my gff3 file disappear using add_transcripts_from_gff3_to_annotations.pl script

### ISSUE THREAD

**Issue by Juke34** [GMOD/Apollo#206]
Hello everyone,
Using the script "add_transcripts_from_gff3_to_annotations.pl" my Ontology attributes are not kept. Indeed when I'm looking "Edit information" nothing appear (except for other attributes as _AED=0.05).

my original feature is like that:
	maker   mRNA    852190  872265  507     -	.	ID=maker-scaffold_0-exonerate_protein2genome-gene-8.12-mRNA-1;Parent=maker-scaffold_0-exonerate_protein2genome-gene-8.12;Name=maker-scaffold_0-exonerate_protein2genome-gene-8.12-mRNA-1;_AED=0.05;_eAED=0.05;_QI=0|0|0|1|0|0|4|0|168;Ontology_term=GO%3A0046703

If I modify Ontology_term=GO%3A0046703 by something like _Ontology_term=GO%3A0046703 it will then appear in the "Attributes" field but still noting in the "Gene Ontology IDs" field of the "Edit information" window.

Coming back to the normal Ontology attribute: Ontology_term=GO%3A0046703
The strange thing is, if I add a Dbxref attribute (e.i: Dbxref=EMBL%3AAA816246) the script will then works out.  Indeed, I will have the Dbxref in the "DBXRefs" field and now my Ontology attribute in the "Gene Ontology IDs" field. 
So, as I don't have any "Dbxref" in my gff3 file, the Ontology information is not saved when I'm using the "add_transcripts_from_gff3_to_annotations.pl" script. But in theory it should be possible to kept the Ontology information without DBxref information, isn't it ?

By the way, Is there an explanation why when we drag-and-drop a gene from a track to the "User-created Annotation" none of the attributes are kept ?

Thank you very much for your help.

**Comment by cmdcolin** [comment]
The GO ontology term will only be loaded from and saved to the DBXRef field so in this case you are correct in your assessment of that issue. Does it need to be customized for your case to allow other fields to be loaded?

>Is there an explanation why when we drag-and-drop a gene from a track to the "User-created Annotation" none of the attributes are kept ?

That's an important issue that needs fixing. Cross reference https://github.com/GMOD/Apollo/issues/52

**Comment by monicacecilia** [comment]
@Juke34, as you have noted, - and as @cmdcolin has explained before - at this time we do not support saving metadata from the evidence tracks into the new User-created Annotations. We have taken notice of the request, from you and other users, and are now looking into it. 

Additional commentary on this is available from #52 as noted before. I previously commented: "Until now Apollo has not imported any metadata to the newly created models, as these are assumed to be updated versions of an existent model / feature from evidence tracks. The assumption has been that a newly-created model is being edited to replace the current one, in which case all metadata are entrusted to the annotator curating the model." We are now aware of scenarios in which retaining this information would be useful and are certain that enabling an option to preserve it will be an enhancement to our tool. 

@nathandunn something more to consider: (from my Trello comments)

For some of our collaborators, (e.g. Mark Yandell's Lab), the option to preserve attributes from the predicted gene into the annotations that users drag to the User-created Annotations area would be useful. Perhaps most useful when splitting / merging genes and fixing erroneous splice sites. Although those changes would affect the quality index and AED attributes, it is unlikely to change the Pfam domain info or homology to swiss-prot; that's the reason why they would like to preserve the information.

In my opinion, if implemented as an option, the conflict will come when you merge two genes with separate metadata on the Information Editor boxes; then you must be careful about which one to choose. That is, we need to create specific rules about which metadata are conserved.

On the subject, @cmdcolin had shared an idea in the past: to create a "prompt to import metadata might be nice. Arbitrary fields imported from the features would go in the "Attributes" section of the Information editor, while Pubmed ids, GO terms, and Dbxrefs would all come from the Dbxrefs attribute of the GFF (they would have to be separated out)."

**Comment by cmdcolin** [comment]
I think since we have a cross referenced issue this can be closed.

**Comment by nathandunn** [comment]
Closing as [cross-referenced here](https://github.com/GMOD/Apollo/issues/52)
