### ISSUE TITLE
Ambiguous method overloading for method java.lang.Integer#div

### ISSUE THREAD

**Issue by mictadlo** [GMOD/Apollo#2065]
Hi, 
I have got the below error:
 
> Ambiguous method overloading for method java.lang.Integer#div. Cannot resolve which method to invoke for [null] due to overlapping prototypes between: [class java.lang.Character] [class java.lang.Number]

after I clicked `create a new annotation -> gene`.

What could cause it?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
Could you provide a screen shot of the gene and view the details of the underlying sequence (and/or maybe any raw GFF)? 

Typically I see this from bad evidence input. 

Nathan

**Comment by mictadlo** [comment]
This happens with the below gene:
![screen shot 2019-02-21 at 3 49 44 pm](https://user-images.githubusercontent.com/588297/53204620-c7a50680-3677-11e9-9b44-784b7fbbdbd8.png)

I have just sent you an email with the gff3 file.

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
It requires a shared point login. 

Can you “View details” on it? 

If its small enough <1 GB you can just email directly (nathandunn@lbl.gov <mailto:nathandunn@lbl.gov>) or send it via a free large file share program like drop-box or https://wetransfer.com/ <https://wetransfer.com/>. 




Nathan

**Comment by mictadlo** [comment]
I have just sent you another email.

**Comment by nathandunn** [comment]
@mictadlo  got it.  If I can get to it by tomorrow I will . . otherwise early next week.

**Comment by nathandunn** [comment]
@mictadlo Not seeing anything obvious . . . can you send me your entire jbrowse directory?  

I'm thinking that it might be related to #2063 

Thanks.

**Comment by abretaud** [comment]
I think this is fixed by https://github.com/GMOD/Apollo/pull/2068, I had this problem because apollo didn't detect that the genome was indexed with the new faidx method

**Comment by nathandunn** [comment]
@mictadlo  Can you retest against master and see if this is still a problem for you?

**Comment by mictadlo** [comment]
Thank you it works.

**Comment by nathandunn** [comment]
:+1 @abretaud
