### ISSUE TITLE
Difference beween primary data and subfeatures

### ISSUE THREAD

**Issue by mictadlo** [GMOD/Apollo#2067]
Hi,
I noticed that when clicking on a gene I get two of the same sequences.

![screen shot 2019-02-22 at 8 54 24 am](https://user-images.githubusercontent.com/588297/53208100-566a5100-3681-11e9-8fcf-bde20698fe01.png)
![screen shot 2019-02-22 at 8 54 46 am](https://user-images.githubusercontent.com/588297/53208108-5e29f580-3681-11e9-95df-ce3255fa14f1.png)

What is the difference between primary data and subfeatures?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
@mictadlo  Subfeatures would be exons, CDS (if you have them), etc.

**Comment by nathandunn** [comment]
This isn't really a bug, so I'm going to close this.    

Some of this might be better done, via the mailing list:

http://genomearchitect.org/

**Comment by nathandunn** [comment]
Though, I think this is more of a JBrowse question (http://jbrowse.org/contact.html). 

Short answer is that I'm pretty sure this is the genomic sequence (not the cDNA), so its dictated by the overlapping positions for the region and not the sequence content, at least for "Region Sequence".
