### ISSUE TITLE
BigWig file caused: An error was encountered when displaying this track

### ISSUE THREAD

**Issue by mictadlo** [GMOD/Apollo#2072]
Hi,
I loaded BigWig files in the following way:

```
~/Apollo/jbrowse/bin$ perl add-bw-track.pl --bw_url /data/apollo/DT_Wlp1.bw --label simulated_bw --key "DT_Wlp1.bw" --in /data/apollo/trackList.json
```
Which caused the following problem:
![screen shot 2019-02-26 at 12 22 10 pm](https://user-images.githubusercontent.com/588297/53382885-66579d00-39c1-11e9-95f5-a83e912ddff2.png)

What did I miss?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
This is more of a JBrowse question.    It looks like you looked here: 

https://genomearchitect.readthedocs.io/en/latest/Data_loading.html#add-bw-track-pl

Also here would be good:

http://gmod.org/wiki/JBrowse_FAQ#How_do_I_set_up_a_BigWig_file.3F

and here: 

http://jbrowse.org/docs/bigwig.html

I would post this question with relevant javascript network, console errors, the `trackList.json`, and directory structure to the [JBrowse mailing list](http://jbrowse.org/contact.html) gmod-ajax@lists.sourceforge.net

They are all very responsive.
