### ISSUE TITLE
allow upload of BLAT to path

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2082]

**Comment by abretaud** [comment]
Hi Nathan!
I'm working on https://github.com/galaxy-genome-annotation/python-apollo/pull/2 to allow uploading orgs/tracks from python-apollo
I'd love to be able to upload the 2bit index using the addOrganismWithSequence api, is this what this issue is talking about?

**Comment by nathandunn** [comment]
Yep.  I can bump it up the todo list if that is helpful.

**Comment by abretaud** [comment]
Hum that would be very nice, on the other end I won't need it until the end of month, so no big hurry :)

**Comment by abretaud** [comment]
Thanks @nathandunn for working on this!
I've just tested #2209, but it's not working in a specific case I'd like to use: currently the new `searchDatabaseData` parameter is only used if using also the `sequenceData` param. Would it be possible to make it also work when using `organismData` instead of `sequenceData`?

**Comment by nathandunn** [comment]
Sure.   Do you have a sample piece of data and the call you want to perform? 

That will make me make it quicker. 

Nathan

**Comment by abretaud** [comment]
So I've uploaded sample files to https://we.tl/t-soM97WLQN7
And I use it by doing a call to /organism/addOrganismWithSequence with these params:
- species: foo
- genus: bar
- commonName: foobar
- organismData: the data_archive_merlin.tar.gz file containing a minimal jbrowse data dir
- searchDatabaseData: the merlin.2bit file

For now the result is that the organism is created, but the searchDatabaseData param is ignored
Tell me if you need any other info

**Comment by nathandunn** [comment]
@abretaud   I didn't test this directly, but I see what the problem is.  

If you use organismData, then searchDatabaseData doesn't get read (only if you add everything separately) 

However, if you add a directory to your zip file called `searchDatabaseData` and add your 2bit file in there, it should work.  That being said, I haven't tested this explicitly, as I wanted your curl file.  

I just added this functionality in https://github.com/GMOD/Apollo/pull/2218 and updated the doc to reflect this.
