### ISSUE TITLE
Indels in long RNAseq reads interpreted as introns when used to make annotations.

### ISSUE THREAD

**Issue by fayerodgers** [GMOD/Apollo#2085]
When making a gene model from a full length RNASeq read, indels seem to be being interpreted as introns. Eg, when making annotations from the top two reads here:

![screen shot 2019-03-01 at 10 16 25](https://user-images.githubusercontent.com/20802386/53631761-2d126d80-3c0b-11e9-9d28-d3522f7536b7.png)

This is on the master branch from 19th Feb (2.3.1-snapshot). 

Thanks!

**Comment by nathandunn** [comment]
@fayerodgers  I may have fixed this already (unsure).  Could you retry against master (should be 2.4.0-snapshot)? 

If not, would it be possible to provide BAM data and/or a JBrowse directory at least with the relevant read track and sequences to speed up the fix?

Thanks,

**Comment by fayerodgers** [comment]
Cheers, will retry with master and let you know!

**Comment by fayerodgers** [comment]
So it looks like with the current master I can't make any genes from RNAseq reads at all (though making pseudogenes and ncRNAs from them seems to work). I've copied an example jbrowse directory here for you: ftp://ftp.ebi.ac.uk/pub/databases/wormbase/STAFF/fr7/t_muris_jbrowse/ 
(both of the BAMs in the BAM directory should illustrate the problem).
Cheers

**Comment by nathandunn** [comment]
@fayerodgers  Okay.  I will take a look.

**Comment by nathandunn** [comment]
- [ ] fix creation of cigar features (should use generateSubFeaturesFromCigar in JSONUtils)
- [ ] render indels properly

**Comment by nathandunn** [comment]
The problem is that https://github.com/GMOD/Apollo/blob/master/client/apollo/js/JSONUtils.js#L276 fails because the test_feature has no type. 

https://github.com/GMOD/Apollo/blob/master/client/apollo/js/JSONUtils.js#L215 needs to be called from DraggableHTMLFeatures

**Comment by nathandunn** [comment]
@fayerodgers  

You should be able to use master to add genes now. 

Can you give me the location and what you expect to see (if it is not working the way you want still). 

We changed some things to fix this behavior in #1788.  As such, we created an exon for each match when you drag it up (as opposed to a single large exon).

**Comment by nathandunn** [comment]
Sorry @fayerodgers I’m being dense.  I’ll see if I can’t come up with a fix that preserves the exon over the indels.

**Comment by nathandunn** [comment]
@fayerodgers  this should be working on master now.  Let me know if you run into any problems with it (or expect different behavior).

**Comment by fayerodgers** [comment]
That's fixed it, thanks very much for the speedy response!
