### ISSUE TITLE
drag and drop seems not to work

### ISSUE THREAD

**Issue by mictadlo** [GMOD/Apollo#2087]
Hi,
In this [video](https://youtu.be/9CZjT0RYTxA?t=25) it was shown that it is possible to drag and drop a gene into the yellow bar. Unfortunately, I am not able to reproduce it.

I loaded the data in the following way to Apollo:
```
perl /home/ubuntu/Apollo/jbrowse/bin/prepare-refseqs.pl --fasta /efs/apollo/NbV1ChF.fasta --out /efs/apollo/
perl /home/ubuntu/Apollo/jbrowse/bin/prepare-refseqs.pl --indexed_fasta /efs/apollo/NbV1ChF.fasta --out /efs/apollo/
perl /home/ubuntu/Apollo/jbrowse/bin/flatfile-to-json.pl --gff /efs/apollo/Gmp_NbV1_Final.gff3 --compress --trackType CanvasFeatures --trackLabel "NbanotFeb2019" --out /efs/apollo/

perl /home/ubuntu/Apollo/jbrowse/bin/add-bw-track.pl --bw_url Wlp1_Feb2019.bw --plot --label "Wlp1_Feb2019.bw" --in trackList.json
perl /home/ubuntu/Apollo/jbrowse/bin/add-bam-track.pl --bam_url NbRNASeq_Wlp.sorted.bam  --label NbRNASeq_Whole_Plant_Feb2019 --key "NbRNASeq_Whole_Plant_Feb2019" -i /efs/apollo/trackList.json
```

What did I miss?

Thank you in advance. 
 
Michal

**Comment by nathandunn** [comment]
@mictadlo  

Drag and drop is only for `HTMLFeatures` (otherwise you have to do a right-click).   You want this command instead:

    perl /home/ubuntu/Apollo/jbrowse/bin/flatfile-to-json.pl --gff /efs/apollo/Gmp_NbV1_Final.gff3 --compress --trackType HTMLFeatures --trackLabel "NbanotFeb2019v2" --out /efs/apollo/

Cheers.

**Comment by mictadlo** [comment]
Thank you it works, but it does not show anymore the introns and I am not able to drag and drop the reads from a bam file.
 
![screen shot 2019-03-06 at 7 48 58 am](https://user-images.githubusercontent.com/588297/53839927-7d5f4600-3fe4-11e9-9485-595d7068404f.png)

What did I miss?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
Can you post your tracklist.conf file?

**Comment by mictadlo** [comment]
Please find attached the trackList.json
[trackList.json.txt](https://github.com/GMOD/Apollo/files/2933332/trackList.json.txt)

**Comment by nathandunn** [comment]
Make alignments2 alignments for any bam track you want to be draggable. 

Nathan

**Comment by mictadlo** [comment]
Could please give me an example because I could not understand your last comment?

**Comment by nathandunn** [comment]
e.g.

`  {
         "key" : "NbAllMerged_BAM_Feb2019",
         "label" : "NbAllMerged_BAM_Feb2019",
         "storeClass" : "JBrowse/Store/SeqFeature/BAM",
         "type" : "JBrowse/View/Track/Alignments2",
         "urlTemplate" : "NbRNASeq_AllS.sorted.bam"
      },
`

type should be `         "type" : "JBrowse/View/Track/Alignments",`:

`
  {
         "key" : "NbAllMerged_BAM_Feb2019",
         "label" : "NbAllMerged_BAM_Feb2019",
         "storeClass" : "JBrowse/Store/SeqFeature/BAM",
         "type" : "JBrowse/View/Track/Alignments",
         "urlTemplate" : "NbRNASeq_AllS.sorted.bam"
      },
`

**Comment by mictadlo** [comment]
Thank you it works, but why I had `Alignments2` in my `trackList.json` and how can I avoid this again?

How to display also the introns?
 
![screen shot 2019-03-06 at 7 48 58 am](https://user-images.githubusercontent.com/588297/53839927-7d5f4600-3fe4-11e9-9485-595d7068404f.png)

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
I think you're going to get better answers in the JBrowse mailing list:

http://jbrowse.org/en/contact.html

**Comment by nathandunn** [comment]
@mictadlo  I often just edit the tracklist.json by hand.  The script by default uses Alignments2, which can be more performant for a lot of reads, but hard to interact with (usually I would do both).   

If you are wanting to see introns, maybe you want to see GFF3s instead?   And then you pass in `type=mRNA` when processing in `flatfile-to-json.pl`

**Comment by mictadlo** [comment]
Thank you, Unfortunately, `type=mRNA` did not help. This is my updated command `perl /home/ubuntu/Apollo/jbrowse/bin/flatfile-to-json.pl --gff /efs/apollo/Gmp_NbV1_Final.gff3 --compress --trackType HTMLFeatures --trackLabel "NbanotFeb2019v3" type=mRNA --out /efs/apollo/`.

What did I miss?

Michal

**Comment by nathandunn** [comment]
should be `--type=mRNA`

But please refer to the docs: http://jbrowse.org/docs/flatfile-to-json.pl.html

**Comment by mictadlo** [comment]
Yes, you right but why have I 7 blue boxes in the introns area

![screen shot 2019-03-06 at 1 02 15 pm](https://user-images.githubusercontent.com/588297/53853163-1bb4d100-4010-11e9-9adc-53d933615f8b.png)

But the GFF3 file shows only 6 entries:
```
NbV1Ch01        NbGenome        gene    93632344        93636542        .       -       .       ID=Nb3PK42714.path1;Name=Equilibrative nucleotide transporter 1
NbV1Ch01        NbGenome        mRNA    93632344        93636542        .       -       .       ID=Nb3PK42714.mrna1;Parent=Nb3PK42714.path1;Name=Nb3PK42714;coverage=100.0;identity=9
9.8;matches=1245;mismatches=3;indels=0;unknowns=0
NbV1Ch01        NbGenome        exon    93632344        93633068        100     -       .       ID=Nb3PK42714.mrna1.exon2;Parent=Nb3PK42714.mrna1;Name=Nb3PK42714;Target=Nb3PK42714 5
24 1248 +
NbV1Ch01        NbGenome        CDS     93632344        93633068        100     -       2       ID=Nb3PK42714.mrna1.cds2;Parent=Nb3PK42714.mrna1;Name=Nb3PK42714;Target=Nb3PK42714 52
4 1248 +
NbV1Ch01        NbGenome        exon    93636020        93636542        99      -       .       ID=Nb3PK42714.mrna1.exon1;Parent=Nb3PK42714.mrna1;Name=Nb3PK42714;Target=Nb3PK42714 1
 523 +
NbV1Ch01        NbGenome        CDS     93636020        93636542        99      -       0       ID=Nb3PK42714.mrna1.cds1;Parent=Nb3PK42714.mrna1;Name=Nb3PK42714;Target=Nb3PK42714 1 523 +
```

What did I miss?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
This is a gene that only has two subfeatures. The CDS features are the important ones and they are coding subfeatures of the mRNA. That is what the purple and red boxes are (which are colored purple and red to correspond to the coding frame).


As I noted in my last post the middle section with the grey and blue alternating is decorative

**Comment by nathandunn** [comment]
Try removing 

`
    "style" : {
            "className" : "feature"
         },
` 

From within the `trackList.json` object.
