### ISSUE TITLE
Exporting annotations as GFF

### ISSUE THREAD

**Issue by trstickland** [GMOD/Apollo#2096]
I've been using the API `/IOService/write` method to export annotations.  It produces GFF3 something like...
```
Pf3D7_01_v3     .       gene    365920  368795  .       +       .       owner=foo@sanger.ac.uk;ID=5275bdbe-07f0-4836-9e58-8dc235491a1c;date_last_modified=2018-11-30;Name=PF3D7_0109100.1;date_creation=2018-11-30
Pf3D7_01_v3     .       mRNA    365920  368795  .       +       .       owner=foo@sanger.ac.uk;Parent=5275bdbe-07f0-4836-9e58-8dc235491a1c;ID=e13ad87b-c13a-4e10-8919-03c9d6d08144;date_last_modified=2018-11-30;Name=PF3D7_0109100.1-00001;date_creation=2018-11-30
Pf3D7_01_v3     .       exon    365920  368795  .       +       .       Parent=e13ad87b-c13a-4e10-8919-03c9d6d08144;ID=955748d7-ba08-498c-b49b-7d01fe4a869a;Name=955748d7-ba08-498c-b49b-7d01fe4a869a
Pf3D7_01_v3     .       CDS     365922  368795  .       +       0       Parent=e13ad87b-c13a-4e10-8919-03c9d6d08144;ID=e13ad87b-c13a-4e10-8919-03c9d6d08144-CDS;Name=e13ad87b-c13a-4e10-8919-03c9d6d08144-CDS
```
This looks correct.  I assume this is supposed to export alterations made by users, which suits our purposes fine -- but of course we need to be able to relate these features to the features in the data we originally loaded.   I figured we would be able to do that with identifiers, but there a problem with that plan, because `ID` value seems to have changed between loading and exporting.

e.g. the gene in the sample above was loaded from this GFF3:
```
Pf3D7_01_v3     chado   gene    365610  368795  .       +       .       ID=PF3D7_0109100;Name=CCp5;previous_systematic_id=PFA0445w,MAL1P2.18;synonym=LAP3
```
So the ID changed from `ID=PF3D7_0109100` in the original file to `ID=5275bdbe-07f0-4836-9e58-8dc235491a1c` in the exported data.

I'm guessing that the new ID is assigned when the data are loaded, as there's no guarantee that the input files contain globally unique identifiers.

Anyway, is there any way to preserve or retrieve the original identifiers?

(Or, possibly, I'm taking totally the wrong approach to this..?)

**Comment by nathandunn** [comment]
@trstickland  I added https://genomearchitect.readthedocs.io/en/latest/Configure.html?highlight=store_orig_id#add-attribute-for-the-original-id-of-the-object as part of #2002 

This is default off, but I'm wondering if I should set the default to on.

**Comment by trstickland** [comment]
That's excellent; sorry I missed it in the documentation!

I'm happy to configure it explicitly, but I would have thought it would suit most people if it was on by default.

Thanks!

**Comment by nathandunn** [comment]
No worries.  There is a lot of documentation. 

I updated it so it was on by default as well (on master).

Cheers, 

Nathan
