### ISSUE TITLE
Troubles with grails versions when launching apollo run-local

### ISSUE THREAD

**Issue by thomas77** [GMOD/Apollo#2106]
Hello,

I'm new in the WebApollo world and I'm currently installing the tool.

I finished to install all the prerequisites following your documentation and I'm having some troubles when I launch "./apollo run-local" to see a dev instance of the tool (I took the last version of apollo :2.3.1).

When I use grails version 2.3.7 I get this error message:

| Installed plugin scaffolding-2.1.2
| Error Plugin scaffolding-2.1.2 requires version [2.4.0 > *] of Grails which your current Grails installation does not meet. Please try install a different version of the plugin or Grails.
| Installed plugin scaffolding-2.1.2...

So I switched and I used grails version 2.4.1 but I get this error message:

BUILD SUCCESSFUL

Total time: 52.51 secs

| Application expects grails version [2.3.7], but GRAILS_HOME is version [2.4.1] - use the correct Grails version or run 'grails set-grails-version' if this Grails version is newer than the version your application expects.

Maybe I missed something in  the documentation, what should I do ?

Thanks for your help,

Best regards,

Thomas Letellier

**Comment by nathandunn** [comment]
If you remove grails altogether it should install the right version locally.  Otherwise you can install and set 2.5.5 grails as the default.  

Nathan

**Comment by thomas77** [comment]
thank you for your answer, actually it seem's that the file doesnt exist anymore : 

> Downloading https://github.com/grails/grails-core/releases/download/v2.5.5/grails-2.3.7.zip to /root/.grails/wrapper/grails-2.3.7-download.zip
> 
> Exception in thread "main" java.io.FileNotFoundException: https://github.com/grails/grails-core/releases/download/v2.5.5/grails-2.3.7.zip
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
> 	at org.grails.wrapper.RemoteFileHelper.retrieve(RemoteFileHelper.java:49)
> 	at org.grails.wrapper.GrailsWrapper.configureGrailsInstallation(GrailsWrapper.java:137)
> 	at org.grails.wrapper.GrailsWrapper.main(GrailsWrapper.java:57)
> 


https://github.com/grails/grails-core/releases/download/v2.5.5/grails-2.3.7.zip  -> Not Found


Regards,

Thomas

**Comment by nathandunn** [comment]
Can you give me some details on how you are installing it (operation system, using docker, using AWS, using tomcat, etc)? 

Also, are you planning to do development on it? 

If you don't need to install grails globally (you aren't doing specialized development) I would not do it.  Apollo will use the `grailsw` command and download the correct version.

If you do need to install it globally I would use https://sdkman.io/  and have it do it for you instead of trying to manually install it.

**Comment by thomas77** [comment]
> Can you give me some details on how you are installing it (operation system, using docker, using AWS, using tomcat, etc)?

I'm working on a centos 6 linux operation system (no docker or AWS). I've got a tomcat 7.0.93 and PG 9.5.

> Also, are you planning to do development on it?
No.

> If you don't need to install grails globally (you aren't doing specialized development) I would not do it. Apollo will use the grailsw command and download the correct version.
> 
> If you do need to install it globally I would use https://sdkman.io/ and have it do it for you instead of trying to manually install it.
> 

Ok thank you, I thought that I needed to run apollo run-local untill the end to see Apollo working correctly (I follow this documentation: https://cmdcolin-apollo.readthedocs.io/en/latest/Apollo2Build.html).

Thanks again for your help

**Comment by nathandunn** [comment]
Let me know if you run into anything else

**Comment by nathandunn** [comment]
The only caveat is you may need to set JAVA_HOME (if the grailsw command complains)


https://genomearchitect.readthedocs.io/en/latest/Setup.html?highlight=java_home#install-node-if-not-present <https://genomearchitect.readthedocs.io/en/latest/Setup.html?highlight=java_home#install-node-if-not-present>

sudo apt-get install ant openjdk-8-jdk 
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/  # or set in .bashrc / .project
