### ISSUE TITLE
add `see suffix` list to add track and add sequence stuff

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2125]
- [x] Change error text to get file name with suffix and note that it is not allowed
- [x] remove full path or say `not found` if null
- [x] re-indicate suffixes?

**Comment by nathandunn** [comment]
![image](https://user-images.githubusercontent.com/751274/55817205-e3f7e800-5aeb-11e9-805d-4dd01cd2c866.png)

**Comment by christabone** [comment]
IMO, it might be more clear to use "Filename extension not supported" as the error message (or something similar). Just from past experience I don't recall seeing the term "suffix" used too often in these types of errors. 

Just my humble opinion on the issue!

**Comment by nathandunn** [comment]
Thanks.  Good feedback. 

Nathan
