### ISSUE TITLE
Trying to delete feature with the WebService

### ISSUE THREAD

**Issue by thomas77** [GMOD/Apollo#2138]
Hello,

I'm using WebApollo v.2.3.0 and I try to delete some annotations. To do that I took the script "deleteFeature.sh"  that you host on [github](https://github.com/GMOD/Apollo/blob/2.3.0/docs/web_services/examples/shell/deleteFeature.sh). 

Here is my command:
`./delete_feature.sh http://10.0.0.200:8080/apollo-2.3.0 test@test.fr apollo TraesCS1A01G129700
`

And the results:
`
`HTTP/1.1` 200 OK
Server: Apache-Coyote/1.1
Set-Cookie: JSESSIONID=F60E4CE9C0FAE823EF6DE394AB3E31CE; Path=/apollo-2.3.0; HttpOnly
Set-Cookie: rememberMe=deleteMe; Path=/apollo-2.3.0; Max-Age=0; Expires=Tue, 16-Apr-2019 14:14:31 GMT
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
Date: Wed, 17 Apr 2019 14:14:31 GMT

{"features":[]}
`

As you can see the array of features is empty and I'm unable to delete my annotation, I checked that the name was the good one: the name is the same that the one appearing in the "Annotations" table on the WebApollo interface.

Do you have an idea ?

Thanks for your help,

Regards,

Thomas

**Comment by nathandunn** [comment]
I fixed this here: https://github.com/GMOD/Apollo/commit/a825bcbe154ebd5e19481888e0a916e63f1f5708

The original script was calling for a uniquename (a UUID), but using that as a feature.  

I added scripts for that explicitly: 

https://github.com/GMOD/Apollo/blob/develop/docs/web_services/examples/shell/deleteFeatureByFeatureName.sh
https://github.com/GMOD/Apollo/blob/develop/docs/web_services/examples/shell/deleteFeatureByUniqueName.sh

**Comment by thomas77** [comment]
Thank you for your help @nathandunn  !
