### ISSUE TITLE
browser refresh should bring a user back to the same place

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#214]
Funny . . . it does this, but not for selected ones.

**Comment by monicacecilia** [comment]
@nathandunn not funny. :-1:  :)

**Comment by nathandunn** [comment]
related to #215 . .  context switching for some organisms do not seem to get stored . ..  probably need a preferences JSON for this

**Comment by nathandunn** [comment]
Duh . .  I need to keep a JSON object of session preference:

    { defaults:
       [{  organism: 'bee',sequence:'Group1.10'}, { organism: 'human':sequence:'chr4' }]
       ,{defaultOrganism:'bee'}
   }

**Comment by nathandunn** [comment]
Need to be able t save the userprefs as well
![img_0170](https://cloud.githubusercontent.com/assets/751274/7081694/537740c0-defb-11e4-8d68-ff9c6e6f572a.jpg)

**Comment by nathandunn** [comment]
Need a domain object: Preference with fields: User user, JSONObj value, String name # name of preference. This will be a pretty loose way to do this. So, when we switch out of the organism, it will go to the Preference table and pick out the value for that organism . . these will be organismId, organismName, referenceSequence, browser info.

Conversely, I could instead use a database table called OrganismUserPreference: Organism organism, String name # preference name, User user, JSONObj values . . . though really the only preference is "sequence" . . . . . That could extend a general "Preference" and still pull the same stuff our of the session that we are now . . . pretty straight-forward.

**Comment by nathandunn** [comment]
Not quite working with multiple organisms.

**Comment by nathandunn** [comment]
/sequence/loadSequences/ is called MULTIPLE times.   Need to call centrally and the provide info centrally as opposed to panels doing separately.

**Comment by nathandunn** [comment]
TODO:
- Need to finish the "getAppState" function
- All "loading" of orgs and sequences should be done into the MainPanel, which just uses getter methods
- Finish methods for "setOrganism" and "setOrganismAndSequence"
- merge back in

**Comment by monicacecilia** [comment]
Ta-dah! Works great! :+1:
