### ISSUE TITLE
when switching organisms, should propagate to all other pages

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#215]
from @monicacecilia 

After switching from bee to human, in both places where the word "Organism" appears, I am still able to "Export" the last selected scaffold (Group) of bee.

-- This is only in theory: I am able to initiate the command to "Export" by clicking on the last selected Group (which still appears after switching to human), but the error to Export still appears. Notice in the image I will upload after this comment, that "Organism" is Human, but the selected Ref Sequence is still Group16.4 from bee.

**Comment by nathandunn** [comment]
I think that this needs a bit more discussion, but overall it makes sense.

**Comment by nathandunn** [comment]
when switching organisms, should update EACH panel

**Comment by monicacecilia** [comment]
No, there error remains. The last selected group is persistent even after changing organisms. 
![screen shot 2015-04-09 at 10 49 33 am](https://cloud.githubusercontent.com/assets/1714621/7073141/3350dcf2-dea6-11e4-956e-e121e405f6c7.png)

**Comment by nathandunn** [comment]
Currently the work is stashed

**Comment by nathandunn** [comment]
Need a domain object:  Preference with fields: User user, JSONObj value, String name # name of preference.    This will be a pretty loose way to do this.       So, when we switch out of the organism, it will go to the Preference table and pick out the value for that organism . .  these will be organismId, organismName, referenceSequence, browser info.  

Conversely, I could instead use a database table called OrganismUserPreference:  Organism organism, String name # preference name, User user, JSONObj values . . . though really the only preference is "sequence" . . .   . .  That could extend a general "Preference" and still pull the same stuff our of the session that we are now . . . pretty straight-forward.

**Comment by monicacecilia** [comment]
I am going with Yes, all clear and behaving as expected. 
But @nathandunn please read the error below for future reference. It was messing with me for a while, and then it disappeared. 


....
There is still an error, which I caught in this scenario:
* Current organism is for example "Honey Bee"
* I have looked at the available "Tracks" on the side panel
* Then I choose the "Ref Sequence" Tab. 
* Then I change to a different organism, for example "Human"
* The "Ref Sequence" tab refreshes and shows the new available ref sequences, HOWEVER, when I click back to "Tracks", it still shows those of the previous organism. 
oh... wait.... and if I change to a third organism.... a mess. 
* Then, I decided to refresh this page and the mysterious error cleared up. I have a feeling this has to do with some "lag" in the connection. ... I am now just as puzzled as you are @nathandunn .
