### ISSUE TITLE
JBrowse build Fail

### ISSUE THREAD

**Issue by csmibrahim** [GMOD/Apollo#2152]
I get this error on Ubuntu when I run  ./apollo run-local

Gradle version: 2
Using system gradle 2.11
Node Version: 11
Npm Version: 6
Yarn Version: 1
javac 1.8.0_191 found
javac installed
JDK 1.8 found: javac 1.8.0_191

:installJBrowseWebOnly
JBrowse already exists
From https://github.com/gmod/jbrowse
 * tag               1.16.2-release -> FETCH_HEAD
Already up-to-date.
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > dojo-webpack-plugin@2.7.7" has unmet peer dependency "webpack-sources@>=1.0.1".
warning " > extract-text-webpack-plugin@3.0.2" has incorrect peer dependency "webpack@^3.1.0".
warning " > url-loader@0.5.7" has unmet peer dependency "file-loader@*".
error An unexpected error occurred: "EFAULT: bad address in system call argument, copyfile '/home/XXX/.cache/yarn/v4/npm-@ava-babel-plugin-throws-helper-2.0.0-2fc1fe3c211a71071a4eca7b8f7af5842cd1ae7c/node_modules/@ava/babel-plugin-throws-helper/index.js' -> '/media/XXX/extra/Apollo/jbrowse/node_modules/@ava/babel-plugin-throws-helper/index.js'".
info If you think this is a bug, please open a bug report with the information provided in "/media/XXX/extra/Apollo/jbrowse/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
:installJBrowseWebOnly FAILED

**Comment by nathandunn** [comment]
If this an upgrade?  If so, you may want to do an:

 ./apollo clean-all 

first.

Also, what version of Ubuntu are you running with?   

I’ve done this extensively on Ubuntu 14 and 16 and they seem to work, but every system is a bit different.

This is Apollo 2.3.1, right?

I just tested with node 11, and that should be fine. 

Nathan

**Comment by csmibrahim** [comment]
Is not Upgrade.
----
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
---
Just new git clone now.

**Comment by nathandunn** [comment]
@csmibrahim  

I would try using node 8 as I was also having problems with node 11 (and let me know if that works).  

nvm is ideal if you can use it to switch node versions (and remove the system installed one):   https://github.com/nvm-sh/nvm#install--update-script

I'm going to test with a few different versions to see where it breaks and to put in a script for detecting and flagging the node version.   At some point I'll get the other stuff working.

**Comment by csmibrahim** [comment]
Yes, this work. but now I have another issue.
![image](https://user-images.githubusercontent.com/44603963/57165859-362ce000-6df0-11e9-9121-e4d0021c46ea.png)
The build process continues and then stuck as in the screen for 30 sec. After that as if new terminal open and no error or anything.

**Comment by nathandunn** [comment]
that compilation step will take awhile.  As long as the processors are active, then all is good.

**Comment by nathandunn** [comment]
but let me know if its not.  I'm going to close this for now.  

Closed by https://github.com/GMOD/Apollo/commit/f91b610399773249d153d41cc24f3eb0047fd7e3

**Comment by nathandunn** [comment]
But feel free to continue to comment in this thread if you run into further trouble

**Comment by csmibrahim** [comment]
Just the same issue after 30 sec the terminal is cleared and nothing come at all

**Comment by nathandunn** [comment]
What do you see if you type `top`?

**Comment by csmibrahim** [comment]
![image](https://user-images.githubusercontent.com/44603963/57166384-efd88080-6df1-11e9-864e-9e4471c04a4f.png)

**Comment by csmibrahim** [comment]
Any idea ... when i try localhost:8080/apollo
![image](https://user-images.githubusercontent.com/44603963/57169098-bd805080-6dfc-11e9-999a-737e40befa38.png)

**Comment by nathandunn** [comment]
Well, the build is borked.  

I would do an 

`apollo clean-all` 

and try the installation again and give me the full build dump stack. 

When I build I get this:

```
            9.bundle.js    57 KiB            9  [emitted]  
       browser.bundle.js   563 KiB      browser  [emitted]  browser
dojo/resources/blank.gif  43 bytes               [emitted]  
          main.bundle.js   567 KiB         main  [emitted]  main
   run_jasmine.bundle.js   771 KiB  run_jasmine  [emitted]  run_jasmine
Entrypoint main = main.bundle.js
Entrypoint browser = browser.bundle.js
Entrypoint run_jasmine = run_jasmine.bundle.js
[./build/dojo-webpack-plugin-loader/dojo/dojo.js] 70.1 KiB {main} {browser} {run_jasmine} [built]
[./node_modules/style-loader/index.js!./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./css/genome.scss] ./node_modules/style-loader!./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./css/genome.scss 1.18 KiB {11} [built]
[./plugins/BlastView/js/View/Track/CanvasFeatures.js] 5.1 KiB {11} [built]
[./plugins/BlastView/js/View/Track/_FeatureDetailMixin.js] 2.7 KiB {11} [built]
[./plugins/BlastView/js/main.js] 354 bytes {11} [built]
[./plugins/CategoryUrl/js/main.js] 4.37 KiB {11} [built]
[./plugins/DebugEvents/js/main.js] 6.07 KiB {11} [built]
[./plugins/GCContent/js/Store/SeqFeature/GCContent.js] 2.61 KiB {11} [built]
[./plugins/GCContent/js/View/Dialog/WindowSizeDialog.js] 3.21 KiB {11} [built]
[./plugins/GCContent/js/View/Track/GCContent.js] 3.14 KiB {11} [built]
[./plugins/GCContent/js/View/Track/GCContentXY.js] 3.13 KiB {11} [built]
[./plugins/GCContent/js/main.js] 659 bytes {11} [built]
[./src/JBrowse/main.js] 13.2 KiB {main} [built]
[./src/JBrowse/standalone.js] 9.41 KiB {browser} [built]
[./tests/js_tests/main.js] 1.48 KiB {run_jasmine} [built]
    + 1839 hidden modules
:javac
Note: /Users/nathandunn/repositories/nathanApolloMaster/src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:gwtc

BUILD SUCCESSFUL

Total time: 53.145 secs
| Compiling 15 source files

| Compiling 234 source files
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
| Compiling 370 source files

| Warning The [pruneTracks] action accepts a parameter of type [org.codehaus.groovy.grails.web.json.JSONArray] which has not been marked with @Validateable.  Data binding will still be applied to this command object but the instance will not be validateable.

       def pruneTracks(JSONArray tracksArray){
       ^
| Compiling 370 source files.....
***
Metrics servlet injected into web.xml
Metrics Admin servlet-mapping (for /metrics/*) injected into web.xml
***
| Running Grails application
Configuring Shiro ...
Shiro Configured
```

That `gwtc` is the most expensive especially on a smaller machine. 

What are the specs of your ubuntu build?

**Comment by csmibrahim** [comment]
I saved the output in a variable and echo 
BUILD SUCCESSFUL Total time: 1 mins 11.165 secs 
This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.11/userguide/
gradle_daemon.html grails: JAVA_HOME environment variable is not set

I created JAVA_HOME abd now working fine .

Thanks
