### ISSUE TITLE
steps after fixing a gene

### ISSUE THREAD

**Issue by mictadlo** [GMOD/Apollo#2154]
Hi,
We have followed (this)[https://www.youtube.com/watch?v=9CZjT0RYTxA] video on how to fix a gene with Apollo. We are wondering how to get the fixed gene back on the track so that other people could see it and the original annotation file gets changed?

Thank you in advance,

Best wishes,

Michal

**Comment by nathandunn** [comment]
Generally folks export the refined models as GFF3 and then merge back the changes in to the original model.

This can be done via a script (typically after more checks), by-hand (**shudder**) etc.   At some point we would like automate this a bit more, but not sure when that will happen.

**Comment by nathandunn** [comment]
@mictadlo 

Also, I might venture to ask on the group discussion list, as I think that folks have many different strategies:

```apollo@lbl.gov```

Results should be here (but please join if you're not already on there): 

https://groups.google.com/a/lbl.gov/forum/#!forum/apollo

Cheers.
