### ISSUE TITLE
create new annotation: update or delete on table "feature" violates foreign key constraint

### ISSUE THREAD

**Issue by charlie068** [GMOD/Apollo#2156]
Dear All,
I have installed apollo2 with postgresql on ubuntu 18.
I added a genome from fasta and gff3 files as described on your website. 
What I would like to get is the cds and protein sequence. For this, I understood I first need to create a new feature.
The problem:
From the left pane, I select a whole gene (exons+introns) and when I want to create an annotation "gene", I get the following error:

Hibernate operation: could not execute statement; SQL [n/a]; ERROR: update or delete on table "feature" violates foreign key constraint "fk_jpvdxc57abfiridcr57x8130" on table "feature_property" Detail: Key (id)=(605) is still referenced from table "feature_property".; nested exception is org.postgresql.util.PSQLException: ERROR: update or delete on table "feature" violates foreign key constraint "fk_jpvdxc57abfiridcr57x8130" on table "feature_property" Detail: Key (id)=(605) is still referenced from table "feature_property".

If I select only one exon, no problem, if I create another feature (e.g. terminator), no problem.
The same problem occurs also when I want to delete a feature I just created.

[catalina.txt](https://github.com/GMOD/Apollo/files/3193143/catalina.txt)

**Comment by nathandunn** [comment]
Do you have some (or all) of the sample gff3?   

If easier, the fasta and gff3 or a tarballs of the jbrowse directory is also useful.  You can email directly to me at nathandunn@lbl.gov if you don’t want that data public.

Thanks,

Nathan

**Comment by charlie068** [comment]
Thank you Nathan for your message.
Indeed it was something wrong with my gff3. Everything seems fine.
Thank you for your help.
Best wishes,
Jean-Charles
