### ISSUE TITLE
user create needs to be more intuitive

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#216]
from @monicacecilia 

I first typed the info on the fields and then clicked "Create". Which made everything disappear, so I assume it was done. -- then I could not find the user. 

It was only after the third time that I realized that typing the info on the fields, then clicking on "Create" was not the appropriate order. I needed to first click "Create", then type, then click "Save".

**Comment by nathandunn** [comment]
@monicacecilia   Can you put in what you would like / expect to see (pictures or words) and I'll make that happen.   We have a similar structure for group and organism, so something more intuitive makes a lot of sense so that we can propagate it throughout the UI.      This is why engineers shouldn't design user interfaces ;)

**Comment by nathandunn** [comment]
hide fields if not selected or not used .

**Comment by monicacecilia** [comment]
Not ready yet. 
The "Create" button is available when no users are selected.
If a user is selected then then the "Create" button is disabled. There is no easy way to "unselect" a user. Command + click is simply not intuitive. An alternative would be to click outside the list of users, or hitting "esc". 
Regardless, the "Create" button remains disabled even after "de-selecting" a user with "Command + click", and it is not possible to add new users.

**Comment by monicacecilia** [comment]
Yep, we checked this when you were here. Brilliant! Much better now! :dancer:
