### ISSUE TITLE
Deploying: updating configuration 

### ISSUE THREAD

**Issue by alpapan** [GMOD/Apollo#2161]
Asking for a friend:
Do we need to rebuild the .war file when we update the `apollo-config.groovy` or is editing `webapps/apollo/WEB-INF/classes/apollo-config.groovy` directly sufficient?

**Comment by alpapan** [comment]
(not within a development environment, straight tomcat)

**Comment by alpapan** [comment]
Or can we use the `scripts/copy_client.sh` script.... (from https://genomearchitect.readthedocs.io/en/latest/Architecture.html)

**Comment by nathandunn** [comment]
If you deploy it as a war file to a tomcat or jetty directory, then you need to rebuild the war file.   The copy_client is really only for dev.   

I'm sure it could be configured to look into another location by default if you needed it to be, but the default is to rebuild.
