### ISSUE TITLE
Error when changing annotation type when status is set

### ISSUE THREAD

**Issue by AgnesBaud** [GMOD/Apollo#2167]
Hello,

I have a problem where once an annotation have been **specified a status** (and even if I take the status off afterward), I can't change the feature type anymore. However, I can change the type of an annotation that have never been specified a status. 
I looked a bit into the database but I didn't find any differences between the genes for which it works (status never specified) and genes for which it doesn't work (status - at least once - specified ).

When I try to change the annotation type from gene to pseudogene, I get this error message:
![Capture du 2019-05-22 10-16-27](https://user-images.githubusercontent.com/22837825/58312801-59094d80-7e0c-11e9-99e8-1ee95449829e.png)
Whereas when I try to change the annotation type from pseudogene to gene, I get this error message:
![Capture du 2019-05-22 16-20-39](https://user-images.githubusercontent.com/22837825/58312868-81914780-7e0c-11e9-895d-20df57428cd3.png)

Below, the output of this operations in the catalina.out:
[ERRORS_catalina.out.pdf](https://github.com/GMOD/Apollo/files/3215897/ERRORS_catalina.out.pdf)

Thank you in advance,

Agnès

**Comment by nathandunn** [comment]
Thanks for reporting @AgnesBaud

**Comment by nathandunn** [comment]
Note: this only happens on the transcript. 

When changing on the gene I get the property:

     {"name":"orig_id","type":{"cv":{"name":"feature_property"}},"value":"GB42586-RA"}

and the property type:

      {"cv":{"name":"feature_property"}}

versus when set on the name we get the property property :

    {"type":{"cv":{"name":"feature_property"}},"value":"Opened"} 

and property type:

    {"cv":{"name":"feature_property"}}

In the database, they are both set the same:

     79591 |       0 |      79572 |    0 |     |         | Opened | org.bbop.apollo.Status

**Comment by nathandunn** [comment]
Changing annotation type leads to a proliferation of incorrect attributes.

![image](https://user-images.githubusercontent.com/751274/58337435-a1b80b00-7dfa-11e9-8e3e-deca7c4cb25f.png)

**Comment by nathandunn** [comment]
Part of a proposed solution:

```
diff --git a/grails-app/services/org/bbop/apollo/FeatureService.groovy b/grails-app/services/org/bbop/apollo/FeatureService.groovy
index 0dfc18621..769067dc2 100644
--- a/grails-app/services/org/bbop/apollo/FeatureService.groovy
+++ b/grails-app/services/org/bbop/apollo/FeatureService.groovy
@@ -1435,20 +1435,42 @@ public void setTranslationEnd(Transcript transcript, int translationEnd) {
                     gsolFeature.addToFeatureProperties(gsolProperty)
                 }
             }
+
+
+            // handle status here
+            if (jsonFeature.has(FeatureStringEnum.STATUS.value)) {
+                String propertyValue = jsonFeature.get(FeatureStringEnum.STATUS.value)
+//                String propertyValue = property.get(FeatureStringEnum.VALUE.value)
+                AvailableStatus availableStatus = AvailableStatus.findByValue(propertyValue)
+                if (availableStatus) {
+                    Status status = new Status(
+                            value: availableStatus.value,
+                            feature: gsolFeature
+                    ).save(failOnError: true)
+                    gsolFeature.status = status
+                    gsolFeature.save()
+                } else {
+                    log.warn "Ignoring status ${propertyValue} as its not defined."
+                }
+            }
+
             if (jsonFeature.has(FeatureStringEnum.PROPERTIES.value)) {
                 JSONArray properties = jsonFeature.getJSONArray(FeatureStringEnum.PROPERTIES.value);
+                println "converting properties ${properties as JSON}"
                 for (int i = 0; i < properties.length(); ++i) {
                     JSONObject property = properties.getJSONObject(i);
                     JSONObject propertyType = property.getJSONObject(FeatureStringEnum.TYPE.value);
-                    String propertyName = ""
+                    String propertyName = null
                     if (property.has(FeatureStringEnum.NAME.value)) {
                         propertyName = property.get(FeatureStringEnum.NAME.value)
-                    } else {
+                    }
+                    else
+                    if (propertyType.has(FeatureStringEnum.NAME.value)) {
                         propertyName = propertyType.get(FeatureStringEnum.NAME.value)
                     }
                     String propertyValue = property.get(FeatureStringEnum.VALUE.value)
 
-                    FeatureProperty gsolProperty = null;
+                    FeatureProperty gsolProperty = null
                     if (propertyName == FeatureStringEnum.STATUS.value) {
                         // property of type 'Status'
                         AvailableStatus availableStatus = AvailableStatus.findByValue(propertyValue)
@@ -1462,7 +1484,8 @@ public void setTranslationEnd(Transcript transcript, int translationEnd) {
                         } else {
                             log.warn "Ignoring status ${propertyValue} as its not defined."
                         }
-                    } else {
+                    } else
+                    if (propertyName) {
                         if (propertyName == FeatureStringEnum.COMMENT.value) {
                             // property of type 'Comment'
                             gsolProperty = new Comment();

```

**Comment by nathandunn** [comment]
Multiple problems to fix.  These all stem from the fact that the status is coming through the properties improperly.

- [ ] changing annotation type locks up with the above error if the status is on the transcript
- [ ] changing annotation type when on the top-level gene / pseudogene adds a property

The fix above actually works perfectly for transcript.   Need to make the same for the gene.

**Comment by nathandunn** [comment]
@AgnesBaud this should be working in the development branch now.   

Thanks for reporting.

**Comment by AgnesBaud** [comment]
It works perfectly. Thank you @nathandunn  !
