### ISSUE TITLE
restrict RO values per GPAD spec

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2172]
moved todo to PR #2177

**Comment by nathandunn** [comment]
FYI @vanaukenk

**Comment by vanaukenk** [comment]
@nathandunn 

I've added a table of allowed gp2term relations for GPAD2.0 to the specs:

https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md

Please let me know if you have any questions.

**Comment by nathandunn** [comment]
Specifcally: https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md#allowed-gene-product-to-go-term-relations


GO Aspect | Relations Ontology Label | Relations Ontology ID
-- | -- | --
Molecular Function | enables | RO:0002327
Molecular Function | contributes to | RO:0002326
Biological Process | involved in | RO:0002331
Biological Process | acts upstream of | RO:0002263
Biological Process | acts upstream of positive effect | RO:0004034
Biological Process | acts upstream of negative effect | RO:0004035
Biological Process | acts upstream of or within | RO:0002264
Biological Process | acts upstream of or within positive effect | RO:0004032
Biological Process | acts upstream of or within negative effect | RO:0004033
Cellular Component | part of | BFO:0000050
Cellular Component | colocalizes with | RO:0002325
Cellular Component | is active in | RO:0002432
