### ISSUE TITLE
uniquename should be shorter with no dashes and informative

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#218]
Should be: Name-Type-Date-UniqueKey

Maybe we don't need UniqueKey if we do compairsons

**Comment by nathandunn** [comment]
@monicacecilia  @selewis 

The more I look at this, the more I think that the UUID is the correct way to go.  We still have the name, but it is a global identifier related to time-stamps.     If I send you a GFF3 file with my UUID's, and you make changes, I can correlate it back to my own system.   And its a standard!!

**Comment by selewis** [comment]
What am I missing?

Yes we absolutely need a UUID.

This also serves as the symbol (aka name, aka label) if none other is
available.

But note! The UUID and the symbol are -not- the same thing. We need both.
UUID for all the reasons you say computer operations etc. And a name for
the biologists to refer to it in common parlance.

-S

**Comment by nathandunn** [comment]
Right .. We have a name and a symbol of a gene.  The unique name is the identifier.  Just looks ugly to have the uuid in the gff3 but it is only marginally worse than current. 

Nathan

**Comment by selewis** [comment]
Please, please do not call it a name. It's an ID, call it such. "Name" is
far too ambiguous and calling an ID a name will confuse people. Don't!

That is - don't have a "name" and a "symbol". Either have
a) name and ID
or
b) symbol and ID

**Comment by selewis** [comment]
You've closed this, but I sure hope it's not left standing as "name" and
"ID" are treated as the same thing!

If so then please re-open.

**Comment by nathandunn** [comment]
There is no change from the original feature object. 

Properties are id name, uniqueName, and symbol .. Same as before.  The only change is that uniqueName is calling the Java uuid method directly instead of rolling our own.  

Nathan

**Comment by selewis** [comment]
Think I need more information. Talk later today.
