### ISSUE TITLE
Keep Blast table links open

### ISSUE THREAD

**Issue by alpapan** [GMOD/Apollo#2180]
Hello

We noticed that in Apollo's JBrowse when you do a BLAST and there is a report table, you can click on each row to go to a hit. However, you have to close the window to see the data. 

If you want to look at the next row, you have to re-perform the BLAST (which is a performance issue on the server).

Is there a way we could minimise the blast result table and be able to see the track data? It would be great if we could also know which row we have already looked at (e.g. it could be marked with a colour like we do with URL (visited) Links?

I'm wondering that perhaps the easiest way of implementing this would be to make the BLAST table's row URL links that we can just right-click Open New link as new Tab rather than the current Javascript implementation? just and idea... 

Thanks!

**Comment by nathandunn** [comment]
I think my long-term plan is to move it to a side-panel to do away with that problem entirely, but I think we should minimally:

- [ ] provide a link
- [ ] allow minimization
