### ISSUE TITLE
elasticsearch plugin under Apollo

### ISSUE THREAD

**Issue by mictadlo** [GMOD/Apollo#2190]
Hi @nathandunn and @cmdcolin ,
Will https://github.com/elsiklab/jbrowse_elasticsearch work under Apollo?

Thank you in advance,

Michal

**Comment by cmdcolin** [comment]
This has been asked previously here
http://gmod.827538.n3.nabble.com/elastic-search-in-genome-apollo-td4059909.html
https://github.com/elsiklab/jbrowse_elasticsearch/issues/7
Is there anything that is problematic that you are seeing currently

**Comment by mictadlo** [comment]
Thank you for the links. Could you please add the ElasticSearch plugin ( https://github.com/elsiklab/jbrowse_elasticsearch ) into Apollo's docker container ( https://github.com/GMOD/docker-apollo )?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
@mictadlo  The docker container is now within Apollo (but it should work roughly the same).

I'm not going to have time to work on this for awhile.    

If you are running Apollo out of a docker image and need this functionality, I would suggest forking Apollo and updating the [Docker file](https://github.com/GMOD/Apollo/blob/develop/Dockerfile) to add elasticsearch and updating the [config](https://github.com/GMOD/Apollo/blob/develop/docker-files/docker-apollo-config.groovy) to include the plugin and supply any configurations.  You should be able to build it locally or via quay or docker hub directly.

JBrowse elasticsearch questions should be referred any of the [JBrowse lists](http://jbrowse.org/contact.html) and questions about doing the Docker fork can come here once you know how to configure JBrowse.  If it is fairly benign it can pull it back into mainstream.

**Comment by mictadlo** [comment]
Hi,
I added ElasticSearch to `cat docker-files/docker-apollo-config.groovy`

```
jbrowse {
    git {
        url = "https://github.com/GMOD/jbrowse"
        branch = "1.16.4-release"
    }
    plugins {
     ...
        ElasticSearch{
            git = 'https://github.com/elsiklab/jbrowse_elasticsearch'
            branch = 'master'
            alwaysRecheck = "true"
            alwaysPull = "true"
        }
    }
}
``` 
Next, I executed 

```
docker build -t apollo .
docker run -it -v "$(pwd)"/mydata:/data -p 8888:8080 -p 8080:3000 apollo
```

- http://localhost:8888/ works
- http://localhost:8080/ does not work for elasticsearch

What did I miss?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
This might be better to ask on the JBrowse and Apollo lists (at the same time) as I think its more of a configuration issue / problem then a development one. 

I’ve not really worked with the elastic search plugin, though I’m guessing that the Dockerfile should likely run install and run elastic search, which we don’t do in the current docker file. 

If you get it to work with straight JBrowse (and Docker) I can probably help you with any remaining problems here.

Nathan

**Comment by nathandunn** [comment]
Oh, I see you did post it.

**Comment by nathandunn** [comment]
I would see if @cmdcolin  would know what it would take to run the elasticsearch plugin: https://github.com/elsiklab/jbrowse_elasticsearch

I would start with doing this in a JBrowse docker first if you need to use docker and then extend that to work in Apollo. 

Again, the elasticsearch will be using its own server (elasticsearch) and its own proxy.

That being said, does the name server not work?

**Comment by nathandunn** [comment]
I would follow-up here: https://gitter.im/GMOD/jbrowse  as I don't know where a good Docker image is.  Feel free to tag me (and @cmdcolin ) there, as well.

**Comment by cmdcolin** [comment]
I can't really provide support for this plugin. I have told other users who try to use the jbrowse_elasticsearch plugin that it is advanced, has many moving parts, and you have to know what you are doing basically to use it

I can't guide the setup process.

I also can't provide any docker support

Sorry!

**Comment by cmdcolin** [comment]
Note that the main idea behind jbrowse_elasticsearch is just having the ability to do a full text search. If you don't need full text searching, you likely don't need the plugin? Just a thought. JBrowse has built in prefix searching, something many users don't realize but which accomplishes many search needs https://jbrowse.org/docs/faq.html#what-does-generate-namespl-do

**Comment by nathandunn** [comment]
@cmdcolin  no worries.    I forgot to mention what you did, that the built in generate names is probably all that is needed.

**Comment by mictadlo** [comment]
Hi all,
I tried to use `generate-names.pl` in the following way

```
> /efs/apollo/Nitab-v4.5$ perl ~/tomcat7-deploy/apollo/jbrowse/bin/prepare-refseqs.pl --fasta /efs/apollo/Nitab-v4.5_genome_Chr_Edwards2017.fasta --out /efs/apollo/ 
> /efs/apollo/Nitab-v4.5$ perl ~/tomcat7-deploy/apollo/jbrowse/bin/generate-names.pl --tracks Nitab-v4.5_gene_models_Chr_Edwards2017.gff --out /efs/apollo/Nitab-v4.5
```
on the below GFF3 file:

```
> cat Nitab-v4.5_gene_models_Chr_Edwards2017.gff
...
Nt01    maker   gene    513567  517023  .       -       .       ID=Nitab4.5_0002367g0080;Name=Nitab4.5_0002367g0080;Parent=Nitab4.5_0002367
Nt01    maker   mRNA    513567  517023  .       -       .       ID=Nitab4.5_0002367g0080.1;Parent=Nitab4.5_0002367g0080;Name=Nitab4.5_0002367g0080.1;_AED=0.01;_eAED=0.01;_QI=61|1|1|1|1|1|2|173|194;Note="Ribosomal protein S6%2C plastid/chloroplast%2C Translation elongation factor EF1B/ribosomal protein S6%2C Ribosomal protein S6"
Nt01    maker   exon    513567  513979  .       -       .       ID=Nitab4.5_0002367g0080.1:exon:2876;Parent=Nitab4.5_0002367g0080.1
Nt01    maker   exon    516618  517023  .       -       .       ID=Nitab4.5_0002367g0080.1:exon:2875;Parent=Nitab4.5_0002367g0080.1
Nt01    maker   five_prime_UTR  516963  517023  .       -       .       ID=Nitab4.5_0002367g0080.1:five_prime_utr;Parent=Nitab4.5_0002367g0080.1
Nt01    maker   CDS     516618  516962  .       -       0       ID=Nitab4.5_0002367g0080.1:cds;Parent=Nitab4.5_0002367g0080.1
Nt01    maker   CDS     513740  513979  .       -       0       ID=Nitab4.5_0002367g0080.1:cds;Parent=Nitab4.5_0002367g0080.1
Nt01    maker   three_prime_UTR 513567  513739  .       -       .       ID=Nitab4.5_0002367g0080.1:three_prime_utr;Parent=Nitab4.5_0002367g0080.1
```

Unfortunately, it did not work. What did I miss?

Thank you in advance.

Michal

**Comment by nathandunn** [comment]
This is a better question for the JBrowse mailing list or Gitter: http://jbrowse.org/en/contact.html <http://jbrowse.org/en/contact.html> 

Please follow-up there.  More doc here: http://jbrowse.org/docs/generate-names.pl.html#generate-namespl <http://jbrowse.org/docs/generate-names.pl.html#generate-namespl>

Very quickly, you run generate-names.pl over the genome directory (/efs/apollo) after you’ve already generated the tracks (flat-file-to-json.pl)

I can do any follow-up in the JBrowse gitter or email list tomorrow.

Nathan
