### ISSUE TITLE
color coding for gene and bam files

### ISSUE THREAD

**Issue by mictadlo** [GMOD/Apollo#2195]
Hi,
I am not able to figure out what the different colours and patterns mean in the gene and BAM tracks. 
![Screen Shot 2019-06-28 at 11 28 39 AM](https://user-images.githubusercontent.com/588297/60310914-397bbc80-9998-11e9-8f52-ff5265b810bd.png)

Could you please pinpoint me to the documentation?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
http://gmod.org/wiki/JBrowse_Configuration_Guide#Alignments2_coloring_schemes

Those are the default JBrowse styles.   I'll take a look if I can't fix the doc, but it will be awhile.  If you see a place to upgrade the doc , that would be great, though:  https://github.com/GMOD/Apollo/tree/develop/docs

The color is the different CDS frame.

**Comment by mictadlo** [comment]
Thank you. Why the colours in the gene sometimes repeat in sequence and occasionally they get interrupted by a different colour (@cmdcolin )?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
The color refers to the protein frame it is in.  It should match the color above with the correlating frame.
