### ISSUE TITLE
(1w) Add ability to change type for feature in UcA area

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#220]
Add ability to change type for feature in UcA area. 
Leftover from issue #23

**Comment by nathandunn** [comment]
If we are simply changing the mRNA class type (or gene to pseudogene) it could be very easy.  However, we will have to re-attach / reload if we end up doing a SQL update.  . ... conversely . .. we could just delete / add with the different type . .  that way we could potentially add it to the history as well.

**Comment by nathandunn** [comment]
Fixed by #1002

**Comment by monicacecilia** [comment]
gets the first 💃 !!
