### ISSUE TITLE
color by type with Apollo class is not working

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2203]
- [x] allow for CDS coloring as it is now with proper intron rendering (remove extra CSS)
- [x] expose a class to allow Coloring by Type via CSS
- [ ] *allow subfeature CSS coloring*
- [ ]   (set to {type} if style is not set, not sure if this should be set as a default or not . . . can't see the harm if `style` is not otherwise set.
- [ ] add documentation for CSS for color by type using  `{type}` and inclusion of the CSS using trackList.json (data/custom.css) in the root trackList.json directory as an example
- [x] fix bad documentation inclusion: https://github.com/GMOD/Apollo/issues/2203#issuecomment-512319539

===

So, there is an error with when using both ColorByCds and the ColorbyType plugin.   The reason for doing this is that the multiple types of things might be loaded on a single track.

Really, the right way would be to pass a class in and bind the css to it.

The code works well in the AnnotTrack.js: 
 https://github.com/GMOD/Apollo/blob/develop/client/apollo/js/View/Track/AnnotTrack.js#L616

The code seems to have been removed in DraggableHTMLFeatures as the class type is no longer exposed:

https://github.com/GMOD/Apollo/blob/develop/client/apollo/js/View/Track/DraggableHTMLFeatures.js#L50

By removing additoinal styles and using a FeatureTrack, we are able to view introns properly with ColorByCDS.   However, because we don't have a proper class exposed, we can't really bind CSS to it.

===

https://github.com/NAL-i5K/ColorByType
 
https://github.com/NAL-i5K/NAL_CSS

**Comment by nathandunn** [comment]
The way that AnnotTrack.json works is that it replaces the class with the class for the prescribed feature type.    This may also work given the appropriate CSS, but need to figure out where that is set.

**Comment by nathandunn** [comment]
Here is the picture of the Inc_RNA / ncRNA against the mRNA:

![image](https://user-images.githubusercontent.com/751274/61257826-93fe7200-a727-11e9-91e7-c5d2bd105cca.png)

**Comment by nathandunn** [comment]
Specific UTR class is set this way:

![image](https://user-images.githubusercontent.com/751274/61257874-c6a86a80-a727-11e9-8490-0c295e34d986.png)

the gnomon is a contributed one.   Somehow this gets mapped through.

**Comment by nathandunn** [comment]
In JBrowse with the volvox example we have:

![image](https://user-images.githubusercontent.com/751274/61338036-91198500-a7ec-11e9-89e4-b8b0bdd5efed.png)


with the native JBrowse we get:

![image](https://user-images.githubusercontent.com/751274/61338096-d047d600-a7ec-11e9-9a24-cb214137dacb.png)

`      {
         "category" : "NCBI Annotation Release 103",
         "key" : "NCBI_Annotation_Release_103_Gene",
         "label" : "NCBI_Annotation_Release_103_Gene",
         "type" : "NeatHTMLFeatures/View/Track/NeatFeatures",
         "urlTemplate" : "tracks/NCBI_Annotation_Release_103_Gene/{refseq}/trackData.json"
      }

`

**Comment by nathandunn** [comment]
If we set it as `{type}` that passes the class name through, so that we'll get `lnc_RNA-minus` (and plus) as mapped classes.   However, I think the code should probably only override the style if not existant.

- [ ] Also the trackList.json should list the way to include the custom CSS for apollo

`
--- a/client/apollo/js/TrackConfigTransformer.js
+++ b/client/apollo/js/TrackConfigTransformer.js
@@ -15,21 +15,25 @@ constructor: function( args )  {
     this.overridePlugins=browser.config.overridePlugins;
     this.transformers["NeatHTMLFeatures/View/Track/NeatFeatures"] = function(trackConfig) {
         trackConfig.type = "WebApollo/View/Track/DraggableNeatHTMLFeatures";
+        trackConfig.style = { className: "{type}", uniqueIdField : "id" };
     };

`

**Comment by nathandunn** [comment]
While I'm at it, I need to fix this.

![image](https://user-images.githubusercontent.com/751274/61387675-599ded80-a86b-11e9-8044-64aaf05fcab3.png)

**Comment by nathandunn** [comment]
The 'type' is set and we can over-ride with this:

```
.jbrowse .minus-lnc_RNA,
.jbrowse .plus-lnc_RNA,
.jbrowse .lnc_RNA
{ 
  background-color:'goldenrod';
  color:'green';
  stroke: '5px';
height: 12px; 
    margin-top: 2px;
    background-color: rgb(0,204,0);
}
```

**Comment by nathandunn** [comment]
This works here (but one should not do the background-color) if className is set to `{type}`:
`
.jbrowse .minus-lnc_RNA,
.jbrowse .plus-lnc_RNA,
.jbrowse .lnc_RNA
{ 
    height: 12px;
    margin-top: 2px;
    color: rgb(50,204,50);
    background-color: rgb(50,4,100) !important;
}
`

However, the subfeature is not properly set.

**Comment by nathandunn** [comment]
FYI @cmdcolin  / @rbuels  this is the madness I am talking about.   For this trackList.json:

```
  {
      "key": "NCBI_Annotation_Release_103_Gene",
      "label": "NCBI_Annotation_Release_103_Gene",
      "type": "NeatHTMLFeatures/View/Track/NeatFeatures",
      "style": {
        "className": "{type}"
      },
      "urlTemplate": "tracks/NCBI_Annotation_Release_103_Gene/{refseq}/trackData.json"
....
  "css":"data/custom.css"
```

and this CSS (for the top-level type lnc_RNA):

```
.jbrowse .minus-lnc_RNA,
.jbrowse .plus-lnc_RNA,
.jbrowse .lnc_RNA
{
    height: 12px;
    margin-top: 2px;
    color: rgb(50,204,50);
    background-color: rgb(50,4,100) !important;
}
```

I get this:

![image](https://user-images.githubusercontent.com/751274/61408104-24f25c00-a894-11e9-8cfe-810019d86d8c.png)

class is as follows:

![image](https://user-images.githubusercontent.com/751274/61408171-46ebde80-a894-11e9-96ad-5bf452e0218d.png)

**Comment by cmdcolin** [comment]
"This is the madness that I am talking about" is not telling me what your question is. What is the question?

**Comment by nathandunn** [comment]
@cmdcolin  The question is how to I populate the UTR regions (as its non-coding) with the same color as the outline.  Because it's a subfeature, I don't see an easy way to do this.  I wasn't sure what the original design behind this was.  I don't think that neatfueatures would have changed this really, but I'm unsure.

**Comment by cmdcolin** [comment]
lncRNAs do not have UTR. I am being very literal about the biology, UTR does not mean any part of a non-coding gene. You are asking why the features are white on the inside?

**Comment by cmdcolin** [comment]
If your lnc_RNA literally contains UTR subfeatures that is just incorrect IMO

**Comment by cmdcolin** [comment]
Now, if the question is how to color subfeatures, the subfeature is not the lnc_RNA, the subfeature is an exon. lnc_RNA's have exons. You should have a GFF like this

```
ctgA    test    lnc_RNA 13000   17200   .       +       0       ID=Testing;
ctgA    test    exon    13500   13800   .       +       0       Parent=Testing
ctgA    test    exon    15000   15500   .       +       1       Parent=Testing
ctgA    test    exon    16500   17000   .       +       2       Parent=Testing

```

Then you color the EXON with the css

```
.minus-exon,
.plus-exon,
.exon {
    height: 12px;
    margin-top: 2px;
    color: rgb(50,204,50);
    background-color: rgb(50,4,100) !important;
}
```

**Comment by nathandunn** [comment]
@cmdcolin  You are correct.  There are no UTR's.    Its an lnc_RNA with two exon subfeatures.    

What I want is to be able to do is style the exons of an lnc_RNA similar to the user annotation track.  

My confusion is the way it is coded a UTR class is added in it:

![image](https://user-images.githubusercontent.com/751274/61418474-7cea8c00-a8af-11e9-8957-5a6a2d2e5e3f.png)


I know in AnnotTrack.json they use the concept of alternateClasses, but I don't see similar hooks.

**Comment by nathandunn** [comment]
@cmdcolin  for your example, that is fine.  The question is, how can I color the exon based on its parent feature type?

**Comment by cmdcolin** [comment]
You can add the parent class to the CSS selector and then the exon style only applies to the this feature type. Is this what you are asking.

```
.lnc_RNA .minus-exon,
.lnc_RNA .plus-exon,
.lnc_RNA .exon {
        height: 12px;
        margin-top: 2px;
        color: rgb(50,204,50);
        background-color: rgb(50,4,100) !important;
    }

```

**Comment by cmdcolin** [comment]
Note: the idea of the minus-container/plus-container (which is Apollo specific), the NeatFeatures (which is a plugin), whether this is lncRNA or not (I don't think NeatHTMLFeatures adds a UTR if there never was one) and then just general CSS HTMLFeatures styles are all interplaying  in this issue in a way that is not necessarily easy to "debug". If you can narrow down the issue it would help

**Comment by nathandunn** [comment]
@cmdcolin  It ended up being this in this case, but as you note its dependent on the specific track:

```
.minus-lnc_RNA .neat-UTR,
.plus-lnc_RNA .neat-UTR,
.lnc_RNA .neat-UTR{
        height: 12px;
        margin-top: 2px;
        color: rgb(200,2,3);
        background-color: rgb(5,4,255) !important;
  }
```
