### ISSUE TITLE
track tab should throw an "alert" on any exception

### ISSUE THREAD

**Issue by mictadlo** [GMOD/Apollo#2204]
Hi,
After loading BAM files and editing the `trackList.joson` the Apollo track tab show only `Loading...` but the Jbrowse show all tracks

![Screen Shot 2019-07-15 at 5 22 54 PM](https://user-images.githubusercontent.com/588297/61200792-f48caf80-a725-11e9-860a-2ee0e3490456.png)

How can I fix it?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
Interesting.  Yeah, that looks like a bug. 

Could you:

1 - open up the javascript console and copy and paste in any errors (or everything you see) on reload.
2 - copy and paste in the `trackList.json` if you don't have any private information

thanks.

**Comment by mictadlo** [comment]
The Web Console show 3 times
```
TypeError: Ev(...).nc(...) is nullindex line 9 > scriptElement:69:289
    MMb https://apollo.benthgenome.qut.edu.au/annotator/index line 9 > scriptElement:69
    NMb https://apollo.benthgenome.qut.edu.au/annotator/index line 9 > scriptElement:76
    Eh https://apollo.benthgenome.qut.edu.au/annotator/index line 9 > scriptElement:485
    Hh https://apollo.benthgenome.qut.edu.au/annotator/index line 9 > scriptElement:329
    Gh https://apollo.benthgenome.qut.edu.au/annotator/index line 9 > scriptElement:209
    sendTracks webpack:///./plugins/WebApollo/js/View/Track/AnnotTrack.js?:251
    handleTrackVisibility webpack:///./plugins/WebApollo/js/View/Track/AnnotTrack.js?:267
    handleMessage webpack:///./plugins/WebApollo/js/View/Track/AnnotTrack.js?:297
```

Please
[trackList.txt](https://github.com/GMOD/Apollo/files/3394371/trackList.txt)
 find attached the `trackList.json` file.

Thank you in advance,

MIchal

**Comment by nathandunn** [comment]
Will that error message open up any further? 

Also, does it work if you remove individual lines from your trackList.json file? 

Nathan

**Comment by nathandunn** [comment]
If you can’t get more detail console log (which may or may not be possible as its compiled down), a couple of things I would recommend:

1 - run in dev mode and see if you get more detail (use ./apolllo devmode). 
2 - provide me a login and I can maybe take a look
3 - send me (nathandunn@lbl.gov <mailto:nathandunn@lbl.gov>) the full directory and I can take a look

I can’t see anything off-hand that would be problematic. 

Nathan

**Comment by nathandunn** [comment]
You are missing a `type` in your trackList.json, which is causing the error I think:

`
 {
         "urlTemplate" : "LabK9 scaled value of the treatment.bigwig",
         "bicolor_pivot" : "zero",
         "label" : "LabK9 scaled value of the treatment",
         "key" : "LabK9 scaled value of the treatment",
         "style" : {
            "className" : "feature"
         },
         "storeClass" : "JBrowse/Store/SeqFeature/BigWig",
         "autoscale" : "local",
         "category" : "iii. ChIP-seq"
      },
`

**Comment by mictadlo** [comment]
Thank you it works. How did you find it out?

**Comment by nathandunn** [comment]
Oh, I kind of inferred from the stack trace that ’type’ was missing and I checked your trackList.json for missing that.

**Comment by mictadlo** [comment]
Would it possible that Apollo would get a validator for `trackList.json`?

**Comment by nathandunn** [comment]
I’d you want to add a separate ticket for it with what you would expect that would be fine.  I’m moving towards just automating the process. 

Nathan

**Comment by nathandunn** [comment]
I think I can just throw an alert error with the proper message on failure.   that should be a better user notification than what I'm doing now.
