### ISSUE TITLE
move user's guide / genomearchitect.org into Apollo repo

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2205]
Add http://genomearchitect.org/ . 
 https://github.com/genomearchitect/genomearchitect.github.io

back to the docs directory to be rendered by read the docs.  

- [ ] have the genomearchitect.org point to the different readthedocs stuff (ping @kltm) 
- [x] add `users-guide`
- [x] transfer main page
- [x] transfer demo page
- [x] drop documentation page
- [x] drop "about us"
- [x] for community point to galaxy.edu and docker
- [x] drop archive

**Comment by nathandunn** [comment]
Picture from old site:


![image](https://user-images.githubusercontent.com/751274/61249010-1cb9e580-a709-11e9-8f61-8e04a2a6361b.png)

**Comment by nathandunn** [comment]
@kltm  Can you point http://geneontology.org to http://genomearchitect.readthedocs.io/en/latest/ ? 

Thanks.

**Comment by kltm** [comment]
How about http://genomearchitect.readthedocs.io .

**Comment by nathandunn** [comment]
@kltm  Yes, that makes more sense.  Thanks.

**Comment by kltm** [comment]
Okay, what this would be is a change from an A record to a CNAME, done through LBL, so the transition times would be slow. Are you okay with possibly knocking yourself out a bit if this goes wrong?

**Comment by nathandunn** [comment]
Slow is okay.  I've already added Meta-Refreshes which are not ideal, but seem to be working. 

Thanks.

**Comment by kltm** [comment]
@nathandunn I have not made any changes yet. I will start in a few minutes unless you stop me on skype or gitter.

**Comment by nathandunn** [comment]
@kltm  I've already forgotten I asked you to do it.

**Comment by kltm** [comment]
@nathandunn And this is a root domain change--if you have anything under or related to genomearchitect.org, it will no longer work. E.g.:

genomearchitect.berkeleybop.org
www.genomearchitect.org
apollo.berkeleybop.org
/apollo_web/
/WebApollo-hg19/
/webapollo/

etc.

Also, we seem to have a proxy back to readthedocs already. What is not working that you want working here again?

**Comment by kltm** [comment]
Ah, sorry, it's to GH.io, not RTD.

Still, are you wanting a similar proxpass, or to re-root the domain?

**Comment by nathandunn** [comment]
@kltm  Sure.  

http://genomearchitect.org/ currently points to http://genomearchitect.github.io 

I am mothballing http://genomearchitect.github.io

**Comment by nathandunn** [comment]
We aren't using the genomearchitect for anything else AFAICT.

**Comment by kltm** [comment]
That's fine. However, it is not a redirect, but a proxypass. Do you just want a redirect there for now, a proxypass, or to re-root the domain?

**Comment by nathandunn** [comment]
Oh, a redirect or a re-root is probably what I need.     Basically everything in that subdomain should transfer over.   Maybe some day, some year it will be used for something else, but I don't know when.

**Comment by kltm** [comment]
If so, have you followed the instruction here: https://docs.readthedocs.io/en/stable/custom_domains.html ?
