### ISSUE TITLE
Genes not displaying correctly 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#221]
Probably has something to do with the JBrowse Controller and established Mime-Type

![screen shot 2015-04-08 at 12 58 32 pm](https://cloud.githubusercontent.com/assets/751274/7054082/fe107dac-ddee-11e4-99b4-402b713062f6.png)

**Comment by cmdcolin** [comment]
This is normally just missing CSS. There is a lot of custom CSS on honey bee example. Normally we add a folder called our_css to the plugins/WebApollo/css/ directory and then include them in plugins/WebApollo/css/main.css or add them using the css flag in the trackList.json
http://gmod.org/wiki/JBrowse_Configuration_Guide#Click_Configuration_Options

**Comment by nathandunn** [comment]
@cmdcolin   I'm fairly certain that is not the issue, though a good place to start . . . I think its that I'm setting the mime-type incorrectly in the JBrowseController.  It was working before I put the code in their to support bigwig and bam files.

**Comment by monicacecilia** [comment]
Genes are displayed correctly now. Thanks!
