### ISSUE TITLE
docker build caused errors

### ISSUE THREAD

**Issue by mictadlo** [GMOD/Apollo#2215]
Hi,
I build the docker container from this repository with `docker build -t apollo .` and encounter the following problems:

```
Building and testing Heap-Simple-Perl-0.14 ... ! Installing Heap::Simple::Perl failed. See /apollo/.cpanm/work/1564198566.13192/build.log for details. Retry with --force to force install it.
FAIL
```
and

```
rm: cannot remove '/apollo/': Permission denied
```

What did I miss?

Thank you in advance

Michal

**Comment by nathandunn** [comment]
What are you trying to do overall? 

Are you forking it to build something else or just trying to run.  

Can you paste in the command (as well as the branch / fork you are working on)? 

Thanks,

Nathan

**Comment by mictadlo** [comment]
Hi Nathan,
Yes, I started to modify your docker files (please see here https://github.com/GMOD/Apollo/issues/2190#issuecomment-515651504 ) in order to get the ElasticSearch plugi-n running.

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
I doubt its the change.   You probably just to to remove all of the images and containers and re-run it and it will likely work.   Again, I would do this with JBrowse first.

**Comment by nathandunn** [comment]
Let me know if this should be re-opened.
