### ISSUE TITLE
API to update organism with archived data directory

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#2219]
Hi,
So addOrganismWithSequence is working well with the upload of a tar.gzipped jbrowse data dir (even with 2bit index now wouhou!), but it would be cool to have the same when updating an organism.
Currently with the galaxy<->apollo code, when we want to update an organism with a new jbrowse data dir (modified tracks for example), we copy the new dir to some shared location and pass this location using updateOrganismInfo (directory param).
It would be great to have a organismData param for updateOrganismInfo(WithSequence?) working the same was as addOrganismWithSequence (=extracting data to apollo data dir, replacing existing data)

**Comment by nathandunn** [comment]
@abretaud  sorry, its taken me awhile.  

If you have an add and update tar example, that would help me speed this up a bit.
