### ISSUE TITLE
Create Annotation from BLAT search

### ISSUE THREAD

**Issue by Jorisvansteenbrugge** [GMOD/Apollo#2225]
I would like to request a feature that allows me to create an annotation based on a BLAT search result. Now I can only highlight the genomic region of a result, is it possible to create a user annotation based on this?

**Comment by nathandunn** [comment]
@Jorisvansteenbrugge   What type of annotations are you thinking.  A single gene / transcript / exon from the given area?

**Comment by nathandunn** [comment]
- add comment field in search tool when generating

**Comment by nathandunn** [comment]
Fixes by #2266
