### ISSUE TITLE
add status filter in annotator panel and add status detail to annotator detail panel

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2269]
- [x] status filter in the status detail portion
- [x] add status filter to the annotator panel
- [ ] allow NOT filter and handle null cases
- [ ] add status filter to changes / reports tab
- [ ] make sure that changes / reports is visible to non-admin users if configured so

**Comment by strumpfe** [comment]
This would be a great addition. Having a status filter would obviate the need to export GFF3, run checks via UNIX/Perl and then go back to Apollo to make the changes.

**Comment by nathandunn** [comment]
@strumpfe  As I understand what you are saying, this is pretty easy to implement if just for the Annotator Panel / tab so I'll see if I can knock it out this week. 

We you thinking that it would be useful from the Ref Sequence panel (for export?) as well?

**Comment by strumpfe** [comment]
Annotator panel is the obvious use case as it lists the annotations (atomic entity that have status). My primary wish is to be able to filter and interact with unfinished status annotation within Apollo. Some thought on the null group and/or default status assignment for new annotations is also relevant.

I get the idea of using this as a filter for export, which means that the Ref Sequence panel is also within scope but I see these as two different use cases but perhaps the same code development.

**Comment by nathandunn** [comment]
> Annotator panel is the obvious use case as it lists the annotations (atomic entity that have status). 

Okay, I will make that happen.

> My primary wish is to be able to filter and interact with unfinished status annotation within Apollo. 

I will add this to the `Report:Changes` screen as well in the admin panel.

> Some thought on the null group and/or default status assignment for new annotations is also relevant.

#2139 addresses the default status.  It ends up being trickier than I would like, but I agree that it is important. 

What do you mean by the `null group`?

> I get the idea of using this as a filter for export, which means that the Ref Sequence panel is also within scope but I see these as two different use cases but perhaps the same code development.

Agreed.  Added to #2357

**Comment by strumpfe** [comment]
Our implementation maybe different from others but we have 'Finished' and 'Not finished' as statuses. As there is no default value here and people don't necessarily assert the 'Not finished', the group of annotations that potentially need mediation are those will no status (null group) and/or asserted 'Not finished'. This could be dealt with if there are some boolean options e.g. filter for NOT 'Finished'

**Comment by nathandunn** [comment]
Thanks.  That makes sense.  I'm certain other people are using statuses, so I wouldn't worry.
