### ISSUE TITLE
re-enable jbrowse-style look and feel the tracklist

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#227]
@cmdcolin   Note that this is 2.1

**Comment by cmdcolin** [comment]
The annotator panel should technically be interfacing with the javascript browser.config object instead of parsing trackList.json itself. This would automatically pick up tracks from tracks.conf files.

**Comment by nathandunn** [comment]
@cmdcolin   this bug needs to be renamed . . .

**Comment by nathandunn** [comment]
Closing in favor of #536.
