### ISSUE TITLE
findAllOrganisms exception when organism does not exist

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#2275]
Hi,
I'm playing with arrow and apollo 2.4.1 (docker image), and I get this error when trying to show a non existing organism:

```sh
$ arrow organisms show_organism "vfsd"
{
    "error": "Failed to convert from type java.lang.String to type java.lang.Long for value 'vfsd'; nested exception is java.lang.NumberFormatException: For input string: \"vfsd\""
}
```

The interesting part of the loooong backtrace is:
```
	at org.bbop.apollo.OrganismController.$tt__findAllOrganisms(OrganismController.groovy:1320)
	at org.bbop.apollo.OrganismController$_findAllOrganisms_closure12.doCall(OrganismController.groovy)
```
Which in develop branch correspond to this line: https://github.com/GMOD/Apollo/blob/develop/grails-app/controllers/org/bbop/apollo/OrganismController.groovy#L1389
I guess there would need some check or try/catch?

**Comment by nathandunn** [comment]
Yeah, I think this could be rolled up into a service of some source actually as its fairly repeated.  The catch block would the

```
          render([error: "Organism not found"] as JSON)
```

I can create a PR for this if that would be helpful.

**Comment by nathandunn** [comment]
@abretaud  let me know if #2278 fixes the PR for you
