### ISSUE TITLE
sandbox user annotations on the same organism

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#228]
My thought is that user's will have a "different" type of permission on an organism, allowing them to see only annotations within their group or self. 

There is a trello card.

**Comment by cmdcolin** [comment]
My idea for just creating multiple "organisms" with the same data directory to sandbox users/groups does not work. You can still see annotations from other people.

**Comment by nathandunn** [comment]
Might be a dupe, but definitely related to other permission stuff.

**Comment by nathandunn** [comment]
this is a dupe
