### ISSUE TITLE
when creating an mRNA with gene / CDS evidence, CDS and Exon not being created

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2296]
since 2.4.1

All of the yeast sample data does this.  I think it worked pre-2.4.1, but not sure why it would break all of a sudden.

- [ ] automatically create an Exon before setting longestORF

**Comment by nathandunn** [comment]
Question @erasche  / @abretaud  : 
- does a CDS without an exon make sense?  I think that it does for some genomes.  We do allow the removal of an exon.
- should we automatically add an exon if an mRNA?
- should we allow manual addition of an exon if an mRNA, but an exon was not in the original evidence?

**Comment by erasche** [comment]
1. None of it makes sense :) yeah I guess for proks maybe without exon
makes sense... Not the right person to ask anymore I guess.
2. Probably not? Maybe ask co-workers from $oldjob
3. I'm not 100% convinced it's Apollo's job to fix input data but, yeah,
I'd say convert whatever messy data you're given into a proper Apollo
eukaryotic Gene model and everyone can deal with it?

Op do 31 okt. 2019 02:16 schreef Nathan Dunn <notifications@github.com>:

**Comment by nathandunn** [comment]
Hmmm . . . I'm actually thinking that we should have someone ask for it, but in general folks will supply exons if they have them.   If we added exons where they don't belong (for example, annotated yeast will not have genes) http://jbrowse-dev.alliancegenome.org/jbrowse/index.html?data=data%2FSaccharomyces%20cerevisiae&tracks=All%20Genes&highlight=&lookupSymbol=SSN3&loc=chrXVI%3A472042..475709 . I think we will create more problems than less.

**Comment by nathandunn** [comment]
@erasche  Can I close this for now?

**Comment by erasche** [comment]
Yep!

Op do 31 okt. 2019 19:17 schreef Nathan Dunn <notifications@github.com>:
