### ISSUE TITLE
provide a default group when remote users get added

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2302]
When a user is created, if configured in `apollo-config.groovy` they would be added that group similar to how admin is set on startup. 

From https://groups.google.com/a/lbl.gov/forum/#!topic/apollo/XjppB0UPhxE

**Comment by nathandunn** [comment]
Something like this:

```
{
  default_user_group: ['virus_group','pathogen_group']
}
```

**Comment by trstickland** [comment]
Thanks, that would resolve the issue I raised on the mail list

**Comment by nathandunn** [comment]
Already fixed by https://github.com/GMOD/Apollo/pull/1445#issuecomment-273438478
