### ISSUE TITLE
Wrong creator metadata in remote mode

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#2303]
So, now that python-apollo 4.0.1 is out, I tested the new apollo tools in https://github.com/galaxy-genome-annotation/galaxy-tools/pull/44, but I have some failing tests because apparently, when adding an organism in remote mode, the creator metadata is set to the user name instead of userid in non-remote mode:

`"metadata": "{\"creator\":\"admin@local.host\"}"`

instead of:

`metadata": "{\"creator\":\"20\"}"`

I don't know if it's a big bug, but at least it's confusing to have different value type depending on how the organism was created.

**Comment by nathandunn** [comment]
I think the original problem was that you won't always have a proper user.  I think I have a quick fix for this.
