### ISSUE TITLE
gff3 export works

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#231]
@deepakunni3   For you to mark ready and assign to me when it is ready (I'll then send it to Moni to test).

**Comment by nathandunn** [comment]
@deepakunni3   I optimized your call (ignore the white-space).   

If you have a way to flag "all" that would probably be optimal.  I'm not sure what the limit for "inList" is when exporting all.    (imagine you had 1K annotated sequence groups) . . . 

Anyway, lower priority.  You can review it, mark it as ready and send it back to me.

**Comment by nathandunn** [comment]
@deepakunni3  The change amounts to doing a single query with a join to feature location so that we only fetch sequences that have annotations.   When you do a "Sequence.findByName()" it is actually executing a SQL query.    Which is fine, unless they are in a loop of 5K!    Anyway, it is always best to get it to work first and then optimize it.

**Comment by monicacecilia** [comment]
Both retrieving the GFF3 directly from the annotation and exporting using the side panel are functional. :fireworks: :sparkler: yay! thanks @deepakunni3! I think having the sequence-region bit on the header of the file is useful!

**Comment by deepakunni3** [comment]
Awesome!
