### ISSUE TITLE
`grails` and macOS Catalina

### ISSUE THREAD

**Issue by Dr-Drosophila** [GMOD/Apollo#2315]
Current OS: Mac OS 10.15.1

Apollo installation does not work.
Within `apollo` file, tried to run through file and install one by one.

All seemed to install fine except for `grails 2.5.5`.
`grails 2.5.5` is not compatible with MacOS Cataline.

However, newer versions of grails including `4.0.1` is compatible.
- [ ] Can we update _Apollo_ to work with newer versions of `grails`?

Best
CR

**Comment by nathandunn** [comment]
@Dr-Drosophila   I use grails 2.5.5 on Catalina.    Unless you are doing development, you can just use `./grailsw`, which will download the proper version automatically.    You will need to download java 8 and make sure that JAVA_HOME is pointed to it.  Conversely, using docker for the same would also work.  Should be more info here: https://genomearchitect.readthedocs.io/en/latest/ 

At some point we'll move to grails 4 as we move to JBrowse2, but not on a timeline I'd recommend waiting for it.

I'm closing this for now, but feel free to reply here, or better yet to the apollo group `apollo@lbl.gov`.

**Comment by Dr-Drosophila** [comment]
Hello Dr. Dunn

I plan on developing for _Apollo_, but do not know the timeline as to when I will be useful.
I am currently using _Docker_ in order to open an instance.

Do you suggest I downgrade back to Mojave for the time-being?
Or could I develop using `./grailsw`? If so, how do I implement it?

Best
CR

**Comment by nathandunn** [comment]
@Dr-Drosophila   It will be called automaticallly.  Possibly you should uninstall grails and then grailsw will automatilly get loaded. 

Conversely, you can use sdkman https://sdkman.io/sdks#grails and install grails 2.5.5 that way as well.

**Comment by nathandunn** [comment]
Post any errors.

**Comment by Dr-Drosophila** [comment]
Uninstalled JDK, `grails`, `cradle' and `groovy`.

Reinstalled all using `sdk`. 

Working now with `grails 2.5.5`.

Sorry for the inconvenience.

Best
CR

**Comment by nathandunn** [comment]
@Dr-Drosophila  Not a problem.  Let me know if you need any further help.
