### ISSUE TITLE
FASTA export works

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#232]
@deepakunni3   For you to mark ready and assign to me when it is ready (I'll then send it to Moni to test).

**Comment by nathandunn** [comment]
@deepakunni3   Looks like the same code as in #231 . . . just review and send back.  If there is a way to fix for "all" that would be great. 

Nathan

**Comment by nathandunn** [comment]
@deepakunni3   Looks like you tried to assign 233 . . . I'll just assign it back.   No worries.

**Comment by monicacecilia** [comment]
Alas, not quite there yet. 
There is a problem. FASTA is exporting **Genomic** sequences well (btw, @deepakunni3 the details you added on the def line are very helpful!), but the export of **cDNA**, **CDS**, and **Peptide** sequences produces FASTA files with 0 (zero) residues per feature. For example:

The gene model GB40008-RA in Group 1.33 has 2,024 amino acid residues, and when exported as part of the FASTA / Peptide option for Group1.33, Apollo produces a FASTA file containing this information:


>7c785ded-5d3c-42ba-80dd-3b0ba910b21c (Gene) 0 residues [Group1.33:432046-453635 - strand] [peptide] name=GB40008-RA

The same is true for all other models in the group:

>802f4fec-9648-47d5-aa26-fc378ea89eab (Gene) 0 residues [Group16.4:588893-641819 - strand] [peptide] name=GB51291-RA
>85b648f2-4a2a-49b0-b5d4-2b751a48f42b (Gene) 0 residues [Group16.4:499808-515783 - strand] [peptide] name=GB51292-RA-00001
>5645b26d-03e0-4065-be9f-5e46f5ffbf1f (Gene) 0 residues [Group16.4:231892-241069 - strand] [peptide] name=GB51299-RA
>f868512a-6495-4778-9533-963d98b4c928 (Gene) 0 residues [Group16.4:497532-611886 + strand] [peptide] name=GB51316-RA
>6b987a82-6311-4529-a5e0-d75907065f4c (Gene) 0 residues [Group16.4:1397756-1415326 + strand] [peptide] name=GB51336-RA
>615bb21f-a42f-4ca9-b3d0-1575a56efd54 (Gene) 0 residues [Group16.4:1515709-1519565 + strand] [peptide] name=GB51343-RA



#### Also, one small change: 
Could you please make sure the export tool correctly indicates **cDNA** instead of **CDNA** (please note incorrect caps). Thanks!

**Comment by deepakunni3** [comment]
@monicacecilia The error has been fixed and 'CDNA' is now 'cDNA'.

**Comment by nathandunn** [comment]
@deepakunni3    I think bigger issue is the lack of residues on the coding sequences for the sequences that  @monicacecilia   highlighted above.

Mark it as ready / review and assign it to me when you think it is working (or if there is another issue).

**Comment by nathandunn** [comment]
@deepakunni3   . . . or did you fix that as well? I'm still not seeing Residues in CDS still.

**Comment by nathandunn** [comment]
It all seems to be working now.

**Comment by deepakunni3** [comment]
:+1:

**Comment by monicacecilia** [comment]
Not yet. 

The export tool is producing a FASTA file with n-1 selected groups. 

For example, I selected five reference sequences, but the export tool only includes information from four of them. This occurs regardless of whether there are annotations in the U-cA area or not. 

![screen shot 2015-04-14 at 9 48 18 pm](https://cloud.githubusercontent.com/assets/1714621/7152395/2106e64c-e2f0-11e4-8cc7-770ede877a25.png)

**Comment by nathandunn** [comment]
@deepakunni3   This could simply be an error in my older selection code.   Conversely it could simply be indicating that only for ref sequences had annotations in which case it should say something like:

"Exported 4 of 5 reference sequences with annotations" or something like that.

**Comment by deepakunni3** [comment]
@nathandunn Having trouble replicating this specific issue but I have seen this before. It doesn't do any check for annotations on GWT side. All selected sequences are sent to server-side. 

This is more related to a scenario where the selected sequences are not handled consistently. When I tried it out, after many attempts, got to a situation where I selected one sequence but export panel showed '0 exported'.

**Comment by nathandunn** [comment]
I wonder if we should close this one and create a ui bug specifically for this issue.  

Nathan

**Comment by deepakunni3** [comment]
@nathandunn  That makes more sense.

**Comment by nathandunn** [comment]
Moved this UI issue to #278.

**Comment by monicacecilia** [comment]
k. :+1:
