### ISSUE TITLE
BLAT search and configuration

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#233]
@cmdcolin  For you to mark ready and assign to me when it is ready (I'll then send it to Moni to test).

**Comment by nathandunn** [comment]
@deepakunni3   I think you marked the wrong one.

**Comment by cmdcolin** [comment]
This is getting pretty close to being done just as a general status update. I think it could be ready by tomorrow

**Comment by nathandunn** [comment]
K thanks.

**Comment by cmdcolin** [comment]
Currently the blat search can get to this stage

    ->>   46 | <init>              in org.gmod.gbol.bioObject.Match
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    |     97 | convertToMatch      in org.bbop.apollo.tools.seq.search.blast.BlastAlignment
    |    109 | runSearch . . . . . in org.bbop.apollo.tools.seq.search.blat.BlatCommandLine$$EP9s8bl2
    |     43 | search              in     ''
    |     25 | $tt__searchSequence in org.bbop.apollo.SequenceSearchService$$EP9s9Jyy
    |    462 | searchSequence      in org.bbop.apollo.AnnotationEditorController$$EP9s99pw
    |    198 | doFilter . . . . .  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
    |     63 | doFilter            in grails.plugin.cache.web.filter.AbstractFilter
    |     69 | handleOperation . . in org.bbop.apollo.AnnotationEditorController$$EP9s99pw
    |    198 | doFilter            in grails.plugin.cache.web.filter.PageFragmentCachingFilter
    |     63 | doFilter . . . . .  in grails.plugin.cache.web.filter.AbstractFilter
    |    449 | executeChain        in org.apache.shiro.web.servlet.AbstractShiroFilter
    |    365 | call . . . . . . .  in org.apache.shiro.web.servlet.AbstractShiroFilter$1
    |     90 | doCall              in org.apache.shiro.subject.support.SubjectCallable
    |     83 | call . . . . . . .  in     ''
    |    383 | execute             in org.apache.shiro.subject.support.DelegatingSubject
    |    362 | doFilterInternal .  in org.apache.shiro.web.servlet.AbstractShiroFilter
    |    125 | doFilter            in org.apache.shiro.web.servlet.OncePerRequestFilter
    |   1145 | runWorker . . . . . in java.util.concurrent.ThreadPoolExecutor
    |    615 | run                 in java.util.concurrent.ThreadPoolExecutor$Worker
    ^    744 | run . . . . . . . . in java.lang.Thread

Then it fails based on I think using the old gbol classes instead of the new ones. Any ideas @nathandunn

**Comment by nathandunn** [comment]
@cmdcolin  Yeah, I would create another source folder under java or src/groovy and copy and paste the code you need to use.    So ou'l need copies of BlatCommandLind, and BlatAlignment . . minimally

**Comment by cmdcolin** [comment]
Should be fixed. I followed the steps that nathan mentioned and copied a lot of spaces from


- Created new SequenceSearchService and loaded some configuration parameters from the ConfigWrapperService
- Moved package org.bbop.apollo.tools.search to org.bbop.apollo.sequence.search in the groovy subdirectory
- Made the search tools specifically load Alignments instead of the Match class because the concepts of "rank" and "sourcefeature" were removed from the new domain objects such as Match
- Used JsonBuilder in the SequenceSearchService to render the matches back to the client so it works pretty well for BLAT protein and nucleotide settings


Here's a probably incomplete list of changes of changes relevant to the issue

394cf5be12428e014d087251162431983b4c0bba
e1800f77d3b5a6a6a583cb8a7ec886afb929b439
c4a954625a1333f159cad7e03070b93fbcdcd3ee
20e38a86dacf3e72cc7a10297c237bd65643eb2c
4c526d2417c03f82a6c829a54264cbaddc01d4e2
d86569828a49a3b2ed001591e456cec75e4b5251
27b105d1aa9682bede87dae25f195e01dbc27d95
2c56c5629c27df68eba2c8be85652c4cc3d123b8
80e9d7c83187a1689582dee9a011be5d87dff521
5e3ad1c2a6c1629653995e8739a91a2487d19219
7252bad8000507725bff0889a1dfef7e94783073
4dd14a1f0c96653a78a6c92fe956c44e09114167
d312fe48fb0063cb543b10de033a94b1c37b9d09
e981587231fc4861df2977b1ed8861bc318ded31
540a4bcfda81e98c68df8d820367eb5271857980
03fc7cc16dbf7482fd3a673c1a83835d24da109e

**Comment by nathandunn** [comment]
@cmdcolin   Let me know when you get the blat database update piece working and assign it to me with the ready label so I can update it.  

Thanks.

**Comment by cmdcolin** [comment]
Blat search working pretty well. I tested protein and nucleotide match classes (there are default ones defined in the Config.groovy). I also tested adding new parameters (i.e. -minMatch=50) and that seems to work pretty well. Since #277 is fixed now this should be ready

**Comment by nathandunn** [comment]
I'm getting this error:  

Error 500: Internal Server Error

URI
/apollo/AnnotationEditorService
Class
org.codehaus.groovy.grails.web.json.JSONException
Message
JSONObject["database"] not found.
Around line 29 of BlatCommandLine.java

26:        try {27:            blatBin = config.getString("search_exe");28:            tmpDir = config.getString("tmp_dir");29:            database = config.getString("database");30:            blatUserOptions = config.getString("params");31:        } catch (Exception e) {32:            throw new SequenceSearchToolException("Error parsing configuration: " + e.getMessage(), e);
Around line 25 of grails-app/services/org/bbop/apollo/SequenceSearchService.groovy

22:        JSONObject searchUtils=configWrapperService.getSequenceSearchTools().get(ret)23:        searchUtils.put("database",database)24:        def searcher=this.class.classLoader.loadClass( searchUtils.get('search_class'), true, false )?.newInstance()25:        searcher.parseConfiguration(searchUtils)26:        Collection<TabDelimittedAlignment> results=searcher.search('blat',27:                input.get('search').residues,28:                input.get('search').database_id)
Around line 451 of grails-app/controllers/org/bbop/apollo/AnnotationEditorController.groovy

448:        Long organismId = session.getAttribute(FeatureStringEnum.ORGANISM_ID.value) as Long449:        Organism organism = Organism.findById(organismId)450:        println organism.toString()451:        render sequenceSearchService.searchSequence(inputObject, organism.getBlatdb())452:    }453:454:
Around line 198 of PageFragmentCachingFilter.java

195:			if (CollectionUtils.isEmpty(cacheOperations)) {196:				log.debug("No cacheable annotation found for {}:{} {}",197:						new Object[] { request.getMethod(), request.getRequestURI(), getContext() });198:				chain.doFilter(request, response);199:				return;200:			}201:
Around line 63 of AbstractFilter.java

**Comment by nathandunn** [comment]
I think its looking in the config instead of the database:

            database = config.getString("database");

**Comment by cmdcolin** [comment]
I think this error would happen if you haven't setup a database for your organism yet via the Organism panel. Should probably handle the error better. It is only using that as a config object, it wouldn't actually be getting it from the config file

**Comment by nathandunn** [comment]
I had the database setup properly.  It doesn't get that far.  Its trying to get a config parameter out that doesn't exist and throws an exception.   You probably have it in your config, so you aren't noticing it.

**Comment by cmdcolin** [comment]
You can see in SequenceSearchService how it sets up the database parameter.

There is probably something else going ...Maybe it is some weird cacheing issue?

**Comment by nathandunn** [comment]
I fixed it to pull the current organism from the database instead of the session, which is kind of a new change.  

Now I'm getting permission errors:

upUn1774","key":"blat_nuc"},"track":"Annotations-GroupUn1774"}
Error creating tmp dir: /opt/apollo/honeybee/tmp/blat_1429642232212828000. Stacktrace follows:
Message: Error creating tmp dir: /opt/apollo/honeybee/tmp/blat_1429642232212828000
    Line | Method
->>  127 | createTmpDir        in org.bbop.apollo.sequence.search.blat.BlatCommandLine
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     41 | search              in     ''
|     29 | $tt__searchSequence in org.bbop.apollo.SequenceSearchService$$EPAW64m8
|    453 | searchSequence      in org.bbop.apollo.AnnotationEditorController$$EPAW8AaW


Because in Config.groovy:

 blat_nuc {
            search_exe = "/usr/local/bin/blat"
            search_class = "org.bbop.apollo.sequence.search.blat.BlatCommandLineNucleotideToNucleotide"
            name = "Blat nucleotide"
            tmp_dir = "/opt/apollo/honeybee/tmp"
            params = ""
        }
        blat_prot {
            search_exe = "/usr/local/bin/blat"
            search_class = "org.bbop.apollo.sequence.search.blat.BlatCommandLineProteinToNucleotide"
            name = "Blat protein"
            tmp_dir = "/opt/apollo/honeybee/tmp"
            params = ""
        }

Let's just use a Java generated tmp directory.  One less thing for a user to configure and the permissions will always be correct (I hope).  

If there is demand for this to be somewhere else, I'll let someone create a feature request, but I think its unlikely.

**Comment by cmdcolin** [comment]
>> Let's just use a Java generated tmp directory 

Sounds good to me!

**Comment by cmdcolin** [comment]
The tmp_dir change should be fixed. I just made it optional and system specified by default

>I fixed it to pull the current organism from the database instead of the session, which is kind of a new change.

Did you happen to push this change yet?

**Comment by nathandunn** [comment]
I pushed this change.   Look in searchSequence under AEC.  

I am not getting the error anymore, but neither am I getting any results (always an empty set . . and with no error).  

Also, the label from “blat_nuc” -> “BLAT nucleotide”  a same for “BLAT protein”.  

Looks like you’re deleting the file on exit?  That is fine if you are, just wanting to confirm as not of the temp files seem to exist after the operation.  

Nathan

**Comment by nathandunn** [comment]
This is what I see:

sequenceSearch {"operation":"search_sequence","search":{"residues":"AAATTTTCCATTTTTATATTTTCT","database_id":"Group1.14","key":"blat_nuc"},"track":"Annotations-Group1.14"}
Organis to string:  {"id":5650,"commonName":"Honey2","genus":null,"species":null,"directory":"/opt/apollo/honeybee/data/"}
/var/folders/fn/5kk1421n5z55z_vcycq0p7340000gn/T/blat_tmp6101367789274316543
/usr/local/bin/blat 
/opt/blat/db/amel.2bit:Group1.14 
/var/folders/fn/5kk1421n5z55z_vcycq0p7340000gn/T/blat_tmp6101367789274316543/query.fa 
/var/folders/fn/5kk1421n5z55z_vcycq0p7340000gn/T/blat_tmp6101367789274316543/results.tab

**Comment by cmdcolin** [comment]
Hmm it looks like it's close to working. A typical query looks very similar to that for me as well. Do you have any output to those files i.e. results.tab?

**Comment by nathandunn** [comment]
It is working for you then? 

Nathan

**Comment by cmdcolin** [comment]
Yea it looks good on my end even after pulling your change. Can get multiple matches. Nucleotide search. Protein search. Etc.

**Comment by nathandunn** [comment]
@cmdcolin  It is working for me now.  I must have been doing something stupid. 

Do you want to change the  labels and get rid of the println's in favor of log.info/debug and then we can mark it as ready.

**Comment by erasche** [comment]
@cmdcolin just got around to reading this thread...

> Added the "Blat db" entry to the Organism configuration panel, but the code is actually configurable enough so that if someone wanted to write a plugin for a different search engine they could do that too (had @erasche in mind for this)

thank you! That's really great! I'll see what I can do to copy your example and make a PR with a Blast version (other search suggestions welcome)

**Comment by cmdcolin** [comment]
Blat doesn't seem to be working for me anymore


    Organism to string:  {"id":4,"commonName":"Honeybee","genus":"Apis","species":"mellifera","directory":"/opt/apollo/honeybee/data"}
    | Error 2015-04-23 10:13:54,906 [http-bio-8080-exec-1] ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [POST] /apollo/AnnotationEditorService - parameters:
    data: {"operation":"search_sequence","search":{"residues":"CTCAGCACTTCTTACAGAACGTACATCTGTTTGGGAGATGGCTCTGTTCACTGCAACTTTGTTTCCTGTGATATCGGTCCGGAGCGATATAGCTATTGGATATCTTGATAGTTTTGACAAAGTTGGATTATAG","database_id":"GroupUn2405","key":"Blat nucleotide"},"track":"Annotations-GroupUn2405"}
    {"track":"Annotations-GroupUn2405","search":{"key":"Blat nucleotide","residues":"CTCAGCACTTCTTACAGAACGTACATCTGTTTGGGAGATGGCTCTGTTCACTGCAACTTTGTTTCCTGTGATATCGGTCCGGAGCGATATAGCTATTGGATATCTTGATAGTTTTGACAAAGTTGGATTATAG","database_id":"GroupUn2405"},"operation":"search_sequence"}:
    Cannot invoke method put() on null object. Stacktrace follows:
    Message: Cannot invoke method put() on null object
        Line | Method
    ->>   43 | $tt__searchSequence in org.bbop.apollo.SequenceSearchService
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
    |    459 | searchSequence      in org.bbop.apollo.AnnotationEditorController
    |    198 | doFilter . . . . .  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
    |     63 | doFilter            in grails.plugin.cache.web.filter.AbstractFilter
    |     70 | handleOperation . . in org.bbop.apollo.AnnotationEditorController
    |    198 | doFilter            in grails.plugin.cache.web.filter.PageFragmentCachingFilter
    |     63 | doFilter . . . . .  in grails.plugin.cache.web.filter.AbstractFilter
    |    449 | executeChain        in org.apache.shiro.web.servlet.AbstractShiroFilter
    |    365 | call . . . . . . .  in org.apache.shiro.web.servlet.AbstractShiroFilter$1
    |     90 | doCall              in org.apache.shiro.subject.support.SubjectCallable
    


Key thing to note is the "Organism to string" output lack the blatdb

**Comment by nathandunn** [comment]
@cmdcolin  If you look on line 43 of SequenceSearchService you can see that the is retrieving a null searchUtils:

its because the "ret" is now "BLAT nucleotide", but you want to lookup the key value "blat_nuc", which is correct.   "BLAT nucleotide" should be the display, but "blat_nuc" should be the value.

**Comment by cmdcolin** [comment]
@nathandunn Oh gotcha. That's my bad I'll make a fix

**Comment by cmdcolin** [comment]
Should be fixed again

**Comment by nathandunn** [comment]
Perfect!

**Comment by monicacecilia** [comment]
I am unable to test. Please see error report on #88

**Comment by monicacecilia** [comment]
When I use the appropriate sequence, BLAT is working well. Great! -- please see persistent issue that has not been solved on #88  -- I know. That's your favorite. :)
