### ISSUE TITLE
inability to name annotations in the user-created annotations track

### ISSUE THREAD

**Issue by Dr-Drosophila** [GMOD/Apollo#2345]
I am trying to rename `Rheb-PA.splan_4636-00003` to something else, but am unable to do it.
![Screen Shot 2020-01-15 at 08 24 30](https://user-images.githubusercontent.com/26606959/72441750-d1909600-3770-11ea-916a-e9fb58e5e67a.png)

I go to the Annotator Panel and select the annotation and try to change the name to something else. 
![Screen Shot 2020-01-15 at 08 24 25](https://user-images.githubusercontent.com/26606959/72441885-0c92c980-3771-11ea-8b5c-0eb3feb14f53.png)

But when I do that, it grays out, and there is no change in the User-Created Annotations track.
![Screen Shot 2020-01-15 at 08 29 04](https://user-images.githubusercontent.com/26606959/72441968-419f1c00-3771-11ea-87e8-33663696a3ec.png)

After a refresh of the page, it just resets back to the starting state, where I can enter the name I want to change it to.
![Screen Shot 2020-01-15 at 08 31 17](https://user-images.githubusercontent.com/26606959/72442377-fa655b00-3771-11ea-8180-b9c9dae52a64.png)

 
Apollo Version:  `2.5.0`
Console Log: [console.log](https://github.com/GMOD/Apollo/files/4065380/console.log)

If anymore files would be useful, please let me know.

**Comment by nathandunn** [comment]
This is helpful.  Not seeing anything on the backend, though.

Could you (1) provide the JavaScript console when you do the move and (2) provide the docker command you use?

Definite bug of some sort, but I just need to make sure I can fix it in the right place. 

Also, I think that this is `gmod:apollo/latest`  not `gmod:apollo/2.5.0` (I may need to update the name). ?

**Comment by Dr-Drosophila** [comment]
1.  provide the JavaScript console when you do the move 
    - Unsure how to do this

2. provide the docker command you use?
    - `docker run -it -p 8888:8080 -v /Users/rele.c/Downloads/apollo/jbrowse_data:/data gmod/apollo:latest`

Yes, I used `good:apollo/latest`, which would refer to `2.6.0`.

**Comment by nathandunn** [comment]
yes, okay that helps . . its a bug in the newer code-base.  You may want 2.5.0 unless there is something specific in the new release.  I'll try to get to it this week either way.

**Comment by nathandunn** [comment]
On chrome, you enter the developer tools (command-shift-i) and click on the console tab.  Anyway, I see the error (its obfuscated here), so you don't necessarily need to send this.

![image](https://user-images.githubusercontent.com/751274/72458470-829d2d80-377d-11ea-8655-8600d845f8b6.png)

**Comment by nathandunn** [comment]
small bug . . should be fixed now . . . let me know if not
