### ISSUE TITLE
exon / CDS should ALSO be editable text fields, but nudge up and down

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#235]
can be "nudged", but not an open text fields

**Comment by nathandunn** [comment]
This just needs two buttons (or something like that) that will allow user's to increase / decrease fmin and fmax.  There is some code in there for the old text-box that handle the onChange event.  It should really just mimick that and check for fmin < fmax, etc. and gray out the buttons while requests are in transit.

**Comment by nathandunn** [comment]
Make "editable": and switch icons.

**Comment by nathandunn** [comment]
@deepakunni3   Talked to @selewis  and @monicacecilia   there were some small changes.

**Comment by nathandunn** [comment]
@deepakunni3  small changes were to make the field editable (as original) and change the +/- icons to < > or something else like that

**Comment by deepakunni3** [comment]
@nathandunn Got it. Will get those changes added soon.

**Comment by deepakunni3** [comment]
@nathandunn Ready to test and feedback.

**Comment by nathandunn** [comment]
@deepakunni3   Looks good to me . . I'll send it to moni a bit later today (I have some outsanding stuff)

**Comment by monicacecilia** [comment]
Error when editing boundaries. Please see details at #335

**Comment by nathandunn** [comment]
I'm going to close this one and leave #335 open as I don't think this caused that error.
