### ISSUE TITLE
Apollo 2.5 tries to fetch from "https://github.com/GMOD/myvariantviewer", which doesn't exist

### ISSUE THREAD

**Issue by EGroWi** [GMOD/Apollo#2350]
Really described in the title. The "apollo deploy" command (also after "apollo clean-all", just in case) tries to fetch the MyVariantView jbrowse plugin from (https://github.com/GMOD/myvariantviewer), which returns a 404. Since the only alternative I found ("https://github.com/elsiklab/myvariantviewer") seems to be rather old (and does not allow a successful deploy), I assume the github repository at "https://github.com/GMOD/myvariantviewer" has been removed? Is there a way of disabling the need for this plugin so apollo can deploy successfully?

**Comment by nathandunn** [comment]
From here: 

https://gmod.github.io/jbrowse-registry/#!?term=myvar

It looks like the plugin is definitely here (and it is kind of old, but should work last I checked): 

https://github.com/elsiklab/myvariantviewer

1 - Where did you find doc for the GMOD/myvariantviewer?    I don't think it should have ever pointed there, so I need to fix that. 
2 - what does your `apollo-config.groovy` look like?

**Comment by EGroWi** [comment]
First of all, thank you for answering. The problem is solved, for more detail see below.
 
> 1 - Where did you find doc for the GMOD/myvariantviewer? I don't think it should have ever pointed there, so I need to fix that.

I am using the apollo-config.groovy that came with Apollo  2.4.1, edited to allow it to connect to the postgresql database on my server. I seem to also have un-commented the section on plugins, though I am not sure when or why I did this (it happened a few weeks ago), and can't see any changes beyond the removal of the comment marks when running diff. Just in case I will attach it to the post, passwords, and usernames xx'ed out. I know this version did deploy successfully with Apollo 2.4.1 a few weeks ago, though it doesn't do so anymore.
The information about GMOD/myvariantviewer popped up as an error message when running "apollo deploy"; I was asked for a github-login to continue. See here the relevant section of the output:

```
Evaluating plugin HideTrackLabels=[included:true]
Plugin jbrowse/plugins/HideTrackLabels exists and appears valid.
Evaluating plugin MyVariantInfo=[git:https://github.com/GMOD/myvariantviewer, branch:master, alwaysRecheck:true, alwaysPull:true]
Plugin is supplied by git
Cloning 'https://github.com/GMOD/myvariantviewer' into 'jbrowse/plugins/MyVariantInfo'
Cloning https://github.com/GMOD/myvariantviewer via shell
Command to execute [git clone  https://github.com/GMOD/myvariantviewer jbrowse/plugins/MyVariantInfo ]
> Building 0% > :installJBrowseUsername for 'https://github.com': 

```
After entering a login:

...
Cloning into 'jbrowse/plugins/MyVariantInfo'...
remote: Repository not found.
...

Looking at the default sample-postgres-apollo-config.groovy from the Apollo 2.5 tarball, the commented out section on MyVariantInfo does point to:

...
////        MyVariantInfo {
////            git = 'https://github.com/GMOD/myvariantviewer'
////            branch = 'master'
...


> 2 - what does your `apollo-config.groovy` look like and where did you find the doc for it (I need to remove / fix it)?

See above. The documentation is here (https://genomearchitect.readthedocs.io/en/latest/), but at the time when Apollo 2.4.1 was active. The groovy-file I use is based on the postgre-variant found in that installation package, with some changes as outlined above. Just to clarify - I did deploy with 2.4.1 and this groovy-file several weeks ago (a few days before 2.5 was released). Since no data was loaded into it yet I decided to use Apollo 2.5, postponing the deploy until now. The only thing that has changed was that I downloaded 2.5, and copied my old groovy file into the directory. 
Since this didn't work I tried by now to re-deploy 2.4.1, just to see if that worked, and it also fails now with the same issue. I assume the location gmod/myvariantviewer existed then, and now it doesn't. 

> 3 - what happens if you remove the line specifying the `myvariantviewer` from your `apollo-config.groovy`, and then do an `apollo clean-all` followed by `apollo deploy` again? Please provide the full stack trace.

Once I have commented out myvariantviewer the deploy runs smoothly, and the war-file can be loaded successfully into tomcat, leading to a functional instance of apollo.
What I assume you mean with the stack trace (sorry, I am what I'd call an advanced user, missing some professional lingo) I have attached. 

Thanks for helping me, and that quickly! Sorry for the hassle, I was just too blind to see that I had removed the comments for some unfathomable reason. Then again it seems the commented out section does link to a non-existent location, so hopefully this was not a waste of your time!


[apollo-config.groovy.tar.gz](https://github.com/GMOD/Apollo/files/4090474/apollo-config.groovy.tar.gz)
[StackError.txt](https://github.com/GMOD/Apollo/files/4090470/StackError.txt)
[StackTrace.txt](https://github.com/GMOD/Apollo/files/4090471/StackTrace.txt)

**Comment by nathandunn** [comment]
Always happy to help.  There are a lot of moving parts here. 

Glad you got it running.
