### ISSUE TITLE
(2h) web_sevices_api (add organism notes)

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#237]

**Comment by nathandunn** [comment]
should look like:

![screen shot 2015-04-10 at 11 19 00 am](https://cloud.githubusercontent.com/assets/751274/7094084/7231d728-df73-11e4-9fbe-13d99e52a086.png)

Help should be a "popup", "version" should go to the correct page.  Web services API page should work (convert to a gsp? )

**Comment by nathandunn** [comment]
Also need to move the "version" out of the "index" tab and into the "version" drop-down

**Comment by cmdcolin** [comment]
The help menu should match now. I am not sure what the other tasks mentioned are (maybe has to do with sidebar?)

**Comment by nathandunn** [comment]
this moot until we specify organisms

**Comment by nathandunn** [comment]
I wired it here:

http://localhost:8080/apollo/web_services/api

via the URL mapper:
        "/web_services/api"(controller:"annotationEditor",action: "web_services", params:params)

the gsp page is "web_services.gsp" 

stylesheet and images are in the assets directory.

**Comment by nathandunn** [comment]
@cmdcolin   Just wanted to get these wired in properly.  

One note about organism, you can pass in commonName, id, or abbreviation. . . 

I can also just finish this one up as well.  I was mostly unsure of adding in the API link into the menu.

**Comment by cmdcolin** [comment]
>One note about organism, you can pass in commonName, id, or abbreviation. . .

I like that! I check it out and see if i can come up with anything

So now 337 237 and 253 are sort of taken care of?

**Comment by nathandunn** [comment]
>So now #337 #237 and #253 are sort of taken care of?

Well, if you want to add a help link for this one (#237), I can finish it up (or you can, just let me know and assign and/or mark it as "working on").   The other two just need to be tested by you.    

Probably next is #319 and #353 , which are related.   I think that #353 is going end up being "important", though its not labeled as such yet.

**Comment by selewis** [comment]
Might also be useful if you could pass in the NCBI taxon ID, or the the
UniProt 4 letter code.

ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/
and
http://www.uniprot.org/docs/speclist

**Comment by nathandunn** [comment]
I moved that request to #367 . . . I think that different organizations will want different types of important meta-data information associated with them.   We had a similar discussion with BLAT and BLAST database directories, as well.

**Comment by nathandunn** [comment]
I haven't updated the doc yet, as I I'll do that while I'm writing the scripts.

**Comment by nathandunn** [comment]
We'll need to continue to update this, but plan to do so as part of #254 and #255.

**Comment by nathandunn** [comment]
Clicking on the "web_services_api" in JBrowse should go to a web_services_api page.

**Comment by monicacecilia** [comment]
Almost, almost, super almost there. 

When you pull the "Help Menu", we give users the option to go to two links (on the bottom right of the Help panel). But these links open within the "annotator" window. So instead of JBrowse+Apollo, what you see is either docs or the guide. And depending on the size of the window, it gets worse (see image below).

**Solution: open the user guide and the config&install guide in separate windows.** 

![screen shot 2015-05-22 at 2 38 44 pm](https://cloud.githubusercontent.com/assets/1714621/7780200/d5b76e96-0090-11e5-8242-60f3334319ae.png)

**Comment by monicacecilia** [comment]
Thanks.
