### ISSUE TITLE
Support full Sequence Ontology (SO) terms for annotation

### ISSUE THREAD

**Issue by obsidian83** [GMOD/Apollo#2392]
Currently Apollo supports most of the SO terms(https://github.com/The-Sequence-Ontology/SO-Ontologies) for annotation, it would be very useful to be able to have the full repertoire of SO terms for annotation. For BRC4 this will be handy on our end when we reconcile the patch builds and we would like to know if there is a mechanism to use and enforce the SO set when annotators make updates.

Not sure if coincides with https://github.com/GMOD/Apollo/issues/41

**Comment by nathandunn** [comment]
We've looked at doing this before.   We actually support ways of doing this in a generic sense.   Unfortunately, the list of SO terms is massive, and I think a lot of the terms in the SO aren't going to be as informative, or make sense to curators if we include them as a direct option. 

Perhaps what might be more practical would be to support all child of a sub-term or allow users's to enter a child of a sub-term via a lookup.   This would allow us to support all ncRNA's, all mRNA's, all pseudogene's, etc.   – either as a secondary option, or as a direct entry. 

Let me know if you have any thoughts, any major sub-categories, etc.

**Comment by nathandunn** [comment]
@obsidian83  any progress on this?

**Comment by obsidian83** [comment]
Expansion of SO terms to cover greater depth of pseudogene and ncRNA

Updates to the stock set of Apollo biotypes/SO terms (based on terms we have seen used in annotations). In the big scheme of things these entries are uncommon (i.e. protein coding genes account for >95% of the annotations), but if we are going to expand annotation of  the pseudogene + ncRNA gene categories these might be useful
1) pseudogene http://www.sequenceontology.org/browser/current_release/term/SO:0000336
potential candidates are entries below
http://www.sequenceontology.org/browser/current_release/term/SO:0000043
(**processed_pseudogene + transcribed_processed_pseudogene + translated_processed_pseudogene**)
+
http://www.sequenceontology.org/browser/current_release/term/SO:0000462
( **pseudogenic_CDS + pseudogenic_exon + pseudogenic_rRNA + pseudogenic_tRNA**)
2) ncRNA http://www.sequenceontology.org/browser/current_release/term/SO:0001263
include all children terms of ncRNA that are not already covered i.e.  (gRNA_gene (SO:0001264) RNase_P_RNA_gene (SO:0001639) tmRNA_gene (SO:0001271) SRP_RNA_gene (SO:0001269) tRNA_gene (SO:0001272) lncRNA_gene (SO:0002127) enzymatic_RNA_gene (SO:0002180) RNase_MRP_RNA_gene (SO:0001640) telomerase_RNA_gene (SO:0001643)  piRNA_gene (SO:0001638) scRNA_gene (SO:0001266))

**Comment by nathandunn** [comment]
@obsidian83  

So is that 2 additional for pseudogene (and keeping pseudogene) and 11 to add for ncRNA?  

I might do a submenu under ncRNA (that also includes ncRNA).

**Comment by obsidian83** [comment]
Yes, submenu sounds good, definitely would keep the interface neater

**Comment by nathandunn** [comment]
Steps to do:
- [ ] add menu options for DraggableHTMLFeatures
- [ ] add menu options for the equivalent Canvas Features
- [ ] add to change menu type
- [ ] add types for each to the database / code

**Comment by nathandunn** [comment]
@obsidian83  for ncRNA we use SO:0000655 http://www.sequenceontology.org/browser/current_release/term/SO:0000655

to describe the transcript, so I'm guessing the sub-classes would be:
 - [x] guide_RNA http://www.sequenceontology.org/browser/current_release/term/SO:0000602
 - [x] RNase_P_RNA: http://www.sequenceontology.org/browser/current_release/term/SO:0000386
 - ) 
- [ ] SRP_RNA_gene (SO:0001269) 
- [ ] tRNA_gene (SO:0001272) 
- [ ] lncRNA_gene (SO:0002127) 
- [ ] enzymatic_RNA_gene (SO:0002180) 
- [ ] RNase_MRP_RNA_gene (SO:0001640) 
- [ ] telomerase_RNA_gene (SO:0001643)
- [ ] piRNA_gene (SO:0001638)
- [ ] scRNA_gene (SO:0001266))
- [ ] **tmRNA_gene (SO:0001271)** ( I need to see what this one should be)
