### ISSUE TITLE
Under organism tab the column named Sequences should be Ref sequences

### ISSUE THREAD

**Issue by selewis** [GMOD/Apollo#240]
Be consistent throughout the application in naming things

**Comment by nathandunn** [comment]
only found one instance

**Comment by monicacecilia** [comment]
@nathandunn you know I have refreshed (and cleaned the cache) a few dozen times today. The suggested enhancement is not yet incorporated. I believe @selewis means that the column labeled as "Sequences" in this table (third column, all the way to the right) should instead be labeled as "Ref Sequences". 
As shown here, the tab labeled "Ref Sequence" is displayed correctly. 

![screen shot 2015-04-14 at 5 43 04 pm](https://cloud.githubusercontent.com/assets/1714621/7150313/efe8f928-e2cd-11e4-9ba8-6a8f19454bb7.png)

**Comment by nathandunn** [comment]
deploye fixed . ,. should be working

**Comment by monicacecilia** [comment]
It is working. :heavy_check_mark:
