### ISSUE TITLE
Merging 2 Apollo instances

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#2408]
Hi!
Historically, on BIPAA I chose to deploy 1 Apollo instance for each organism we host. It works well, but not entirely satisfying (eating too much cpu/ram as the number of orgs increases)
So I would like to switch to a single instance for all organisms.
Is there already a recommended method that would allow me to export the annotation data from the running Apollos and import it into the new single Apollo, without losing any metadata (comments, dbxrefs, names, symbols, creation dates, owners, ...)?
The users are the same between all the instances (already synchronised automatically based on our ldap).
If there's no such method, would you recommend to do it using the api, or sql queries?

**Comment by nathandunn** [comment]
@abretaud in theory if you export a GFF3 and import it again it again using the [perl script](https://github.com/GMOD/Apollo/blob/develop/tools/data/add_features_from_gff3_to_annotations.pl) (which uses the web services) it should be identical :

This is verified by these tests:
https://github.com/GMOD/Apollo/blob/develop/test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy#L3540-L3897

In practice, I'm a bit worried about the gene-level annotation being preserved, so I'm working on this: https://github.com/GMOD/Apollo/pull/2401

**Comment by abretaud** [comment]
As I wanted to preserve as much as possible (including the history of each feature), I ended up writing this script which performs the transfer at the SQL level: https://github.com/abretaud/migrate_apollo_db/

It seems to work fine on my test instances, I'll use it for real in the coming days I think :crossed_fingers:  (unless I find other bugs)

(Still interested in a python replacement for the perl script that uses the api though, but no so urgent for me now)

FYI @hexylena

**Comment by hexylena** [comment]
Tons of sql? :heart_eyes: amazing. That is low key horrifying that it works but amazing!

**Comment by abretaud** [comment]
To be honest I was the first to be surprised that it worked, but it does :unicorn: :rainbow:

**Comment by nathandunn** [comment]
Wow.  I was expecting something worse.    I'll have to share it with a few folks that would be interseted in this structure. 

Thanks.
