### ISSUE TITLE
Get rid of extraneous Ref Sequence text field above the tabs

### ISSUE THREAD

**Issue by selewis** [GMOD/Apollo#241]
It's redundant with what's under the Ref Sequence tab and is confusing because as a user I assumed it must be somehow someway different.

**Comment by nathandunn** [comment]
@monicacecilia   FYI . . we should talk about this behavior.

**Comment by nathandunn** [comment]
We are replacing this with simply listing "current organism".

**Comment by monicacecilia** [comment]
looks great! :dancer:

note to self: remember we no longer use check boxes to select reference sequences but just clicks, and "shift" and "command" keys to select multiple ones.
