### ISSUE TITLE
gene product should suggest names from other gene products (query all)

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2424]

**Comment by obsidian83** [comment]
<img width="940" alt="Screenshot 2020-04-07 at 10 51 14" src="https://user-images.githubusercontent.com/10411470/78655506-0454b100-78be-11ea-8096-4ded8655b51a.png">
<img width="784" alt="Screenshot 2020-04-07 at 10 51 34" src="https://user-images.githubusercontent.com/10411470/78655509-0585de00-78be-11ea-8cc0-a105630008ac.png">
<img width="683" alt="Screenshot 2020-04-07 at 10 51 43" src="https://user-images.githubusercontent.com/10411470/78655511-061e7480-78be-11ea-9221-9d144e103f64.png">

These are the current interface in Artemis showing the Product Descriptions
