### ISSUE TITLE
for GO annotations: with/ from required for ISS / ISO / IMP evidences

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2426]

**Comment by obsidian83** [comment]
Hello Nathan, think it was IPI (protein interaction) and not IMP for the third with/from required evidence code.

The full list is IPI, ISS, ISO, IGI, ISA, IBA, IC - with/from required

IEP, ISM, IGC, IBA - with/from recommended. but, not required,

Thanks Dave

**Comment by nathandunn** [comment]
Thanks @obsidian83  I just remade those changes.
