### ISSUE TITLE
On annotations tab make it clear what ref sequences the current list refers to

### ISSUE THREAD

**Issue by selewis** [GMOD/Apollo#243]
1. The ref sequence text field label should be changed to "Ref Sequence(s)"
2. The field shouldn't be brought up empty, but (in grayed-out text) should say "All"
3. The second search field should be labeled "Annotation Name" (whatever you end up calling it, but use the same words consistently) to match the column heading.
Generally speaking never have an unlabeled text field, far too amiguous.

**Comment by monicacecilia** [comment]
1. Is awfully similar to #242 ... 
2. Not yet available.
3. Not yet available. 

... and if they are, I can't understand it. All I see is "Search" on the search field and an empty field on the "Ref Sequence" search box of the "Annotations" tab.

**Comment by nathandunn** [comment]
should be available now

**Comment by monicacecilia** [comment]
2. and 3. are working well. :heavy_check_mark:
See #242 for 1.
