### ISSUE TITLE
Annotation details panel refreshes self twice on initial load

### ISSUE THREAD

**Issue by selewis** [GMOD/Apollo#244]
I typed "lalalala" into the description text field and after switching back an forth to other annotations the entire panel disappeared!!

**Comment by selewis** [comment]
Wait, could be wrong. Problem seems to be that there are no "details" for pseudogenes. That's not right.

**Comment by selewis** [comment]
Need a much clearer indication of what gene/transcript row in the table is currently being shown in the details panel. Perhaps an arrowhead pointing at the matching row.

**Comment by selewis** [comment]
The clicking behavior genes on this panel is heterogeneous. Sometimes it opens and closes, other times it selects. Rather see a right/down arrowhead or a plus/minus symbol of the hierarchy.

**Comment by selewis** [comment]
Details panel needs a lot of reworking, missing information right now. Needs to replace that stupid dialog box...

**Comment by nathandunn** [comment]
I can't reproduce this locally . . . I think itwill work.

**Comment by nathandunn** [comment]
Still problematic.

**Comment by nathandunn** [comment]
I don't get this behavior via localhost.  However, I do get it with a remote server (icebox)  . . with or without tomcat . . and on the USDA server.  

Nathan

**Comment by nathandunn** [comment]
with working websockets it does this ALL the time now

**Comment by monicacecilia** [comment]
@nathandunn Yes, all the time. Is this "expected behaviour" now?

**Comment by nathandunn** [comment]
@monicacecilia  The expected behavior is that it works by loading data once.  What @selewis  was experiencing was that it loaded the annotator panel once and then it decided it wanted to refresh itself.  It also did this with the genomic browser.   My guess is that you are not seeing it, because I'm sure I would have heard about it from you already ;)

**Comment by monicacecilia** [comment]
hehehe... either that or it is that "flash" thingy that happens at super-lightning speed and I just got used to seeing... :smirk:

**Comment by monicacecilia** [comment]
a'ight... I'm happy with this and it goes buh-bye now. :dancer:
