### ISSUE TITLE
problem with Isoseq bam file

### ISSUE THREAD

**Issue by lfaino** [GMOD/Apollo#2440]
Dear Developer,

I get this error when I load an IsoSeq bam file generated by using GMAP software and Minimap2
Any idea what maybe wrong?

[apollo.pdf](https://github.com/GMOD/Apollo/files/4491610/apollo.pdf)

 Thanks 
Luigi

**Comment by nathandunn** [comment]
Could you provide some additional details?   

- The trackFile.json
-  javascript console logs
- tomcat (or equivalent) logs (Catalina.out typically) 
- Also, does it load with JBrowse (I would guess not)?
- What is your system setup (are you running a proxy?)?

**Comment by lfaino** [comment]
Hi Nathan,

I found the problem. it was permission issue on the bam file.

sorry about this
Luigi
