### ISSUE TITLE
calls loadUsers and gets because no users are present

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2443]
When we load up with a login, `loadUsers` is called, probably for the user and groups tab, but as there are no credentials, the call fails.  

What we should only call this after login or on loading of the page if we have a valid admin user.

**Comment by fbemm** [comment]
Might be unrelated but I currently get "Incorrect login" with docker setup using 'admin@local.host' and 'password'

**Comment by fbemm** [comment]
Guess this is again a proxy redirect issue again. Fixes in the docs however are not working.

**Comment by fbemm** [comment]
```
2020-05-04 21:39:57,699 [Catalina-utility-1] WARN  apollo.UserService  - User exists felix.bemm@kws.com and can not be added again.
Not phoning home
<6>Deployment of web application directory [/var/lib/tomcat9/webapps/ROOT] has finished in [41,619] ms
2020-05-04 21:40:03,465 [http-nio-8080-exec-1] WARN  apollo.PermissionService  - Failed to authenticate user
2020-05-04 21:40:57,107 [http-nio-8080-exec-2] WARN  apollo.PreferenceService  - No user present, so using the client token
2020-05-04 21:40:57,236 [http-nio-8080-exec-3] WARN  apollo.PermissionService  - No user provided, please log in
2020-05-04 21:40:57,257 [http-nio-8080-exec-6] WARN  apollo.PermissionService  - Failed to authenticate user

```
@nathandunn this should go into another issue correct?

**Comment by nathandunn** [comment]
@fbemm  Are you able to see a login screen?

**Comment by nathandunn** [comment]
This can probably go in the previous issue, or probably best to post here: https://groups.google.com/a/lbl.gov/forum/#!forum/apollo

**Comment by nathandunn** [comment]
But all of those are normal warnings for not being able to login.  Not being able to connect to the server is a bigger problem.

**Comment by fbemm** [comment]
Yes, and after entering the defaults it says Incorrect login! in red.

**Comment by nathandunn** [comment]
@fbemm  Can you open another issue or use the google group?  I'll have more advice there.

**Comment by fbemm** [comment]
Will do first thing in the morning with everything that I collected so far on that!

**Comment by nathandunn** [comment]
Sounds good. 

Everything looks normal in there. 

You may wish to see what other environmental variables you have set as well as what the outgoing and incoming network traffic is.
