### ISSUE TITLE
loadLink with loc=some_name

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#2444]
Hi,
In one of my webapp, I'd like to add links with urls like the following to let users open apollo on a specific organism (`Some organism`), and at a specific position using the name of a feature indexed in the jbrowse data dir by generate-names.pl (`FOOBAR026052-RA`)

```
https://bipaa.genouest.org/apollo/annotator/loadLink?organism=Some%20organism&loc=FOOBAR026052-RA
```

Selecting the organism works great, but the loc parameter has no effect (unless I set it to a `chr1:1..1000` value, but that's not possible in my case).

With an url like this, I get redirected to another url like that: `https://bipaa.genouest.org/apollo/annotator/index?clientToken=<random_id>` (so, no loc parameter)

Of course, when writing manually the FOOBAR026052-RA id in the jbrowse search box, it is found, so I don't think the problem is on the jbrowse side.

Do you have any clue why it's not working?

**Comment by nathandunn** [comment]
Hmmm . . . . having it use the search explicitly might be hard.   The track service could iterate and do a linear scan and search and scan.  I do this for track services already, but usually I specify the track. 

I think this would work unless you have a ton of tracks with no way to specify them. 

We could also do this by flagging specific annotations.  Just let me know.

**Comment by abretaud** [comment]
Wouldn't it be possible to just pass it to jbrowse and let it find the correct position?

**Comment by nathandunn** [comment]
If it can be passed into the JBrowse url, then probably.

**Comment by abretaud** [comment]
yep, it's the loc url param I use for standalone jbrowse

**Comment by nathandunn** [comment]
Okay, I will see what I can do.    I can make it part of RC2 2.6.0

**Comment by abretaud** [comment]
that would be great, thanks :)
(by the way, I just release python-apollo 4.2)

**Comment by nathandunn** [comment]
Note to self:

`loadLink` is a method on the AnnotatorController.   The current method sets a preference and then calls "setCurrentSequenceLocation". 

What we'll have to do instead is to do a `index?search=XXX` instead and pass that directly to the client with `selectedSequence = "searchString"` `minRegion = null`, `maxRegion = null` and `forceUrl = true`

**Comment by nathandunn** [comment]
public URL:

http://localhost:8080/apollo/6791/jbrowse/index.html?loc=Group3.9:1174809..1194693&tracks=Official%20Gene%20Set%20v3.2

this also works:

http://localhost:8080/apollo/6791/jbrowse/index.html?loc=GB53650-RA&tracks=Official%20Gene%20Set%20v3.2

logged in URL:

http://localhost:8080/apollo/annotator/loadLink?loc=Group3.9:1174809..1194693&organism=6791&tracks=Official%20Gene%20Set%20v3.2

we should be able to pass in:

http://localhost:8080/apollo/annotator/loadLink?loc=GB53650-RA&organism=6791&tracks=Official%20Gene%20Set%20v3.2

**Comment by nathandunn** [comment]
http://localhost:8080/apollo/annotator/loadLink?loc=GB55650-RA&organism=6791&tracks=Official%20Gene%20Set%20v3.2

also works

**Comment by abretaud** [comment]
Thanks for the fix @nathandunn! It works great
