### ISSUE TITLE
GFF3 / FASTA - optimize performance

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#245]
We are doing a lot of loops within loops . . . just need a better join query here so that there is a single query.  

        for (Sequence eachSeq in sequenceList) {
            List<FeatureLocation> featureLocationList = sequenceService.getFeatureLocations(eachSeq)
            if (featureLocationList.size() == 0) {
                log.debug "No features on sequence ${eachSeq}"
                continue
            }
            for (FeatureLocation entity in featureLocationList) {
                if (entity.feature.class.cvTerm == MRNA.cvTerm) {
                    // getting only MRNA features; might want to extend to other features in future
                    Feature featureToWrite = Feature.findByUniqueName(entity.feature.uniqueName)
                    listOfFeatures.add(featureToWrite)
                }
            }
        }

**Comment by nathandunn** [comment]
@deepakunni3   What I would typically do would be: 

select distinct f from FeatureLocation fl join fl.sequence s join fl.feature f where s in (:sequenceList)

something like that.  If you need to filter by feature type you could do f.ontologyId in (:ontologyIdList). .  . . something like that.

**Comment by deepakunni3** [comment]
@nathandunn  This has been implemented

**Comment by nathandunn** [comment]
@deepakunni3   Looks good . . . !
