### ISSUE TITLE
GFF3 / FASTA - workaround the popup

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#246]
Somehow we need to not have it issues another popup.  Chrome likes to block popups and you have to specifically disallow.  

Possible better solution:
- issue a meta refresh to the link for the response 
- create a link with a key.  Store the link and temp file in a session object.  Delete the tmp file and link when done.  (similar to the 1.0 solution).

**Comment by nathandunn** [comment]
nathandunn@Apollo/09b2867

**Comment by nathandunn** [comment]
@deepakunni3   If you want to take a look at what I did differently here is the commit: nathandunn/Apollo@09b2867

**Comment by deepakunni3** [comment]
@nathandunn Looks good.

**Comment by monicacecilia** [comment]
@nathandunn You mean a second popup, correct? Because it still creates one with the dialog box. Please clarify? If so, then it is only producing one and if this is expected, it is ok.

**Comment by nathandunn** [comment]
@monicacecilia   Right the second one was being blocked by default by the browser and you had to explicitly ask Chrome to "unblock".  That is now fixed.
