### ISSUE TITLE
merge in origin master 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#247]
There are a few dependencies on this.

**Comment by nathandunn** [comment]
I'll do a first-pass of this on Monday and then have @cmdcolin  review.

**Comment by nathandunn** [comment]
Related to #248 request

**Comment by cmdcolin** [comment]
I merged the #248 so it should be ready now. I think some things that still need checking out are things like

In help menu

Version does not work
Web Services API link does not work

Dunno if we want to update those. It might be cool if the Version one is sort of a popup is similar to jbrowse, but not essential.
