### ISSUE TITLE
Any tips for Apollo reverse proxy with HAProxy?

### ISSUE THREAD

**Issue by mattsarrasin** [GMOD/Apollo#2495]
Hello,

I've got a working instance of Apollo that is reverse-proxied by HAProxy with SSL offloading. However, I've been struggling to get "User-created Annotations" to work properly because the proxy is refusing websocket connections, and I'm getting 403 errors with /apollo/stomp/*/xhr_streaming and /apollo/stomp/*/xhr. I've tried quite a lot of different HAProxy configuration tweaks at this point and consulted previous issues involving HAProxy to no avail, so I was wondering if anyone would be willing to share any insight on working configurations. I can also provide additional information on request.

Thanks in advance!

**Comment by nathandunn** [comment]
Yeah, this is a pretty comon problem.  Have you looked here? 

https://groups.google.com/a/lbl.gov/forum/#!forum/apollo

Also some good info here: https://genomearchitect.readthedocs.io/en/latest/search.html?q=proxy&check_keywords=yes&area=default

If its still a problem, please post to that group. 

Closing this for now.

**Comment by nathandunn** [comment]
if you're unsure what I mean, feel free to ask here.
