### ISSUE TITLE
missing wheel

### ISSUE THREAD

**Issue by epaule** [GMOD/Apollo#2499]
I had a problem with wheel not being installed after the setuptools step happens.
adding

RUN pip3 install wheel

fixes it. But I am not sure if it is an isolated case and need to be wrapped in

https://github.com/GMOD/Apollo/blob/c0b2bc5a7941916729cf6357e8dc0d22b46711c7/Dockerfile#L65

**Comment by nathandunn** [comment]
I pushed a couple of commits to dev.  Can you let me know if those fix it.   

For some reason travis is having problems, so hopefully those are intermittent.
