### ISSUE TITLE
firefox + windows makes weird layout for the annotations tab 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2502]
> I recently upgraded to version 2.6.1 of Apollo. In Firefox on Windows I get a weird layout for the Annotations tab, see the attached picture. There should be a list of 25 annotations, but instead I see a gray bar. Curiously, it works fine on Firefox/Linux and Edge/Windows. I already tried running it in a Private Window to avoid caching issues, but that didn’t help.

from R. Ohm

**Comment by suryasaha** [comment]
I also see this in Firefox 83.0 on Mac OS Catalina 10.15.7

**Comment by nathandunn** [comment]
Sorry, this was the original error @suryasaha : 

![image](https://user-images.githubusercontent.com/751274/101063215-6c3fc200-3547-11eb-8111-80b43606e064.png)
 
basically they were having the annotations tab being called within its own iFrame.   Is this what you were seeing as well?

**Comment by nathandunn** [comment]
This was the original view from R. Ohm:

![image](https://user-images.githubusercontent.com/751274/101064250-a1004900-3548-11eb-8173-2d77597f0d84.png)

**Comment by nathandunn** [comment]
@suryasaha  if you make the window vertically taller does it fix it? 

Also, are you running it within an iFrame?

**Comment by suryasaha** [comment]
@nathandunn Making the window taller brings the header into view but don't see any annotations. Its not running within an iframe. Now if I start zooming out, the annotations start to appear

Short window
![image](https://user-images.githubusercontent.com/1084749/101079252-3b768180-3575-11eb-982d-6adb7293842e.png)

Tall window
![image](https://user-images.githubusercontent.com/1084749/101079317-534e0580-3575-11eb-8afa-af958151c664.png)

But if I zoom out, the annotations start to appear...
90% zoom
![image](https://user-images.githubusercontent.com/1084749/101079827-ff8fec00-3575-11eb-85ec-6cbde7b15086.png)

50% zoom
![image](https://user-images.githubusercontent.com/1084749/101079894-11718f00-3576-11eb-8eaf-eae90711f6f1.png)

**Comment by nathandunn** [comment]
@suryasaha  I can see if I can't make the details window ONLY appear (as opposed to be ing blank) if something is selected, but for now, you need to provide sufficient vertical space

todo: 
- [ ] make detail panel height zero if not selected and animate when selected
- [ ] allow deselection when single-selecting an already selected version

**Comment by nathandunn** [comment]
@suryasaha  it should be better now . . the details panel was obscuring it . . Now it will only show up if you have something selected.  In the develop branch.  Let me know how it works.

**Comment by suryasaha** [comment]
Finally set up a test VM to check out 2.6.2. Works great! @nathandunn 
Cheers!
