### ISSUE TITLE
non-default translation table causes problems when running with docker

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2504]
FYI @MoffMade 

This is only a problem if we use docker.    If we switch from 1 to 11, we see the alternate starts / stops and proteins rendered perfectly if running on bare metal when specifying organisms.

**Comment by nathandunn** [comment]
This is because the call to get_translation actually fails:

http://demo.genomearchitect.org/Apollo-staging/16302876191584817967/AnnotationEditorService

with post:

`{"track":"Lorac","operation":"get_translation_table"}`

returns:

```
{"clientToken":"16302876191584817967","start_proteins":["I","M","L","V"],"translation_table":{"ATT":"I","CTT":"L","GTT":"V","TAT":"Y","AAA":"K","CAA":"Q","AAC":"N","CAC":"H","GAA":"E","AAG":"K","CAG":"Q","GAC":"D","GAG":"E","TGA":"*","TGC":"C","TCA":"S","AAT":"N","TCC":"S","TGG":"W","CAT":"H","TCG":"S","GAT":"D","TTA":"L","TGT":"C","TTC":"F","TCT":"S","TTG":"L","TTT":"F","AGA":"R","CGA":"R","AGC":"S","CGC":"R","ACA":"T","CCA":"P","GGA":"G","ACC":"T","AGG":"R","CCC":"P","CGG":"R","GGC":"G","GCA":"A","ACG":"T","CCG":"P","GCC":"A","GGG":"G","GCG":"A","ATA":"I","AGT":"S","ATC":"I","CTA":"L","CGT":"R","ACT":"T","CTC":"L","ATG":"M","GTA":"V","CCT":"P","TAA":"*","GGT":"G","CTG":"L","GTC":"V","TAC":"Y","GCT":"A","GTG":"V","TAG":"*"},"track":"Lorac","stop_proteins":["*"],"operation":"get_translation_table"}
```

For the same one against docker:

`{"track":"Lorac","operation":"get_translation_table"}: `

there is NO response.

**Comment by MoffMade** [comment]
I'm wondering if the Dockerfile is properly copying the web-app directory recursively or not. I'm doing a little bit of testing on my fork to see if I can remedy it. The tables are found from `web-app/translation-tables/` in bare metal, right?

**Comment by nathandunn** [comment]
@MoffMade  They are just below the exploded WAR directory, so I think you are right.   I see that tha tis what is happening.  

What I don't know is why I'm setting translational_table (maybe its ignored), and if the code is coming through correctly.   . . Testing now.

**Comment by nathandunn** [comment]
It is failing here and swallowing the error: 

https://github.com/GMOD/Apollo/blob/develop/src/groovy/org/bbop/apollo/sequence/SequenceTranslationHandler.groovy#L141

So, I'm guessing that it is because the pathname is `.`. 

Adding this:

```
  String currentPath = new File(".").absolutePath
                println "current path ${currentPath}"
                def fileList = FileUtils.listFiles(new File("."),new NameFileFilter("ncbi_1_translation_table.txt"),TrueFileFilter.INSTANCE)
```

We get:

```
current path /.
```

What we really want is servlet context if we can get it, not necessarily the current path.   Working on fix.

**Comment by MoffMade** [comment]
It does seem to fix the issues I was having!

**Comment by nathandunn** [comment]
Awesome, thanks for reporting!

**Comment by MoffMade** [comment]
Any idea when 2.6.2 will be released, or can this fix be back-patched to 2.6.1 so I can tie our update to a release image rather than a develop/latest?

**Comment by nathandunn** [comment]
I can try and make a 2.6.2 release this or next week

**Comment by nathandunn** [comment]
@MoffMade  I just pushed a tag: https://github.com/GMOD/Apollo/releases/tag/2.6.1-a

Let me know if that is sufficient.  

I have some work to do with a few other groups that may trigger further changes, but if you need a full-on release of 2.6.2, I can do that as well.

**Comment by MoffMade** [comment]
I can work with that! I just wanted a tagged image to pull rather than develop. Thank you!
