### ISSUE TITLE
More help when adding GO annotation

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#2507]
I've update to 2.6.1, and am testing the new annotation panel.
I have to say I'm confused when trying to add a GO term for one of my mrna: I managed to add a go term, an evidence, but now I don't know what to write in the "With" and "Reference" fields.
Would it be possible to add some help on what is expected in each field?
Maybe by adding tome tooltips/mouseover text to each field?

Same applies to gene product/provenance panels.
By the way the "info" link in the gene product panel seems to be dead

**Comment by nathandunn** [comment]
- [ ] I'll add this link for GO reference:  http://geneontology.org/docs/go-annotations/
- [ ] I'll fix the link on the gene product column
- [ ] In terms of how to annotate Gene Product, this should be similar to GO, I can add the link there.
- [ ] the provenance is just an explanation of why you annotated a field. 

Both the Gene Product and GO were special requests for the VeupathDB community (which I think is part of i5K), so you may have more info on it.

**Comment by nathandunn** [comment]
@abretaud  Let me know if those changes help.  Happy to add further info / links.
