### ISSUE TITLE
"Save track data" missing in 2.0, requires get_data_adapters api

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#251]
The function to "save track data" directly from the user created annotations track menu requires the get_data_adapters api.

**Comment by nathandunn** [comment]
{"data_adapters":[{"permission":4,"key":"Chado","options":"display_features=false"},{"permission":1,"key":"GFF3","options":"output=file&format=gzip"},{"permission":1,"key":"FASTA","data_adapters":[{"permission":1,"key":"peptide","options":"output=file&format=gzip&seqType=peptide"},{"permission":1,"key":"cDNA","options":"output=file&format=gzip&seqType=cdna"},{"permission":1,"key":"CDS","options":"output=file&format=gzip&seqType=cds"}]}]}

**Comment by deepakunni3** [comment]
@nathandunn Export data from user created annotations now works. 
Ready for feedback and testing.

**Comment by nathandunn** [comment]
@deepakunni3  When I export GFF3 I see the following.  Are you sure you pushed your code? 

![screen shot 2015-04-22 at 5 52 46 pm](https://cloud.githubusercontent.com/assets/751274/7288566/7402196a-e918-11e4-8baf-887440f198e6.png)

**Comment by deepakunni3** [comment]
@nathandunn  Whoops.  Its pushed now.

**Comment by nathandunn** [comment]
@deepakunni3   Much better!  . . .

**Comment by monicacecilia** [comment]
"Save track data" option is not available on the Apollo2 instance at icebox.lbl.gov/Apollo2/
It is possible to export GFF3 and FASTA using the tool on the "Ref Sequence" tab from the panel on the right, but the option is not available from the Uc-A area track label. 

![screen shot 2015-05-01 at 2 27 33 pm](https://cloud.githubusercontent.com/assets/1714621/7437653/3f042ab2-f00e-11e4-8162-615793a76126.png)

**Comment by nathandunn** [comment]
{"operation":"get_data_adapters","track":"Annotations-chrII","data_adapters":[{"permission":1,"key":"GFF3","options":"output=file&format=gzip&type=GFF3"},{"permission":1,"key":"FASTA","data_adapters":[{"permission":1,"key":"peptide","options":"output=file&format=gzip&type=FASTA&seqType=peptide"},{"permission":1,"key":"cDNA","options":"output=file&format=gzip&type=FASTA&seqType=cdna"},{"permission":1,"key":"CDS","options":"output=file&format=gzip&type=FASTA&seqType=cds"}]}]}

VS

    {"data_adapters":[{"permission":4,"key":"Chado","options":"display_features=false"},{"permission":1,"key":"GFF3","options":"output=file&format=gzip"},{"permission":1,"key":"FASTA","data_adapters":[{"permission":1,"key":"peptide","options":"output=file&format=gzip&seqType=peptide"},{"permission":1,"key":"cDNA","options":"output=file&format=gzip&seqType=cdna"},{"permission":1,"key":"CDS","options":"output=file&format=gzip&seqType=cds"}]}]}

**Comment by nathandunn** [comment]
Weird, am not seeing anything significantly different unless the it is the user permissions, which makes more sense:

{"operation":"get_user_permission","username":"ndunn@me.com","track":"Annotations-chrII","permission":70}

vs 

{"operation":"get_user_permission","username":"ndunn@me.com","track":"Annotations-chrII","permission":15}

**Comment by monicacecilia** [comment]
:zap: The option to "save track data" is now available, so I will close this issue. BUT, there is a problem with the export, reported at #403
