### ISSUE TITLE
ReturnAllOrganisms flag for UpdateOrganismInfo API Endpoint

### ISSUE THREAD

**Issue by MoffMade** [GMOD/Apollo#2511]
Can we get the same interaction with the ReturnAllOrganisms option for the UpdateOrganismInfo API so that we can choose to not have the entire organism list returned for the Update calls, similar to the function in the AddOrganism and DeleteOrganism endpoints?

**Comment by nathandunn** [comment]
I think that makes sense (I was thinking of doing that as well).

**Comment by nathandunn** [comment]
You have write access now @MoffMade , so go wild.  @rbuels  is admin so he can add more people as maintainers / write access as necessary.
