### ISSUE TITLE
Creating annotation from BLAT search creates annotation on wrong scaffold

### ISSUE THREAD

**Issue by Esetz** [GMOD/Apollo#2514]
Hi,

I added BLAT search to my Apollo instance a few days ago. The search in itself works perfectly. So does the "Save sequence" option available after the search, however, when I try to create annotations from the BLAT search results, it creates all the annotations on one scaffold per organism (the longest one, in each organism), at the exact positions found by the BLAT search.

I don't know if I'm clear, so here's an example : let's say I BLAT a sequence and find a match at coordinates X1-->X2 on scaffold N. If I try to create an annotation from this match, it'll create an annotation at coordinates X1-->X2 on scaffold A, which is the longest scaffold of the organism. It does this for all my species, so it's most likely not related to my genomes.

Also, when I click on "Create annotation", nothing's written in ```catalina.out```, which is why I didn't upload it.
 
Do you have any hints about what could be causing this ?

Thanks in advance !

**Comment by nathandunn** [comment]
@Esetz  Yeah, its not sending in the sequence through when it creates the annotation.

**Comment by nathandunn** [comment]
@Esetz it should be fixed now.  Please let me know either way.

**Comment by nathandunn** [comment]
It is on the develop branch, so just redownload the latest or wait an hour for the docker build.

**Comment by Esetz** [comment]
@nathandunn Alright, thanks, I'll test it and get back to you !

**Comment by Esetz** [comment]
Sorry I wasn't able to test your fix earlier, but it works fine ! Thank you !
