### ISSUE TITLE
Bug with Bacteria and Phage track in Functional Annotation 

### ISSUE THREAD

**Issue by mlmoore9** [GMOD/Apollo#2518]
I ran the functional annotation on my phage genome and there is an issue with the Bacteria and Phage track. Here is a screenshot of the error. It should be a pretty average size genome. Please let me know if you need any more information and thank you for your help. 
<img width="420" alt="Screen Shot 2020-10-02 at 5 26 23 PM" src="https://user-images.githubusercontent.com/72285667/94978887-6f311e80-04d4-11eb-87bc-a5c2d2743bd7.png">

**Comment by nathandunn** [comment]
Do you get the same error if you load the track directly from JBrowse?

**Comment by cmdcolin** [comment]
Can probably increase chunkSizeLimit in your config file. That would be editing the trackList.json to have something like "chunkSizeLimit": "50000000" (that would be ~5mb, which you can even increase that). This says its downloading more than a megabyte of gene annotation data, which is probably totally fine. Probably jbrowse should increase it's default for this....

**Comment by cmdcolin** [comment]
Sometimes there are also cases where you can optimize gff3tabix loading so that it loads less data but I'd try increasing chunkSizeLimit first

**Comment by cmdcolin** [comment]
Note: increased the default in jbrowse dev branch...

**Comment by nathandunn** [comment]
@cmdcolin  is that a recommendation for me in all cases or @mlmoore9 in this case?

**Comment by cmdcolin** [comment]
Well, if you would like to fix this issue, you can

(a) Increase chunkSizeLimit in your gff3tabix track's config file
(b) Update to jbrowse dev branch which has increased the default chunkSizeLimit

**Comment by nathandunn** [comment]
I see. 

The current version of Apollo is 1.6.10 (I usually just update automatically)

If that isn’t sufficient, then the user could fix this by either setting this explicitly in the track file or setting the branch to dev in the apollo config:

https://genomearchitect.readthedocs.io/en/latest/Configure.html#jbrowse-plugins-and-configuration

**Comment by mlmoore9** [comment]
Hi Colin and Nathan,

Could either of you you explain how I would update to the jbrowse dev
branch with the increased chunksize limit? I have been accessing Apollo by
clicking the icon on the Galaxy main page.

I also tried modifying the track's config file but couldn't find any lines
referencing chunksize, so I wasn't sure what to add.

Thank you for your help!
Best,
Madeline

**Comment by nathandunn** [comment]
You should be able to temporarily edit the chunkSizeLimit in JBrowse / Apollo by clicking on the track and “Edit Config”. 

You may need to add it explicitly if not already there (I haven’t tried it).

@cmdcolin

That being said, it would be worth contacting your admin and referring them to this thread so that they can change it explicitly for everyone. 

What site are you accessing it from?

**Comment by cmdcolin** [comment]
@nathandunn  Unfortunately it is not possible to edit chunkSizeLimit through the GUI edit config


>>I also tried modifying the track's config file but couldn't find any lines


There is likely not an entry for chunkSizeLimit there by default, but if you added a line that increases it I think that would work

So if you can see a track config such as

```
{
"label": "trackid",
"urlTemplate": "file.gff.gz",
"type": "CanvasFeatures",
/* etc */
}
```

Might not look exactly  like that but just find your track, and then make it say

```
{
"label": "trackid",
"urlTemplate": "file.gff.gz",
"type": "CanvasFeatures",
"chunkSizeLimit": 50000000
/* etc */
}
```

That would make the limit 50mb and would likely never be hit. If you have the gff3 file you are using I could also test to see if there is anything that is making it request such a large amount by default too, even fetching 1MB is sort of abnormal which is what you are seeing.

**Comment by MoffMade** [comment]
Howdy! I think this may for our CPT Apollo instance? Are you experiencing the issue on https://cpt.tamu.edu/apollo ?

**Comment by mlmoore9** [comment]
Hi Cory!

Yes, I receive this error when using Apollo through the CPT site (at the
link you included).

**Comment by MoffMade** [comment]
I checked your organism, it looks like it was created before we implemented the increase in chunkSize as the others mentioned above. Unfortunately we don't have a way to retroactively apply the fix to your track but if you re-run the functional workflow again it should re-create it with the proper settings to load.

Thanks for your understanding, and if you need further help on this please email me at cory.maughmer@tamu.edu or you can open issues at our forked repository (https://github.com/TAMU-CPT/Apollo)

**Comment by mlmoore9** [comment]
Thanks Cory. Sounds good, I'll run the annotation again.
