### ISSUE TITLE
add GZIP compression to FASTA and GFF3 downloads

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#252]

**Comment by nathandunn** [comment]
@deepakunni3   Not sure if you wanted this one or not  . . for 2.0.1 (unless something changes).

**Comment by cmdcolin** [comment]
Added via #471. I'd test it with large files exports just to be sure but it seems like it is using an efficient gzip output stream

**Comment by nathandunn** [comment]
@cmdcolin  Great thanks.  Now we just have to get the rest of it efficient ;)

**Comment by nathandunn** [comment]
To test:  confirm that downloads are gzip files.     Seemed to work for me.

**Comment by monicacecilia** [comment]
It is confirmed. :dancer:
