### ISSUE TITLE
(2d) web_services need to be defined based on organism

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#253]
Re-enable #237  after this one.

**Comment by nathandunn** [comment]
@childers  FYI

**Comment by nathandunn** [comment]
Related to #219

**Comment by nathandunn** [comment]
@cmdcolin  I ended up doing this one as a result of doing #337 . .  if you want to verify / comment / close

**Comment by cmdcolin** [comment]
Looks good, cross-validated against #337
