### ISSUE TITLE
Sync Name to Gene/Transcript behavioral UX Issues

### ISSUE THREAD

**Issue by MoffMade** [GMOD/Apollo#2531]
Fasta + GFF track used to test these things [org_data.zip](https://github.com/GMOD/Apollo/files/5490690/org_data.zip)

Steps to reproduce:
- create organism from FASTA
- add GFF CANVAS track from the gff3, with gene as top level feature type
- promote any of the evidence pieces as a gene
- right click -> Open Annotation on the gene annotation
- Click on mRNA (this usually triggers the first panel crash below)
- Change mRNA name in panel, hit enter then Sync Name to Gene (this would generally trigger the second crash)

Issues we have found: 

- [x] Accessing the Annotation Editor for mRNA annotations
Sometimes when clicking on "Open Annotation" on a feature through Right Click menu, sometimes the editor window does not load directly unless you open the gene first and THEN the mRNA, console shows a js error. Transient and difficult to reproduce, seems to happen mostly when recently logged in. Several members have reported this from both Chrome and Firefox, and varying levels of frequency. I missed nabbing the console message when I was able to reproduce it but Jolene reported ```Uncaught TypeError: c is undefined```

- [x] Annotation window closes with a js error in console after syncing name from either gene or transcript to the other (although the change does seem to sync correctly if reloaded), again seemingly transient. This doesn't crash every time. Tested on Chrome
```
Uncaught zt {e: Rh, f: "Exception caught: (TypeError) : Cannot read property 'C' of null", g: null, __gwt$backingJsError: Error: Exception caught: (TypeError) : Cannot read property 'C' of null
    at gj.dj [as Ib] (annot…, a: kDb}
```

- [ ] Sometimes, when changing name in gene or transcript or also syncing name to other feature, the list will refresh but changes will not be displayed unless list is refreshed again (either full page refresh or changing tab to tracks and back for example)

- [ ] mRNA name changes will be immediately displayed on the Annotation Track in jBrowse but not updated in the Annotations list in the Apollo UI

- [ ] gene or mRNA change can be input and accepted, but will not refresh in the UI, allowing for users to try again but the UI will not accept the change again until reloaded.

**Comment by nathandunn** [comment]
The error is there because we don't set a gene in the annotatorPanel.geneSelected before we check the transcript. 

The first two should be fixable, but the last 3 maybe be related to other things, and may not be directly fixable. 

The workaround for the error below is to explicitly open the annotator panel and click on the gene you want, but that is less than convenient.  

```
TranscriptDetailPanel.java:332 Uncaught TypeError: Cannot read property 'getChildAnnotations_1_g$' of undefined
    at TranscriptDetailPanel_1_g$.checkSyncButton_1_g$ [as checkSyncButton_3_g$] (TranscriptDetailPanel.java:332)
    at TranscriptDetailPanel_1_g$.updateData_18_g$ [as updateData_22_g$] (TranscriptDetailPanel.java:248)
    at updateAnnotationInfo_1_g$ (AnnotatorPanel.java:706)
    at AnnotatorPanel$2$1_1_g$.onResponseReceived_6_g$ [as onResponseReceived_105_g$] (AnnotatorPanel.java:324)
    at Request_2_g$.fireOnResponseReceived_0_g$ [as fireOnResponseReceived_1_g$] (Request.java:250)
    at RequestBuilder$1_1_g$.onReadyStateChange_0_g$ [as onReadyStateChange_1_g$] (RequestBuilder.java:412)
    at XMLHttpRequest.<anonymous> (XMLHttpRequest.java:329)
    at apply_0_g$ (Impl.java:247)
    at entry0_0_g$ (Impl.java:306)
    at XMLHttpRequest.<anonymous> (Impl.java:72)
```

**Comment by nathandunn** [comment]
@MoffMade  this fixed the first two I think. 

For better versions of the other ones, I think you'll need to wait for Apollo 3 with JB2 integration as the mixture between 10yo technologies doesn't always yield the desired affect ;) \
