### ISSUE TITLE
(1d) create user migration script using web services

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#254]
Create a script to use web services to extract user's from web_services and insert them into a local 2.0 databases.

@childers @littlebunch

**Comment by deepakunni3** [comment]
The main issue here is that Apollo 1.0.x web services API does not have any methods to get users.

**Comment by nathandunn** [comment]
My suggestion is that we write a sql script to pull the data from the 1.0 database.

**Comment by nathandunn** [comment]
@deepakunni3   I am pulling users from the database using groovy (though one could use whatever).  It seems to work with the older JDBC correctly.   The rest should be pretty straightforward.  Will leave the rest to you.

**Comment by deepakunni3** [comment]
@nathandunn Great. This is really helpful!

**Comment by monicacecilia** [comment]
@nathandunn  :+1:

**Comment by nathandunn** [comment]
Realized that there is really no  mapping between the two.   Users in WA1 is ID, username, password.  Users in WA2 is username (now an email), firstname, lastname, password.   

Better to just import a CSV file.

**Comment by nathandunn** [comment]
@cmdcolin   Can you test to make sure this works when you have a chance.  The script is "add_users.groovy"

Thanks.

**Comment by nathandunn** [comment]
FYI @childers

**Comment by childers** [comment]
Thanks for the heads up!

**Comment by cmdcolin** [comment]
There was some weird things with this. For example, you have to pass two passwords, one for authentication on the API, one for the new user. That was not working and 502aae tried to start fixing it

**Comment by nathandunn** [comment]
@cmdcolin   Can this be closed?

**Comment by nathandunn** [comment]
@cmdcolin   Re-open if there is still a problem.
