### ISSUE TITLE
search by location name yields error, should use name instead

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2544]
Generated from here: https://groups.google.com/a/lbl.gov/g/apollo/c/2jEE4ngA6To

**Comment by mictadlo** [comment]
Hi, I use this link `https://apollo.nbenth.com/annotator/loadLink?loc=gene.12886.0.3.p1:72134951..72166050&organism=334799&tracks=Annotation-CDS,Annotation%20v3.02` and it jumps to the right chromosome but it does not zoom into the gene or it does not highlight it.

What did I miss?

Thank you in advance,

Michal

**Comment by garrettjstevens** [comment]
I don't think that type of link will highlight the region. As for the boundaries being wrong, is `gene.12886.0.3.p1` the name of the annotation? If so, what happens if you leave off the `:72134951..72166050`?
