### ISSUE TITLE
(2d) create annotation migration script using web services

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#255]
create annotation migration script using web services.  

Pull off features from USDA remote server and install them locally. 

Dependent on  #253  . . . 

FYI: @childers @littlebunch

**Comment by deepakunni3** [comment]
Progress so far:
It is easy to login to Apollo 1.0.x via curl but the task becomes near impossible when trying through groovy (RESTClient).
Additionally, ran into a problem of Internal Server Error 500 indicating permission issues. This has to do with the authentication_class.

**Comment by nathandunn** [comment]
@deepakunni3   You can review and close when you have a chance.    I ended up using curl in both instances.  
In *theory* you can do "a simple command".execute() . . . in practice it looks like you have to do:  ["a","simple","command"].execute().

This could be parallelized, as well, but for now I think it works well enough. 

Please close if you think its working.

**Comment by nathandunn** [comment]
@cmdcolin  @deepakunni3  Also note the "Apollo1Operations" and the "Apollo2Operations".  Just to simplify the refactoring.  Still debating if these should stay here or go into the tools scripts.   Anyway . . I think that this is fine for now.

**Comment by nathandunn** [comment]
@cmdcolin  @deepakunni3   Closing this.
