### ISSUE TITLE
doc: organism search database naming

### ISSUE THREAD

**Issue by alpapan** [GMOD/Apollo#2550]
The correct way to implement both blat and blast is to ensure that the 'search database' for the organism is:
a) full path to the 2bit file
b) blast databases are suffixed on the 2bit file

e.g. this
```
naturalis_ragout2_final.2bit
naturalis_ragout2_final.2bit.nhd
naturalis_ragout2_final.2bit.nhi
naturalis_ragout2_final.2bit.nhr
naturalis_ragout2_final.2bit.nin
naturalis_ragout2_final.2bit.nog
naturalis_ragout2_final.2bit.nsd
naturalis_ragout2_final.2bit.nsi
naturalis_ragout2_final.2bit.nsq
```

to create them, do this:
```
faToTwoBit fasta fasta.2bit
makeblastdb -dbtype nucl -in fasta -out fasta.2bit
```

any other way and either blat or blast will (silently) fail

**Comment by nathandunn** [comment]
Alexie,

I’m only doing this automatically via docker.  Where you creating a suggestions for doc? 

If you want to add this bit to the doc, you can just edit directly to create a PR here: https://github.com/GMOD/Apollo/blob/develop/docs/Configure.md#search-tools <https://github.com/GMOD/Apollo/blob/develop/docs/Configure.md#search-tools>

And I can merge it into the doc.    I think this is good clarification, though. 

Nathan
