### ISSUE TITLE
apollo-config.groovy missing

### ISSUE THREAD

**Issue by mictadlo** [GMOD/Apollo#2563]
Hi,
I can not find `apollo-config.groovy` in Apollo 2.6.2 in order to add BLAST in the following way:

```
apollo{
   sequence_search_tools   {
      blat_nuc      {
         search_exe = "/usr/local/bin/blastn"
         search_class = "org.bbop.apollo.sequence.search.blast.BlastCommandLine"
         name = "Blast nucleotide"
         params = "-num_threads 2"
         tmp_dir = "/efs/apollo/tmp"

      }
      blat_prot      {
          search_exe = "/usr/local/bin/tblastn"
          search_class = "org.bbop.apollo.sequence.search.blast.BlastCommandLine"
          name = "Blast protein to translated nucleotide"
          params = "-num_threads 2"
          tmp_dir = "/efs/apollo/tmp"
      }
   }
}
```

How is it possible to add BLAST internally to Apollo?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
You copy the sample-<database>-config.groovy to apollo-config.groovy in the top-level directory of apollo.  

The explicit blast  / blat instructions are here.   But basically you need to install blast or blat locally and then point to it. 

https://genomearchitect.readthedocs.io/en/latest/Configure.html?highlight=blast#search-tools

**Comment by nathandunn** [comment]
An example of the search tab is available as an example here: http://demo.genomearchitect.org/Apollo2/annotator/loadLink?loc=Group1.25:45027..404447&organism=3836&tracks=Official%20Gene%20Set%20v3.2

demo@demo.com / demo

**Comment by mictadlo** [comment]
I can't see `sample--config.groovy` I only see:
```
Apollo-2.6.2$ ls -1 sample-*
sample-docker-apollo-config.groovy
sample-h2-apollo-config.groovy
sample-mysql-apollo-config.groovy
sample-postgres-apollo-config.groovy

```

**Comment by nathandunn** [comment]
sorry, I meant `sample-postgres-apollo-config.groovy` etc. etc. I think it swallowed my tag
