### ISSUE TITLE
Option to mark a gene as partial in Apollo

### ISSUE THREAD

**Issue by uliboehme** [GMOD/Apollo#2565]
Similar to Artemis it would be good to have an option in Apollo to mark a gene as partial. Attached is a screenshot showing the database version of Artemis with the tick boxes 3'partial, 5'partial. 
![Artemis_partial](https://user-images.githubusercontent.com/25098772/107479776-7dbecf00-6b73-11eb-81f8-1a3c4f7d057f.png)

**Comment by nathandunn** [comment]
This may be worth doing in Apollo directly now in order to make sure that the API is directly sufficient.
