### ISSUE TITLE
(4h) search annotations by user needs to be visible

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#257]

**Comment by nathandunn** [comment]
@childers   . . . FYI

**Comment by nathandunn** [comment]
I think that I'm going to do this as a "template" page.  Links will go back into the annotator .  . quick way to do it and an easier way to let user's start adding their own "admin" pages.

**Comment by nathandunn** [comment]
? . . but I'm almost done

**Comment by monicacecilia** [comment]
@nathandunn how do I test this? 
- in annotations tab? there is not an option to enter user
- in user tab? there is not a list of annotations that each user has created
- in admin tab? no search fields

**Comment by nathandunn** [comment]
@monicacecilia   This is annoying as it is there half of the time and half the time now.  Partly because I restricted the search to admins only.   So, 

Q: is it admins only? 

I'll try to get it always showing up.

**Comment by monicacecilia** [comment]
Drop-down menu to search annotations by user is available and visible under "Annotations" tab.
