### ISSUE TITLE
Tracks menu display problems when using tabix + canvasFeatures for bed files

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#2571]
Apollo version: 2.1.1-SNAPSHOT
Jbrowse version: 1.16.9

We are working on setting up bed tracks using tabix and canvasFeatures (see https://github.com/GMOD/jbrowse/issues/1511 for background). The display works fine for Jbrowse 1.16.9. In Apollo, the 'Tracks' menu in the right hand Apollo panel does not load.

<img width="1368" alt="staging-apollo" src="https://user-images.githubusercontent.com/5487172/107793330-6585b600-6d13-11eb-9752-d3bf47c6f4e7.png">

We get the following Javascript console error when logging on to Apollo, when turning on any tracks (via the Jbrowse-style track menu), and/or when selecting the 'Tracks' menu in the right hand Apollo panel. I _don't_ get the errors when I remove the bed tracks from trackList.json.

<img width="796" alt="js-console-log" src="https://user-images.githubusercontent.com/5487172/107793272-54d54000-6d13-11eb-954c-40e1d2c427cc.png">

Server log: No stacktrace is posted on the server logs. 

Any ideas what might be going on? Thanks!

**Comment by nathandunn** [comment]
Can you paste in the trackList.json for the section you are trying to add?

**Comment by mpoelchau** [comment]
Actually, @cmdcolin just solved the problem - I needed to add `"type": "CanvasFeatures"` to the trackList. All console errors disappeared, Tracks show up, styling is fine in this Jbrowse version (1.16.9). Thanks @cmdcolin!
