### ISSUE TITLE
allow obsolete to be set

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2574]
This is already part of the feature code, however, it is not set anywhere.  However, no one is explicitly asking for it yet.  

@uliboehme how does Artemis use `obsolete`?

- [ ] add "isObselete" to interface in detail?
   - [ ] add "showObsolete" to features in AnnotatorPanel
   - [ ] double-check the export for GFF3
   - [ ] add service method that sets for whatever feature you happen to be on

**Comment by uliboehme** [comment]
@nathandunn Obsolete is an option in the database version of Artemis. An obsolete gene is still visible in the database. One can open the feature editor of an obsolete gene in Artemis and see all the details. It is useful for genes that were erroneously made obsolete! The GFF exporter we use for Artemis has an option to not export obsolete genes.
