### ISSUE TITLE
delete_annotations_from_organism.groovy

### ISSUE THREAD

**Issue by ajulian0416** [GMOD/Apollo#2576]
Running ` docs/web_services/examples/groovy/delete_annotations_from_organism.groovy -destinationurl http://localhost:8080/apollo -organismname Swiss_hellem_v1`

yields

`org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:`
`/.../opt/Apollo-2.6.2/docs/web_services/examples/groovy/delete_annotations_from_organism.groovy: 2: unable to resolve class groovyjarjarcommonscli.Option`
` @ line 2, column 1.`
   `import groovyjarjarcommonscli.Option`
   `^`
`1 error`

Unsure of how to resolve.

**Comment by ajulian0416** [comment]
Commenting out the offender line as follows removed the error.

`\\import groovyjarjarcommonscli.Option`

**Comment by nathandunn** [comment]
Cheers.  Feel free to create PRs from any of these.

**Comment by nathandunn** [comment]
I did push this into the main codebase though
