### ISSUE TITLE
Cannot load CDS gff to annotation using add_features_from_gff3_to_annotations.pl

### ISSUE THREAD

**Issue by ajulian0416** [GMOD/Apollo#2577]
When I run add_features_from_gff3_to annotations.pl on a converted tblastn-gff file as follows
` /home/.../opt/Apollo-2.6.2/tools/data/add_features_from_gff3_to_annotations.pl -U localhost:8080/apollo -u 'xxx' -p 'xxx' -i ~/Swiss_hellem/new_assembly_data/BLAST/Swiss_E_hel/Swiss_hel_og_prot.tblastn.6.gff -t match -e match_part -o "Swiss_hellem_v1"`
my user added annotations are present. However, when I run add_features_from_gff3_to_annotations.pl on a prodigal gene prediction gff file as follows
`/home/.../opt/Apollo-2.6.2/tools/data/add_features_from_gff3_to_annotations.pl -i usa_reordered.filtered.sorted_1k.chromo.reoriented_long.gff -U localhost:8080/apollo -u 'xxx' -p 'xxx' -o Swiss_hellem_v1 -t gene
`
there are no user added annotations present.

How can I resolve this?

**Comment by nathandunn** [comment]
Can you post a sample from your GFF3? 

My guess is that you need to use -t mRNA but that is just a guess. 

I would also look at this: https://pypi.org/project/apollo/ <https://pypi.org/project/apollo/>


Nathan

**Comment by ajulian0416** [comment]
![image](https://user-images.githubusercontent.com/72114871/107861088-f9857980-6e08-11eb-9823-7deac9e44ce7.png)

Here is sample of my file. I will look into the provided links.

**Comment by nathandunn** [comment]
In this case the other project wouldn’t necessarily help. 

If you are only encoding the CDS, I would use that as a filter and/or change the CDS type to mRNA and use -t mRNA


Nathan

**Comment by ajulian0416** [comment]
All the features in the file are CDS, so I will write up a quick script that replaces CDS with mRNA and run with the -t mRNA flag. Will report the results.

**Comment by ajulian0416** [comment]
The annotations are now appearing, so the workaround has seemed to be successful. However this is a repeated error message that is thrown at the beginning as follows

![image](https://user-images.githubusercontent.com/72114871/107861512-dd370c00-6e0b-11eb-892a-7f3e3594508f.png)

**Comment by nathandunn** [comment]
Could you post the new GFF3 (a least a few lines) and the command you ran it with? 

Nathan

**Comment by ajulian0416** [comment]
The new GFF3 file
![image](https://user-images.githubusercontent.com/72114871/107861881-6c452380-6e0e-11eb-82ea-9b8c7312bf79.png)

The command
`/home/julian/opt/Apollo-2.6.2/tools/data/add_features_from_gff3_to_annotations.pl -i check.gff -U localhost:8080/apollo -u xxx -p xxx -o "Swiss_hellem_v1" -t mRNA`

**Comment by nathandunn** [comment]
I don't have any idea off hand, as everything you are doing looks correct.  Short answer is use this library with arrow:

https://pypi.org/project/apollo/

    arrow annotations load_gff3 myorganism test1.gff3

All python and supported my multiple organisms (including this one).

**Comment by ajulian0416** [comment]
I will give it a go. Thank you for your assistance.
