### ISSUE TITLE
Change Track Name

### ISSUE THREAD

**Issue by spficklin** [GMOD/Apollo#26]
We are trying to manage multiple instances of WebApollo using the same user database.  We are handling it in this way:

1)  Each instance of WebApollo has it's own config.xml file with the annotation_track_name element customized with a unique project name.
2)  Reference sequences are prepared using the extract_seqids_from_fasta.pl and are given a prefix (-p option)  that matches the project name.  This ensures that if there are two or more sequences from different projects with the same name that there won't be any conflicts.

But, I am having a problem with JBrowse in that it doesn't want to show the annotation track.  This happens because JBrowse calls the AnnotationEditorService servlet and passes the track name as "Annotations" rather than the project name that was listed in the config.xml file.  WebApollo returns that read permissions is not available for the track named 'Annotations-[seq name]'.   It really should be checking the permission for the track named '[Project Name]-[seq name]'.

The problem seems to occur because the track name 'Annotations' is hard-coded on line 56 and 155 of the add-webapollo-plugin.pl perl script.  If I edit the trackList.json file and change the track name to be the project name then JBrowse works just fine.  

Would it be possible to add a command-line argument to that script to allow us to set the track name?

Thanks

**Comment by nathandunn** [comment]
Need to make sure we're handling this case.  I largely left the "Annotations-" prefix, but I like Stephen's solution better.

**Comment by monicacecilia** [comment]
@nathandunn  says that we can store the "new" name in the database, which will over-ride the display.

**Comment by cmdcolin** [comment]
This has a workaround in 1.0 and 2.0 doesn't require any workarounds at all. Suggest closure

**Comment by nathandunn** [comment]
Agreed.
