### ISSUE TITLE
Duplicate username produces error in 2.0

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#260]
Fairly easy to reproduce. Unfortunately the user does not get the error message so that is annoying, just printed on server side.

**Comment by cmdcolin** [comment]
Connected to trello card https://trello.com/c/xpE51ch2/442-check-for-duplicate-username-in-user-panel

**Comment by nathandunn** [comment]
just need to add a check and an error . . should be an easy fix

**Comment by nathandunn** [comment]
@cmdcolin   Is this ready or are you still working on it?

**Comment by cmdcolin** [comment]
Should be ready (just shows an alert box now and avoids the error)

**Comment by nathandunn** [comment]
Not the best user experience (it eliminates the fields!!), but should be fine for now.

**Comment by cmdcolin** [comment]
Ya and uses alert boxes. I guess I will try and iteratively improve ux

**Comment by nathandunn** [comment]
Good enough for now.  Its kind of an edge-case, so I'm not worried.   I'd grab one of the other "Important" bugs for 2.0.0.

**Comment by monicacecilia** [comment]
sweet! the warning message popped up and I was not able to create a duplicate user. :dancer: :+1: 
![screen shot 2015-05-01 at 3 03 49 pm](https://cloud.githubusercontent.com/assets/1714621/7438077/5fbd09fe-f013-11e4-8e19-348b9942e641.png)
