### ISSUE TITLE
Option to stop recalculating the CDS structure when creating gene as well as lock CDS structure

### ISSUE THREAD

**Issue by uliboehme** [GMOD/Apollo#2604]
Apollo recalculates gene structures when dragging and dropping an existing gene model into the user-created annotation area. If one only wants to add functional annotation to a gene, this is not ideal. It would be great if there is an option in the drop-down menu that says: don’t change the gene structure.

**Comment by nathandunn** [comment]
What aspects of the gene structure are changing?   

Are you talking about the gene itself, or the underlying components? 

Currently we recalculate the gene position based on the isoforms and we don’t carry up any of the gene’s functional annotations.

**Comment by uliboehme** [comment]
I'm talking about the gene itself. When dragging and dropping the gene in the user created annotation area, UTRs, or the start codon are sometimes recalculated.

**Comment by nathandunn** [comment]
@uliboehme  I see.  

You can actually set a flag `use_cds_for_new_transcripts` so that it never recalculates the CDS:

https://genomearchitect.readthedocs.io/en/latest/Configure.html#main-configuration

This was developed for the WhipWorm project.  I think it is global, though. 

That being said, are the recalculated CDS's wrong or just different than the evidence suggests?

**Comment by nathandunn** [comment]
Accidentally closed.

**Comment by uliboehme** [comment]
Thanks for looking into this and for letting me know about the flag. Attached is an example of a recalculation. In this case, it is just wrong. Is this maybe a bug?

Ideally, VEuPathDB would like to use Apollo for functional annotation. A possible pipeline would be to check if coordinates have changed, if they have not changed only functional annotation will be extracted. For such cases where the user only wants to add functional annotation an option in the drop-down menu that says "keep the gene structure" would be ideal. Hope this makes sense. 

![Screen Shot 2021-04-08 at 07 15 52](https://user-images.githubusercontent.com/25098772/113976675-5c0f5a80-9839-11eb-9787-282bd4152467.png)

**Comment by nathandunn** [comment]
@uliboehme  I think that this is the case you want: https://github.com/GMOD/Apollo3Server/issues/87

I should have moved it over here earlier.  But having a track treated as evidence is the primary point here.  Having the ability to do only functional annotation is also definitely on the road map.  In that world, if you pull from the official gene set (one or more tracks designated as such), the model is imported as is.  I tried to do this with Apollo2, but there were too many architectural changes required to make this happen.

With regard to that bug, that definitely looks like a bug.  Yikes.   I would advocate closing this in favor of https://github.com/GMOD/Apollo3Server/issues/87 and the creating a new issue for the above bug.

**Comment by nathandunn** [comment]
@uliboehme  I created a new issue here: https://github.com/GMOD/Apollo/issues/2606
