### ISSUE TITLE
Bad calculation of ORF

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#2606]
Bad calculation of ORF. 

From https://github.com/GMOD/Apollo/issues/2604#issuecomment-815486355

![](https://user-images.githubusercontent.com/25098772/113976675-5c0f5a80-9839-11eb-9787-282bd4152467.png)

I'm not sure the reason for recalculation away from the methionine. 

@uliboehme  can you provide the full sequence and gff3 to me (over email is fine), just in case there is something I'm missing there?

**Comment by uliboehme** [comment]
Hi Nathan, VEuPathDB is currently not using the most recent version of Apollo. There is a plan to update to the newest version. Maybe best to close this issue for now and in case this also happens in the newest version of Apollo reopen it again. Hope this sounds ok.

**Comment by nathandunn** [comment]
@uliboehme  So in this case it is inferring that there may be a partial start here.   As if there was a partial start it would potentially build a longer protein sequence it chooses that. 

I'm wondering if it would make sense to build out an option to disallow this calculation by default.  I guess it depends if you allow for partial starts to be calculated, but we also have no way to add a partial start at this point unless we added a "remove partial start" option, or an "allow partial start" option.

**Comment by nathandunn** [comment]
So, these are all highly related and all from @strumpfe :
- #2129
- #2133
- #1303 / #2111  (maybe better for JB2)

@uliboehme  I think that calculating an "optimal" solution, might be pretty doable (i.e. no partials), but curious how your group would like to do that. 

My suggestions would be:
- have a default setting where it globally will or will not check for partials
- in the drop-down, in addition to the setLongestORF function, we also have a setOptimalORF function

Let me know what you and the group think.

**Comment by uliboehme** [comment]
Thank you for providing the related tickets. Providing a setOptimalORF function would be perfect. So, this ticket probably can be moved together with #2129.

**Comment by nathandunn** [comment]
closing in favor of #2129
