### ISSUE TITLE
arrow/python-apollo not present in docker image

### ISSUE THREAD

**Issue by abretaud** [GMOD/Apollo#2620]
Hi,
It looks like the docker image from https://hub.docker.com/r/gmod/apollo does not contain the arrow binary anymore, nor the python modules that are supposed to be installed in https://github.com/GMOD/Apollo/blob/develop/Dockerfile#L73
Is it the real Dockerfile used by https://hub.docker.com/r/gmod/apollo ? I don't have access to the build logs to check

**Comment by garrettjstevens** [comment]
Hi @abretaud,

Yes, that is the Dockerfile that gmod/apollo uses, but I'm seeing the same same thing as you. I can see setuptools, apollo, etc. being installed in the build logs, but when I run the image they're not there anymore. I'm not sure what's going on. Do you happen to know a version of the docker image where this did work?

**Comment by abretaud** [comment]
The problem seems to be the call to [build.sh](https://github.com/GMOD/Apollo/blob/develop/Dockerfile#L81) which [removes `/apollo`](https://github.com/GMOD/Apollo/blob/develop/docker-files/build.sh#L8) where the python modules are installed (in `/apollo/.local`)
I guess the pip3 install could be made as the root user as anyway a global install is fine no?
