### ISSUE TITLE
Cannot create features.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#263]
This is a complex issue that includes many things, thus the generic Title. There may be more things, but I am starting with these.

1. Cannot create a new **_repeat_region_** nor a new **_transposable_element_** anywhere in the genome
2. Cannot create a second **_gene_** feature after a **_gene_** feature has been created in the same region, with complete or partial overlap, UNLESS, the next **_gene_** feature is being created in the opposite strand. This is preventing the possibility to create isoforms.
3. Cannot create a **_gene_** feature after a different type of feature has been created in the same region, with complete or partial overlap, UNLESS, the **_gene_** feature is being created in the opposite strand. After this, no other **_gene_** features (partial or complete overlap) can be created if they are being created on the same strand.
4. It is not possible to duplicate **_gene_** features on the User-created Annotations area.

**Comment by nathandunn** [comment]
@monicacecilia   I'm going to close this one in order to split up the separate issues.
