### ISSUE TITLE
URL to fetch PubMed ID trows 404 error.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#264]
Hopefully this is an easy one!

When trying to add a PubMed ID on the Information Editor, Apollo replies with an error warning the curator that the PMID is invalid (see image below). I know the IDs I am using are valid and current so this is an error on the Apollo side. I checked and it is throwing a 404 in the back as follows:

<code>
GET http://icebox.lbl.gov/WebApollo2/ProxyService?proxy=eutils&operation=fetch&db=pubmed&id=20167027 404 (Not Found)
</code>
<code>ReferenceError: errorHandler is not defined {stack: (...), message: "errorHandler is not defined"}
</code>

## Current outcome:
Note the box with the warning, and the actual paper on the right.
![screen shot 2015-04-14 at 1 12 36 pm](https://cloud.githubusercontent.com/assets/1714621/7146510/dc4323aa-e2a8-11e4-8909-fbb3fcf3adad.png)

## Expected outcome: 
![screen shot 2015-04-14 at 1 21 42 pm](https://cloud.githubusercontent.com/assets/1714621/7146560/4fd2c988-e2a9-11e4-9ab1-01c21c84808c.png)

### While we are here:
Could I kindly ask that you please update the header of this box to reflect the word "PubMed" instead of "Pubmed" (please note caps). Thanks!

**Comment by nathandunn** [comment]
I need to re-enable ProxyServiceController from ProxyService  . . . we can use a similar formula for the GOLR stuff as well. 

http://icebox.lbl.gov/WebApolloDemoStaging/ProxyService?proxy=eutils&operation=fetch&db=pubmed&id=PMC3013679

**Comment by monicacecilia** [comment]
It works now.
