### ISSUE TITLE
imported annotations not populating annotations tab

### ISSUE THREAD

**Issue by jaspwn** [GMOD/Apollo#2641]
Hi,

I am very new to apollo but would like to improve annotations of my favourite gene families, but when I add a gff track from an online database the annotations within are not appearing in the searchable annotations menu. Only the annotations that I have dragged up to the user-created annotations track appear.

My workflow at the moment is import my organism genome, add a gff annotation track, add RNAseq evidence track and then annotate.

Here is the gff track configurations:

`{"storeClass":"JBrowse/Store/SeqFeature/GFF3", "urlTemplate":"raw/1718121519122424116.gff", "label":"1718121519122424116", "type":"JBrowse/View/Track/HTMLFeatures", "style":{"className":"feature"}, "key":"1718121519122424116", "topLevelFeatures":"mRNA", "apollo":{"source":"upload", "type":"GFF3", "topType":"mRNA"}}`

Any help would be much appreciated.

![annotations](https://user-images.githubusercontent.com/19551203/154472997-7faef434-c34f-4926-8d98-2fe2c7812789.png)

**Comment by hexylena** [comment]
They're not annotations yet, just a track of data. If you right click/create annotation (or drag them up to the yellow bar) then they'll become proper annotations.

**Comment by jaspwn** [comment]
Thanks for the feedback, is there a way import the data track as annotations so I do not have to drag each one up? Or alternatively is there a way to search the names in the data track so I can find the gene models that I want to fix more easily?

**Comment by hexylena** [comment]
I've automated that in the past with scripting, I'm not sure there's a built in way to do that. You should be able to search track values if they've been indexed (sorry not super helpful)

**Comment by garrettjstevens** [comment]
You can load a GFF3 from the command line using the `arrow organisms add_organism` command. See here for more details: https://github.com/galaxy-genome-annotation/python-apollo/blob/master/docs/commands/organisms.rst

**Comment by jaspwn** [comment]
Hi, sorry to get back to this after all this time but I was wondering if you could provide more insight to how you did this via scripting @hexylena ?

Or @garrettjstevens I am not sure how I would use arrow organisms add_organism to load a gff3 file? These are the options I can use for that command.

`--blatdb TEXT      Server-side path to 2bit index of the genome for Blat
--genus TEXT       Genus
--species TEXT     Species
--public           Should the organism be public or not
--metadata TEXT    JSON formatted arbitrary metadata
--suppress_output  Suppress output of all organisms (true / false) (default
                   false)

-h, --help         Show this message and exit.
`

**Comment by garrettjstevens** [comment]
@jaspwn I can't remember what I was trying to say in my last comment, but what you actually probably need is [`arrow annotations load_gff3`](https://github.com/galaxy-genome-annotation/python-apollo/blob/master/docs/commands/annotations.rst#load_gff3-command). You can use `arrow organisms add_organism` to add the organism first, or you can use an organism you've already created in the UI. You can see some examples of `load_gff3` [here](https://github.com/galaxy-genome-annotation/python-apollo/blob/master/bootstrap_apollo.sh).

**Comment by hexylena** [comment]
Yep, @garrettjstevens's got it, you need the `load_gff3` subcommand for that.

**Comment by jaspwn** [comment]
Thanks both. Perhaps this needs to be another thread (or forum search) but as I’m running this as a docker container could you provide advice about how to run that command or what script I might add it to?

Sorry, I’m very much a novice when it comes to this.

**Comment by hexylena** [comment]
Sure @jaspwn you can just do:

```
arrow init
```

to setup the connection, it can be run from outside of the container. You'll need your apollo address where it's accessible and username/password. After that you can invoke the `arrow organism load_gff3 <path-to-gff3>` command which will use your connection details to talk to your apollo server.

**Comment by jaspwn** [comment]
Ah amazing! Works exactly how I need it! Thanks @hexylena & @garrettjstevens for the step through!

For future novices I had to install python-apollo

`pip install apollo`

Have my apollo docker container running, then run

`arrow init`

One trick was getting the url exactly right - mine was run locally so I had to input 

`http://localhost:8888`

Then finally

`arrow annotation load_gff3 ORGANISM /path/to/file.gff`

And now it my annotations appear in the User-created Annotations track and their names are now searchable in the Annotations tab!

**Comment by hexylena** [comment]
Fantastic, glad you got it working @jaspwn !

**Comment by jaspwn** [comment]
Thanks both. Perhaps this needs to be another thread (or forum search) but as I’m running this as a docker container could you provide advice about how to run that command or what script I might add it to?

Sorry, I’m very much a novice when it comes to this.
