### ISSUE TITLE
Upgrade to more modern versions of dependencies?

### ISSUE THREAD

**Issue by jorvis** [GMOD/Apollo#2647]
I'm using RHEL 8.5 and am struggling through a sea of dependencies to get Apollo running.  For example, just doing the basic first step yields major version issues:

```
$ ./apollo run-local
/usr/bin/which: no gradle in (/export/.sdkman/candidates/grails/current/bin:/home/jorvis/.sdkman/candidates/grails/current/bin:/home/jorvis/.local/bin:/home/jorvis/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin)
/export/.sdkman/candidates/grails/current/bin/grails
Grails version: 5.1.7
Grails version 5.1.7 not supported.  Only grails 2.5.5 supported so using local ./grailsw instead
Using gradlew

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.15'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Gradle version: 
Node Version: 16
node version 6 to 13 must be installed.  Please install an updated version of node.js by following the instructions appropriate for your system https://nodejs.org/en/download/package-manage
```

So here Grails needs to go from 5.1.7 -> 2.5.5, Java is far too new to even be recognized in version numbers, and even Node has to go back several versions.

I get that it can be difficult to keep up with especially major version changes so this ticket could be a feature request with understanding.  For now it seems like it might be too much work to get it running.

**Comment by hexylena** [comment]
Docker is also a good option here! We have a couple containers available, an official and a few unofficial ones. It'll avoid the sea of dependencies problem.

```
docker run -d -it \
    -e APOLLO_ADMIN_EMAIL=admin \
    -e APOLLO_ADMIN_PASSWORD=pass \
    -p 8888:8080 gmod/apollo:latest
```

should get you up and running

**Comment by jorvis** [comment]
Understood, and thanks for the recommendation.
