### ISSUE TITLE
JBrowse events should set action in GWT Annotator

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#266]
In AnnotTrack.js  . . . on receiving websocket requests. 

should call:

    // TODO: handle errors without broadcasting
                                if (changeData.operation == "ERROR" && changeData.username == track.username) {
                                    alert(changeData.error_message);
                                    return ;
                                }
    + window.parent.handleGenomicBrowserAction(changeData); 

    // 
in Annotator.java (or MainPanel.java):

    // expose function statically:

    handleGenomicBrowserAction(String jsonData){
    
    }

need to have a converter that can pull the:
1 - operation
2 - original function
3 - features affected 
4 - user affected (we may not want to always propagate this if a different user)

**Comment by nathandunn** [comment]
FYI: @deepakunni3  @cmdcolin

**Comment by nathandunn** [comment]
This is needed to open up a lot of doors to other functionality.

**Comment by cmdcolin** [comment]
At least one thing that should happen is that the refseq should be updated on the GWT panel when it is changed inside the genome browser. This currently leads to some problems

![screenshot-localhost 8080 2015-04-21 12-10-42](https://cloud.githubusercontent.com/assets/6511937/7258542/e90fd96e-e822-11e4-931d-294efb1cbe30.png)

I already let deepak and nathan know about this

**Comment by nathandunn** [comment]
@cmdcolin  Where would I get access to these events?  Basically any time we change the location I want to make a call to the server.

**Comment by cmdcolin** [comment]
The jbrowse subscribe/publish system might work. I think these two events are sort of relevant:

'/jbrowse/v1/n/navigate' - any location change (side scroll) or refseq change
'/jbrowse/v1/n/visibleChanged' - any refseq change


to subscribe to the event, basically anywhere in the javascript you can say

    browser.subscribe('/jbrowse/v1/n/navigate',function() { /* your code here */ });

**Comment by nathandunn** [comment]
Yeah, I think that those will  work.  

Thanks,

Nathan

**Comment by nathandunn** [comment]
Worked like a charm thanks

**Comment by nathandunn** [comment]
Using this instead gives the current location.

                            browser.subscribe("/jbrowse/v1/n/navigate", dojo.hitch(this, function (currRegion) {
                                window.parent.handleNavigationEvent(JSON.stringify(currRegion));
                            }));

**Comment by nathandunn** [comment]
@cmdcolin  @deepakunni3   Just an FYI.  You can look at the commits and see how I do the communication from JBrowse to into the GWT Annotator.  

https://github.com/GMOD/Apollo/commit/e574f03df93805c88194a1ace8e77a36ad84d5db

and https://github.com/GMOD/Apollo/commit/721d063098af234ba7b47590b6b4ff980f9233a5 are the most relevant.

**Comment by cmdcolin** [comment]
The particular error that I had pointed to (the refseq updating) is fixed now

**Comment by monicacecilia** [comment]
AFAICS the details referenced on #219 and changes inside the genome browser such as the action to switch between reference sequences are being picked up by the panel on the right. 

One curious -and annoying- thing related to this (I think): this does not happen all the time, but at times, using a Mac, I am unable to get rid of the red bar that appears after a screen capture. 
* The red bar indicating the coordinates can be brought up by holding down the shift key.
* When you use the keyboard to capture a screenshot while using Apollo in a Mac, the red bar persists and you can eliminate it by holding the shift key momentarily. 
* On Apollo2, while viewing the JB window + panel on the right, the red bar does not always appear after screen captures, but when it does it is not possible to make it go away with the shift key. I have to reload the page. 
* If viewing Apollo2 on "Full-screen view", the behavior is as it was with 1.0.x. 
It seems curious, and I guess this likely also has to do with GWT and JB communication. 

It is absolutely not a show-stopper, but a rather annoying bug. It would be great if this did not happen.

![screen shot 2015-05-01 at 3 29 03 pm](https://cloud.githubusercontent.com/assets/1714621/7438382/3b791fc4-f018-11e4-89a1-ab19310404b5.png)

**Comment by nathandunn** [comment]
Can you open a separate issue for the new bug?  Thanks
