### ISSUE TITLE
load_gff3 miscalculates CDS

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#2662]
Hi Apollo team,

We are trying to use the python-apollo `arrow annotations load_gff3` command to load annotations to the user-created annotations track. It is changing the CDS locations of the model, both with and without the --disable_cds_recalculation option. 

Here is what a load without --disable_cds_recalculation looks like; the correct frame can be seen in the track below.

<img width="921" alt="Screenshot 2023-11-28 at 2 53 30 PM" src="https://github.com/GMOD/Apollo/assets/5487172/e24a8586-c836-43b3-9da0-76db710e2718">

The gff3 that was used to load the annotation has 6 CDS lines; the gff3 for the uploaded annotation has 12 CDS lines (even though the view shows only one CDS segment). Apollo also won't calculate a protein or CDS sequence on the uploaded annotation. 

Here is what a load _with_ --disable_cds_recalculation looks like (command: `arrow annotations load_gff3 --source https://apollo2-stage-node1-cbo.nal.usda.gov/apollo Anoplophora_glabripennis ~/Downloads/NW_019416298.gff3 --disable_cds_recalculation`)
<img width="881" alt="Screenshot 2023-11-28 at 2 50 01 PM" src="https://github.com/GMOD/Apollo/assets/5487172/59ae8001-2623-4fc9-afd0-cda05e92d6d1">

Again, the gff3 for the uploaded annotation in Apollo has 12 CDS lines instead of 6. Apollo also won't calculate a protein or CDS sequence on the uploaded annotation. 
 I'll note that if you run the same command multiple times, the single CDS will display in a different spot each time.  

If you load the annotation by dragging it up, it loads correctly: 

<img width="862" alt="Screenshot 2023-11-28 at 2 56 20 PM" src="https://github.com/GMOD/Apollo/assets/5487172/9069d5de-ac4a-4b9c-9b22-164046a93391">

This is happening for many (but not all) annotations in multiple assemblies/organisms. 

Some other observations:
- We haven't observed the problem for models with a single CDS/exon segment
- The underlying genomic sequence has lowercase nucleotides
- I tried using load_legacy_gff3, and that calculated the CDS correctly, but I'm unable to delete features when I load them with that method (Hibernate operation: could not execute statement; SQL [n/a]; ERROR: update or delete on table "feature" violates foreign key constraint "fk_8jm56covt0m7m0m191bc5jseh" on table "feature_relationship" Detail: Key (id)=(4858111) is still referenced from table "feature_relationship".; nested exception is org.postgresql.util.PSQLException: ERROR: update or delete on table "feature" violates foreign key constraint "fk_8jm56covt0m7m0m191bc5jseh" on table "feature_relationship" Detail: Key (id)=(4858111) is still referenced from table "feature_relationship".) 
 
I've attached "before" and "after" gff3s. (Used .txt extension because GitHub wouldn't let me upload otherswise)
[before.txt](https://github.com/GMOD/Apollo/files/13493815/before.txt)
[after-nocdsrecalc.txt](https://github.com/GMOD/Apollo/files/13493835/after-nocdsrecalc.txt)
[after.txt](https://github.com/GMOD/Apollo/files/13493837/after.txt)

* Provide the javascript console log output generated from the action. 
None.
 
* Provide the server log output generated from the action (typically ```catalina.out```).
 nothing is added to Catalina.out when I add the annotations.

**Comment by garrettjstevens** [comment]
Hi @mpoelchau. `arrow` is actually maintained by a separate group, so you'll need to file an issue in that repository here: https://github.com/galaxy-genome-annotation/python-apollo.

**Comment by garrettjstevens** [comment]
There's not an official method for loading GFF3s that we maintain. However, if there's some way to get the log from `arrow` of what requests are sent to the Apollo endpoint, I'd be happy to look at those and see if anything looks off.

**Comment by MonicaPoelchau-USDA** [comment]
Thanks @garrettjstevens ! I attached the output to a comment in the other issue: https://github.com/galaxy-genome-annotation/python-apollo/issues/60#issuecomment-1832602086. The only other output that the command issues is  the following warning (it does this for all arrow commands): 
`/Users/mpoelchau/Documents/programs/apollo-arrow-env/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020`
