### ISSUE TITLE
Add Search Sequence Track has results that jump around when Reverse Strand Protein Sequence

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#267]
First the error: 
The sequence search track should show an error reading "Region too large to search; zoom in to see detail" when the zoom is not sufficient to visualize the results of the search. However, even when I know a fragment has been found and it should be visible on the track, there is a level of zooming where the fragment marking the region where the string was found is not yet visible, but the error does not appear either. This is quite inconvenient for the user --- I spent a few minutes trying to find the region, thinking Apollo still had that error where amino acid strings were not visible. That was not the case, the region marking the match to the query was simply not visible. 
#### The arrow marking the match to my query should be visible here and it is not, neither is the error - (it has nothing to do with dark/light schema):

![screen shot 2015-04-14 at 2 29 26 pm](https://cloud.githubusercontent.com/assets/1714621/7147900/46028204-e2b3-11e4-8b80-e40983c3c6cd.png)
#### After zooming in a bit more the arrow is visible.

![screen shot 2015-04-14 at 2 31 34 pm](https://cloud.githubusercontent.com/assets/1714621/7147902/494a1486-e2b3-11e4-8d22-284fba6d2c06.png)

**Comment by monicacecilia** [comment]
Second... the unexpected options. 

The search track also has options for "Display mode" that are not available anywhere else. Was this deliberate? What are the reasons for these options? 

![screen shot 2015-04-14 at 2 43 39 pm](https://cloud.githubusercontent.com/assets/1714621/7148069/a2579a98-e2b4-11e4-893f-40877ab1285a.png)

**Comment by cmdcolin** [comment]
Those are CanvasFeatures options. Rare in the webapollo world since they
are not draggable

**Comment by nathandunn** [comment]
Jumps around.  Will take a look.

**Comment by nathandunn** [comment]
To clarify this bug (which is definitely a bug), when using the search sequence track, search results jump around and are not consistently in the same place.

**Comment by nathandunn** [comment]
I get good results for forward-strand AA and DNA and reverse-strand DNA.  For some bizarre reason, reverse-strand AA fails and drops strand info as well depending on the zoom level.

**Comment by nathandunn** [comment]
This is correct.  Top strand is protein search strand and bottom strand is dna search strand:

![screen shot 2016-12-01 at 11 24 14 am](https://cloud.githubusercontent.com/assets/751274/20808791/beea1836-b7b8-11e6-8373-d38872d425c4.png)

When I zoom in the strand is dropped and its in the wrong place.  No console errors.

![screen shot 2016-12-01 at 11 24 24 am](https://cloud.githubusercontent.com/assets/751274/20808790/bee93682-b7b8-11e6-83b8-32c7b07d94ad.png)

**Comment by nathandunn** [comment]
This is a JBrowse bug in the RegexSearch plugin.   #833.

**Comment by deepakunni3** [comment]
The RegexSearch plugin issue referenced above points to #833 of Apollo instead of JBrowse. 

The right issue is https://github.com/GMOD/jbrowse/issues/833

**Comment by nathandunn** [comment]
@deepakunni3  Thanks for noting it.   Fixed.

**Comment by monicacecilia** [comment]
Ok to link to the JBrowse issue, but let's keep open until solved.
