### ISSUE TITLE
extend mRNA causes 500 error

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#27]
Notes from Asela:

>Hello All,

>I have 4 different genomes running as separate webapollo instances on the same tomcat7 server. Issue 2 stated below occurred only on one instance, and the others are running just fine.

>1) jbrowse/data symlink : META-INF/context.xml -> WEB-INF/context.xml

>I continued to have problems with loading data when a symlink was used as the data folder. After googling, I copied the META-INF/context.xml file into WEB-INF folder and now it seems to have solved the issue. The idea was to add a xml file with  <Context allowLinking="true"> . (I am not sure whether this caused the error stated next.)

>2) extending mRNA sometimes success sometimes failure. 

>Now I am faced with this very peculiar issue when I try to extend the mRNA. Sometimes I am able to extend it and sometimes I cannot and It gives an error . Then when I flip the strand of the mRNA back and forth, then I can extend the mRNA. I played around with this issue for some time and narrowed it down to the following scenario with the corresponding error messages on the tomcat7 log.

        Action                                                                                                                                                               Error
    Drag gene from evidence track to User Annotation track                                             "POST /myGenome/AnnotationEditorService HTTP/1.1" 200 466 and "GET /myGenome/AnnotationChangeNotificationService?track=Annotations-                               myGenome&dojo.preventCache=1411432103780 HTTP/1.1" 200 1963
    Try to extend 5' end of mRNA                                                                                  "POST /myGenome/AnnotationEditorService HTTP/1.1" 500 1813
    Right click -> Flip strand                                                                                          "POST /myGenome/AnnotationEditorService HTTP/1.1" 200 439 and  "GET /myGenome/AnnotationChangeNotificationService?track=Annotations-myGenome&dojo.preventCache=1411433032843 HTTP/1.1" 200 2070
    Extend the new 5' end                                                                                             "POST /myGenome/AnnotationEditorService HTTP/1.1" 200 468 and "GET /myGenome/AnnotationChangeNotificationService?track=Annotations-myGenome&dojo.preventCache=1411433274515 HTTP/1.1" 200 2070
    Right click -> Undo extension                                                                                  "POST /myGenome/AnnotationEditorService HTTP/1.1" 200 35 and "GET /myGenome/AnnotationChangeNotificationService?track=Annotations-myGenome&dojo.preventCache=1411433312796 HTTP/1.1" 200 1280
    Right click -> Flip strand (now it is back to original form)                                            "GET /myGenome/AnnotationChangeNotificationService?track=Annotations-myGenome&dojo.preventCache=1411433413468 HTTP/1.1" 200 1277 and "POST /myGenome/AnnotationEditorService HTTP/1.1" 200 359 
    Now extend the 5' end (This was the original intent)                                                   "GET /myGenome/AnnotationChangeNotificationService?track=Annotations-myGenome&dojo.preventCache=1411433482249 HTTP/1.1" 200 1277 and "POST /myGenome/AnnotationEditorService HTTP/1.1" 200 369 

>Some times I can extend the mRNA in one go without all the flipping. While googling the error messages I came across this post that discussed a similar issue which is to do with sessions and tokens. https://github.com/jaredhanson/passport-twitter/issues/12
I am not sure whether that will be helpful (I am not familiar with JSP development).

>I am sure I have messed up something very small... Please point me to what it is...

>Cheers,
>Asela

**Comment by nathandunn** [comment]
fixed in 2.0.0?

**Comment by monicacecilia** [comment]
@nathandunn I have been testing this on 2.0 and [happily] I have not been able to reproduce it. For now I am closing this issue and if it reappears on 2.0, we'll address it again.
