### ISSUE TITLE
Cannot create isoforms

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#270]
Cannot create a second gene feature after a gene feature has been created in the same region, with complete or partial overlap, UNLESS, the next gene feature is being created in the opposite strand. This is preventing the possibility to create isoforms.

#263    @monicacecilia  Can you explain how to create a second gene in the same region in the old interface?

**Comment by nathandunn** [comment]
This is also related to this one as I believe its the same mechanism: 

Cannot create a gene feature after a different type of feature has been created in the same region, with complete or partial overlap, UNLESS, the gene feature is being created in the opposite strand. After this, no other gene features (partial or complete overlap) can be created if they are being created on the same strand

**Comment by nathandunn** [comment]
I think that this bug was "can not create isoforms" . . this is working now.

**Comment by monicacecilia** [comment]
Able to create more than one copy per gene, and able to duplicate features. Also able to create additional gene features after a different feature type has been created (regardless of partial or complete overlap).
