### ISSUE TITLE
It is not possible to duplicate gene features on the User-created Annotations area.

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#271]
It is not possible to duplicate gene features on the User-created Annotations area.

From #263.

This is the error I get:

hodMessageHandler  - Unhandled exception
Message: No signature of method: org.bbop.apollo.FeatureService.setOwner() is applicable for argument types: (null, org.codehaus.groovy.grails.web.json.JSONObject) values: [null, [username:ndunn@me.com, location:[fmin:383802, strand:-1, ...], ...]]
    Line | Method
->>  176 | $tt__generateTranscript in org.bbop.apollo.FeatureService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    485 | $tt__addTranscript      in org.bbop.apollo.RequestHandlingService
|    591 | doCall . . . . . . . .  in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure5_closure6_closure7
|    590 | doCall                  in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure5_closure6
|    586 | doCall . . . . . . . .  in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure5

**Comment by nathandunn** [comment]
This commit:  46bf532828edad94cef9d5e134a7fb7e168db257

**Comment by nathandunn** [comment]
Not ready:

cv:[name:sequence]]], [location:[fmin:1211579, strand:-1, fmax:1219937], type:[name:CDS, cv:[name:sequence]]]], type:[name:mRNA, cv:[name:sequence]]]
2015-04-14 17:19:29,020 [clientInboundChannel-3] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
java.lang.reflect.InvocationTargetException
	at org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure4_closure5_closure6.doCall(AnnotationEditorController.groovy:586)
	at org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure4_closure5.doCall(AnnotationEditorController.groovy:585)
	at org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure4.doCall(AnnotationEditorController.groovy:581)

**Comment by monicacecilia** [comment]
It is now possible to duplicate features.
