### ISSUE TITLE
Data not available for some Ref Sequences

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#276]
For example: 
GroupUn2710 
<code>http://icebox.lbl.gov/WebApollo2/jbrowse/data/tracks/Official%20Gene%20Set%20v3.2/GroupUn2710/trackData.json 404 (Not Found)
</code>

**Comment by nathandunn** [comment]
more of a dev issues . . . I fixed it so it returns a proper 404. .   . . 

The track data is just not there, but for some reason there is reference sequence, which I think is normal.

**Comment by nathandunn** [comment]
I'm not sure if this is a @monicacecilia  or @cmdcolin   issue.  The data track is still not there, but it is returning a proper error.  I don't see any change from demo either, so I think that this is correct:

http://icebox.lbl.gov/WebApolloDemo/jbrowse/?loc=GroupUn2710%3A1..880&tracks=DNA%2CAnnotations%2CAugustus%20Set%2012%2COfficial%20Gene%20Set%20v3.2&highlight=

**Comment by monicacecilia** [comment]
@nathandunn  the "proper" error is visible on the dev tools, but nothing is being "told" to the curator on the Apollo window. 

It is entirely possible there are no models there, right? this scaffold only has ABOUT 900bp. It is peculiar that there is an error. 

On a side note, did you see how the two tracks crowd together at the top? 
![screen shot 2015-04-15 at 7 20 39 pm](https://cloud.githubusercontent.com/assets/1714621/7172993/5c44f2b6-e3a5-11e4-88d5-b7db216feb03.png)

**Comment by nathandunn** [comment]
Let's discuss this on Thursday.  It seems pretty conceivable for a fragment like this. 

Nathan

**Comment by monicacecilia** [comment]
:+1:

**Comment by nathandunn** [comment]
@monicacecilia   will create a new jbrowse bug for the clumping 

IF there is no data for that refseq when we click on, it should show that information when we click on it.

**Comment by nathandunn** [comment]
Should probably go in some sort of "status bar" at the top . . . once we make room for it.

**Comment by cmdcolin** [comment]
This is cross posted on jbrowse now. Suggest closing?
