### ISSUE TITLE
(1h) sequence panel "select" does not reflect selected count properly when switching orgs

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#278]
From #232   . . this is due to the count not being updated properly . . either do to switching orgs, or pagination.

@monicacecilia   said:

"
The export tool is producing a FASTA file with n-1 selected groups.

For example, I selected five reference sequences, but the export tool only includes information from four of them. This occurs regardless of whether there are annotations in the U-cA area or not.
"

**Comment by monicacecilia** [comment]
sweet! it refreshes without a problem between organisms. 
:dancer:
