### ISSUE TITLE
annotation tab : unexpected interaction with filters

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#279]
From #242 . . . 

from @monicacecilia  

the field in front of "Ref Sequence(s)" echoes what is on display only when the Ref Sequence is chosen by typing the name in that field. If the display changes by using the drop-down menu or by typing its name on the search box on the Apollo window, the field in front of "Ref Sequence(s)" in the Annotation tab remains with the text that reflects the last Group that was typed in it.

**Comment by nathandunn** [comment]
@monicacecilia   I'm not sure what you expect to see (or maybe I've done things in the wrong order).  It looks like its behaving correctly to me other than that there is a small lag, which I should either fix or make apparent to the users.

**Comment by monicacecilia** [comment]
@nathandunn I have further clarified in #242 I don't think this needs to be a different issue so I am closing.
