### ISSUE TITLE
properly handle BAD track additions

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#28]
e.g., when importing a GFF3 file with both gene and mRNA on the same region into jbrowse, when the imported track is annotated, it causes an error, but still "adds" the annotation and leaves the database in an inconsistent state.   It also is unclear what would be annotated, as well.   We should disallow this type of annotation explicitly.

**Comment by nathandunn** [comment]
@deepakunni3   Feel free to kick this down the road (2.1) if it looks tough.   Basically, should issue an error of some type.  It might be that this is more appropriate for @cmdcolin   as well.

**Comment by monicacecilia** [comment]
We have not ran into this again -
