### ISSUE TITLE
Make new style for readthedocs page for 2.0

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#282]
The default readthedocs is a little bland and many sites share that theme. The page could use a nice enhancement for 2.0 (maybe style it like genomearchitect.org)

Here are some nice readthedocs pages from around the web

http://bedtools.readthedocs.org/en/latest/
https://intermine.readthedocs.org/en/latest/

**Comment by monicacecilia** [comment]
This is a nice suggestion, but this is not a priority right now.

**Comment by nathandunn** [comment]
Yep . . its on the list. . . if it needs to slip that's okay . . .  probably be good to do whenever we look at the sphinx stuff when we're a bit more functional complete.

**Comment by cmdcolin** [comment]
Only if someones really motivated
