### ISSUE TITLE
(2h) Non-admin can change organisms, but admin tabs are shown only for where you have admin permissions

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#283]

**Comment by cmdcolin** [comment]
Should we have the same thing on the user panel too?

**Comment by cmdcolin** [comment]
I added some error messages for invalid inputs. 

cdad9891c37a2388e6abfe89d309d19f0a31420d
7767da15beeefdc0879097ebc23fe8eda8ca35f6
f80db894595318280d243f596426ac0abcab6ccf

I guess if you want i can go a little further and finish this issue off (I was de-assigned but i think i can do it)

**Comment by nathandunn** [comment]
Apologies, yeah, if you want to finish it off that would be great.  Thanks.

**Comment by nathandunn** [comment]
Yeah, it looks like its still hiding the organism tab for “non-admin” users. 

You know, that might be okay for now.   I originally wrote this when I had removed the drop-down.   I really don’t think that this is necessary now as you start to use this interface.

If you already go this part going, though, that is fine, so long as the fields are read-only.  Probably don’t need to show the data directories, though to non-admin users. 

Nathan

**Comment by cmdcolin** [comment]
@nathandunn  I actually agree that the current behavior should be ok. However, if we did want to enable them in read-only mode, i made a comment here that would re-enable those tabs https://github.com/GMOD/Apollo/issues/329

**Comment by nathandunn** [comment]
Great.  Let’s mark this as ready and un-assign it.  

I think you can change the title to “we can change organisms if non-admin person” and mark it as ready (and un-assign it).

Nathan

**Comment by cmdcolin** [comment]
Alright so we have decided not to show these tabs for non-admin users,

The new title of the issue is "Non-admin can change organisms, but admin tabs are shown only for where you have admin permissions"

Note: the backend was also secured against non-admin users editing the organism information during the process of this editing, so the web services api docs will reflect this.

**Comment by nathandunn** [comment]
@cmdcolin  Can it be marked as ready?

**Comment by cmdcolin** [comment]
@nathandunn yes. I also checked and the "global admin" can give specific users admin permissions for their organism, and in this case, they will be able to see the full tab list, so should be better now.

**Comment by nathandunn** [comment]
@cmdcolin   Awesome thanks.

**Comment by monicacecilia** [comment]
Brilliant! Thank you @cmdcolin 
I can confirm that this is displayed as you and @nathandunn agreed. 
:dancer:
