### ISSUE TITLE
Error in UserOrganismPreferences

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#284]
I get this error in the error console pretty frequently

    Message: ERROR: null value in column "name" violates not-null constraint
      Detail: Failing row contains (22793, 0, null, null, org.bbop.apollo.UserOrganismPreference, 3, null, 11463).
        Line | Method
    ->> 2161 | receiveErrorResponse in org.postgresql.core.v3.QueryExecutorImpl
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    |   1890 | processResults       in     ''
    |    255 | execute . . . . . .  in     ''
    |    559 | execute              in org.postgresql.jdbc2.AbstractJdbc2Statement
    |    417 | executeWithFlags . . in     ''
    |    363 | executeUpdate        in     ''
    |     70 | $tt__loadSequences . in org.bbop.apollo.SequenceController
    |    198 | doFilter             in grails.plugin.cache.web.filter.PageFragmentCachingFilter
    |     63 | doFilter . . . . . . in grails.plugin.cache.web.filter.AbstractFilter
    |    449 | executeChain         in org.apache.shiro.web.servlet.AbstractShiroFilter
    |    365 | call . . . . . . . . in org.apache.shiro.web.servlet.AbstractShiroFilter$1
    |     90 | doCall               in org.apache.shiro.subject.support.SubjectCallable
    |     83 | call . . . . . . . . in     ''
    |    383 | execute              in org.apache.shiro.subject.support.DelegatingSubject
    |    362 | doFilterInternal . . in org.apache.shiro.web.servlet.AbstractShiroFilter
    |    125 | doFilter             in org.apache.shiro.web.servlet.OncePerRequestFilter

Perhaps "User currentUser = permissionService.currentUser" in loadSequences is not the preferred way to do this

**Comment by nathandunn** [comment]
Yeah, I switched the "not-null" requirement back and forth.   You'll either need to explicitly set it to nullable again or drop your database and reload it (or maybe just the table).   

Nathan

**Comment by nathandunn** [comment]
You can probably go ahead and close it once you've confiremed that it is working again.

**Comment by cmdcolin** [comment]
Is working again
