### ISSUE TITLE
Remove/update old command line scripts

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#289]
The command lines scripts such as add-user.pl/add-tracks.pl are unused

They should be removed or updated to be compatible with the current database model

**Comment by cmdcolin** [comment]
I was imagining that the best way to update them would be to actually implement them in java...perhaps even using groovy ? it works pretty well on the command line

**Comment by nathandunn** [comment]
I think that it is related to #254 . . . I might leave these here until those are done.    If you want to do #254  after you're done with the BLAT that would be fine.

Some such as #255 require #253 as well, which is on the todo-list.

**Comment by cmdcolin** [comment]
Mostly duplicates as nathan noted. Other command line scripts have separate issues now.
