### ISSUE TITLE
render non-transcript features in "getFeatures"

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#292]

**Comment by monicacecilia** [comment]
? Please explain where/how to test.

**Comment by nathandunn** [comment]
Create a feature that is not a transcript (e..,g repeat region or transposable element) and it now shows up properly.   

Nathan

**Comment by monicacecilia** [comment]
There maybe something more to it, but I am unable to create ANY features right now.
This is a new error I am receiving: 
<code>WebSocket connection to 'ws://icebox.lbl.gov/Apollo2/stomp/966/h90o3k69/websocket' failed: WebSocket is closed before the connection is established.</code>
This one I have seen before:
<code>Uncaught com.google.gwt.json.client.JSONException: Error parsing JSON: SyntaxError: Unexpected token </code>

**Comment by monicacecilia** [comment]
Also, for the record, I am also testing Staging and all things work as expected there. I thought it could have been my connection, but Staging works just fine. Apollo2 is non-responsive. 
On a different attempt with Apollo2 I also got this one: 
<code>Uncaught Error: INVALID_STATE_ERR</code>

**Comment by monicacecilia** [comment]
working correctly. hooray! :dancer:
