### ISSUE TITLE
clicking on repeat region and transposable element should list details and navigate

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#293]

**Comment by nathandunn** [comment]
similar behavior to transcripts / genes . . .

**Comment by nathandunn** [comment]
@monicacecilia   Should these drill-down similar to a gene / transcript?  I only see a single level of editing in the information editor.

**Comment by selewis** [comment]
only a single level
(one day we hope to have more, but it isn't there yet)

**Comment by deepakunni3** [comment]
@nathandunn Ready for testing and feedback.

**Comment by monicacecilia** [comment]
Expected information is visible on all non-gene features. 
:dancer:
