### ISSUE TITLE
Exporting CDS/GFF3 generates JSON-like name

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#294]
The name for Exon and CDS is generated incorrectly and this observed in the GFF3 export as well as 'Get GFF3'.

Example:
```
Group1.1	.	exon	325091	328828	.	+	.	Name=7d56815b-baae-4732-a747-9d01ac0d3738-[name:exon%2C cv:[name:sequence]];date_creation=2015-03-17;Parent=4e82366a-9a06-4caf-b8f8-b84267668ab9;ID=7d56815b-baae-4732-a747-9d01ac0d3738;date_last_modified=2015-03-17
Group1.1	.	CDS	300389	325348	.	+	.	Name=79787f4a-8a5a-4fd1-90ac-7a6c50c7dc56-[name:CDS%2C cv:[name:sequence]];date_creation=2015-03-17;Parent=4e82366a-9a06-4caf-b8f8-b84267668ab9;ID=79787f4a-8a5a-4fd1-90ac-7a6c50c7dc56;date_last_modified=2015-03-17
```

**Comment by selewis** [comment]
Why are we even generating names for exons? I don't recall that as a
requirement from anyone.

Same for the CDS.

For the protein itself that's a different matter. It does need a name.

-S

**Comment by nathandunn** [comment]
they are just generic names in the name field . . . it should be of the form "unique-name-<type>" . . .  we may remove it later

**Comment by deepakunni3** [comment]
@nathandunn The bug has been fixed. Just a one line change in FeatureService.

**Comment by monicacecilia** [comment]
Thanks @deepakunni3 ! I can confirm it works now :dancer: 

@nathandunn - trombones playing - there is a delay in the display of GFF3 and sequences. For at least 2 or 3 seconds I get what you see in the figure. Expected? Fixable? 

![screen shot 2015-05-22 at 3 42 15 pm](https://cloud.githubusercontent.com/assets/1714621/7780847/5463a2fc-0099-11e5-8117-73f9aaf8a959.png)

**Comment by nathandunn** [comment]
I moved the delay piece to #402.      As we discussed before, I'd like to optimize the export first and if not we can put something in there.
