### ISSUE TITLE
Tracks not loading after latest build

### ISSUE THREAD

**Issue by littlebunch** [GMOD/Apollo#296]
After I pulled and deployed yesterday (4/17) and today (4/18), tracks won't load, i.e. RequestError: Unable to load http://gmod-dev.nal.usda.gov:8080/apollo/jbrowse/data/tracks.conf status: 500.   The log indicates some sort of database issue.  The species were added while running the 4/16 build and seemed to be OK.  

````2015-04-18 11:56:57,411 [http-bio-8080-exec-4] ERROR errors.GrailsExceptionResolver  - PSQLException occurred when processing request: [GET] /apollo/jbrowse/data/trackList.json
ERROR: null value in column "name" violates not-null constraint
  Detail: Failing row contains (308641, 0, null, null, org.bbop.apollo.UserOrganismPreference,3,Scaffold1069, 6, t).. Stacktrace follows:org.postgresql.util.PSQLException: ERROR: null value in column "name" violates n
ot-null constraint
  Detail: Failing row contains (308641, 0, null, null, org.bbop.apollo.UserOrgan
ismPreference, 3, Scaffold1069, 6, t).
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryEx
ecutorImpl.java:2161)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1890)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:559)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)```

**Comment by nathandunn** [comment]
I changed one of the domain objects columns from null to not-null as part of the dev process.  It should be switched back now.  If not do:

“delete from preference” on the SQL table.  

Conversely:

"alter table preference alter name column drop not null ;  "


Once we do a formal release I’ll use the DB_migration plugin (or something similar) to manage any of these small changes between stable version.

Nathan

**Comment by littlebunch** [comment]
Thanks.  That worked.

**Comment by monicacecilia** [comment]
@nathandunn can you please do the same on icebox? Tracks are not loading there either.

**Comment by nathandunn** [comment]
I think this is unrelated to Gary's problem, but something is seriously wrong, nonetheless.  It is loading the JBrowse mainline inexplicably instead of the release.   

Anyway, I patched it on icebox.   You may need to quit your browse entirely.   I'll look for a more permanent solution.

**Comment by nathandunn** [comment]
Closing this in favor of #297.

**Comment by monicacecilia** [comment]
@nathandunn gracias.
