### ISSUE TITLE
Apollo "release" target failing to build

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#297]
From #296 . . . 

Running the "./apollo release" binary ends up deploying the master branch of JBrowse instead of 1.6-release.  

This doesn't happen in deploy. 

The original checkout is correct, but what gets deployed to the web-app/jbrowse directory is a different version (i.e., master).    This was working earlier (this last week), so not sure what has changed.  

Please make this a priority.  Thanks.

**Comment by nathandunn** [comment]
FYI @monicacecilia   WRT to #296 .

**Comment by cmdcolin** [comment]
Please elaborate because it's not clear to me what this is about

**Comment by cmdcolin** [comment]
The code on http://icebox.lbl.gov/WebApollo2/annotator/index is probably not using the master branch (I can check files like http://icebox.lbl.gov/WebApollo2/jbrowse/jbrowse.conf which have not been updated to master branch)

**Comment by nathandunn** [comment]
It is the master branch:

Some more info:

ndunn:Apollo% find . -name JBrowse\*    ## I excluded irrelievatn directories
./JBrowse-dev
./jbrowse-download/
./jbrowse-download/JBrowse-dev/


ndunn:Apollo% find . -name jbrowse
./web-app/jbrowse    
ndunn:Apollo% 

JBrowse-dev   master 
./jbrowse-download/  1.11.6-release
./jbrowse-download/JBrowse-dev  1.11.6-release
./web-app/jbrowse    1.11.6-release

. .. . however, the precompiled code, I am assuming is coming from JBrowse-dev. 


This is what Moni and I were seeing:






Nathan

**Comment by cmdcolin** [comment]
Hmm. Ok i will look around. One thing I just did could help though. I fixed a small error with the javascript minimization release target. The javascript in the WA client module had a syntax error 

Maybe that will help with this bug (i'll continue looking)

**Comment by cmdcolin** [comment]
Also, we might want to integrate a command like this into our travis-CI

    node src/dojo/dojo.js load=build --require "src/JBrowse/init.js" --profile "plugins/WebApollo/js/WebApollo"


That way it will continuously run those syntax checks on our client code :)

**Comment by nathandunn** [comment]
@cmdcolin   Says that the webapollo plugin code may not have been installed properly.

**Comment by nathandunn** [comment]
I tested it locally and it seems to work . .

**Comment by cmdcolin** [comment]
I changed the name of the issue name since i think some of the other things were sort of a side-effect of the main issue (the syntax error). Also now the syntax will be checked via the travis-ci for each git commit so these errors should be easier to catch

**Comment by nathandunn** [comment]
@cmdcolin   Great thanks!

**Comment by nathandunn** [comment]
Nothing to check for @monicacecilia   . .  will close.

**Comment by lfaino** [comment]
Dear All,
was this problem fixed?

Luigi

**Comment by nathandunn** [comment]
@Ifaino Yes.  If you have a new issue, please create a new bug or post to the list: "apollo@lists.lbl.gov".  Thanks!
