### ISSUE TITLE
Wrong login should fail more gracefully.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#298]
A message warning of "Invalid Login Credentials" would be helpful. 

... especially if someone changes your credentials without you knowing. wink, wink. :scream:

**Comment by cmdcolin** [comment]
We now at least have a popup when the logins fail.

**Comment by monicacecilia** [comment]
a thing of beauty. ... thanks! :dancer: 
![screen shot 2015-05-22 at 3 26 34 pm](https://cloud.githubusercontent.com/assets/1714621/7780676/03a10208-0097-11e5-9a3b-4fdfe096bc19.png)

![screen shot 2015-05-22 at 3 26 48 pm](https://cloud.githubusercontent.com/assets/1714621/7780677/052ca91a-0097-11e5-97c3-74b357cb1100.png)
