### ISSUE TITLE
Genome insertion trigers recalculate CDS on non-coding features

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#30]
If a sequence insertion is made on the exon for a feature, Web Apollo calculates the longest CDS.  This is a problem for non-coding features, which are not supposed to have CDS features.
Here is an example:
###
    Scaffold1	WebApollo	gene	870322	875660	.	+	.	Name=73DAC4E888056EE3754995061F15375C;
    Scaffold1	WebApollo	tRNA	870322	875660	.	+	.	Name=LdecTmpM001045-RA;
    Scaffold1	WebApollo	exon	871543	871777	.	+	.	Name=C3C416C288FA09E123B0F0F225FC685E;
    Scaffold1	WebApollo	exon	870322	870366	.	+	.	Name=5B5C479A0399008A64FA8D01EF3813CE;
    Scaffold1	WebApollo	exon	873246	873730	.	+	.	Name=8835B8B0B924A447756DFBD92D945E67;
    Scaffold1	WebApollo	exon	875510	875660	.	+	.	Name=8DB97ABB2C1623E701E05FEE5B4E454F;
###
###
    Scaffold1	WebApollo	gene	870322	875660	.	+	.	Name=73DAC4E888056EE3754995061F15375C;
    Scaffold1	WebApollo	tRNA	870322	875660	.	+	.	Name=LdecTmpM001045-RA;
    Scaffold1	WebApollo	exon	871543	871777	.	+	.	Name=C3C416C288FA09E123B0F0F225FC685E;
    Scaffold1	WebApollo	exon	870322	870366	.	+	.	Name=5B5C479A0399008A64FA8D01EF3813CE;
    Scaffold1	WebApollo	CDS	870329	870366	.	+	0	Name=BE5E8F6277CB18AEDD3684C093B5E99C-CDS;
    Scaffold1	WebApollo	CDS	871543	871777	.	+	2	Name=BE5E8F6277CB18AEDD3684C093B5E99C-CDS;
    Scaffold1	WebApollo	CDS	873246	873730	.	+	0	Name=BE5E8F6277CB18AEDD3684C093B5E99C-CDS;
    Scaffold1	WebApollo	CDS	875510	875625	.	+	2	Name=BE5E8F6277CB18AEDD3684C093B5E99C-CDS;
    Scaffold1	WebApollo	exon	873246	873730	.	+	.	Name=8835B8B0B924A447756DFBD92D945E67;
    Scaffold1	WebApollo	exon	875510	875660	.	+	.	Name=8DB97ABB2C1623E701E05FEE5B4E454F;
###

**Comment by nathandunn** [comment]
@monicacecilia   I want to retest this in 2.0.0  I looked and it appears that we have the correct code in there, but I want some separate eyes to verify.

**Comment by monicacecilia** [comment]
@nathandunn You are correct, genomic insertions are no longer causing the generation of a CDS in tRNA features. However, while investigating this issue, I found a few other things. Please see #263

**Comment by nathandunn** [comment]
@deepakunni3   Could this be relevant?

**Comment by deepakunni3** [comment]
@nathandunn This bug doesn't occur in Apollo 2.0

The rationale holds for recalculating CDS only when the transcript is an instance of mRNA.
