### ISSUE TITLE
Increase distance between top edge of U-cA area and the first annotation

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#300]
It is not as noticeable on the light schema, but definitely on the dark one, that the top-most annotation is too close to the upper edge of the U-cA area. I think it coincides with. We should bring it down a few pixels. At least so some space is visible between the edge of the U-cA and the top-most annotation. 

![screen shot 2015-04-19 at 12 55 04 pm](https://cloud.githubusercontent.com/assets/1714621/7221107/bd6f615c-e693-11e4-88fd-b4dd79334cfd.png)

![screen shot 2015-04-19 at 12 55 37 pm](https://cloud.githubusercontent.com/assets/1714621/7221108/c1827b76-e693-11e4-900a-e9bac23722ba.png)

**Comment by nathandunn** [comment]
The "element" over-rides it.  Adding it explicitly to a 1 px and 2 px is hard as you have to do the same for the label as well or it starts to look funny.    Conversely, we could pull it up one and leave it the same possibly.   Overall, I don't think its important enough to do for this. 

<img width="279" alt="screen shot 2016-11-27 at 8 23 09 pm" src="https://cloud.githubusercontent.com/assets/751274/20656244/6f1b7a7e-b4df-11e6-89cf-8b7adb0373c6.png">
