### ISSUE TITLE
can not delete an organism with a preference

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#302]
Error 500: Internal Server Error

    URI
    /apollo/organism/deleteOrganism
    Class
    org.postgresql.util.PSQLException
    Message
    ERROR: update or delete on table "sequence" violates foreign key constraint "fk_i94ksmdxi88hcqnuycebgkdvs" on table "preference" Detail: Key (id)=(11299) is still referenced from table "preference".
    Around line 60 of grails-app/services/org/bbop/apollo/PermissionService.groovy

    57:58:    Set<Organism> getOrganisms(User user) {59:        if (isAdmin()) {60:            return Organism.listOrderByCommonName()61:        }62:        Set<Organism> organismList = new HashSet<>()63:        for (UserPermission userPermission in UserPermission.findAllByUser(user)) {
    Around line 402 of grails-app/services/org/bbop/apollo/PermissionService.groovy

    399:    def getOrganismsForCurrentUser() {400:        User thisUser = currentUser401:        if (thisUser) {402:            return getOrganisms(thisUser)403:        }404:        return []405:    }
    Around line 140 of grails-app/controllers/org/bbop/apollo/OrganismController.groovy

    137:138:    def findAllOrganisms() {139:140:        def organismList = permissionService.getOrganismsForCurrentUser()141:        UserOrganismPreference userOrganismPreference = UserOrganismPreference.findByUserAndCurrentOrganism(permissionService.currentUser, true)142:        Long defaultOrganismId = userOrganismPreference ? userOrganismPreference.organism.id : null143:
    Around line 34 of grails-app/controllers/org/bbop/apollo/OrganismController.groovy

    31:        if (organism) {32:            organism.delete()33:        }34:        render findAllOrganisms()35:    }36:37:    @Transactional
    Around line 198 of PageFragmentCachingFilter.java

    195:			if (CollectionUtils.isEmpty(cacheOperations)) {196:				log.debug("No cacheable annotation found for {}:{} {}",197:						new Object[] { request.getMethod(), request.getRequestURI(), getContext() });198:				chain.doFilter(request, response);199:				return;200:			}201:
    Around line 63 of AbstractFilter.java

    60:		try {61:			// NO_FILTER set for RequestDispatcher forwards to avoid double gzipping62:			if (filterNotDisabled(request)) {63:				doFilter(request, response, chain);64:			}65:			else {66:				chain.doFilter(req, res);
    Trace

**Comment by nathandunn** [comment]
Possibly worse-named bug ever . . . .  Anyway, just need to go into preference table in Delete Organism and remove preferences for this organism, or create a cascade via a BelongsTo

**Comment by nathandunn** [comment]
To test: 
1 - create an organism 
2 - navigate to any reference sequence on that organism
3 - delete the organism ..  should work

**Comment by monicacecilia** [comment]
:+1:
