### ISSUE TITLE
(2d) do not persist flanking region

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#306]
We are persisting flanking regions in the database, which just slows things down and creates unnecessary data.   Its just used for calculations and should simply be a POJO and/or JSON object.

**Comment by nathandunn** [comment]
@deepakunni3   Make sure to add any notes, what you tried, why got stuck, etc.  . . . we'll have to come back to this.    I didn't see any really obviously solution, either.

**Comment by nathandunn** [comment]
@deepakunni3   Hey, you should take a look at FeatureEvent and FeatureEventService:

https://github.com/GMOD/Apollo/blob/8c3587ef6a036b4794a7adb21f0f7c7fe49cfecb/grails-app/services/org/bbop/apollo/FeatureEventService.groovy

You should continue working on what you're working on, just an FYI.

**Comment by nathandunn** [comment]
These were also serialized in WA1, but since we can't see that data easily, it didn't matter.

**Comment by nathandunn** [comment]
FlankingRegion is typically used in conjunction with "getResiduesWithAlterationsAndFrameshifts".  

Initial getResidues code from SequenceService that uses Flanking region requires:
- attributes of FeatureLocation (min, max, strand, sequence), and top-level transcript, if any, and any overlapping sequence alterations (or at least those just on the sequence)  
- If it is not an instance of a CDS (as in the case of a FlankingRegion) it goes to "getResiduesWithAlterationsNew()", which calls getResiduesFromFeature(feature). 
- at the end we call SS::getResiduesFromFeature.  For FlankingRegion (where we call it), there is only one region and it calls:  getResiduesFromFeatureLocation, which requires , min, max, and sequence ONLY.    The strand is used to create the reverse-compliment.  
- lastly we APPLY the sequence alterations.  This requires the fmin, fmax, and strand only, / the feature location and the source coordinate of the alteration (which it converts to local).  FS::convertSourceCoordinateToLocalCoordinate . . and those are applied fairly straightforwardly.  

*Proposal*

For fmin, fmax, strand, sequence create method SS::getResiduesAndAlterationsFromSequence(seq,fmin,fmax,strand)

1 - Get SequenceAlterations for sequence (can get upstream / downstream ones later)
2 - SS::getResiduesFromSequence(seq,fmin,fmax)
3 - reverse compliment if need be
4 - Apply sequence alterations based on translated location

**Comment by nathandunn** [comment]
@deepakunni3   Can you verify that this is working sometime this week . . .esp for sequence alterations.  By working I mean, works as expected, but never creates a FlankingRegion.

**Comment by deepakunni3** [comment]
@nathandunn This works as expected. Flanking regions are not persisted.

**Comment by nathandunn** [comment]
@deepakunni3   Thanks for testing.

**Comment by deepakunni3** [comment]
:+1:
