### ISSUE TITLE
Owners of annotations

### ISSUE THREAD

**Issue by jwlin** [GMOD/Apollo#314]
I am testing WA 2.0, and found that owner of each annotation is "undefined". Am I missing some configuration? Also, I tried to recognize the owners from DB but got likely incomplete list. I mean I have more than 10 annotations but saw only a few of them in feature_grails_user; How to get the owner information from DB? Thanks

![owner](https://cloud.githubusercontent.com/assets/5249835/7348775/49f83e12-ecc2-11e4-9485-09033dd0f302.png)

**Comment by nathandunn** [comment]
This is a legitimate bug.   If you click on the details panel, you'll see that it matches the database.  The error is in the getFeatures() call:

What Annotrack.js expects:
properties: [{value: "demo", type: {name: "owner", cv: {name: "feature_property"}}}]

What it gets:
owner: "ndunn@me.com"

Probably what we should be doing is passing the UserInfo object:
owner: "{ userId: 3,firstName:'Nathan', lastName: 'Dunn',email:'ndunn@me.com', role: 'admin' . . . .  
etc. etc. 

which will require both server and client-side changes.

**Comment by nathandunn** [comment]
@jwlin   This should work now if you do a pull . .

**Comment by jwlin** [comment]
Thanks! I did a pull and redeployed the war, and owner information was correctly displayed. But somehow I can not add 'pseudogene', 'tRNA', 'snRNA', ... etc (the POST returns "204 No Content"). It seems that only adding gene works. Is this a problem of my system? 

![add annotation](https://cloud.githubusercontent.com/assets/5249835/7399869/d5633fc2-ee86-11e4-919f-387cd19cb1b4.jpg)

**Comment by nathandunn** [comment]
If you do a pull does it fixed the problem?   I had *just* fixed something for adding non-transcripts.  

Nathan

**Comment by jwlin** [comment]
I did a pull 5 minutes ago. All kinds of features can be added but only gene(mRNA)'s owner info was displayed, and others are 'None'

![screenshot-1](https://cloud.githubusercontent.com/assets/5249835/7421572/bc03125a-ef53-11e4-9f11-3b898cdf6088.jpg)

**Comment by nathandunn** [comment]
This should be fixed on the most recent push.   You’ll have to recreate your annotations, t hough.

Thanks for catching that.

Nathan

**Comment by monicacecilia** [comment]
I'm the owner of aaaaall my annotations. Mine! 
it works well. Thanks @jwlin! 
and thank you very much @nathandunn :+1: 
:dancer:
