### ISSUE TITLE
jbrowse deployment should not have test, sample data, or staging data

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#315]

**Comment by cmdcolin** [comment]
The release versions already do not contain the tests directory. What is the purpose of this aside from that?

**Comment by cmdcolin** [comment]
See http://jbrowse.org/jbrowse-1-11-6/ for example of the contents of the release version

**Comment by nathandunn** [comment]
When it does the git clone . .  I want to make sure that only the minimum needed to deploy is copied to the web-app directory.   Hopefully this is just a small change to the build.xml.  

Nathan

**Comment by cmdcolin** [comment]
That seems reasonable. I noticed there were commits trying to omit the tests/ directory in build.xml but maybe those were failing because the release package does not have the tests/ directory. In general i don't see why this is super high priority though.

**Comment by enuggetry** [comment]
Shouldn't it have some data, at least to verify that the deployment was successful?  However, it is possible to reference remote test data?

**Comment by nathandunn** [comment]
Its good not to add more than needed to the release.   Currently we have a LOT of stuff that it simply doesn’t need, including JBrowse-dev, dev-dev, doc, etc. anything that will not actually ever be used.

This should be low-hanging fruit to fix.  It could just be a bug, I think that it doesn’t typically copy these over.  

git/2.0-Apollo-release$ du -sh web-app/jbrowse/* 
4.0K	web-app/jbrowse/INSTALL
29M	web-app/jbrowse/JBrowse-dev
108M	web-app/jbrowse/JBrowse-dev-dev
26M	web-app/jbrowse/JBrowse-dev-dev.zip
5.9M	web-app/jbrowse/JBrowse-dev.zip
36K	web-app/jbrowse/LICENSE
4.0K	web-app/jbrowse/Makefile.PL
4.0K	web-app/jbrowse/README.md
444K	web-app/jbrowse/bin
16K	web-app/jbrowse/build
4.0K	web-app/jbrowse/combination_tracks.css
4.0K	web-app/jbrowse/compat_121.html
1.1M	web-app/jbrowse/docs
4.0K	web-app/jbrowse/export_dialog.css
8.0K	web-app/jbrowse/faceted_track_selector.css
4.0K	web-app/jbrowse/file_dialog.css
4.0K	web-app/jbrowse/genome.css
4.0K	web-app/jbrowse/hierarchical_track_selector.css
4.0K	web-app/jbrowse/icons.css
816K	web-app/jbrowse/img
8.0K	web-app/jbrowse/index.html
4.0K	web-app/jbrowse/jbrowse.conf
4.0K	web-app/jbrowse/jbrowse_conf.json
24K	web-app/jbrowse/main.css
4.0K	web-app/jbrowse/maker.css
4.0K	web-app/jbrowse/menubar.css
2.9M	web-app/jbrowse/plugins
124K	web-app/jbrowse/release-notes.html
108K	web-app/jbrowse/release-notes.txt
4.0K	web-app/jbrowse/sequence.css
8.0K	web-app/jbrowse/setup.sh
93M	web-app/jbrowse/src
10M	web-app/jbrowse/tests
12K	web-app/jbrowse/track_styles.css
4.0K	web-app/jbrowse/tristate.css

**Comment by nathandunn** [comment]
I don’t think its used in that capacity (though its not a bad idea).   The sample data is there to get folks up and going with JBrowse quickly, which is a great thing.  

Here, we are deploying it as part of an application, and so we want the minimum needed to run it. 

Nathan

**Comment by cmdcolin** [comment]
Ah, i see the point. The extra blaot from the JBrowse-dev-dev files being copied is unnecessary. I think perhaps the copy-resources step is being unnecessarily run?

**Comment by nathandunn** [comment]
Something is screwing with the release script . . . or the code / build was simply in a bad state.   

Basically I want to have:

./apollo clean-all
./apollo release

And always be guaranteed of the same result. 

Nathan

**Comment by nathandunn** [comment]
Actually, I think that it might be related to this?

https://travis-ci.org/GMOD/Apollo/builds/60264870 <https://travis-ci.org/GMOD/Apollo/builds/60264870>

Any ideas? 

Nathan

**Comment by cmdcolin** [comment]
Well, I don't think your branch merge was related really. I think the real problem is that the copy-resources is being run. In the comments, it says copy-resources is called externally, whereas now, we made it part of the basic compilation dependencies list (i.e. gwtc target).

It seems to be fixed if we make it external again (i.e. call copy-resources from apollo binary) and remove it from the gwtc target

**Comment by nathandunn** [comment]
I opened a new bug for it here: #316    . . . I'll take a quick look and see what the trouble might be

**Comment by cmdcolin** [comment]
@nathandunn I think this is just due to the cache being out of date. I am re-running the builds on the site for these

**Comment by cmdcolin** [comment]
This is the minimal change that I can make for now to fix the problem.


    diff --git a/apollo b/apollo
    index 237c841..6818204 100755
    --- a/apollo
    +++ b/apollo
    @@ -87,7 +87,7 @@ if [[ $1 == "devmode" ]];then
     elif [[ $1 == "run-local" ]];then
         # should call the copy target first
         check_configs
    -    ant gwtc && grails run-app
    +    ant copy-resources gwtc && grails run-app
     elif [[ $1 == "debug" ]];then
         # TODO: feel like there is a better way to do this
         OLD_MAVEN_OPTS=$MAVEN_OPTS
    @@ -111,12 +111,12 @@ elif [[ $1 == "deploy" ]];then
         rm -f src/java/apollo-config.groovy
         cp apollo-config.groovy src/java/apollo-config.groovy
         #grails deploy
    -    ant gwtc &&  grails war
    +    ant copy-resources gwtc &&  grails war
     elif [[ $1 == "release" ]];then
         # should call the copy target first
         check_configs
         check_configs_for_release
    -    ant clean-all release gwtc && grails war
    +    ant clean-all release gwtc install.jbrowse.perl && grails war
     elif [[ $1 == "compile" ]];then
         # should call the copy target first
         ant gwtc && grails compile
    diff --git a/build.xml b/build.xml
    index 81bdaf0..42ef7af 100644
    --- a/build.xml
    +++ b/build.xml
    @@ -38,7 +38,7 @@
             </copy>
         </target>
 
    -    <target name="gwtc" depends="copy-resources,javac" description="GWT compile to JavaScript (production mode)">
    +    <target name="gwtc" depends="javac" description="GWT compile to JavaScript (production mode)">

**Comment by nathandunn** [comment]
What is the reason for moving the jbrowse perl install to be external?  

Nathan

**Comment by cmdcolin** [comment]
@nathandunn The copy-resources was removed but the install.jbrowse.perl dependency needed to be kept

**Comment by cmdcolin** [comment]
The install.jbrowse.perl could technically be added as a dependency of the release target as well, basically the same idea though.

**Comment by nathandunn** [comment]
There is an ant target in there called "install.jbrowse.perl", which calls that exec.  It would be better to use that.   The nice thing about using ant is that it can be used as a dependency. 

If you type: "ant -d -p " . . it might help (seems to show at least first-level dependencies).

**Comment by cmdcolin** [comment]
I think it is using that ant target now. Feel free to mark as ready or close if it gets tested under not just release, but debug/deploy/other commands as well

**Comment by nathandunn** [comment]
@cmdcolin   K, thanks.  I will try testing it.

**Comment by nathandunn** [comment]
@cmdcolin I think that this is working as designed.
