### ISSUE TITLE
when adding / changing an annotation to UcA, should update AnnotatorPanel

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#318]
when adding / changing an annotation to UcA, should update AnnotatorPanel.  

We are already registering the GWTEven'ts, just need to handle . .  I think in 

MainPanel::handleNavigationEvent()

will probably just call AnnotatorPanel::reload . . .

**Comment by cmdcolin** [comment]
This does seem to update eventually (good) but you have to "interact" with the annotator panel before it is updated (might need improvement). That fact seems to be corroborated by the fact that the refresh happens during "handleNavigationEvent" on the commit https://github.com/GMOD/Apollo/commit/2cc530ee185f7877c8db7dfdf71bf6ebbcf67d57

**Comment by nathandunn** [comment]
I wonder if you're just seeing a delay.

**Comment by cmdcolin** [comment]
It only updates once you scroll in jbrowse or something like that it seems. If you just drag and drop and then remain stationary it doesn't update the list.

Also the sorting is a little wonky when it updates

**Comment by nathandunn** [comment]
@cmdcolin   Good catch.   I forgot to add it to the "changeData" section . . .

**Comment by monicacecilia** [comment]
Brilliant. Annotations panel is being updated immediately.
