### ISSUE TITLE
(2d) list organism in JBrowse section

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#319]
List the current organism in the JBrowse section .. . 

Should be in the MainPanel (which comes from "Preferences") . .. I would not recommend grabbing it from the session. 

- [x] need websockets to be enabled with no side-panel to show changes back on the client
- [x] list organism in panel
- [x] connect websocket when logged-in and no super-panel
- [x] provide a link to the "annotator" window (the preference will be for the logged-in user so going back to the base servlet container should work)

**Comment by cmdcolin** [comment]
JBrowse technically has the ability to list organisms


![screenshot-jbrowse org 2015-04-28 15-35-53](https://cloud.githubusercontent.com/assets/6511937/7379708/5f649de0-edbc-11e4-932c-b0927f3f56cd.png)



Unfortunately it uses the space where the WA logo is, so that is a little awkward

**Comment by nathandunn** [comment]
Can we replace the “browse full-screen” section?   It doesn’t really need to be there.  It only shows up because I am including it as an iFrame.  

Nathan

**Comment by cmdcolin** [comment]
Do we still have to do this now that we have the select box on the sidebar?

**Comment by nathandunn** [comment]
If the side-bar is closed it would be good to have this info.   However, let me get some of this web socket stuff fixed first.   

Nathan

**Comment by nathandunn** [comment]
I think that the easy way would be to set the data on "refSeqs.json" in the JBrowseController . .  Probably get the whole organism object that way.

**Comment by nathandunn** [comment]
@cmdcolin   Do you mind if I populate the organism locally?  I need this (at least on the backend) done for #391 .   They you can put it anywhere you want after that.    I was thinking of putting it on the refSeq.json object, but let me know if you have any better ideas.  Working on a branch right now.

**Comment by cmdcolin** [comment]
@nathandunn 

I don't necessarily see what strategy would be used for injecting the organism information into the refSeqs.json. I would instead inject it into a config file, like trackList.json or just attach it to the javascript programmatically similar to how we interface with the track list.

**Comment by nathandunn** [comment]
I think it would best to dynamically inject this in order to keep the database and data directory.  Otherwise you’d be trying to match the database to the whatever you put into your trackList.json as opposed to just exposing the directory and having the software synchronize it.

**Comment by nathandunn** [comment]
@cmdcolin   Actually it ends up being easier than that, because the side-panel exposes this information directly . .  which is I think lot easier than these rewrites I was attempting.

**Comment by cmdcolin** [comment]
>>because the side-panel exposes this information 

that is probably best approach for now, but for the public only jbrowse...if we're running without the sidebar...could be a different story

**Comment by nathandunn** [comment]
Right . . . just thoguht that . . . 

I had left some code in JBrowseController that populated the trackList just fine, . . . I'm not sure how to get it into the client though, as it didn't seemed to get picked up properly (or I didn't do it right).   Same with refseqs . . esp. since it is an entire Array:

               if (fileName == "trackList.json") {
                    JSONObject jsonObject = JSON.parse(file.text) as JSONObject
                    Organism organism = preferenceService.currentOrganismForCurrentUser
                    JSONObject organismObject = new JSONObject()
                    organismObject.put(FeatureStringEnum.NAME.value,organism.commonName )
                    organismObject.put(FeatureStringEnum.ID.value,organism.id)
                    organismObject.put("genus",organism.genus)
                    organismObject.put("species",organism.species)
                    jsonObject.put(FeatureStringEnum.ORGANISM.value, organismObject.toString())
                    response.outputStream << jsonObject.toString()
               }

**Comment by cmdcolin** [comment]
1. use the code snippet that nathan provided to rewrite the trackList.json to include datasets and dataset_id
2. the drop down will contain only organisms the user has permission on
3. write loadLink urls into the datasets and dataset_id fields so that they are correctly switched too

**Comment by nathandunn** [comment]
Make sure that when you click on "full-screen view" it also has the organism in there (otherwise it goes to the selection screen).  The ID would be ideal, but if its the common name, that is fine as well, just need to make some small adjustments to the other code.

**Comment by nathandunn** [comment]
@cmdcolin   It looks like it broke the jbrowse link code, which was working in #353.  

Fixed that . . . and that part works now.

**Comment by cmdcolin** [comment]
@nathandunn ya just noticed that. will re-fix that ;)

**Comment by cmdcolin** [comment]
Added review tag. Feel free to check if this works for us

**Comment by nathandunn** [comment]
Thanks for fixing . .  I never ended up pushing my change .  ..

**Comment by nathandunn** [comment]
I'll take a look.

**Comment by nathandunn** [comment]
@cmdcolin   I think that this will work (after I fixed some of the caching mumbo-jumbo).  Its a little counter-intuitive when logged out that clicking on the drop-down takes you back to the annotator, but I think that the solution will work.  If it had the word "annotate" (when logged out) to indicate that that is what you were doing, it might help, but I think that this will work as-is.   

I will send it on.   Waiting for #427 and then I will push.

**Comment by nathandunn** [comment]
I will send it on. Waiting for #427 and then I will push to icebox.

**Comment by nathandunn** [comment]
@cmdcolin   If I am logged-in and there is no side-panel, I still need websockets to be enabled to show changes back on the client.   I think that some of the changes you had made should allow this.

**Comment by cmdcolin** [comment]
@nathandunn  That particular thing we discussed on #353 yesterday and it was almost done so I think I wrapped it up. Feel free to check it again

**Comment by nathandunn** [comment]
@cmdcolin   Looks to work for me.  Options options options.  I'll move it to the "ready" pile.

**Comment by monicacecilia** [comment]
It is now possible to see all organisms on the JBrowse window. 
After going to a "Full-screen view" window, the tab for selecting a different organism is still visible.
Curiously, if I switch organisms while on the "Full-screen view", the new organism shows up on the now-default window with the "annotator" side panel. This is ok. Just bringing it up fyi. 

Thanks! :dancer:
