### ISSUE TITLE
set longest ORF seems to fail with a weird error

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#320]
After setting the translation end I get this error when I set the ORF:

om DB: 20000
| Error 2015-04-28 13:23:34,924 [clientInboundChannel-2] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
Message: deleted object would be re-saved by cascade (remove deleted object from associations): [org.bbop.apollo.Comment#27052]; nested exception is org.hibernate.ObjectDeletedException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.bbop.apollo.Comment#27052]
    Line | Method
->>  705 | setLongestOrf in org.bbop.apollo.RequestHandlingService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    704 | doCall        in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure3_closure4_closure5
|    703 | doCall . . .  in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure3_closure4
|    699 | doCall        in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure3
|    289 | call . . . .  in groovyx.gpars.group.PGroup$3
|    313 | run           in groovyx.gpars.group.PGroup$4
|   1145 | runWorker . . in java.util.concurrent.ThreadPoolExecutor
|    615 | run           in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . in java.lang.Thread

**Comment by nathandunn** [comment]
@deepakunni3 Its possible that these are working, but I either broke them in my history branch or am testing it wrong.

**Comment by deepakunni3** [comment]
@nathandunn Cannot reproduce the same error. It seems to work without any errors on the console.

**Comment by nathandunn** [comment]
@deepakunni3   Thanks. . I'll close it then.

**Comment by deepakunni3** [comment]
@nathandunn I can verify it once again after fixing #87 and #321
