### ISSUE TITLE
(1d left?) set translation start and end giving wrong behavior

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#321]
Looking at GB40734-RA, GB40833-RA

For GB40833-RA . .  setting the translation END works, but doesn't calculate the ORF properly (it appears).  

setting translation START and END to the exact same thing.

**Comment by nathandunn** [comment]
@deepakunni3   Its possible that these are working, but I either broke them in my history branch or am testing it wrong.

**Comment by monicacecilia** [comment]
@deepakunni3 It seems that this has been fixed (hooray!). I see "Start" and "End" being correctly sent in these gene models. Thank you!

Even so, I am still curious about the steps you take when you use the "Set translation Start" and "Set translation End" features. Are you setting the cursor on the nucleotide residue where you want translation to begin/end?
