### ISSUE TITLE
(4h) Support "Status"

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#322]
Not sure if this is necessary for 2.0.0 . . or not.  @childers and @mpoelchau might have an opinion?

**Comment by mpoelchau** [comment]
Can you remind me what "Status" is?

**Comment by childers** [comment]
Status:
Approved Accepted Delete
It is another attribute section that lets you specify a number of radio buttons.

**Comment by mpoelchau** [comment]
Thanks - I wasn't thinking about the Information Editor...
I know a number of our users have liked this option; some use it more heavily than others. Unless another mechanism is in the works to replace this, it would be nice to keep.

**Comment by nathandunn** [comment]
We’ll definitely have it, just was not sure if it needs to be in our initial 2.0.0 release or not (vs 2.0.1 vs 2.1).  
I have the same question for canned comments.

I just need to know either way for planning.

Nathan

**Comment by mpoelchau** [comment]
You could probably get away with implementing the Status field in a later version of WA. I don't know how heavily other groups rely on it, though. 

We got a number of complaints when we tried to do away with the Canned Comments, so it would be great if you could implement those in 2.0.0. Also, I think if the 'Status' option is unavailable for a couple of releases, the canned comments should be there as an alternative method to designate whether a model should be deleted or the like.

**Comment by nathandunn** [comment]
Thanks @mpoelchau  and @childers   I'll move this one to 2.0.1 and leave the canned comments  #70  for here.

**Comment by nathandunn** [comment]
@mpoelchau  @childers   My implementation for Canned Comments made this too easy not to do.   Maybe we can review this on Thursday.    Probably worth looking at again whenever Gary has a chance.  Mostly I just want to make sure this works for your workflow and then when can gussy up the interface later.

**Comment by mpoelchau** [comment]
Great! I think the VectorBase folks use the Status option, so they would also appreciate it if it made it into WA 2.0.0. Let us know when we should pull to test (and perhaps they will be willing to test, as well).

**Comment by nathandunn** [comment]
I think its safe to test this one.   It is up on icebox and it seems to be working, though Moni has not tested it yet.  

Nathan

**Comment by mpoelchau** [comment]
Just checked on icebox - The UI works, but the gff3 export needs a tag for the status (i.e. should say 'status=Approved;' instead of 'Approved;'. It also looks like it's concatenated by a comma with the value of the Notes field. Here's the gff3 output for an mRNA I just created:

Group16.4	.	mRNA	1591786	1594913	.	-	.	=Needs more data!!!,Approved;Name=status;date_creation=2015-04-14;Owner=monica.poelchau@ars.usda.gov;Parent=24b7b1f7-4ba0-4bba-95a4-1dfe87f8952f;status=Approved;ID=576bf7c7-415d-4905-8b69-36b55cb10831;Note=Needs more data!!!;date_last_modified=2015-04-14

**Comment by nathandunn** [comment]
@deepakunni3   Just looks like status needs to be fixed for the GFF3 export.

**Comment by deepakunni3** [comment]
At, Gff3HandlerService:327, currently there was no check for a scenario where getTag() returns null. Hence we see a blank followed by =Approved in the GFF3 export.
featureProperties with a null tag value are generic properties and are handled separately.

**Comment by monicacecilia** [comment]
"Status" is now supported and different statuses can be configured by admin.
The ease of creating statuses, canned comments, and feature types is pretty rocking. 
#NoConfigs :grimacing:
