### ISSUE TITLE
gff3_config.xml is not included when the warfile is created

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#323]
The title sums up the problem.  The lack of gff3_config.xml breaks exporting gff and fasta sequences.  Has anyone else noticed this behavior?  Copying the config file in place once everything is unpacked restores export functionality.

This is for release 1.0.4.

**Comment by nathandunn** [comment]
@childers   That is by design.   

You can still do annotations without it, but you have to create a gff3_config.xml.  There is a warning, but no an error.

I can throw an error if they are there if they are considered essential. 

Nathan

**Comment by childers** [comment]
@nathandunn I did create the gff3_config.xml and place it in the base directory along with the other configuration files. I understand that it might be designed that way, but I didn't see any documentation for where I would need to have that file for it to get incorporated into the WAR.  

It does throw an internal server error which is visible in two different places. Since the export gff3 and fasta options are available, tomcat throws an exception that the needed config file is missing. There is also an error box in the WA interface, so users get to see an error, something I never like hearing about especially when I thought I had done everything needed for exports to work.

**Comment by nathandunn** [comment]
So it looks like this was fixed after the 1.0.4 release (shoot, sorry). 

So, the way it works now (after 1.0.04) is that it copies in a “default_gff3_config.xml” to gff3_config.xml and then it copies over any customized gff3_config.xml.  Same for FASTA, canned_comments, etc.

If you pull out of the 1.0 branch those changes should be in there.  

In the interim . . . in the 1.0.4 release, the gff3_config.xml is source-controlled (grrr) in the src/webapp/config directory.   You can still copy over it and then do a war.  

Feel free to contact me on Skype.  

Nathan

**Comment by childers** [comment]
Is there a post 1.0.4 official release? 
The fix itself was straightforward without needing a restart (just copied in my custom config file). I was mostly worried that this was an issue that had larger ramifications.  I don't like the idea of my config files disappearing.  Thanks for explaining the issue.

**Comment by nathandunn** [comment]
There is not, yet.   We’ll discuss it at this Thursday’s meeting.  You guys are welcome to attend.

Nathan

**Comment by nathandunn** [comment]
confirmed that this is so on the build
