### ISSUE TITLE
Small problem with group/user panel causes organism list to be blank in 2.0

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#324]
Procedure:

1. navigate to the user/group panel on the sidebar
2. while the "detail" tab on the lower pane is selected, select a user from the list of users in the top pane
3. then switch to the "organism" tab on the lower pane

This will cause the organism list to be empty

Example bug behavior (organism list empty):
![screenshot-localhost 8080 2015-04-29 14-10-41](https://cloud.githubusercontent.com/assets/6511937/7399373/1966a6a2-ee7b-11e4-9f87-3bb4ae11e687.png)

Expected behavior:
![screenshot-localhost 8080 2015-04-29 14-22-29](https://cloud.githubusercontent.com/assets/6511937/7399399/437b2b2a-ee7b-11e4-81cd-c6ea6f4c026b.png)

**Comment by cmdcolin** [comment]
corresponded with @nathandunn about this

**Comment by cmdcolin** [comment]
Should be fixed now

**Comment by monicacecilia** [comment]
Yes, this has been fixed. Thank you.
