### ISSUE TITLE
AnnotatorPanel fix label for type of row 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#326]
Just need to change the label to "transp elem" or something shorter.

![screen shot 2015-04-29 at 2 39 41 pm](https://cloud.githubusercontent.com/assets/751274/7402053/a9a3bc30-ee7d-11e4-9298-d4fe8bfa6a89.png)

**Comment by cmdcolin** [comment]
I like the "maxlength" that is done for the usernames so it just does a ... after a few characters

**Comment by nathandunn** [comment]
I'd rather just have a label .  . e.g., we should never show underscores in a label.

**Comment by monicacecilia** [comment]
* "transp elem" seems fine. - unless @selewis has a more refined abbreviation (should we use TE?).
* "repeat reg" should be replaced with "repeat region", or "repeat rgn" if you really need it to be short. That abbreviation is acceptable and appropriate in the sciences (see http://www.allacronyms.com/region/abbreviated). "reg", to me, is more indicative or "regulation" / "regulatory", etc.

**Comment by monicacecilia** [comment]
Thank you.
