### ISSUE TITLE
naming for non-mRNA transcripts are not right

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#328]
![screen shot 2015-04-30 at 1 33 04 pm](https://cloud.githubusercontent.com/assets/751274/7421927/83330b62-ef3d-11e4-98c5-4d9e17b3c825.png)

**Comment by nathandunn** [comment]
Seems to also be a problem for repeat regions and transposable elements.  Names should be identical to the way mRNA's are named (for the most part).

**Comment by nathandunn** [comment]
so in the older code, it names it for the Group its on, which makes more sense.

**Comment by monicacecilia** [comment]
This issue has been fixed.
