### ISSUE TITLE
Can't create annotations if user has admin permissions

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#329]
After creating a new admin login and using this account, I found that I couldn't create or view annotations. I then realized that I needed to give myself read and write permissions. After doing so and refreshing the browser, I can only see three tabs: Annotations, Tracks, and Ref Sequence; I still can't see the annotations. (I noticed these three problems in sequence, so I'm assuming they're related...). I also ran into the same problem with your account on icebox, Nathan (guess I shouldn't be messing with your permissions :) ):
![screen shot 2015-05-01 at 7 49 57 am 2](https://cloud.githubusercontent.com/assets/5487172/7431061/e9cd0996-efd7-11e4-91b0-1458962c1a0c.png)

**Comment by nathandunn** [comment]
I reloaded everything and I am not seeing that problem.  If the user has a global role of "admin", they will be able to see everything. 

Colin is actively working on #283 so that folks should be able to see organisms in the organism tab even if they can't edit them.

**Comment by nathandunn** [comment]
@mpoelchau   Anyway, let me know if / how this is working now.

**Comment by mpoelchau** [comment]
By reload - do you mean clear your browser cache, or re-build WA?

I can now see all tabs on the icebox WA instance under your login, but I still can't create annotations. *Update* - actually, I think I can - it just takes > 5 minutes for the annotation to visualize (refreshing the browser doesn't help). So, perhaps creating an annotation would be another point at which to trigger the 'loading...' pop-up. 

Even after clearing the cache on our own WA instance, I still only have three tabs (Using firefox 37.0.2). Chris has observed the same behavior on our instance. It doesn't look like I can create annotations, but maybe I haven't waited long enough...

**Comment by nathandunn** [comment]
@mpoelchau    @childers

Issue 1 - unable to add annotations: Can you tell me what organism / sequence / annotation you are working on ?    It is working fine on Icebox under chrome for me.   Also, if they do show up, but are *REALLY* slow, let me know what annotations they are.    Bonus points if it is honeybee / Group1.10 . . but not necessary.

Issue 2 - tabs not showing up when admin:  I removed my entire database.  A less drastic measure would be to drop the preferences table (which records specific organisms) while tomcat is down and then reload:

    drop table preference cascade ;

**Comment by mpoelchau** [comment]
Issue 1 - I've been trying honeybee (group 1.10) and yeast (chr II). I manged to create 1 annotation in yeast out of several attempts. *update* - annotation YBR086C-00001 on yeast chrII just popped up after about a 5 minute wait. Better late than never! 

This is the URL I've been using, in case that's changed: http://icebox.lbl.gov/Apollo2/annotator/index

**Comment by nathandunn** [comment]
@mpoelchau   

Something weird is going on.  Following your link it is almost instantaneous for me (for yeast).  

Do you have time to ping me on Skype?  I'll send details.

**Comment by nathandunn** [comment]
If you have any relevant info from your console (from when you add an annotation) that would be helpful.

Thanks.

**Comment by nathandunn** [comment]
So @mpoelchau  tried the usda (pure tomcat but behind a firewall) and icebox (firewall?, tomcat + nginx) from a government office.  Results:
- usda: very slow and intermittent results
- icebox: same result as USDA (also a lot of socket errors).  Most functions worked . .. eventually. 
- icebox / tomcat:  worked perfectly! 

@mpoelchau  Is going to try again from home with icebox to see if its any different.

**Comment by nathandunn** [comment]
@cmdcolin   Have you noticed anything bizarre with your servers like this?

**Comment by cmdcolin** [comment]
I have noticed it takes a little longer (and sometimes, much longer) to add transcripts with tons of subfeatures. Sometimes it is shorter though, so it depends.

I have also identified those cacheing issues and the websocket issue. I guess I'm just trying to narrow down concrete things

**Comment by cmdcolin** [comment]
I haven't had much progress on the admin vs user behavior on the sidebar tabs though so I'll try and catch up with that

**Comment by nathandunn** [comment]
@cmdcolin .. I should specify, I was more wondering if you’d been able to create annotations.  I’m assuming so.  I think the admin tabs piece has been fixed.

Nathan

**Comment by nathandunn** [comment]
If you can identify some of the annotations that take longer (and how long) we can try to optimize them.  I’ve yet to try and optimize any of these.  

Nathan

**Comment by cmdcolin** [comment]
I get this error if I create a new user, assign permissions for that user, and then login as that user. this user will also have disappearing tabs as well, so this could be related to this issue


    i| Error 2015-05-08 11:44:59,122 [http-bio-8080-exec-5] ERROR errors.GrailsExceptionResolver  - ValidationException occurred when processing request: [POST] /apollo/sequence/getSequences/ - parameters:
    sort: length
    asc: true
    start: 0
    name: 
    length: 20
    Validation Error(s) occurred during save():
    - Field error in object 'org.bbop.apollo.UserOrganismPreference' on field 'currentOrganism': rejected value [null]; codes [org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable.error.org.bbop.apollo.UserOrganismPreference.currentOrganism,org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable.error.currentOrganism,org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable.error.java.lang.Boolean,org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable.error,userOrganismPreference.currentOrganism.nullable.error.org.bbop.apollo.UserOrganismPreference.currentOrganism,userOrganismPreference.currentOrganism.nullable.error.currentOrganism,userOrganismPreference.currentOrganism.nullable.error.java.lang.Boolean,userOrganismPreference.currentOrganism.nullable.error,org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable.org.bbop.apollo.UserOrganismPreference.currentOrganism,org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable.currentOrganism,org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable.java.lang.Boolean,org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable,userOrganismPreference.currentOrganism.nullable.org.bbop.apollo.UserOrganismPreference.currentOrganism,userOrganismPreference.currentOrganism.nullable.currentOrganism,userOrganismPreference.currentOrganism.nullable.java.lang.Boolean,userOrganismPreference.currentOrganism.nullable,nullable.org.bbop.apollo.UserOrganismPreference.currentOrganism,nullable.currentOrganism,nullable.java.lang.Boolean,nullable]; arguments [currentOrganism,class org.bbop.apollo.UserOrganismPreference]; default message [Property [{0}] of class [{1}] cannot be null]
    . Stacktrace follows:
    Message: Validation Error(s) occurred during save():
    - Field error in object 'org.bbop.apollo.UserOrganismPreference' on field 'currentOrganism': rejected value [null]; codes [org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable.error.org.bbop.apollo.UserOrganismPreference.currentOrganism,org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable.error.currentOrganism,org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable.error.java.lang.Boolean,org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable.error,userOrganismPreference.currentOrganism.nullable.error.org.bbop.apollo.UserOrganismPreference.currentOrganism,userOrganismPreference.currentOrganism.nullable.error.currentOrganism,userOrganismPreference.currentOrganism.nullable.error.java.lang.Boolean,userOrganismPreference.currentOrganism.nullable.error,org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable.org.bbop.apollo.UserOrganismPreference.currentOrganism,org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable.currentOrganism,org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable.java.lang.Boolean,org.bbop.apollo.UserOrganismPreference.currentOrganism.nullable,userOrganismPreference.currentOrganism.nullable.org.bbop.apollo.UserOrganismPreference.currentOrganism,userOrganismPreference.currentOrganism.nullable.currentOrganism,userOrganismPreference.currentOrganism.nullable.java.lang.Boolean,userOrganismPreference.currentOrganism.nullable,nullable.org.bbop.apollo.UserOrganismPreference.currentOrganism,nullable.currentOrganism,nullable.java.lang.Boolean,nullable]; arguments [currentOrganism,class org.bbop.apollo.UserOrganismPreference]; default message [Property [{0}] of class [{1}] cannot be null]
        Line | Method
    ->>   36 | $tt__getCurrentOrganism          in org.bbop.apollo.PreferenceService
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
    |     14 | getCurrentOrganismForCurrentUser in     ''
    |    205 | $tt__getSequences . . . . . . .  in org.bbop.apollo.SequenceController
    |    198 | doFilter                         in grails.plugin.cache.web.filter.PageFragmentCachingFilter
    |     63 | doFilter . . . . . . . . . . . . in grails.plugin.cache.web.filter.AbstractFilter
    |    449 | executeChain                     in org.apache.shiro.web.servlet.AbstractShiroFilter
    |    365 | call . . . . . . . . . . . . . . in org.apache.shiro.web.servlet.AbstractShiroFilter$1
    |     90 | doCall                           in org.apache.shiro.subject.support.SubjectCallable
    |     83 | call . . . . . . . . . . . . . . in     ''
    |    383 | execute                          in org.apache.shiro.subject.support.DelegatingSubject
    |    362 | doFilterInternal . . . . . . . . in org.apache.shiro.web.servlet.AbstractShiroFilter
    |    125 | doFilter                         in org.apache.shiro.web.servlet.OncePerRequestFilter
    |   1145 | runWorker . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor
    |    615 | run                              in java.util.concurrent.ThreadPoolExecutor$Worker
    ^    744 | run . . . . . . . . . . . . . .  in java.lang.Thread

**Comment by cmdcolin** [comment]
Perhaps currentOrganism can be a nullable field?

**Comment by cmdcolin** [comment]
Also a new break statement needs to be added: otherwise the switch case would apply the permissions but then remove the tabs unnecessarily:

    diff --git a/src/gwt/org/bbop/apollo/gwt/client/MainPanel.java b/src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
    index 5670a31..67fec7d 100644
    --- a/src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
    +++ b/src/gwt/org/bbop/apollo/gwt/client/MainPanel.java
    @@ -240,6 +240,7 @@ public class MainPanel extends Composite {
                     GWT.log("setting to EXPORT permissions");
                 case READ:
                     GWT.log("setting to READ permissions");
    +                break;
                 case NONE:
                 default:
                     GWT.log("setting to no permissions");


I can push that out

**Comment by cmdcolin** [comment]
As per discussion on  #283 the non-admin users are not going to be allowed to see the "admin type" tabs.

This can remain marked as "Ready" I think, but just observe that caveat about non-admin users. Admin users for specific organisms will not be able to create new organisms, but perhaps they will be allowed to create new users and add permissions for that user on their specific organism.

**Comment by nathandunn** [comment]
@cmdcolin   That sounds perfect . .

**Comment by cmdcolin** [comment]
From my quick tests, what I described should be the behavior that exists currently.

**Comment by monicacecilia** [comment]
this issue wins for the one with most name changes. 
Thanks @cmdcolin! I can confirm all the described behaviour is as expected. I closed #283 as well. 
Thanks @mpoelchau for the heads up!
:dancer:
