### ISSUE TITLE
GFF3 exports bad coordinates

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#33]
2014-10-04 22:59 GMT-04:00 Daniel Hughes <dsth@cantab.net>:
aha, the very last buggy model:

gff is 1-based coordinates - but the problem is probably the same sort of thing as before given the GBOL that follows the gff - it'd take looking at it properly to see what's going on as updating the start to either 1 or 2 results in stops in the coding sequence:

##sequence-region Scaffold6154 1 10437
Scaffold6154    WebApollo       gene    0       7739    .       +       .       Name=A464CB0E837997D1C1D87DDEDDB8E0BB;date_creation=2014-07-2;owner=hughrobe@uiuc.edu;ID=A464CB0E837997D1C1D87DDEDDB8E0BB;date_last_modified=2014-07-2
Scaffold6154    WebApollo       mRNA    0       7739    .       +       .       Name=Scaffold6154:75-606;date_creation=2014-07-2;Parent=A464CB0E837997D1C1D87DDEDDB8E0BB;owner=hughrobe@uiuc.edu;ID=CC2EB7C7C3624151D93F1A98191540FA;date_last_modified=2014-07-2
Scaffold6154    WebApollo       exon    0       726     .       +       .       Name=3D2A22D0A9059B01D465618B00B659BB;date_creation=2014-07-2;Parent=CC2EB7C7C3624151D93F1A98191540FA;owner=hughrobe@uiuc.edu;ID=3D2A22D0A9059B01D465618B00B659BB;date_last_modified=2014-07-2
Scaffold6154    WebApollo       CDS     2       726     .       +       0       Name=CC2EB7C7C3624151D93F1A98191540FA-CDS;date_creation=2014-07-2;Parent=CC2EB7C7C3624151D93F1A98191540FA;owner=hughrobe@uiuc.edu;ID=CC2EB7C7C3624151D93F1A98191540FA-CDS;Note=Manually set translation start;date_last_modified=2014-07-2
Scaffold6154    WebApollo       CDS     7449    7725    .       +       2       Name=CC2EB7C7C3624151D93F1A98191540FA-CDS;date_creation=2014-07-2;Parent=CC2EB7C7C3624151D93F1A98191540FA;owner=hughrobe@uiuc.edu;ID=CC2EB7C7C3624151D93F1A98191540FA-CDS;Note=Manually set translation start;date_last_modified=2014-07-2
Scaffold6154    WebApollo       exon    7449    7739    .       +       .       Name=81268E97CF1F24E9DC7053C58897FB0D;date_creation=2014-07-2;Parent=CC2EB7C7C3624151D93F1A98191540FA;owner=hughrobe@uiuc.edu;ID=81268E97CF1F24E9DC7053C58897FB0D;date_last_modified=2014-07-2

typename : gene, type : sequence:gene - chado uniquename : A464CB0E837997D1C1D87DDEDDB8E0BB : -1 - 7739
 typename : mRNA - chado uniquename : CC2EB7C7C3624151D93F1A98191540FA : -1 - 7739
  typename : exon - chado uniquename : 3D2A22D0A9059B01D465618B00B659BB : -1 - 726
  typename : CDS - chado uniquename : CC2EB7C7C3624151D93F1A98191540FA-CDS : 1 - 7725
  typename : exon - chado uniquename : 81268E97CF1F24E9DC7053C58897FB0D : 7448 - 7739

=======

before i forget - the GBOL versions:

typename : gene, type : sequence:gene - chado uniquename : 2C0BB5880CD39A3BC6DCD557B7E51543 : 2147483647 - -2147483648
 typename : mRNA - chado uniquename : D3D8D326733984FD60F20D6C98668F7E : 2147483647 - -2147483648
  typename : CDS - chado uniquename : D3D8D326733984FD60F20D6C98668F7E-CDS : 258637 - 

typename : gene, type : sequence:gene - chado uniquename : B38042A319EE29716CDD8F798F737ADD : 2147483647 - -2147483648
 typename : mRNA - chado uniquename : 9208823E7608CEE5F5BC46775904F31E : 2147483647 - -2147483648
  typename : CDS - chado uniquename : 9208823E7608CEE5F5BC46775904F31E-CDS : 913924 - 913936

typename : gene, type : sequence:gene - chado uniquename : E75DF9601260F1A386B30CA0191F3AD3 : 2147483647 - -2147483648
 typename : mRNA - chado uniquename : EBED00783D648B17E71C60DD46CA6FEF : 2147483647 - -2147483648
  typename : CDS - chado uniquename : EBED00783D648B17E71C60DD46CA6FEF-CDS : 912483 - 912513

======

first chance i've had to look at this since last week and was just building an ensembl db to simplify a few tasks when i noticed there seems to be what i'm guessing is a 32-bit signed integer overflow issue for coords:

2^31=2147483648

Scaffold1001    WebApollo       gene    -2147483648     -2147483648     .       -       .       Name=2C0BB5880CD39A3BC6DCD557B7E51543;date_creation=2014-04-13;owner=gyocum;ID=2C0BB5880CD39A3BC6DCD557B7E51543;date_last_modified=2014-04-13
Scaffold1001    WebApollo       mRNA    -2147483648     -2147483648     .       -       .       Name=Scaffold1001:258637-258738;date_creation=2014-04-13;Parent=2C0BB5880CD39A3BC6DCD557B7E51543;owner=gyocum;ID=D3D8D326733984FD60F20D6C98668F7E;date_last_modified=2014-04-13
Scaffold51      WebApollo       gene    -2147483648     -2147483648     .       -       .       Name=B38042A319EE29716CDD8F798F737ADD;date_creation=2014-04-19;owner=gyocum;ID=B38042A319EE29716CDD8F798F737ADD;date_last_modified=2014-04-19
Scaffold51      WebApollo       mRNA    -2147483648     -2147483648     .       -       .       Name=Scaffold51:913919-913967;date_creation=2014-04-19;Parent=B38042A319EE29716CDD8F798F737ADD;owner=gyocum;ID=9208823E7608CEE5F5BC46775904F31E;date_last_modified=2014-04-19
Scaffold51      WebApollo       gene    -2147483648     -2147483648     .       +       .       Name=E75DF9601260F1A386B30CA0191F3AD3;date_creation=2014-04-19;owner=gyocum;ID=E75DF9601260F1A386B30CA0191F3AD3;date_last_modified=2014-04-19
Scaffold51      WebApollo       mRNA    -2147483648     -2147483648     .       +       .       Name=Scaffold51:912412-912513;date_creation=2014-04-19;Parent=E75DF9601260F1A386B30CA0191F3AD3;owner=gyocum;ID=EBED00783D648B17E71C60DD46CA6FEF;date_last_modified=2014-04-19

dan

**Comment by nathandunn** [comment]
@deepakunni3   Can you verify that this does or does not work.   Can kick to 2.0.1 if no time.

**Comment by monicacecilia** [comment]
@nathandunn shares that this is fixed and we won't see the error again on 2.0. If this resurfaces, please let us know.
