### ISSUE TITLE
(2h) creating organism UI improvements

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#330]
1 - when creating an organism should use fire off the "Loading Dialog" until all loading is done on the organism tab.
1a - when deleting should say "Deleting ..."
1b - if changing refseq data / refreshing should mimic 1)
2 - the state of the organism tab should look like it does on reload:

![screen shot 2015-05-01 at 9 46 21 am](https://cloud.githubusercontent.com/assets/751274/7433524/fb062b8e-efe6-11e4-88be-7cd6947c7b93.png)

**Comment by cmdcolin** [comment]
I think I fixed these errors and commented on #301 about it

**Comment by nathandunn** [comment]
@cmdcolin   Looks great.  Thanks!

**Comment by monicacecilia** [comment]
:+1:
