### ISSUE TITLE
when changing organism, reload / clear refseq data for current organism

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#331]
Expect just the two yeast chromosomes.   

1 - Subscribe to the "organism loaded / changed" event
2 - clear "search"
3 - re-execute search

![screen shot 2015-05-01 at 9 48 50 am](https://cloud.githubusercontent.com/assets/751274/7433546/4b02e1e0-efe7-11e4-9add-bc14945892d7.png)

**Comment by monicacecilia** [comment]
This is working.
