### ISSUE TITLE
(2h) transcript coding editing screen should be "blank" if no coding sequence is selected

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#334]

**Comment by nathandunn** [comment]
@deepakunni3   If nothing is selected in the coding panel, we shouldn't show anything on the right hand-side as its unclear what is being selected.   

I think its an easy matter of just setting that panel visibility to false when the selectionHandler has nothing selected.

![screen shot 2015-05-13 at 8 59 11 am](https://cloud.githubusercontent.com/assets/751274/7614844/618bf2ec-f94e-11e4-9265-d145915eb1d8.png)

**Comment by deepakunni3** [comment]
@nathandunn Ready for testing and feedback.

**Comment by nathandunn** [comment]
@deepakunni3   Made a small tweak here, to hide when it unselects, but other than that looks great.

**Comment by deepakunni3** [comment]
:+1:

**Comment by monicacecilia** [comment]
It took quite an explanation to understand this behavior (but at this moment I lack a suggestion for a better alternative). This issue is corrected.
