### ISSUE TITLE
(2h) Coding tab disappears after modifying exon boundaries

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#335]
After modifying the boundaries of an exon for a given transcript, the "Coding" tab disappears from the bottom portion of the panel on the right. 
The tab is only visible again after "closing" the gene (i.e. hiding all the transcripts) and re-opening it.

**Comment by nathandunn** [comment]
@deepakunni3   I made a small tweak but looks ready.

**Comment by nathandunn** [comment]
@deepakunni3   Works perfectly.  I think this is a lot more elegant (and correct) than what I had.

**Comment by monicacecilia** [comment]
Thanks!
