### ISSUE TITLE
(1d) API authorization improvements needed

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#337]
Background: I noticed that when my session was expired, I could still play around inside the app. This led me to formalize this problem and I created a scenario where I could create a feature via the command line even when I was not logged in

Example: First run a git pull...just added the script. Then take a username that you know exists on our server and then run this command using that for the --username parameter (Sorry, ignore the really long --featuredata...it is just for the example...)

    perl client/apollo/tests/perl_tests/test_add_feature_not_logged_in.pl --username colin.diesh@gmail.com --url http://localhost:8080/apollo --featuredata '[{"location":{"fmin":383802,"fmax":501601,"strand":-1},"type":{"cv":{"name":"sequence"},"name":"mRNA"},"name":"GB42156-RA","children":[{"location":{"fmin":383802,"fmax":386863,"strand":-1},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"fmin":383802,"fmax":387151,"strand":-1},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"fmin":388514,"fmax":388871,"strand":-1},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"fmin":390098,"fmax":390391,"strand":-1},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"fmin":390611,"fmax":390964,"strand":-1},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"fmin":392553,"fmax":392854,"strand":-1},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"fmin":395196,"fmax":395323,"strand":-1},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"fmin":426566,"fmax":426716,"strand":-1},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"fmin":433180,"fmax":433330,"strand":-1},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"fmin":501556,"fmax":501601,"strand":-1},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"fmin":386863,"fmax":501601,"strand":-1},"type":{"cv":{"name":"sequence"},"name":"CDS"}}]}]' --track Group1.1

You'll note that this annotation will be accepted and added without any login taking place. In the 1.0 branch, this wouldn't happen, and you would first have to login (see test_add_feature.pl for example of how that worked in 1.0)

**Comment by nathandunn** [comment]
@cmdcolin   So this is interesting.    This is a function of the fact that we allow it to be called from a websocket, as well, and we'll lose the session. 

In AEC we want it to check for the user session and that it has write permission.  We can assume that the websocket is already secure once established.  

So, in *AEC::addFeature* we need:

 - if Session.session(false) == null 
 - login with username / password credentials and throw PermissionException if failure  
 - if Session.principal.subject is there, make sure it matches what is on the inputObject. 
 - check permissions for user versus organism (see permissionService)

The login code should mirror LoginController code . . . though you can probably check user permissions first:

            Subject subject = SecurityUtils.getSubject();
            Session session = subject.getSession(true);
            subject.login(authToken)
            session.setAttribute("username", username);
            session.setAttribute("permissions", new HashMap<String, Integer>());

            User user = User.findByUsername(username)
            Map<String, Integer> permissions = permissionService.getPermissionsForUser(user)
            if(permissions){
                session.setAttribute("permissions", permissions);
            }
            JSONObject responseJSON = new JSONObject();
            render responseJSON as JSON

**Comment by nathandunn** [comment]
@cmdcolin   I think you can test and close this when you have a moment.

**Comment by cmdcolin** [comment]
The get_sequence function is now failing in PermissionService

    JSONObject["username"] not found.. Stacktrace follows:
    Message: JSONObject["username"] not found.
        Line | Method
    ->>  613 | $tt__checkPermissions in org.bbop.apollo.PermissionService$$EPCTomiW
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    |    801 | hasPermissions        in org.bbop.apollo.AnnotationEditorController$$EPCTomiW
    |    528 | getSequence . . . . . in     ''
    |    198 | doFilter              in grails.plugin.cache.web.filter.PageFragmentCachingFilter
    |     63 | doFilter . . . . . .  in grails.plugin.cache.web.filter.AbstractFilter
    |     68 | handleOperation       in org.bbop.apollo.AnnotationEditorController$$EPCTomiW
    |    198 | doFilter . . . . . .  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
    |     63 | doFilter              in grails.plugin.cache.web.filter.AbstractFilter
    |    449 | executeChain . . . .  in org.apache.shiro.web.servlet.AbstractShiroFilter
    |    365 | call                  in org.apache.shiro.web.servlet.AbstractShiroFilter$1
    |     90 | doCall . . . . . . .  in org.apache.shiro.subject.support.SubjectCallable
    |     83 | call                  in     ''
    |    383 | execute . . . . . . . in org.apache.shiro.subject.support.DelegatingSubject
    |    362 | doFilterInternal      in org.apache.shiro.web.servlet.AbstractShiroFilter
    |    125 | doFilter . . . . . .  in org.apache.shiro.web.servlet.OncePerRequestFilter

**Comment by nathandunn** [comment]
I might need to double check if it's still organism specific. 

Nathan

**Comment by nathandunn** [comment]
Should be fixed for both the web interface and web services now. 

Nathan

**Comment by nathandunn** [comment]
@cmdcolin   Can this be closed?

**Comment by cmdcolin** [comment]
This particular issue seems fixed now.
