### ISSUE TITLE
Persistent red bar

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#338]
From #266 

One curious -and annoying- thing: this does not happen all the time, but at times, using a Mac, I am unable to get rid of the red bar that appears after a screen capture. 
* The red bar indicating the coordinates can be brought up by holding down the shift key.
* When you use the keyboard to capture a screenshot while using Apollo in a Mac, the red bar persists and you can eliminate it by holding the shift key momentarily. 
* On Apollo2, while viewing the JB window + panel on the right, the red bar does not always appear after screen captures, but when it does it is not possible to make it go away with the shift key. I have to reload the page. 
* If viewing Apollo2 on "Full-screen view", the behavior is as it was with 1.0.x. 
It seems curious, and I guess this likely also has to do with GWT and JB communication. 

It is absolutely not a show-stopper, but a rather annoying bug. It would be great if this did not happen.

![screen shot 2015-05-01 at 3 29 03 pm](https://cloud.githubusercontent.com/assets/1714621/7438382/3b791fc4-f018-11e4-89a1-ab19310404b5.png)

**Comment by nathandunn** [comment]
@cmdcolin   Might have some insight into this.   The only other thing I can thing of is that its because its an iFrame in JBrowse.

**Comment by cmdcolin** [comment]
I'm sort of familiar with the general issue here when taking screenshots but i haven't seen this happen really. Is it still a problem?

**Comment by nathandunn** [comment]
I haven't seen it.  My guess is that it has more to do with the iFrame.
