### ISSUE TITLE
(2h) unique names are ONLY organism specific

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#339]

**Comment by nathandunn** [comment]
From #258 . . 

 @monicacecilia  Ah . . so it should be unique name "per organism"? i.e. ,I can have identical gene names, so long as they belong to other organisms?

@ndunn The "a" "b" ., etc. is a way to provide unique gene names. We want folks to customize this eventually.

@monicacecilia commented an hour ago
Yes, unique names per organism. The scenario in which we will be looking at two different organisms with exactly the same gene names is unlikely. In the unlikely case that this were necessary, one would identify the names of the genes in some other way, by adding a prefix, or something similar. At any rate, I can explain this in greater length to you at a later time; for now, yes, unique name per organism. Do not include the a, b, stuff.

**Comment by nathandunn** [comment]
Also related to: #341

**Comment by selewis** [comment]
I'm not sure I agree. But that depends on whether we're discussing "names"
(labels for the users) or "IDs" (and not the internal DB kind, but the
longer term ID).

For names, sure then I agree

But if (lacking a user provided name) we're discussing an identifier then
it needs to be globally unique.So if we are stubbing in the ID, when a name
isn't provided by the user, then these should -not- be shared across
organisms.

-S

**Comment by nathandunn** [comment]
Just names.    Have have to have a sox6 hum, mouse, zebrafish (and who knows what else), so they have to share symbol and name, but each one would be uniquely identified. 

The unique ID’s are globally unique.

Nathan

**Comment by cmdcolin** [comment]
Are we still using the GUID as the ID? Is there any particular reason we aren't just using a more simple ID naming system like autoincrementing with a organism prefix? I feel like having easy-to-use IDs goes a long way for making better systems (like refseq and ensembl ids).

Dr Elsik always says, the identifier problem is actually hard and it is getting worse....need to enable things like http://useast.ensembl.org/info/genome/stable_ids/index.html?redirect=no

**Comment by nathandunn** [comment]
The database internally uses an auto incrementing ID as is standard with relational databases.

We are also using a UUID (which is the same thing as a GUID).  

This allows us to associate a global identifier, between GFF3’s, etc. with a single piece of data.  If data is migrated between systems / formats, etc. we can re-correlate it. 

I don’t like having identifiers “mean” anything other than being globally unique.    The entire point is to have relevant meta-data associated with the UUID in the first place (like a name, or links into other associations).    Its kind of like having database keys also used for display.   You can do it, but you are obfuscating the roles and will eventually run into trouble.   

Nathan

**Comment by cmdcolin** [comment]
This trello card for this issue says
```
ID: 
should follow a scheme, for example a convention of letters 
(can be assigned by each research group; should be easily configured, e.g. when installing WA) 
and numbers in incremental order. 

The IDs generated using this scheme will become default IDs and names*.
```

Is there anything that has changed about this that makes us want to use GUID? I think that the trello card is quite sensible about this configuration.

**Comment by nathandunn** [comment]
That is in reference to the transcript and gene names / symbols, not the unique ID’s or internal database representations.

Typically we’ll only interact with the latter when doing things like merges and to maintain the data internally.  

Nathan

**Comment by cmdcolin** [comment]
Ok well the thing that is described on that trello board is not yet implemented is it?

**Comment by nathandunn** [comment]
No.  It will be for 2.0.1 via bug https://github.com/GMOD/Apollo/issues/341 <https://github.com/GMOD/Apollo/issues/341>  #341.


Nathan

**Comment by nathandunn** [comment]
Code should exist in a service and look like this:

     boolean isUnique(Organism organism,String name){
                    return (int) Feature.executeQuery("select count(t) from Feature t join t.featureLocation fl join fl.sequence s join s.organism org where org = :org and t.name = :name ",[org:organism,name:newName])==0
    }

and 

    String makeUniqueFeatureName(feature,organism,principalName,paddingStrategy){
         i = 0 
        name = principalName + paddingStrategy.pad(i++)
        while(!isUnique(organism,name)){
             name = principalName + paddingStrategy.pad(i++)
        }
        return name 
    }

**Comment by nathandunn** [comment]
Labelled as important as its a good convention to name orthologous genes the same things where possible.
