### ISSUE TITLE
Overlapper issue 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#34]
- Overlapper issue - Not sure what the deal is, but it might be worth noting that we're using the November 2013 WA version for this particular genome (didn't want to deal with updating issues while people were actively annotating).

**Comment by nathandunn** [comment]
Probably just need to double-check or clarify.

**Comment by monicacecilia** [comment]
Unable to reproduce this. 
Should it arise again after 2.0, let's bring it back. I'm closing for now.
