### ISSUE TITLE
define BLAT external config properly in order to handle non-default BLAT location

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#342]
Related to #88 .  failure occurs rather readily and with a good error.  

Unable to currently create BLAT with a non-standard BLAT location.

**Comment by cmdcolin** [comment]
I put this in my apollo config and it worked fine (loading this alternative binary "blat2" instead of "blat")



    // default username/password on h2 are given here. see docs for adjusting
    dataSource {
        pooled = true
        jmxExport = true
        driverClassName = "org.h2.Driver"
        username = "sa"
        password = ""
    }
    // environment specific settings
    environments {
        development {
            dataSource {
                dbCreate = "update" // one of 'create', 'create-drop', 'update', 'validate', ''
                url = "jdbc:h2:file:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE"
            }
        }
        test {
            dataSource {
                dbCreate = "create-drop" // one of 'create', 'create-drop', 'update', 'validate', ''
                url = "jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE"
            }
        }
    
        //note: not necessarily recommended to use h2 in production mode. see precautions
        production {
            dataSource {
                dbCreate = "update"
                //note: production mode uses file instead of mem database
                url = "jdbc:h2:/opt/apollo/h2/prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE"
                //url = "jdbc:h2:prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE"
                properties {
                   // See http://grails.org/doc/latest/guide/conf.html#dataSource for documentation
                   jmxEnabled = true
                   initialSize = 5
                   maxActive = 50
                   minIdle = 5
                   maxIdle = 25
                   maxWait = 10000
                   maxAge = 10 * 60000
                   timeBetweenEvictionRunsMillis = 5000
                   minEvictableIdleTimeMillis = 60000
                   validationQuery = "SELECT 1"
                   validationQueryTimeout = 3
                   validationInterval = 15000
                   testOnBorrow = true
                   testWhileIdle = true
                   testOnReturn = false
                   jdbcInterceptors = "ConnectionState"
                   defaultTransactionIsolation = java.sql.Connection.TRANSACTION_READ_COMMITTED
                }
            }
        }
    }
    
    
    
    apollo{
        sequence_search_tools {
            blat_nuc {
                search_exe = "/usr/local/bin/blat2"
                search_class = "org.bbop.apollo.sequence.search.blat.BlatCommandLineNucleotideToNucleotide"
                name = "Blat nucleotide"
                params = "-minScore=0 -minMatch=1"
                tmp_dir = "/opt/apollo/tmp"
            }
            blat_prot {
                search_exe = "/usr/local/bin/blat2"
                search_class = "org.bbop.apollo.sequence.search.blat.BlatCommandLineProteinToNucleotide"
                name = "Blat protein"
                params = "-minScore=0 -minMatch=1"
                tmp_dir = "/opt/apollo/tmp"
            }
        }
    }

**Comment by nathandunn** [comment]
Was the original BLAT available to be called (/usr/local/bin/blat)?   

Nathan

**Comment by cmdcolin** [comment]
It was not available and I took some extra steps to verify that the external config was actually loaded, for example, I can change the name attribute to "extconf" or something similar

![screenshot-localhost 8080 2015-05-04 12-39-41](https://cloud.githubusercontent.com/assets/6511937/7458535/c57e183e-f25a-11e4-992e-e67187b43e2b.png)

**Comment by nathandunn** [comment]
Okay . . I'll take a look.  I might have messed something else up somewhere.

**Comment by nathandunn** [comment]
BLAT should be working now.  The deployment script for release was broken.

**Comment by nathandunn** [comment]
Test:  BLAT should work

**Comment by monicacecilia** [comment]
It does.
