### ISSUE TITLE
more tightly reflect ambiguity codes during BLAT

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#344]
@cmdcolin This is a bug in the older code, but the fix is pretty clear .. .  From #88 .  

1 - in SequenceSearch.js this line:
else if (residues.match(/[^ACDEFGHIKLMNPQRSTVWXY\n]/)) {
alert("The sequence should only contain non redundant IUPAC nucleotide or amino acid codes (except for N/X)");
ok = false;
}

2 - should be replaced with an if/else based on the tool selected, which comes through here:

sequenceToolsSelect.value

Would be nice in the drop-down if we could specify the type, but we can just use name for now. Here are the codes (except X/N) apparently.

http://www.dnabaser.com/articles/IUPAC%20ambiguity%20codes.html

Not sure if its worth using this BLAT for comparison:

https://genome.ucsc.edu/cgi-bin/hgBlat?command=start

**Comment by monicacecilia** [comment]
The list of characters ACDEFGHIKLMNPQRSTVWXY takes into account degeneracy of the code (e.g: Y = position could be either pyrimidine, etc) as well as all amino acid one-letter abbreviations.
I know BLAST can take any degeneracy, and by my testing so does BLAT. 

I would have very much like it for us to find a way to tell users they have used the wrong sequence for the Blat option they selected.

Also, @nathandunn I don't understand what you mean by "Here are the codes (except X/N) apparently."

**Comment by monicacecilia** [comment]
Just singing "happy birthday" to this old issue... sheesh. 
Unbelievably enough, we still do not have warnings for users that have entered a nucleotide sequence and are trying to run 'BLAT protein' and the opposite, entered an amino acid sequence and are trying to run 'BLAT nucleotide'. 
Up next... this! :) (after all the "up next" things already in our list).

**Comment by monicacecilia** [comment]
Oh, would you look at that... this issue just turned two! The terrible twos... time.to.do.it. soon. After all the "up next" things already on the list. :bowtie:
