### ISSUE TITLE
(1d left?) Coordinate error in 'set readthrough stop codon'

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#347]
![screen shot 2015-05-05 at 7 16 46 pm](https://cloud.githubusercontent.com/assets/4530272/7485441/89c73a44-f35b-11e4-83fd-a79ea977583c.png)

'Set readthrough stop codon’ extends the CDS to the next in-frame stop codon successfully, but the coordinates of stop_codon_read_through are incorrect.
The purple box here highlights codon ACC.

Other genes with same behavior: GB47747-RA

**Comment by deepakunni3** [comment]
Ready for testing and feedback.

**Comment by nathandunn** [comment]
Haven't put it on the server yet, I'll re-assign it then.

**Comment by monicacecilia** [comment]
Checked GB488994 and GB47747 -- as well as many other models. The coordinates are now appropriate and the codon is highlighted where and when necessary. EXCEPT in #400
