### ISSUE TITLE
(1h) 2.0.0 clean out cruft / old code (LAST)

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#348]
- remove src/main
- remove src/test
- remove any large sets of uncommented code

**Comment by cmdcolin** [comment]
it might be good to do this sooner than later, just to ensure no dependencies are breaking when we remove them?

**Comment by nathandunn** [comment]
One I finish merge / split of transcripts I'll remove the extra stuff.  I also need to move some of your CSS stuff into the assets directory. 

Nathan

**Comment by nathandunn** [comment]
@cmdcolin   Looks like I'd already moved that stuff.  I'll do a final check and then wipe the rest of it.

**Comment by nathandunn** [comment]
Nothing to test . . . it will either work or fail.
