### ISSUE TITLE
(4h) verify / fix rememberme cookie

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#349]
I am not sure if the rememberme cookie is working.  Should have a two-week expire.  

I think it works with the login, but I don't know if the "checkLogin" mechanisms is re-logging in the user after the session expires (30 minutes?).

**Comment by nathandunn** [comment]
2 options for this:  http://shiro.apache.org/session-management.html

1 - on logout tell the client (as we do now)
2 - create click on "touch" for the session when there is any sort of activity

**Comment by nathandunn** [comment]
In theory could attach a sessionListener and fire an event towards the specific user on the websocket.  Not sure where the listener should be attached.  Maybe at login?

**Comment by cmdcolin** [comment]
I was going to work on this one next. I wanted to get the rememberme cookie to work and then look into auto logouts

**Comment by cmdcolin** [comment]
This is sort of only tangentially related, but one thing i saw is that if you login, then clear your cookies and cache, and then drag and drop an annotation, it actually works? I know that the add_transcript is working over websocket so maybe it is different but this was still surprising to me

**Comment by nathandunn** [comment]
Sounds good.  Should just be a matter of integrating with the shiro remember me cookie code.  

Nathan

**Comment by nathandunn** [comment]
The websocket is authenticated at the session level.  Once established you would have to either kill or explicitly invalidate the session (what is done on logout).  Lots of fun moving parts.  

Look at the notes.  Thanks for looking into this.  

Nathan

**Comment by nathandunn** [comment]
@cmdcolin  Just assigning it to you as you said you were working on it.

**Comment by cmdcolin** [comment]
It looks like the "Remember me" feature was already working basically. I tested this by forcing sessions to expire in the tomcat manager app.

**Comment by nathandunn** [comment]
Oh, so it is storing a remember me cookie in the client and using it to login?  

I don’t know if I was able to get it to put the cookie there or not.  

So the behavior I was shooting for was:

1 - if remember-me (checkbox on login that needs to be put back, or we just do this by default), it creates a cookie that automatically that has a hashed login. It will do this until the cookie expires (typically two weeks)
2 - if remember-me is NOT checked (or on logout), the session expiring (30 minutes) forces a reload (or a banking style . .  do you want to refresh your session?).  This will be nice if on the rich app pieces that aren’t always hitting the database so that you aren’t necessarily working off of expired data. 

Anyway, you can let me know what you think / where we are. 

Nathan

**Comment by cmdcolin** [comment]
Number 1 looks like it's working now. Looks like the cookie expiration is 24 hours. Might have to dig a little to see where that is configured.

![t2](https://cloud.githubusercontent.com/assets/6511937/8705372/c4cd0130-2aee-11e5-9b4f-bab76e413993.png)


Number 2 is not implemented yet. I might suggest making it a separate issue.

**Comment by cmdcolin** [comment]
Correction: cookie appears to last one year not one day

**Comment by nathandunn** [comment]
Okay . . I added #480 about the force logout piece.

**Comment by cmdcolin** [comment]
Thanks. It is not exactly clear how to configure it for me but I will mark as ready for now just since it has a clear test case.

**Comment by nathandunn** [comment]
Hmm . . . 

https://github.com/pledbrook/grails-shiro/issues/30

I'm looking through the shiro documentation, I'm not seeing an obvious way to set this internally, you have to get access to the shiro rememberme manager at some point. 

Looks like you can over-ride the rememberMeManager:

securityManager.rememberMeManager.cookie.maxAge = <max_age>

**Comment by nathandunn** [comment]
In the interi, though I agree that this should be good enough.

**Comment by nathandunn** [comment]
@cmdcolin   If you login, wait for 30 minutes and refresh the browser it will log you out still.  If it is using the rememberMe cooking it will use the cookie to re-authenticate.  

http://shiro.apache.org/web.html#Web-RememberMeServices

Anyway, probably not more important than what you are working on now.  If you are seeing something different, then let me know and I'll recheck.

**Comment by nathandunn** [comment]
It is working for @cmdcolin  properly.    @cmdcolin  Will write test conditions.

**Comment by cmdcolin** [comment]
The best way to test this manually is by logging into Web Apollo with the "Remember me" checkbox checked

Then go into the tomcat manager app and force all sessions to expire (see figure), or just wait 30 minutes for the session to expire if you have a lot of patience.

Then refresh Web Apollo and it will automatically be logged in again despite the session being expired (this is similar to how gmail or other sites remember you automatically)

![x2-resize](https://cloud.githubusercontent.com/assets/6511937/8732879/e3758bfc-2bc5-11e5-8e56-1f41e2db7a5c.png)


That will complete the test of the remember me function.

To test that remember me is also disabled when the checkbox is not checked, you can then logout of Web Apollo and re-login without the "Remember me" checkbox checked.

Then do the same thing: expire all the sessions and try refreshing the page. It will then make you re-login since it doesn't have the cookie.

**Comment by nathandunn** [comment]
To test:
1 - logout
2 - login and click on "remember me" 
3 - come back to tomorrow (or after 30 minutes) and verify that when performing an action that you are still logged in

Works for me still.

**Comment by nathandunn** [comment]
this is working
