### ISSUE TITLE
##sequence-region Scaffold6154 1 10437 - 0-base issue

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#35]
The ##sequence-region Scaffold6154 1 10437 - 0-base issue - yep, this is a problem, but I don't understand how this should throw this particular model out of frame, since the CDS starts at bp 2... confused.

**Comment by nathandunn** [comment]
Need to verify / fix.

**Comment by monicacecilia** [comment]
I need more background to test this.

**Comment by cmdcolin** [comment]
While it's unclear how the original problem was generated, I have tried to simulate inputs that might cause problems like this. In once case,  i used my script test_add_feature.pl to generate inputs where fmin/fmax are larger than UINT_MAX (other thread https://github.com/GMOD/Apollo/issues/33#issuecomment-90984341)


For example this command that i mentioned in that thread still has problems with Apollo2

    perl client/apollo/tests/perl_tests/test_add_feature.pl --username nathandunn@lbl.gov --password demo --url http://localhost:8080/apollo --featuredata '[{"location":{"fmin":4294967296,"fmax": 559153,"strand":1},"type":{"cv":{"name":"sequence"},"name":"mRNA"},"name":"TEST4","children":[{"location":{"fmin":559153,"fmax": 559153,"strand":1},"type":{"cv":{"name":"sequence"},"name":"exon"}}]}]' --track Group1.1


This will return a "valid" feature with invalid coordinates (the gff3 results will actually say the start position is -1, not 0)

**Comment by nathandunn** [comment]
@cmdcolin   K . . thanks I'll take a look.

**Comment by nathandunn** [comment]
We won't encounter reference sequences scaffolds larger than an int value.
