### ISSUE TITLE
(2h) reloading app when a very fragmented scaffold is loaded takes minutes

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#350]
Reported by the USDA folks (@childers @mpoelchau).  The brown recluse has about 100K scaffolds.  

Some ideas:
1 -  @cmdcolin also suggested that it might be due to the refseqs file being pulled into JBrowse as well.  However, I think that would just delay JBrowse being loaded, but its hard to say . . it might end up blocking other processes.  Typically JBrowse is loaded only after the panel comes up.
2 - The getAppState code doesn't pull much data in.  . .  However, we calculate the Annotation Count for each organism.   With 100K sequences, this query would likely die horribly.    

            Integer annotationCount = Feature.executeQuery("select count(distinct f) from Feature f left join f.parentFeatureRelationships pfr  join f.featureLocations fl join fl.sequence s join s.organism o  where f.childFeatureRelationships is empty and o = :organism and f.class in (:viewableTypes)",[organism:organism,viewableTypes:requestHandlingService.viewableAnnotationList])[0] as Integer

The relationship is: organism -> sequence -> feature location -> top-level feature 

Two solutions would be:
A - if sequence.count > 10K don't count the annotations or do it as a background process
B - get all sequences for an organism, count(*), feature_locations (vs feature) . . . have to do a sub-query or a join.  

If we can't tune it then we'll probably just do A.

**Comment by nathandunn** [comment]
@childers . . . significantly faster now . .

**Comment by monicacecilia** [comment]
Yes, it is faster.
