### ISSUE TITLE
"feature_id" contstraint

### ISSUE THREAD

**Issue by littlebunch** [GMOD/Apollo#352]
Deploying today's (5/7) pull results in this error in catalina.out when trying to write an annotation:

```Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "feature_id" violates not-null constraint
  Detail: Failing row contains (752703, 0, t, 2015-05-07 10:01:24.605, 5, null, 2015-05-07 10:01:24.605, ADD_TRANSCRIPT, [{"date_creation":1431007284444,"location":{"fmin":197647,"stran..., [], a750cf70-8052-4430-80fc-53bb091b6529,{"operation":"add_transcript","username":"christopher.childers@a...).```

**Comment by nathandunn** [comment]
When we move to official releases I’ll try to automate some of this using liquibase / the database migration plugin .  In the interim I would run:


1 - turn off server
2 - drop table feature_event;
3 - 2 - drop table feature_event_feature ;  — if exists
4 - turn on server

Should re-create these tables properly.

Nathan

**Comment by littlebunch** [comment]
Fixed.  Thanks.

**Comment by nathandunn** [comment]
@mpoelchau  

Can you run `delete from feature_event` ? 

Otherwise yes, follow these instructions: https://github.com/GMOD/Apollo/issues/352#issuecomment-99892331

Once established, hopefully you won't run into this much, but if do, let me konw.

**Comment by mpoelchau** [comment]
Thanks @nathandunn! this solved the problem for some of our gffs but not others. We're exploring other methods for the ones that failed.

**Comment by mpoelchau** [comment]
@nathandunn it's the same gff3 as in #1938. We were using the perl script because the groovy script doesn't load the full metadata. We may check out what @abretaud set up in https://github.com/GMOD/Apollo/pull/1934. Thanks!
