### ISSUE TITLE
(4h) addComment / deleteComment / updateComment  not there

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#355]

**Comment by nathandunn** [comment]
@deepakunni3   Where are you with this one?   I need it for #70 . . . if you are inthemiddle, that' fine, I'll just wait for you to finish up.  Otherwise, I will probably need to take it in order finish up.   Let me know either way.

**Comment by deepakunni3** [comment]
@nathandunn You can take it over if there are other issues depending on addComments.

**Comment by monicacecilia** [comment]
add/delete/update comment is ready and working well. :dancer:
