### ISSUE TITLE
(3d) merging / splitting transcript undo / redo history not working

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#356]
branch:  ~~split-merge-history~~ -> history-tree

- [x] change implementation strategy to use history tree -> childkey, childsplitkey, parent, parentmergekey
- [x] delete / hide alternate histories (future), when doing an insert
- [x] split transcript 
  - [x] write service 
     - [x] tests work
     - [x] wire into code:
       - [x] rename split gene and transcript to something unique 
       - [x] get history for transcript 2  (should be the exact same as 1)
       - [x] getHistoryForFeatures should take in multiple transcripts into account 
  - [x] add integration tests (undo, redo)
     - [x] stub out
     - [x] gene names should be "unique" when stored on split
     - [x] get all tests working (may fix redo as well)
  - [x] UI test
    - [x] show history properly
    - [x] do undo:
      - [x] delete should be pushed actively (if deletion is not on the same transcript)
      - [x] history should be visible on either object
      - [x] should set back to the correct unique name 
      - [x] gene name should be restored (and not made into the transcript)
      - [x] delete should work on undo object
      - [x] history should be visible on undo if from non-split child id
      - [x] retest undo 
      - [x] retest redo 
      - [x] revert to any point in history
- [x] merge transcript 
  - [x] write service 
     - [x] tests work
     - [x] wire into code
  - [x] add integration tests
  - [x] fix integration tests 
    - [x] undo only adds one transcript
  - [x] UI test 
    - [x] show history properly (matches WA1)
    - [x] do undo (not deleting transcripts properly)
      - [x] history should be added to both on undo
      - [x] make sure that underlying data is clean after undo
    - [x] do redo 
    - [x] revert to any point in history
- [x] confirm deletes work throughout 
- [x] delete should NOT force a refresh (error in AnnotationController not handling the websocket properly) - publish event to NOT do update ?

**Comment by nathandunn** [comment]
waiting on #223 approval to start on this one.

**Comment by nathandunn** [comment]
Transaction history . . new JSON array on old feature event is being set incorrectly (With newer Feature Event's two old JSONArray values) when merging transcripts is done.

**Comment by nathandunn** [comment]
show history is working the same as in staging . . . , just showing the single unmerged left-hand transcript

**Comment by nathandunn** [comment]
need to delete the older merges . .

**Comment by nathandunn** [comment]
Redo needs to delete correctly. . .  I think it needs to send through what is to be deleted.

**Comment by nathandunn** [comment]
not deleting the other transcript . . .

**Comment by nathandunn** [comment]
when doing a split . .  make sure to track the other transcript via the other feature_event as an alternate

**Comment by nathandunn** [comment]
@cmdcolin    @deepakunni3  said that you might have bright ideas on this as you've worked on this code before.  I keep running around in circles on this.    It is on "split-merge-history". 

If you have any brilliant insights on this, I would appreciate it.    The current implementation is pretty stateless (it deletes and adds each time, and history is detached), so doing this for 1.0 is fairly reliable.

**Comment by cmdcolin** [comment]
Ya I'll take a look at it

**Comment by nathandunn** [comment]
It occurs to me that uniquenames should have a parent and a child.  We kind of do this with features in a Json array but it's a bit hacky.   

So if no splits or merges then the parent and child uniquename is the same.   Should likely be a hasmany relationship for each.  Not sure if that will be too slow though.

**Comment by nathandunn** [comment]
Conversed with @monicacecilia  .  . the use-cases are reperesented here:

![screen shot 2015-06-10 at 1 47 41 pm](https://cloud.githubusercontent.com/assets/751274/8093870/63116cba-0f78-11e5-8340-ba41504b9b94.png)

In the simple case we use the Memento pattern.   I think the question boils down to this:

    Q: What happens when we go back to a location and then forward another direction?
    A: We ditch history for all prior elements.   

In the case of a split, if either element goes forward in a different direction then all data is lost for both elements prior to the split (i.e., you can not redo the merge).

**Comment by nathandunn** [comment]
The current implementation maintains the alternate history.  This is not wholly bad, since we are stateless, but I think we would need to indicate that in a sort of a git-like fashion.

**Comment by monicacecilia** [comment]
@nathandunn :+1:

**Comment by nathandunn** [comment]
Marked as WA1 bug as a lot of this was not consistently implemented.

**Comment by monicacecilia** [comment]
Fabulous -- up until that part where the "Undo" of the "unset the readthrough" no longer highlights the stop (described in #400) . . . other than that, fabulous. So with the caveat of that issue still being opened, I'll do a cautious happy dance here. :dancer:
