### ISSUE TITLE
(1d) undo / redo behavior for isoforms tracked separately vs gene

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#357]

**Comment by nathandunn** [comment]
I think this actually works on further testing.

**Comment by monicacecilia** [comment]
@nathandunn I don't know what you are describing here. This sounds like a conversation you were having, and then... 

History and undo/redo behavior for each isoform are being tracked separately - although with faults. This is not ready.  -- we are creating new issues to better track this.
