### ISSUE TITLE
(2h) add web-service call for adding organisms

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#360]
will just have name, genus, species, blat dir, data dir

Can be moved to 2.0.1

**Comment by cmdcolin** [comment]
This is probably already available, just needs documentation, and also, of course, the proper permissions via the API to do so. The error reporting was also improved for the organism creation too, so they should be fairly robust once documented

related issues
https://github.com/GMOD/Apollo/issues/337
https://github.com/GMOD/Apollo/issues/283
https://github.com/GMOD/Apollo/issues/237

**Comment by nathandunn** [comment]
@cmdcolin   Do you want to review this when you have a moment? 

Its the script under docs/web_services/add_organism.groovy

**Comment by cmdcolin** [comment]
It just hangs when I try to run it. Any idea how to fix it?

I like this concept though, very useful, and to automatically create the session without having to manually call the login and save the cookie and everything is very nice.

**Comment by cmdcolin** [comment]
Nevermind i was really impatient...the usage message seems to take a second to load which is a little annoying but the script works fine!

Maybe we can move this to the bin directory?

**Comment by nathandunn** [comment]
That should be under a second .. Likely system caching / compiling should minimize it .. Would be interested if it continues to rake more than that. 

Nathan

**Comment by cmdcolin** [comment]
The script doesn't work if the organism list is empty. It basically throws an exception when there are no organisms to check permissions for. I can see if it's fixable

**Comment by nathandunn** [comment]
Oh, its probably this line in PermissionService.hasPermissions():

        Organism organism = getCurrentOrganismPreference().organism
        
Obviously you can't have an organism preference if you have no organisms, so that should be null.

**Comment by nathandunn** [comment]
Unless you are working on it as we speak, let me fix this .  . I'm running into another error right now as well.

**Comment by nathandunn** [comment]
@cmdcolin  I think it should be ready to test again.   Thanks for catching this!

**Comment by cmdcolin** [comment]
Sweet. I was attempting a fix yesterday but I'll test out what you have now

**Comment by cmdcolin** [comment]
This is pretty good. would it be ok if we merged saveOrganism and the addOrganism method?

**Comment by nathandunn** [comment]
Sure . . I added it to the notes . . I just didn't take the time to do it, as there were some minor nuances that made it a little more difficult than I'd initially thought.

**Comment by cmdcolin** [comment]
That would be nice. I wanted it to properly return errors if there was invalid information being added which the "saveOrganism" does have but the "addOrganism" does not have.

can do myself

**Comment by nathandunn** [comment]
That would be fine.  Just make sure it works in both instances.  I can review it when you are done. 

Nathan

**Comment by cmdcolin** [comment]
Tested again for both instances

**Comment by nathandunn** [comment]
Awesome . . shall we close it?

**Comment by cmdcolin** [comment]
Yep
