### ISSUE TITLE
Changes page causes system instability. (1.0.4)

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#362]
Changes page crashes the tomcat  service when filtering on username when filtering on a username. It looks like some users were going through multiple instances and checking for annotations by user. 

Is changes not releasing the open files once it is done?  We’ve had to bump the max files a few times to keep up with the open files.

**Comment by nathandunn** [comment]
@childers   I put a "patch" on staging to test.  I'll send it to you in a separate email.  I don't know if it will fix anything.     The original servlet was just a direct conversion of the original JSP file, so I'm not sure if the behavior will be any different.    I'll send you both the staging and the older Apollo locations to see if there is a difference.

**Comment by childers** [comment]
How did the patch go?  We recently had another case of tomcat running out of memory, and I think it is related to this issue, but don't see a way to safely recreate this issue.

**Comment by nathandunn** [comment]
Glad you asked.  I got a bug and I’ll have to fix it . . .  will try to get something later today:

type Exception report

message je.env.isReadOnly is set to true in the config parameter which is incompatible with the value of false in the underlying environment

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.lang.IllegalArgumentException: je.env.isReadOnly is set to true in the config parameter which is incompatible with the value of false in the underlying environment
	com.sleepycat.je.EnvironmentMutableConfig.checkImmutablePropsForEquality(EnvironmentMutableConfig.java:669)
	com.sleepycat.je.DbInternal.checkImmutablePropsForEquality(DbInternal.java:251)
	com.sleepycat.je.dbi.EnvironmentImpl.checkImmutablePropsForEquality(EnvironmentImpl.java:2270)
	com.sleepycat.je.dbi.DbEnvPool.getEnvironment(DbEnvPool.java:153)
	com.sleepycat.je.Environment.makeEnvironmentImpl(Environment.java:246)
	com.sleepycat.je.Environment.<init>(Environment.java:227)
	com.sleepycat.je.Environment.<init>(Environment.java:170)
	org.bbop.apollo.web.datastore.JEDatabase.<init>(JEDatabase.java:42)
	org.bbop.apollo.web.RecentChangeServlet.doGet(RecentChangeServlet.java:196)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.55 logs.


Nathan

**Comment by nathandunn** [comment]
@childers  This last patch seems to have fixed this problem:  

http://icebox.lbl.gov/WebApolloDemoStaging/changes

I might run it through a few trials first, though, just to be sure.

**Comment by childers** [comment]
@nathandunn Have you noticed any issues with the patched instance?

**Comment by nathandunn** [comment]
@childers  It looks good to me, but have a run-through yourself:

http://icebox.lbl.gov/WebApolloDemoStaging/changes

Nathan

**Comment by childers** [comment]
I did earlier this morning.  I'll be very happy if you have not seen any issues on the server side today.

**Comment by nathandunn** [comment]
I haven't really been using it except for periodically changing, so I may not be the best judge.  

What was the issue?

**Comment by childers** [comment]
The issue was that using the changes page, and more specifically the various filters to view subsets of the data resulted in allocating resources that were never released.  We got around that by increasing the max files repeatedly, but that is a stopgap that can't scale indefinitely.
