### ISSUE TITLE
Improve the drawings for exons, introns, UTRs*

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#365]
We have had conversations about improving how a features are visualized, and as we do not yet have an issue or trello card about this, I am starting one. 

This is a beautiful example from Mark Yandell and Daniel Ence's paper (doi:10.1038/nrg3174).

Exons and introns are clearly distinguishable from each other, and URTs are much, much easier to differentiate. The intro also 'bends' up and down as it gets longer. - think also of Apollo desktop. 

![screen shot 2015-05-09 at 1 07 07 am](https://cloud.githubusercontent.com/assets/1714621/7549422/6ed372c2-f5e8-11e4-87b3-25f92382225c.png)

*Please note later milestone.

**Comment by nathandunn** [comment]
:+1:

**Comment by selewis** [comment]
This is beautiful. Exactly what we need to be seeing.

I also like showing the start and stop codons within the model as well.

**Comment by dence** [comment]
Glad to see that you guys like the illustration! Wish I could take credit it for it. 

~Daniel

**Comment by nathandunn** [comment]
I think we've done most of this, but I want to confirm after the holidays.

**Comment by nathandunn** [comment]
Just wanted to note that this is being done as part of the NeatFeatures plugin in JBrowse (its there, but some minor bugs have prevented it from being default. and hopefully as part of the pure-svg track:

https://github.com/GMOD/jbrowse/issues/846

**Comment by nathandunn** [comment]
This has been done via Neat Features
