### ISSUE TITLE
add metadata key/values (with some set keys) to organism

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#367]
See #237 . . . also, BLAT / BLAST database information should potentially be handled as metadata (and potentially genus and species).  

Might also be useful if you could pass in the NCBI taxon ID, or the the
UniProt 4 letter code.

ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/
and
http://www.uniprot.org/docs/speclist

**Comment by erasche** [comment]
This and my super poorly worded request in https://github.com/GMOD/Apollo/issues/981 are covering similar territory. I just wanted to follow up / ping and see if there was any planned timeline for exposing an API for adding arbitrary key/value pairs to an organism for maintaining metadata. (No need for doing it in Chado if that would make it easier, I just (eventually) need some way to store this, and I'd rather do it in apollo than maintaining a separate DB)

**Comment by nathandunn** [comment]
@erasche  There is a ```metadata``` column in Organism that you can use right now.   In organismController, there is an ```updateOrganismInfo``` method.   You could easily add metadata here, or create an ```updateOrganismMetadata``` method.  

If you want first-class properties as well, let me know.  

Or do you just want to add a hasMany relationship from [Organism](https://github.com/GMOD/Apollo/blob/master/grails-app/domain/org/bbop/apollo/Organism.groovy) to [CVTerms](https://github.com/GMOD/Apollo/blob/master/grails-app/domain/org/bbop/apollo/CVTerm.groovy)?

**Comment by nathandunn** [comment]
@erasche  Or did you just wanted a simple key/value pair database object?  From your example, it looked like you wanted a cv_term.

**Comment by erasche** [comment]
@nathandunn I'm fine with KV, suggested cv* because it seemed like the obvious thing to do. I'm just looking to tag organisms in a useful way. I can use empty groups for this, but it's definitely not the right way to do it.

**Comment by erasche** [comment]
Great! @ metadata, that sounds like exactly what I want. If that was exposed, that'd be perfect.

**Comment by nathandunn** [comment]
@erasche  Try this PR out and let me know.

**Comment by nathandunn** [comment]
I mean this one: #1534.

**Comment by erasche** [comment]
Will do in ~1 hour, sorry for delay.

**Comment by nathandunn** [comment]
No rush on my part.
