### ISSUE TITLE
"key" can not be a keyword, conflicts in mysql and other databases

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#368]

**Comment by nathandunn** [comment]
Please note that you may have to drop the turn off tomcat and drop the data_adapaters table.  When tomcat is restarted it should create the proper table.  

Still need to merge.

**Comment by nathandunn** [comment]
Looking further at this, I think it is in the code already, but probably just need to drop the table.

**Comment by cmdcolin** [comment]
Ya I think this was something I fixed awhile back? I know ctc used a pretty early version

**Comment by nathandunn** [comment]
Hey, I just found it.   Liquibase (what grails wraps) is pretty awesome, but sometimes you have to drop a table now and again.  When we get into "full-releases" we'll create migration scripts for the SQL (if need be).
