### ISSUE TITLE
(1h) if a "user" has no organism level permissions, admin tabs are shown

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#372]
Basically as the title says, if you create a new user, but you don't grant the new user any organism permissions, then they will get an alert box telling them that they don't have any permissions, but they will be able to to see the admin panels for some reason. I think there is an uncaught exception that crashes the code before the code for hiding the panels is run (updatePermissionsForOrganism:around lines 250-270)

Additionally, if you grant them permissions, and then they browse around, but then you revoke their permissions, then it will try to load the organism initially (probably from the user preferences?) but then it fails to load the annotations from the organism and just has an infinite loading spinner on the annotation track due to a server side exception. This is the server side exception for this case:

    | Error 2015-05-13 16:34:05,819 [http-bio-8080-exec-10] ERROR errors.GrailsExceptionResolver  - AnnotationException occurred when processing request: [POST] /apollo/AnnotationEditorService - parameters:
    data: {"operation":"get_sequence_alterations","track":"Annotations-Group1.1"}
    { "track": "Annotations-Group1.1", "operation": "get_sequence_alterations" }:
    You have insufficent permissions [none < read] to perform this operation. Stacktrace follows:
    Message: You have insufficent permissions [none < read] to perform this operation
        Line | Method
    ->>  600 | $tt__checkPermissions  in org.bbop.apollo.PermissionService
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    |    387 | getSequenceAlterations in org.bbop.apollo.AnnotationEditorController
    |    198 | doFilter . . . . . . . in grails.plugin.cache.web.filter.PageFragmentCachingFilter
    |     63 | doFilter               in grails.plugin.cache.web.filter.AbstractFilter
    |     68 | handleOperation . . .  in org.bbop.apollo.AnnotationEditorController
    |    198 | doFilter               in grails.plugin.cache.web.filter.PageFragmentCachingFilter
    |     63 | doFilter . . . . . . . in grails.plugin.cache.web.filter.AbstractFilter
    |    449 | executeChain           in org.apache.shiro.web.servlet.AbstractShiroFilter
    |    365 | call . . . . . . . . . in org.apache.shiro.web.servlet.AbstractShiroFilter$1
    |     90 | doCall                 in org.apache.shiro.subject.support.SubjectCallable

**Comment by nathandunn** [comment]
@cmdcolin   Let me know if this works for you.  Close it if so.   Thanks!

**Comment by cmdcolin** [comment]
The second part of the issue that i raised still has some problems, e.g:

>Additionally, if you grant them permissions, and then they browse around, but then you revoke their permissions, then it will try to load the organism initially (probably from the user preferences?) but then it fails to load the annotations from the organism and just has an infinite loading spinner on the annotation track due to a server side exception.

I am not sure what exactly that would involve but it could be added as a separate issue since the tabs thing is fixed already.

**Comment by nathandunn** [comment]
So, if this only occurs when they have 1, and then you remove that one (back to 0), I think that this is fine.   Am I missing part of it?

Nathan

**Comment by cmdcolin** [comment]
Well normally when they have 0, it is now producing the popup that notifies them of that. If you do the procedure of adding them to 1, and then removing them back to 0, then i thought perhaps it should be producing the popup again

**Comment by nathandunn** [comment]
I think I have a fix for this now.

**Comment by cmdcolin** [comment]
Looks good now!

**Comment by cmdcolin** [comment]
It might be a good idea for the old annottrack.js functions to handle errors a lot better because otherwise it just gets this "infinite loading" bar that might confuse users. It's probably better to have some error message than none. In any case, I think this can be closed
