### ISSUE TITLE
(1h) on create user, should fail in interface if we fail to add a user

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#373]
Basically throws an error on the backend and that is that.  e.g., enter an email 'a@a.a'.   I don't catch it on the front, just the back.

**Comment by cmdcolin** [comment]
The createUser in UserRestService has a detection for "error" from duplicate user names. is there another condition that fails?

Note that in general, i have tried to sort of proliferate a pattern of error detection to try and catch exceptions that are being thrown before JSON is being rendered by the controllers, and render the exceptions as error messages in JSON.

**Comment by nathandunn** [comment]
Yes.  The username is an email, which is validated on the server.  I’m wondering if I should remove that constraint, though.   Mostly I hate “not” being able to use my email.

Nathan

**Comment by monicacecilia** [comment]
Yes, it fails if it fails to add a new user.
