### ISSUE TITLE
(2h) do not refresh genomic location if already at or near the same location when clicking on exon

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#378]

**Comment by monicacecilia** [comment]
What are the coordinates of "near"? 
How close is near? 
Is this a percentage? 
Does it depend on the size of the window? 
Does "near the exon" include being able to see only that exon but not the rest of the annotation? 

It still refreshes if I am zoomed-in, or if I see the model partially.

**Comment by nathandunn** [comment]
UPDATE_DIFFERENCE_BUFFER  . . . was 10%, will make 30%.  
   int oldLength = maxRegion - minRegion;
            double diff1 = (Math.abs(currentStartBp - minRegion)) / (float) oldLength;
            double diff2 = (Math.abs(currentEndBp - maxRegion)) / (float) oldLength;
            if (diff1 < UPDATE_DIFFERENCE_BUFFER && diff2 < UPDATE_DIFFERENCE_BUFFER) {
//                GWT.log("Not updating sequence position");
                return;
            }
