### ISSUE TITLE
(2h) update "coding" / detail panel when changing transcript details

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#379]
When you make a change to an exon, it should be reflected in the details panel.

**Comment by monicacecilia** [comment]
This one needs to be fixed by 2.0.5. No more punting. :bowtie:

**Comment by monicacecilia** [comment]
The edit is sending the notification, but the client isn't refreshing after the change. So the result is a blank panel for 'Coding', and deselection of the mRNA.  User has to either click on mRNA again to display the change, or must refresh page. 

We can do better!

### See before the edit to the boundaries of exon 2: 
![screen shot 2016-12-01 at 5 23 58 pm](https://cloud.githubusercontent.com/assets/1714621/20819726/319396a0-b7eb-11e6-8440-2bf617d5e20c.png)


### Immediately after editing exon 2:
![screen shot 2016-12-01 at 5 24 08 pm](https://cloud.githubusercontent.com/assets/1714621/20819735/3855fd7a-b7eb-11e6-9792-967e4c2c18e7.png)

**Comment by monicacecilia** [comment]
The 'Coding' tab in the Annotator Panel is now refreshing and updating immediately after the edit. Great!
