### ISSUE TITLE
(1d) when setting exon / other boundaries, should merge / split gene if in-sequence

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#383]

**Comment by nathandunn** [comment]
@selewis  @monicacecilia   So I was looking at this . .. I am not sure this is working any differently the before.  On the 1.0 demo box we have:

http://icebox.lbl.gov/WebApolloDemo/jbrowse/?loc=Group1.10%3A135761..154440&tracks=DNA%2CAnnotations%2COfficial%20Gene%20Set%20v3.2&highlight=

2 genes, 2 transcripts:

![screen shot 2015-05-14 at 4 32 41 pm](https://cloud.githubusercontent.com/assets/751274/7644234/dcf28fb4-fa56-11e4-8d93-771076a8adf6.png)

If I drag one of the exons such that the overlapping regions . .  overlap:

![screen shot 2015-05-14 at 4 34 21 pm](https://cloud.githubusercontent.com/assets/751274/7644245/19072762-fa57-11e4-98f8-d12a0b8cc41b.png)

Each gene is still on its own transcript:

![screen shot 2015-05-14 at 4 34 39 pm](https://cloud.githubusercontent.com/assets/751274/7644249/276487e6-fa57-11e4-8051-886363f17fd8.png)

I brought up an exon and split it and it failed to create a new gene when they were no longer over-lapping (sorry skipped a step).

![screen shot 2015-05-14 at 4 36 49 pm](https://cloud.githubusercontent.com/assets/751274/7644279/91eb0752-fa57-11e4-91d0-df0668a86fa0.png)

*THAT BEING SAID*

I think what might be more would be a mechanism for a transcript to switch the gene its on . . .but I have no idea if that is a good idea or not.

**Comment by selewis** [comment]
It absolutely HAS TO.

Let me say this one more time. Then get it FIXED.

If 2 transcripts share coding sequence in the same frame (i.e. some portion
of the 2 proteins from these transcripts is shared) then they are isoforms
of the SAME gene.

If they do not share any coding sequence in the same frame (i.e. no protein
in common) then they belong to DIFFERENT genes.

This is not optional. This is the definition of isoforms (aka alternate
transcripts).

So whenever a user makes any edit that effects its overlap with other
transcripts then the above needs to checked to see whether genes are merged
or split.

Can I possibly make this any clearer?

**Comment by nathandunn** [comment]
No.  I thought it was pretty clear when you explained it to me.   

I had just assumed it was working in the older system and I wanted to make sure I was not misunderstanding.  

Would it be possible for someone (other than myself) to confirm that this was not working properly on the older Web Apollo? 

http://icebox.lbl.gov/WebApolloDemo/sequences <http://icebox.lbl.gov/WebApolloDemo/sequences>


Nathan

**Comment by cmdcolin** [comment]
It has been a long standing problem that when you forcefully drag an exon so that it overlaps another transcript, that they will not be "merged" right (and similarly, they will not be "unmerged" when they are dragged such that they don't overlap anymore). This was originally brought up here https://github.com/GMOD/Apollo/issues/73

In most other cases, the "OrfOverlapper" strategy that @selewis describes works fine in the 1.x versions

It's just that dragging the transcripts such that it introduces new overlaps that can cause problems...

**Comment by nathandunn** [comment]
Thanks for the clarification.  I agree that it is the exact same Issue as in #73 . . so I'm going to close this as a duplicate.   I tried this on pre-1.X and dragging exons simply doesn't re-calculate the gene.   There is overlap calculation code in there for calculating overlaps for transcription addition using the OrfOverlapper, some most likely, we should just re-use that.
