### ISSUE TITLE
(1d) UI improvements

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#385]
Sequence Panel:
~~- [ ] add # of annotations (bonus if sortable)~~
- [x] default sort descending length (for some reason opposite now)
- [x] searching for group 1.33 (quickly) gives redundant results? 
- [x] GFF3 / FASTA should go above Select / All
- [x] on search in box pagination should go to one
- [x] count seems to be wrong for pagination (always +over 20)

Organism Panel:
- [x] sync header alignment

~~- [] remove annotations count or update dynamically~~

**Comment by nathandunn** [comment]
Annotation Panel:
- add sequence name to table (and sort this by default)

Sequence panel:
- add # of annotations  (bonsu if sortable)
- default sort descending length (for some reason opposite now)

**Comment by nathandunn** [comment]
FYI @monicacecilia

**Comment by monicacecilia** [comment]
@nathandunn brilliant!

**Comment by cmdcolin** [comment]
This is a weird gripe, but currently, our "Ref Sequences" panel contains all functionality for GFF3/FASTA exports. Should it be called "Export data"? I think the emphasis on the refseqs downplays it's importance for exports

**Comment by nathandunn** [comment]
Exporting is one function of it.  Also searching and navigating.  

Worth discussing on Thursday. 

Nathan

**Comment by selewis** [comment]
Perhaps "Sequence Utilities" ?

**Comment by nathandunn** [comment]
That panel has 3 functions, browsing sequences, exporting sequences, and navigating to sequences (though this is a minor one).  

Export functionality is important, but so is listing and sorting (I think).  We could definitely re-arrange it pretty easily.

Nathan

**Comment by nathandunn** [comment]
Still working. 

To test:  validate criteria above on the sequence and organism panel.

**Comment by nathandunn** [comment]
works .  . chose not to implement dynamic organism count stuff
