### ISSUE TITLE
(2h) changing to an organism (or changing ref seq) from side-panel fails to change JBrowse organism if lots of annotations

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#387]

**Comment by nathandunn** [comment]
change is made in database (is correct on reload)

**Comment by nathandunn** [comment]
Does not happen on startup, only after some activity (e.g., adding some transcripts).

**Comment by nathandunn** [comment]
Inadvertently caused by #378

**Comment by monicacecilia** [comment]
How many annotations is "lots"? 
I have 66. Is that "lots"?

**Comment by monicacecilia** [comment]
-- it looks fine -- just want to know how many is "too many" for testing.

**Comment by nathandunn** [comment]
@monicacecilia  It took about 30 to see the effect pretty noticeabley.

**Comment by monicacecilia** [comment]
Cheers. I was working with >100 at a time and it worked well.
