### ISSUE TITLE
Annotation Information Popup does not go away after keyboard command if not on focus

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#390]
In the U-cA area, the right-click menu can be displayed using either mouse or keyboard commands. In Mac OS X v 10.8.5 after pulling the menu with keyboard commands (press down control while clicking on annotation) the menu will not go away despite clicking outside the menu or using the 'escape' key. 

After pulling right-click menu with the mouse commands, it is possible to dismiss it by either clicking outside the menu or pressing the 'escape' key.

**Comment by nathandunn** [comment]
@monicacecilia   It does work.   You have to make sure you are clicked somewhere on the frame.   It is the same as in 1.0.4, but now we have somewhere else to click.  Either way, the "X" is still available.  I agree, though, that so long as its popped up, it should work.   My hope is that the entire thing goes away anyway.

**Comment by nathandunn** [comment]
So, the fix for this would either be to have JBrowse running in a div - OR - the popup panel info in the annotator panel.
