### ISSUE TITLE
(1d) websocket callback goes out to EVERY sequence and organism

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#391]

**Comment by nathandunn** [comment]
The older code had track queues (and of course only one organism).    

Requirements: client has to know the organism. . . it already has to know the sequence.

**Comment by nathandunn** [comment]
Dependent on #319 . . . . can probably solve all but the view-level stuff here, though.

**Comment by nathandunn** [comment]
should be able to do things on one group / organism without it affecting the other

**Comment by monicacecilia** [comment]
... alas. . . 
modifications on Group1.37 are still visible on Group1.33. Even better, they are visible in 1.33 and NOT in 1.37.

**Comment by nathandunn** [comment]
NEed to grab "refseq" from the operation and NOT the preference, as there may be multiple preferences.

**Comment by monicacecilia** [comment]
@nathandunn "preference" --> "reference".

**Comment by monicacecilia** [comment]
@nathandunn "preference" --> "reference"? ... 
the reference sequence?

**Comment by nathandunn** [comment]
Nope preferences .. Set for each organism .. If you reload it will come back to the same place.

**Comment by nathandunn** [comment]
Every function calls:

    PermissionService::checkPermssions()

We use the track to get the sequenceName. . . however, if we already have a organism preference, we use that sequence.  

Clearly we need to explicitly check and/or set that:
    
         Sequence sequence = Sequence.findByNameAndOrganism(trackName,organism)
        if(userOrganismPreference.sequence.name!=trackName){
            userOrganismPreference.sequence = sequence
            userOrganismPreference.save()
        }

**Comment by monicacecilia** [comment]
Hallelujah! After repeated testing I can confirm this is no longer happening. :dancer: !!
