### ISSUE TITLE
(1h) "undo" isoform is generating a new isoform name when adding back the transcript

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#392]
It should use its previous transcript name, not create a new one.

**Comment by monicacecilia** [comment]
@nathandunn I think "when adding back the transcript" is misleading --> "when reverting to previous state, e.g: adding back an exon".

**Comment by nathandunn** [comment]
featureEvent SET_EXON_BOUNDARIES -> 2015-05-20 08:45:22.455
    final feature event: org.bbop.apollo.FeatureEvent : 515020 ->SET_EXON_BOUNDARIES
    current feature events for unique name 1
    | Error 2015-05-20 08:47:11,036 [clientInboundChannel-1] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
    Message: Cannot get property 'name' on null object
        Line | Method
    ->>  595 | $tt__checkPermissions in org.bbop.apollo.PermissionService
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
    |    653 | $tt__addTranscript    in org.bbop.apollo.RequestHandlingService
    |    293 | $tt__setHistoryState  in org.bbop.apollo.FeatureEventService
    |    365 | $tt__undo             in     ''
    |   2101 | $tt__undo . . . . . . in org.bbop.apollo.RequestHandlingService
    |    821 | doCall                in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure3_closure4_closure5
    |    820 | doCall . . . . . . .  in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure3_closure4
    |    816 | doCall                in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure3

**Comment by nathandunn** [comment]
Same issue when creating features as well.  Steps to recreate:
1 - create a "repeat_region" 
2 - set boundaries
3 - undo

Note rename.

**Comment by nathandunn** [comment]
Can fix this with having 2 transactions (which works).  However if "add" fails for any reason you end up losing it entirely (see #397). 

The other possibility is to suppress "unique naming" if the "suppressHistory" flag is set.

**Comment by monicacecilia** [comment]
I can confirm that this is not happening any more. :dancer: !!
