### ISSUE TITLE
(2h) if you add a second isoform, the "owner" shows up in the attributes column

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#393]

**Comment by nathandunn** [comment]
Unable to reproduce.  My method:
1 - create a single isoform
2 - create another identical isoform

Right-click and confirm that attributes are empty for both.
Hover over and confirm that owner is listed correctly.

Note that there was a prior bug (now fixed) where this did happen.   I am hopeful that that was what we were looking at.  Its also possible that I am missing a step reproducing it.

**Comment by monicacecilia** [comment]
Yeah, it used to look like this:
![screen shot 2015-05-19 at 4 56 49 pm](https://cloud.githubusercontent.com/assets/1714621/7761407/5437c9d0-ffda-11e4-881d-f8b095d5f801.png)

And now it's gone!! I tested quite a bit and I cannot reproduce it any more! :) :dancer: !!
