### ISSUE TITLE
(4h) any undo operations on an isoforms "appear" to be lost after another isoform is added

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#394]
Add an isoform.  
Do an operation.  
Verify that there is history there.   

Add another isoform.  
Verify that you can't do an undo on the second isoform.

However . . . if you do a prior undo operation on the most recent one, magically you can do one again. 

My theory (I hope) is that the callback mechanism is somehow screwy.

**Comment by nathandunn** [comment]
I think that this is magically working again with the other fixes from #392, #397, and #398.

**Comment by monicacecilia** [comment]
The case is actually "after another isoform has been added and edited". 
Problems persist. 

1. Also, something is not right with "undo" when setting a readhthrough stop. 
After "unsetting" readthrough you can "undo" the "unset" so the readthrough is back on, but Apollo does not highlight the stop any more. Notice the upper most transcript in this figure: TAA should be highlighted in purple as "stop".
![screen shot 2015-05-21 at 4 01 17 pm](https://cloud.githubusercontent.com/assets/1714621/7761326/5b1d3a10-ffd9-11e4-9b3b-8dff50971890.png)
2. When "Seth readthrough" is done without first "setting start of translation" Apollo loops to the beginning to find the longest ORF after skipping a stop (which is ok and expected when translation start has not been set), but Apollo does not highlight the stop that is being skipped, so the resulting CDS contains a stop in the middle without visual warning of the skip. Note that the transcript in the figure has a stop in frame and although Apollo is reading through it, it is not highlighted in purple.
![screen shot 2015-05-21 at 4 05 30 pm](https://cloud.githubusercontent.com/assets/1714621/7761333/72c36716-ffd9-11e4-985c-4c83fd43223c.png)
3. When you get to a gene model with a readthrough stop after using the "redo" command, it is no longer possible to "unset" the readthrough from the right click menu, and the stop is not highlighted as in the cases above. 
4. Redo is lost after an edit has occurred in a different gene model. It is also not possible to "redo" using the History Tab.

**Comment by nathandunn** [comment]
"Seth readhthrough"

**Comment by nathandunn** [comment]
From #398:

I am not seeing history disappear. What I am seeing is undo being taken away seemingly randomly:
1 - add a transcript, go crazy with history, undo/redo . . it works
2 - add an isoform, go crazy with history, undo/redo . .. it works, but the first transcript undo operations do not work (though history does)
3 - do an operation on the first transcript. Now it works (including its older history) and the second one does not.

Hoping its a silly UI-thing.

**Comment by nathandunn** [comment]
A quick caveat . . . breaking the "undo" operations doesn't happen *UNTIL* you do at least one other operation on the second isoform.

**Comment by nathandunn** [comment]
Its because its setting 1 current isoform as current. . . . should be an easy fix.

**Comment by nathandunn** [comment]
Actually, the problem is that every time it records a new feature operation it is clearing them all out.

**Comment by nathandunn** [comment]
Should work now.

**Comment by monicacecilia** [comment]
This part, "any undo operations on an isoforms "appear" to be lost after another isoform is added" now works. ... but it uncovered another problem. I created a new issue for that. #401
