### ISSUE TITLE
(2h) undo: unknown sequence name during undo option causes permission exception

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#397]
Found testing #392. 

    featureEvent SET_EXON_BOUNDARIES -> 2015-05-20 08:45:22.455
    final feature event: org.bbop.apollo.FeatureEvent : 515020 ->SET_EXON_BOUNDARIES
    current feature events for unique name 1
    | Error 2015-05-20 08:47:11,036 [clientInboundChannel-1] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
    Message: Cannot get property 'name' on null object
        Line | Method
    ->>  595 | $tt__checkPermissions in org.bbop.apollo.PermissionService
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
    |    653 | $tt__addTranscript    in org.bbop.apollo.RequestHandlingService
    |    293 | $tt__setHistoryState  in org.bbop.apollo.FeatureEventService
    |    365 | $tt__undo             in     ''
    |   2101 | $tt__undo . . . . . . in org.bbop.apollo.RequestHandlingService
    |    821 | doCall                in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure3_closure4_closure5
    |    820 | doCall . . . . . . .  in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure3_closure4
    |    816 | doCall                in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure3

**Comment by nathandunn** [comment]
To reproduce reliably:
1 - Create a transcript
2 - Move an exon
3 - Undo that move

**Comment by nathandunn** [comment]
Occurs if sequence preference is not set for the user . . .

**Comment by nathandunn** [comment]
Nothing to test .

**Comment by monicacecilia** [comment]
yay . . . this crazy renaming business is solved.
