### ISSUE TITLE
(1h) undo features is not suppressing history properly

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#398]
Every time I added / remove a feature it adds another feature to the history.  Leads to the cool effect that it just pops back and forth.

**Comment by nathandunn** [comment]
To Test: 
- create a non-transcript feature (A)
- move the boundary (B)
- move the boundary again (C)
- undo (should go to (B) )
- undo (should got (A), was going back to (C) and writing more history).

**Comment by monicacecilia** [comment]
If you only have one feature, the History is kept. The moment I add a second feature and conduct an edit there, the first one (or some times the second one!) loses its History and you cannot "undo". 
The inconsistency between which feature loses its History is a little disconcerting. I'll keep testing just in case, but that part (described in #394) is not working.

**Comment by nathandunn** [comment]
I am not seeing history disappear.  What I am seeing is undo being taken away seemingly randomly:
1 - add a transcript, go crazy with history, undo/redo . . it works
2 - add an isoform, go crazy with history, undo/redo .  .. it works, but the first transcript undo operations do not work (though history does)
3 - do an operation on the first transcript.  Now it works (including its older history) and the second one does not.  

Hoping its a silly UI-thing.

**Comment by nathandunn** [comment]
Closing in favor of #394.
