### ISSUE TITLE
(1d) Readthrough stop codons are not being highlighted after undo/redo

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#400]
This part was additional on #394 so it was overlooked. I am opening a new issue for it because it is not yet resolved. It concerns the problem with readthrough stop codons not being highlighted. 

1.Something is not right with "undo" when setting a readhthrough stop. 
After "unsetting" readthrough you can "undo" the "unset" so the readthrough is back on, but Apollo does not highlight the stop any more. Notice the upper most transcript in this figure: TAA should be highlighted in purple as "stop".
![screen shot 2015-05-21 at 4 01 17 pm](https://cloud.githubusercontent.com/assets/1714621/7761326/5b1d3a10-ffd9-11e4-9b3b-8dff50971890.png)
2. When "Set readthrough" is done without first "setting start of translation" Apollo loops to the beginning to find the longest ORF after skipping a stop (which is ok and expected when translation start has not been set), but Apollo does not highlight the stop that is being skipped, so the resulting CDS contains a stop in the middle without visual warning of the skip. Note that the transcript in the figure has a stop in frame and although Apollo is reading through it, it is not highlighted in purple.
![screen shot 2015-05-21 at 4 05 30 pm](https://cloud.githubusercontent.com/assets/1714621/7761333/72c36716-ffd9-11e4-985c-4c83fd43223c.png)
3. When you get to a gene model with a readthrough stop after using the "redo" command, it is no longer possible to "unset" the readthrough from the right click menu, and the stop is not highlighted as in the cases above.

**Comment by nathandunn** [comment]
should see a "purple" where set readthrough is set . . 

![screen shot 2015-05-26 at 7 57 41 pm](https://cloud.githubusercontent.com/assets/751274/7827904/83e4756a-03e1-11e5-80e4-0512d431df06.png)

**Comment by cmdcolin** [comment]
At least one thing I noticed with this is that when you undo and then redo, the stop_codon_read_through does not show up in the gff3 either.

I was trying to browse FeatureEvent to see if anything might help but I haven't figured it out yet.

**Comment by nathandunn** [comment]
@deepakunni3  This one might be good for you to look at if you have time.

**Comment by deepakunni3** [comment]
@nathandunn Will get started on this soon.

**Comment by deepakunni3** [comment]
This bug is a result of StopCodonReadThrough not being accounted for, in convertJSONToOntologyId().

Commit b2694ba5 fixes this issue.

**Comment by nathandunn** [comment]
Good catch @deepakunni3  . .

**Comment by nathandunn** [comment]
Seems to work.

**Comment by monicacecilia** [comment]
Brilliant - and good eye @deepakunni3. Indeed it works. :dancer:
