### ISSUE TITLE
(2h) gene name is being set to the transcript name on "REDO" causing additional isoform naming errors.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#401]
Steps to reproduce:
1. Drag a gene model into U-cA area
2. Edit the model (e.g: add an exon from a different model, delete an exon, modify coordinates)
3. "Undo" the operation you just conducted
4. Drag a second isoform for that same gene model

In our testing instance for Apollo2
The name of the evidence is: AA1234-RA
The name of the first isoform is AA1234-RA-00001
The name of the second isoform is AA1234-RA-00001-00001 (see left part of figure), instead of the expected AA1234-RA-00002 (as in the model on the right).

![screen shot 2015-05-22 at 1 56 42 pm](https://cloud.githubusercontent.com/assets/1714621/7779560/66f86f9c-008a-11e5-932c-1622a476f444.png)

**Comment by nathandunn** [comment]
Dargh . . the core of this bug is that the gene name is being set to the transcript name on "undo".   The isoform is then creating the new name correctly based on the updated gene name.

**Comment by monicacecilia** [comment]
oh, oh, and maybe this is related. 

When creating a pseudogene, an extra letter is added to the name. 
For example, the name of the evidence where I get the pseudogene is AA12345-RA
When "create new annotation --> pseudogene" the name is AA12345-RAa-00001
If I were creating a gene model, it would be AA12345-RA-00001

Why the difference? Is this deliberate or a glitch? 

![screen shot 2015-05-22 at 3 01 24 pm](https://cloud.githubusercontent.com/assets/1714621/7780409/71690848-0093-11e5-804d-6444f9c71326.png)

**Comment by monicacecilia** [comment]
@nathandunn FYI, while testing this: 
in front of my eyes a pseudogene disappeared while I was editing its "information" box. Apollo seemed to be having issues connecting to the GO database. When I closed the box - the gene was gone, and I started another pseudogene. Apollo "remembered" that another pseudogene had been dragged up (the name sequence showed that. -- and then I realized the naming issue I just reported.

**Comment by nathandunn** [comment]
Redo renames the gene

**Comment by nathandunn** [comment]
TODO: set feature name for EACH event . . .

**Comment by monicacecilia** [comment]
I can confirm that this is now fixed. 
hooray! :dancer:
