### ISSUE TITLE
(4h)  Option to "Save track data as GFF3" in U-cA area should include all annotations

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#403]
### First, "Save track data as GFF3" only includes gene annotations in the GFF3. 
No other user-created annotations are included. However, retrieving individual files for each annotated feature, shows populated GFF3 files for each of the other annotations. 

In the example below, there are one gene, one repeat region, one transposable element and one pseudogene. Individually, the GFF3 file produced using "Get GFF3" over the pseudogene looks like this:
![screen shot 2015-05-22 at 4 02 35 pm](https://cloud.githubusercontent.com/assets/1714621/7781095/15a336f0-009d-11e5-81d7-0f9d8ad99897.png)

However, when exporting the GFF3 for the entire track using the "Save track data as GFF3 option", only the gene model visible in the track is exported.
![screen shot 2015-05-22 at 4 08 06 pm](https://cloud.githubusercontent.com/assets/1714621/7781103/38b5d3e6-009d-11e5-9f39-c8e2a252e2cb.png)

**Solution: all annotations created by users should be included in the GFF3.** Apollo 1.0.4 issues the data from the U-cA area as shown here: 

![screen shot 2015-05-22 at 4 17 56 pm](https://cloud.githubusercontent.com/assets/1714621/7781186/b7eff7b2-009e-11e5-8da9-dddd28bdf2ba.png)

### Second, GFF3 export no longer includes the FASTA sequence, nor do we offer an alternative option to export a GFF3 file that contains it. 
This was a feature before and I would like for us to at least offer the option to include FASTA sequence in the GFF3 file. See figure above.

**Comment by nathandunn** [comment]
@monicacecilia   I added #404 so we can track the issues separately.

**Comment by nathandunn** [comment]
@deepakunni3   Was just going to look at it, but you made it so easy to fix I just fixed it.  

Thanks.

**Comment by monicacecilia** [comment]
Brilliant.  - All features are included in the GFF3 exported from U-cA area, as seen in this [ridiculous] example. 

![screen shot 2015-05-27 at 4 51 30 pm](https://cloud.githubusercontent.com/assets/1714621/7849988/b049a602-0490-11e5-95cd-cee36be9a9e9.png)
