### ISSUE TITLE
(1d) GFF3 export should allow the export of FASTA sequence

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#404]
From #403

**Comment by deepakunni3** [comment]
Commit 1eee4dc enables the export of reference sequence FASTA as part of the GFF3 export.

**Comment by nathandunn** [comment]
@deepakunni3   I tested it with insertions and it looked correct to me.

**Comment by nathandunn** [comment]
This is from the reference sequence tab that it includes the sequence.

**Comment by monicacecilia** [comment]
FASTA is now being exported as an option. 

Unfortunately, we seem to have lost the ability to report sequence alterations. Does anyone know where those are currently reported?

**Comment by nathandunn** [comment]
Specifically: get_gff3 function is not getting insertions .. .

**Comment by monicacecilia** [comment]
The option to export FASTA sequences along with GFF3 is now available. :dancer:
