### ISSUE TITLE
(1d) "Tracks" tab does not reflect changes when switching organisms

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#405]
While on the "Tracks" tab, I switched organism and the Apollo window updated, but the list of tracks remained the same as the last organism I was looking at. I had to go to a different tab and come back to the "Tracks" tab, then the list had changed. Notice the "Human" label on the drop down menu with the honey bee tracks. 

![screen shot 2015-05-22 at 4 58 15 pm](https://cloud.githubusercontent.com/assets/1714621/7781527/45caf10e-00a4-11e5-9f19-2906baba4c85.png)

**Comment by nathandunn** [comment]
So this isn't a problem if you are on another tab, just if you're on the track tab / panel.   There is no published event (AFAIK) when tracks are fully loaded, unless maybe a nav event.  Probably the best solution would be to: 

1 - clear the tracks panel while loading if the sequence has changed
2 - the "handleTrackVisibility" command is issued with the list command, but probably need to provide another argument (i.e., the organism) compare against and then re-issue the command after a short delay if not yet there. 
!!3 - we can just re-issue command (TrackPanel.reload() . . ) and setting the frame . . . if the sequence has changed (probably the easiest fix)

**Comment by monicacecilia** [comment]
That did the trick. Thanks.
