### ISSUE TITLE
Problem saving organism (while adding a new organism)

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#408]
While adding a new organism to a fresh instance of Apollo 2.0, after some load time the UI gives the following error:

```problem saving organism: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '[org.bbop.apollo.Organism : 22604]' with class 'java.util.LinkedHashSet' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List(org.bbop.apollo.Organism```

**Comment by nathandunn** [comment]
Should be working now.  Please close if working.

**Comment by nathandunn** [comment]
@deepakunni3   Can I close this?

**Comment by deepakunni3** [comment]
@nathandunn It works.
