### ISSUE TITLE
(1h) Drop-down menu and search box atop "Annotator" panel on the right gets cut-off in Firefox

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#409]

**Comment by nathandunn** [comment]
Should convert to Bootstrap events (small or xsmall)

**Comment by monicacecilia** [comment]
### Firefox:

![screen shot 2015-05-26 at 2 20 52 pm](https://cloud.githubusercontent.com/assets/1714621/7823722/6f0c7220-03b2-11e5-8e65-9dace1b41cdf.png)

### Chrome:

![screen shot 2015-05-26 at 2 21 39 pm](https://cloud.githubusercontent.com/assets/1714621/7823736/826b1dbc-03b2-11e5-902e-1f029fa4f4d5.png)

**Comment by monicacecilia** [comment]
Brilliant. Thanks!

### Firefox:
![screen shot 2015-05-27 at 9 19 34 am](https://cloud.githubusercontent.com/assets/1714621/7841444/81e5bed4-0451-11e5-9050-488f410e5365.png)
