### ISSUE TITLE
Cannot open Apollo 2 on Firefox

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#410]
Persistent error on console: 
<code>GET 
http://icebox.lbl.gov/Apollo2/annotator/F76CD4939769164EBACE1E30F8A01D97.cache.js
</code>

**Comment by monicacecilia** [comment]
--- and it did not show an error to the user - only on the console.

**Comment by monicacecilia** [comment]
I think this is the same issue Ke Jiang was experiencing (reported on Apollo list) - cache trouble in Firefox.  -- after cleaning "Everything" (Time to clear in history), I am able to work on Firefox without trouble.

**Comment by nathandunn** [comment]
Kind of . . . looking at it GWT is supposed to include "nocache.js"
