### ISSUE TITLE
chunkSizeLimit error when displaying BAM features

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#411]
Both RNAseq reads tracks display errors with chunkSizeLimit (in both instances, Honey1 and Honey2): 
<code>http://icebox.lbl.gov/Apollo2/annotator/loadLink?loc=Group1.10:964661..965094&organism=5649&highlight=0&tracklist=0&tracks=Reference sequence,Official Gene Set v3.2,User-created Annotations,Nurse RNA-Seq reads
</code>
*note spaces on URL

![screen shot 2015-05-26 at 3 23 30 pm](https://cloud.githubusercontent.com/assets/1714621/7824827/2a22d3b2-03bb-11e5-8602-9bbac42c6000.png)

**Comment by nathandunn** [comment]
Config error . . should be working.

**Comment by monicacecilia** [comment]
It is!
