### ISSUE TITLE
BAM (draggableAlignments) don't support color by strand or some other configuration

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#412]
From this conversation with @mpoelchau (and a few others) :

http://gmod.827538.n3.nabble.com/bam-track-display-configuration-td4040828.html

We should have a way to display the strand in the BAM track.  Making Canvas tracks draggable would be one way.  Conversely, just coloring the BAM tracks appropriately as a default would probably also work.

**Comment by cmdcolin** [comment]
We added ability to create annotations from  canvas features in #576 and i think we should keep moving in that direction. I'd suggest closing

**Comment by nathandunn** [comment]
Also working on this in 2.1 (via REST) .. so I would agree.

**Comment by childers** [comment]
@nathandunn this was closed without  addressing the fact that draggableAlignments don't support color by strand.  We get requests for this every so often, and we wanted to verify with you before responding. Is the idea to move towards rendering BAM data as canvas features?

**Comment by childers** [comment]
The other request we get is support for showing cognate pairs in the case of paired end BAM files.  From what I've read and seen, there is no way to support showing mate reads as a connected unit in any feature type. Can this be reopened, or moved to a (or two) new feature request?

**Comment by nathandunn** [comment]
@childers   Thanks for catching.  Yeah, it is a pet peeve of our team as well.   I'm not sure how hard it would be to pull the JBrowse code through to fix this.     

I created a separate issue for the other one.
