### ISSUE TITLE
(4h) when merging transcripts and one transcript has an isoform there is a "fragment" left over

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#413]
When you start with two genes, one of which has an isoform:

![screen shot 2015-05-26 at 6 31 19 pm](https://cloud.githubusercontent.com/assets/751274/7826916/74bb52ae-03d5-11e5-9f70-8d7f108e0283.png)

and you merge them . . . it ends up deleting most of one of the isoforms:

![screen shot 2015-05-26 at 6 32 20 pm](https://cloud.githubusercontent.com/assets/751274/7826931/9d0dfc2a-03d5-11e5-97b1-decbe7e4a2eb.png)

expected behavior:

The other isoform should not be touched (other than changing the gene model).

**Comment by nathandunn** [comment]
On branch: lagging-features-when-merge

**Comment by nathandunn** [comment]
Everything "works" as expected, but for some reason the length of the remaining transcript is reset, even though the exons are appropriately positioned.

**Comment by nathandunn** [comment]
[ ] - figure out length on transcript 
[ ] - make sure that tests pass

**Comment by monicacecilia** [comment]
It works as expected now!
