### ISSUE TITLE
(2h) exporting annotations ignores organism

### ISSUE THREAD

**Issue by lfaino** [GMOD/Apollo#415]
Dear,
after building the WebApollo, we start to add two organisms. we annotated one gene for each organism and tried to export the gff from only one organism. however, we had a gff file in which coordinates for both organisms were present. what to do? 

we thought that this is one of the power of this new release. one database and multiple organisms. is it correct?
thanks 
Luigi

**Comment by nathandunn** [comment]
Thanks for reporting this.  No, it is not correct.  Should just export for the current organisms.

**Comment by lfaino** [comment]
Hi Nathan,
I think that the two organisms need to be separate in the database or at least the annotation for one are identified in a different way than the other. how can i check this?

**Comment by nathandunn** [comment]
It is a bug in our code that we'll have fixed soon (today or tomorrow).  It is ignoring the current organism when grabbing features to export.    

            def listOfFeatures = FeatureLocation.executeQuery("select distinct f from FeatureLocation fl join fl.sequence s join fl.feature f where s.name in (:sequenceName) and fl.feature.class in (:ontologyIdList) order by f.name asc", [sequenceName: sequenceName, ontologyIdList: ontologyIdList])

A separate database *would* fix it, but it is the wrong solution.  Fixing our code is the right solution.  Most likely you have two scaffold / groups, etc. named the same thing in separate organisms (or something like that) and it is grabbing them both.

**Comment by lfaino** [comment]
where can i add/change this line?

**Comment by nathandunn** [comment]
I haven’t had my coffee yet.   I’ll fix it first thing and have you do a pull later today (US West Coast here).  

You are welcome to fix it yourself as well and then issue a pull-request.    

It has to be fixed in two places I think.  SequenceController::exportSequences  and IOServices::write

Nathan

**Comment by lfaino** [comment]
Have your coffee and please let me know when you are done. I would be not able to fix it.



Dr. Luigi Faino
Laboratory of Phytopathology
Plant Sciences Group
Wageningen University and Research Centre
-----------------------------------------------------
Email: luigi.faino@wur.nl<blocked::mailto:luigi.faino@wur.nl>
-----------------------------------------------------------------------
Visiting address: Droevendaalsesteeg 1, 6708PB, Wageningen, The Netherlands

**Comment by nathandunn** [comment]
This should be working now.

**Comment by nathandunn** [comment]
FYI @lfaino

**Comment by nathandunn** [comment]
Should be working now.  Just do a git pull and you should pick up the fix (though you will need to redeploy). 

Nathan

**Comment by lfaino** [comment]
Hi Nathan,
just to be clear. I pool and I rebuild the war file.
Is it correct?

Luigi

Dr. Luigi Faino
Laboratory of Phytopathology
Plant Sciences Group
Wageningen University and Research Centre
-----------------------------------------------------
Email: luigi.faino@wur.nl<blocked::mailto:luigi.faino@wur.nl>
-----------------------------------------------------------------------
Visiting address: Droevendaalsesteeg 1, 6708PB, Wageningen, The Netherlands

**Comment by nathandunn** [comment]
If you are using tomcat or jetty, yes.   This is roughly what I do:

./apollo deploy 
rm -rf $WEBAPPS_DIR/apollo*
cp target/apollo*war  $WEBAPPS_DIR/

Roughly based on this:

http://webapollo.readthedocs.org/en/latest/Apollo2Build/ <http://webapollo.readthedocs.org/en/latest/Apollo2Build/>

Nathan

**Comment by monicacecilia** [comment]
Dear Luigi, 

**As always, I offer a kind reminder that Apollo2 is still a project under development, it has not been formally released, and will lack some of the features and stability necessary for annotation.**

You will want to checkout 1.0 if you want the 1.0 version of the code (older, but stable and full-feature). Version 1.0.4 is the latest, fully-functional version of Apollo and is available at https://github.com/GMOD/Apollo/releases/latest

**Comment by lfaino** [comment]
Thanks Nathan. It works

**Comment by monicacecilia** [comment]
Works now.
@nathandunn will add to issues we discussed for enhancements.
