### ISSUE TITLE
(4h) undo should "delete" when far back enough, redo should give indication that all the way forward?

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#419]

**Comment by monicacecilia** [comment]
@nathandunn "undo" already asks whether you want to delete if you are back at the top of the history stack

**Comment by monicacecilia** [comment]
if it doesn't, then you broke it. :)

**Comment by monicacecilia** [comment]
ToDo: 
- [ ] When reaching the top of the history stack, 'undo' should warn about deleting the feature
- [ ] When reaching the bottom (most recent) part of the history stack, then 'redo' should warn curator.

**Comment by nathandunn** [comment]
Make sure we should search to see if this is duplicated anywhere.
