### ISSUE TITLE
Can't Import data into Organism page <error msg>

### ISSUE THREAD

**Issue by ifishlin** [GMOD/Apollo#421]
Hi, I download Apollo two days ago.
But in this version, I can't import data into organism page.
Here is error msg.
![error2](https://cloud.githubusercontent.com/assets/9721827/7866910/88514208-0540-11e5-9a49-0bb88eecbe92.png)

I pretty sure this data set is good. I tested it in previous version.

**Comment by nathandunn** [comment]
@ifishlin . . . The mainline (Apollo2) under active development so things may not work out of the box for awhile.   Our previous version release (for a single organism) is here:  https://github.com/GMOD/Apollo/releases/latest  (we call this the Apollo 1 release)

However, if you want to continue using Apollo2, I would do another pull and this should be working.

**Comment by nathandunn** [comment]
Was this working?

**Comment by nathandunn** [comment]
will close . . .please let me know if it is still not working @ifishlin

**Comment by ifishlin** [comment]
hi, it works good!!~
