### ISSUE TITLE
Table "GRAILS_USER" not found

### ISSUE THREAD

**Issue by holmrenser** [GMOD/Apollo#422]
I frequently get the following error in my jetty logs:
	ERROR spi.SqlExceptionHelper  - Table "GRAILS_USER" not found; SQL statement:

After these errors al kinds of things happen:
-Refreshing causes a crash: the browser shows 'an error has occurred' and I have to restart my jetty
-After a refresh my previously loaded organisms and users are no longer available

Also: after restarting jetty I seem to have lost all configurations and manual annotations. I am not sure if this is normal behaviour though.

**Comment by nathandunn** [comment]
The mainline is still actively under development (WebApollo2) so it may be a bit buggy, though we do get it up and running with out the below errors.  Our latest stable release (1.0.4) is found here:  https://github.com/GMOD/Apollo/releases  and we will provide a conversion script.

That being said, what you are most likely running into is a misconfigured DataSource.    If you are running in Jetty (I think that this is the normal dev mode), you should have an "apollo-config” in your root directory (same level as the Readme.md) that looks like this based on sample-postgres-apollo-config.groovy:

    production{
      dataSource.dbCreate = "update" // one of 'create', 'create-drop', 'update', 'validate', ''
      dataSource.username = “mydatabaseusername"
      dataSource.password = "mydatabasepassword"
      dataSource.driverClassName = "org.postgresql.Driver"
      dataSource.dialect = org.hibernate.dialect.PostgresPlusDialect
      dataSource.url = "jdbc:postgresql://localhost/apollo-production”
}

Notice that dbCreate is set to “update”.  To get this to work you have to:

1 - create a new database
2 - launch the server.  The server automatically creates the schema based on the code.  

If you had create-drop selected it would drop it each time (why it is set to that for the test environment).

If my advice is not working, please post your apollo-config.groovy file (without any classified information) if it doesn’t work. 

Thanks,

Nathan

**Comment by holmrenser** [comment]
Here is my full apollo-config.groovy:

    grails {


        environments {
            development {
                dataSource.dbCreate = "update" // one of 'create', 'create-drop', 'update', 'validate', ''
                dataSource.username = "panwu01x14"
                dataSource.password = "panwu01x14"
                dataSource.driverClassName = "org.postgresql.Driver"
                dataSource.dialect = org.hibernate.dialect.PostgresPlusDialect
                dataSource.url = "jdbc:postgresql://localhost/apollo"
            }
            test {
                dataSource.dbCreate = "create-drop" // one of 'create', 'create-drop', 'update', 'validate', ''
                dataSource.username = "panwu01x14"
                dataSource.password = "panwu01x14"
                dataSource.driverClassName = "org.postgresql.Driver"
                dataSource.dialect = org.hibernate.dialect.PostgresPlusDialect
                dataSource.url = "jdbc:postgresql://localhost/apollo-test"
            }
            production {
                dataSource{
                    dbCreate = "update" // one of 'create', 'create-drop', 'update', 'validate', ''
                    username = "panwu01x14"
                    password = "panwu01x14"
                    driverClassName = "org.postgresql.Driver"
                    dialect = org.hibernate.dialect.PostgresPlusDialect
                    url = "jdbc:postgresql://localhost/apollo-production"
                    properties {
                        // See http://grails.org/doc/latest/guide/conf.html#dataSource for documentation
                        jmxEnabled = true
                        initialSize = 5
                        maxActive = 50
                        minIdle = 5
                        maxIdle = 25
                        maxWait = 10000
                        maxAge = 10 * 60000
                        timeBetweenEvictionRunsMillis = 5000
                        minEvictableIdleTimeMillis = 60000
                        validationQuery = "SELECT 1"
                        validationQueryTimeout = 3
                        validationInterval = 15000
                        testOnBorrow = true
                        testWhileIdle = true
                        testOnReturn = false
                        jdbcInterceptors = "ConnectionState"
                        defaultTransactionIsolation = java.sql.Connection.TRANSACTION_READ_COMMITTED
                    }
                }
            }
        }

    }

I am actually doing exactly what you describe. When everything runs I do the following:

    psql -d apollo-production -U panwu01x14 -W
    apollo-production=# \dt
    No relations found.

This would mean no configurations are set?

**Comment by nathandunn** [comment]
I'm wondering if this is related to #423 . . .

**Comment by cmdcolin** [comment]
I'm not sure if this is related but I thought that&nbsp;apollo-config.groovy should not have the outer grails {} block. I previously had problems with this that were fixed by removing that



On May 29, 2015 10:31 AM, Nathan Dunn &lt;notifications@github.com&gt; wrote: 


I'm wondering if this is related to #423 . . .

**Comment by nathandunn** [comment]
@cmdcolin   Good catch.  @holmrenser  we updated the sample configs to get rid of those as they didn't seem to be as portable.  Try it that way and let us know.   I will still try it with Jetty to double-check.

**Comment by nathandunn** [comment]
@holmrenser   I'm going to close this.  Please feel free to re-open if you continue to experience this issue.

**Comment by holmrenser** [comment]
After a short break I checked the suggested fix and it worked. Cheers!
