### ISSUE TITLE
Jetty: No Spring WebApplicationInitializer types detected on classpath

### ISSUE THREAD

**Issue by holmrenser** [GMOD/Apollo#423]
I am serving webapollo via jetty and get the following error in my log when starting up:

	2015-05-29 13:14:31.989:INFO:apollo:main: No Spring WebApplicationInitializer types detected on classpath

I read this somewhere:

The problem is that Jetty's AnnotationConfiguration class does not scan non-jar resources on the classpath (except under WEB-INF/classes).

Is this relevant?

**Comment by nathandunn** [comment]
I will take a look.  Our dev environment is typically jetty, but our war files are launched with tomat.

**Comment by nathandunn** [comment]
What version of Jetty are you using?  I will setup the same.

**Comment by nathandunn** [comment]
A couple more things:
1 - if you can enable websockets in Jetty, I would recommend it
2 - if you want to run WA 2.0.0 (what we're actively developing on the mainline), I would recommend upgrading to tomcat 8
3 - If you want to run a bug-free Apollo right now that will likely work with Jetty, I would recommend our 1.0.4 release.  https://github.com/GMOD/Apollo/releases/tag/1.0.4

**Comment by nathandunn** [comment]
I was wrong . .  it runs tomcat in dev-mode.   I switched it to Jetty, but the grails plugin doesn't support Websockets by default (but the fallback works).  

I tested with Jetty 9 and WA2 and it worked perfectly (and includes WebSockets).  

Are you running grails 2.4.4?

**Comment by nathandunn** [comment]
I'm going to close this for now.  Please let me know if you continue to have trouble or there are additional details.

**Comment by holmrenser** [comment]
I was away for a vacation, so I could not respond. Basically the same is still happening.

I am running jetty 9.2.10 and grails 2.4.4.

**Comment by cmdcolin** [comment]
Are there any other errors? Like, the page is blank or something? I am just wondering because in your original post, the message seems to be an "info" level message rather than an error.

I have also tried installing jetty with homebrew and it seemed to work ok so far

**Comment by nathandunn** [comment]
@holmrenser   

What version of Java are you using?  (java -version,  javac -version) I would use 1.7 minimally.

http://stackoverflow.com/questions/22938689/info-no-spring-webapplicationinitializer-types-detected-on-classpath

Additionally, make sure to completely clean your war directory when you fix it:

If you deploy your war file to:  /var/lib/tomcat/webapps/Apollo2.war

You'll want to remove both the directory and the war file (rm -rf /va/lib/tomcat/webapps/Apollo2* ).  

Also, in the Apollo checkout directory try:  
 - rm -rf target 
 - ./apollo clean  (should do the same as above)

**Comment by holmrenser** [comment]
@cmdcolin Actually you're right, the message is at the INFO level. This didn't produce any errors in the end so I guess this can be closed?

**Comment by 344553788** [comment]
when i was start up the project, the error was happened which is "No Spring WebApplicationInitializer types detected on classpath". and what to do next?

**Comment by nathandunn** [comment]
@344553788 I'll need some more details (and maybe a separate issue).   Details that would be helpful:

- process you used to create the war
- the full tomcat log once you started up, etc.
- what version you are using
