### ISSUE TITLE
(3d) Issue while creating sequence alterations

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#427]
Branch: sequence-alternation-fix

### To fix (testing GB40788-RA) :
- [x] insertion fmin location is always -1
- [x] Deletion must record length
- [x] Cannot create genomic insertions within exons of some multi-exon gene (ex: GB42149-RA)
- [x] Cannot create genomic insertions within introns of a gene
- [x] Should be able to revert CDS if deleting a sequence alteration (maybe just debug mode).

**Comment by nathandunn** [comment]
The issue is that it has a localCoordinate for the insertion that is "global", and stored / retrieved as such.   Then it errors out and always puts it back on 0.

**Comment by nathandunn** [comment]
Currently the problem is that when it recalculates the stop codons / ORF after the insertion, it starts / stops in the wrong place.

**Comment by nathandunn** [comment]
Talked with @monicacecilia   We found that the exported sequence in WA1 was correct, though visually it was not visually represented on the same strand, nor drawn in the correct place.

**Comment by nathandunn** [comment]
It looks like its setting the CDS just off of the first exon only.

**Comment by deepakunni3** [comment]
sequence-alternation-fix branch merged to master.
 All changes related to this bug is on master.

While working on this issue, a new bug was encountered. See #442

**Comment by monicacecilia** [comment]
I can confirm that:
- it is possible to create genomic insertions within exons 
- it is possible to create genomic insertions within introns of a gene
- CDS is reverted to previous state when deleting a sequence alteration

hooray! :dancer: 

However, I am unable to confirm that: 
- insertion fmin location is no longer -1
- the report of a deletion is recording its length

As I mentioned on #420 I cannot find where alterations are being recorded.

**Comment by monicacecilia** [comment]
I am able to confirm that all the errors have been corrected. 
:dancer:
