### ISSUE TITLE
get peptide sequence not working properly

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#428]
- [x] Get peptide sequence of a single exon, of a multi-exon gene, fails.
- [x] Get peptide sequence of GB42152-RA results in an incomplete sequence (misses an exon).

Related to #427

**Comment by nathandunn** [comment]
@deepakunni3   This change is on a branch: https://github.com/GMOD/Apollo/commit/0e5c7069f310ba64de414b51f43d41c955e99bb4

However, it fixes the error with getting the Peptide (you have to create the relationship from both sides, Feature <->FeatureLocation ).  

I'm still getting a difference with Genomic region, but everything else seems to be correct.

**Comment by nathandunn** [comment]
@deepakunni3   I inadvertently fixed this as well.   Please review these changes and let me know if you think they're wrong or I'm missing something bigger.   If you have a test built-up, that would be great, as well.  I can also just expand what I have (though tests need to use a Gene from Group 1.10)

Thanks.

**Comment by deepakunni3** [comment]
@nathandunn This works now. 

Will add integration tests to catch this problem in the future.

**Comment by monicacecilia** [comment]
I have not had any issues retrieving peptide sequences. This issue has been corrected. :dancer:
