### ISSUE TITLE
(1d) FASTA exports of annotations should always include insertions 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#429]
When exporting FASTA sequence of UcA, the behavior is different.  Currently we emulate WA1, but I think we should probably be consistent with WA2.

- [x]  get_sequence (on the annotation itself), integrates alterations
- [x]  save track data -> FASTA, exports the original sequence only (no alterations)
- [x] SequencePanel - FASTA , only exports the original sequence (no alterations)

**Comment by nathandunn** [comment]
From #420  . .  just splitting up the issue to track separately.   FYI @deepakunni3  @monicacecilia

**Comment by nathandunn** [comment]
Marked it as important so we don't forget.  Just have to finish fixing the sequence alteration code, first.

**Comment by deepakunni3** [comment]
Export of FASTA from U-cA as well as Export Panel includes alterations as part of the sequence, when alterations are present.

**Comment by nathandunn** [comment]
you work fast!  I'll check them when I deploy.

**Comment by deepakunni3** [comment]
:+1:

**Comment by monicacecilia** [comment]
they do now. :dancer:
