### ISSUE TITLE
Error creating user

### ISSUE THREAD

**Issue by lfaino** [GMOD/Apollo#432]
Dear,
I have a problem to create additional users. I was able to create the first user but now do not allow to create more. the error is 

error creating user
failed to add the user null

however, I can create organisms
thanks
Luigi

**Comment by nathandunn** [comment]
Can you provide more details and/or screen shots? 

It should be a matter of clicking on “Create” in the user’s tab, filling out the forms and hitting save. 




Thanks,

Nathan

**Comment by lfaino** [comment]
Hi Nathan,
The problem is solved. I think that it was the access to the database very slow. Actually, I noticed that the V2.0 is very slow compared to previously version. Can you confirm this?

Luigi

**Comment by nathandunn** [comment]
@lfaino   Glad it worked.  It is a little slower (esp. if using H2, but even with a regular DB).  Once we get everything working the way we want, we will focus on optimization.  Also, make sure you have sufficient memory for tomcat (1-2 GB).  Less than that and you will see significant slow-downs.

http://webapollo.readthedocs.org/en/latest/Troubleshooting/index.html?highlight=tomcat

**Comment by lfaino** [comment]
I gave 10g to tomcat or jetty. It is slow. Do you have any idea when the optimization would start?





Inviato dal mio dispositivo Samsung


-------- Messaggio originale --------
Da: Nathan Dunn <notifications@github.com>
Data: 05/06/2015 22:44 (GMT+01:00)
A: GMOD/Apollo <Apollo@noreply.github.com>
Cc: "Faino, Luigi" <luigi.faino@wur.nl>
Oggetto: Re: [Apollo] Error creating user (#432)


@lfaino<https://github.com/lfaino> Glad it worked. It is a little slower (esp. if using H2, but even with a regular DB). Once we get everything working the way we want, we will focus on optimization. Also, make sure you have sufficient memory for tomcat (1-2 GB). Less than that and you will see significant slow-downs.

http://webapollo.readthedocs.org/en/latest/Troubleshooting/index.html?highlight=tomcat

-

**Comment by nathandunn** [comment]
Should not need more than 1G unless you have a lot of organisms. 

When part is slow?  Some operations, like merges, adds, and exports are significantly slower right now.

Nathan
