### ISSUE TITLE
(3d) allow only some organisms to be public via jbrowse 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#433]

**Comment by nathandunn** [comment]
Not sure if this is redundant.

**Comment by cmdcolin** [comment]
I think it's still a good issue. Currently any organism can create the public link to browser. Would probably be good to make that optional in some cases.

It would probably be pretty easy to add this on the "create organism" panel

**Comment by nathandunn** [comment]
It is related sort of to #17  . . . and all of the permission code in 2.0.1.

**Comment by cmdcolin** [comment]
True. I guess that is concerned with public vs private tracks, but the concept of public vs private organisms might be worthwhile too.

**Comment by cmdcolin** [comment]
I know that phytozome has done some stuff using just Apache htaccess to make private organism browsers, but of course, we aren't really using Apache!

**Comment by nathandunn** [comment]
FYI: also request via chestnut group as well.  I think that this is on the USDA list as well.

**Comment by cmdcolin** [comment]
One thing that was happening with 2.0.0 is that in the public jbrowse mode, the organism wouldn't be displayed in top left. This was actually desirable according to Chris E so I added that here https://github.com/GMOD/Apollo/tree/display_organism

It could be extended to perhaps enumerate organisms that have a "public" attribute added to them

**Comment by nathandunn** [comment]
I think that would be fine so long as you know what organism you are on (somewhere).  If you could set the organism based on the URL that would be great, as well.

**Comment by cmdcolin** [comment]
>>If you could set the organism based on the URL that would be great, as well.
Yes! I mentioned a potential strategy for this here https://github.com/GMOD/Apollo/issues/441

**Comment by cmdcolin** [comment]
Trying to fast track this for a special use case at our lab

**Comment by nathandunn** [comment]
:+1:

**Comment by cmdcolin** [comment]
I made a basic implementation of this on the display_organisms branch.

It basically just adds a checkbox to the OrganismPanel, and a -public option for the add_organism.groovy web services script

https://github.com/GMOD/Apollo/tree/display_organism


Might be almost ready but I merged in changes from master and it started failing isoform tests

**Comment by nathandunn** [comment]
To test:
- basically when you go to this page:

http://icebox.lbl.gov/Apollo-staging/jbrowse/

Only "public" organisms should be shown.  This can be marked in the organism panel.

**Comment by monicacecilia** [comment]
Will close this one when we close #626 to make sure going back to seeing the _Annotator Panel_ is ready.

**Comment by monicacecilia** [comment]
:dancer:
