### ISSUE TITLE
(1d) Multi-select drag-and-drop produces error, should merge features (WA2)

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#434]
I was testing some features with multi selecting features and dragging/dropping them.

I think a common example from WA1 was selecting two features, and dragging them together onto the annotation track, which implied a merge.

This produces an error like this currently:

    | Error 2015-06-05 15:40:29,266 [clientInboundChannel-2] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
    Message: JSONObject["name"] not found.
        Line | Method
    ->>  245 | $tt__generateTranscript in org.bbop.apollo.FeatureService
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    |    678 | $tt__addTranscript      in org.bbop.apollo.RequestHandlingService
    |    823 | doCall . . . . . . . .  in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure3_closure4_closure5
    |    822 | doCall                  in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure3_closure4
    |    818 | doCall . . . . . . . .  in org.bbop.apollo.AnnotationEditorController$_annotationEditor_closure3
    |    289 | call                    in groovyx.gpars.group.PGroup$3
    |    313 | run . . . . . . . . . . in groovyx.gpars.group.PGroup$4
    |   1145 | runWorker               in java.util.concurrent.ThreadPoolExecutor
    |    615 | run . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
    ^    744 | run                     in java.lang.Thread
   
In WA1 it does a merge.

**Comment by cmdcolin** [comment]
Note: the standard merge where you use the "right click->merge" on the annottrack still works. It's just the multi-select drag and drop

**Comment by nathandunn** [comment]
Interesting, the "merge" is done up-stream in the JSON file.   The "name" obviously is not being passed into the JSON string:
```
String geneName = jsonTranscript.getString(FeatureStringEnum.NAME.value)       // error here from above
```
sample JSON passed in with merge:
```
{ "track": "Annotations-Group1.10", "features": [{"location":{"fmin":403882,"fmax":414600,"strand":1},"type":{"cv":{"name":"sequence"},"name":"mRNA"},"children":[{"location":{"fmin":403882,"fmax":404044,"strand":1},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"fmin":405031,"fmax":405154,"strand":1},"type":{"cv":{"name":"sequence"},"name":"exon"}},{"location":{"fmin":414369,"fmax":414600,"strand":1},"type":{"cv":{"name":"sequence"},"name":"exon"}}]}], "operation": "add_transcript" }
```
In this case the name is auto-assigned, which is all you can do.   This code uses the group name.

**Comment by monicacecilia** [comment]
Multi-drag&drop is working as "expected by Colin" -- 

I must confess the behaviour of automatically merging models that are being dragged and dropped together is news to me. - I'll write a separate issue about this - .

**Comment by selewis** [comment]
We (apollo) has always merged all spans that were dragged-dropped as a
unit. This is absolutely the behavior we need.

Otherwise it creates unnecessary manipulations by the user.

**Comment by monicacecilia** [comment]
Not saying it is isn't useful - just remarking it is news to me.
