### ISSUE TITLE
Proposal for removing the add-webapollo-plugin.pl script

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#435]
One common source of confusion during setup has been the add-webapollo-plugin.pl script. If this step is missed, it often just results in most webapollo features not being loaded, and the browser just uses "jbrowse mode" and people get confused.

In 2.0, it would be good if we can just implicitly load the plugin instead of requiring this script to be run during setup on each data directory. This happens to be quite easy and we already discussed modifying the configuration on the fly in #319

**Comment by nathandunn** [comment]
@cmdcolin   Why don't you try doing this in a branch.   I agree that this would very good for 2.0.0 and fall right in-line with our 0-config philosophy.   If it works out of the box . . . that would be great, if not we can kick it down the road.  

To that end:
1 - How would be handle tracks pre-configured for Apollo? 
2 - How would be handle tracks with elaborate configs?
3 - I don't know the relationship between tracks.conf and trackList.json, but I assume that you always need trackList.json.  

So, are you parsing the JSON file, appending if need be and then spitting it back out as JSON?   I guess that would be pretty easy.  

Interested to see what you come up with.

**Comment by nathandunn** [comment]
Looks good!
