### ISSUE TITLE
import updated bigbed binary format from EBI into evidence tracks

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#439]
we do import bed . . .trying to confirm if we are importing bigbed directly as well, or if we convert it first.

FYI  @monicacecilia  @cmdcolin

**Comment by cmdcolin** [comment]
There is no bigbed support. There is some partial "stub" code in jbrowse, since bigbed has a similar format to bigwig, but there is no way to import it in full yet.

**Comment by cmdcolin** [comment]
I would maybe want to again add interest for this. There is a format called "bigchain" that is basically just a fancy bigbed file the represents the liftover files. We manually converted the chain files to a regular bed for loading (which is what Chris talked about at our meeting) but it would be cool to load these with bigbed

**Comment by cmdcolin** [comment]
Also, biodalliance has support for this which is what made me remember it in the first place :+1:
