### ISSUE TITLE
Move to using websockets from long-polling

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#44]

**Comment by nathandunn** [comment]
So, using the grails-websocket would be by far the easiest as it wraps both Spring and Stomp and would result in most likely a lot less code:

https://github.com/zyro23/grails-spring-websocket

However, since everything is so dojo-fied . . it might be very problematic.    If I re-enable the service via the service endpoint (AnnotationEditorEndpoint) it might work well enough.

**Comment by nathandunn** [comment]
The AMD is the bigger problem . . . even if I get the older code in there, adding the annotation to the controllers, means that I still need access to the grails service classes.   I can do this via websockets . . . or somehow include HTML that will bridge the two implementations.  Its unfortunate that dojo does not support stomp.

**Comment by cmdcolin** [comment]
we use a couple non-AMD modules in webapollo. it's a little hacky but i have examples of this setup at the top of main.js to load some bbop modules.

**Comment by nathandunn** [comment]
Awesome.  I see.      That looks pretty straight-forward.      Doing this with spring and stomp library support eliminates a lot of code.

I also wanted to note that websockets are very well supported on all major web browsers except IE 8 and 9.  



Nathan

**Comment by cmdcolin** [comment]
ie8 and 9 are not really supported by jbrowse either. from the homepage

    Microsoft Internet Explorer (9 and later, 10 required for BAM, BigWig, VCF+Tabix)

**Comment by nathandunn** [comment]
That worked great . . . in here . . . now trying to put it all back together . . on this branch (grails1-realdata) until after the conference.

https://trello.com/c/drb7Fzk4

**Comment by nathandunn** [comment]
Note that I also added a "./copy_client.sh" method for the inteirm.

**Comment by cmdcolin** [comment]
why is sockjs needed? it says it is websocket emulation

**Comment by nathandunn** [comment]
The most important reason to use it is because it integrates directly with Spring and thus Grails.  

SockJS, from this description: 

https://github.com/sockjs/sockjs-client <https://github.com/sockjs/sockjs-client>

tries to use native web sockets first and then uses the fallback.    This is nice, but definitely not essential. 

I think the other reason is that its a nice wrapper around web sockets, as well (on both ends) and requires a lot less (and more manageable code).  

Nathan

**Comment by cmdcolin** [comment]
sockjs has an extra protocol layer built on top of websockets. i would personally vote against it since we already established we don't need the additional backwards compatibility.

**Comment by cmdcolin** [comment]
i dunno. i guess things like socket.io also have an extra protocol. it just seems like it is kind of a silly thing to have but i won't protest

**Comment by nathandunn** [comment]
Convenience wrappers are good things.  Especially if they implement a lot of sane defaults that provide stability, performance, and scalability.

Nathan

**Comment by nathandunn** [comment]
hell's yes!
