### ISSUE TITLE
CDS end is set at the wrong position when several sequence alterations are added to the same gene

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#442]
Related to #427

**Comment by nathandunn** [comment]
@deepakunni3   I'm wondering (though am probably wrong) if it has to do with using this overlap function? 

            // sequence from feature, as is
            residueString = sequenceService.getResiduesFromFeature(feature)
            for (SequenceAlteration eachSequenceAlteration : sequenceAlterations) {
                if (overlapperService.overlaps(eachSequenceAlteration, feature, false)) {
                    sequenceAlterationsInContext.add(eachSequenceAlteration)
                }
            }

I hate to say, but really it needs to be looking upstream (e.g., if you have an upstream insertion or deletion, your downstream coordinates are different).    This is correct @monicacecilia ? 

I'm sure it would be easy to reproduce a case where the sequence alteration is altered and it messes up the overlap calculation.  But you know this code better than me.

**Comment by deepakunni3** [comment]
@nathandunn This is an interesting point.

Perhaps this might be what was missing! :+1: 
Will take a look at it soon.

**Comment by deepakunni3** [comment]
@nathandunn The overlap function compares the fmin and fmax of each alteration with the given mRNA. Since there are no changes to a mRNA's fmin and fmax while adding sequence alterations, this bit of code works fine. 

Here all its doing is getting sequence alterations that overlap with the mRNA. The incorporation of alterations to the sequence is done at a later point. 

i.e. the resulting sequence is calculated dynamically each time.

**Comment by nathandunn** [comment]
@deepakunni3   Ah thanks for the explanation.

**Comment by deepakunni3** [comment]
@nathandunn I have added a fix for this bug and updated the tests.
But it would require extensive testing, similar to #427

**Comment by selewis** [comment]
Coming in late, but...

(e.g., if you have an upstream insertion or deletion, your downstream
coordinates are different).

Yes, all alterations -must- be handled from 5' to 3' as these can change
the effective coordinates.

Furthermore, the reverse complement must either be the first operation on
the transcript sequence, or for things on the minus strand you have to
apply the alterations from 3' to 5'. I would recommend the former.

-S


On Tue, Jun 23, 2015 at 2:37 PM, Deepak <notifications@github.com> wrote:

> @nathandunn <https://github.com/nathandunn> I have added a fix for this
> bug and updated the tests.
> But it would require extensive testing, similar to #427
> <https://github.com/GMOD/Apollo/issues/427>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GMOD/Apollo/issues/442#issuecomment-114648885>.
>



-- 
In the long history of humankind (& animal-kind too) those who learned to
collaborate & improvise most effectively have prevailed - Charles Darwin

**Comment by monicacecilia** [comment]
This is correct. Despite numerous alterations to the reference sequence, the CDS is being accurately produced and I corroborated that the end coordinates are as expected. :dancer:
