### ISSUE TITLE
Add some client side hashing algorithm

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#445]
This feature is debateable, but adding a client side hashing strategy can increase security in many cases (see recent LastPass coverage, their claim is that things are made more secure by client side hashing).

HTTPS is the best scenario for encrypted traffic but not everyone has the ability to set this up and having at least a basic client side hashing can prevent passive sniffing.

**Comment by nathandunn** [comment]
It does protect your password, but it is still insecure, unfortunately.   Someone could simply post the same hash and wala.   Something to chew on.

**Comment by cmdcolin** [comment]
Ya. I think generally the server will send a salt to avoid that.

**Comment by cmdcolin** [comment]
This is probably one of those unnecessary things. I think I saw some other service doing it but really https support is the best way to ensure security.
