### ISSUE TITLE
(1h) Annotations seq/type/length columns overlapping

### ISSUE THREAD

**Issue by holmrenser** [GMOD/Apollo#449]
In the annotations tab of the dashboard, the columns for seq/type/length overlap when the names are too long:

![screen shot 2015-06-22 at 14 08 53](https://cloud.githubusercontent.com/assets/8225367/8281458/6e08777a-18e8-11e5-9def-75fa8f0aba73.png)

**Comment by nathandunn** [comment]
Related to #385 .

**Comment by nathandunn** [comment]
By default these should wrap as they do in the first-column.

**Comment by cmdcolin** [comment]
I think it is wrapping on the "dash" character (the - character)

**Comment by nathandunn** [comment]
I was thinking that as well.   Its just a table cell (e.g.):

<td style="outline-style:none;" __gwt_cell="cell-gwt-uid-173" class="">Group1.10</td>

so, probably just need to add:

td{
    word-wrap:break-word
}



Nathan

**Comment by cmdcolin** [comment]
Ya that works pretty well


    diff --git a/src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.ui.xml b/src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.ui.xml
    index 57393f3..8cdeb8d 100644
    --- a/src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.ui.xml
    +++ b/src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.ui.xml
    @@ -28,6 +28,11 @@
                 margin-bottom: 40px;
             }
 
    +
    +        .dataGrid td  {
    +            word-wrap: break-word;
    +        }
    +
         </ui:style>
         <gwt:SplitLayoutPanel ui:field="splitPanel">
             <gwt:north size="100">
    @@ -81,7 +86,7 @@
                         </gwt:HTMLPanel>
                     </gwt:north>
                     <gwt:center>
    -                    <cellview:DataGrid ui:field="dataGrid"/>
    +                    <cellview:DataGrid ui:field="dataGrid" styleName="{style.dataGrid}" />
~                                                                                                     


I was thinking using ellipses (as I mentioned here #326) but maybe the word break is ok now

**Comment by nathandunn** [comment]
I was thinking about that as well, but you run into the problem of:

GroupABC123_1
GroupABC123_2
GroupABC123_3

if you have an ellipse, you lose the important information.   I think that the wrap will be the better solution.   If you want to commit that solution (if it works for you) that would work.

Thanks,

Nathan

**Comment by nathandunn** [comment]
works great . . thanks @cmdcolin

**Comment by monicacecilia** [comment]
Yes, it's wrapping the words as expected. Nice! Thanks. :dancer:
