### ISSUE TITLE
create upgrade guide doc from 1.0 to 2.0, dev to production, etc.

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#451]
Will be related to #360, #254, #237, and #255. 

- [x] @deepakunni3  review
- [x] @cmdcolin review
- [x] @monicacecilia  review

FYI @childers

**Comment by nathandunn** [comment]
This should just be additional doc.

**Comment by nathandunn** [comment]
If you're the last one close it: @cmdcolin  @monicacecilia  @deepakunni3

**Comment by cmdcolin** [comment]
If you add the Migration.md to https://github.com/GMOD/Apollo/blob/master/mkdocs.yml then it'll go on the readthedocs page

**Comment by nathandunn** [comment]
Just added it.  Thanks.

Nathan

**Comment by monicacecilia** [comment]
Where is it?

**Comment by nathandunn** [comment]
Details details:

https://github.com/GMOD/Apollo/blob/master/docs/Migration.md

**Comment by monicacecilia** [comment]
Well written! Thanks. I like the humorous bits, and it is both succinct and clear. I approve. :dancer:

**Comment by monicacecilia** [comment]
@deepakunni3 @cmdcolin  -- please review and comment / approve at your earliest convenience. :eyeglasses: :coffee:

**Comment by deepakunni3** [comment]
Looks good. :+1: 
Pointing out the scripts for each scenario was a good idea!

**Comment by cmdcolin** [comment]
Checked my checkbox. Haven't tried any migrations yet but the documentation looks fine.

**Comment by nathandunn** [comment]
@cmdcolin  Thanks.  

FYI @childers . . . the doc is edited.  I'm happy to help with any of the migration stuff.
