### ISSUE TITLE
evaluate optimizations

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#452]
- [x] create a stress-test script in order to create a baseline
  - [x] collect data based on iterations and concurrency off both icebox and locally
  - [x] find hot spots with yourkit locally
  - [x] evaluate effect of "Audit" (~5% performance increase without)
  - [x] evaluate: "when we add a transcript, the NonCanonicalSplitSiteService calls the getResiduesWithAlterations which in turn calls getResiduesFromSequence repeatedly for each tiny little two-base splice site. It should ideally just get the whole sequence region, and check for the splice sites in that larger sequence."
     - [x] merge in #454  non_canonical split site optimization
  - [x] add / evaluate read-only caches (e.g., sequence chunk, sequence, etc.) - no improvement
  - [x] should delete feature history
      - [x] use async
- [x] ```performance-improve``` branch to master

- [ ] evaluate other pieces of code
  - [x] search for places to do async functions
  - [ ] find searches that could take advantage of fmin / fmax 
  - [x] optimize getFeatures by adding a fastConvertToJSON
  - [x] optimize getFeatures in other ways, potentially using fmin/fmax
  - [ ] optimize sequence / sequence chunk into a join
  - [ ] optimize getGff3 conversion with better hql query (similar to getFeatures)
- [ ] ```performance-improve``` branch to master

Related to #137 .

**Comment by nathandunn** [comment]
FYI @cmdcolin  @deepakunni3   I added a stress_test.groovy code in order to evaluate changes to code when trying to optimize performance:

https://github.com/GMOD/Apollo/blob/master/docs/web_services/examples/groovy/stress_test.groovy

I allowed iterations (# of times to run the test), load (1-10, # of transcripts to add), and concurrency (# of threads to run at the same time).  

Not completely confident that it is doing, though all of the numbers look correct to me (you can remove the delete portion to test).

**Comment by nathandunn** [comment]
Did an initial load, and this was the SQL badness:  
![screen shot 2015-06-24 at 12 54 43 pm](https://cloud.githubusercontent.com/assets/751274/8339976/4bb10ff0-1a70-11e5-94f6-89cd0d1404d8.png)

./stress_test.groovy -organism Honey1 -username ndunn@me.com -password demo -destinationurl http://localhost:8080/apollo -concurrency 1 -iter 10 -load 2


The worst offender was the audit log at 2.4 seconds (0.24 seconds per iteration), and the equivalent for the others.  By default, that should probably be off.  

This is followed by convertFeatureToJSON and getChildrenForFeatureAndType, using this:

select this_.id as id1_29_0_, this_.version as version2_29_0_, this_.child_feature_id as child_fe3_29_0_, this_.parent_feature_id as parent_f4_29_0_, this_.rank as rank5_29_0_, this_.value as value6_29_0_ from feature_relationship this_ where this_.parent_feature_id=? 1188 0 1679

and getSequenceForChunk:

select this_.id as id1_63_0_, this_.version as version2_63_0_, this_.chunk_number as chunk_nu3_63_0_, this_.residue as residue4_63_0_, this_.sequence_id as sequence5_63_0_ from sequence_chunk this_ where this_.sequence_id=? and this_.chunk_number=? limit ? 1086 1 828

followed by org.bbop.apollo.SequenceService$_getGenomicResiduesFromSequenceWithAlterations_closure5.doCall(TransactionStatus) SequenceService.groovy  :

select distinct sequenceal0_.id as id1_18_, sequenceal0_.version as version2_18_, sequenceal0_.date_created as date_cre3_18_, sequenceal0_.dbxref_id as dbxref_i4_18_, sequenceal0_.description as descript5_18_, sequenceal0_.is_analysis as is_analy6_18_, sequenceal0_.is_obsolete as is_obsol7_18_, sequenceal0_.last_updated as last_upd8_18_, sequenceal0_.md5checksum as md9_18_, sequenceal0_.name as name10_18_, sequenceal0_.sequence_length as sequenc11_18_, sequenceal0_.status_id as status_12_18_, sequenceal0_.symbol as symbol13_18_, sequenceal0_.unique_name as unique_14_18_, sequenceal0_.alteration_residue as alterat16_18_, sequenceal0_.deletion_length as deletio17_18_, sequenceal0_.class as class15_18_ from feature sequenceal0_ inner join feature_location featureloc1_ on sequenceal0_.id=featureloc1_.feature_id inner join sequence sequence2_ on featureloc1_.sequence_id=sequence2_.id where sequenceal0_.class in ('org.bbop.apollo.SequenceAlteration', 'org.bbop.apollo.Insertion', 'org.bbop.apollo.Deletion', 'org.bbop.apollo.Substitution') and sequence2_.id=? 904 1 828

**Comment by nathandunn** [comment]
As predicted (same group):  

![screen shot 2015-06-24 at 1 00 21 pm](https://cloud.githubusercontent.com/assets/751274/8340099/09b8148a-1a71-11e5-9f05-f102585ada79.png)

addTransript is much greater than deleteFeature

**Comment by nathandunn** [comment]
Using run-war after refresh:
```
concurrency,iter,load,total,mean-iter,stdv,per_iter,per_trans,per_feature
1,5,1,7.531,1.506199951171875,0.4268264247618697,1.5062,1.5062,1.5062
Starting testing
concurrency,iter,load,total,mean-iter,stdv,per_iter,per_trans,per_feature
1,5,1,7.421,1.484199951171875,0.5172357417077826,1.4842,1.4842,1.4842
1,5,2,10.354,2.070800048828125,0.6243899522734171,2.0708,2.0708,1.0354
1,5,4,15.245,3.049,0.5536822193280185,3.049,3.049,0.76225
1,5,8,25.139,5.0277998046875,1.0722671075809425,5.0278,5.0278,0.628475
2,5,1,7.119,1.423800048828125,0.441024712317802,1.4238,0.7119,0.7119
2,5,2,9.982,1.9964000244140625,0.4392575589844755,1.9964,0.9982,0.4991
2,5,4,14.744,2.948800048828125,0.6116525259491699,2.9488,1.4744,0.3686
2,5,8,23.869,4.7737998046875,0.534450009355412,4.7738,2.3869,0.2983625
4,5,1,7.33,1.466,0.5279791662556392,1.466,0.3665,0.3665
4,5,2,11.079,2.215800048828125,0.5488996379120685,2.2158,0.55395,0.276975
4,5,4,16.073,3.21460009765625,0.5644831153364998,3.2146,0.80365,0.2009125
4,5,8,25.864,5.1727998046875,0.5387418792891453,5.1728,1.2932,0.16165
1,10,1,12.421,1.2420999755859374,0.5712467997722175,1.2421,1.2421,1.2421
1,10,2,18.19,1.819,0.4946028709985416,1.819,1.819,0.9095
1,10,4,28.135,2.8135,0.534285036286812,2.8135,2.8135,0.703375
1,10,8,47.419,4.74189990234375,0.6478695132895204,4.7419,4.7419,0.5927375
```

**Comment by nathandunn** [comment]
Without audit logging:

```
concurrency,iter,load,total,mean-iter,stdv,per_iter,per_trans,per_feature
1,5,1,6.78,1.356,0.5584496396274243,1.356,1.356,1.356
1,5,2,10.108,2.0215999755859375,0.38842657365968153,2.0216,2.0216,1.0108
1,5,4,16.159,3.231800048828125,0.5884902824176454,3.2318,3.2318,0.80795
1,5,8,41.283,8.256599609375,3.2334840342887112,8.2566,8.2566,1.032075
2,5,1,14.096,2.819199951171875,0.9712738092319796,2.8192,1.4096,1.4096
2,5,2,22.256,4.4512001953125,1.0167629086960244,4.4512,2.2256,1.1128
2,5,4,22.84,4.568,1.4013001106115706,4.568,2.284,0.571
2,5,8,25.178,5.03560009765625,0.6434541067550972,5.0356,2.5178,0.314725
4,5,1,7.522,1.5044000244140625,0.5091809139441501,1.5044,0.3761,0.3761
4,5,2,11.139,2.227800048828125,0.7528285412363163,2.2278,0.55695,0.278475
4,5,4,17.484,3.496800048828125,0.4650298881523638,3.4968,0.8742,0.21855
4,5,8,27.552,5.51039990234375,1.126372607088791,5.5104,1.3776,0.1722
1,10,1,12.267,1.226699951171875,0.5359888933084341,1.2267,1.2267,1.2267
1,10,2,19.024,1.9024000244140624,0.8655589956785154,1.9024,1.9024,0.9512
1,10,4,29.455,2.9455,0.6382197897276455,2.9455,2.9455,0.736375
1,10,8,57.266,5.72660009765625,4.329256518156438,5.7266,5.7266,0.715825
```

**Comment by cmdcolin** [comment]
I started adding "evaluate: "when we add a transcript, the NonCanonicalSplitSiteService calls the getResiduesWithAlterations which in turn calls getResiduesFromSequence repeatedly for each tiny little two-base splice site. It should ideally just get the whole sequence region, and check for the splice sites in that larger sequence."

on the branch https://github.com/GMOD/Apollo/tree/refactor_non_canon

I imagine that it will speed up addTranscript substantially

**Comment by nathandunn** [comment]
Do you think you can merge the master in first? 

I had removed the flanking region concept altogether and that causes numerous conflicts with your branch.    If you run (comparing yourself to master branch)

/Users/ndunn/repositories/Apollo/docs/web_services/examples/groovy/stress_suite.sh  

You should be able to see if there is a net positive difference.    

See other results here:  https://github.com/GMOD/Apollo/issues/452


Nathan

**Comment by cmdcolin** [comment]
@nathandunn yep thanks for noting that. it is pulled into that branch now

I made some pretty big changes but my initial tests show that it is working pretty well.

I introduced my branch here #454 but I would recommend some manual testing first (it passes automated tests though :))

**Comment by nathandunn** [comment]
Numbers for @cmdcolin  Branch ```refactor_non_canon```. . . I may re-run when plugged in: 

```
1,5,1,6.371,1.274199951171875,0.4740725649887367,1.2742,1.2742,1.2742
1,5,2,9.565,1.913,0.5129327441292865,1.913,1.913,0.9565
1,5,4,14.737,2.94739990234375,0.6089640280837613,2.9474,2.9474,0.73685
1,5,8,24.244,4.8487998046875,0.5735249013774381,4.8488,4.8488,0.6061
2,5,1,6.409,1.281800048828125,0.5655323266622343,1.2818,0.6409,0.6409
2,5,2,9.616,1.923199951171875,0.5352969386237885,1.9232,0.9616,0.4808
2,5,4,14.667,2.93339990234375,0.5211940017882017,2.9334,1.4667,0.366675
2,5,8,23.943,4.78860009765625,0.6017982946968196,4.7886,2.3943,0.2992875
4,5,1,7.384,1.476800048828125,0.5168972939569331,1.4768,0.3692,0.3692
4,5,2,10.571,2.114199951171875,0.441505149318782,2.1142,0.52855,0.264275
4,5,4,17.493,3.49860009765625,1.0793531627785227,3.4986,0.87465,0.2186625
4,5,8,29.453,5.89060009765625,0.5354765984615948,5.8906,1.47265,0.18408125
1,10,1,14.016,1.4015999755859374,1.0200001838235129,1.4016,1.4016,1.4016
1,10,2,18.8,1.88,0.7125321045398587,1.88,1.88,0.94
1,10,4,30.329,3.03289990234375,0.6990886254617508,3.0329,3.0329,0.758225
1,10,8,50.083,5.0082998046875,0.729719209696442,5.0083,5.0083,0.6260375
```

**Comment by cmdcolin** [comment]
Yay...slightly faster in most cases :)

![rplot03](https://cloud.githubusercontent.com/assets/6511937/8358555/75194914-1b26-11e5-8b33-781dc9b3a9ba.png)

**Comment by nathandunn** [comment]
@cmdcolin   I was going to say it was slightly slower, but apparently I can't read a graph:

![screen shot 2015-06-25 at 10 51 59 am](https://cloud.githubusercontent.com/assets/751274/8361479/41c4035e-1b28-11e5-9105-136f46c9b0a3.png)
![screen shot 2015-06-25 at 10 51 59 am](https://cloud.githubusercontent.com/assets/751274/8361481/4349817c-1b28-11e5-951d-8f9af7d7db0a.png)

2per .. . are the original ones, the others belong to refactor_non_canon.    I imagine this result would be exacerbated with actual sequence alterations.

I'll merge it once Moni is done testing or for 2.0.1.

**Comment by nathandunn** [comment]
Overall % improvement is about 10% .  However, it should be more when interacting with sequence alterations and is more correct.

**Comment by nathandunn** [comment]
With datasource EhCache enabled, works much faster:

Added this to ```Datasource.groovy``` vis http://grails-plugins.github.io/grails-cache-ehcache/guide/usage.html :
```
hibernate {
    cache.use_second_level_cache=true
    cache.use_query_cache=true
    cache.provider_class='org.hibernate.cache.EhCacheProvider'
}
```

```
concurrency,iter,load,total,mean-iter,stdv,per_iter,per_trans,per_feature
1,5,1,6.669,1.333800048828125,0.5098693919770042,1.3338,1.3338,1.3338
1,5,2,10.755,2.151,0.5431169303197977,2.151,2.151,1.0755
1,5,4,15.046,3.009199951171875,0.656093600410795,3.0092,3.0092,0.7523
1,5,8,26.233,5.24660009765625,1.3461364158212197,5.2466,5.2466,0.655825
2,5,1,6.415,1.283,0.6338280523927606,1.283,0.6415,0.6415
2,5,2,10.047,2.0094000244140626,0.7729496668606566,2.0094,1.0047,0.50235
2,5,4,13.967,2.79339990234375,0.5321138858364814,2.7934,1.3967,0.349175
2,5,8,22.758,4.55160009765625,0.619203672065985,4.5516,2.2758,0.284475
4,5,1,6.881,1.376199951171875,0.609513586805085,1.3762,0.34405,0.34405
4,5,2,10.272,2.05439990234375,0.5228529310427551,2.0544,0.5136,0.2568
4,5,4,18.306,3.661199951171875,2.0802617623751103,3.6612,0.9153,0.228825
4,5,8,25.471,5.0942001953125,1.0681098960313025,5.0942,1.27355,0.15919375
1,10,1,11.278,1.127800048828125,0.5566090133567727,1.1278,1.1278,1.1278
1,10,2,16.758,1.675800048828125,0.5259235626495545,1.6758,1.6758,0.8379
1,10,4,26.503,2.650300048828125,0.6057706610178476,2.6503,2.6503,0.662575
1,10,8,45.772,4.5772001953125,0.5950240278761859,4.5772,4.5772,0.57215
```

**Comment by cmdcolin** [comment]
It does appear to be not a very stark improvement, so we can delay the merge. 
Anyways, my graphs are mostly intended to compare the multiple tables on a specific column (in this case I was looking at the per_trans and per_feature since I thought those might be the most informative)

Here it is with the read only cache added

![rplot](https://cloud.githubusercontent.com/assets/6511937/8363638/ce67cbc0-1b45-11e5-923e-6d21689198b9.png)
![rplot01](https://cloud.githubusercontent.com/assets/6511937/8363639/ce695a76-1b45-11e5-834c-06e129f4dfd1.png)

**Comment by nathandunn** [comment]
Does the red and green include both changes?   I had similar performance improvements with either change.  I had not yet tested the combination. 

I’m on the branch: "performance-improve”, which should include both sets of changes.  

Also, how are you creating read-only cache?   

Nathan

**Comment by cmdcolin** [comment]
I was just using the data from the tables your pasted


Black is from the table that you called without audit logging



Red is from the refactor_non_canon table



Green is the read only cache table (most recent comment)

**Comment by nathandunn** [comment]
Well, here are both:

```
concurrency,iter,load,total,mean-iter,stdv,per_iter,per_trans,per_feature
1,5,1,6.289,1.257800048828125,0.698944069650784,1.2578,1.2578,1.2578
1,5,2,8.291,1.658199951171875,0.6517904667145723,1.6582,1.6582,0.8291
1,5,4,13.106,2.621199951171875,0.5391370999105887,2.6212,2.6212,0.6553
1,5,8,23.162,4.63239990234375,0.9460154266712568,4.6324,4.6324,0.57905
2,5,1,5.49,1.098,0.6285284400884339,1.098,0.549,0.549
2,5,2,7.447,1.4894000244140626,0.5893786452697451,1.4894,0.7447,0.37235
2,5,4,12.995,2.599,0.917791915414382,2.599,1.2995,0.324875
2,5,8,21.737,4.34739990234375,0.7535391081423711,4.3474,2.1737,0.2717125
4,5,1,6.443,1.2885999755859374,0.7620558952596588,1.2886,0.32215,0.32215
4,5,2,8.827,1.7654000244140624,0.6446806864642372,1.7654,0.44135,0.220675
4,5,4,15.429,3.085800048828125,0.5963143571137627,3.0858,0.77145,0.1928625
4,5,8,24.879,4.9757998046875,0.7192140241263376,4.9758,1.24395,0.15549375
1,10,1,9.572,0.9572000122070312,0.7362266125317666,0.9572,0.9572,0.9572
1,10,2,14.783,1.478300048828125,0.6187358836773571,1.4783,1.4783,0.73915
1,10,4,23.454,2.34539990234375,0.7535836881196408,2.3454,2.3454,0.58635
1,10,8,40.821,4.08210009765625,0.5898855026613216,4.0821,4.0821,0.5102625
```

**Comment by nathandunn** [comment]
FYI, I only enabled second-level cache.  I did not setup read-only cache.

**Comment by nathandunn** [comment]
@cmdcolin   Let me know the script you are using to generate the plots and I can add them directly (or we can check in the code).    If doing it by hand no worries.

**Comment by cmdcolin** [comment]
It is just a small R script. Maybe more work than necessary to automate it. Looking good though!

**Comment by nathandunn** [comment]
Explicitly set ehcahce (41a14afc8c3117652fa990e2458f87bdc8db8281):

```
concurrency,iter,load,total,mean-iter,stdv,per_iter,per_trans,per_feature
1,5,1,5.447,1.0894000244140625,0.6046331015582921,1.0894,1.0894,1.0894
1,5,2,7.836,1.567199951171875,0.590419183716112,1.5672,1.5672,0.7836
1,5,4,12.062,2.41239990234375,0.5805697094234249,2.4124,2.4124,0.6031
1,5,8,19.516,3.903199951171875,1.014989070138196,3.9032,3.9032,0.4879
2,5,1,4.853,0.9705999755859375,0.5044791404260438,0.9706,0.4853,0.4853
2,5,2,7.117,1.4234000244140625,0.6373516984365853,1.4234,0.7117,0.35585
2,5,4,10.975,2.195,0.6193625755565153,2.195,1.0975,0.274375
2,5,8,18.429,3.685800048828125,0.48880343377987845,3.6858,1.8429,0.2303625
4,5,1,5.44,1.088,0.7049567362611695,1.088,0.272,0.272
4,5,2,7.541,1.508199951171875,0.5511395580975839,1.5082,0.37705,0.188525
4,5,4,12.999,2.599800048828125,0.5994988010830381,2.5998,0.64995,0.1624875
4,5,8,21.192,4.23839990234375,0.6474157763755839,4.2384,1.0596,0.13245
1,10,1,8.337,0.8337000122070313,0.5453421804243644,0.8337,0.8337,0.8337
1,10,2,12.342,1.234199951171875,0.6191700846697941,1.2342,1.2342,0.6171
1,10,4,20.126,2.0125999755859376,0.4856504980436034,2.0126,2.0126,0.50315
1,10,8,35.891,3.58910009765625,0.6253774110487202,3.5891,3.5891,0.4486375
```

**Comment by cmdcolin** [comment]
Another piece of code that is in dire need of optimization is the getFeatures operation

I added some timing code to the log for this function, and here is the timing outputs in milliseconds

    2015-06-27 16:22:11,073 [http-bio-8080-exec-8] DEBUG apollo.RequestHandlingService  - getFeatures for organism -> sinv and Si_gnF.scaffold04510
    2015-06-27 16:28:05,834 [http-bio-8080-exec-1] DEBUG apollo.RequestHandlingService  - selecting top-level features 41
    2015-06-27 16:28:09,332 [http-bio-8080-exec-1] DEBUG apollo.RequestHandlingService  - selecting transcripts 3498
    2015-06-27 16:29:21,484 [http-bio-8080-exec-1] DEBUG apollo.RequestHandlingService  - convert to json 72152

This means that the database query for 42 top-level features,  it takes a snappy .035 seconds
Then getting the transcripts for the top-level features, 3.498 seconds (slightly slower, but not unbearable)
Then the convert to JSON is just an unbearable 70 seconds.

Needs optimization!

**Comment by nathandunn** [comment]
Can you add it to the checklist and associate it with the fmin / fmax piece.  

By fmin / fmax, this was one of the things I’d meant to fix.   I can quickly grab all of the relevant sub-features, I can easily do a single query between relevant fmin / fmax locations and pull out any reasonable associates.   Same with convertToJSON.   Iterating over relationships is very slow in GORM/Grails, because you are checking the relationships is populated and then pulling it from the database.   Conversely, you could also do a single join query, but really, if the fmin/fmax of the top-level feature doesn’t tell you where the sub-feature is, you have bigger problems (actually, right now it doesn’t, but overlapping CDS *WILL* denote an overlap later).  I think that the performance for doing a single query either way will yield similar results.  

Nathan

**Comment by cmdcolin** [comment]
I think the convertToJSON is just doing too many things. It should just get the relevant attributes that are necessary to render that feature to the screen, or there should be a fastConvertToJSON that is doing that

**Comment by nathandunn** [comment]
Very good point.  Just make sure that they share some code.   Also, add that to a checkbox, so that when we look back on the bug we can see what optimizations we evaluated. 

Thanks,

Nathan

**Comment by cmdcolin** [comment]
Kk. Added that.

**Comment by cmdcolin** [comment]
I was thinking of adding a combined SQL query for getting the children and the children's feature locations in one query from FeatureService too. 


In psql I was trying out something like


    select * from feature_relationship INNER JOIN feature ON (feature.id = feature_relationship.child_feature_id) INNER JOIN feature_location ON (feature_location.feature_id = feature_relationship.child_feature_id)  ;


I found that before, getting the child features and their locations would take about 500ms and i think combining it in one query like this would be an improvement

**Comment by nathandunn** [comment]
Sounds good.  Just make sure to branch etc.  

Nathan

**Comment by nathandunn** [comment]
I think that sequence / sequence chunk could benefit from the same thing. Right now I think it's pulling iteratively. 

Nathan

**Comment by nathandunn** [comment]
Just a note for us @cmdcolin  on what we discussed today. 

You said you would continue to work on these, pulling the good stuff out of the pull request #460, but getting rid of the eager fetching.

**Comment by nathandunn** [comment]
@cmdcolin   Do you want to close this, or leave it open?

**Comment by cmdcolin** [comment]
Close is ok with me. Will reopen if i see something out of the ordinary

**Comment by nathandunn** [comment]
I think we integrated some of this work already, esp. the caching and some work in #137.
