### ISSUE TITLE
Peptide sequence export rules

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#453]
From the #448 issue about stop codons, we had a discussion about peptide sequence exports.

In that thread, we had an annotation that looks like this:

![1234](https://cloud.githubusercontent.com/assets/6511937/8337006/ec93b646-1a6d-11e5-8bcf-23f3785a2626.png)

This has an in frame stop codon

![4567](https://cloud.githubusercontent.com/assets/6511937/8337342/40b7b252-1a70-11e5-854c-008cba3dfa51.png)

This essentially shows how our annotation essentially "trusts" the evidence track, and does not try to calculate longest ORF on import.

Yet, our exported peptide is still trying to "follow" the stop codons in the sequence, so the sequence that we get is highly truncated in this case.

In our old official gene sets, we would ignore these stop codons and place X's instead.

For example, it would be

    >gnl|Sinv_1.0|SINV10883-PA
    LVSMSMEYLVLRLRPLAGIRRAPDNLRRXLRRETQLRPFYAXHRVASRHVASRRASRHVS
    SRHFTSRHITATK(X)EDSTRRSVIECRSVDLGRRAILAKICWNFRLGIRVRKSHPVTPLRR
    HETVDRRPRRYVSRVLDVQVNVLLRLTEEVVYLLHGAERTDLLLGAVGDEPPGGAGRSSA
    VINDVRVTVGIDXARSRSRRSXQPPAIAERNRGFGASVSHRLXLRVFKVYIGIALGVNRE
    SPATFLSDCEPRHRRRRRRRRHRRRPRVGARRRCPSGGGAQSGSVSRSDGDTGITGSRGD
    SHIGRIAVGSQADIEVPTCLRKFPAGKDGRGWRWGXGRSLACNQGVLCSQQQVAVSQKRT
    VRARRAARSESSGGRLGGGGDRQGHPLRFSXKGARRPIAAQDRPRRLVLDAXDRPRVAIV
    EIVXMMRLRRSLFPACR

In our current case (WA1.0, WA2.0 still needs to address #448), we are stopping at the first stop codon though.

    >SINV10883-RA
    LVSMSMEYLVLRLRPLAGIRRAPDNLRRLRRETQLRPFYAHRVASRHVASRRASRHVS
    SRHFTSRHITATK

@deepakunni3 outlined a case for modified export rules that I thought were compelling:

1) on import, annotation CDS boundaries are trusted (currently doing this)
2) if a exon boundary is changed, then setLongestORF is called so CDS boundaries are recalculated (currently doing this)
3) therefore, if the exon boundaries are unchanged, then we can trust the CDS boundaries, and export the peptides for that whole CDS even if there are stops in it. (not doing this, we attempt to truncate protein sequence despite CDS being longer)

**Comment by monicacecilia** [comment]
Hello @cmdcolin & @deepakunni3 

The reasons behind extending the protein beyond a stop in the sequence are escaping me. 

Unless you have annotated that protein to skip over a TGA, which in addition to _Stop_ can also code for a selenocysteine, why else would you want to skip the _Stop_? May I kindly ask that one of you please explain further?

For what I can see in your example, Apollo's logic is correctly truncating the protein when a _Stop_ TAA appears. In the absence of other information, this is expected and appropriate behaviour. 

Thanks! :)

**Comment by cmdcolin** [comment]
The reason is complicated, and I will grant you that much. It arises from fairly bad gene set that we were using.

This gene set aligns proteins straight to the genome, and it calculates the CDS to correspond to that, so splice site and other information on these genes is generally very messy. The issue is that, if we create an annotation from these genes, then we get a highly truncated gene. However, the annotation as you can see here has full length CDS

![1234](https://cloud.githubusercontent.com/assets/6511937/8337006/ec93b646-1a6d-11e5-8bcf-23f3785a2626.png)

In this case, it is unexpected that the protein export is heavily truncated, which is not maybe what you would expect seeing that figure. Indeed, that figure has CDS running the full length of the gene.

The reason for it having the long CDS there is because on import, the setLongestORF is not called, and instead, we "trust" the annotations CDSs. Only after some exon boundaries are edited is the setLongestORF call, which would make the gene more truncated according the the webapollos rules


![x24](https://cloud.githubusercontent.com/assets/6511937/8443521/084f6fa4-1f4d-11e5-9640-4d39ced37d6f.png)

I would say this is a complex issue and not necessarily a bug, but I was notified of this issue by Chris E and it might warrant some more discussion

**Comment by monicacecilia** [comment]
@cmdcolin: yep, I agree. Let's discuss more :) 
If you'd like, I can take a look at the model and the region - and you'd have to please issue credentials to the SINV instance for me. (via pm).

**Comment by selewis** [comment]
Definitely discuss more. I think there has to be alternatives that don't
involved ignoring the biology.

**Comment by nathandunn** [comment]
@cmdcolin  @monicacecilia   Did we ever figure this out?

**Comment by monicacecilia** [comment]
Hi @nathandunn, I don't yet have permissions to access the SINV instance so I am unable to offer further advise. 
What @selewis said, is the most important thing to consider here - we cannot ignore the biology.

**Comment by nathandunn** [comment]
@cmdcolin  Said he is going to get to this a bit later this week or today (granting you permission).

**Comment by cmdcolin** [comment]
I made an account for moni with username: youremail@lbl.gov and password guest


the gene in question was here http://genomes.missouri.edu:8080/Apollo2/annotator/loadLink?loc=Si_gnF.scaffold00779:3139963..3141834&organism=5663&tracks=Sinv_OGSv2.2.3

**Comment by nathandunn** [comment]
Great thanks. 

Nathan

**Comment by nathandunn** [comment]
@monicacecilia   . . . @deepakunni3  said he would take a look at these.

**Comment by deepakunni3** [comment]
Commit 6419e12 (on issue456 branch) fixes this bug.

**Comment by nathandunn** [comment]
@cmdcolin  @deepakunni3   I'll have you double-check that I didn't mess up the merge.

**Comment by monicacecilia** [comment]
Although the sequence export bug reported in #448 has been fixed, in the SINV Apollo instance is still drawing this gene model incorrectly. @cmdcolin @deepakunni3 May I kindly ask one of you to please let me know when you have updated it?

**Comment by nathandunn** [comment]
@cmdcolin  @deepakunni3  I think Moni means updated the Missouri server with 2.0.0-RC3.

**Comment by monicacecilia** [comment]
Hi there, the rules stated above are not correct. 

**"1) on import, annotation CDS boundaries are trusted (currently doing this)"**
 --> This is incorrect. The structure should be adopted as it came from the evidence, i.e. the intron/exon boundaries from the evidence should be retained, but Apollo should calculate the CDS when the model is dragged into the U-cA, without prejudice from the evidence. Apollo should "read" the reference sequence underlying the region, not "think" that the evidence track has any authority to dictate the CDS.

**"2) if a exon boundary is changed, then setLongestORF is called so CDS boundaries are recalculated (currently doing this)"**
--> should happen ALWAYS, every time an edit is conducted.

**"3) therefore, if the exon boundaries are unchanged, then we can trust the CDS boundaries, and export the peptides for that whole CDS even if there are stops in it. (not doing this, we attempt to truncate protein sequence despite CDS being longer)."**
--> This is incorrect. See "1)".

**Comment by cmdcolin** [comment]
Well personally I was surprised by the fact that this behavior was not in place before and so I was throwing up my hands trying to justify it.


Our behavior is now substantially different than previous versions, but maybe it is more accurate.

**Comment by cmdcolin** [comment]
Furthermore: this could be sort of a special case. Like, NCBI has two different pipelines, alignments (NM_ prefix IDs) and gene predictions (XM_ prefix IDs)

The NM_ ones have high quality evidence but the gene models may be messed up (similar to what I posted in OP)

The XM_ ones have good ab initio evidence and gene prediction, so they satisfy the more typical situations

I think the NM_ type evidence can be very valuable (we use it a lot in our lab) so I just thought there might be better ways to support it better (i.e. allow exports of full length peptide even if there are stop codons because we have good protein alignments suggesting that this is just a "error")

**Comment by nathandunn** [comment]
@cmdcolin  @deepakunni3   So we fixed this last night to comply to the updated rules.  See https://github.com/GMOD/Apollo/commit/62267cd6405f46d816e843a164d72b7bfe5ef049   . . . fortunately it was pretty easy.

**Comment by cmdcolin** [comment]
I saw that and that's why I commented


"Our behavior is now substantially different than previous versions"

**Comment by nathandunn** [comment]
Ahh . . thanks.

**Comment by monicacecilia** [comment]
The rules have been updated and I am closing this issue because it is now on WA2.0.0-RC5 :dancer: 

An observation to @cmdcolin @deepakunni3: As far as I can tell, the _Solenopsis_ instance has not yet been updated to reflect this change. Is that a correct assumption? - just an observation; naturally your lab will update it when it is appropriate for your workflow. cheers, ~m.

**Comment by cmdcolin** [comment]
Apparently WA1.0 had a flag called "use_cds_for_new_transcripts" that would disable the setLongestORF on initial import. This value was true by default. Now our WA2.0 behavior is "false" by default (and not configurable)

**Comment by nathandunn** [comment]
Its called in places like this:

https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy#L1544 <https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy#L1544>

-> 

https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/ConfigWrapperService.groovy#L16 <https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/ConfigWrapperService.groovy#L16>

-> 

https://github.com/GMOD/Apollo/blob/master/grails-app/conf/Config.groovy#L187 <https://github.com/GMOD/Apollo/blob/master/grails-app/conf/Config.groovy#L187>

And so you should be able to over-ride it.

However, I agree that it is not used consistently to flag setting the longest ORF or not.   

Furthermore, I think it should be used as a flag passed in on import, not as a global server setting.  

Nathan

**Comment by cmdcolin** [comment]
So that is for the addFeature code but now addTranscript automatically does the setLongestORF by default, correct?

https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy#L660
