### ISSUE TITLE
Add buffered I/O to range requests for extra large file handling

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#455]
I had brought up during meetings that some of our code for implementing the Range requests (which are used to grab chunks of BAM files) have failed for us on our servers. The error simply says "Unable to fetch <ourfile.bam>" or something of this nature

My hypothesis is that the RandomFileAccess class is not well suited for the buffered I/O that would be appropriate for returning these requests

This link seems to confirm that http://stackoverflow.com/questions/10132749/java-randomaccessfile-vs-datainputstream-for-byte-operations

**Comment by cmdcolin** [comment]
Should be fixed now :) much better on our main servers. Could also be backported to the 1.0 branch too

**Comment by nathandunn** [comment]
Thanks.    To test:

1 - view large BAM tracks and observe that it works.

**Comment by nathandunn** [comment]
working

**Comment by monicacecilia** [comment]
ok... I was in the process of testing as well ... w/e. :)

**Comment by nathandunn** [comment]
Yeah, you would only see this on the server either way.

**Comment by cmdcolin** [comment]
This actually still has problems with BAM files that are approx 30 GB

**Comment by cmdcolin** [comment]
This is a fairly esoteric bug and actually, I think it is often said not to host such large files from a servlet container. We can bypass by adding the files to a apache server and serving from there. Will note in documentation
