### ISSUE TITLE
Stop signals resulting from sequence alterations are mishandled in newly created gene annotations

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#458]
This bug is somewhat related to #431. 

####  What to do: 
- [x]  Check that premature stop codons introduced from sequence alterations are accurately read and incorporated in the sequence, and that the CDS stops at that place.
- [x]  Check that selenocysteine residues (U) are not mistakenly added  

## Description
These errors occur on gene annotations newly created after overlapping sequence alterations have been introduced in the area. To test, 1) create a gene annotation, 2) then create a sequence alteration that introduces a premature stop signal on the CDS, then 3) create a new gene annotation and observe what happens with the CDS. 

Expected behavior:
When conducting sequence alterations, the CDS for all features with coordinates that go through those alterations should be affected by the alteration, even when added after the alteration was created.

That is, if you drag first transcript into U-cA --> create sequence alterations --> modify CDS accordingly --> drag and drop second transcript (isoform of the first) into U-cA --> the same modifications resulting from the overlapping sequence alterations should be seen. 

### 1. Apollo is reading amino acid residues despite the presence of a STOP signal, which was prematurely added as a result of a sequence alteration.
In this case, the transcript I added after the alteration was not "aware" of the stop and kept reading the coding sequence through it without highlighting the stop (in purple) in the browser. When using the "Get sequence" function, the stop signal was visible as a an asterisk and additional amino acid residues were included after that. 

The alteration was an insertion: TCTCTCTCTAGAG, which introduced a stop codon. 

This is the resulting peptide sequence for the gene model that was created before the sequence alteration was introduced.
>7552dca7-dc3d-4c1e-b0db-5fce08ec782d (sequence:mRNA) 79 residues [Group1.33:243448-244577 + strand] [peptide]
MARGSSAGFDRHITIFSPEGRYQVEYAFKAINQGGLTSVAVKGVDTAVFATQKKGPKKQNYDHDETIQLA
IISL*SMFI

After the sequence alteration was introduced, I added a second isoform. The resulting sequence for that one, overlapping the already created alteration is:
>a01ff29d-0244-45dd-b206-fb637885834a (sequence:mRNA) 86 residues [Group1.33:243448-244577 + strand] [peptide]
MARGSSAGFDRHITIFSPEGRYQVEYAFKAINQGGLTSVAVKGVDTAVFATQKKGPKKQNYDHDETIQLA
IISL*SMFIYCFISRF

The error here is that these sequences should be identical, and obviously they are not.

### 2. Apollo is adding selenocysteines where a stop (TGA) should be marked. 

Again, this is happening to the gene annotation that was added after the sequence alteration was created.

In this case, Apollo found a TGA codon a few nucleotide residues after the deletion and read it as a selenocysteine (amino acid single letter code = U) instead of introducing a stop signal (marked as star = *). Apollo then stopped reading the string of amino acid residues after that. Additionally the browser display shows that the CDS expands to the end as though the sequence alteration had not caused any changes in the coding sequence. 

Yes, U is also coded by TGA, but the mystery here is that Apollo was not "told" to read a selenocysteine.

So why did Apollo incorporate a selenocysteine without continuing to read the rest of the amino acids, even though it is drawing them? If the logic dictates to draw a selenocysteine, then the rest of amino acids should be also included in the protein sequence obtained using "Get Sequence".
If the logic says that a "Stop" has been encountered and the protein is truncated, then a stop (*) and not a selenocysteine (U) should have been read (and actually, the stop (*) is never included in the "peptide" sequence when reporting it via the "Get Sequence" function. 

In the figure below, "alteration" is the gene model that was already in the Uc-A area when the alteration was created, and "added-later" is the one that was, well, added later.

![screen shot 2015-06-26 at 1 00 57 pm](https://cloud.githubusercontent.com/assets/1714621/8386513/cabd9ea8-1c05-11e5-84a3-ecbde6c3861d.png)

**Comment by nathandunn** [comment]
@monicacecilia  Perfect.  Thanks.  I'll be out next week, but hopefully @deepakunni3  or @cmdcolin  will be able to take a look.

**Comment by deepakunni3** [comment]
@monicacecilia Can I get the name of the gene and the location where sequence alteration was introduced.

**Comment by monicacecilia** [comment]
@deepakunni3  The gene name and coordinates are visible in the figure; for future reference, you can click on the image to see a larger version.
GB40020 Group1.33:240046..240230

**Comment by deepakunni3** [comment]
@monicacecilia Right. I was referring to section 1 that had an insertion of TCTCTCTCTAGAG, which introduced a stop codon. From the coordinates it is clear that the gene is GB40031-RA but I was curious about the coordinate where the insertion was made.

**Comment by monicacecilia** [comment]
@deepakunni3 I'm sure any alteration introducing a stop codon will have the same effect. It does not have to be exactly the same one. I'll try to look for this again... but can't promise I'll be able to find the same place.

**Comment by deepakunni3** [comment]
@monicacecilia Oh, okay. No problem. :)

**Comment by monicacecilia** [comment]
@deepakunni3 and @nathandunn 
this is weeeeiiirrrrd. 
turns out there is an even more bizarre event - I've been trying to figure out where I made the original insertion -that's not the issue here - and when I make another insertion, an old annotation from 2015-06-26 shows up!! and then when I delete the insertion it goes away. 
At first, I thought Deepak was working on the same region, but then I looked at its History, and the "new" annotation is one I made ~10 days ago. 

![screen shot 2015-07-06 at 11 11 31 am](https://cloud.githubusercontent.com/assets/1714621/8529632/88956c40-23d0-11e5-8484-091aa93517bb.png)

**Comment by monicacecilia** [comment]
... also, note the unnecessary "non-canonical splice site" flags that appear --- 

this happens when I make the same insertion TCTCTCTCTAGAG in position 244177 in Group 1.33

![screen shot 2015-07-06 at 11 29 25 am](https://cloud.githubusercontent.com/assets/1714621/8529887/90c2a386-23d2-11e5-9b88-ec46407b300d.png)

**Comment by nathandunn** [comment]
@deepakunni3   You said you are not seeing this, right, but were going to add an integration test for good measure.  Just confirming.

**Comment by deepakunni3** [comment]
@nathandunn My bad. The bug exists.

**Comment by nathandunn** [comment]
Retested and appears to work.

**Comment by monicacecilia** [comment]
Not ready. :cry: somewhat related to process in #453 and #456.

**Comment by nathandunn** [comment]
@deepakunni3   Do you think that this is fixed as well ?

**Comment by monicacecilia** [comment]
"if you drag first transcript into U-cA --> create sequence alterations --> modify CDS accordingly --> drag and drop second transcript (isoform of the first) into U-cA --> the same modifications resulting from the overlapping sequence alterations should be seen." This behavior is now observed. :dancer:
