### ISSUE TITLE
(3d) augment reporting 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#459]
What would want to have in those reports?   If you could iterate each + items.  My initial take would be (glossary genome==organism, annotator==user==editor):

- ~~moved to #488~~
- [x] Config.groovy should automatically go into the drop-down
- [x] identify queries to time
- [x] rollup annotator report to perform better
- [x] adopt the bootstrap theme (angular / jQuery for dynamic loading?)
- [x] General content page / per genome:   
  - [x] Gene Count, 
  - [x] Transcript Count
  - [x] Feature count (for each).   
  - [x] Exon count, Avg # exons/transcript, 
  - [x] # of different feature types? 
  - [x] xx% protein coding?
  - [x] # of references sequences
  - [x] add active annotators
- [x] make apollo header 
- [x] organism link / ref sequences link:
   - [x] annotators active on each
   - [x] gene count
   - [x] transcript count + breakdown (% protein coding)
   - [x] feature count + breakdown
- [x] Annotator content: Same info as in (1) but broken down by annotator. 
    - [x] List of annotators:  Roles /privileges on each organism, features edited per genome
- [x] Resource usage: Memory? Threads?    Something like this:  https://grails.org/plugin/grails-melody ?

**Comment by nathandunn** [comment]
FYI @childers @mpoeulchau

**Comment by selewis** [comment]
On Fri, Jun 26, 2015 at 2:14 PM, Nathan Dunn <notifications@github.com>
wrote:

> What would want to have in those reports? If you could iterate each +
> items. My initial take would be (BTW genome==organism,
> annotator==user==editor):
>
>    -  General content page / per genome: Gene Count, Transcript Count
>    (and type for each). Feature count (for each). Exon count (why not).
>
> Avg # transcripts/gene?
Avg # exons/transcript
# of different feature types? (xx% protein coding?)

**Comment by nathandunn** [comment]
@selewis  Okay.  I've integrated these.

**Comment by mpoelchau** [comment]
I think all of your suggestions are great ideas. I worry that the list of edits will be overkill, though, and difficult to display. I think @childers commented on stats for resource usage already in today's meeting.

**Comment by nathandunn** [comment]
I think for the list of edits . .  . we already have some of this WRT to history for every feature which we track anyway.  Showing high-level would not be hard (and will probably be what you want anyway).   Being able to drill-down and see more would be good.    Anyway, my thought is that these should all have use-cases.  The “changes” between dates from VectorBase is kind of the same thing.  Hopefully its something that I can get started and then can be iterated over or other users can do other stuff in order to fit their specific needs.   

Nathan

**Comment by nathandunn** [comment]
Was going to use java melody, but not compatible with tomcat7 and later . . wow:

https://github.com/javamelody/grails-melody-plugin/issues?q=is%3Aopen

**Comment by nathandunn** [comment]
All of the report screens should work.  This is a first-pass.   I would suggest putting any non-bugs in a separate issue for 2.0.1.  

<img width="569" alt="screen shot 2015-07-23 at 1 49 30 pm" src="https://cloud.githubusercontent.com/assets/751274/8861871/a9a492de-3141-11e5-93dd-c2d4bbfc6d2e.png">

**Comment by nathandunn** [comment]
its there and working . .  the "changes" needs some work and it is being worked on.
