### ISSUE TITLE
Tracklist for honeybees doesn't show up in annotator panel (WA2)

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#461]
See http://icebox.lbl.gov/Apollo2/annotator/index

Also reproduced on our servers

Also, this is maybe another quip, but there is an arbitrary and hardcoded limit of 100 tracks in the trackpanel

We have instances with more than this

**Comment by monicacecilia** [comment]
@cmdcolin I am able to see the lists of tracks in the annotator panel for both Honey1 and Honey2 on icebox.

**Comment by cmdcolin** [comment]
I can also see it now on icebox but unfortunately I still have problems on genomes.


    [15:00:41.747] uncaught exception: com.google.gwt.event.shared.UmbrellaException: Exception caught: Exception caught: (TypeError) : object_0_g$.get_110_g$(...) is null


This is the "vague" exception that can GWT throws that can be narrowed down if i can run the Amel in my development environment (@monicacecelia which ties into creating the data folder download you requested)

**Comment by cmdcolin** [comment]
Here is the error that I get on my local machine now


    Uncaught com.google.gwt.event.shared.UmbrellaException: Exception caught:
    Exception caught: (TypeError) :
    Cannot read property 'isString_2_g$' of nullfireEvent_1_g$ @ HandlerManager.java:129
    fireEvent_5_g$ @ Widget.java:129
    fireNativeEvent_1_g$ @ DomEvent.java:125
    onBrowserEvent_5_g$ @ Widget.java:177
    dispatchEventImpl_0_g$ @ DOM.java:1480
    dispatchEvent_4_g$ @ DOM.java:1419
    dispatchEvent_6_g$ @ DOMImplStandard.java:317
    apply_0_g$ @ Impl.java:247
    entry0_0_g$ @ Impl.java:306
    (anonymous function) @ Impl.java:72


It actually goes away if I remove this extra line from my trackList.json

    "include": ["extraTracks.json"]

As it so happens, I like the extra "include" functionality in trackList.json, so if this could be fixed that would be great.

**Comment by cmdcolin** [comment]
Should be fixed now. This bug occured when no "key" was set on the trackList.json

This is technically valid, only a "label" is required, and in the case where only a label is specified, the key can be equal to the label.

**Comment by nathandunn** [comment]
@monicacecilia  This should be on the server now.

**Comment by nathandunn** [comment]
@cmdcolin   Not sure if Colin should just close this as our trackList.json probably doesn't have this formatting issues.

**Comment by cmdcolin** [comment]
Should be fine
