### ISSUE TITLE
Adding organism permissions for user has problems in WA2

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#463]
The function for adding permissions via the UserController always throws 401 Unauthorized

The code that does this currently is

        if(!permissionService.checkPermissions(dataObject, PermissionEnum.ADMINISTRATE)){
            render status: HttpStatus.UNAUTHORIZED
        }

Even though I am an admin it returns null. It somehow get's into this code in checkPermissions(JSONObject,PermissionEnum) function, and then it returns null because userOrganismPreference.sequence is null:

        if(userOrganismPreference!=null) {
            return userOrganismPreference.sequence
        }

**Comment by cmdcolin** [comment]
Note that technically, the code for adding the permissions was working, but that is only because this code block

    if(!permissionService.checkPermissions(dataObject, PermissionEnum.ADMINISTRATE)){
        render status: HttpStatus.UNAUTHORIZED
    }

Should actually be


    if(!permissionService.checkPermissions(dataObject, PermissionEnum.ADMINISTRATE)){
        render status: HttpStatus.UNAUTHORIZED
        return // break when user is unauthorized
    }

So, we do have a bug on our hands

**Comment by cmdcolin** [comment]
Should be fixed now. We do not want to use the "fancy" checkPermissions in this case. I would suggest in the near future we define our "permissions API" more clearly because the things that it returns can be unclear (Sometimes checkPermissions returns Sequence, sometimes hasPermissions returns Organism, and they update the users preferences sometimes...etc)

**Comment by monicacecilia** [comment]
:+1:

**Comment by monicacecilia** [comment]
Don @nathandunn you get to test this on icebox, yes?

**Comment by nathandunn** [comment]
@monicacecilia  Yes.  This is on icebox.  Sorry should have sent it to you earlier.

**Comment by nathandunn** [comment]
confirmed working on icebox
