### ISSUE TITLE
(2h) Download function in IOServiceController is insecure

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#464]
This function takes an arbitrary filesystem path as an input parameter, reads the file, and outputs it

That is probably not a good thing to do.

**Comment by nathandunn** [comment]
Probably the easiest thing is to maintain a hashmap with this data such that the references are always to the hashmap UUID and file-paths are stored only within memory.

**Comment by nathandunn** [comment]
To Test: 

Export from the track label.  Should work as normal.  

Worked for me (still).

**Comment by nathandunn** [comment]
Works
