### ISSUE TITLE
(2h) Secure SequnceController::exportHandler

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#467]
Based on this fix:

https://github.com/GMOD/Apollo/pull/466

SequenceController has a handle to a map for both, so we can just use that.  

First exportSequences, which should register the UUID filename and then exportHandler is called, which should now pass a UUID.

**Comment by nathandunn** [comment]
to Test: SequencePanel should export GFF3 / FAST as before.

**Comment by cmdcolin** [comment]
This is a dumb dumb question, but why do we maintain both Sequencecontroller::exportHandler and IOControllerService::write

**Comment by nathandunn** [comment]
It takes time to refactor them and we are still migrating from older code.  I think that @deepakunni3  tried to make them use the same methods, though as much as possible.   I'm sure that there are other slight differences as well.

**Comment by cmdcolin** [comment]
Sure just wanted to point that out

**Comment by cmdcolin** [comment]
There is one thing that is kind of annoying about this. Currently, the "link" that we give is a one time use. After that usage is expired, it just throws an error that the user doesnt receive. Either need to persist for longer. This applies to #466 too

**Comment by nathandunn** [comment]
Yesterday you said that was an advantage ;)

**Comment by cmdcolin** [comment]
Well the advantage is that we don't have to periodically run a cleanup script to delete temporary files. I think basically just throwing an error message when such things fail is the best thing to do so that the user can just retry instead of getting confused

**Comment by nathandunn** [comment]
Does it fail ever?  If so, I can just clean it out on a timer, say 30 minutes, and I would add a creation date to the DownloadFile.  Let me know.

**Comment by cmdcolin** [comment]
Right now it has an error message that says to retry the download if the link is empty now. So, should be able to close this

**Comment by nathandunn** [comment]
Let's have @monicacecilia  test and close it to make sure we haven't messed up anything. 

Thanks for adding that.

**Comment by nathandunn** [comment]
@cmdcolin  Did you push the code yet for this bug (I don't see the code reference here).

**Comment by cmdcolin** [comment]
The particular code that made the nicer error message is here b03a766e9bc8


But the particular whole issue here "i.e. Secure SequenceService::exportHandler" is now outdated since #471 removed the exportHandler

I'd might suggest renaming this issue to "Secure the IOService to use one-time-click links" and then check to make sure one-time-click links are working as expected.

**Comment by nathandunn** [comment]
renamed . . . I'll assume that you will retest it.

**Comment by nathandunn** [comment]
Still seems to work . . . to test:

SequencePanel should export GFF3 / FAST as before.

**Comment by nathandunn** [comment]
working on Sequence Panel
