### ISSUE TITLE
'Move to Opposite Strand' function does not recognize stop codons in display or gff3

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#468]
Hi y'all,

I noticed this on our current instance of WA1.0.4 and was able to replicate the issue on the WA2 demo on icebox. If you drag and drop evidence into the Uca track (I've tried RNA-Seq reads and mRNA so far) and flip the strand, models are 1) not truncated at the first stop codon in either the display or the gff3, and 2) the protein sequence is truncated, but not always at the first stop codon. I've created some examples of this on the icebox WA2 site for Honey1 at Group1.1:963667..963843 (177 b). It seems that the gff3 and display coordinates are calculated from the original strand. 

![screen shot 2015-07-08 at 1 59 06 pm 2](https://cloud.githubusercontent.com/assets/5487172/8580747/86eda4c0-2579-11e5-8875-10aa19f8bd66.png)

Issue may or may not be related to issue #55. 

Also, from looking at the protein sequences calculated from these models, I have to admit that I'm confused as to how WA2 determines whether a TGA should represent a selenocysteine or a stop codon in the calculated protein sequence. I look forward to reading the documentation on this later on!

**Comment by nathandunn** [comment]
Ack.  I will take a look.  Glad you found it in both as I used the smart code in both.

**Comment by deepakunni3** [comment]
@nathandunn The fact that the transcript, once flipped to the opposite strand, doesn't have the proper CDS is because setLongestORF() method is not being called.

**Comment by nathandunn** [comment]
Still need to have @monicacecilia  and @mpoelchau  check this.

**Comment by mpoelchau** [comment]
So - is this supposed to be fixed on the demo site (http://icebox.lbl.gov/Apollo2/annotator/index)? Because it doesn't look like it is - I just re-created the same broken model (Name=GB42147-RAa, Group1.1:963204..964163 (961 b), Honey1). Let me know if I'm missing something!

**Comment by nathandunn** [comment]
We haven’t updated the server yet.  Sorry. 

Nathan

**Comment by nathandunn** [comment]
@mpoelchau   I'll update this next week when we tag RC2.   In the interim, it should be on the mainline.

**Comment by mpoelchau** [comment]
Great, thanks!

**Comment by mpoelchau** [comment]
Looks like it works on icebox now - thanks!

**Comment by monicacecilia** [comment]
Bingo on RC3. woop woop! (i.e. yes, it works as expected). :dancer:
