### ISSUE TITLE
Customized annotations for features and transcripts

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#473]
We have some use cases for wanting to annotate some certain generic types of features.

Currently, as nathan put it we have "two different paths" that annotations take: the transcript path, and the generic feature type path, and I am just interested in extending more generic features

Points of interest
-Ability to define some types in config
-Ability to add add some custom domain objects(?)
-Other customizations like dialog boxes or similar things

Related issues #144 #143 #207

**Comment by nathandunn** [comment]
Great thanks.  Could you put this on rc2?  I just want to see if there is anything we should stub in before the 2.0.0 release.

Nathan

**Comment by nathandunn** [comment]
@cmdcolin  Okay I pulled in code for this.

**Comment by deepakunni3** [comment]
@nathandunn Yes, this would be very useful in extending the feature types that can be annotated.

**Comment by selewis** [comment]
What does "generic" mean??

The term is setting off all kinds of alarm bells in my head. Don 't feel
comfortable with this.

**Comment by nathandunn** [comment]
The title should say customizable we even changed it in the code to customizable.

Nathan
