### ISSUE TITLE
(1d) update logout for multiple windows on the same browser

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#480]
- [x] jbrowse standalone is not subscribing to logout events properly
- [x] when logged out on one (per user) should logout on all
- [x] should work on pure jbrowse when logged in (annottrack.js is present)
- [x] should work when embedded (do we need to handle more than once?)
- [x] should work on reports page.   I believe we can use the first code example (with dojo) for that or just subscribe to websockets on each page (can put in the reports header file).   (#513)

**Comment by nathandunn** [comment]
The easiest method to do this, just put in the jbrowse header file:

```
        function warning() {
            window.logoutTimeout = setTimeout(function() { loggedout(); }, 300000); //5 minutes = 300000
            $('#timeoutModal').modal('show');
        }

        function resetWarning() {
            window.warningTimeout = setTimeout(function() { warning(); }, 6900000); //115 minutes = 6900000
            window.logoutTimeout = null;
        }

        function keepalive() {
            $.ajax('/apollo/auth/keepalive');
            resetWarning();
        }

        function loggedout() {
            $('#timeoutModal').modal('hide');
            $('#loggedoutModal').modal('show');
        }

        $(document).ready(function() { resetWarning(); });
```

**Comment by nathandunn** [comment]
Looking into the older Web Apollo code, the AnnotTrack.js was calling this off of long-polling:

```
else if (ioArgs.xhr.status == 403) {
                    track.hide();
                    track.changed();
                    track.handleError({responseText: '{ error: "Logged out" }'});
                    window.location.reload();
                    return;
                }
```

**Comment by nathandunn** [comment]
I am using websockets.  In ed's code, the "close" function is over-written to fire the "Logged out".   Basically we just need from this https://github.com/sockjs/sockjs-client : 

```
sock.onclose = function() {
     console.log('close');
    alert("Logged out") ; 
    window.location.reload(); 
 };
```

Need these on the reports pages as well.

**Comment by cmdcolin** [comment]
I would like to ***pretty please*** avoid the alert box for this one. Just reload with some text box in the LoginDialog that says the user was logged out.

Reason being: if you are navigating in some other random tab, and an alert box comes up in webapollo, most browsers will still pop it up and interrupt everything that you are doing. If it just reloads automatically with some text on the Login box, i am not very annoyed (many banking sites do this for example...)

Generally, I think that the gmail model is even better though. Never even have to think about whether the internet is dead or the connection is down. It just reconnects when ready.

**Comment by cmdcolin** [comment]
Also, yes...this is secondarly annoying that you would auto logout when session is done. Defeats purpose of the remember me cookies.

**Comment by nathandunn** [comment]
The idea is that when the session is logged out (e.g., via expiration or forced logout) it will render these for any other page.  

In the case of the remember-me . .  when you have a session expiration it should check for the cookie and use it to re-login.  

Agreed on the alert box.   I added it to the todo-list.

**Comment by cmdcolin** [comment]
If it is just doing a page refresh when the session expires, then it will indeed relogin if remember me is set.


If it tries to call any "logout" functions, that will expire any remember me functionality. I don't think it is calling any logout functions though so it seems ok

**Comment by nathandunn** [comment]
It's even better than that it's just sending an Ajax request.

Nathan

**Comment by selewis** [comment]
I agree

**Comment by monicacecilia** [comment]
"when logged out on one (per user) should logout on all" is not happening. Instead, the other window stops processing requests and the user has no warnings about being "logged out".

**Comment by nathandunn** [comment]
it should logout on ALL Apollo windows for that browser (won't work cross-browsers)

**Comment by monicacecilia** [comment]
I am only using it on a single browser.

**Comment by monicacecilia** [comment]
... ah, when I used the "Logout" button on the annotation window (browser) it did warn the other windows when logging out.

![screen shot 2015-08-12 at 10 30 22 am](https://cloud.githubusercontent.com/assets/1714621/9231472/3e8dd2c0-40dd-11e5-916f-ac4c3edee960.png)

However, when using the "logout" button on the annotator panel, the other window does not log out and no messages are issued. 

![screen shot 2015-08-12 at 10 31 32 am](https://cloud.githubusercontent.com/assets/1714621/9231481/5109b964-40dd-11e5-9ff2-82aaf570e647.png)

**Comment by nathandunn** [comment]
this is something specific to the proxy on icebox.    Works on the 8080 port as designed.

**Comment by nathandunn** [comment]
There is a problem with the jbrowse standalone mode .

**Comment by cmdcolin** [comment]
Problem? I am testing and it seems like it might give a 404 in proxy but seems to work on normal tomcat. Still weird

**Comment by nathandunn** [comment]
yeah, if you do an operation locally it will send it, but will only refresh the operation on the browsers with the annotator open . . very weird . .

**Comment by nathandunn** [comment]
I take that back . . just rebuilt and now I'm seeing it work perfect . . . I'm wondering if it just didn't build correctly.   Just did a clean-all, run-app with no problems.    Its still not subscribed to logout events, but I think I know what is wrong there.

**Comment by monicacecilia** [comment]
Alright! It even worked across browsers. :) :dancer:
