### ISSUE TITLE
integrate reverse complement in Apollo

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#482]
- ~~sequence~~ moved to #1273
- ~~**edit functionality**~~ moved to #1280
- ~~nclist (chunks)~~ moved to #1281
  - ~~**re-assess what is getting reverse and how, could be that chunk 1 is using 2's and vice versa . ..  maybe chunk values should be reversed**~~
  - ~~create integration tests~~
- [x] getFeatures
   - [x] flip strands on projection 
- [x] nclist (trackData)
   - ~~11.4 case~~ moved to #1270

https://trello.com/c/3tMaHPcQ/100-reverse-complement-hard

Please add additional visualizations as you have time. 

Related somewhat to #481  . . . .

**Comment by nathandunn** [comment]
Just wanted to add this from @cmdcolin   . .  I think that it still needs to be completed for other track types and tested for annotation and Apollo integration (we should automatically over-ride and flip these tracks), but overall it works well within JBrowse.

**Comment by cmdcolin** [comment]
@nathandunn thanks. I think that should be possible. Automatically "upgrading" the store types to use projection types should be possible too
BAM,
BigWig,
NCList,
Sequence

A remaining store class for the annotation track on apollo (that uses a store class called scratchpad)

**Comment by nathandunn** [comment]
Updated interfaces @selewis  @monicacecilia 

![image](https://cloud.githubusercontent.com/assets/751274/18398563/39561b24-7682-11e6-92a7-9df97c83fa99.png)

This implies that the scaffolds are ordered and the entire scaffold is reversed or not.

**Comment by nathandunn** [comment]
It should be noted that a lot of this might already be done.

**Comment by nathandunn** [comment]
moved mega-issue to other issues
