### ISSUE TITLE
(4h) replace all "alert" dialogs with something boot-strappy in GWT

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#489]
I was going to do with for the logout dialog, but I realized that this is everywhere within the jbrowse / apollo-plugin code.  

@cmdcolin  @enuggetry   Let me know if you have any thoughts.  

Gwt-land uses its own bootstrap dialog.  Would be great to emulate this.  Not sure if this is in JBrowse, but doesn't necessarily need to be.

**Comment by nathandunn** [comment]
I think we can at least do this in a lot of GWT-code pretty easily

**Comment by nathandunn** [comment]
Nothing to test here really . . .

**Comment by cmdcolin** [comment]
If you enter invalid user information in the Login then there is a bootbox but there is also some other layer making it impossible to click anything

**Comment by nathandunn** [comment]
Thanks for reporting.   Probably the glass pane . . . I’ll put something else there. 

Nathan

**Comment by nathandunn** [comment]
To test:
- GWT will only create "bootstrap" alerts that look like the attached . . vs the old "alert" dialog of old.  
![screen shot 2015-10-20 at 9 28 52 am](https://cloud.githubusercontent.com/assets/751274/10614056/0f7b990c-770d-11e5-8cdc-603a5e71537a.png)

**Comment by nathandunn** [comment]
You can't really test that everywhere, but let me know if overall they look better or if you have any other changes (or run into any problems).

**Comment by monicacecilia** [comment]
Uh-oh... this one is still an _old style_ alert... 

![screen shot 2015-10-26 at 4 43 13 pm](https://cloud.githubusercontent.com/assets/1714621/10745617/bf6372c0-7c00-11e5-8b69-855c303d00b2.png)

**Comment by monicacecilia** [comment]
otherwise, the ones I've seen are mostly looking fine. :+1:

**Comment by nathandunn** [comment]
I just saw this . . its going to be impossible for you to determine which ones are "dojo" and which ones are GWT / Bootstrap . . .  so I'll close this one for now and open another one to convert the dojo ones to something else

**Comment by monicacecilia** [comment]
:+1:
