### ISSUE TITLE
(1h) add 2.0.0 changelog

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#491]
- [x] list major features
- [x] https://github.com/GMOD/Apollo/issues?q=milestone%3A2.0.0+is%3Aclosed
- [x] https://github.com/GMOD/Apollo/issues?q=milestone%3A2.0.0-RC2+is%3Aclosed
- [x] https://github.com/GMOD/Apollo/issues?q=milestone%3A2.0.0-RC3+is%3Aclosed
- [x] https://github.com/GMOD/Apollo/issues?q=milestone%3A2.0.0-RC4+is%3Aclosed
- [x] https://github.com/GMOD/Apollo/issues?q=milestone%3A2.0.0-RC5+is%3Aclosed
- [x] https://github.com/GMOD/Apollo/issues?q=milestone%3A2.0.0-RC6+is%3Aclosed
- [ ] https://github.com/GMOD/Apollo/issues?q=milestone%3A2.0.0+is%3Aclosed

**Comment by nathandunn** [comment]
List major features and . . . :
https://github.com/GMOD/Apollo/issues?q=milestone%3A2.0.0+is%3Aclosed
https://github.com/GMOD/Apollo/issues?q=milestone%3A2.0.0-RC2+is%3Aclosed

**Comment by cmdcolin** [comment]
I feel like the best thing is to just create it as we go along. Why not have changelog for the RC1 tag, RC2 tag, etc. 

It adds more continuity

**Comment by nathandunn** [comment]
That would be fine.  I think we only have RC1 right now, though, + WA2 features.

Let’s wait on RC2 until we are sure they are all closed in that tag.  
  

Nathan

**Comment by nathandunn** [comment]
Going to start on some of the smaller pieces, but will probably have to wait for all of RC3.

**Comment by cmdcolin** [comment]
#510 did some of this
