### ISSUE TITLE
(4h) add "add_comment", "add_attribute", "set_status" to the web services API

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#492]
- [x] add to the web services API (unless already there)
- [x] add to the doc (is not there)
- [x] write a brief test

**Comment by nathandunn** [comment]
@deepakunni3  Code commits are here:  

9bf11529aef0407fb486a894485d43cf302b820c
6b128da7b48828b1f211f3330d2e7232687ceeae
1140454386b03d12717435653370d1bb783bf66c

**Comment by nathandunn** [comment]
@deepakunni3   Looks good.

**Comment by nathandunn** [comment]
Going to re-test.

**Comment by monicacecilia** [comment]
They are all added. :dancer:
