### ISSUE TITLE
(2d) add "canned attribute" 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#494]
Basically expand attributes to work like canned comments for attribute key/value pairs.  In the VB and USDA workflow there is need for this.

- [ ] provide canned attribute key values (add CannedAttribute object) similar to CannedComment object
- [ ] for each CannedAttribute should provide a list of values.   This could be two tables (CAKey, CAValue)
- [ ] create pages to manage
- [ ] update "edit" box to incorporate these

**Comment by nathandunn** [comment]
FYI @mpoelchau  @childers @selewis

**Comment by childers** [comment]
@nathandunn this sounds really good.

**Comment by nathandunn** [comment]
dupe of #86
