### ISSUE TITLE
(1d) Gene -> Pseudogene post-annotation

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#495]
We had discussed some ways to annotate pseudogenes.  It seemed as though the major problem was that pseudogenes were either initially being annotated wrong (drag and drop default) or that further evidence changed the prediction.  

Ideas:
1 - have users choose on the onset when dragging
2 - allow users to change the type from Gene -> Pseudogene -> Feature (RepeatRegion / TransposableElement). 

If we choose 2, will likely execute SQL manually on backend and re-query the object.  Both quick and complete.   Will probably have to delete attributes (CDS, exons, transcripts etc.) depending on transformation.

**Comment by nathandunn** [comment]
FYI @mpoelchau  @childers @selewis

**Comment by selewis** [comment]
On Thu, Jul 23, 2015 at 11:40 AM, Nathan Dunn <notifications@github.com>
wrote:

> We had discussed some ways to annotate pseudogenes. It seemed as though
> the major problem was that pseudogenes were either initially being
> annotated wrong (drag and drop default) or that further evidence changed
> the prediction.
>
> Ideas:
> 1 - have users choose on the onset when dragging
>
#1 is what we have now. It's awful (prone to errors or creating excessive
demands on the curators. Either way a bad situation)


> 2 - allow users to change the type from Gene -> Pseudogene -> Feature
> (RepeatRegion / TransposableElement)
>

Don't constrain it at all. Users should be able to switch from feature type
A to feature type B as needed (and back again). The wee bit of complexity
is that some features have a different 'depth' and the history will need to
keep track of the prior depth.

Also wanted to add that in past discussions it's clear that 'pseudo' can be
apply to different levels (pseudogene, pseudotranscript, pseudoexon). It
seems to be synonymous with broken/non-functional.  Don't think we need to
go there yet, but bear it in mind.

**Comment by nathandunn** [comment]
This is a duplicate / sub-case of #220  .
