### ISSUE TITLE
create data for human browser on demo server

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#499]
Variants:
- [ ] links rsABCD to cvicdb and GA4GH / UCSC, dbSNP
- [ ] make vertical lines into dots / with varying sizes / colors
# 

Update Evidence tracks:
- [ ] implement using updated gene models (see #481) for evidence tracks
- [ ] implement using updated annotation data (also #481)
# 

Relevant data types . . add to WA2:
- [x] add genbank data  (draggable)
  - [x] recollect raw data
  - [x] fix chr1 configuration 
  - [x] default to Canvas track (for now)
    - [x] chr1 is misconfigured
  - [x] **fix gene look and feel for draggable**
- [x] **verify we can see BRCA1 and BRCA2 variant and gene data**
- [x] verify link: http://icebox.lbl.gov/Apollo2/jbrowse/index.html?overview=1&nav=1&loc=chr1%3A97230113..97691114&tracks=Annotations%2CHomo_sapiens.GRCh38.81.gff3&tracklist=1&highlight=&organism=5402342
- [x] add human refeqs
  - [x] refetch raw data (**working**)
  - [x] map via reference: http://www.ncbi.nlm.nih.gov/projects/genome/assembly/grc/human/data/
  - [x] reprocess (it _looks_ good)
- [ ] clinvar:
  - [ ] get data 
  - [ ] add track
- [ ] dbsnps: http://www.ncbi.nlm.nih.gov/projects/SNP/snp_summary.cgi
  - [ ] get data 
  - [ ] add track
- [ ] 1K genomes
  - [ ] get data (**working**)
  - [ ] configure tracks
  - [ ] add track
- [x] rerun generate_names.pl

**Comment by nathandunn** [comment]
JBrowse for reference:  http://jbrowse.org/ucsc/hg19/touch.html?loc=chr1:208,056,300..208,073,080&tracks=DNA,knownGene,ccdsGene,snp131,pgWatson,simpleRepeat

 . . I think that we'll be using hg38 unless there is a reason not to.

**Comment by selewis** [comment]
Check with Nicole.
I think there may have been an update. Important to have the up to date
version.

**Comment by nathandunn** [comment]
@nlwashington  let me know how if this sounds like a good starting point (the checklist above).  I expect we'll do a bit of iteration over it.  

http://icebox.lbl.gov/WebApolloHuman/jbrowse/?loc=chr11%3A476355..654095&tracks=DNA%2CAnnotations%2COGS-GRCh38%2COGS-GRCh38-gene&highlight=

**Comment by cmdcolin** [comment]
I mentioned this awhile back but the gene track is getting confused by the presence of some of the pseudogenes for some reason (I don't have the data file but generally I would load pseudogenes as a separate track anyways). I would load just the genes from the file using either using the --type "gene" argument for a CanvasFeatures type track or --type "mRNA" in HTMLFeatures. We would normally prefer HTMLFeatures in WebApollo anyways to --type "mRNA" is most likely the best option

![screenshot-icebox lbl gov 2015-07-24 15-20-35](https://cloud.githubusercontent.com/assets/6511937/8882801/d91ba40e-3217-11e5-9f40-40417457ad81.png)

**Comment by cmdcolin** [comment]
The Red highlighted features in the above image are technically a glitchy pseudogene, probably just need to clean up the GFF if these need to be loaded cc @deepakunni3

**Comment by nathandunn** [comment]
definitely need to clean up the GFF . . . I don't even think that all of the chromosomes load.

**Comment by nathandunn** [comment]
@monicacecilia  @selewis  This is the human server corresponding to our deliverables and what we'd put in the grant (as opposed to icebox): 

https://genome.monarchinitiative.org/apollo/507/jbrowse/index.html?loc=chr7:102240331..102240644&tracks=dbsnps,clinvar,GenBank%20TopLevel%20MRNA

I'm not sure which of this we want to move over.  The ClinVar and dbSnp data is manageable, but the modEncode data is massive.

**Comment by nathandunn** [comment]
Kind of done
