### ISSUE TITLE
Track panel has a hard limit on 100 tracks

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#502]
We have some browsers where there are over 100 tracks, so the annotator panel track browser cannot display all our tracks.

https://github.com/GMOD/Apollo/blob/master/src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java#L61

We could just increase the limit but I was wondering if anyone has other ideas.

**Comment by nathandunn** [comment]
Feel free to change the size to somerhign reasonable and close this.   You could also add a paginator as well, pretty easily.  

Long-term I want to do something like #227 .

**Comment by cmdcolin** [comment]
Raised to 1000. Will defer to that issue for future stuff.
