### ISSUE TITLE
(1h) adding organism should only support "absolute" paths

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#503]
if the path does not start with a "/" it should be rejected, otherwise will try to load relative to tomcat.

**Comment by cmdcolin** [comment]
I just added a scenario where we might want to load data relative to tomcat in #501 

I just don't see why we would necessarily disallow this

**Comment by nathandunn** [comment]
That is not considered best practice for working with tomcat.   

Nathan

**Comment by nathandunn** [comment]
Test:
Try to add an organism withOUT an absolute path as a directory.  Should see warning.

**Comment by nathandunn** [comment]
Confimr works
