### ISSUE TITLE
test annotation migration and generate performance statistics for live database

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#507]
- [x]  pre-fill database with annotations to observe differences (wait until after user-migrating a DB)
- [x]  do a network latency test (off of icebox) to observe differences

NAL / i5K can have:
100 organisms per server( ? . . not sure what that limit is)
5K annotations per organism
up to 100K sequences per organism
so maybe 1Mil annotations per server

**Comment by childers** [comment]
Our record right now is around 148k sequences for one assembly. Hopefully that will be an outlier moving forward, but that's our upper bound as of now.

**Comment by nathandunn** [comment]
I don't think it will effect it.  It performs better with fewer annotations per sequence.  

Nathan

**Comment by nathandunn** [comment]
Did network latency test off of icebox and still good results . . . some initial erroring out on one of the genes, but other than that ran for 10 hours fine.  Was pretty much 3.5 ops / sec for most of the testing time.   Assuming that at some point there were some network latency issues.  

![screen shot 2015-07-30 at 6 19 58 am](https://cloud.githubusercontent.com/assets/751274/8989916/012c2f82-36a4-11e5-862f-bba3c34989da.png)

**Comment by nathandunn** [comment]
This has already been done
