### ISSUE TITLE
refactor DraggableHTMLFeatures to be more polymorphic

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#508]
Basically we can't use any of @enuggetry related to #481  changes without this being refactored.

**Comment by cmdcolin** [comment]
Just to be more precise about what (I think) is happening, DraggableHTMLFeatures does inherit from HTMLFeatures, but it is fully overriding various methods from HTMLFeatures instead of delegating properly calling super()/this.inherited().

**Comment by cmdcolin** [comment]
Prevents new introns from being drawn and dragged  in the #481

**Comment by nathandunn** [comment]
This may go away if @enuggetry  fix works.

**Comment by enuggetry** [comment]
I refactored it into a JB plugin that operates out-of-band (ie post render).
It requires a minor change to HTMLFeatures.js and doesn't require any changes to DraggableHTMLFeatures.js.
It has some special code to handle the nested subfeatures in Apollo, which JBrowse doesn't have.
Currently resides in a separate branch.
https://github.com/GMOD/jbrowse/tree/Eric_work_f1/plugins/NeatFeatures

My preliminary testing suggest that it seems to work with the annotation track.

**Comment by nathandunn** [comment]
I think we can close this, but re-open it @cmdcolin  if there is work you want to do on this still.
