### ISSUE TITLE
!!(2h) only able to add 4 organism max to permissions

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#512]
- [x] user page
- [x] group page

**Comment by cmdcolin** [comment]
Pretty much same issue as https://github.com/GMOD/Apollo/issues/502?

**Comment by nathandunn** [comment]
@cmdcolin   It is similar, yes.

**Comment by nathandunn** [comment]
To Test:  have more than 4 organisms.  Try to assign permissions to a user and group for the "fifth" one.

**Comment by monicacecilia** [comment]
I was able to add permissions for >4 organisms.
