### ISSUE TITLE
(1h) add security to reports 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#513]
should be admin in order to view report

to test:
- logout and connect to report url 

OR

- logout and login as user and connect to report url

**Comment by nathandunn** [comment]
Test:  Logout and see if you can still get to the reports pages.

**Comment by monicacecilia** [comment]
I logged in as "user" and I am still able to see all the reports. :confused:

**Comment by nathandunn** [comment]
So, if the user is an admin on at least one project they are allowed to see these.

**Comment by monicacecilia** [comment]
The user is NOT an admin, and it only has permissions to see one organism, yet it can see all reports.

**Comment by monicacecilia** [comment]
.... k, done.
