### ISSUE TITLE
(4h) Need to optimize merges.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#515]
Optimize:
- [x] mergeTranscripts (use TS::convertToJSON())
- [x] addExon  /  TranscriptService::addExon() .  . . use queries and TS::convertToJSON()

It is possible to merge two gene models by dragging a model on top of one already on the "User-created Annotations" (U-cA) area. However, the merge is very slow (top image). 
Merges are occurring faster when both gene models are dragged into the U-cA area separately, then merged together using the right-click menu (bottom). 

<img width="797" alt="screen shot 2015-08-03 at 4 43 57 pm" src="https://cloud.githubusercontent.com/assets/1714621/9050110/e60e1efa-39fe-11e5-91ea-bc12bc6437c8.png">

**Comment by nathandunn** [comment]
Merge transcript is using generic feature code to process JSON, which I've already shown to be really slow.    Fix is pretty straight-forward.

**Comment by nathandunn** [comment]
It was doing a lot of "transcript" processes for EVERY exon it merged.

**Comment by nathandunn** [comment]
doing jmeter -t jmeter-dev-blast-test-4.jmx  . . I get almost identical results from #137  .. which is good.

**Comment by monicacecilia** [comment]
much faster. :dancer:
