### ISSUE TITLE
Support different types of sequence stores

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#517]
Currently we only support the hashed sequence stores, the default prepare-refseqs argument. We should add support for

- Using prepare-refseqs.pl with the --nohash option
- Using prepare-refseqs.pl with the --compress option
- Supporting possible future formats where just plain fasta files are used (jbrowse pull requests for 2bit and fasta index are avaiable)

**Comment by nathandunn** [comment]
:+1:

**Comment by cmdcolin** [comment]
This branch actually demonstrated using a indexed fasta file in place of the sequnece chunks

https://github.com/GMOD/Apollo/tree/seq_chunk_remove

Just for reference (not ready for merge)

**Comment by cmdcolin** [comment]
I was trying to load a dataset with a lot of different refseqs (100000+...one of those really bad assemblies) and I got the error

[error:problem saving organism: org.apache.shiro.session.InvalidSessionException: java.lang.IllegalStateException: getAttribute: Session already invalidated]


Just something to be aware of

**Comment by cmdcolin** [comment]
I added ability to use --compress via 081331a79eec18ba6

I will just close this and we can pull in indexed fasta if jbrowse enables it on their end

Using nohash is probably really rare and or unnecessary
