### ISSUE TITLE
(3w) enable genome folding

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#525]
- [x] Build "bookmark" tab out with drag and drop for re-arrangement
  - [x] wrap JSONArray / JSONObject of view objects
  - [x] persist Bookmarks to users
  - [x] enable "duplicate" function of bookmarks
  - [x] **enable "view" of bookmark**
    - [x] **should not return multiple refseqs** . . should return one combined refseq
    - [x] pass URL to JBrowse: organism, sequence, feature(s), etc in JBrowse mapping (triggers projection lookup / application)
    - [x] merge ProjectDescription and BookmarkInfo
    - [x] **JBrowseController / trackList.json create multisequence projection based on "Sequence" passed in / used: (proj::sequence1:[feature1,feature2],sequence2) . . . ** (or in organism preference?)
       - [X] process refSeq.json
       - [x] **process trackList.json**     (merge between different sequences)
       - [x] **process lf-X.json**  (when an lf-X is called, hopefully it should go to the right place and likewise project)
           - [x] cache trackList.json when referring to chunks and process as:  projected-sequence->chunk->->proper sequence 
       - [x] create a "projection" pattern where each object calls its own "projection service" that knows how to do a projection with a particular projector    
    - [x] create projection based on "Sequence" 
    - [x] JBrowse Controller . . . get projection based on "sequences"
  - [x] allow variable "padding" for exon, left, right, etc.
- [x] preferences should reference a "projection" instead of a "sequence / organism"
- [x] **replace current projection the MultipleProjection system** (should work in the current OGS case)
  - [x] should call "getProjection" . . if null then "createProjection"
  - [x] MainApp calls the genome browser URL,  should support &project-ref-track=<reftrack name>&project=fold=<exon|transcript|none>&project-padding=<0-N>&project-seq=[name1,name2]&project-features=[X:name1,Y:name2,Z:name3] . .  
     - ref-track and fold are required and the rest are optional.  
     - hashing may also be optional
- [x] persist sequence order (into sequences directly)
  - [x] cut (with chunks) according to coordinates in projector
  - [x] initial implementation: need fix these calls to the reverseProjection: ```jbrowse/data/seq/f0e/1ab/15/Group1.14-10.txt ```, project continuous chunks . . N X (ChunkSize+1)  
  - [x] **fix lf-X.json** projections are off (esp. last one)

==== 

- [x] **write a projector for exons / hide introns**
- [x] make sure that ```track detail view``` has the original coordinates (and will copy up with the original).  Some options:
  - [x] override the menu option
  - [x] integrate with track service
  - [x] configure server to retrieve "original" json
    - [x] do a linear "scan" of the trackdata track in trackservice
    - [x] create an index of the data to parse it (tables, store in memory, necessary)? 
   - [x] **use URL http://gmod.org/wiki/JBrowse_Configuration_Guide#Click_Configuration_Options**
     (if fail make look same or better (bootstrap / jquery UI included below) include refseq) . . . via a recursive function
      - [x] **move config back into annot.json and out of DraggableHTMLFeatures.js (experiment with trackList.json first)**

=== 

- [x] trackData is missing necessary intron / exons on rendering
- [x] wire filter JBrowseController:
    - [x]  ~~"/jbrowse/index.html"(controller: "jbrowse", action: "indexRouter", params:params)~~ (nothing to do)
    - [x]  ~~"/jbrowse/data/trackList.json"(controller:"jbrowse", action: "trackList")~~ (nothing to do)
    - [x]  "/jbrowse/data/${path}" / ** (controller: "jbrowse", action: "data")
      - [x] rewrite trackData /jbrowse/data/tracks/<trackName>/<seqName>/trackData.json 
             - [x] maxEnd, minStart
             - [x] for each element of ncList, rewrite start, end
      - [x] handle generic types? 
      - [x] rewrite some JSON data out of lf-<chunk>.json (jbrowse/data/tracks/<track>/<group>/lf-<chunk>.json)
             - [x] for each element of array, rewrite start (1) and stop (2)
- [x] rewrite refseq file (rewrite length and end) (jbrowse/data/seq/refSeqs.json)
- [x] **handle bigwig files (looks similar to coverage):**
    - [x] use the [REST API](http://gmod.org/wiki/JBrowse_Configuration_Guide#JBrowse_REST_Feature_Store_API) , expose BAM files using IGV to expose via a projection:
      - [x] configure track (```"type":       "JBrowse/View/Track/HTMLFeatures",
    "storeClass": "JBrowse/Store/SeqFeature/REST",
    "baseUrl":    "http://my.site.com/rest/api/base",```)
     - [x] create REST API:
          - [x] GET (base)/stats/global
          - [x] GET (base)/features/(refseq_name)?start=234&end=5678
     - [x] make it the proper track type ("Wiggle"?)
     - [x] **project the track!**
- [x] **write a central "ProjectionService" for both storage / retrieval processing of projections . . and wire in

== fin == 

- [x] handle the rest of the projections properly
- [x] convert getSequence() methods (need to upgrade sourceCoordinate methods)
- [x] wire AnnotationEditorService/getFeatures , re-write fmin / fmax
  - [x] **handle editing (reverse-projection)**
     - [x] add exon 
     - [x] flipStrand (return function)
     - [x] makeIntron (project fmin only)
     - [x] mergeExons (return function)
     - [x] mergeTranscipts (probably return fuciont)
     - [x] setAccecptor / Donor 
     - [x] setLongestOrf ? 
     - [x] setReadhthrough StopCodon
     - [x] setBoundaries
     - [x] setExonBoundaries
     - [x] setTranslationStart/End
     - [x] unsetTranslationStart/End
     - [x] splitTranscript
     - [x] splitExon
     - [x] undo / redo
  - [x] handle addition (reverse-projection, getting original)
    - [x] handle view (projection)
  - [x] handle just the view (getFeatures)
- [x] create engine for discontinuous project
   - [x] create factory for creating discontinuous projection between two tracks
   - [x] test forward projection
   - [x] test reverse projection
   - [x] create track projection 
   - [x] project coordinates (~~out of phase~~), (~~in-phase~~), exonA-B, left edge, right edge, overlap left, overlap right
   - [x] handle overlap reference track properly
   - [x] handle out of interval properly
   - [x] handle BETWEEN interval properly
- [x] create projections when loading tracks
  - [x] create Projections based on OGS track . .. if any track from JBrowseController is called "OGS" then create a singleton with the projection
   - [x] project trackData (almost done)
  - [x] refactor into a separate removable method
- [x] error in projection code to the right of 5' when overlap (e.g., all of Group 1.10, little of 1.1)
   - [x] **create a unit test to load Group1.10 and verify that there are no overlapping coordinates**
   - [x] **fix features created with an error** (e.g., 10.19 [only 138K]) . . .minMap.size()!=maxMap.size() . . has some overlaps . . which should not happen

We need to allow genome folding, especially in the case of transcripts with large introns (i.e. human).  
This could be done on either the backend (via dynamic rewrite) or on the front-end (client re-write).  
Some level of updated JBrowse support will be necessary, regardless as a discontinuous view is not supported AFAIK.

**Comment by nathandunn** [comment]
Met with @enuggetry  @selewis  and Ian.  Step one is to sort of reproduce this on the back-end and possibly hide the ref-seq data.

**Comment by nathandunn** [comment]
Takes about 733 ms to process honeybee . . . however, this is 1.6K tracks.   But we should only do this once.

**Comment by nathandunn** [comment]
We want it to pick out the appropriate projection locations (since it makes byte-range projections and comparisons) since it is making the calls with projected coordinates.  

Question: How / does the client use the BAI file to generate Byte-range alls and interpret BAM files?  It looks like its a port of the SAMTools C-code to the client, i.e., it reads in the bai file, and calls the appropriate BAM file range-locations.

**Comment by nathandunn** [comment]
Was thinking about .BAM tracks and realized we don't want to render BAM tracks, we want to render references based on BAM tracks data such that we get useful data zoomed in or out.   Most of the data delivered by the BAM track is unused (too much detail) or can be collapsed to increase visibility of other tracks.  I think using .BAM as a source file is great, but we should be able to pull the reads out fairly readily without re-parsing on the client. . . . what would be better would be the way that HTMLFeatures is written to show histograms (or something similarly useful) when zoomed out and then zoom in to show things like track density.

**Comment by nathandunn** [comment]
Just as an FYI to store:

- https://www.biostars.org/p/65558/ (crossmap, esp.) 
- https://www.biostars.org/p/10395/  (UCSC liftover)

**Comment by nathandunn** [comment]
The original JBrowse2 source attempts to use OpenLayers for projection:

https://dojotoolkit.org/reference-guide/1.10/dojox/geo/openlayers.html

as here:  https://github.com/dojo/dojox/blob/master/geo/openlayers/Map.js#L566

though its unclear if that is used.  

There is a projection package that looks almost identical to the server side code already written:

https://github.com/GMOD/jbrowse/tree/2.x/src/JBrowse/Projection

this goes here:  

https://github.com/GMOD/jbrowse/blob/2.x/src/JBrowse/View/RegionBrowser.js#L523

I'm seeing that we have a scale and an offset, but not much else (i.e., the projections are not necessarily discontinuous.   These could be stored / created this way, but it is not.

**Comment by nathandunn** [comment]
Looking at the newer source, while it would be easy to load that package, actually integrating it would be really hard.

**Comment by nathandunn** [comment]
![image](https://cloud.githubusercontent.com/assets/751274/9706075/7c611d9a-548e-11e5-9b4d-b6a1fca2b213.png)

Added architecture / design (also in docs)

**Comment by nathandunn** [comment]
ITs slightly different, but it works:

```
     {
         "key" : "TEST Sampled Forager RNA-Seq XY Plot",
         "storeClass" : "JBrowse/Store/SeqFeature/REST",
         "type": "JBrowse/View/Track/Wiggle/XYPlot",
         "label" : "Test Forager RNA-Seq XY Plot",
         "baseUrl":    "http://localhost:8080/apollo/bigwig",
         "query": {
             "urlTemplate" : "bigwig/forager.bw"
         },
         "max_score" : 100,
         "min_score" : 0
      },
```

The test is the middle one:

![screen shot 2015-09-08 at 2 58 50 pm](https://cloud.githubusercontent.com/assets/751274/9748536/2543bcd6-563a-11e5-9468-f11df56a891d.png)

Need to work on projection now.

**Comment by cmdcolin** [comment]
That looks good. Some of the differences are probably due to the fact that bigwigs have  "summary" blocks and are not always rendering at the base level. there are lots of weird issues with this like here https://github.com/GMOD/jbrowse/pull/504

Otherwise that looks good

**Comment by nathandunn** [comment]
Right now I'm ignoring the summary tracks, but otherwise it is pretty efficiently parsing the same data (I need to speed up some of the other parts, though).

**Comment by nathandunn** [comment]
Talked with @monicacecilia   . . . a priority is to create a projection (and annotate) across multiple scaffolds.   That, in and of itself, isn't too bad . . we just add scaffold / sequence (which includes organism) as a has to lookup and a value on the "Coordinate" object.  

The trickier part is 1) displaying the proper "details view" in jbrowse and 2) when dragging up an annotation I need to re-retrieve the coordinates.  

For 1, I could get this from an alternate array (or use an alternate for changing) . . . I listed options at the top.   If the track items is included the track and sequence, that could be used for a lookup, but I think that is a bad solution.    Most likely, the "old" array will be stored and used to re-replace during annotation (and re-converted when retrieved).  

Alternatively, there are a lot of different projections that could be stored in the client, as well.

**Comment by nathandunn** [comment]
@cmdcolin   I am over-riding the track view detail stuff.  I can return the correct content / over-ride pretty easily.  What I'm struggling with is the popup.  My guess of what is going on is that then function is being executed, but somehow either the wrong container is being updated or . . something else:

Here is my over-ride:

https://github.com/GMOD/Apollo/blob/feature/genometry1/client/apollo/js/View/Track/DraggableHTMLFeatures.js#L50

Here is the default (I believe) I think is the functionality in _FeatureDetailMixin.   

I just get a title with an okay button:

![screen shot 2015-09-18 at 2 34 35 pm](https://cloud.githubusercontent.com/assets/751274/9971669/7169fc3a-5e12-11e5-8232-be2f833d229b.png)

If you have any ideas that would be great.   Otherwise will do with jQuery / UI instead.

**Comment by cmdcolin** [comment]
i dont think you should need to copy code into html features like that. you could just "inject" code into tracklist.json config files perhaps like we have done done for other config issues.



There is this which is targetted in modifying specific parts of the default view details popup

http://gmod.org/wiki/JBrowse_Configuration_Guide#Customizing_parts_of_the_.27View_details.27_Pop-ups_with_callbacks



Or there's this that just modifies the whole popups via the config (i think you copied some code in draggablehtmlfeatures to access this type of function, but again, i think you can just modify that config dynamically or something)


http://gmod.org/wiki/JBrowse_Configuration_Guide#Click_Configuration_Options

**Comment by nathandunn** [comment]
Ah . . . I could do this in trackList.json (dynamically or otherwise).  

Can you see an advantage to rewriting it in trackList.json or in the javaScript directly?  I would probably write it in trackList.json if possible (assuming this works) just to follow our pattern. 

```
menuTemplate: [
                    { label: 'Peruse the DNA ',
                        title: '{type} {name}',
                        action: 'contentDialog',
                        iconClass: 'dijitIconTask',
                        //content: dojo.hitch( this, 'defaultFeatureDetail' )
                        url: context_path +"/sequence/loadSequence"
                    },
```

**Comment by nathandunn** [comment]
So how do you pass the track and sequence name in with the rest of the argument?   Do I need the function callback to get this or are there defined variables? I'm only seeing variables for the feature name and type.  

Nathan

**Comment by cmdcolin** [comment]
You can get the sequence name from the feature i think


    feature.get('seq_id')


track name, i dunno.

**Comment by nathandunn** [comment]
Ahh . . the function callback example shows what to do.  This should work perfectly . . I just need to get the escaping right . . this might also have to go directly into the trackList instead.:

```
url: "function(track,feature) { return '+context_path +'/track/featureDetail?track='+track.name + '?refseq='+track.refSeq.name +'&name='+feature.get('name')+'; }"
```

**Comment by nathandunn** [comment]
Track view detail works roughly the same

**Comment by cmdcolin** [comment]
what is this bookmark panel function? just curious

**Comment by nathandunn** [comment]
Bookmarks are a way to organize projections.  

http://icebox.lbl.gov/Apollo2-1/annotator/index <http://icebox.lbl.gov/Apollo2-1/annotator/index>

Note the bookmark tab, and the “bookmark” buttons on annotations / ref sequence.  They don’t actually generate folding yet, but that is next on the agenda (wiring it in). 

Nathan

**Comment by cmdcolin** [comment]
A generic bookmark feature would be pretty nice as well. Dunno if that is related or not

**Comment by nathandunn** [comment]
We will have a generic one, as well.  . . . but its a “projected” one.  No reason why not having a projected one might not make sense. 

Nathan

**Comment by cmdcolin** [comment]
This is sort of random (and this may have even been mentioned before) but I like the way ensembl does this

Example

![ensembl](http://useast.ensembl.org/img-tmp/2015_10_08/session_3953401/ImJQnZCH.png)

**Comment by nathandunn** [comment]
Need to properly convert this when setting sequence in MainPanel::genomic:


```
{ "track": "{"projection":"None", "padding":50, "referenceTrack":"Official Gene Set v3.2", "sequences":[{"name":"Group2.19"},{"name":"Group5.14"}]}:-1..-1", "operation": "get_user_permission” }
```

to 

```
{ "track": {"projection":"None", "padding":50, "referenceTrack":"Official Gene Set v3.2", "sequences":[{"name":"Group2.19"},{"name":"Group5.14"}]}, "operation": "get_user_permission” }
```

when passing in as a URL.

**Comment by nathandunn** [comment]
split up into multiple other issues
