### ISSUE TITLE
Enable MSA view using JalView, PANTHER

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#526]

**Comment by selewis** [comment]
JalView
See http://www.jalview.org/

**Comment by monicacecilia** [comment]
See also section in Apollo grant on _MSA Views and Ortholog Identification_ - part of _Year 3 - AIM 1: Additional Curation Tools._

And this comment from @selewis on 2016-01-06

![screen shot 2016-02-18 at 5 13 13 pm](https://cloud.githubusercontent.com/assets/1714621/13163553/f82a6958-d662-11e5-9246-5cb053a6ba88.png)

**Comment by nathandunn** [comment]
Having the D3 / SVG tracks in there will open this up to using the BioJS widgets.   They also did a really nice job on the API for it. 

Nathan

**Comment by monicacecilia** [comment]
:+1:
