### ISSUE TITLE
User's last location isn't used on page refresh

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#527]
If the user is navigating somewhere, and refreshes the page, it stays on same scaffold but then zooms out to the fullscreen view. tested on local and icebox 2.0.0-RC4

**Comment by nathandunn** [comment]
This is also true when clicking on a transcript.

**Comment by nathandunn** [comment]
Retagged to 2.0.0-RC4

**Comment by nathandunn** [comment]
Should be working now. 

To test:
1 - go to a gene . .  refresh the page and see that you are at the same location
2 - got a a gene on a difference organism and refresh confirming your at the same place . . . go back to the original organism and verify that you are at the location you were on the original organism in (1)

**Comment by monicacecilia** [comment]
works as expected - it remembers.
