### ISSUE TITLE
Set translation start produces uncaught out of bounds exception in an intron

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#532]
I don't know if this is a biologically relevant operation but if you perform "Set translation start" in an intron, it generates an out of bounds exception

    Message: String index out of range: -1
        Line | Method
    ->> 1904 | substring                in java.lang.String
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    |    632 | $tt__setTranslationStart in org.bbop.apollo.FeatureService
    |    503 | $tt__setTranslationStart in     ''
    |    488 | $tt__setTranslationStart in     ''
    |    706 | _do_setTranslationStart  in org.bbop.apollo.RequestHandlingService
    |    782 | doCall                   in org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure3_closure4_closure5
    |    781 | doCall . . . . . . . . . in org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure3_closure4
    |    777 | doCall                   in org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure3
    |    289 | call . . . . . . . . . . in groovyx.gpars.group.PGroup$3
    |    313 | run                      in groovyx.gpars.group.PGroup$4
    |   1145 | runWorker . . . . . . .  in java.util.concurrent.ThreadPoolExecutor
    |    615 | run                      in java.util.concurrent.ThreadPoolExecutor$Worker
    ^    744 | run . . . . . . . . . .  in java.lang.Thread

**Comment by selewis** [comment]
Definitely it is not allowed to set translation start within an intron
(obey the biology). Should have been caught and the menu item grayed out.

**Comment by nathandunn** [comment]
assigned accordingly  . . should be greyed out, I agree

**Comment by cmdcolin** [comment]
Ya, technically the behavior now is "do nothing" since the crash causes nothing to happen, but a greyed out button would be nice.

**Comment by monicacecilia** [comment]
@nathandunn says this is done.

**Comment by monicacecilia** [comment]
@nathandunn now says he's not sure. will check.
