### ISSUE TITLE
chunkSizeLimit error: too much BAM data

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#533]
Reported on 2015-07-25 via email.
I'm getting this same chunkSizeLimit error that Chris (@childers) fixed in an instance at NAL and despite increasing the limit ( to 500,000,000) - the error persists:

* We followed: http://gmod.827538.n3.nabble.com/Gmod-ajax-BAM-file-too-much-data-td4036008.html
* We re-started the instance, also cleaned the cache on the browsers, but the error persists. 
* I know it is marginally being discussed here: https://github.com/GMOD/jbrowse/issues/540 but the patch (according to Colin) may not be the right approach.

===========
@cmdcolin responded: 
![screen shot 2015-08-11 at 1 47 07 pm](https://cloud.githubusercontent.com/assets/1714621/9210172/92f96670-402f-11e5-8a95-ad644a055ef8.png)

===========
I added: 
Thanks @cmdcolin, this was on a different instance we loaded on a portable server; it is not open to the public. -- Apologies, it seems I was not completely clear on that :) I just saw the same error in a different server and was trying to see if someone had additional advise, since nothing seemed to work on our end. 

@nathandunn, the "too many BAM features" error is also visible on icebox.  - it was not there last time I checked (~ 2 weeks ago). 

And @cmdcolin, it is also now visible on the two test instances on genomes at Mizzou, which were working just fine until very recently - I used them last ~3 weeks ago.  (see below). 
### 1. This is the error on icebox:
<img width="1418" alt="screen shot 2015-07-25 at 3 17 01 pm" src="https://cloud.githubusercontent.com/assets/1714621/9210265/1b9ca154-4030-11e5-84a7-3aa81bc604e1.png">

### 2. This is the error on our portable server (after changing chunkSizeLimit):
On our instance we changed chunkSizeLimit up to 300,000,000 to allow visualization, but now we are getting an error when trying to pull this group (2.18). The new error reads (see also console on the right of the image below): 

<code>
:8080/apollo/jbrowse/src/JBrowse/Store/LRUCache.js:296 XHRBlob chunk cache cannot fit http://192.168.0.100:8080/apollo/jbrowse/data/bam/forager_Amel4.5_accepted_hits.bam (bytes 2083291136..2118680575) (35,389,440 > 10,000,000)
:8080/apollo/jbrowse/src/JBrowse/Store/LRUCache.js:296 XHRBlob chunk cache cannot fit http://192.168.0.100:8080/apollo/jbrowse/data/bam/forager_Amel4.5_accepted_hits.bam (bytes 2056912896..2081619967) (24,707,072 > 10,000,000)
LRUCache.js:296 XHRBlob chunk cache cannot fit http://192.168.0.100:8080/apollo/jbrowse/data/bam/forager_Amel4.5_accepted_hits.bam (bytes 2123694080..2291236863) (167,542,784 > 10,000,000)
</code>

![image 1](https://cloud.githubusercontent.com/assets/1714621/9210302/4d31c51e-4030-11e5-8589-80c0609f7893.png)

### 3. And this is the error on genomes.missouri:

<img width="1418" alt="screen shot 2015-07-25 at 3 24 10 pm" src="https://cloud.githubusercontent.com/assets/1714621/9210293/45287930-4030-11e5-9292-fb69b3e651f1.png">

=======

@nathandunn added: 
I get this with Web Apollo 1.0.4 as well, so I’m wondering if it is Apache or track specific:
![screen shot 2015-07-25 at 3 45 56 pm](https://cloud.githubusercontent.com/assets/1714621/9210444/38c8a538-4031-11e5-93f9-8aefe7a59339.png)

I am getting this same error locally when fixing the chunk limit.  However, this is very specific for this (and a few other) groups on Honeybee, but by no means ubiquitous.  

I *think* its a matter of hitting JBrowse limits, where were put into place so that the browser wouldn’t crash / hang.  

http://icebox.lbl.gov:8080/WebApolloDemo/jbrowse/?loc=Group2.18%3A547034..562123&tracks=DNA%2CAnnotations%2COfficial%20Gene%20Set%20v3.2%2CForager%20RNA-Seq%20reads&highlight=

If this is working on the NAL servers for the same data, I would be curious as to what the differences are.  

It looks like Colin was working on a fix for something like this, but I may have been reading it wrong:
https://github.com/GMOD/jbrowse/issues/540

===================

I responded: 
* Thanks for looking into it. 
* unfortunately, the gene I needed to use for the workshop lives in this scaffold...
* About the instances for i5K (NAL), these are not on the same data. Different organisms, and I did not get any other errors while using those instances.
* At the end of https://github.com/GMOD/jbrowse/issues/540 @cmdcolin remarks that his patch may not be the best approach. -- still a work in progress, I imagine. 

* And this is also happening. - a hybrid. Different group this time. 

error: 
<code>
GET http://icebox.lbl.gov/Apollo2/jbrowse/data/bam/forager_Amel4.5_accepted_hits.bam 404 (Not Found)i._fetch @ dojo.js:978(anonymous function) @ dojo.js:978f.hitch @ dojo.js:121
dojo.js:1180 D…r.aT {message: "404 (Not Found) when attempting to fetch http://ic…browse/data/bam/forager_Amel4.5_accepted_hits.bam"} undefined
</code>

<img width="1408" alt="screen shot 2015-07-25 at 11 38 04 pm" src="https://cloud.githubusercontent.com/assets/1714621/9210539/bf6e2c02-4031-11e5-822f-8fa1ff7383a0.png">

==============
@childers added:
![screen shot 2015-08-11 at 2 03 58 pm](https://cloud.githubusercontent.com/assets/1714621/9210565/dda7750c-4031-11e5-9d33-8d8701ad715b.png)

==============
@cmdcolin added:
![screen shot 2015-08-11 at 2 04 44 pm](https://cloud.githubusercontent.com/assets/1714621/9210582/f0215b4e-4031-11e5-8741-0c21d4239708.png)

=============
Finally, @nathandunn said: 
![screen shot 2015-08-11 at 2 05 25 pm](https://cloud.githubusercontent.com/assets/1714621/9210598/0b982114-4032-11e5-8085-9de0e8578897.png)

**Comment by nathandunn** [comment]
@monicacecilia   This is a JBrowse issue that shows up on some tracks but not others.  I moved it to another release date, since we need wait for significant imporvements to JBrowse.

**Comment by monicacecilia** [comment]
@enuggetry ... fyi.

**Comment by cmdcolin** [comment]
I think the jbrowse side of things (and/or) the cram support will try and target fixes. re-open if needed (sorry triaging here)

all the issues here are noted though so thanks moni for documenting
