### ISSUE TITLE
GWT "links" can be bootstrap popups 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#538]
This can be a simple bootstrap popup instead of yet another panel.

<img width="1033" alt="screen shot 2015-08-13 at 4 48 46 am" src="https://cloud.githubusercontent.com/assets/751274/9249086/9db32068-4176-11e5-9cc7-89ba804537c8.png">

**Comment by cmdcolin** [comment]
I thought we didn't like popups!

**Comment by nathandunn** [comment]
I'm open to ideas.  Its just not that polished.

**Comment by nathandunn** [comment]
Will fix this error in #603  . .
