### ISSUE TITLE
(4h) block user from trying to delete organism with annotation from the interface

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#539]
I actually noted this problem yesterday and was hoping it was a fluke, but I noticed that deleting an organism has problems via the "Delete organism" button on OrganismPanel

Log:

    | Error 2015-08-13 13:10:18,729 [http-bio-8080-exec-4] ERROR errors.GrailsExceptionResolver  - ObjectDeletedException occurred when processing request: [POST] /apollo/organism/deleteOrganism - parameters:
    data: {"id":"72274", "commonName":"Amel4", "directory":"/opt/apollo/honeybee/data", "genus":"Apis", "species":"mellifera", "sequences":543, "annotationCount":543}
    deleted object would be re-saved by cascade (remove deleted object from associations): [org.bbop.apollo.FeatureLocation#82921]. Stacktrace follows:
    Message: deleted object would be re-saved by cascade (remove deleted object from associations): [org.bbop.apollo.FeatureLocation#82921]
        Line | Method
    ->>  101 | doCall                in org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    |     35 | isAdmin               in org.bbop.apollo.PermissionService
    |    192 | $tt__findAllOrganisms in org.bbop.apollo.OrganismController
    |     49 | $tt__deleteOrganism   in     ''
    |    198 | doFilter . . . . . .  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
    |     63 | doFilter              in grails.plugin.cache.web.filter.AbstractFilter
    |    449 | executeChain . . . .  in org.apache.shiro.web.servlet.AbstractShiroFilter
    |    365 | call                  in org.apache.shiro.web.servlet.AbstractShiroFilter$1
    |     90 | doCall . . . . . . .  in org.apache.shiro.subject.support.SubjectCallable
    |     83 | call                  in     ''
    |    383 | execute . . . . . . . in org.apache.shiro.subject.support.DelegatingSubject
    |    362 | doFilterInternal      in org.apache.shiro.web.servlet.AbstractShiroFilter
    |    125 | doFilter . . . . . .  in org.apache.shiro.web.servlet.OncePerRequestFilter
    |   1145 | runWorker             in java.util.concurrent.ThreadPoolExecutor
    |    615 | run . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
    ^    744 | run                   in java.lang.Thread

This only appears to happen if there are annotations added for the organism.

I also tested this on icebox and it appears to cause problems there too. It just says "Processing ..." and this overlay does not disappear after several minutes. I don't know the logs on icebox though

**Comment by cmdcolin** [comment]
I think changing the join type on FeatureLocation in this commit is probably causing it https://github.com/GMOD/Apollo/commit/f60d190567e20aea36bc2ae996540eb83c36660e

This goes back to the eager vs lazy issue. I think fetchtype join is similar to eager.

**Comment by nathandunn** [comment]
Should not be a common operation (initially).   However, what *should* happen is that it asks you if you want to delete  N annotations and then we simply add "delete features" to the delete organisms code.   I kind of left it this way on purpose as it won't be that common of an operations.  I'm not sure what other type of metadata needs to be deleted from organism (maybe permissions?).

**Comment by cmdcolin** [comment]
Should we just remove the delete organism button then?

**Comment by nathandunn** [comment]
Let's leave it for now.  Its a "bug".   Most of the time users will delete if there are no annotations.

**Comment by nathandunn** [comment]
Conversely we could create a script .. Delete features for organism which might work in the interim.

**Comment by cmdcolin** [comment]
this could possibly fix it but it is slow

    diff --git a/grails-app/controllers/org/bbop/apollo/OrganismController.groovy b/grails-app/controllers/org/bbop/apollo/OrganismController.groovy
    index 2e52e61..4fdc582 100644
    --- a/grails-app/controllers/org/bbop/apollo/OrganismController.groovy
    +++ b/grails-app/controllers/org/bbop/apollo/OrganismController.groovy
    @@ -38,6 +38,12 @@ class OrganismController {
                 Organism organism = Organism.findById(organismJson.id as Long)
                 if (organism) {
                     UserOrganismPreference.deleteAll(UserOrganismPreference.findAllByOrganism(organism))
    +                Sequence.findAllByOrganism(organism).each { it ->
    +                    log.debug "${it.name}"
    +                    Feature.executeQuery("select distinct f from Feature f join f.featureLocations fl where fl.sequence = :sequence", [sequence: it]).each { it2 ->
    +                        it2.featureLocations.clear()
    +                    }
    +                }
                     organism.delete()
                 }
             }

This works on pythium ultimum which has just 1 scaffold pretty effectively but it is slow on organisms with tons of scaffolds

**Comment by cmdcolin** [comment]
I think I will add this and we can close the bug. It is kind of slow but as long as it it eventually works then we can optimize it later

**Comment by nathandunn** [comment]
Related to a few other issues.

**Comment by cmdcolin** [comment]
I think we might want to reconsider that act of "deletion". Instead of just wiping it out, gone for good, which can introduce data inconsistencies, we can just flag it as deleted and then not show it

We could have a "big hammer" to actually delete things, but I think flagging things at deleted can solve more headaches in the short term, and it actually provides a better record


This can go for deleted organisms, deleted users, deleted annotations etc. Just flag as deleted instead of actually deleting.

**Comment by nathandunn** [comment]
I think having flags that this makes sense it terms of OGS and 2.2.  The concept of a deleted status flag and how it gets interpreted throughout the interface is pretty involved. 

We are already going to have a web service to handle annotation deletion of organisms.   In the interim (WRT to this update) . . I think that the most appropriate thing to do (before going nuclear) is:

1 - warn that there are N annotations associated with this organism that need to be deleted before the organism can be deleted. 
2 - suggest that they use the web service to delete all of them . . 

Nathan

**Comment by cmdcolin** [comment]
In the case of deleting an organism, ok maybe they do want to go away completely. No record of it ever existing.


In the case of a user deleting an annotation, I actually think it is more subtle. I think that having a record of that annotation existing is important.

The case of deleting a user, we need to have the fact that this user existed to remain in the database because they can have associated annotations.

**Comment by cmdcolin** [comment]
Ref #11

**Comment by nathandunn** [comment]
They should be logged in FeatureEvent history.  If AuditLogging is on, it will be logged there, as well. 

Maybe a bigger question is "where does one want to see this information”?  Admin will have “changes” pages so we can show there. 

Nathan

**Comment by cmdcolin** [comment]
Would definitely like to recreate the "changes" page.


Also, we have always sort of had trouble naming these things, but it could also be called "Annotation overview" or something and then just happen to have a feature for sorting by date providing recent changes.

**Comment by nathandunn** [comment]
We are doing that here:

https://github.com/GMOD/Apollo/issues/488 <https://github.com/GMOD/Apollo/issues/488>

Nathan

**Comment by nathandunn** [comment]
- [x] add a service for deleting the features 
- [ ] (1d) create a web-service for "deleting features from an organism" 
- [ ] (1h) add a "block" for deletion of an organism (basically you can't do it if there are annotated features on it)

**Comment by nathandunn** [comment]
To test:
- find an organism with annotations on the organism panel and "delete".   You should see the following:

![screen shot 2015-10-20 at 9 30 40 am](https://cloud.githubusercontent.com/assets/751274/10614106/5062f5a0-770d-11e5-8344-188f2ff6bbaf.png)

There is a web service to allow them to delete all the annotations (or they can do it manually or they can create another organism).

**Comment by monicacecilia** [comment]
Okay, the warning message does show up. 
However, let's change the wording so it doesn't sound like someone is *inappropriately yelling at someone else*. :) 


#### Cannot delete organism 'ZZZ'
##### You must first remove ## annotations before deleting organism 'ZZZ'. Please see our documentation on 'Web Services API' from the 'Help' menu for mode details on how to perform this operation in bulk.

**Comment by nathandunn** [comment]
![screen shot 2015-10-27 at 9 30 33 am](https://cloud.githubusercontent.com/assets/751274/10764891/747edc80-7c8d-11e5-9893-c42bb7fb7add.png)

**Comment by nathandunn** [comment]
The link in the dialog goes to the correct place.

**Comment by cmdcolin** [comment]
We could reasonably just call that web service API from the webapp if the user is sure. Not sure if it is necessary to redirect them to use command line

**Comment by nathandunn** [comment]
Yeah .. True.  I'd like to get some user feedback first.   Typically it seems as though there is a larger custom workflow, but maybe not. 

Nathan

**Comment by cmdcolin** [comment]
I mean, in this case we are giving them a link to the raw REST API docs, but we do have a command line script for performing the action too (delete_annotations_from_organism.groovy ).

**Comment by nathandunn** [comment]
I like the idea of providing the script. 

Nathan

**Comment by monicacecilia** [comment]
works as expected. 
:dancer:
