### ISSUE TITLE
Organism panel not showing all organisms

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#540]
I was testing the add organism functions, and everything looked fine through the first ten.  The eleventh organism did not show in the organisms panel, though it is visible in the instance drop-down box at the top.

<img width="576" alt="wa2-organism-panel" src="https://cloud.githubusercontent.com/assets/421248/9259598/2a386d6e-41d0-11e5-9bcc-4db0bb5ffdf1.png">

**Comment by nathandunn** [comment]
Doh .. Easy fix .. I'll take care of it.

**Comment by monicacecilia** [comment]
great. we like the "easy" ones. :) 
@nathandunn - please let us know when this has been pushed and is available for @childers to check again.

**Comment by nathandunn** [comment]
It is pushed and ready for @childers  to check (it is on both 2.0.0 and master).

**Comment by nathandunn** [comment]
Working on icebox . . .

**Comment by childers** [comment]
This looks nice, thanks!
