### ISSUE TITLE
History of edits and History of metadata changes should be tracked identically

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#541]
Current behaviour: 
- create new annotation
- change name (on Information Editor)
- edit the gene model
- "Undo" the change
- The result is that the change is reverted, BUT the gene name change also disappears. 

Expected behaviour: 
- ... the result should be a change back to the structure before the edit, but no changes to the metadata in the Information Editor should occur. 

@nathandunn wrote: We don't (yet) track "setName", "setSymbol", etc. which is unchanged from WA1. In WA1 they were keeping the name, however, but history functions were inconsistent, which is now fixed. [...] My suggestion would be to track history for setName, setSymbol as we do for genomic features (so it would be obvious as to why your name is re-changing). Tracking meta-info (name, symbol, description) and genomic info separately would have to be well-defined or it will be a mess.

**Comment by nathandunn** [comment]
should also make a note that as part of #967 we could query for updated features using the history, but non-genomic edits are not recorded.

**Comment by nathandunn** [comment]
From @erasche  #1060:

> The feature history currently only includes structural changes. We noted over the course of our course that it would be incredibly useful if that feature history also included things like users adding / removing / changing annotations on the feature.

> That way we can keep an accurate log of who added a feature name, and allow undoing various changes.

> We had one student who ran a tool which renamed all of their genes. Had this been a logged change in the feature history, the student could have gone through each feature and reverted the names appropriately.

**Comment by nathandunn** [comment]
Just wanted to capture this:

> I think a better model might be simply capturing those changes internally in the same way we do now and in the UI, indicating the type of change (and possibly the metadata change).

**Comment by nathandunn** [comment]
After talking with @monicacecilia and @selewis , we decided that we should track metadata history (i.e., name, symbol, etc.) in the same manner that we track structural edit history.
