### ISSUE TITLE
Admins for specific organisms are able to create organisms and assign permissions for organisms they don't own

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#542]
The behavior that was previously described for users that are *admins for a specific organism* here are not being followed now: https://github.com/GMOD/Apollo/issues/329

In that issue, I said that "Admin users for specific organisms will not be able to create new organisms, but they will be allowed to create new users and add permissions for that user on their specific organism."

Neither of these things is now correct in the latest versions

Admin users can now create organisms and assign permissions for organisms that they are not an admin for.

**Comment by nathandunn** [comment]
If a user is an admin in one place, they are an admin EVERYWHERE . . . working on this now.

**Comment by nathandunn** [comment]
probably should not automatically close this

**Comment by cmdcolin** [comment]
I'll check this out

**Comment by cmdcolin** [comment]
The organisms sub-tab on the User panel is empty now, it just says "Please select a user to view organism permissions" but selecting a user does nothing

**Comment by cmdcolin** [comment]
I also changed the "Role" of a user that previously was class "user" to "admin" and re-logged in as this user and I was not able to see the admin type tabs

**Comment by nathandunn** [comment]
@cmdcolin  I "refixed" this as then then admin did not have access to the any organisms . . .

**Comment by nathandunn** [comment]
Just close it if it works .. .if you want to look at it more tomorrow, that is fine as well.

**Comment by nathandunn** [comment]
It does appear to be working on icebox now.

**Comment by cmdcolin** [comment]
I think it's a lot better now at least for the user panel.

**Comment by nathandunn** [comment]
@cmdcolin  Can we close it then or do you want to test it more first?   We can also issue bugs for 2.0.1 . . . just need to have this in a good state sometime tomorrow.

**Comment by cmdcolin** [comment]
@nathandunn I made a change to make it only so that admin user can add and delete organisms. I think it is now valid for both web services and OrganismPanel

**Comment by cmdcolin** [comment]
See 23992bbabf

Previously it was checking if the user was an admin on their current organism preference...now it checks whether the "role" is admin which is more accurate

**Comment by cmdcolin** [comment]
Should be fixed now
