### ISSUE TITLE
create user dialog is confusing

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#544]
The Create button is used to open the add user interface, then is grayed-out.  Could you make it disappear once the dialog is open?  It was confusing to me, as my internal logic was to click the create button to create my new user, and it took a while before I realized that I was supposed to use the Save button to create the account.  I know now, but it is not an intuitive interface for me.

**Comment by cmdcolin** [comment]
What about something more similar to the Organism panel

Less confusing?

Similar but different button names

**Comment by childers** [comment]
Dos it automagically save the user information for updating, or does it always need explicit saving?  I never noticed it on the organism setup panel, so maybe all is needs is a similar type of labaling for the interface options.

Thanks!

**Comment by cmdcolin** [comment]
The initial save user does not automatically upload IIRC, but when you are editing a users info, it will automatically upload (i.e. there is no save button when editing a users info, and similarly, no save button when editing an organisms info). I think adding a save when editing is probably useful.

**Comment by cmdcolin** [comment]
Similar things exist for our information editor and other panels. No save button

**Comment by cmdcolin** [comment]
And there is no technical reason not to add a save button, just a UI thing.

**Comment by childers** [comment]
I like that for the user interface, to help keep from accidentally destroying somebody's password.

**Comment by cmdcolin** [comment]
Ya definitely. Could easily accidentally edit the password field.

**Comment by nathandunn** [comment]
@childers   I'm hoping that the UI for 2.0.1 is a little simpler, but let us know.

**Comment by nathandunn** [comment]
Screenshots are here:  #610

**Comment by nathandunn** [comment]
We can always make changes later if its still not working adequately.
