### ISSUE TITLE
Query all features for an organism is slow

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#545]
I am opening up this thread because unless I am missing something, we are not able to query all features for a given organism in an efficient manner.

Currently our schema is like this

A feature has a feature location
A feature location has a sequence
A sequence has an organism

So to get all features that a particular organism has, we have to loop over all sequences where sequence.organism is our organism, and then get all features for that sequence. This is a classic "N+1" problem in databases

In Chado, the organism_id is attached to a feature, so you can simply query the features with a given organism ID, but our schema does not have this, making it difficult to make a query like this.

**Comment by cmdcolin** [comment]
Technically, in some places in the code, it is actually doing this [simplified for context]


>"select distinct f from FeatureLocation fl join fl.sequence s join fl.feature f where s in (:sequenceList)", [sequenceList: sequenceList])


I am not sure how performant the database is when it has to iterate through a "sequenceList" of 100000 scaffolds for instance

**Comment by cmdcolin** [comment]
Unless this causes implementation or performance complications, I will close this.

Can be re-opened for discussion

**Comment by nathandunn** [comment]
It should only do what you have listed below if there are a finite list of sequences (<10 but typically 1).  If it is doing that when including all sequences then it is clearly a bug and should be fixed to just be a join from sequence to organism .. Which would be very fast relative to what is above.

**Comment by cmdcolin** [comment]
I believe that it is doing that on even large lists of sequences.

See the concept of "exportAllSequences" in IOServiceController.

**Comment by nathandunn** [comment]
I and Deepak had also identified that.  Good to go ahead and fix. 

Nathan

**Comment by cmdcolin** [comment]
Ok, I'll go ahead and re-open then. I'll mark this as enhancement since it hasn't been identified to cause problems

**Comment by nathandunn** [comment]
Closing, as other enhancements fix this.
