### ISSUE TITLE
better document REST API 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#546]
Every controller (and they all register with the system) should have a "describe web services" that provides input and can be parsed up via JSON / AngularJS:

- [x] for each controller provide the proper info in the webservices method:
   - [x] have it do an angularJS rendering . . can look like this: http://loic911.github.io/restapidoc/
   - [x] create a utility class for creating the JSON object (controller, method, arguments, description, etc.)
- [x] properly document all of the webservices in every controller that has them:
  - [x] organism
  - [x] user
  - [x] group 
  - [x] ioservice
  - [x] annotation editor (ugh)
- [x] add webservices header info from the .md file
- [x] auto-close:
   - [x] add collapse-all / expand-all
~~ - [ ] add animation!!~~
- [x] move URL Mapping (just uncomment one line of code)
- [x] double-check webservices.md and html (no sense in having older doc)
- [x] remove webservices.md and html (no sense in having older doc)

If all else fails, move doc into docs/.md  . . .

**Comment by cmdcolin** [comment]
I think this is a good idea. I added web services API to markdown and added some updates along the way, and then I think that having "live" or "automatic" documentation could be a good feature (many of our current docs are actually showing WA1 scenarios, and the APIs do not 100% match)

**Comment by nathandunn** [comment]
I don't think that the rest-api-doc will work for us. 

Probably just need to create a better manual page.

**Comment by cmdcolin** [comment]
Agree. Since documentation is just continuous and we are not switching platforms can we close this as an issue?

**Comment by nathandunn** [comment]
Not yet . . it is really bad and incomplete.  I need to think of a way to either move it into markup or tie it into the code base.

**Comment by cmdcolin** [comment]
I actually migrated the html to markup here https://github.com/GMOD/Apollo/blob/master/docs/Web_services.md

**Comment by cmdcolin** [comment]
We should actually move that markdown back to html to use in the web services link from the help tab

**Comment by nathandunn** [comment]
So . . would I would *like* would be to annotate (Java Web Annotations) the web services directly and have it auto generated.   Since these are on the controllers it shouldn’t be too bad.  

When you create a new Grails projects it creates a home page that lists all of the controllers (and maybe views?).   If we could modify the help page to only pick up the annotated actions (and read the annotations describing the actions) I think we would be good.  . .  . 

Nathan

**Comment by cmdcolin** [comment]
I don't know what java web annotations are. no results from https://www.google.com/search?client=safari&rls=en&q=%22Java+Web+Annotations%22&ie=UTF-8&oe=UTF-8#

**Comment by cmdcolin** [comment]
If it is "java web service annotations", then that looks like it is from a bygone era of SOAP

**Comment by nathandunn** [comment]
Sorry .. I meant Java annotations. 

Not sure if there is a specific tool for it. 

Nathan

**Comment by cmdcolin** [comment]
This type of annotation looked pretty good http://loic911.github.io/restapidoc/

I guess whatever you think is easiest though. We do have the markdown version and I think just improving the markdown and the example code that we have is good

**Comment by nathandunn** [comment]
I had issues getting that to work .. But it is exactly what I am looking for.   Maybe we could modify it.  

Nathan

**Comment by nathandunn** [comment]
@cmdcolin   / @deepakunni3   FYI . . please feel free to update this as you see fit:

. . . relevant files are:
- https://github.com/GMOD/Apollo/blob/master/grails-app/views/webServices/index.gsp
- https://github.com/GMOD/Apollo/blob/master/grails-app/assets/javascripts/WebServicesController.js

And of course the annotations on any of the controllers. 

This should be helpful with the caveat that there is something up with the transitions, but otherwise it works:

http://angular-ui.github.io/bootstrap/

**Comment by cmdcolin** [comment]
How do you update the restapidoc.json file?

**Comment by nathandunn** [comment]
Very good point . . .

I put it in the apollo binary as: create-rest-doc . . .  “./apollo create-rest-doc"

but it is:

grails rest-api-doc

Nathan

**Comment by nathandunn** [comment]
FYI . . not sure what is up with the transitions . . they should be smooth but are not

**Comment by nathandunn** [comment]
To test:

Go to the webservices API page (either on the admin panel or "Help Web Services" and should see this page .  . . 

.. but I am missing some things . . . grr . . one sec.

http://icebox.lbl.gov/Apollo-staging/WebServices/

**Comment by monicacecilia** [comment]
@nathandunn our _Web Service API_ document at https://github.com/GMOD/Apollo/blob/master/docs/Web_services.md still points to an outdated page at http://icebox.lbl.gov/Apollo2/WebServices/ -- the error, is of course also visible in ReadTheDocs http://webapollo.readthedocs.org/en/latest/Web_services.html

Will http://icebox.lbl.gov/Apollo-staging/WebServices/ be the final place where this documentation will live? On 'Staging'?  or are you planning to send that somewhere else?

**Comment by nathandunn** [comment]
Its local to their machine.  We might point to the generic one on the demo machine at some point.   


Nathan

**Comment by nathandunn** [comment]
Those links will be "correct" and they will be the final resting place once deployed.

**Comment by nathandunn** [comment]
So I think it can be closed unless there is something else in there.

**Comment by monicacecilia** [comment]
Nah, nah... our documentation reads: 

![screen shot 2015-10-26 at 5 42 47 pm](https://cloud.githubusercontent.com/assets/1714621/10746514/06cc6506-7c09-11e5-8e14-610f4f54fd21.png)

And when I go to http://icebox.lbl.gov/Apollo2/WebServices/ I get a 404. 

![screen shot 2015-10-26 at 5 43 18 pm](https://cloud.githubusercontent.com/assets/1714621/10746523/18668300-7c09-11e5-86b9-88cb53b5c196.png)

We need to update the one on GitHub for *our* instances.

**Comment by monicacecilia** [comment]
so we can offer an example.... that is.

**Comment by cmdcolin** [comment]
The idea is that once the new app is deployed the documentation will be live

Ideally I don't even want to link it like this

I'd rather have the documentation for the web services contained within readthedocs, I see the documentation being "inside the app" as unnecessary

**Comment by cmdcolin** [comment]
See http://icebox.lbl.gov/Apollo-staging/WebServices for the live example though

**Comment by nathandunn** [comment]
It needs to be self-contained inside the app.   Because we can can't control what version users are using they need to be able to know what their own instance is.   I'd rather have less documentation to maintain that is correct.    
- [ ] move link to <yourhost>/WebServices (or link from your API) . . something like that
- [ ] reference an "Example" in the demo (stating that it might not match your version or be temporarily down)

I think that this fixes both caveats and allows us to maintain a good level of consistency with minimal effort.    I'll take care of it.

**Comment by monicacecilia** [comment]
Yes, I saw the example, and I am aware of what it contains.

I suggesr we either we update the currebt documentation to point to the
live example on Staging, or we do not provide an 'example' to a broken URL
at all.

I can do that (remove/update) the URL once I'm back at a desktop.

**Comment by monicacecilia** [comment]
10-4z

**Comment by cmdcolin** [comment]
>Because we can can't control what version users are using they need to be able to know what their own instance is.

The readthedocs already allows versioned documentation. Each release tag has it's own readthedocs page.

**Comment by nathandunn** [comment]
Right . . . I think the problem is  . . how do we have the readthedocs use the latest stable version only (as opposed to master).  Then everything should be somewhat consistent.  

Anyway, will have a think and mess with it all tomorrow. 

Nathan

**Comment by nathandunn** [comment]
@monicacecilia  I think you can close this . . I fixed the links so that they would be both 2.0.0 and 2.0.1 backwards compatible.
