### ISSUE TITLE
(4h) Deleting a feature that consists of merged transcripts causes error on annotator panel

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#548]
The annotator panel uses findAnnotationsForSequence to update the gene list, but apparently this method crashes after we delete a feature that consists of merged transcripts

    | Error 2015-08-18 11:38:28,103 [http-bio-8080-exec-39] ERROR apollo.AnnotatorController  - No row with the given identifier exists: [org.bbop.apollo.Feature#11701]
    | Error org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [org.bbop.apollo.Feature#11701]
    | Error     at org.hibernate.internal.SessionFactoryImpl$1$1.handleEntityNotFound(SessionFactoryImpl.java:253)
    | Error     at org.hibernate.proxy.AbstractLazyInitializer.checkTargetState(AbstractLazyInitializer.java:262)
    | Error     at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:176)
    | Error     at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:286)
    | Error     at org.codehaus.groovy.grails.orm.hibernate.proxy.GroovyAwareJavassistLazyInitializer.invoke(GroovyAwareJavassistLazyInitializer.java:176)
    | Error     at org.bbop.apollo.Feature_$$_javassist_173.hashCode(Feature_$$_javassist_173.java)
    | Error     at org.bbop.apollo.Feature_$$_javassist_173$hashCode.call(Unknown Source)
    | Error     at org.bbop.apollo.FeatureRelationship.hashCode(FeatureRelationship.groovy:37)
    | Error     at java.util.HashMap.hash(HashMap.java:366)
    | Error     at java.util.HashMap.put(HashMap.java:496)
    | Error     at java.util.HashSet.add(HashSet.java:217)
    | Error     at java.util.AbstractCollection.addAll(AbstractCollection.java:342)
    | Error     at org.hibernate.collection.internal.PersistentSet.endRead(PersistentSet.java:344)
    | Error     at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollection(CollectionLoadContext.java:249)
    | Error     at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:236)
    | Error     at org.hibernate.engine.loading.internal.CollectionLoadContext.endLoadingCollections(CollectionLoadContext.java:209)
    | Error     at org.hibernate.loader.plan.exec.process.internal.CollectionReferenceInitializerImpl.endLoading(CollectionReferenceInitializerImpl.java:168)
    | Error     at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishLoadingCollections(AbstractRowReader.java:255)
    | Error     at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.finishUp(AbstractRowReader.java:218)
    | Error     at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:140)
    | Error     at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:138)
    | Error     at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:102)
    | Error     at org.hibernate.loader.collection.plan.AbstractLoadPlanBasedCollectionInitializer.initialize(AbstractLoadPlanBasedCollectionInitializer.java:100)
    | Error     at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:693)
    | Error     at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:92)
    | Error     at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1897)
    | Error     at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:558)
    | Error     at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:260)
    | Error     at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:554)
    | Error     at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:142)
    | Error     at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:180)
    | Error     at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1372)
    | Error     at org.codehaus.groovy.runtime.dgm$149.invoke(Unknown Source)
    | Error     at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
    | Error     at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
    | Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    | Error     at org.bbop.apollo.FeatureRelationshipService.$tt__getChildrenForFeatureAndTypes(FeatureRelationshipService.groovy:11)
    | Error     at org.bbop.apollo.FeatureRelationshipService$_getChildrenForFeatureAndTypes_closure1.doCall(FeatureRelationshipService.groovy)
    | Error     at sun.reflect.GeneratedMethodAccessor667.invoke(Unknown Source)
    | Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    | Error     at java.lang.reflect.Method.invoke(Method.java:606)
    | Error     at org.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:47)
    | Error     at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1299)
    | Error     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    | Error     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    | Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
    | Error     at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
    | Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
    | Error     at groovy.lang.Closure.call(Closure.java:423)
    | Error     at org.bbop.apollo.FeatureRelationshipService$_getChildrenForFeatureAndTypes_closure1.call(FeatureRelationshipService.groovy)
    | Error     at groovy.lang.Closure.call(Closure.java:439)
    | Error     at org.bbop.apollo.FeatureRelationshipService$_getChildrenForFeatureAndTypes_closure1.call(FeatureRelationshipService.groovy)
    | Error     at org.codehaus.groovy.grails.orm.support.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:90)
    | Error     at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
    | Error     at org.codehaus.groovy.grails.orm.support.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:87)
    | Error     at org.bbop.apollo.FeatureRelationshipService.getChildrenForFeatureAndTypes(FeatureRelationshipService.groovy)
    | Error     at sun.reflect.GeneratedMethodAccessor666.invoke(Unknown Source)
    | Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    | Error     at java.lang.reflect.Method.invoke(Method.java:606)
    | Error     at org.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:47)
    | Error     at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1299)
    | Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
    | Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
    | Error     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    | Error     at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
    | Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    | Error     at org.bbop.apollo.FeatureService.$tt__convertFeatureToJSON(FeatureService.groovy:1549)
    | Error     at org.bbop.apollo.FeatureService$__do_convertFeatureToJSON_closure67.doCall(FeatureService.groovy)
    | Error     at sun.reflect.GeneratedMethodAccessor717.invoke(Unknown Source)
    | Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    | Error     at java.lang.reflect.Method.invoke(Method.java:606)
    | Error     at org.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:47)
    | Error     at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1299)
    | Error     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    | Error     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    | Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
    | Error     at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
    | Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
    | Error     at groovy.lang.Closure.call(Closure.java:423)
    | Error     at org.bbop.apollo.FeatureService$__do_convertFeatureToJSON_closure67.call(FeatureService.groovy)
    | Error     at groovy.lang.Closure.call(Closure.java:439)
    | Error     at org.bbop.apollo.FeatureService$__do_convertFeatureToJSON_closure67.call(FeatureService.groovy)
    | Error     at org.codehaus.groovy.grails.orm.support.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:90)
    | Error     at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
    | Error     at org.codehaus.groovy.grails.orm.support.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:87)
    | Error     at org.bbop.apollo.FeatureService._do_convertFeatureToJSON(FeatureService.groovy)
    | Error     at org.bbop.apollo.FeatureService.this$2$_do_convertFeatureToJSON(FeatureService.groovy)
    | Error     at org.bbop.apollo.FeatureService$this$2$_do_convertFeatureToJSON$0.callCurrent(Unknown Source)
    | Error     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
    | Error     at org.bbop.apollo.FeatureService$this$2$_do_convertFeatureToJSON$0.callCurrent(Unknown Source)
    | Error     at org.bbop.apollo.FeatureService.convertFeatureToJSON(FeatureService.groovy)
    | Error     at org.bbop.apollo.FeatureService$convertFeatureToJSON.callCurrent(Unknown Source)
    | Error     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
    | Error     at org.bbop.apollo.FeatureService$convertFeatureToJSON.callCurrent(Unknown Source)
    | Error     at org.bbop.apollo.FeatureService.$tt__convertFeatureToJSON(FeatureService.groovy:1559)
    | Error     at org.bbop.apollo.FeatureService$__do_convertFeatureToJSON_closure67.doCall(FeatureService.groovy)
    | Error     at sun.reflect.GeneratedMethodAccessor717.invoke(Unknown Source)
    | Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    | Error     at java.lang.reflect.Method.invoke(Method.java:606)
    | Error     at org.springsource.loaded.ri.OriginalClassInvoker.invoke(OriginalClassInvoker.java:47)
    | Error     at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1299)
    | Error     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    | Error     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    | Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1206)
    | Error     at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
    | Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
    | Error     at groovy.lang.Closure.call(Closure.java:423)
    | Error     at org.bbop.apollo.FeatureService$__do_convertFeatureToJSON_closure67.call(FeatureService.groovy)
    | Error     at groovy.lang.Closure.call(Closure.java:439)
    | Error     at org.bbop.apollo.FeatureService$__do_convertFeatureToJSON_closure67.call(FeatureService.groovy)
    | Error     at org.codehaus.groovy.grails.orm.support.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:90)
    | Error     at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
    | Error     at org.codehaus.groovy.grails.orm.support.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:87)
    | Error     at org.bbop.apollo.FeatureService._do_convertFeatureToJSON(FeatureService.groovy)
    | Error     at org.bbop.apollo.FeatureService.this$2$_do_convertFeatureToJSON(FeatureService.groovy)
    | Error     at org.bbop.apollo.FeatureService$this$2$_do_convertFeatureToJSON$0.callCurrent(Unknown Source)
    | Error     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
    | Error     at org.bbop.apollo.FeatureService$this$2$_do_convertFeatureToJSON$0.callCurrent(Unknown Source)
    | Error     at org.bbop.apollo.FeatureService.convertFeatureToJSON(FeatureService.groovy)
    | Error     at org.bbop.apollo.FeatureService$convertFeatureToJSON.call(Unknown Source)
    | Error     at org.bbop.apollo.AnnotatorController.findAnnotationsForSequence(AnnotatorController.groovy:253)
    | Error     at org.bbop.apollo.AnnotatorController.findAnnotationsForSequence(AnnotatorController.groovy)
    

There are actually a few oddities with the annotator panel updating after feature adds and deletes, but this scenario confirms a crash (the annotator panel will just say "Loading" without updating after this error, and this error above will appear in the server logs)

**Comment by nathandunn** [comment]
Most likely triggering query event prior to commit being finished.

**Comment by deepakunni3** [comment]
@cmdcolin Having trouble reproducing this bug since the merge operations that I do are snappy.
Let me know if you have a specific example to try out with.

**Comment by nathandunn** [comment]
I’m wondering if my optimization of the history operations fixed the timing issue that caused this.  

NAthan

**Comment by deepakunni3** [comment]
@nathandunn That is most likely the reason. Before the optimization the time delay was from several seconds to a minute. This would have led to the timing issue.
