### ISSUE TITLE
in-frame stop codons not identified after manually setting translation start

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#55]
The 'set translation start' option does not re-calculate the translation stop at the display level - models that have in-frame stop codons are displayed as complete, and the exported gff3 contains the display-level coordinates, although the protein sequence appears to be calculated correctly in the 'Get sequences' option. Is it possible to set the default behavior to recalculate the stop after manually setting the start, or if not, to display a warning that in-frame stop codons will not be recognized? Thanks!

**Comment by monicacecilia** [comment]
@nathandunn just in case, let's be sure re-check this on 2.0, when appropriate.

**Comment by nathandunn** [comment]
@monicacecilia   Moni, I have a Trello card in 2.0 that says to check for *ALL* closed 1.0 bugs and make sure that they are both working and that the patches have been pulled over.     I assigned you to that card.  https://trello.com/c/Za55Z2jz
