### ISSUE TITLE
An admin with read-only permissions only gets read-only permissions (for tabs at least)

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#551]
==== 

- [x] fix typo on "insufficient"
- [x] admin with read-only permissions only gets read-only permissions (for tabs at least)
- [x] confirm that user's don't have access / drop-down to organisms that they should not be able to read

====

When loading the apollo 2 demo on icebox, I can try to access the brown recluse from the annotator panel as demo@demo.com, but I get this error

    Error: {"error":"problem getting features: org.bbop.apollo.AnnotationException: You have insufficent permissions [none < read] to perform this operation"}

I think the brown recluse shouldn't even be in the dropdown for the guest user because it doesn't have access to brown recluse. Screenshot from an admin users perspective shows demo@demo.com doesn't have permissions on brown recluse

![screenshot-icebox lbl gov 2015-08-26 09-09-41](https://cloud.githubusercontent.com/assets/6511937/9495706/839badc4-4bd2-11e5-8e3a-b0847dceb24c.png)

Also insufficent is spelled wrong there and the brown recluse genome is very fragmented and takes like a minute to load (refSeqs.json is 10+MB) so we have to figure out how to handle these cases

**Comment by cmdcolin** [comment]
I don't seem to have this problem on our instance, that is, a "demo user" with read access to only certain organisms can only see those certain organisms in the dropdown.

Not sure how icebox got into this state

**Comment by cmdcolin** [comment]
Here is another confusing permissions scenario that is perhaps not totally related to the original one posted here.


If you are logged in as a admin user (that is, a user with a global admin role), but then you grant yourself only "read" permissions on a particular organism, then your permissions will drop to that of a normal user with only read permissions on that organism and the admin tabs on the annotator panel disappear. 

This was weird to me, but I'm sure someone could say this is a feature not a bug...i'd say it needs fixing though

**Comment by nathandunn** [comment]
Hmm . . . I saw that as well (the last thing you reported) . . . I though I'd fixed it though.   

WRT to icebox . . . I agree that we should do a fresh install.

**Comment by nathandunn** [comment]
copied:

 createdb -O apollo2_user -T apollo-release-production apollo-release-production_bu_2015_08_26

**Comment by nathandunn** [comment]
I re-installed the server, which seemed to fix the one problem you weren't seeing.  

The "read-only" issue is only affecting the tabs being shown.

**Comment by cmdcolin** [comment]
@nathandunn I can't login as demo@demo.com anymore

**Comment by cmdcolin** [comment]
Ok I fixed demo@demo.com login. That is important as it is what we tell users to login with at WebApolloDemo


The demo user now has global admin role now too (I did not make it this way, and it was not this way previously, the WebApolloDemo page suggests emailing to get the admin features)

**Comment by cmdcolin** [comment]
Since the original bug on icebox was fixed, and it doesn't necessarily correspond to any code fixes, I'll rename this issue to the last remaining checkbox

**Comment by nathandunn** [comment]
This is fixed on icebox now.  

```admin with read-only permissions only gets read-only permissions (for tabs at least)```
