### ISSUE TITLE
If two organisms have refseqs that share the same name, the wrong sequence can be used

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#552]
Currently, if the refseq from two different organisms share the same name, then the sequence data from organism 2 can get returned into the browser for organism 1

As an example, one genome has a scaffold5692 with length ~4500, and another has scaffold5692 with length ~3175

You can see here that the organism thinks that it is using the one with length ~4500 (i.e. you can keep scrolling), but the sequence data stops at ~3175

![screenshot-genomes missouri edu 8080 2015-08-26 14-06-29](https://cloud.githubusercontent.com/assets/6511937/9503340/e2a06dea-4bfb-11e5-96e2-66a53c2272b9.png)

It can go both ways too where sometimes the sequence from organism 1 is loaded for organism 2 and the sequence for organism 2 loaded into organism 1

I haven't confirmed if this can produce non-sense annotations yet, it seems like perhaps the backend handles it better than the client

**Comment by nathandunn** [comment]
Do you think that this is due to caching?

**Comment by cmdcolin** [comment]
I don't think so. Haven't fully untangled it yet. Can make a reproducible use case if you can't get it to work either

**Comment by nathandunn** [comment]
@cmdcolin   I can't reproduce this . . . if you could make a reproducible case when you have a monent that would be great.

**Comment by nathandunn** [comment]
@cmdcolin   Per our earlier conversation, can we close this and re-open it if it re-appears?

**Comment by cmdcolin** [comment]
Sure. wasn't able to reproduce on cflo on my instance. might have been from browsing in two tabs which as we know causes problems (see #441 )
