### ISSUE TITLE
If a user closes a track in the genome browser, it remains as checked on the annotator panel

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#554]
If a user closes a track on the genome browser, then it will remain checked on the annotator track panel

This issue doesn't seem to have any serious consequences, just an aesthetic weirdness

**Comment by cmdcolin** [comment]
This was fixed by dffc00006777aa9dd021dc60e3c60bf90124c9e3

**Comment by nathandunn** [comment]
just going to have a re-check . . . glad that its work that's already done . . . I'll add it to the changelog . . thanks

**Comment by monicacecilia** [comment]
Yep, fixed. :dancer:
