### ISSUE TITLE
Excess dijit menu attribute buildup on feature and feature-label dom elements

### ISSUE THREAD

**Issue by enuggetry** [GMOD/Apollo#556]
This appears to happen upon rollover of the feature elements.
You can see it in the DOM browser.
It doesn't seem to cause any functional problems.

![ice_screenshot_20150827-223354](https://cloud.githubusercontent.com/assets/10053377/9539830/3edf3f9e-4d0c-11e5-8440-2703ce759d69.png)

WA 2.0.0

**Comment by cmdcolin** [comment]
Do you see the same amount of buildup in jbrowse proper? The menus initialized dynamically and are also supposed to be deleted after a certain timeout period

The following code from HTMLFeatures illustrates

    _refreshMenu: function( featDiv ) {
        // if we already have a menu generated for this feature,
        // give it a new lease on life
        if( ! featDiv.contextMenu ) {
            featDiv.contextMenu = this._makeFeatureContextMenu( featDiv, this.config.menuTemplate );
        }

        // give the menu a timeout so that it's cleaned up if it's not used within a certain time
        if( featDiv.contextMenuTimeout ) {
            window.clearTimeout( featDiv.contextMenuTimeout );
        }
        var timeToLive = 30000; // clean menus up after 30 seconds
        featDiv.contextMenuTimeout = window.setTimeout( function() {
            if( featDiv.contextMenu ) {
                featDiv.contextMenu.destroyRecursive();
                Util.removeAttribute( featDiv, 'contextMenu' );
            }
            Util.removeAttribute( featDiv, 'contextMenuTimeout' );
        }, timeToLive );
    },

The CanvasFeatures is a little different I imagine since there is not actually a dom element to attach the menu to.

**Comment by enuggetry** [comment]
I'm not seeing the same problem on JBrowse alone.
This particular track is in the Volvox Sample: HTMLFeatures - Example Features.

**Comment by nathandunn** [comment]
I have had issues withe the Volvox Sample data in general.
