### ISSUE TITLE
(4h) verify that web services scripts suppport HTTPS 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#557]
Some groovy scripts have issues connecting to HTTPS.

http://stackoverflow.com/a/9578244/1739366

**Comment by cmdcolin** [comment]
I can recreate this error

But then again, the error seems to indicate that it is due to not having a valid SSL certificate.

I am using a self-signed one for testing based on this setting https://gist.github.com/jessedearing/2351836

**Comment by cmdcolin** [comment]
I was able to get it to work by adding my custom certificate to java's CAStore

http://blog.alwold.com/2011/06/30/how-to-trust-a-certificate-in-java-on-mac-os-x/

I.e.


sudo keytool -importcert -alias newcert -file /etc/ssl/certs/myssl.crt -keystore /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre/lib/security/cacerts


After that I had no errors using add_organism (I also restarted my comp first but that might have not been necessary)

**Comment by nathandunn** [comment]
The thought is to have a "--ignore-ssl-issues" option in the groovy scripts:

http://stackoverflow.com/questions/19723415/java-overriding-function-to-disable-ssl-certificate-check
http://stackoverflow.com/a/29220321/1739366

In theory the RESTClient has an option to do this . . but this is a different source:

https://github.com/jgritman/httpbuilder/blob/master/src/main/java/groovyx/net/http/RESTClient.java

**Comment by nathandunn** [comment]
@cmdcolin   You should update the front-matter for this in the HTTPS section:

https://github.com/GMOD/Apollo/blob/master/grails-app/views/webServices/index.gsp

**Comment by cmdcolin** [comment]
Sure. Looks like the web service documentation is getting very well improved

**Comment by nathandunn** [comment]
you may want to switch to use this:

https://maven-repository.com/artifact/org.codehaus.groovy.modules.http-builder/http-builder/0.7.2

@Grapes(@Grab(group='org.codehaus.groovy.modules.http-builder', module='http-builder', version='0.7.2’))

(update to 0.7.2) . . .

the API should be here:

https://github.com/jgritman/httpbuilder

Its a bit confusing as it looks like codehaus has shut down. 

Sorry, the “doc” is here . . . specifically at the bottom (and with 0.7.2 or 0.7.1) they added the “ignoreSSLIssues” option at the bottom. 

https://github.com/jgritman/httpbuilder/wiki/SSL

**Comment by cmdcolin** [comment]
@deepakunni3 added these new options via d30298696f245b




works great in my tests

**Comment by cmdcolin** [comment]
merged to master

**Comment by nathandunn** [comment]
:+1:

**Comment by nathandunn** [comment]
FYI @childers  our scripts should support https now

**Comment by cmdcolin** [comment]
To be clear...I think they always did...this is just adding the ability to bypass a certificate authority issue with the added flag.

**Comment by nathandunn** [comment]
Yep!

Nathan
