### ISSUE TITLE
Make instances of all WA versions on icebox / EC2

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#560]
It would be very useful to have many versions of WA available for testing. JBrowse does this with http://jbrowse.org/code/JBrowse-x.y.z for all versions after about 1.10. Having these instances available is actually really useful just to quickly determine regressions and verify behavior in past versions.

**Comment by nathandunn** [comment]
Agreed.  What versions do you think we should have?   Right now we have 1.0.4 and 2.0.0.  

I'm assuming we also want master and possibly 2.1?

**Comment by cmdcolin** [comment]
Ya. I guess 1.x and 2.x versions. Nightly/master build would be cool. I'd just like to have this mindset going forward. Having the version in the URL might help too instead of just WebApolloDemo. With JBrowse there is jbrowse.org/code/latest-version and this is symlinked to the latest version

**Comment by nathandunn** [comment]
- [ ] add master versions for continuous integration
- [ ] add version / git hash to server

**Comment by nathandunn** [comment]
I agree on all of this stuff . ..  now I just need to find the time.

**Comment by monicacecilia** [comment]
aaaaah, like I said :) :+1:

**Comment by nathandunn** [comment]
@cmdcolin   Was going to do this with Docker and then load using an EC2 container service . .. any thoughts.  . .

**Comment by nathandunn** [comment]
http://docs.docker.com/mac/step_one/   . . . a fancy gui client might work best . . .

**Comment by nathandunn** [comment]
Perusing EC2 instances, probalby want a m3.xlarge . . . 80 GB SSD.  Minimum of about 30-40 GB's need (20 GB just for data)

**Comment by nathandunn** [comment]
export GRAILS_VERSION=2.4.5
%n:%C%% docker run --rm -v `pwd`:/app:rw -p 80:8080 --name grails mozart/grails

build image via:

docker build https://raw.githubusercontent.com/mozart-analytics/grails-docker/master/Dockerfile

will need to fork to create the image correctly and prebuild  / preload the database.

**Comment by nathandunn** [comment]
Quick note no method for creating snapshot.  In my case I got it working on a smaller m3.xlarge instance . . and took a snapshot (which did not include the EBS volume).  I then got it working on a larger r3.2xlarge image and transferred the EBS-related stuff over.   From that I took a 100 GB snapshot.  I can launch working (including data) mounted on the root from that.   Weird part is that when launching from smaller instance type I always get the larger disk mounted at root . . which makes sense. 

- get stuff working on a large instance (with EBS storage)
- take snapshot
- launch anything

**Comment by nathandunn** [comment]
@monicacecilia  Storage of useable snapshot is roughly $10 / mo. You can probably run a demo for ~$50 (5 instances, 48 hours).  About $0.15 / hour roughly.

**Comment by cmdcolin** [comment]
gmod in the cloud might have input. plus they are wanting to use apollo2 for new version.. 

FYI jbrowse runs off a micro instance...i think testing on a micro would be worth it

**Comment by nathandunn** [comment]
That is a good idea.  I’ll shoot off an email to Scott.  

I can probably run off of a small to medium (need about 4 GB of memory for the full stack).    The real limiting factor is hosting 20GB of honeybee data.  

Nathan

**Comment by cmdcolin** [comment]
Why was this closed?

**Comment by cmdcolin** [comment]
Or, was there anything done?

**Comment by nathandunn** [comment]
I think I meant to close #564 . . . which is done (and on Amazon).

**Comment by nathandunn** [comment]
this is done
