### ISSUE TITLE
(2h) create a script 'delete_annotations_from_organism.groovy' to delete all annotations from an organism

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#562]

**Comment by nathandunn** [comment]
. . . for when you have time . . . or we can switch later . . . just don't want to forget it

**Comment by cmdcolin** [comment]
Note that there is a similar problem with user


If you try and delete a user that has annotations associated with them, it produces this error

![screenshot-icebox lbl gov 2015-10-08 12-12-25](https://cloud.githubusercontent.com/assets/6511937/10373905/dd2fb6b4-6db5-11e5-8d74-d5be08daf644.png)


Error Deleting User
Failed to delete the user Hibernate operation: could not execute statement; SQL [n/a]; ERROR: update or delete on table "grails_user" violates foreign key constraint "fk_35nc3xd2axx6fwyap4bjkt09u" on table "feature_event" Detail: Key (id)=(185819) is still referenced from table "feature_event".; nested exception is org.postgresql.util.PSQLException: ERROR: update or delete on table "grails_user" violates foreign key constraint "fk_35nc3xd2axx6fwyap4bjkt09u" on table "feature_event" Detail: Key (id)=(185819) is still referenced from table "feature_event".


In my opinion, just "flagging" the user as deleted is better in this case.

**Comment by nathandunn** [comment]
This is "mostly" done, just have not yet tested / run it, but I think that all of the hooks are there.

**Comment by nathandunn** [comment]
@deepakunni3   Can you take a look at this one now.   It should be mostly done, but I haven't tested it at all.   The service method should work, however (knock on wood).

**Comment by nathandunn** [comment]
dang you move quickly . . .

**Comment by deepakunni3** [comment]
It would be good to test the scripts, in case there is something missing.

**Comment by nathandunn** [comment]
I’ll test this and the other one you finished today. 

Nathan

**Comment by deepakunni3** [comment]
:+1:

**Comment by nathandunn** [comment]
that worked without a hitch . . I like the explicit usage setting for org id and name.  I added some additional doc for adminuser and adminpassword, but the code is unchanged.
