### ISSUE TITLE
create a multi-organism snapshot for Apollo2

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#564]
Related to #560 . . . but we want to host lots of identical organisms (with different users with write access to each) on the same server.

**Comment by cmdcolin** [comment]
that is the current way that this can be handled but it doesn't scale well. I think it would be better if we added better control over "who can see what" (i.e. instead of a user just having READ permission, they might only have READ-THEIR-OWN-ANNOTATIONS)

**Comment by nathandunn** [comment]
I think that we have that use-case in an issue somewhere as well (if not, please add it).   Yeah, this will replicate the organism / sequence / scaffolds, which is not ideal, but should work in the interim if we don't fix the permissions fixed.

**Comment by nathandunn** [comment]
Done and ran successful training (Sao Paolo images).
