### ISSUE TITLE
Small difference in file loading between Apollo 1 and Apollo 2

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#569]
I noticed this on the honeybee webapollo instances

The Honeybee tracks called "Fgenesh++ with RNASeq training data" and "Fgenesh++ without RNASeq training data" don't load in Apollo2 on the demo browser.

These tracks did work in Apollo1

I think Apollo2 for some reason doesn't like the "+" signs in the filenames.  You can see on the backend that the filenames that Apollo2 is searching for replace the "+" with a space.

This whole issue is actually avoidable by using a simpler arguments for the --trackLabel argument to flatfile-to-json, and then including the full fancy track name as the --key argument, and this makes it so that + signs aren't included in the filenames.

**Comment by nathandunn** [comment]
Hmm . . wonder if it messes up the JSON parsing?  Do you know where its happening on the backend code (too lazy to look right now)?

**Comment by cmdcolin** [comment]
I don't know at what level, but I imagine grails perhaps does something smart. Sometimes websites think things like

"google.com/?query=This+Is+My+Query"

is actually a query for "This Is My Query"


Therefore...the scope of this bug might be really limited to this case with the plus signs...not very important...

**Comment by nathandunn** [comment]
Agreed .. lower priority
