### ISSUE TITLE
allow collapsible HTMLFeatures in evidence track

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#571]
Related to view of transcripts here.   #568  . .. . where we just want the overlapped coding region.

Ideally should be able to put in trackList.json and / or exist in drop-down. 

@cmdcolin   For when you have time.

**Comment by nathandunn** [comment]
@cmdcolin   How much work do you think that this would be?

**Comment by nathandunn** [comment]
Or . . if I were to do it (if that was advisable) where would I look to do it. 

Thanks.

**Comment by cmdcolin** [comment]
should just be copying these lines from AnnotTrack into DraggableHTMLFeatures (and making sure that these methods are only defined once in the file..)

https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/AnnotTrack.js#L5580-L5611

**Comment by cmdcolin** [comment]
Woop. Meant to link this too https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/AnnotTrack.js#L5561-L5578

_getLayout and _trackMenuOptions

**Comment by nathandunn** [comment]
Perfect thanks.

**Comment by cmdcolin** [comment]
I went ahead and added this. Should be fixed

**Comment by nathandunn** [comment]
awesome!

**Comment by nathandunn** [comment]
To test:  

- you can collapse evidence tracks like you can annotation tracks.   Longer-term I think we'll want to "somehow".  See #612.

**Comment by monicacecilia** [comment]
:dancer:
