### ISSUE TITLE
(1h) feature search on Annotator, Search, Track Panels/Tabs should be case-insensitive

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#575]
- [x] annotator search panel
- [x] sequence search panel (this was already true . . in 2.0.0)
- [x] track search panel (this was already true . . in 2.0.0)

**Comment by cmdcolin** [comment]
Hmm. Track panel search is case insensitive.

**Comment by monicacecilia** [comment]
:+1: :dancer:
