### ISSUE TITLE
Information Editor shows only the first attribute in the 'Attributes' section even if there are more attributes

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#579]
This is due to a bug in FeaturePropertyService::getNonReservedProperties

```
    @NotTransactional
    def getNonReservedProperties(Feature feature) {
        return FeatureProperty.findAllByFeature(feature).find(){
            return !nonReservedClasses.contains(it.cvTerm)
        }
    }
```

The fix is to remove `@NotTransactional` and use `findAll()` instead of `find()` for `findAllByFeature()` statement.

**Comment by nathandunn** [comment]
Test:
- add multiple attributes to an annotation in the information editor.  Confirm that they are visible, can be deleted, updated, etc.

**Comment by monicacecilia** [comment]
More "Attributes" are now visible, but user is unable to "Delete" any of them. Also, odd behaviour on the "Attributes" fields is described at #627

**Comment by nathandunn** [comment]
I think that this is either a side-effect of another bug or it somehow got into chrome oddly.   Unless there is a clear reproduction path . . I think we might be able to wait until RC5 . . but we'll see.  Will take a look at the end.

**Comment by monicacecilia** [comment]
:dancer:
