### ISSUE TITLE
Error while merging transcripts with long names

### ISSUE THREAD

**Issue by deepakunni3** [GMOD/Apollo#580]
While merging transcripts, if one of the transcript has a name that is long (ex. fgeneshpp_with_rnaseq_Group1.10_108_mRNA-00001), the server gives a PSQL Exception.
`org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)`

**Comment by nathandunn** [comment]
If you could take a look at this @monicacecilia  when you have a chance.    We just need to know if a transcript name should ever be greater than 255 characters.

**Comment by nathandunn** [comment]
Talked to @monicacecilia   . . unlikely, before machine-generated names, this will happen.  We'll just either make it twice as long or change it to type "text".

**Comment by nathandunn** [comment]
Test:
- create two annotations with really long names (say 255 characeters or more) and confirm
- merge the two annotations and confirm that the merged names are also more than 255 characters long.

**Comment by monicacecilia** [comment]
:dancer:
