### ISSUE TITLE
When the number of overlapping transcripts for a given gene changes, the # of transcripts in the Information Editor drop-down menu does not always update accordingly.

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#587]
when changing the number of genes on a transcript related isoform overlap . . the # of names in the info editor drop-down does not always change

**Comment by nathandunn** [comment]
Related to #73.   Everything works fine, but the number of transcripts in the drop-down does not always reflect the change in isoform.

**Comment by monicacecilia** [comment]
@deepakunni3 if you have a minute, could you please check that this has been fixed? 
Else, I'll test in the next 2 weeks. Thank you!

**Comment by monicacecilia** [comment]
This has been fixed. Also checked details related to #73, to be sure. And those have also been fixed. Great job! 💃
