### ISSUE TITLE
Splitting and then merging back together causes exception

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#588]
When you split a feature and then merge the pieces back together again, it causes an exception

    2015-10-09 12:18:37,136 [clientInboundChannel-2] DEBUG apollo.AnnotationEditorController  - exception org.bbop.apollo.AnnotationException: Not one current feature event being merged for: 5b38fc25-9bd6-4f18-a528-72b3304b84d8
    2015-10-09 12:18:37,136 [clientInboundChannel-2] DEBUG apollo.AnnotationEditorController  - exception message Not one current feature event being merged for: 5b38fc25-9bd6-4f18-a528-72b3304b84d8

This exception is thrown from FeatureEventService

Note that this operation "worked" in that the feature does become merged but I imagine the history for the feature is not consistent in this case

**Comment by nathandunn** [comment]
Do you have an example annotation / steps taken?  I just tried it and it worked fine.

**Comment by cmdcolin** [comment]
For me it always happens on the transcripts that I have tried, but as I said, it "works" but only after a page refresh, presumably because the thrown exception prevents the update operation from happening

Try GB48937-RA

Select the two 5' most exons, right-click, and select "split"

It will split into two transcripts

Then select the the two transcripts, right-click, and select "merge"

Then they will not merge on screen, the log will have the messages that I noted, but upon page refresh they will be merged



![unknown2](https://cloud.githubusercontent.com/assets/6511937/10401743/92110f9e-6e86-11e5-93d3-fe45408b162b.png)


Figure: the split transcripts. I selected merge on these two and they did not merge immediately and the error was thrown in the error log.

**Comment by nathandunn** [comment]
Ahh . . it will for the first split and first merge but not after that.   The update history is not being sent back to the server properly.   I'll take a look.

**Comment by nathandunn** [comment]
So . . the issue (which @cmdcolin  alluded to) is that the history is throwing exceptions for some reason, explicitly in addMergeFeatureEvents after some history has been shown.  I was not seeing this earlier, but it causes at least one of the side-cases.

**Comment by nathandunn** [comment]
Test:
- create a feature and do stuff with out to add history to it
- create another feature and do stuff with out to add history to it
- merge the features
- add some more history
- split the features and add more history

Should all work as expected.

**Comment by monicacecilia** [comment]
well, there are a number of other things going on, and I think they are all linked so I am going to remove the 'Ready' label until we solve all of those: 
- #628 Merge and split fails to reproduce the correct results
- #73 isoforms should belong to the same gene model, removing overlap should result in transcripts that belong to separate gene models
- #498 isoform overlap rules seem to be inconsistently applied

**Comment by monicacecilia** [comment]
Still waiting on #73

**Comment by monicacecilia** [comment]
After testing, it works as expected. 
Also #73, #498, and #628 are now closed. 
:dancer:
