### ISSUE TITLE
It is possible to get into a state where switching organism is not possible

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#589]
This is hard to reproduce but I have seen it some months back and now.

Basically, as the title says, you can get into a state where it is impossible to change your which organism you are viewing (when logged it)

The UserOrganismPreferences table allows having different preferences for each organism, but it seems to have gotten into an inconsistent state where multiple organisms have "current_organism" set to true

      id  | version | domain | name | preferences_string |                 class                  | user_id | current_organism | endbp | organism_id | sequence_id | startbp
    ------+---------+--------+------+--------------------+----------------------------------------+---------+------------------+-------+-------------+-------------+---------
       17 |     112 |        |      |                    | org.bbop.apollo.UserOrganismPreference |      15 | t                | 92316 |          16 |          47 |   64964
     9254 |      12 |        |      |                    | org.bbop.apollo.UserOrganismPreference |      15 | t                | 69544 |        9253 |        9284 |   31613

**Comment by nathandunn** [comment]
Hmm . . not sure if it should re-check / fix this on load or fix it when it is boot-strapped.

**Comment by monicacecilia** [comment]
Have there been any other reports about this? 
We are closing for now - as it should have been fixed. If not, please report and we will re-open.

**Comment by cmdcolin** [comment]
This just happened to me so I think it is still a bug

**Comment by nathandunn** [comment]
This is usually associated with a timeout for me, and if I refresh the screen it typically "fixes" it.  Either way, not ideal.  If you have a recipe for reproducing it, I'm sure we can fix the rest of it.

**Comment by cmdcolin** [comment]
As I noted in my original post, it is not related to timeout. It is actually because multiple "current_organism" tags become switched on. The code gets quite confused by this and refreshing or logging in and out don't fix it. You have to manually go into the database and send a "update preferences set current_organism=false where id=..." so that there is only one current_organism=true in the table

**Comment by nathandunn** [comment]
Right.  I have made a few fixes to it, but I have had trouble getting it into the bad state, again as I try to clear out the old ones, first.  Do you know how you are getting in this state?

**Comment by cmdcolin** [comment]
When I did it I was creating a new organism. It's not straightforward to reproduce but I think that the "current organism" should not be stored in the database like this.  It causes other problems such as https://github.com/GMOD/Apollo/issues/441

**Comment by nathandunn** [comment]
I'll have to make changed to accommodate 441 on both ends.

Nathan
