### ISSUE TITLE
Annotator panel doesn't remember the width that the user set it to

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#591]
As title says. If you resize annotator panel, and refresh page, its position is not remembered.

**Comment by cmdcolin** [comment]
I'd just make this a cookie or something rather than storing this in the database.

**Comment by nathandunn** [comment]
I think that is a good idea.  I agree that it is annoying the way it is.   I'll fix this right now.

**Comment by nathandunn** [comment]
http://www.gwtproject.org/doc/latest/DevGuideHtml5Storage.html

**Comment by nathandunn** [comment]
Put in the wrong branch . . . some overlap issues as well.

**Comment by nathandunn** [comment]
Fixed now . . . remembers the "open/close" state and the last open width.

**Comment by nathandunn** [comment]
Panel remembers if it was last opened or closed and what it's last open width was.

**Comment by monicacecilia** [comment]
:+1: :dancer:
