### ISSUE TITLE
Create group functionality in UI throws exception

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#592]
On clicking the "plus" button under Users Tab->bottom panel->Groups Tab, I receive the following:

```
uncaught exception: com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : this$static is undefined
```

**Comment by monicacecilia** [comment]
@erasche do you mean when you try to add a new "Group" using the plus (+) sign? -

gah! @nathandunn I just got an error on our demo - slightly different wording at the end.
<code>
Uncaught com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : Cannot read property 'userId' of undefined
</code>

**Comment by nathandunn** [comment]
I will take a look.  Most likely the button should be disabled until you enter text. 

Nathan

**Comment by erasche** [comment]
@monicacecilia yep, exactly what I mean. It's a select field so no way to enter text.

**Comment by monicacecilia** [comment]
But the box to type that text doesn't allow the admin to do so in the first place. - at least at http://genomearchitect.org/WebApolloDemo

**Comment by nathandunn** [comment]
So . . there are few problems . . . mostly due to a hastily assembled UI.  I get something similar to above if I don't click on a user and try to add a group.     I'll try to clean up some of the ambiguity on the master branch (and soon 2.0.1) and you can tell me if its there.  

In the interim @erasche   if you click on the user such that it is highlighted and then click "+" does it work okay?

**Comment by nathandunn** [comment]
I'm going to continue continue to work on UI fixes . . . feel free to pull master at any point.  I will probably be done tomorrow.

**Comment by nathandunn** [comment]
- [x] unselect group editing when unselected
- [ ] re-select (don't unselect) when adding / removing group to a user
- [ ] review other user / group interfaces for a similar failed paradigm (do not add when not selected)

**Comment by erasche** [comment]
@nathandunn oh! Okay. This is all making a bit more sense. I finally figured out that I have to go to groups, create the group, go to users, select a user, then I can click the plus button which applies a group to a user. That workflow was not at all clear. For some reason I expected the "+" to allow me to create a new group on the user tab, clearly wrong.

**Comment by nathandunn** [comment]
Thanks for the feedback.   I agree that this workflow needs to be tweaked to feel more “standard”.   We’ll see what we can do.  

Nathan

**Comment by nathandunn** [comment]
This is what confluence does . . which is a lot more explicit.  However, if you have 30 (or more) organisms per server and want a group for each, this won't exactly work well.

<img width="452" alt="screen shot 2015-10-14 at 11 48 59 am" src="https://cloud.githubusercontent.com/assets/751274/10494790/3e502aee-726d-11e5-9cad-b8c3601e058a.png">

**Comment by erasche** [comment]
That looks very admin friendly. 

My org's use case is on one extreme, we'll have thousands of organisms, but organised into relatively few groups. I can see that something like that wouldn't work for groups like i5K. 

If you were looking for design options that scale,something akin to select2's "Multiple Select Boxes" [https://select2.github.io/examples.html]() would be brilliant

![select-groups](https://cloud.githubusercontent.com/assets/458683/10495033/4e2c0b7e-727f-11e5-9c84-722b1f3eda1a.png)

**Comment by nathandunn** [comment]
Too funny.   This is what confluence uses on its group panel to add groups (as well as to add tags).    I’ll take a look as to how they implemented that or to see if there is a similarish way to implement that widget.  

Just as an FYI, I’m using confluence as a reference just because they do this large user/group management stuff all the time and I think its pretty tried and tested.  

Nathan

**Comment by nathandunn** [comment]
@erasche   Got caught up with some other stuff.  Am aiming to get this into the 2.0.1 release, though.  This week or early next weeek.

**Comment by erasche** [comment]
No rush. We don't have it in prod yet, so I'm just reporting things as I
find 'em.
15. okt. 2015 2.55 a.m. skrev "Nathan Dunn" <notifications@github.com>:

**Comment by nathandunn** [comment]
No worries.  I think you're not the first person to run into these.  If these changes don't get it out in 2.0.1 they should be out fairly shortly.

Also, I think that this will work for us out of the box:

http://jdramaix.github.io/gwtchosen/

**Comment by erasche** [comment]
Oh, nice, those look great. Will make the experience much nicer. Thanks again!

**Comment by nathandunn** [comment]
Associated pull request is in there.   I'll try to get screen shots in there tomorrow.   Should be much simpler. 

Nathan

**Comment by nathandunn** [comment]
Test:
- user and group UI's should be easier to work with . . . see screenshots below:

![screen shot 2015-10-20 at 9 48 55 am](https://cloud.githubusercontent.com/assets/751274/10614556/cd4666ae-770f-11e5-95e9-739e69760973.png)

![screen shot 2015-10-20 at 9 49 16 am](https://cloud.githubusercontent.com/assets/751274/10614564/daeea55a-770f-11e5-8f03-560ac328b3ca.png)

**Comment by nathandunn** [comment]
FYI . . the first one is the user panel. . .

**Comment by erasche** [comment]
Wow! Awesome!

**Comment by monicacecilia** [comment]
@nathandunn  I cannot delete current users that someone else created: 
![screen shot 2015-10-26 at 4 03 00 pm](https://cloud.githubusercontent.com/assets/1714621/10745000/5040a188-7bfb-11e5-84d9-ed3db0bb5abf.png)

But I am able to create new users and delete users I created.

**Comment by monicacecilia** [comment]
I can confirm improvements to UI for user and group edits. 
:dancer:
