### ISSUE TITLE
export GWT 2-way data-binding

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#594]
Will hopefully minimize some coding / errors.  

http://www.lteconsulting.fr/hexabinding/

I also like the idea of being able to do an angular-style two-way binding:
<g:textBox ui-field="someTextBox.text" value="internalValue"/>

<g:textBox ui-field="someTextBox.text"/>

**Comment by nathandunn** [comment]
also the use of "generators" to remove REST boiler-plate (might) be interesting, as well.

**Comment by nathandunn** [comment]
Probably Tessel would be the best . . . reactive . . similar to Angular in pieces and removes a lot of biolerplate:
- https://www.youtube.com/watch?v=iA33B8cfTiA
- http://www.tessell.org/

**Comment by cmdcolin** [comment]
We could move to use a pure JS framework for the annotator panel, move away from gwt :)

I feel like we could make it a lot more lightweight that way, and it could still keep the style of the current annotator panel.

**Comment by nathandunn** [comment]
That probably won't happen unless JBrowse moves away from Dojo and into another framework like React, Angular2, Polymer, pure JQuery, etc.   Also note that Angular2 utilizes TypeScript, but like GWT you can always write JavaScript.

**Comment by cmdcolin** [comment]
Currently GWT serves a page with annotator panel and has jbrowse in an iframe. All I meant is that there could just as easily have just have a similar setup where we make some other javascript (any framework) and still contain jbrowse in an iframe. Just an option

**Comment by nathandunn** [comment]
I spent about 2-3 weeks look at any other javascript option (not sure where this is) before using GWT to build what amounted to a full web application.   Getting the split-panel behavior with tabs which also have a split-panel behavior, similar to a modern application, was relatively easy this way.    Definitely sure its possible, but the UI implementation of the basic UI was pretty fast this way, and it was trading hacks this way.  Would have preferred using pure-JS for the communication layer, but overall this has been pretty robust.  We'll see where we go with this.
