### ISSUE TITLE
Document method for using other jbrowse plugins in WA

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#596]
As the title says

Would be good to have a workflow for this, or at least have it documented

There are pretty obvious workarounds but having a best practices scenario would be good

**Comment by nathandunn** [comment]
I agree.  I think this would be good documentation to add . . esp. before the hackathon.

**Comment by nathandunn** [comment]
@cmdcolin   I actually think this is done, but let me know if it requires additional documentation: 

https://github.com/GMOD/Apollo/blob/master/docs/Configure.md

I did a small update to reflect the current state.
