### ISSUE TITLE
enable toggle of JBrowse-style track selector

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#597]
Basically just need to flip this to to 1 here when the trackList is faceted:

https://github.com/GMOD/Apollo/blob/master/src/gwt/org/bbop/apollo/gwt/client/MainPanel.java#L383

There is a "list" command . . . . issued into AnnotTrack.js  there is probably a very easy way you could just change it here to pass along those changes:

https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/AnnotTrack.js#L316

TrackPanel calls loadTracks here:

https://github.com/GMOD/Apollo/blob/master/src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java#L277

and then here:

https://github.com/GMOD/Apollo/blob/master/src/gwt/org/bbop/apollo/gwt/client/TrackPanel.java#L287

When parsing the JSON object, you can just set a flag in TrackPanel that MainPanel can access.  It will change potentially based on the organism, so it should be interesting.

**Comment by nathandunn** [comment]
Also, the order of loading is . . . 

1 - update genomic location via MainPanel
2 - show tracks based on loaded frames from the MainPanel (at that point you can parse them)

Thinking about this . . . you might have to actually scan the file-system first once the organism is selected / changed.  Not hard but non-optimal.

**Comment by cmdcolin** [comment]
The order of loading that you have specified is correct and in this case it makes it difficult to choose to even in principle know what type of tracklist is being used

I would have to make a rest call from the GWT code to a grails controller that then parses some config files, and even at the end of this it could wrong since the config file system that jbrowse uses is very complex

**Comment by nathandunn** [comment]
I can take a look at this if you want.  

I'm doing a lot of this type of thing for projection so I think I know what needs to be done.   

Do you know what file(s) it should be looking for? 

Nathan

**Comment by cmdcolin** [comment]
How about i put it a different way.

This is one of those cases where we are trying to be "smarter than the user" by trying to make a decision for them about what they want.

We should instead just have a configuration variable called "use native track selector" and use that

**Comment by cmdcolin** [comment]
That would be easy to implement I think and probably less headache, easier to configure, etc.

**Comment by nathandunn** [comment]
That's brilliant.  We can just put a flag in the track panel that says use native selector.  If you want a default value in the config file it wouldn't hurt but having the selection and storing it using browser storage would be a pretty easy / elegant solution. 

Nathan

**Comment by nathandunn** [comment]
Definitely lets do that. 

Nathan

**Comment by cmdcolin** [comment]
Should be ready since #611 was merged

**Comment by nathandunn** [comment]
Yep . . thanks . .. I'll get these deployed shortly . .  . let me know if you have any final thoughts on the merge notes.

**Comment by nathandunn** [comment]
I'm going to "disable/hide" the Track datagrid when show native is selected (easier than trying to sync them).  And call reload when we hide the native track again.

**Comment by cmdcolin** [comment]
That seems just awkward to me. I can see why but the synchronization "reasoning" is unnecessary. Synchronization should happen automatically via the subscribe/publish event system

**Comment by nathandunn** [comment]
If you think you can work that . .. (I mean . . I know it works, because we use it).

If you want to:

A) hide the table dataGrid.setVisible(false) when showing and the opposite when hiding (and the request “loadTracks”)
B) synchronize them directly (which I think is what you’re proposing).

I’m fine with either.  Do you want to finish this out?

Thanks,

Nathan

**Comment by nathandunn** [comment]
Otherwise I can finish it up.

**Comment by cmdcolin** [comment]
I added the commit to "synchronize them" here dffc0000677

**Comment by cmdcolin** [comment]
Feel free to review and mark as ready if needed

**Comment by nathandunn** [comment]
That is perfect.  Thanks. I think we are a go!

**Comment by monicacecilia** [comment]
It works as expected. :dancer: 
@nathandunn and if available, it will show a hierarchical display of the data, correct? 


@nathandunn, for Milestone 2.0.2:
- will this "Tick" box also be the way users access the faceted browsing style? 
- My suggestions on the matter are in #536

**Comment by nathandunn** [comment]
@nathandunn and if available, it will show a hierarchical display of the data, correct?
- yes

@nathandunn, for Milestone 2.0.2: will this "Tick" box also be the way users access the faceted browsing style?
  - yes
My suggestions on the matter are in #536
  - we can get "closer" to that, though we can't emulate exactly that (the button can't be in the navbar area, but can be just to the right of it or anywhere else that is close).  I'm going to add it to "discussion".

**Comment by monicacecilia** [comment]
:+1:
