### ISSUE TITLE
add info logging for permission granting

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#599]
Is there a logging level that will let us keep track of the addition or removal of permissions, at the group and user level?

**Comment by nathandunn** [comment]
We can add logging for this pretty easily . . .  I'll add some documentation on how to adjust logging-level (you can get pretty specific).  
- [ ] add logging for adding / removing permissions
- [ ] add documentation for how to adjust logging level in ```apollo-config.groovy```

**Comment by nathandunn** [comment]
Customizing configurations goes here.

**Comment by nathandunn** [comment]
@cmdcolin  Can you review and close this when you have a chance.

**Comment by cmdcolin** [comment]
Sure. I tested this out and it looked good

**Comment by cmdcolin** [comment]
I might also want to add some more docs on separating logs to different files e.g. http://stackoverflow.com/questions/6330436/grails-and-log4j-how-to-logs-in-different-files-with-same-level

Then have separate logfiles for logins, permissions

**Comment by cmdcolin** [comment]
@childers if you had any other specific use cases let us know or feel free to reopen

**Comment by nathandunn** [comment]
That’s fine.  You might want to create a separate doc for that and reference it.  I mostly just wanted to give a quick high-level of it.  Also, make sure you’re not duplicating something we can just link to.   

Nathan
