### ISSUE TITLE
a user with "no access" has access to all of the admin panels (and the name does not show up) on okay

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#615]

**Comment by cmdcolin** [comment]
Not sure what this refers to?

**Comment by nathandunn** [comment]
![screen shot 2015-10-21 at 9 07 39 am](https://cloud.githubusercontent.com/assets/751274/10642580/3cfe0394-77d3-11e5-85e1-2f3e821f9b29.png)

closing yields this . .  all active:

![screen shot 2015-10-21 at 9 08 06 am](https://cloud.githubusercontent.com/assets/751274/10642589/46bd5326-77d3-11e5-97e4-e45bd1360931.png)

- [ ] allow public jbrowse link (similar to login)
- [ ] hide all tabs!

**Comment by cmdcolin** [comment]
Thanks. It is also kind of weird because normal users will see those admin tabs while logging in but they will disappear once they finish logging in

**Comment by nathandunn** [comment]
True . . . would be good to fix in 2.0.2.  

Nathan

**Comment by nathandunn** [comment]
Also (and most importantly) have to disallow closing the modal.

**Comment by nathandunn** [comment]
last one!

**Comment by monicacecilia** [comment]
I'm on it.... !!!!! almost :)

**Comment by monicacecilia** [comment]
I can corroborate that: 
- User without admin privileges cannot see other tabs
- User without any access cannot see any organisms and the 'Welcome' window allows to either Logout or see public browsers but not any other information. 

Looks good and behaves as expected. :dancer:
