### ISSUE TITLE
Add new organism broken on RC1

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#616]
If you go and try to add new organism, it fails due to checkLogin

    | Error 2015-10-21 09:59:03,828 [http-bio-8080-exec-2] ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [GET] /apollo/user/checkLogin
    Stacktrace follows:
    Message: null
        Line | Method
    ->>  139 | $tt__checkLogin  in org.bbop.apollo.UserController
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    |    198 | doFilter         in grails.plugin.cache.web.filter.PageFragmentCachingFilter
    |     63 | doFilter . . . . in grails.plugin.cache.web.filter.AbstractFilter
    |    449 | executeChain     in org.apache.shiro.web.servlet.AbstractShiroFilter
    |    365 | call . . . . . . in org.apache.shiro.web.servlet.AbstractShiroFilter$1
    |     90 | doCall           in org.apache.shiro.subject.support.SubjectCallable
    |     83 | call . . . . . . in     ''
    |    383 | execute          in org.apache.shiro.subject.support.DelegatingSubject
    |    362 | doFilterInternal in org.apache.shiro.web.servlet.AbstractShiroFilter
    |    125 | doFilter         in org.apache.shiro.web.servlet.OncePerRequestFilter
    |   1145 | runWorker . . .  in java.util.concurrent.ThreadPoolExecutor
    |    615 | run              in java.util.concurrent.ThreadPoolExecutor$Worker
    ^    744 | run . . . . . .  in java.lang.Thread

**Comment by nathandunn** [comment]
See the one I just submitted as well

**Comment by cmdcolin** [comment]
Updated to reflect one issue that I found

**Comment by cmdcolin** [comment]
Didn't mean to close necessarily. Feel free to test if needed

**Comment by nathandunn** [comment]
Getting this error . . which is a liquibase problem:

```
problem saving organism: org.springframework.dao.DataIntegrityViolationException: Hibernate operation: could not execute statement; SQL [n/a]; ERROR: null value in column "seq_chunk_prefix" violates not-null constraint; nested exception is org.postgresql.util.PSQLException: ERROR: null value in column "seq_chunk_prefix" violates not-null constraint
```

I'll fix it.

**Comment by nathandunn** [comment]
Was something wrong with the build . . . Doing a dump of 2.0.0 database into 2.0.1 . . .

**Comment by cmdcolin** [comment]
Can you elaborate? 

I mean, I see the same issue if I try to directly upgrade a 2.0.0 instance to 2.0.1

**Comment by cmdcolin** [comment]
Do you have to literally do a database dump? You cannot just point a 2.0.1 version to 2.0.0 database?

**Comment by nathandunn** [comment]
It should work the same either way . . . most of the time liquibase will take care of things, but sometimes it doesn't.  

Anyway, I tried it with the dump method and I got the exact same result, which is actually good.  Typically, I would do this with a quick SQL patch, but that doesn't really work for all of our user's obviously. 

Anyway, I'll wade through this until I get the appropriate effect. 

http://grails-plugins.github.io/grails-database-migration/docs/manual/guide/gettingStarted.html

**Comment by cmdcolin** [comment]
Ah ok. I guess we might need to resolve the migration from #586

**Comment by nathandunn** [comment]
Yeah .. we'll just fix it here, though.

**Comment by nathandunn** [comment]
Putative Work-log based on this:  http://wpgreenway.com/posts/grails-db-migration-tutorial/ . . . **trying to simulate a user experience**:

- [ ] get 2.0.0 dump from icebox 
- [ ] load into a new 2.0.0 database   (rename role in script, drop db, create db, create role from database, load sql)
- [ ] point to the new 2.0.0 database 
- [ ] run server in dev mode (make sure it works)
- [ ] dbm-status to check 
- [ ] dbm-generate-changelog changelog-2.0.0.groovy
- [ ] update to 2.0.1 and re-run to get any fixes
  - [ ] dbm-status to check 
  - [ ] dbm-generate-changelog changelog-2.0.1.groovy
  - [ ] checkin the changelog-2.0.1 file (into master)
- [ ] enable automatic checkin:
    - [ ] grails.plugin.databasemigration.updateOnStart = true
    - [ ] grails.plugin.databasemigration.updateOnStartFileNames = ['changelog-2.0.0.groovy','changelog-2.0.1']

**Comment by nathandunn** [comment]
Its possible that there are SQL changes on the production database which are creating issues with this tracking system . . I'll try to re-enforce the constraints to re-check

**Comment by nathandunn** [comment]
Also, you can generate the dbm-generate-gorm-changelog . . instead . . does not require a database.  This might be the more "correct" way to do it, since we can't say for sure what user's have done with their database (as in our case).

**Comment by nathandunn** [comment]
Ran into some caching issues . . .turning it off temporarily to see if I can't get around it:

```
Caused by: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: DefaultConfigurationSource [ ehcache.xml or ehcache-failsafe.xml ]
	at net.sf.ehcache.CacheManager.assertNoCacheManagerExistsWithSameName(CacheManager.java:628)
	at net.sf.ehcache.CacheManager.init(CacheManager.java:392)
	at net.sf.ehcache.CacheManager.<init>(CacheManager.java:270)
	at org.hibernate.cache.ehcache.EhCacheRegionFactory.start(EhCacheRegionFactory.java:86)
	... 77 more
```

**Comment by nathandunn** [comment]
Fix was to update the database migration plugin to 1.4.1 : https://jira.grails.org/browse/GPDATABASEMIGRATION-161

**Comment by cmdcolin** [comment]
Migration worked well for me

**Comment by deepakunni3** [comment]
If I create a fresh clean database and then try to deploy, I get migration failed with stacktrace:
```
ERROR context.GrailsContextLoaderListener  - Error initializing the application: Migration failed for change set changelog-2.0.1.groovy::1445460972540-25::nathandunn (generated):
     Reason: liquibase.exception.DatabaseException: Error executing SQL ALTER TABLE sequence DROP COLUMN ref_seq_file: ERROR: column "ref_seq_file" of relation "sequence" does not exist:
          Caused By: Error executing SQL ALTER TABLE sequence DROP COLUMN ref_seq_file: ERROR: column "ref_seq_file" of relation "sequence" does not exist:
          Caused By: ERROR: column "ref_seq_file" of relation "sequence" does not exist
Message: Migration failed for change set changelog-2.0.1.groovy::1445460972540-25::nathandunn (generated):
     Reason: liquibase.exception.DatabaseException: Error executing SQL ALTER TABLE sequence DROP COLUMN ref_seq_file: ERROR: column "ref_seq_file" of relation "sequence" does not exist:
          Caused By: Error executing SQL ALTER TABLE sequence DROP COLUMN ref_seq_file: ERROR: column "ref_seq_file" of relation "sequence" does not exist:
          Caused By: ERROR: column "ref_seq_file" of relation "sequence" does not exist
```

**Comment by nathandunn** [comment]
Shoot . . I didn’t try that . . . let me take a look.  

Nathan

**Comment by cmdcolin** [comment]
Maybe use something like "precondition" to check if these columns exist perhaps https://fbflex.wordpress.com/2012/07/14/preconditions-with-the-database-migration-plugin-in-grails/

**Comment by nathandunn** [comment]
That’s a good idea.   I’ll take a look. 

Nathan

**Comment by nathandunn** [comment]
note:  

http://grails-plugins.github.io/grails-database-migration/docs/manual/guide/groovyPreconditions.html <http://grails-plugins.github.io/grails-database-migration/docs/manual/guide/groovyPreconditions.html>

**Comment by nathandunn** [comment]
http://www.liquibase.org/documentation/preconditions.html <http://www.liquibase.org/documentation/preconditions.html>

**Comment by cmdcolin** [comment]
This might still have problems i.e. #623 didn't fix it

**Comment by nathandunn** [comment]
Yeah, I think it just doesn’t run it.   Getting the same error.  

Nathan

**Comment by cmdcolin** [comment]
I think checkColumn needs to specify the schemaName according to liquibase docs

Assume schemaName "public" ?

**Comment by nathandunn** [comment]
Ahh . .  okay I’ll try that . . tagging is fun ;)

**Comment by nathandunn** [comment]
Looks like you forgot to check the table as well, but otherwise worked (so it was checking the column on the table that wasn’t there (not sure why it wouldn’t assume that failing to find the table was also a failure).

Just as an FYI for @deepakuni as well . . . I think it stores the applied change sets in the database itself, so if it fails for some reason during development, but may apply the change set, you have to remove the database and re-apply. 

Nathan

**Comment by monicacecilia** [comment]
Also checked creating new organisms (from UI) while inspecting #621 (Delete organism is greyed out after creating new organism in RC2) and corroborated that it works as expected. 
:dancer:
