### ISSUE TITLE
Use Shiro authorization measures

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#618]
Our permission system is pretty complicated, and probably unnecessarily so

Could be simplified by taking advantage of Shiro authorization

http://shiro.apache.org/java-authorization-guide.html

**Comment by cmdcolin** [comment]
From a zoomed out point of view, the simply large number of methods that we have in permissionservice is overwhelming


    Boolean hasPermissions(JSONObject jsonObject, PermissionEnum permissionEnum) {
    def checkPermissions(JSONObject jsonObject, Organism organism, PermissionEnum requiredPermissionEnum) {
    Boolean checkPermissions(PermissionEnum requiredPermissionEnum) {
    Sequence checkPermissions(JSONObject inputObject, PermissionEnum requiredPermissionEnum) {
    Organism checkPermissionsForOrganism(JSONObject inputObject, PermissionEnum requiredPermissionEnum) {
    public static String getSequenceNameFromInput(JSONObject inputObject) {
    def getOrganismsForCurrentUser() {
    JSONObject copyUserName(JSONObject fromJSON, JSONObject toJSON) {
    String findUserName(JSONObject jsonTranscript) {
    User findUser(JSONObject jsonTranscript) {
    int findHighestEnumRank(List<PermissionEnum> permissionEnums) {
    PermissionEnum findHighestEnum(List<PermissionEnum> permissionEnums) {
    int findHighestEnumValue(List<PermissionEnum> permissionEnums) {
    Map<String, Integer> getPermissionsForUser(User user) {
    User getCurrentUser() {
    boolean isUserAdmin(User user) {
    boolean isAdmin() {
    Set<Organism> getOrganisms(User user) {
    List<Organism> getOrganisms(UserGroup group) {GroupOrganismPermission.findAllByGroup(group)) {
    static Collection<PermissionEnum> mergeOrganismPermissions(Collection<PermissionEnum> permissionsA, Collection<PermissionEnum> permissionsB) {
    public List<PermissionEnum> getOrganismPermissionsForUser(Organism organism, User user) {
    public List<PermissionEnum> getOrganismPermissionsForUserGroup(Organism organism, UserGroup userGroup) {
    public void setOrganismPermissionsForUser(List<PermissionEnum> permissions, Organism organism, User user) {
    public void setOrganismPermissionsForUserGroup(List<PermissionEnum> permissions, Organism organism, UserGroup group) {
    private String generatePermissionString(List<PermissionEnum> permissionEnums) {
    private String convertHashMapToJsonString(Map map) {

**Comment by nathandunn** [comment]
So, shiro is good, but it scratches the surface of what we are doing.  

For each *user* we track the specific permissions for:
- [ ] global 
- [ ] organism
- [ ] track (soon)

And of course, this is integrated with groups.

I agree, though, that it needs to be better / more concise.   If we can leverage shiro for this, that would be great, but I'm not holding my breath ;)   MInimally a code-review (attached to this case) would be a great idea.

**Comment by cmdcolin** [comment]
The problem that I see is our permission service has outgrown it's purpose, so it is not just checking permissions, it is also resolving the sequence IDs, organisms, updating userorganismpreferences, etc.


code review would be great.

I also think that it is pretty flexible, and even if shiro isn't the main platform we target, we should wrangle our permission system better.

**Comment by nathandunn** [comment]
:+1:

**Comment by cmdcolin** [comment]
Also our problems with resolving the organism might be improved through better routing/urlmapping

For example, it would be much better if we were just able to navigate to /Apollo2/Amel_4.5/jbrowse or /Apollo2/Amel_4.5/annotator for accessing an organism, but currently, we have to have a complicated url with the organism ID

**Comment by nathandunn** [comment]
I think that the organism separate / important issue.   Can you see if its not already an issue and if not, create one with the proposal?    Its true that Shiro path's might help with this, but would be good to see an entire proposal.

Thanks.

**Comment by cmdcolin** [comment]
I added this comment here https://github.com/GMOD/Apollo/issues/441

This is because simply using routes to define what organism is used is more effective than trying to retrieve the current organism from sessions and user preferences.

**Comment by cmdcolin** [comment]
Also, as long as this is a discussion thread, we are not doing very good testing of the permission system, because each of these methods has a specially coded scenario for the Environment.TEST

**Comment by nathandunn** [comment]
In general, it should be simplified in the entirety and moved to something other than Shiro, as well (whether on the client, or using the Grails server config, can't say)
