### ISSUE TITLE
icons not being cleaned up in RC2

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#619]
Not a showstopper . . but good to fix if an RC3.

![screen shot 2015-10-21 at 10 17 13 am](https://cloud.githubusercontent.com/assets/751274/10644325/fa70b472-77dc-11e5-94d2-1f84dd4d6048.png)

**Comment by cmdcolin** [comment]
Woops. Pushed a fix

**Comment by nathandunn** [comment]
thanks!

**Comment by nathandunn** [comment]
Test: 
Only a single "Incorrect login" is ever created with a single icon.

**Comment by monicacecilia** [comment]
:+1: :dancer:
