### ISSUE TITLE
password field missing

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#620]
![screen shot 2015-10-21 at 10 18 36 am](https://cloud.githubusercontent.com/assets/751274/10644360/239caffe-77dd-11e5-90fc-bf5056f2fa8c.png)

Admin should be able to change /edit a password

**Comment by nathandunn** [comment]
I was logged in as the wrong user . . user's can edit their own passwords.

**Comment by nathandunn** [comment]
admin's can still edit everyones

**Comment by cmdcolin** [comment]
But the normal users don't even see the user panel so they are not able to edit their password?

We should just make a normal grails gsp page for this i think

**Comment by nathandunn** [comment]
Good point.   You could also just put it in a dialog popup linked from the user-name since its already setup to do this and the user is already focused there.    When we review permissions, we can start thinking about moving things along.    

Nathan

**Comment by nathandunn** [comment]
Can you take a look at this?   I think that a dialog from MainPanel (turning the "username" at the top into a link) will fix this.

**Comment by cmdcolin** [comment]
Yep

**Comment by nathandunn** [comment]
Are you working on this one now?  . . otherwise I'll take a stab at it.

**Comment by cmdcolin** [comment]
Well what is the idea? Just a popup for changing password? Or external gsp?

**Comment by nathandunn** [comment]
Just a popup for now . .  I can do it quickly while I’m working on migration stuff, but if you think you can do it quickly no worries. 

Am on Skype if you need clarification.

Nathan

**Comment by nathandunn** [comment]
I just did a quick fix on this so I could tag it.  If you want to add more that is fine.    Its not much:

![screen shot 2015-10-21 at 5 14 23 pm](https://cloud.githubusercontent.com/assets/751274/10653729/358b3bd8-7817-11e5-9cf7-47e8545fb5bc.png)

**Comment by nathandunn** [comment]
Test: 
A non-admin user (one that can't see the "User" panel) can edit their own password with this ridiculous looking modal I made.

**Comment by cmdcolin** [comment]
I just did approximately the same  thing on a branch but this looks ok

**Comment by nathandunn** [comment]
Should I look at your branch or should I just go with this?

**Comment by cmdcolin** [comment]
it's really exactly the same except it uses regular gwt dialogbox instead of bootstrap box. I think yours is fine

**Comment by nathandunn** [comment]
Then we are good . . thanks.

**Comment by monicacecilia** [comment]
Password edits are not being saved. 

- User edited password
- User Saved changes
- received "Ok" notification
- logged out. 
- Tried to log back in, did not take new password (Invalid Login alert). Had to use old password.

I refreshed the cache every time. 
I also used a "user" role.

If logged in as "admin", password can be changed OK in self profile.

**Comment by nathandunn** [comment]
- [ ] need to clear out "repeat password" field, as well.

**Comment by nathandunn** [comment]
I did what @monicacecilia  and had worse luck:

![screen shot 2015-10-26 at 4 49 41 pm](https://cloud.githubusercontent.com/assets/751274/10745737/97bebd96-7c01-11e5-9813-f41ae42ff4b7.png)

Ack!

**Comment by monicacecilia** [comment]
Also, this is somewhat surprising: our regex for user generation may be too strict and special characters such as _ñ_ are not allowed on the email address, aparentemente.

Y si me da por escribir mi nombre en Español? Mónica Muñoz --> e.g.  <code>mónica.muñoz@email.com</code> ???!
no can't do :disappointed: 

![screen shot 2015-10-26 at 4 46 37 pm](https://cloud.githubusercontent.com/assets/1714621/10745697/4ba79252-7c01-11e5-81a8-934c42492f04.png)

**Comment by monicacecilia** [comment]
Some options for future reference, perhaps: 
https://tools.ietf.org/html/rfc6530
https://en.wikipedia.org/wiki/Email_address#Internationalization

**Comment by monicacecilia** [comment]
@nathandunn uh-oh!! :scream:

**Comment by nathandunn** [comment]
I’m using the default email restriction provided by grails:

http://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-email-address <http://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-email-address>

It gets messy, though. I would create another issue for this. 

Nathan

**Comment by monicacecilia** [comment]
Ok. -- the main issue remains, though, so I'm leaving open.

**Comment by nathandunn** [comment]
Several issues remain . . glad you caught them.  

Nathan

**Comment by nathandunn** [comment]
Two options to fix this:

1 - hide with  http://stackoverflow.com/questions/11519660/twitter-bootstrap-modal-backdrop-doesnt-disappear
2 - use a Dialog that is not a Modal object

**Comment by cmdcolin** [comment]
I am not able to change my password with the popup box currently

I change it and then I can still login with my old password and not the new one

**Comment by cmdcolin** [comment]
Also the "You do not have access to any organisms on this server" has a glass panel over it

**Comment by nathandunn** [comment]
Thanks for reporting . . .  So bizarre getting all of these glass panel errors when not an admin.

**Comment by nathandunn** [comment]
@cmdcolin   Non-admin users should be able to change their own now.   I'll look at more of the glass panel stuff.

**Comment by monicacecilia** [comment]
Hooray! :dancer: 
All issues clear.
