### ISSUE TITLE
Delete organism is greyed out after creating new organism in RC2

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#621]
As title says, even if organism has 0 annotations, the delete organism button always greyed out

**Comment by nathandunn** [comment]
Can you show me a screen shot?  I'm not seeing it.  Are you sure that your user is a full global admin?

**Comment by cmdcolin** [comment]
Weird. It went away when I refreshed page. 

I can't reproduce

**Comment by cmdcolin** [comment]
Closed for now

**Comment by cmdcolin** [comment]
Actually it happens if you create a new organism. You can't delete an organism you just created apparently

**Comment by nathandunn** [comment]
alright . . I'll take a look . .. all of the migration stuff seems to be working . . so this and the password are all that is left for RC3

**Comment by cmdcolin** [comment]
Ya. This is a minor issue. Just surprising.

**Comment by cmdcolin** [comment]
Updated title to reflect issue

**Comment by nathandunn** [comment]
Test:  Create or delete an organism and observe that you can still edit it (or other organisms)

**Comment by monicacecilia** [comment]
:+1: Created and deleted organisms, behaviour as expected. First dancer of the day! :dancer:
