### ISSUE TITLE
make organism, groups, users tabs more consistent

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#622]
all three of these tabs should function / look the same.  Group panel is probably closest to what should be there, but we should talk briefly.   Important points:

1 - "add new" should be on the top"
2 - we should use a save button (which should be of type primary, and icon)
3 - ideally "new" things should come in with a popup
4 - details panel should be hidden if nothing selected
5 - they should all have a search

**Comment by cmdcolin** [comment]
I don't know what you think about this, but I almost think we should just move the organism, groups, and users tabs to separate GSP pages outside the side panel. They are basically admin functions.

Then we can focus on annotator panel features with the annotator panel instead of admin functions.

**Comment by nathandunn** [comment]
I think that is also a good though as well and should be pretty easy.   I think that it has the same issue WRT to consistency (which format makes sense).  But doing something like this with angularjs / bootstrap simplifies things immensely and reduces the amount of code.    We should definitely discuss it.  

Nathan
