### ISSUE TITLE
Generic list/set operations (and display) of entities with genomic coordinates

### ISSUE THREAD

**Issue by selewis** [GMOD/Apollo#624]
Lists - we need a generic component for handling lists of entities that have genomic coordinates. Examples of an 'entity' include a blast/blat alignment, but may also be a gene, or transcripts, or any feature, or a SNP, or a repeat unit, or just a coordinate pair, strand, and reference that the user has provided.

@nathandunn note:  Some of this is redundant / finished in #525 . 
- [x] A bookmark can be uniquely identified (its stored in the database uniquely, but the display name should also be unique)
- ~~A user can name a list~~ handled in #1207
- [x] A user can maintain multiple lists (persistently) this is already working
- ~~A user can share a list (create a URL)~~ handled in #1207
- ~~A user can create new lists by set operations on 1 or more existing lists: selecting individual items (subset), intersection with another list(s), union with another list(s), XOR with another list(s).~~ moved to #1217
- [x] The display of the these lists is independent of the list itself (Model & View!)
- [x] Lists views can be sub-classed. (For example, a list can be duplicated, and the duplicate can be further modified). 
- [x] Selecting a list item can center the genomic display on that location.  

See also https://github.com/GMOD/Apollo/issues/585

**Comment by nathandunn** [comment]
@selewis I'm kind of interpreting these as an enhancement to the concept of "track" (or where I'd like to see tracks go) and overlaps bookmark (a set of genomic locations) a bit.   Exceptions to this are:
1 - "lists" (we need a better name) can be stored much like a bookmark can (planned)
2 - a generated "list" can be persisted (see 1)
3 - **a "list" is both a set of locations and a set of tracks**

**Comment by nathandunn** [comment]
There is some redundancy with #525 but some good additional data.

**Comment by nathandunn** [comment]
Renaming "list" to what I'm calling "Bookmark" on the interface and back-end, which is just a region with an annotated indication of "projection" or "folding" (e.g., padding, reverse compliment, transcript or exon etc.).

**Comment by nathandunn** [comment]
Handling some of this in #1207 .  Needs some clarification on:

> A user can create new lists by set operations on 1 or more existing lists: selecting individual items (subset), intersection with another list(s), union with another list(s), XOR with another list(s).

@selewis 

Can definitely create unions and select individuals to create lists, but not sure how this would work with an XOR.

**Comment by monicacecilia** [comment]
After lengthy discussion during ApolloDevs call, we decided to change it back to 'Lists'. 
Moved item number 5 to issue _#1217 Create new lists by set operations on 1 or more existing lists_.

**Comment by nathandunn** [comment]
@monicacecilia  Can this be closed now?

**Comment by monicacecilia** [comment]
@nathandunn let's run a demo of each of these functions and then we'll close it.
