### ISSUE TITLE
The username won't display in Apollo sometimes 

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#625]
On a "fresh" install of 2.0.1, you get the username nicely displayed in the button area

![t1](https://cloud.githubusercontent.com/assets/6511937/10738573/087bf01a-7be6-11e5-8704-ee202cdba49f.png)

In a version upgraded from 2.0.0, the username will not be displayed

![t2](https://cloud.githubusercontent.com/assets/6511937/10738577/0be480e6-7be6-11e5-8dbf-26712a14cfc3.png)

Might be indicative of underlying problems, haven't tracked down issue yet

**Comment by nathandunn** [comment]
I've seen that as well . . not sure what causes it, but it is still functional, so I don't think its a showstopper.  You could try trashing the cache, logging out and logging in and see where you get.

**Comment by nathandunn** [comment]
I think that this is a bootstrap "space" issue, but not sure as it happens so randomly.  This instance was upgraded from 2.0.0 to 2.0.1 and it shows up fine.   It is pretty random whether or not it shows the "username" text.  Either way, it is still functional, so I'm going to punt it to 2.0.3.

![screen shot 2016-01-21 at 11 33 07 am](https://cloud.githubusercontent.com/assets/751274/12491981/cc283772-c032-11e5-8453-cc00b94bf667.png)

**Comment by nathandunn** [comment]
Actually, I wonder if it is over sub-stringing the name . . . I'll take a look.

**Comment by nathandunn** [comment]
I mean it is doing a sub-string incorrectly based on the space allowed . . .

**Comment by monicacecilia** [comment]
Thanks for checking & updating :+1:

**Comment by nathandunn** [comment]
seeing this on all of the icebox instances, except training (2.0.0) . . . not seeing this on my localhost at all . . . I'll try to update staging and see what I get.

**Comment by nathandunn** [comment]
Very weird . . . .  I saw this for a fleeting second locally, but on hide / show it disappears again.   I think it occurs if the user is already logged in (e.g. rememberme) and don't go through the login / logout screen.   I think I have a fix for that, but we'll see.

**Comment by nathandunn** [comment]
I'm going to try testing this on staging.

**Comment by monicacecilia** [comment]
Yes, please! Thank you. :+1:

**Comment by nathandunn** [comment]
Not sure why it closed itself . . . didn't seem to fix, sadly:

<img width="249" alt="screen shot 2016-01-22 at 12 12 44 pm" src="https://cloud.githubusercontent.com/assets/751274/12521856/02b72918-c102-11e5-8c16-4227c0484234.png">
