### ISSUE TITLE
Logging in from 'Public Genomes' does not allow user to return to Annotator Panel

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#626]
If I use the new option to 'Browse Public Genomes' in the 'Login' window, 
![screen shot 2015-10-26 at 1 40 22 pm](https://cloud.githubusercontent.com/assets/1714621/10741913/782d3d82-7be7-11e5-941e-fc1af44a724b.png)

and then I choose to 'Login', I am not able to see the 'Annotator Panel' view, unless I go back to the previous window and refresh the 'Login' page. 

Solution: 
- [ ] Create menu option to 'Return to 'Annotator Panel' view', or something similar.

**Comment by nathandunn** [comment]
I will add something.  If you switch organisms on the upper left hand side it will add it back.  I'll put something in the view menu to do the same.  

Nathan

**Comment by nathandunn** [comment]
Putative solution . . . going to have Colin review / come up with something better:  

![screen shot 2015-10-26 at 4 39 31 pm](https://cloud.githubusercontent.com/assets/751274/10745554/252e1e9e-7c00-11e5-83b6-2e2d48b6e34d.png)

**Comment by nathandunn** [comment]
Quick chat with @monicacecilia   . . I will try to get it up where "full-screen view" is . . barring that, I think we'll leave it in the "View" area as I think that tools is moving into the annotator panel.

**Comment by nathandunn** [comment]
![screen shot 2015-10-27 at 2 45 10 pm](https://cloud.githubusercontent.com/assets/751274/10773604/902c49dc-7cb9-11e5-95c0-dde3d7d183ee.png)

This takes you back to the "annotator view" 

and on the annotator view you see:

![screen shot 2015-10-27 at 2 47 30 pm](https://cloud.githubusercontent.com/assets/751274/10773622/aaa420fa-7cb9-11e5-9b52-b9b14c5d473a.png)

**Comment by monicacecilia** [comment]
oooooh, yay! :+1:

**Comment by monicacecilia** [comment]
:dancer:
