### ISSUE TITLE
Automatic 'Enter New Tag' and 'email' on 'Attributes' fields.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#627]
These automatically generated Tags appear while working a gene model:

![screen shot 2015-10-26 at 3 13 07 pm](https://cloud.githubusercontent.com/assets/1714621/10744030/45dc09be-7bf4-11e5-807a-c9f2d787e77d.png)

After trying to erase them Apollo renamed them to _undefined_. In both cases, the value is the username. 

This happened while testing the GOLR and PMID features.

**Comment by nathandunn** [comment]
from @monicacecilia  : It happened while adding PMID and GO

**Comment by nathandunn** [comment]
@monicacecilia   I couldn't reproduce this locally or on staging.  Maybe getting into a weird error state?

**Comment by monicacecilia** [comment]
:dancer:
