### ISSUE TITLE
Merge and split fails to reproduce the correct results

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#628]
On group 1.10 if I add GB40770-RA-00001 and GB40769-RA-00001 (twice) and then I merge one of the 770 isofrorms and 769 isoforms it works . . and then when I split it it fails.   To be fair, I think this wasn't working at all in previous versions:

![screen shot 2015-10-26 at 4 09 31 pm](https://cloud.githubusercontent.com/assets/751274/10745103/01f485b6-7bfc-11e5-92ae-262cad7bda1a.png)

**Comment by nathandunn** [comment]
When I delete it looks like not all of the sub-features are properly being removed.: 

![screen shot 2015-10-26 at 4 11 50 pm](https://cloud.githubusercontent.com/assets/751274/10745132/4d4d0178-7bfc-11e5-8764-8def91a51f7b.png)

**Comment by nathandunn** [comment]
@deepakunni3   I marked this as ready . . that was correct?

**Comment by deepakunni3** [comment]
yes, it is ready.

**Comment by nathandunn** [comment]
:+1:

**Comment by monicacecilia** [comment]
Able to split and merge with expected behavior, and able to delete features after that as well.  :dancer:
