### ISSUE TITLE
checkPermissions in deleteUser (UserController.groovy)

### ISSUE THREAD

**Issue by ifishlin** [GMOD/Apollo#631]
Hi

I guess there is a bug here, 
Shouldn't there be a hasPermissions instead?

Because in updateUser and createUser, they all check authority by hasPermissions.

thanks

**Comment by nathandunn** [comment]
I agree . . though in the end I think "hasPermissions" calls "checkPermissions" which throws an exception or returns a non-null value which evaluates to "true" in groovy.   However the hasPermissions does the login properly, which is correct.  Thanks for catching this!
