### ISSUE TITLE
remove alternate "hover" css on tables from #601

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#632]
Originally reported in #601 .  

The one thing that bothers me is this effect of _a highlight over a highlighted name_

If you select a user it looks like this: (and notice I am hovering over a different user)
![screen shot 2015-10-26 at 5 04 08 pm](https://cloud.githubusercontent.com/assets/1714621/10746000/bc60dcc2-7c03-11e5-916b-e746826045b9.png)

But when you hover over the selected user, this highlight appears and the name turns almost invisible. It's inconvenient: 

![screen shot 2015-10-26 at 5 03 55 pm](https://cloud.githubusercontent.com/assets/1714621/10745994/b14bbeec-7c03-11e5-8d1c-0a5e9ffa5b4b.png)

Hovering is good . . but it allows two selection models.   I don't think we want the keyboard selection:

```           dataGrid.setKeyboardSelectionPolicy(HasKeyboardSelectionPolicy.KeyboardSelectionPolicy.DISABLED);
        dataGrid.setSkipRowHoverStyleUpdate(true);
        dataGrid.setSkipRowHoverCheck(true);
        dataGrid.setSkipRowHoverFloatElementCheck(true);
```

This needs to be propagated to ALL the panels.

**Comment by deepakunni3** [comment]
@nathandunn The bug still persists. If I click on a user, in the UserPanel, and then hover over the entry the text becomes white, as showing in the images above.

**Comment by nathandunn** [comment]
@deepakunni3  I think I'm going to merge it anyway.  Its actually usable now with both selection modes.  I changed the highlight color to black so its not as jarring.
