### ISSUE TITLE
delete_annotations_from_organism.groovy deletes annotations from all organisms

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#636]
Procedure

I added two different organisms (different species)

Then I run the delete_annotations_from_organism.groovy script with -organismname as one of their names (or ID, doesn't matter)

Then the annotations are deleted from both organisms

Cross-ref #539

**Comment by cmdcolin** [comment]
Looks like line 47 of the OrganismService doesn't check organism here


session.createSQLQuery("delete from feature where not EXISTS (select 'x' from feature f join feature_location fl on fl.feature_id=f.id)").executeUpdate()

**Comment by nathandunn** [comment]
I'm not checking organism because it is deleting any organism without a feature location (from the previous step).   I'm not sure that there is a feature without a feature location that could be considered valid, but let me know if you know so and we can change it.

**Comment by cmdcolin** [comment]
See pull request for possible solution

**Comment by nathandunn** [comment]
Looks good!
