### ISSUE TITLE
Branding: WebApollo2 -> Apollo

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#638]
I'm writing up an API client library in python and some associated Galaxy tools for interacting with WebApollo servers. I'd like to know what the official name is that should be used everywhere. The repository is named "Apollo" and that's what's at the head of the readme file, however "WebApollo" is used extensively in code and variables in the docs, and "WebApollo2" is even used in places. 

Is there a preference for which name I should use in my user-facing code?

**Comment by nathandunn** [comment]
We’ve been trying to go back to using “Apollo” everywhere.   Though, I think you are right that we need to clean up the doc to reflect that better. 

@cmdcolin . . do you have time to take a look at this? 

Nathan

**Comment by erasche** [comment]
@nathandunn okay, great. Thanks! I'll do my best to be consistent about that as well.

**Comment by nathandunn** [comment]
Or maybe this is a @monicacecilia  thing?

**Comment by monicacecilia** [comment]
Thanks for the note @erasche 

It should be __Apollo__ everywhere. 

@cmdcolin If the name of the ReadTheDocs page could be changed from http://webapollo.readthedocs.org/en/latest/ to http://apollo.readthedocs.org/en/latest/ that would be ideal. 

I have tried to go through documentation in the repo and update to Apollo everywhere possible. I haven't gotten to every place yet.

**Comment by erasche** [comment]
Thanks all! :)
