### ISSUE TITLE
Recent changes page has several bugs

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#642]
Currently, the date sort is not working, and also the number of results returned per page is inconsistent

![screenshot-bovinegenome org 8080 2015-10-29 10-58-24](https://cloud.githubusercontent.com/assets/6511937/10823961/1eaa8f5c-7e2c-11e5-8b64-318cf1ad9fc3.png)

**Comment by cmdcolin** [comment]
Also noted: all organisms are grouped together. Probably should be able to filter by organism or something.

**Comment by nathandunn** [comment]
Note #488 . . . definitely needs to be redone.  I would probably close this in favor of that one.

**Comment by cmdcolin** [comment]
Okay. Well, during call I said that I could take a stab at this.

Personally think a simple page is useful with added features perhaps being extended over time.

**Comment by nathandunn** [comment]
Doing it with AngularJS isn’t hard . . but it is a little different.   The performance will be better with doing Ajax and you use pretty identical MVC paradigms.  Worth learning unless you have to get something working quickly (and the changes you wanted were small).  

Nathan

**Comment by cmdcolin** [comment]
So I sort of observed how the current recent changes page was centered on the FeatureEvents, which is maybe sort of ideal for listing the details of all the FeatureEvents, but due to how buggy it is, I made a new page that is centered around Features.

The new page is usable for basic things like

- sorting by annotation owner
- sorting by last updated
- sorting by feature types


Example

![ti](https://cloud.githubusercontent.com/assets/6511937/10954319/4d70b8e4-8312-11e5-87ce-ecebfad7c9c8.png)

**Comment by nathandunn** [comment]
Looks good . .. if you might want to add additional filters at some point (as needed), but it is probably fine.  

My guess is that this code is fairly modular . . . if so can probably be pulled in to 2.0.1 via a pull request.  

Does the link go to the annotator? 

Also, instead of CV Term you might want to have type (and then link to go).    Overall looks good, though.

**Comment by cmdcolin** [comment]
Yup, link goes to annotator. I added a couple more filters. Pull request launched!

**Comment by monicacecilia** [comment]
Lots of improvement on this. Thanks to you both. :dancer:
