### ISSUE TITLE
Get single user/group information from web api

### ISSUE THREAD

**Issue by ifishlin** [GMOD/Apollo#643]
Hi

Could we have a web api for retrieving specific user/group information?
In some cases, I need do it without using loadUser/loadGroups that slow down performance.

thanks

**Comment by cmdcolin** [comment]
We have getOrganismPermissionsForGroup and getOrganismPermissionsForUser

Does that help?

This fits the need of loading the info for a specific user or group.

**Comment by nathandunn** [comment]
We could just add a param that is a list of users that can be used to filter results of loadUsers without fetching all of them.   This way we are only modifying the original methods (loadUsers, loadGroups).  

Nathan

**Comment by ifishlin** [comment]
I would like to have a single record, like

[{"organismPermissions":[{"userId":15,"permissions":"[]","organism":"MOUSE"},{"userId":15,"permissions":"[]","organism":"PYU"}],
 "availableGroups":[{"name":"ISD"},{"name":"KSD"}],"lastName":"Lin","username":"ifishlin324@gmail.com","userId":15,"role":"ADMIN","firstName":"Fish","groups":[]},]

Because loadUser() always return all users information, it slow down when we have a lot of users.
I tested loadUser() where 1000 users on Apollo, it took about 5 seconds to finish every time.

**Comment by ifishlin** [comment]
Yes, I think add a param will be great.
Could the params be userId or username for loadUsers, and groupId or groupname for loadGroups? (Either one when I call it)

**Comment by cmdcolin** [comment]
I think #644 will address this

**Comment by nathandunn** [comment]
Looks good . . . pushed to master.

**Comment by ifishlin** [comment]
Hello

I realize this function doesn't work in version 2.0.1
I thought there maybe some problem when you tried to fix the security issues.

Can I have it back ? thanks

**Comment by ifishlin** [comment]
I got a "{"error":"java.lang.Integer cannot be cast to java.lang.Long"}" in version 2.0.1,
and another errormsg {"error":"Cannot get property 'id' on null object"} in instance build by Chris.( I think it's quite new)

**Comment by nathandunn** [comment]
@ifishlin   You should be able to pass in a "groupId" or userId" for the appropriate method when doing loadUsers or loadGroups:

http://icebox.lbl.gov/Apollo2-1/WebServices/

It might be in the most recent release, though . . but it looks like its been in there since Oct. 30:

https://github.com/GMOD/Apollo/releases/

. . . . now just seeing your error .. one minute .

**Comment by nathandunn** [comment]
Is this for "loadUsers?"  . . . is there any other information you can give (what you passed in, etc.)?

**Comment by ifishlin** [comment]
I use two curl command to test it.

curl -b cookies.txt -c cookies.txt -e "http://10.11.210.66:8085"  -H "Content-Type:application/json" -d "{'username': 'R2D2@i5k.org', 'password': 'demo'}" "http://10.11.210.66:8085/apollo/Login?operation=login"

curl -b cookies.txt -c cookies.txt -e "http://10.11.210.66:8085" -X POST --header "Content-Type:application/json"  --data "{"userId" : 76}" http://10.11.210.66:8085/apollo/user/loadUsers

**Comment by ifishlin** [comment]
It actually worked when I pull the master branch at Oct 30.
but I pull a branch 2.0.1 today, and it doesn't work

**Comment by nathandunn** [comment]
I'll take a look with those curl commands . . . thanks for reporting.

**Comment by ifishlin** [comment]
Hello

I have the source code that downloaded around Oct 30
and it works well in this version. 

Hope it helpful.

[GroupController.groovy.txt](https://github.com/GMOD/Apollo/files/49013/GroupController.groovy.txt)
[UserController.groovy.txt](https://github.com/GMOD/Apollo/files/49014/UserController.groovy.txt)

**Comment by cmdcolin** [comment]
Woops. I am pushing a fix here shortly

Thanks for the details

**Comment by nathandunn** [comment]
Let me know when you have something pushed to master and I’ll retest / retag.  

Thanks.

**Comment by ifishlin** [comment]
Hello

I'm testing new version of 2.0.1
and when I used loadUser for someone who don't have permission for any organisms(it may be a new account), it return "{"error":"User does not have permission for any organisms."}"

but, I just want the information of the user. Could it return the user info as usual JSON format?

**Comment by nathandunn** [comment]
The username / password combination should be sent with your admin user credentials.   The userId should be the userId of the user you are trying to pull.   

The web services work a bit different.   You don't need to call "Login" . . but you do need to pass in your credentials (why https is recommended for a production environment) for each request unless you can bind the session.  

This is what I did for a user with no permissions:

```
 curl --header "Content-Type:application/json" --data "{'userId' : 5953,'username':'ndunn@me.com','password':'demo'}" http://localhost:8080/apollo/user/loadUsers
```

which returned:
```
[{"organismPermissions":[{"userId":5953,"permissions":"[]","organism":"Honeybee"},{"userId":5953,"permissions":"[]","organism":"Yeasta"}],"availableGroups":[],"lastName":"Permissions","username":"no@nope.com","userId":5953,"role":"USER","firstName":"No","groups":[]}]%      
```

**Comment by ifishlin** [comment]
I'm curious about What is different between "call Login first, then call loadUser" and call loadUser directly with username/password?

In many cases, they both work well.

**Comment by nathandunn** [comment]
They should work fine.  It grabs the cookie and passes it in, mimicking the session.  I tried it this way and got the same result (also working).

Can you pull the JSON for your "admin" user?  My guess is that that is the problem. 

```
curl -b cookies.txt -c cookies.txt -e "http://localhost:8080" -H "Content-Type:application/json" -d "{'username': 'ndunn@me.com', 'password': 'demo'}" "http://localhost:8080/apollo/Login?operation=login"
```

```
curl -b cookies.txt -c cookies.txt -e "http://localhost:8080" -X POST --header "Content-Type:application/json" --data "{"userId" : 5953}" http://localhost:8080/apollo/user/loadUsers
```

```
[{"organismPermissions":[{"userId":5953,"permissions":"[]","organism":"Honeybee"},{"userId":5953,"permissions":"[]","organism":"Yeasta"}],"availableGroups":[],"lastName":"Permissions","username":"no@nope.com","userId":5953,"role":"USER","firstName":"No","groups":[]}]
```

**Comment by ifishlin** [comment]
hello

Sorry for bothering you continuously, 
Could I also use 'email' as primary key to retrieve data through loadUser?
As I know, email is also unique in Apollo.

Usually, user don't know there userId, they only know their username(email)

**Comment by nathandunn** [comment]
I agree.  I think that makes more sense.  

@cmdcolin . . . do you want to add this or should I? 

Nathan

**Comment by cmdcolin** [comment]
We can certainly add the username/email lookup, but I would like to say one thing here:

We really need to take a minute to "design" the API, because we have sort of "grown" it as it fits our needs but we're gonna have to kick ourselves for introducing incompatibilities and such

**Comment by nathandunn** [comment]
True . . . . but in this case what @ifishlin is asking is a pretty well-established pattern and this instance (just using the database id instead of allowing for the username / group name, etc.) is more exception than rule.

**Comment by ifishlin** [comment]
I totally agree what Colin concern.
you should not expand your API to fit all customer's demands.
but I think provide API with getByPK is not such unreasonable.

I can truly do what I need by checking userlist, one by one to get who I interested.

**Comment by nathandunn** [comment]
Using the email as another key (which we already do in other places) makes a lot of sense and we’ve done it other places.   

Other users have asked for the same thing.    The email is a better key in case you don’t have explicit database access or don’t want to do two queries.  

Agreed, that at some point we will want to review our designs.

**Comment by nathandunn** [comment]
@ifishlin   This worked for me . . .let us know if this works.

**Comment by nathandunn** [comment]
Closing for now.   Please re-open or create another issue if there is something missing.
