### ISSUE TITLE
Sequence display within annotation won't update immediately when 'move to opposite strand' is used

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#645]
Hi y'all,

An annotator brought this (fairly minor) bug to our attention: When you create a model, then invoke the 'move to opposite strand' function, the nucleotide sequence that is displayed inside the model won't switch to the opposite strand until you refresh the browser. This happens in both WA1 and WA2. 

Monica P

**Comment by nathandunn** [comment]
I'm not seeing this.   If you try it on icebox do you see it?   If you have a reproducible example data I can see what is going on.

**Comment by mpoelchau** [comment]
Sure. Here's the model before switching to the opposite strand (excuse my super-sophisticated image markup): 
![seq_1](https://cloud.githubusercontent.com/assets/5487172/10853423/91a420fc-7efb-11e5-942a-07c6d93afaac.png)

Here's the same model after switching to the opposite strand. The sequence displayed within the model hasn't changed:
![seq_2](https://cloud.githubusercontent.com/assets/5487172/10853429/9c6bde6c-7efb-11e5-92ca-940cd128f1da.png)

Here's the model after refreshing the browser. The sequence within the model has been updated to the correct strand:

![seq_3](https://cloud.githubusercontent.com/assets/5487172/10853435/a4d1a88e-7efb-11e5-8f83-4a39051a5c44.png)

**Comment by nathandunn** [comment]
I see . . you shouldn't have to refresh.  If you click off and then back on it will fix the alignment.   However, you shouldn't have to do that.  Its probably just missing a call in the "update" code.

**Comment by nathandunn** [comment]
@cmdcolin  Not high priority, but was wondering if there was a way to "reselect" a selected annotation that could be called on an update.

**Comment by cmdcolin** [comment]
Just saw this message. Can check into it

**Comment by nathandunn** [comment]
thanks . .. I figured (hoped) it would be an easy fix for you

**Comment by monicacecilia** [comment]
@deepakunni3 would you mind please looking into this to see if it is still showing up in the current version? We'll go from there. :) Thanks!

**Comment by deepakunni3** [comment]
Tried to reproduce this issue.

If I zoom to base level, click an annotation and flip its strand then the sequence displayed remains the same. But if I were to deselect the annotation and click on it again the sequence is updated. i.e. there is no need to do a page refresh. Perhaps this was fixed along the way.

**Comment by nathandunn** [comment]
I think the idea would be to trigger the refresh without unclicking and re-clicking. 

Looking for ```AnnotTrack.js```

**Comment by nathandunn** [comment]
@monicacecilia  Seems to remember other cases where this is an issue.

**Comment by monicacecilia** [comment]
- 👍  to trigger refresh (drawing) after function to 'move to opposite strand'.

**Comment by nathandunn** [comment]
@monicacecilia types: we need to trigger this refresh (drawing) after function to 'move to opposite strand'.

**Comment by nathandunn** [comment]
somehow in flip strand, need to re-trigger renderResidue / renderTranslation on update.    Probably the easiest it to call "AnnotTrack::selectionRemoved / selectionAdded) when it comes back, if it was selected at all.   Probably triggering wrong thing right now.

**Comment by monicacecilia** [comment]
This is not yet working. See screen capture. This is after I moved to opposite strand (from reverse to forward). The color of the exon correctly changed from dark blue (non coding) to purple (+1 frame), but the sequence is still the one displayed in the reverse strand. It only clears up after refresh. 
![screen shot 2016-12-01 at 5 16 03 pm](https://cloud.githubusercontent.com/assets/1714621/20819597/393e9ce8-b7ea-11e6-9b15-544b3d7c2d92.png)

**Comment by nathandunn** [comment]
Ahh . . . because if you reverse-strand when the exon is selected, we need to detect the changed strand (and change it) on the transcript, not the exon!

**Comment by monicacecilia** [comment]
Brilliant. It now refreshes the sequence after 'Move to opposite strand'.
