### ISSUE TITLE
json format to call updateOrganismPermission()

### ISSUE THREAD

**Issue by ifishlin** [GMOD/Apollo#647]
Json format for calling updateOrganismPermission is a little unclear to me.
for example, I want increase permission(write/read) of CAT and DOG into group GROUP_A

Should I sent json 
(1). as a big package for two organisms
[[groupId = GROUP_A'id, name = GROUP_A, organism=CAT, administrator=false, write=true, read=true, export=false],[groupId = GROUP_A'id, name = GROUP_A, organism=DOG, administrator=false, write=true, read=true, export=false]]

(2). or use separate call for each organism
[groupId = GROUP_A'id, name = GROUP_A, organism=CAT, administrator=false, write=true, read=true, export=false]
[groupId = GROUP_A'id, name = GROUP_A, organism=DOG, administrator=false, write=true, read=true, export=false]

thansk

**Comment by cmdcolin** [comment]
I would just use two API calls in this case, not really designed for bulk, but if necessary we can design a bulk app. Could see where this might be useful.

**Comment by nathandunn** [comment]
@cmdcolin  built a script with good examples around it here:

https://github.com/GMOD/Apollo/blob/master/docs/web_services/examples/groovy/alter_user_groups_and_permissions.groovy

I'll close this for now unless we need to do a change . . and then we can re-open it.
