### ISSUE TITLE
AnnotatorController not secured or annotated 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#649]
need to add web services for the AnnotatorController

**Comment by nathandunn** [comment]
- [x] loadLink
- [x] index
- [x] adminPanel
- [x] updateFeature
- [x] updateFeatureLocation
- [ ] findAnnotationsForSequence
- [ ] version
- [ ] getAppState
- [ ] setCurrentOrganism
- [ ] setCurrentSequence
- [ ] notAuthorized
- [ ] report
- [ ] detail

**Comment by nathandunn** [comment]
Keep in mind that this this checkin: https://github.com/GMOD/Apollo/commit/aa409d52ae4706acb75e68edcaed6ba8b6aa261b

was inadvertently on master.

**Comment by cmdcolin** [comment]
This will need to remain open until I can validate a couple of things.

In particular, the change in setCurrentSequence et al will possibly trigger authentication failures during session timeouts which I want to monitor

**Comment by nathandunn** [comment]
sounds good

**Comment by nathandunn** [comment]
Closing as no further problems encountered.  Session trigger issues are unrelated.

**Comment by monicacecilia** [comment]
:+1:
