### ISSUE TITLE
Non-canonical splice site does not refresh after redoing a merge operation

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#654]
Very awesome work on #633 

One small bug appears to exist with some non-canonical splice sites during split and merge operations though

Error text:

    | Error 2015-11-03 14:39:46,047 [Actor Thread 8] ERROR apollo.FeatureService  - CV Term not known non_canonical_five_prime_splice_site for CV sequence
    2015-11-03 14:39:46,048 [Actor Thread 8] WARN  apollo.FeatureService  - Feature type not set for [name:non_canonical_five_prime_splice_site, cv:[name:sequence]]
    | Error 2015-11-03 14:39:46,222 [Actor Thread 8] ERROR apollo.FeatureService  - CV Term not known non_canonical_three_prime_splice_site for CV sequence
    2015-11-03 14:39:46,222 [Actor Thread 8] WARN  apollo.FeatureService  - Feature type not set for [name:non_canonical_three_prime_splice_site, cv:[name:sequence]]

Apparently this is the alternativeCvTerm instead of the main cvTerm

I imagine FeatureService should match on the alternativeCvTerm in this case

**Comment by cmdcolin** [comment]
Procedure

- Take two transcripts
- Merge them (produce some non-canon splice sites)
- Split them again
- Then undo, which should re-merge, and the expected behavior is that the non-canon splice sites reappear as well

**Comment by nathandunn** [comment]
FYI @deepakunni3   . .  nothing to do here . . just to be aware

**Comment by cmdcolin** [comment]
This is pretty much attached to #633 so I'll close this for now

**Comment by cmdcolin** [comment]
It is attached to #633 in an interesting way, which is the fact that it has to use the alternativeCv presumably since the featureEvents stored as JSON use that alternativeCv (also used on client side) but in general this is fixed
