### ISSUE TITLE
Feature lastUpdated field not updated when a change is made

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#657]
My expectation was for this field to be updated for an annotation change, such as setExonBoundaries, but was not updated.

**Comment by nathandunn** [comment]
That would only update the feature location on the exon and anything else that changed as a result:

http://stackoverflow.com/questions/11211367/update-lastupdated-field-in-parent-domain-class-in-grails

The FeatureEvent history should capture that.   Conversely, there is support for the AuditLogging plugin:

https://grails.org/plugin/audit-logging

but you'll still have to traverse the heirarchy to come up with the view you want.

**Comment by cmdcolin** [comment]
The gene boundaries are updated by a change to an exon boundaries....

**Comment by nathandunn** [comment]
Are those feature locations updated?   

It is basically a timestamp for an update on that database row changed.  If the feature name / description changes it *should* issue an update (maybe it doesn’t, but it has in the past).  If associated data changes (e.g., the feature location, or a property), it won’t trigger an update on the feature itself.  

Nathan

**Comment by cmdcolin** [comment]
Well in the case of a setExonBoundaries call, neither the Exon,Transcript,CDS,or Gene have their lastUpdated changed.

**Comment by nathandunn** [comment]
Are the feature locations changed?

Nathan

**Comment by cmdcolin** [comment]
Well yes they are but they do not have lastUpdated markers.

Other operations besides setExonBoundaries do perform setLastUpdated, so I thin this particular case (setExonBoundaries) should just include it too

**Comment by nathandunn** [comment]
What are you trying to accomplish that touching all up-stream features would be necessary?   This isn’t a particular reliable or efficient way to do it.  Its more for managing transactions and data integrity.  I think that the feature event code should handle that case.  If it doesn’t it should probably be fixed. 

Nathan
