### ISSUE TITLE
Silent failure on bad email

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#658]
```
webapollo2_1 | grails.validation.ValidationException: Validation Error(s) occurred during save():
webapollo2_1 | - Field error in object 'org.bbop.apollo.User' on field 'username': rejected value [hxr@local.host]; codes [org.bbop.apollo.User.username.email.error.org.bbop.apollo.User.username,org.bbop.apollo.User.username.email.error.username,org.bbop.apollo.User.username.email.error.java.lang.String,org.bbop.apollo.User.username.email.error,user.username.email.error.org.bbop.apollo.User.username,user.username.email.error.username,user.username.email.error.java.lang.String,user.username.email.error,org.bbop.apollo.User.username.email.invalid.org.bbop.apollo.User.username,org.bbop.apollo.User.username.email.invalid.username,org.bbop.apollo.User.username.email.invalid.java.lang.String,org.bbop.apollo.User.username.email.invalid,user.username.email.invalid.org.bbop.apollo.User.username,user.username.email.invalid.username,user.username.email.invalid.java.lang.String,user.username.email.invalid,email.invalid.org.bbop.apollo.User.username,email.invalid.username,email.invalid.java.lang.String,email.invalid]; arguments [username,class org.bbop.apollo.User,hxr@local.host]; default message [Property [{0}] of class [{1}] with value [{2}] is not a valid e-mail address]
```

apparently `localhost` and `local.host` are rejected as invalid domains. The interface however:

- fails to login
- fails to display a message
- refreshes unexpectedly back to login box

**Comment by nathandunn** [comment]
Just to double-check, this is during the registration phase?

**Comment by nathandunn** [comment]
@cmdcolin  Can you take a look at this?  I think its just what we did for the Login Box (handling errors properly and adding bootstrap).

**Comment by nathandunn** [comment]
@erasche   You *should* be able to refresh the server and you'll see the  reset or restart the server and it will give you another opportunity to reset with the right email.  Or just try opening in an anonymous  window.

 Worst-case you can "reset" you can just drop and re-create the database and it should get you back into that state so you can register with a proper email, but that should not be necessary.

Anyway, I think I have a fix for it (so nvmd @cmdcolin )

**Comment by erasche** [comment]
It (was) only during login, double checking that this is still an issue on master, I was behind a few weeks of development.

**Comment by erasche** [comment]
Yes, okay, I'm on 82dbe0607195e099d51ce14129dde5160609b247 and the admin registration form is the "old" style whereas the look of the basic login form has been updated and responds nicely with "bad password" and other such hints.

**Comment by nathandunn** [comment]
Okay . . so the registration is still a problem?   I think I have a quick fix for it.

**Comment by cmdcolin** [comment]
Should be ok. It's still not gonna accept user@localhost as a email though, FYI, even if that might technically be a valid email address. Wants a domain

**Comment by erasche** [comment]
Okay, great. I usually use `local.host` or `local.domain` in that case then. Thanks for fixing this! :)

**Comment by nathandunn** [comment]
was going to have moni test and then I realized that this was a "special" condition and not a typical use-case.
