### ISSUE TITLE
findAllOrganisms doesn't work as a web service

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#661]
The credentials that are passed in don't get propagated to permissionService.currentUser

**Comment by nathandunn** [comment]
This is related to the other permission errors, right?

**Comment by cmdcolin** [comment]
Basic idea is that wherever we call isAdmin, it can't be used as a web service, since this presumes the use of the Security principle (not used by web services currently)

I pushed a fix so this should be ready

**Comment by cmdcolin** [comment]
Should call isUserAdmin instead

**Comment by cmdcolin** [comment]
Actually this has other problem with this. Probably related to what @erasche brought up

The only function that creates a User authentication token  is 

    Boolean hasPermissions(JSONObject jsonObject, PermissionEnum permissionEnum)

If any function does not use this, then the user can be authenticated without a password

**Comment by cmdcolin** [comment]
I'm learning towards using more extensively Shiro to fix https://github.com/GMOD/Apollo/issues/618

**Comment by cmdcolin** [comment]
In any case this particular issue is fixed

**Comment by nathandunn** [comment]
Sounds good.  I’ll take a look.    I’m sure that we’re under-utilizing shiro.    I think that utilizing it more effectively when we add track permissions makes sense.

I’ll take a look at the pull request. 

Nathan

**Comment by nathandunn** [comment]
Right . . . every method that is a web service should use:

```
Boolean hasPermissions(JSONObject jsonObject, PermissionEnum permissionEnum)
```

**Comment by nathandunn** [comment]
But I think that this does essentially the same thing:

```
putativeOrganismList.each {
-                List<PermissionEnum> permissionEnumList = permissionService.getOrganismPermissionsForUser(it,permissionService.currentUser)
+         List<PermissionEnum> permissionEnumList = permissionService.getOrganismPermissionsForUser(it,permissionService.getCurrentUser(organismJson))
           if(permissionEnumList.contains(PermissionEnum.ADMINISTRATE)){		                           
               if(permissionEnumList.contains(PermissionEnum.ADMINISTRATE)){
                      organismList.add(it)	
                 }		                 
           }
```

**Comment by nathandunn** [comment]
@cmdcolin   Does it make sense to close this as its the same tests as in #665?

**Comment by cmdcolin** [comment]
@nathandunn I think so!
