### ISSUE TITLE
When adding new organism, the processing dialog sometimes does not disappear

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#662]
This should be debugged or otherwise resolved so that users are not worried by the fact that it never finishes

Reported to the mailing list

**Comment by nathandunn** [comment]
K . . trying to get some follow-up information . . . I'd put my money on low memory and large scaffolds.

**Comment by cmdcolin** [comment]
I've had it happen fairly frequently but didn't think to report it. Low memory likely not a factor, large scaffolds is though.

**Comment by nathandunn** [comment]
Yeah, it took me about 10-30 minutes to run all of the Brown Recluse (100K scaffolds).  We could also not block and run it in the background . . . notifying the user when it is available. 

Nathan

**Comment by nathandunn** [comment]
Was due to memory issues with tomcat.
