### ISSUE TITLE
Documentation inconsistency on organism/addOrganism vs required params

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#663]
In addOrganism's controller https://github.com/GMOD/Apollo/blob/master/grails-app/controllers/org/bbop/apollo/OrganismController.groovy#L123 we see the parameter organism, type=json.

Actually sending json encoded/escaped data there fails:

```
data={<snip auth>, "organism": "{\"directory\": \"\", \"publicMode\": false, \"commonName\": \"test902\"}"}
```

fails with error `problem saving organism: org.codehaus.groovy.grails.web.json.JSONException: JSONObject["commonName"] not found.` whereas I would have expected `empty fields detected`.

I next considered it may expect a json object, instead of a string of a json object inside the parent json blob that gets sent:

```
data={<snip auth>, "organism": {"directory": "", "publicMode": false, "commonName": "test231"}}
```

failed with the same commonName not found.

Now on to the test which actually works:

```
data={<snip auth>, "directory": "", "publicMode": false, "commonName": "bob52"}
```

returns the expected `problem saving organism: java.lang.Exception: empty fields detected'}`.

I take this to mean that the controller never expected to receive a JSON object and I'm not 100% sure how it actually functions as such. Between that, and the fact that there's a new, undocumented, mandatory parameter `publicMode`, it seems like the JSON object of the controller should be replaced with the individual parameters passed. That said, I've literally never used grails/groovy in my life so I may be off base here...

**Comment by erasche** [comment]
getSequencesForOrganism also uses commonName instead of organismId which is a bit strange when deleteOrganism and deleteOrganismFeatures both use ID.

updateOrganismInfo also needs new publicMode parameter documented. (I'm happy to do this, just let me know :) )

**Comment by nathandunn** [comment]
From @cmdcolin 

"I guess the crux of it is:
do we adopt using this:

{"username":...,"password":...,"organism":{"commonName":...}}

Or do we use

{"username":...,"password":...,"commonName":...,"directory":...,...}
"

I agree with you . . I like the former as well.  

I think that its okay to have both the ID and the commonName, however.

**Comment by cmdcolin** [comment]
I updated some of the docs to match what is currently reflected by the api, and also added to ability to use organism id and organism name on the getSequencesForOrganism for consistency sake

**Comment by nathandunn** [comment]
in e3a137236bfe0327f15e60eb1d20af97b10501f4

**Comment by nathandunn** [comment]
@cmdcolin  I'm not sure the exact commits, but for I think that this:

https://github.com/GMOD/Apollo/blob/master/grails-app/controllers/org/bbop/apollo/OrganismController.groovy#L120-L125

should just be a single line:

https://github.com/GMOD/Apollo/blob/master/grails-app/controllers/org/bbop/apollo/OrganismController.groovy#L170

Maybe there is a way to describe the JSON Object, but probably not be necessary.  

Jumped the gun . . . sorry, didn't see you were still working on it.

**Comment by cmdcolin** [comment]
I didn't change the API, so currently, I think it is accurate to list them separately.



might be nice to make it a sub object, but then again, breaking changes to APIs....

**Comment by nathandunn** [comment]
Yeah . . . we definitely don’t want to break the API . . . alright . . I’ll take care of it. 

Thanks.

**Comment by nathandunn** [comment]
okay . . think it looks good now. 

@erasche  Feel free to comment / re-open if you have anything else.

**Comment by cmdcolin** [comment]
I know this is just a documentation issue but I don't think the update doc in 630e691 is accurate


@erasche has the orgiinal comment "I take this to mean that the controller never expected to receive a JSON object and I'm not 100% sure how it actually functions as such."

This is true, the addOrganism API does not expect a json object for the organism, just a like of json parameters for each part of the organism


i.e. I would call the API like this


    curl -H "Content-Type: application/json" -X POST -d '{"username":"me","password":"pass","directory":"/opt/apollo/pyu_data","commonName":"orgname","publicMode":true}' http://localhost:8080/apollo/organism/addOrganism


and not

    curl -H "Content-Type: application/json" -X POST -d '{"username":"me","password":"pass","organism":{"directory":"/opt/apollo/pyu_data","commonName":"orgname","publicMode":true}}' http://localhost:8080/apollo/organism/addOrganism

**Comment by nathandunn** [comment]
You're right . . . its a list of parameters . .. I was reading it wrong . . . also in the original I'd neglected to put the ID.

**Comment by cmdcolin** [comment]
I also pushed a a fix to permission service that i had wrong in fc81a99 when I was supporting the organism ID and name

**Comment by erasche** [comment]
Thanks for getting this fixed :)
