### ISSUE TITLE
Can't assign group permission

### ISSUE THREAD

**Issue by ifishlin** [GMOD/Apollo#664]
I used the master branch. (#192ec67)

Two operations end in the same situation.
(1). I set group permission from web, but the permissions didn't show on the web after I reloaded.
(2). I set group permission from web api(updateOrganismPermission),  but the JSON response (loadGroups) show no permission([])

However, there is actually a record in table permission
![image](https://cloud.githubusercontent.com/assets/9721827/11004824/76a21b14-8488-11e5-8f99-02f76160b65c.png)

By the way, I saw a error report when I working on group permission. 
![image](https://cloud.githubusercontent.com/assets/9721827/11005079/ca01350a-8489-11e5-812d-006bdff8e15e.png)

**Comment by ifishlin** [comment]
![image](https://cloud.githubusercontent.com/assets/9721827/11005152/45ce083e-848a-11e5-8919-9dc49c59bc33.png)

**Comment by cmdcolin** [comment]
can check into this

**Comment by nathandunn** [comment]
That would be great thanks,

Nathan

**Comment by cmdcolin** [comment]
Fixed it....we were not able to compare, and hence, search for organisms properly due to the hashcode/equals functions not being implemented.

I added this to organism with a groovy intrinsic in 80af69e

**Comment by nathandunn** [comment]
Do you that this will work when doing updates, though? 

e.g., if I update genus or species or the directory?   Its probably fine, just double-checking.

**Comment by cmdcolin** [comment]
@nathandunn should be fine. tested it out a bit. I think if it did reveal any issues, they would be actual issues with our app and not due to the comparator.

**Comment by nathandunn** [comment]
So long as you tested it. 

Its not unusual to NOT compare or use everything in a hash-code or equals or do a custom-comparison (e.g., I want to compare my unsaved object to a saved object . . the only differences would be the ID and version).  

Should be fine.  Thanks,

Nathan

**Comment by monicacecilia** [comment]
I am able to assign group permissions. This does not seem to break any other behavior --- yet. :dancer:
