### ISSUE TITLE
List of insecure web APIs

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#665]
- [x] deleteOrganism
- [x] addOrganism
- [x] updateOrganismInfo

I can demonstrably perform these from the command line without authentication

@erasche was right

Other ones will need to be double checked

**Comment by cmdcolin** [comment]
Basic idea behind this was mentioned in #661

**Comment by cmdcolin** [comment]
Should be fixed after pull request merger

**Comment by nathandunn** [comment]
Test:
- [x] test the web service API's (@nathandunn)
- [ ] re-test that adding an organism, updating organism info, and deleting an organism still works (for @monicacecilia for when after we tag)

@erasche  Please feel free to chime in if you notice anything not quite right.

**Comment by nathandunn** [comment]
Note .. to add organisms, you can just use the same directory from another organism.

**Comment by erasche** [comment]
I'm on d2f9b0adcdebaf393e05486809a7f693301771c9, adding/updating/deleting all work from the web UI, however those are all using the cookie based auth.

As for passing username/password in the json dict, I'm unable to access any of the web APIs from the command line.

```console
$ curl 'http://192.168.0.100:8080/apollo/organism/addOrganism' \ 
  --data 'data={"commonName":"Test", "directory":"/data/merlin-gff/data", "genus":"", "species":"", "blatdb":"", "publicMode":false, "username": "hxr@tamu.edu", "password": "password"}' 
{"error":"Not authorized"}
```

same for findAllOrganisms. Things like listing users/adding users all work fine so I'm assuming it was in something that was touched recently/in regards to this commit.

**Comment by cmdcolin** [comment]
Hi @erasche 
I would use the following format



curl -H "Content-Type: application/json"  'http://localhost:8080/apollo/organism/addOrganism' -d '{"commonName":"Test", "directory":"/data/merlin-gff/data", "genus":"", "species":"", "blatdb":"", "publicMode":false, "username": "yourname", "password": "yourpass"}'


This ensures that we have a request.JSON object. This is probably the best format for the web services calls. The "data=" parsing generally happens from requests made from the webapp where you have already been authorized by session

**Comment by erasche** [comment]
@cmdcolin aha! That would be it. 

I'd been confused about the `data=` and ended up hardcoding that in my python WA2 library along with a web-appropriate content type. Now that this issue seems to be fixed as far as I can tell, I'll correct that and use proper json/content types. Thanks again :)

**Comment by monicacecilia** [comment]
This issue now gets a :dancer: !!
