### ISSUE TITLE
Can we have a webapi for retrieving specific organism?

### ISSUE THREAD

**Issue by ifishlin** [GMOD/Apollo#666]
There is only findAllOrganisms() now, can I have one version for specific organism?

likem getOrgansim(oid)?

I think it will be much scalable.

**Comment by nathandunn** [comment]
I think that seems reasonable.

**Comment by nathandunn** [comment]
I tested and am going to close this.  @ifishlin   Let me know if you run into any problems and we can re-open it.   Thanks.
