### ISSUE TITLE
add a border between contigs / scaffolds / features so it is obvious to users  (JBrowse changes)

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#673]
TODO
==== 

- ~~support padding #996~~
- ~~fix initial scaling issue on load #996~~
- ~~add general color-coded label~~
- ~~can the "overview" be colored, but the direct version not be colored?~~
- [x] fix grid for genes
   - [x] fix for individual genes
- [x] add a searchbox for names back 
- [x] pin to very top
- [x] set always on (if projection)
- [x] add track for index for relative location where we are at (REST-backed)
  - [x] extend custom type use (or be like) LocationScale or develop type
  - [x] align all of the grid marks so that there is no 0-20K-25K . . should be 0-20-40
    - [x] adjust for zoom by rendering inner-ticks in fillBlock (instead of renderFeatures) or just remove those blocks from the store and re-ping
    - [x] should be an ending AND beginning of each track
  - [x] track label should be the current projection
  - [x] set height
- ~~Bookmark should go over annottrack as well (should not matter)~~
  - [x] set permanent label (and remove other track)
- [x] add global track for what we are currently looking at  (REST-backed)
    - [x] color by region and make pretty (subclass track)
    - [x] remove this one as redundant
- [x] remove ref-seq drop-down and leave remaining empty (using empty)
- [x] remove block-based labels (or make them explicit)

Mockup
=====

![image](https://cloud.githubusercontent.com/assets/751274/13971343/b7390cf2-f04c-11e5-8e11-ad58383d31c4.png)

![image](https://cloud.githubusercontent.com/assets/751274/13971345/c21941fa-f04c-11e5-8018-b5a732f0eb64.png)

Older Notes
====

Add a border between contigs.  
Route now . . the border between contigs is seamless (but still awesome).  
We should give *SOME* indicator of where the different contigs are.   GB50290-RA and GB55506-RA are on different contigs, but one would not know. 

<img width="336" alt="screen shot 2015-11-06 at 2 24 45 pm" src="https://cloud.githubusercontent.com/assets/751274/11010239/449cb57a-8492-11e5-85c3-b80ce269909d.png">

Possibilities:
1 - a line and arrow on opposite sides of the track, indicating what is there
2 - different shading on the bottom of the tracks with a label (so you always know where you're at) . . maybe via a combo track
3 - like 2 above, but as a separate track (maybe the best way to start)

I could just return an array or arrays (or an array of objects):
1 - [[min,max,label],[min,max,label] . . etc. etc. ]

**Comment by nathandunn** [comment]
- [ ] @nathandunn will add a startbp/endbp and oldstartbp/oldendbp to each object in the sequenceList array 
- [ ] @enuggetry will add something (after being sketching something out)

**Comment by cmdcolin** [comment]
I was thinking that the highlight function could be extended to show something like this.

Highlights are the best way to draw a big vertical line through all the tracks and they don't necessarily hve to be yellow.

We did something like this for a lab project that I think could be relevant

**Comment by nathandunn** [comment]
I think that would be a good start.   

Would there be any way to notate which is which? 

More importantly . . how would the server relate this to the client?   We could leave it in the sequence URL (does not show location) for now or have it be inserted into the refSeq.json.

If we could float that above (in) the UcA that might be good.  . . 

Nathan

**Comment by nathandunn** [comment]
@cmdcolin   As we talked about yesterday . . can you work on this with @enuggetry based on those other designs.  

My preference:
![apollo splits](https://cloud.githubusercontent.com/assets/751274/11597125/65f16436-9a6e-11e5-9096-a84e91a54469.png)

**Comment by nathandunn** [comment]
If for some reason this won't work . . I have some mobkcups in the "doc" section.  If additional information needs to come through the JSON let me know.   Also if you look in the ApolloLabelProc client plugin you can see what sort of manipulations its doing (I just did a quick hack . . . I'm sure that there are better things to do.

**Comment by nathandunn** [comment]
I just wanted to reiterate the stuff on the dev list.  Pieces to add:

1 - the ability to specify the line color and thickness
2 - making the label show up somewhere
3 - making sure that if the back-ground color is not specified that it should transparent (this background piece is already there).

On the server side we just need a hook that handles the JSON for that, which Colin is writing, that taps in my projection engine, which should be pretty quick to do.  Should include:

- start, end, color (background color), border-width (something like that), border-color, refseq (this is the label). 

Quick question for @cmdcolin :

How does JBrowse get configured to use the Apollo URL?   Do we define that in the annot.json?

**Comment by cmdcolin** [comment]
Went ahead and tried to get that vertical text thing working.

Kind of tricky, but it is possible

![screenshot-localhost 2015-12-08 12-00-24 1](https://cloud.githubusercontent.com/assets/6511937/11663874/4a7f04e0-9da4-11e5-837b-66358eca313c.png)

**Comment by nathandunn** [comment]
Looks okay - making text vertical with CSS, etc. can be a bit of a time-suck (having tried it before).  If it doesn't work that's fine - horizontal text will work, esp. if we have some way to style it and make it "permanent" somewhere.  

More important is getting the background color to be transparent and have a border.

**Comment by cmdcolin** [comment]
I don't really know what you mean like a empty box? Or just a line?

**Comment by nathandunn** [comment]
I mean . . if the highlights have a transparent background and a thick line they will look like this:

https://github.com/GMOD/Apollo/issues/673#issuecomment-162037010

**Comment by cmdcolin** [comment]
Alrighty. Horizontal added. It should be pretty easy to use now and has more reliable positioning

![screenshot-localhost 2015-12-08 12-48-14](https://cloud.githubusercontent.com/assets/6511937/11664931/14b66f96-9daa-11e5-9a90-648bbfe5bf2d.png)


Should be able to be styled pretty much as needed

**Comment by nathandunn** [comment]
Excellent.

If we are not at the border, does it still give an indication of where you are at?  
e.g., if I am off to the left at 1K, do I know I am in ctgA and ctgB is off to the right?

**Comment by cmdcolin** [comment]
I think apollo proc plugin should take care of that. I imagined it just changes what the location bar says depending on what scaffold you are in

**Comment by nathandunn** [comment]
I thought about that . . something that looks like this where the numbers correspond to scaffolds:
  
![screen shot 2015-12-08 at 11 15 30 am](https://cloud.githubusercontent.com/assets/751274/11665602/2145eac8-9d9d-11e5-9139-01e47b9bd7ad.png)

It definitely would not hurt.  

What I would like to see, however, is the Blue (cyan?) part of the mockup in the upper-left that implies permanency (fancy region label XY).   It might have to permanently float to the left until you get to a border area, though.   Conversely putting the label at the very top might be okay, but I like the blue label the most.  Thoughts?

**Comment by cmdcolin** [comment]
Hmm....well, I'm not sure. I kind of feel like just doing the minimal thing is best. Our users aren't clueless, they just want the extra bonus functionality here


Anyways, I opened PR here https://github.com/GMOD/jbrowse/pull/668 if anyone wants to review

**Comment by nathandunn** [comment]
I think the consensus is that we want to get as close to the mockup as possible so user's don't have to work harder to use our interface.   If we can't add the persistent label via a highlight then we need to add an extra track or somehow annotate the track interface.  

I'm sure the pull request is fine, but I'll let @enuggetry  take a look.

**Comment by nathandunn** [comment]
We also need a way to add coordinates to the label somehow:

![screen shot 2015-12-30 at 4 31 56 pm](https://cloud.githubusercontent.com/assets/751274/12059585/fed9be6a-af12-11e5-921b-576a006aadd1.png)
![screen shot 2015-12-30 at 4 31 47 pm](https://cloud.githubusercontent.com/assets/751274/12059586/feef0658-af12-11e5-83e4-ae25cbd7ee40.png)

**Comment by nathandunn** [comment]
It looked like you were having issues using per CSS to replicate [Eric’s mockup above](https://github.com/GMOD/Apollo/issues/673#issuecomment-162037010).   I also think that straight SVG makes more sense then using the dojo library (as you inferred).  D3 might make sense, but probably not for this.  

The goal for this is to demonstrate that we can replicate what Eric has suggested using any method.  We can definitely add data to what the client receives from the server.   We can possibly move this into the client later, but its kind of moot if we don't have a way to draw it.

**Comment by nathandunn** [comment]
http://documentup.com/wout/svg.js#plugins

**Comment by nathandunn** [comment]
I added some SVG code into my branch.  Its still garbage (zooming and alignment needs work) but gets the point across:  https://github.com/GMOD/jbrowse/commit/13c6a5620cd18e208f68111122891fb422021bd6

I think you end up with a lot more flexibility.   Clearly we also need to grab other projected values from the backend as well and hide the track numbers.

![screen shot 2016-01-08 at 1 55 15 pm](https://cloud.githubusercontent.com/assets/751274/12210528/854b6252-b60f-11e5-85d9-880ee45ff188.png)

**Comment by nathandunn** [comment]
Added some demo code mockups with the goal of supporting the following mechanisms:

- we can tell where we are at at any point
- we can tell what projection operations have been applied 
- we can tell quickly find the original projection values
- we can tell how far away we are from the next value
- we know relatively where we are globally (i.e., the original track coordinates are unchanged)

The solution to this is three-fold:

- use the block-based region as we have it now to indicate borders locally and globally
- add a track to highlight regions, so that it is ALWAYS in scope
- add a track to highlight original coordinates and indicate projection.  If there is overlap, this track will stack automatically


This is a mix of old and new demonstrations:

<img width="772" alt="canvas 11" src="https://cloud.githubusercontent.com/assets/751274/13955061/8f1a1e60-f000-11e5-9869-e2033cefef23.png">
<img width="1305" alt="canvas 6" src="https://cloud.githubusercontent.com/assets/751274/13955062/8f302e44-f000-11e5-931e-45714aa2b018.png">
<img width="714" alt="canvas 7" src="https://cloud.githubusercontent.com/assets/751274/13955063/8f66a65e-f000-11e5-80b0-18015652da2a.png">
<img width="714" alt="canvas 8" src="https://cloud.githubusercontent.com/assets/751274/13955067/8fa43f14-f000-11e5-9872-24b9722a5bc3.png">
<img width="783" alt="canvas 10" src="https://cloud.githubusercontent.com/assets/751274/13955066/8fa38bdc-f000-11e5-9819-8e730422b32b.png">
<img width="773" alt="canvas 9" src="https://cloud.githubusercontent.com/assets/751274/13955068/8fbef908-f000-11e5-8a15-b98c81ddd671.png">
<img width="825" alt="canvas 12" src="https://cloud.githubusercontent.com/assets/751274/13955065/8f97b618-f000-11e5-99c8-a4060dbbad88.png">
<img width="725" alt="canvas 13" src="https://cloud.githubusercontent.com/assets/751274/13955069/903062d2-f000-11e5-9df2-0025e9dbb420.png">
<img width="725" alt="canvas 16" src="https://cloud.githubusercontent.com/assets/751274/13955073/90bd953a-f000-11e5-92f5-c43195d4c3bb.png">
<img width="725" alt="canvas 17" src="https://cloud.githubusercontent.com/assets/751274/13955071/90bd6858-f000-11e5-9dd3-879caea569af.png">
<img width="725" alt="canvas 18" src="https://cloud.githubusercontent.com/assets/751274/13955072/90bd8d38-f000-11e5-8fea-e06b84fd49cb.png">
<img width="725" alt="canvas 3" src="https://cloud.githubusercontent.com/assets/751274/13955074/90bf47b8-f000-11e5-9e7a-9986a59481f4.png">
<img width="725" alt="canvas 4" src="https://cloud.githubusercontent.com/assets/751274/13955075/90c82f22-f000-11e5-91f6-044987f3b263.png">
<img width="772" alt="canvas 5" src="https://cloud.githubusercontent.com/assets/751274/13955080/911cb768-f000-11e5-91d0-9218bb0182d2.png">
<img width="772" alt="canvas 14" src="https://cloud.githubusercontent.com/assets/751274/13955076/90d7d31e-f000-11e5-8419-ff68588a2001.png">
<img width="772" alt="canvas 15" src="https://cloud.githubusercontent.com/assets/751274/13955077/90db4224-f000-11e5-8206-2755ffccb7b6.png">
<img width="725" alt="canvas 1" src="https://cloud.githubusercontent.com/assets/751274/13955078/90dc9dcc-f000-11e5-87c8-804242936315.png">
<img width="725" alt="canvas 2" src="https://cloud.githubusercontent.com/assets/751274/13955079/90e4b4b2-f000-11e5-89f7-d51ba2f2cc61.png">

**Comment by nathandunn** [comment]
Made text smaller and added small carats:

![image](https://cloud.githubusercontent.com/assets/751274/13961417/cd05f49c-f019-11e5-9b12-aa82b8771f1f.png)

![image](https://cloud.githubusercontent.com/assets/751274/13961419/d07251ac-f019-11e5-802b-2ea91019722e.png)

**Comment by nathandunn** [comment]
The folding parameters (padding only really) should be configurable / removable by clicking on the icon directly.

**Comment by nathandunn** [comment]
From discussion with @selewis  Added some additional screenshots.

![image](https://cloud.githubusercontent.com/assets/751274/13971343/b7390cf2-f04c-11e5-8e11-ad58383d31c4.png)

![image](https://cloud.githubusercontent.com/assets/751274/13971345/c21941fa-f04c-11e5-8018-b5a732f0eb64.png)

**Comment by nathandunn** [comment]
Note to self:  I think that top part (between the two scales with the "settings" icon can be moved to the bookmark panel and settings can be configured and set over there.    All of this can come in via REST as well as functions.  Conversely, we can pre-load everything at the start.  Not sure what will require more rewrite.

**Comment by nathandunn** [comment]
So, there are two approaches for displaying the internal tick-marks and getting the correct numbers.   We want Left label (and number), Right label (and number) and internal grid lines.    The left and right labels can come out of REST.   The internal grid marks can either be (1) calculated on the fly using the current projection engine (with a subclassed SVGTrackBase) or (2) grabbed via REST or (3) we can over-ride fillBlock instead or (4) eliminate the cached region.

The requirements to support are reiterated from above:
1 - zoom in / zoom out without clutter
2 - region always in view 
3 - labeled edges and coordinates
4 - grid coordinates are relevant to the current zoom level and relative coordinates

Tried doing this with a cache . . but you have to erase SVG components  . . which is what showRange does.  That could be combined with REST as a first-pass.   However, you can delete the elements at a pass, as well.

**Comment by nathandunn** [comment]
I think that 3/4 are out as deletion is messy at best.    Will try 1.  I think we need to get back both the region, the start / end and the current region for each coordinate.

The goal being to get the grid (red lines in green text) to zoom in and out properly.   However, we need to see if the blue text can be properly formatted for density.

![screen shot 2016-04-18 at 10 42 20 am](https://cloud.githubusercontent.com/assets/751274/14613648/3f33f832-0552-11e6-9db8-bfce608fd23e.png)

**Comment by nathandunn** [comment]
Actually, I can just do a linear interpolation if I know the start and end and where the last fold is.

**Comment by nathandunn** [comment]
Fixed by bringing in projection code from the client.

**Comment by nathandunn** [comment]
![screen shot 2016-04-18 at 3 04 40 pm](https://cloud.githubusercontent.com/assets/751274/14623300/c898c8d6-0585-11e6-97ec-5aa1085de48e.png)

**Comment by nathandunn** [comment]
![screen shot 2016-04-18 at 4 51 32 pm](https://cloud.githubusercontent.com/assets/751274/14623303/d42e3546-0585-11e6-93e5-a3778a0bc839.png)

**Comment by nathandunn** [comment]
After a number of problems usi ght estore, I thought that just listing the groups made more sense:

<img width="705" alt="screen shot 2016-04-19 at 3 41 14 pm" src="https://cloud.githubusercontent.com/assets/751274/14657888/32927d80-0645-11e6-873a-d19d0312093c.png">

<img width="533" alt="screen shot 2016-04-19 at 3 41 22 pm" src="https://cloud.githubusercontent.com/assets/751274/14657887/327ad572-0645-11e6-8aca-8e1e65f07f0d.png">
<img width="611" alt="screen shot 2016-04-19 at 3 49 10 pm" src="https://cloud.githubusercontent.com/assets/751274/14658081/50c4bede-0646-11e6-9d1b-02fc514e45ca.png">
