### ISSUE TITLE
project reverse complement

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#681]

**Comment by nathandunn** [comment]
This will allow us to re-project the ENTIRE SCAFFOLD as a reverse compliment.

**Comment by monicacecilia** [comment]
*complement*  -- we are not issuing inverted words of praise for the scaffold. :bowtie:

**Comment by nathandunn** [comment]
Not even for very good scaffolds?

**Comment by nathandunn** [comment]
Closing in favor of #482
