### ISSUE TITLE
handle VCF / variant display

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#685]

**Comment by nathandunn** [comment]
This project is pretty similar to what we are envisioning /partially:  https://github.com/hammerlab/varcode

**Comment by nathandunn** [comment]
https://github.com/hammerlab/cycledash

**Comment by nathandunn** [comment]
@cmdcolin  You can probably ignore my comments . .  I just wanted to be able to track what I think folks are working on.  Simulating what is in the grant with a combo track is probably the most important.

**Comment by cmdcolin** [comment]
I'll take a look. I have the document on hand right now

**Comment by monicacecilia** [comment]
Redundant with #524, #583, #893
