### ISSUE TITLE
display projected BAM tracks

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#686]
Doing this already with the REST API using the htseq API from BROAD:

- [ ] project mismatches correctly as subfeatures (or correclty populate another string?)
- [ ] handle MD string mismatches correctly
- [ ] project MD strings
- [ ] automatically adjust histogram depth defaults to avoid "too much detail"
- [ ] test other track types (should match 128k pair), etc. etc. etc. 
- [ ] replace strings with official SAMTag and CigarOperation's

- [ ] add integration test for `ctgA_19043_19563_1:0:0_1:0:0_18a0` at `ctgA:19281..19910 (631 b)`

- [ ] enable caching 

- [ ] fix render range bug (below) if still exists
- [ ] Template length?

== DONE ==

- [x] populate the remaining track feature details (below)
   - [x] Multi segment next segment reversed
   - [x] Multi segment template
   - [x] Qc failed
   - [x] Seq reverse complemented

- [x] project cigar alignments properly
- [x] trace through to make sure I have the cigar attribute populated and the md attribute populated 
    - [x] - or - add subfeatures with cigar strings and md strings [emulating this code] (https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/Store/SeqFeature/BAM/LazyFeature.js#L427-L475) .  Shows up, but clearly is wrong.  Compare to other types. 

- [x] test logged out
- [x] populate alignments
- [x] handle strand information correctly (should have minus-bam-read / plus-bam-read)
  - [x] indicate strand on draggable alignments (use the arrow icon?) on the two classes 

- [x] handle mismatches
- [x] over-ride BAM featuredetails to handle refSeq as JSON

=== 
 - [x] use htsjdk to do the read properly for an interval 
- [x] merge in BigWig fixes
- [x] rewrite track (similar to BigWig) 
- [x] handle projection 
- [x] populate features 
- [x] confirm that index is working by removing it and see what happens (needs the index!)
- [x] populate global
- [x] populate region
- [x] review Honeybee data (works)
- [x] populate regionFeatureDensities

**Comment by nathandunn** [comment]
Uses this: https://github.com/timpalpant/java-genomics-io/tree/master/src/edu/unc/genomics/io/BAMFileReader

**Comment by deepakunni3** [comment]
@nathandunn I think you are referring to htslib API from Broad: https://samtools.github.io/htsjdk/

htseq is an entirely different tool written in Python for estimating read counts from RNAseq BAMs ;)

**Comment by nathandunn** [comment]
Yes that is right.  I think I ended up using the genomics Java lib from unc for bigwig and the same for bam.

**Comment by nathandunn** [comment]
Zoomed out histogram view will happen automatically once I populate those methods.

**Comment by nathandunn** [comment]
[Uploading Screen Shot 2017-07-24 at 4.48.24 PM.png...]

**Comment by nathandunn** [comment]
<img width="609" alt="screen shot 2017-07-24 at 4 48 24 pm" src="https://user-images.githubusercontent.com/751274/28549712-d8866380-7090-11e7-8533-f0dc41996847.png">

**Comment by nathandunn** [comment]
```
NO Track assemblage null and {"organism":"21","clientToken":"11410287301476095970","sequenceList":[{"organism":"Honeybee","name":"GroupUn1076","start":0,"length":970,"end":970,"location":[{"fmin":0,"fmax":970}],"id":449,"reverse":false}]}
params [controller:bam, organismId:21, action:global, trackName:Forager RNA-Seq reads]
| Error 2017-07-25 16:28:08,278 [http-bio-8080-exec-13] ERROR errors.GrailsExceptionResolver  - SAMFormatException occurred when processing request: [GET] /apollo/bam/Forager%20RNA-Seq%20reads/21/stats/global
Error parsing SAM header. @HD line has non-conforming SO tag value: sorted.. Line:
| Error 2017-07-25 16:28:08,278 [http-bio-8080-exec-13] ERROR errors.GrailsExceptionResolver  - SAMFormatException occurred when processing request: [GET] /apollo/bam/Forager%20RNA-Seq%20reads/21/stats/global
Error parsing SAM header. @HD line has non-conforming SO tag value: sorted.. Line:
@HD	VN:1.0	SO:sorted; File /opt/apollo/honeybee/data/bam/forager_Amel4.5_accepted_hits.bam; Line number 1. Stacktrace follows:
Message: Error parsing SAM header. @HD line has non-conforming SO tag value: sorted.. Line:
@HD	VN:1.0	SO:sorted; File /opt/apollo/honeybee/data/bam/forager_Amel4.5_accepted_hits.bam; Line number 1
    Line | Method
->>  265 | reportErrorParsingLine in htsjdk.samtools.SAMTextHeaderCodec
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    236 | parseHDLine            in     ''
|    102 | decode . . . . . . . . in     ''
|    667 | readHeader             in htsjdk.samtools.BAMFileReader
|    298 | <init> . . . . . . . . in     ''
|    176 | <init>                 in     ''
|    376 | open . . . . . . . . . in htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl
|    202 | open                   in     ''
|    107 | global . . . . . . . . in org.bbop.apollo.BamController
|    198 | doFilter               in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . . . . in grails.plugin.cache.web.filter.AbstractFilter
|    449 | executeChain           in org.apache.shiro.web.servlet.AbstractShiroFilter

```

**Comment by nathandunn** [comment]
JBrowse / volvox is using Alignment2, which we don't want to do.  However, they are essentially the same.

- [ ] name: ctgA_27360_27908_0:0:0_0:0:0_10ca
- [ ] position: (sequence.refname to handle) , ctgA:27809..27908 (-)
- [ ] type: e.g., match
- [ ] score
- [ ] Seq (Array)
- [ ] Qual (array)
- [ ] CIGAR (not Cigar?)
- [ ] attributes 
   - [ ] fix mapping per code entry with custom handling
- [ ] remove "Class"
- [ ] Duplicate
- [ ] Length on ref
- [ ] Multi segment next segment reversed
- [ ] Multi segment template
- [ ] Qc failed
- [ ] Secondary alignment
- [ ] Seq length
- [ ] Seq reverse complemented
- [ ] Source e.g., volvox-sorted.bam
- [ ] Supplementary alignment
- [ ] Template length
- [ ] Unmapped

**Comment by nathandunn** [comment]
The properties come in between Alignments.js and _AlignmentsMixin.js  and they can be hidden in the configuration file.

**Comment by nathandunn** [comment]
Header properties:

```
[comments:[], sortOrder:unsorted, attributes:[VN=1.5], standardTags:[VN, GO, SO], programRecords:[], class:class htsjdk.samtools.SAMFileHeader, validationErrors:[], SAMString:@HD	VN:1.5
@SQ	SN:ctgA	LN:50001
, version:1.5, groupOrder:none, creator:null, textHeader:@SQ	SN:ctgA	LN:50001
, sequenceDictionary:SAMSequenceDictionary:( sequences:1 length:50001  md5:3d62af8e60a6f9b772a2bcbcd2b5af92), readGroups:[]]

```

SAM Read properties:
```
[alignmentBlocks:[htsjdk.samtools.AlignmentBlock@14e4143c], duplicateReadFlag:false, mateAlignmentStart:0, start:24494, readNameLength:33, readGroup:null, readPairedFlag:false, mappingQuality:37, unclippedStart:24494, baseQualityString:2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222, readUnmappedFlag:false, binaryAttributes:htsjdk.samtools.SAMBinaryTagAndValue@5daa9, variableBinaryRepresentation:[99, 116, 103, 65, 95, 50, 52, 52, 57, 52, 95, 50, 53, 48, 48, 53, 95, 51, 58, 48, 58, 48, 95, 50, 58, 49, 58, 48, 95, 49, 49, 56, 100, 0, 64, 6, 0, 0, 18, 40, -127, 40, -120, 36, 20, 72, 20, 36, 24, 18, 18, -127, 72, 66, 17, 36, 24, 65, 18, 34, 18, -127, -127, 72, 40, -127, 72, 65, -120, -126, 24, 72, -120, -127, 40, -127, 36, 36, 17, 17, 36, -124, 68, 72, -120, 68, -126, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 88, 84, 65, 85, 78, 77, 67, 3, 88, 48, 67, 1, 88, 49, 67, 0, 88, 77, 67, 3, 88, 79, 67, 0, 88, 71, 67, 0, 77, 68, 90, 50, 48, 71, 52, 84, 54, 56, 84, 53, 0], readString:ACCTTACTTTCGAGGTAGCGATACACTAGTGCAACGATGAACCCACTATAGTCTTAGTGATTTCATGTTTTACTTACGCGAAAACGTGGGGTTTGGTCAA, secondaryOrSupplementary:false, pairedReadName:ctgA_24494_25005_3:0:0_2:1:0_118d, class:class htsjdk.samtools.BAMRecord, header:SAMFileHeader{VN=1.5}, valid:null, notPrimaryAlignmentFlag:false, inferredInsertSize:0, baseQualities:[17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17], readName:ctgA_24494_25005_3:0:0_2:1:0_118d, readLength:100, referenceName:ctgA, readFailsVendorQualityCheckFlag:false, end:24593, contig:ctgA, cigarString:100M, attributes:[htsjdk.samtools.SAMRecord$SAMTagAndValue@3ea68054, htsjdk.samtools.SAMRecord$SAMTagAndValue@6b0fa21f, htsjdk.samtools.SAMRecord$SAMTagAndValue@2cf5e547, htsjdk.samtools.SAMRecord$SAMTagAndValue@18044111, htsjdk.samtools.SAMRecord$SAMTagAndValue@12aac665, htsjdk.samtools.SAMRecord$SAMTagAndValue@4238175, htsjdk.samtools.SAMRecord$SAMTagAndValue@7ff936b, htsjdk.samtools.SAMRecord$SAMTagAndValue@3dc9464c], unclippedEnd:24593, readBases:[65, 67, 67, 84, 84, 65, 67, 84, 84, 84, 67, 71, 65, 71, 71, 84, 65, 71, 67, 71, 65, 84, 65, 67, 65, 67, 84, 65, 71, 84, 71, 67, 65, 65, 67, 71, 65, 84, 71, 65, 65, 67, 67, 67, 65, 67, 84, 65, 84, 65, 71, 84, 67, 84, 84, 65, 71, 84, 71, 65, 84, 84, 84, 67, 65, 84, 71, 84, 84, 84, 84, 65, 67, 84, 84, 65, 67, 71, 67, 71, 65, 65, 65, 65, 67, 71, 84, 71, 71, 71, 71, 84, 84, 84, 71, 71, 84, 67, 65, 65], mateReferenceIndex:-1, flags:0, alignmentEnd:24593, validationStringency:SILENT, SAMFlags:[], cigar:100M, cigarLength:1, fileSource:null, readNegativeStrandFlag:false, attributesBinarySize:41, indexingBin:4682, mateReferenceName:*, SAMString:ctgA_24494_25005_3:0:0_2:1:0_118d	0	ctgA	24494	37	100M	*	0	0	ACCTTACTTTCGAGGTAGCGATACACTAGTGCAACGATGAACCCACTATAGTCTTAGTGATTTCATGTTTTACTTACGCGAAAACGTGGGGTTTGGTCAA	2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222	X0:i:1	X1:i:0	MD:Z:20G4T68T5	XG:i:0	NM:i:3	XM:i:3	XO:i:0	XT:A:U
, referenceIndex:0, alignmentStart:24494, supplementaryAlignmentFlag:false, originalBaseQualities:null]
```

**Comment by nathandunn** [comment]
BAM/LazyFeature.js has the remaining mapping components out of the tags and values.  

Also, the tag values for a samrecord look like this:

```
SAMRecord tag: X0 -> 1
SAMRecord tag: X1 -> 0
SAMRecord tag: MD -> 31C0C5G61
SAMRecord tag: XG -> 0
SAMRecord tag: NM -> 3
SAMRecord tag: XM -> 3
SAMRecord tag: XO -> 0
SAMRecord tag: XT -> U
```

**Comment by nathandunn** [comment]
Test instance: ```ctgA_19043_19563_1:0:0_1:0:0_18a0``` at `ctgA:19281..19910 (631 b)`

**Comment by nathandunn** [comment]
BAM is returned with `file` and `byte` fields as well.  I think those are already being absorbed by the API and are just used for reading.

**Comment by nathandunn** [comment]
https://samtools.github.io/hts-specs/SAMtags.pdf

https://samtools.github.io/hts-specs/SAMv1.pdf

**Comment by nathandunn** [comment]
Its unclear how the cigar strings are failing.   They should be returning things of the nature: `100M` .  The BAM / File, LazyFeature.js, etc. is all store related data that we are ignoring anyway in favor of just alignments.  It seems like somehow the subfeatures are just not being passed in properly during the parsing process. 

<img width="742" alt="screen shot 2017-07-29 at 11 53 18 am" src="https://user-images.githubusercontent.com/751274/28747496-b2ca1430-7454-11e7-83e5-6a288feb3437.png">
<img width="343" alt="screen shot 2017-07-29 at 11 53 16 am" src="https://user-images.githubusercontent.com/751274/28747495-b2c86554-7454-11e7-90a9-57c63dc973aa.png">
<img width="610" alt="screen shot 2017-07-29 at 11 52 55 am" src="https://user-images.githubusercontent.com/751274/28747497-b2ce685a-7454-11e7-8aa1-dd5e51ea92b2.png">

We need to emulate this code to generate the subfeatures properly:

```
    _cigarToSubfeats: function(cigar)    {
        var subfeats = [];
        var min = this._get('start');
        var max;
        var ops = this._parseCigar( cigar );
        for (var i = 0; i < ops.length; i++)  {
            var lop = ops[i][1];
            var op = ops[i][0];  // operation type
            // converting "=" to "E" to avoid possible problems later with non-alphanumeric type name
            if (op === "=")  { op = "E"; }

            switch (op) {
            case 'M':
            case 'D':
            case 'N':
            case 'E':
            case 'X':
                max = min + lop;
                break;
            case 'I':
                max = min;
                break;
            case 'P':  // not showing padding deletions (possibly change this later -- could treat same as 'I' ?? )
            case 'H':  // not showing hard clipping (since it's unaligned, and offset arg meant to be beginning of aligned part)
            case 'S':  // not showing soft clipping (since it's unaligned, and offset arg meant to be beginning of aligned part)
                break;
                // other possible cases
            }
            if( op !== 'N' ) {
                subfeats.push(
                    new SimpleFeature(
                        {
                            data: {
                                type: op,
                                start: min,
                                end: max,
                                strand: this._get('strand'),
                                cigar_op: lop+op
                            },
                            parent: this
                        })
                );
            }
            min = max;
        }
        return subfeats;
    }
```

**Comment by nathandunn** [comment]
Render range bug?
[Uploading Screen Shot 2017-07-31 at 3.37.51 PM.png...]

**Comment by nathandunn** [comment]
For the mismatch handling, its a bit interseting.  Its reinterpreting the cigarString and the MD string, elements which should have already been re-interpreted. 

Ultimately, what we want is something that draws the subclass spans with the classes, align_mismatch mismatch base_[T|A|G|C]

**Comment by nathandunn** [comment]
Mismatch rendered as class:

<img width="872" alt="screen shot 2017-08-01 at 12 45 21 pm" src="https://user-images.githubusercontent.com/751274/28844010-19796306-76b8-11e7-8b72-a1da7d049d0a.png">



<img width="287" alt="screen shot 2017-08-01 at 12 42 08 pm" src="https://user-images.githubusercontent.com/751274/28844011-198726c6-76b8-11e7-9ead-43f1bb34b88f.png">

**Comment by nathandunn** [comment]
The render error (not getting now, though):

<img width="562" alt="screen shot 2017-07-31 at 3 37 51 pm" src="https://user-images.githubusercontent.com/751274/28844096-5d18b0ee-76b8-11e7-8fb5-08e9ddb04a7b.png">

**Comment by nathandunn** [comment]
Closing in favor of #1826
