### ISSUE TITLE
on changes page, use combo-box / on-change instead of exact text-box / submit

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#695]
A pretty minor change.  Not worth putting into 2.0.1.
- [x] owner should be a drop-down (no submit, on-change)
- [x] organism should be a drop-down (no submit, on-change)
- [x] feature type should probably be a drop-down as well  (no submit, on-change)

**Comment by nathandunn** [comment]
This is already done (yeah!)

**Comment by monicacecilia** [comment]
@nathandunn where can the owner be seen in a drop down menu?

**Comment by nathandunn** [comment]
@monicacecilia  We just show who changed it, not who the originally owned it (if the person was different).  That would be a neat feature, though.
