### ISSUE TITLE
Unable to access Apollo on IE or Edge

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#697]
Unable to access Apollo (http://icebox.lbl.gov/Apollo2/annotator/index) on Internet Explorer or MS Edge. Chrome & Firefox worked mostly ok (except for #585).
Working on: DELL Inspiron 15, 5000 Series. MS Windows 10.

Observed behavior: 
- Login window appears
- Enter correct credentials
- Auto-refresh and continuously taking user back to the login window

**Comment by nathandunn** [comment]
tried this on Win 8.1 / IE 11 and it worked in virtualbox . .  time to upgrade my virtual instances  . . 

If there are any "dev console" errors that would be helpful as well.

**Comment by monicacecilia** [comment]
Sorry @nathandunn I only watched briefly as students were working on their machines and asked them to turn dev mode for the searches but not for the login. I'll try to do it if I come across a windows machine again any time soon.

**Comment by nathandunn** [comment]
No worries.  The bug report should be enough to reproduce it. 

Nathan

**Comment by monicacecilia** [comment]
If this ever shows up again.. then we'll re-open.
