### ISSUE TITLE
Apollo or grails sensitive to slashes

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#699]
Maybe this is a non-issue but Apollo can be quite sensitive to slashes. In the best case we would at least have a better "fail" page, because entering the wrong thing is just a white page

As an example, our main page is this

    http://localhost:8080/apollo/annotator/index

But navigating to any of these gives silent errors

    http://localhost:8080/apollo//annotator/index
    http://localhost:8080/apollo/annotator//index
    http://localhost:8080/apollo/annotator/index/

**Comment by nathandunn** [comment]
It has to do with the URLMapper

**Comment by cmdcolin** [comment]
Probably true. There is another similar bug that comes up sometimes

This is a valid url

http://localhost:8080/Apollo_special/

But the URL encoded underscore will fail with a strange error

http://localhost:8080/Apollo%5Fspecial/

Technically this should be valid

In any case, can close as "wontfix". I just wanted to have a point of reference in case it came up
