### ISSUE TITLE
(2d) support canned comments

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#70]
11. 
there were no "canned comments" to test on the information editor.

**Comment by nathandunn** [comment]
@monicacecilia   Need to retest.

**Comment by monicacecilia** [comment]
Canned comments are not available for any feature tested (gene, ncRNA, tRNA). I have refreshed after cleaning cache, and I also opened an incognito window. Canned comments are not available.

**Comment by nathandunn** [comment]
Add link to "Preferences" and handle it off-line that way via Angular?   Not really required most of the time for annotating.

**Comment by nathandunn** [comment]
@cmdcolin  @deepakunni3  @childers

What I was thinking is that the Preferences / Admin panel (the last one) would contain an HTML page configured with links created via the config.  These would point to internal pages (or really any app you wanted).  

For CannedComments, I was just going to create a relatively easy list to run through / add with AngularJS / bootstrap.   I think that will be the EASIEST way to do at least admin-level administration.    

Conversely, I could just include it directly on the Admin panel via GWT, but I think that this will be much more flexible without over-crowding the interface.    

Thoughts?

**Comment by nathandunn** [comment]
on this branch:  canned-comments

**Comment by cmdcolin** [comment]
Well this is just another sort of paradigm shfit but I have maintained for awhile that we should have things outside of the annotator panel. I would advocate moving even more things out of there.

**Comment by cmdcolin** [comment]
I suppose our current situation with a lot of annotator panel features is not that bad, but i think having more options is better, so more user interface features like this will be good

**Comment by nathandunn** [comment]
I think that the paradigm should be something like:

1 - things associated with active annotation should go in the side-bar to be available while annotating (annotations, reference sequences, organisms)
2 - things done infrequently, as well as things like reports or other management, can be within a separate interface (users / groups, general preferences)

Organisms / users are kind of weird as they are *more* associated.   I think as more folks use the interface, it should become more apparent. 

Nathan

**Comment by monicacecilia** [comment]
1. The list of "canned comments" at Apollo2/cannedComment/index had 2 items, (i.e: "My favorite Gene" and "Needs more data") but only the second one was visible when trying to use them. 
2. After creating two additional canned comments and refreshing the "Annotator" page, the new comments were not available. @nathandunn what are the requirements for being making new canned comments available?

**Comment by monicacecilia** [comment]
"Assignee" feature triggered too fast and mistakenly added Rob -- disregard. 
I've correctly added @nathandunn again. :)

**Comment by nathandunn** [comment]
@monicacecilia   No more caffeine for you . . . 

I tried to replicate what the USDA gave me.   Basically, if there is not filter (like "Needs more data") it shows up everywhere. 

If there is a filter (like gene), it will ONLY show up for the Gene.   If you want it to show up for the MRNA, you have to add that explicitly.

**Comment by monicacecilia** [comment]
Ah, ok. Thanks. 

Also, this list is riddled with typos. Please update as shown below: 
![screen shot 2015-05-18 at 2 25 39 pm](https://cloud.githubusercontent.com/assets/1714621/7690603/d3a673b0-fd69-11e4-9f71-6ba98c33be2e.png)

* MRNA --> mRNA
* SnRNA --> snRNA
* SnoRNA --> snoRNA
* MiRNA --> miRNA
* TRNA --> tRNA
* NcRNA --> ncRNA
* RRNA --> rRNA

**Comment by nathandunn** [comment]
@monicacecilia   These are the CVTerms, not typos.   However, I'll just the "alternate", which is the more display appropriate.

**Comment by nathandunn** [comment]
the display should be fixed now

**Comment by monicacecilia** [comment]
All systems GO on this one. :checkered_flag: :trophy: :checkered_flag:
