### ISSUE TITLE
fast forward button not consistently enabled on Users panel

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#700]
We're testing the RC5 codebase and noticed that when there are a lot of users the top navigation button to jump to the end of the list is not always enabled. It is enabled on the first screen, but not on any subsequent screens.

![users_jump_button_disabled](https://cloud.githubusercontent.com/assets/421248/11194789/1fdfdfc2-8c7c-11e5-9399-7a52d246e9c7.png)

**Comment by nathandunn** [comment]
Weird, usually if the number at the top is correct it will figure out the pagination as well.

**Comment by childers** [comment]
Could it be because we're testing with over a thousand users? We're over 400 distinct users now, so this isn't too far-fetched.

**Comment by childers** [comment]
Also, should this tab take seconds to populate? It seems to be very slow  (3-5 seconds) to populate this panel when I first log on.

**Comment by nathandunn** [comment]
No . . . I **think** the problem is that the pagination code provides "counts" in a few areas and it may have put the current one in the wrong place.   Should be an easyish fix.

**Comment by cmdcolin** [comment]
I think the super fast forward button is designed to jump 1000 forward so I feel like what you are seeing is the expected behavior

**Comment by nathandunn** [comment]
oh . . I thought it was to jump to the end as well.  . . .  I see . . there is a "fast forward" button and a "last page" button.   I think by default we show the fast forward button (which defaults to 1K) instead of the last-page button.    

Question:  What makes the most sense? I would lean towards the last-page button for user's and groups.  

WRT to the slowness . . does this speed improve or is it consistently slow each time you come back to the tab?    I'm seeing about 1 second of lag, but I've only went up to about 100 users.

**Comment by cmdcolin** [comment]
We can turn on the "last page" button, it just isn't enabled right now. We could add a "last page" button, it is available from SimplePager.java.

We have WebApolloSimplePager.java which implements SimplePager http://www.gwtproject.org/javadoc/latest/com/google/gwt/user/cellview/client/SimplePager.html

**Comment by nathandunn** [comment]
That makes sense to me, but @childers  is the one supporting the large number of user's, so I defer to him.

**Comment by cmdcolin** [comment]
Sounds good, I added some code here to demonstrate adding the last page button for reference, also adjusts the fast forward size to be a little more manageable (50 instead of 1000) https://github.com/GMOD/Apollo/pull/701

**Comment by childers** [comment]
Thanks for the discussion and clarification! It took your description and a second look to realize the difference in the button types.  

@nathandunn In terms of slowness, if I reload the page, it still takes some time, though it seems faster. I'm at 1,006

**Comment by cmdcolin** [comment]
Currently the fast forward button was removed actually in #701. We will need to double down on the configurability for the annotator panel.

**Comment by cmdcolin** [comment]
Just FYI the pagination on the annotatorpanel was messed up too in 2.0.1 RCs but was fixed today 9e93f68ebe3e3100973ef594870b97e813363670

**Comment by nathandunn** [comment]
Thanks.  Yeah, I might retag . . .we’ll see.  

Nathan

**Comment by monicacecilia** [comment]
Well, this is solved, so it gets a :dancer: 
...  but now this: #727
