### ISSUE TITLE
Some environment variables should be hidden from System Info Page

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#702]
With the `sample-docker-apollo-config.groovy` I added, a number of new environment variables were needed, one of was `WEBAPOLLO_DB_PASSWORD`. In the event that apollo admin `!=` postgres/server admin, that should probably be redacted.

(I'm volunteering to contribute this, I just wanted to submit a proper issue so I can keep track of this until I can get around to it later this week.)

**Comment by nathandunn** [comment]
Thanks for adding these.  Just let issue a new pull request when you're ready.

**Comment by nathandunn** [comment]
@erasche   just updating this for scheduling.  Whenever you have a pull request, let me know.  It was great mentioning your "docker" implementation of Galaxy + Apollo at PAG.

**Comment by erasche** [comment]
@nathandunn okay, this should be a pretty easy one to knock out, I'll try and get it done this weekend. Hope people liked it! We'll have more "presentation" quality materials (+demos) this summer if the community is interested in that sort of things.

**Comment by nathandunn** [comment]
:+1:
