### ISSUE TITLE
updateOrganismPermission doesn't work on organism who have blank in name.

### ISSUE THREAD

**Issue by ifishlin** [GMOD/Apollo#718]
This is my test command

curl -b cookies.txt -c cookies.txt -X POST --header "Content-Type:application/json" --data "{"name": "GROUP_ANOGLA_USER", "organism" : "Agrilus planipennis", "ADMINISTRATE" : false, "WRITE" : true, "EXPORT" : true, "READ" : true, "username": "R2D2@i5k.org", "password": "demo"}" http://localhost:8085/apollo/group/updateOrganismPermission

and error msg on Apollo console

| Error 2015-12-03 16:21:44,615 [http-bio-8085-exec-1] ERROR errors.GrailsExceptionResolver  - JSONException occurred when processing request: [POST] /apollo/group/updateOrganismPermission
Expected a ',' or '}' at character 44 of {name: GROUP_ANOGLA_USER, organism : Agrilus. Stacktrace follows:
Message: Expected a ',' or '}' at character 44 of {name: GROUP_ANOGLA_USER, organism : Agrilus

it seems cause by blank in 'Agrilus planipennis'

**Comment by nathandunn** [comment]
Did you use the single-quote as the outer quote around "data”? 

i.e., does this line work? 

curl -b cookies.txt -c cookies.txt -X POST --header "Content-Type:application/json" --data '{"name": "GROUP_ANOGLA_USER", "organism" : "Agrilus planipennis", "ADMINISTRATE" : false, "WRITE" : true, "EXPORT" : true, "READ" : true, "username": "R2D2@i5k.org <mailto:R2D2@i5k.org>", "password": "demo”}' http://localhost:8085/apollo/group/updateOrganismPermission

**Comment by ifishlin** [comment]
yeh, it works, thanks

**Comment by nathandunn** [comment]
Feel free to re-open if there are additional issues.
