### ISSUE TITLE
export box looks odd and needs to be converted to bootstrap

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#726]
In reference to #704 .

**Comment by nathandunn** [comment]
Visual in comment:  https://github.com/GMOD/Apollo/issues/704#issuecomment-163754523

![screen shot 2015-12-10 at 1 25 38 pm](https://cloud.githubusercontent.com/assets/1714621/11728963/981cd0e4-9f41-11e5-8aab-23361355ea05.png)

**Comment by nathandunn** [comment]
Commits are in #704 . .. . mean to do a branched pull request, but ended up on master. 

To Test:
- use all of the export functionality as you normally would

**Comment by nathandunn** [comment]
@monicacecilia   Not on the server yet . . still waiting.  In the interim . . this is what it looks like. 

<img width="762" alt="screen shot 2015-12-11 at 11 57 35 am" src="https://cloud.githubusercontent.com/assets/751274/11754188/668c901a-9ffe-11e5-9f4b-43cdd57d7537.png">

<img width="640" alt="screen shot 2015-12-11 at 11 58 08 am" src="https://cloud.githubusercontent.com/assets/751274/11754202/79618f60-9ffe-11e5-8529-4ec021b7f7be.png">

Example screens.  Have to highlight an option.   Let me know if it needs any modification.

**Comment by monicacecilia** [comment]
much better. This also closes #704 :dancer:
