### ISSUE TITLE
Unable to create a new user after editing an existing one.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#727]
While reviewing #700 I discovered the following bug. Follow these steps: 
- Go to User tab
- Click on '+Create User'
- Place the cursor on any of the fields
- Without clicking on 'Save' go to click on a different user from the existent list of users

__Result:__ The '+Create User' is now disabled, and you can't go back to the 'Details' for the user you were trying to create before. The only active button is 'xDelete' on the current user. This can only be solved by refreshing the page

**Comment by nathandunn** [comment]
Ideally this should be a popup as related to #622.    In the interim I think that the best solution is to silently "cancel" the "Add" mode once you select a user.  

I toyed with removing the users themselves, but it makes the interface more awkward if you select off and on (though I guess you could re-use that).  

Let me know what makes sense (other than the "popup").

**Comment by nathandunn** [comment]
@monicacecilia  I have fixed (not deployed) a solution for this.  Mostly just wanted to check if its sufficient.

**Comment by monicacecilia** [comment]
The initial problem is gone. So it is currently sufficient. :dancer:
