### ISSUE TITLE
Increase screen real estate for instance reference sequence name

### ISSUE THREAD

**Issue by strumpfe** [GMOD/Apollo#728]
Is it possible to increase the space available for the instance and reference sequence names. There appears to be space and in my view erring on the side of caution for longer names is good practice.

![instance_location_screen_real_estate](https://cloud.githubusercontent.com/assets/2750489/11732759/03c08a0e-9f9f-11e5-9517-e93847e35771.png)

**Comment by nathandunn** [comment]
Yeah it should be scale to the available space.   I'll see what I can do. 

Nathan

**Comment by monicacecilia** [comment]
@nathandunn is working on improving this with the new coordinates transformation code.

**Comment by nathandunn** [comment]
this drop-down will go away with the projection code in favor of the sequence panel

**Comment by nathandunn** [comment]
Should be there on selection. 

![Screen Shot 2019-02-07 at 11.08.51 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5424680176b57b0200a2a95c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216454f46b7191a379ee0c2b59415a4fbc21254d58eeb9cb74fce36f34985619e8d6395d77c66b47aaec801dec01bc758b4cd3e5eadb18c4fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34fe84b55ad143265e472326e0a.png)
