### ISSUE TITLE
Increase flexibility of Annotation summary menu

### ISSUE THREAD

**Issue by strumpfe** [GMOD/Apollo#729]
The Annotations summary panel (which lists all user-created annotations with their location, type and length) is a welcome addition. When reviewing submissions from even a moderate number of users having greater flexibility in the displayed columns would be advantageous.

Specifically, including the user helps when triaging submissions. I know you can filter by user but there is a Rumsfeldian logic here - one needs to know which users have been active before you can filter for that user. There are other displays/data summaries for this but they are on different pages and hence require flipping between pages.

Having a timestamp (created or modified) would also be useful. Again, I'm aware that the Report:Changes page could be viewed as covering this functionality but being able to see the timestamp and sort using it within the same page as the jbrowse would be helpful.

Finally, and more useful to me, we (VectorBase) maintain a status field for each user-created locus to capture whether they have completed work on that locus. This was deployed as a method of dealing with unfinished and low quality predictions when performing a data freeze and merge/integration for a gene set update. It would be useful to be able to display/filter for this field. I acknowledge this is serious feature creep in that it requires the ability to configure and work with non-core data fields (as opposed to the user and timestamp which are in the core data model and hence easier to implement).

![navigation_menu_configurability](https://cloud.githubusercontent.com/assets/2750489/11733029/c81f5766-9fa1-11e5-89fa-0462fe3e673e.png)

**Comment by nathandunn** [comment]
Our "hope" was that user's might be able to create their own reports pages off of specific needs.  That being said, this has been a common request (including status) and it is also baked into WA2, so it would be pretty straight-forward to add.

**Comment by nathandunn** [comment]
- [x] timestamp field added
- [x] status field added in #2269 so closing this now
