### ISSUE TITLE
Use of pagination versus scrollable list in some interfaces

### ISSUE THREAD

**Issue by strumpfe** [GMOD/Apollo#731]
Always a thorny UI choice. Can I voice my support for scrollable lists rather than pagination for some interfaces, e.g. the user admin. In our implementation of WebApollo2 we have 36 species and when you edit the permissions per species as an administrator the pagination is for 4 items. That is the first page contains items 1-4 of 36. The interface only allows me to step through the list in groups of 4 with no filtering/jumping between pages which makes editing of this data when there are many species instances frustratingly painful. Having a scrollable list would (a) show all instances at the same time aiding navigation and (b) be more efficient in making multiple edits.

![menu_pagination_v_scroll](https://cloud.githubusercontent.com/assets/2750489/11733312/1c14eab4-9fa4-11e5-8208-b5ef69fd1e78.png)

**Comment by strumpfe** [comment]
This is also true of the Admin organism menu.

![organism_menu_pagination](https://cloud.githubusercontent.com/assets/2750489/11733376/a2e54124-9fa4-11e5-96a2-671d8d114bef.png)

**Comment by cmdcolin** [comment]
this had occurred to me too. as in your other comments, having some special "recent changes" type pages specifically for admin functions could help too

**Comment by nathandunn** [comment]
I'm not sure what the UI rule of thumb is, but for less than 100 it makes good sense to get rid of paging if favor of scrolling.

More than 100, having better filters might start to become optimal.
