### ISSUE TITLE
Set to upstream/downstream (canonical) splice donor/acceptor functionality

### ISSUE THREAD

**Issue by strumpfe** [GMOD/Apollo#735]
The addition of this functionality is a nice inclusion in WebApollo 2 as correcting the splice junctions, with all of the concomitant joy of zooming in and out to base level takes up much of the annotators time. I have a question and a potential UI improvement.

Firstly, the question..
It appears to me that this 'spring to splice site' functionality works once only, that is if you invoke the process of finding an upstream or downstream splice site it will edit the boundary of the exon accordingly but once set any further attempts to set the splice junction will be ineffective. This makes sense in that you have asked WebApollo to find a valid canonical splice junction (which it has) and subsequent requests are not needed as the exon is already at a valid junction. In reality the junction may not be the correct one supported by transcript or peptide similarity data. So the logic should be to find the next available upstream/downstream splice donor/acceptor not including the one at the current coordinates, i.e. find the next valid donor/acceptor each time the process is invoked. 

and the potential UI improvement..
As this functionality can be heavily used maybe having a keyboard short cut could be helpful. Its complicated by having 4 permutations so this one may not fly. I was musing about the fact that iterative select, scroll down, select operations are not good from an ergonomic point of view and could be positively RSI inducing to some.

![spring_to_splice_site_1](https://cloud.githubusercontent.com/assets/2750489/11734398/d449e10c-9fae-11e5-8eed-f3d0dcc358ab.png)

![spring_to_splice_site_2](https://cloud.githubusercontent.com/assets/2750489/11734404/e344152e-9fae-11e5-8c19-ee562cc079f3.png)

**Comment by nathandunn** [comment]
I think that @monicacecilia  might have a better answer than myself on this one.

**Comment by nathandunn** [comment]
@monicacecilia types:
>It appears to me that this 'spring to splice site' functionality works once only[...].

@strumpfe This has now been fixed.

>[...]select operations are not good from an ergonomic point of view and could be positively RSI inducing to some.

@strumpfe I wholeheartedly agree with you. One happier day we may actually make it more compliant to not causing RSI... let's keep dreaming this one.
