### ISSUE TITLE
Unclear instructions about WebApollo deployment

### ISSUE THREAD

**Issue by terrymun** [GMOD/Apollo#742]
A quick question—I find the documentations on actual WebApollo deployment a little unclear, especially to those who are not exactly familiar with server setups and/or are first time WebApollo users.

So far I have managed to:

- [x] Install all the dependencies required
- [x] Install WebApollo
- [x] Run `$ ./apollo run-local` to deploy WebApollo in test/dev mode
- [x] Performed initial setup on port 8080

&hellip;but is stuck at:

- [ ] Deploying WebApollo in production mode

The readme mentions that:

> ## Generate a war file
> 
> Users can generate a war file (for example target/apollo-1.0.2.war) that will be copied into their tomcat webapps directory for production deployments:
> 
> `apollo deploy `

So by running `$ apollo deploy` I have received a success message on the Terminal and can verify that a .WAR file has been generated. Where do I go from here? Let's say I intend to deploy WebApollo from the server path of `/var/www/html/apollo` (i.e. a subfolder in the URI space, `/apollo`), what additional configurations do I have to do?

p/s: I have installed the git repo outside the URI space, but not sure if that's a good idea after all.

**Comment by cmdcolin** [comment]
The key it to learn to use something like Tomcat :) https://tomcat.apache.org

The basic idea is that tomcat has a "webapps" directory, and if you copy a war file to the webapps directory, it detects that and automatically unzips it and starts running it.

By default tomcat will often run on port 8080, hence the reason you see that port 8080 is often used in docs.

Some parts of tomcat administration are outside the scope of our documentation, but we're happy to help with any issues and can try and improve docs as needed!

**Comment by cmdcolin** [comment]
If you have info about the system you are running, we might be able to provide more specific tips too. Folders are often slightly different across systems

**Comment by nathandunn** [comment]
@terrymun   Thanks for reporting and I'm glad you got that far!  I think the proper information is there, but we have a lot of doc and aren't probably pointing to the right places.  

Some quick questions / comments:
- what doc were you using.   I'm guessing [this](https://github.com/GMOD/Apollo/blob/master/docs/Setup.md).  It should point [here](https://github.com/GMOD/Apollo/blob/master/docs/Troubleshooting.md).
- like @cmdcolin  said, it has to be installed in a Web container of some type: https://en.wikipedia.org/wiki/Web_container  .  . . of which Tomcat and Jetty are the two most popular
- once installed you need to adjust the memory (see the troubleshooting guide above) . ..  I'll update those specs
- every system installs the servlet container differently so updating the memory, etc. will depend on the installation, but I think they all have some type of "webapps" directory

**Comment by nathandunn** [comment]
@terrymun  I've updated the instructions somewhat.  Let us know if you get it to run.  Also, make sure to set the tomcat memory (the default is far too low).

**Comment by nathandunn** [comment]
Going to close this . . let us know / re-open if it continues to be a problem.  Thanks.

**Comment by cmdcolin** [comment]
I know @terrymun has also worked on making smooth apache deployments on other projects like sequenceserver so if you'd like a tight integration between tomcat and a normal apache server, also look into the reverse proxy section of our docs! http://webapollo.readthedocs.org/en/latest/Configure.html#apache-nginx-configuration
