### ISSUE TITLE
Sequence modifications aren't included in gff3 export 

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#748]
Hi again,

I've created some sequence mods (insertion, substitution, deletion) in the Apollo 2 demo instance:
http://icebox.lbl.gov/Apollo2/annotator/loadLink?loc=Group1.1:725082..725173&organism=3836&tracks=Official Gene Set v3.2
In Web Apollo 1, the modifications were retrievable from the exported gff3 file. However, they weren't present in the exported gff3 file from this instance (I used the export options from the 'Ref Sequence' tab). 

Apologies if this is due to my lack of familiarity with Apollo 2!

**Comment by nathandunn** [comment]
This was in 2.0.0 (and working perfectly) and somehow it got removed from 2.0.1 . . . I have a few ideas where.   I'll send you the details for our training server and you can see that it *DID* work.

**Comment by nathandunn** [comment]
@cmdcolin   It looks like you'd removed the sequence alteration code from the GFF3 / FASTA output.  Can you fix this when you have a chance.

**Comment by cmdcolin** [comment]
Yep, will see. Sorry bout that

**Comment by nathandunn** [comment]
Still needs to be tested

**Comment by nathandunn** [comment]
@cmdcolin   Somehow these disappeared again.  I know they were here earlier in the GFF3 and FASTA file.

**Comment by cmdcolin** [comment]
Essentially the same as #836, will fix that here in a jiff

**Comment by monicacecilia** [comment]
It's all there :dancer: 
p.s: and the alterations should come with a warning: 'remember Apollo always searches for the longest ORF after each edit'. Where have I heard that before?! :smile:
