### ISSUE TITLE
Include full sequence of insertion or substitution as attribute in gff3 export

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#754]
It would be great if the sequence of an insertion or substitution could be included as an attribute in the gff3 export. This is currently possible through 'Reference Sequence -> Save track data', but not through the regular gff3 export.

**Comment by nathandunn** [comment]
@cmdcolin   While you're in there, could you take a look at this?  Thanks!

**Comment by nathandunn** [comment]
If its too crazy we can kick it to 2.0.3.

**Comment by monicacecilia** [comment]
I see them in there. :dancer: 
Thanks @cmdcolin
