### ISSUE TITLE
Add support for translation tables

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#757]
On release 2.0.1, Server side shows:

```
webapollo2_1 | 2016-01-04 19:15:44,856 [clientInboundChannel-4] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
webapollo2_1 | java.lang.reflect.InvocationTargetException
webapollo2_1 |  at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure3_closure4_closure5.doCall(AnnotationEditorController.groovy:1075)
webapollo2_1 |  at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure3_closure4.doCall(AnnotationEditorController.groovy:1074)
webapollo2_1 |  at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure3.doCall(AnnotationEditorController.groovy:1070)
webapollo2_1 |  at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
webapollo2_1 |  at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
webapollo2_1 |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
webapollo2_1 |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
webapollo2_1 |  at java.lang.Thread.run(Thread.java:745)
webapollo2_1 | Caused by: java.lang.NullPointerException: Cannot invoke method getStartCodons() on null object
webapollo2_1 |  at org.bbop.apollo.FeatureService._do_setLongestORF(FeatureService.groovy:994)
webapollo2_1 |  at org.bbop.apollo.FeatureService.$tt__setLongestORF(FeatureService.groovy:466)
webapollo2_1 |  at org.bbop.apollo.FeatureService._do_calculateCDS(FeatureService.groovy:448)
webapollo2_1 |  at org.bbop.apollo.FeatureService.$tt__calculateCDS(FeatureService.groovy:425)
webapollo2_1 |  at org.bbop.apollo.FeatureService._do_generateTranscript(FeatureService.groovy:194)
webapollo2_1 |  at org.bbop.apollo.RequestHandlingService.$tt__addTranscript(RequestHandlingService.groovy:651)
webapollo2_1 |  ... 8 more
```

whenever I attempt to create a `gene` type feature from a gff3 snippet which looks like this:

```
##gff-version 3
##sequence-region NC_005880 1 148317
NC_005880	.	gene	40096	40436	.	-	.	ID=gene_80
NC_005880	.	CDS	40096	40422	.	-	0	ID=cds_gene_80;Parent=gene_80
NC_005880	.	Shine_Dalgarno_sequence	40432	40436	.	-	.	ID=rbs_gene_80;Parent=gene_80
```

I've tried adding mRNAs and mRNAs + exons to the gene model, but neither of those display as nicely in JBrowse for whatever reason. They also generate the same error on trying to create a gene feature from them.

![selection_521](https://cloud.githubusercontent.com/assets/458683/12098204/3e6d6fbe-b2e6-11e5-9096-3c2ea2a08661.png)

(-mRNA-exon, +mRNA+exon, +mRNA-exon respectively)

**Comment by erasche** [comment]
Hmm, this may not be the latest 2.0.1 release, let me double check that.

**Comment by nathandunn** [comment]
The error is being triggered here:

https://github.com/GMOD/Apollo/blob/release/2.0.1/grails-app/services/org/bbop/apollo/FeatureService.groovy#L994

implying that the translation table is null.  

Mostly likely you are using a translation code not 1 (apollo get_translation_code), which should be fine, but we haven't re-enabled it.   

If that is the case, let me know and we can re-add it.   It should be pretty easy to do.

**Comment by erasche** [comment]
Okay, thanks for the help tracking it down. The table is set to 11 (assuming my config file is correct), I'll test with table 1.

**Comment by erasche** [comment]
Tested with table 1 and it worked immediately. It'd be great if support was re-added for other tables.

**Comment by nathandunn** [comment]
Okay . .  we'll try to get to it by this week.

**Comment by erasche** [comment]
Thanks @nathandunn!

**Comment by hdzierz** [comment]
Hi There,

I get the same error even though I have actually re-built erasche's docker container with the latest version of Apollo. Can you please clarify where you configure the translation table?

Thanks

Helge

**Comment by erasche** [comment]
Hi @hdzierz 

This error should've been fixed in the `:latest` image. The image defaults to using translation table 1, but you can configure that with an environment variable [as I do](https://github.com/erasche/docker-webapollo2/blob/master/docker-compose.yml#L13). I'll test this shortly. (Or perhaps you're experiencing a slightly different error?) (Also, wow, great to hear that someone is using the images! I hope they're working ok. Let me know if you have feature requests!)

**Comment by nathandunn** [comment]
Nothing to user test.
