### ISSUE TITLE
Removing dbxrefs visually removes features from track

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#764]
On page reload the feature is still there, just disappears temporarily from the user-created annotation track. No rush, I know y'all are getting ready for PAG.

To reproduce:

- create feature -> gene
- edit information
- add Dbxref (I usually entered "IPR" and "10231023" (or some other string of numbers))
- do not select any dbxrefs, click "delete"

Reproducible on http://icebox.lbl.gov/Apollo2/annotator/loadLink?loc=Group1.1:644263..647766&organism=3836&tracks=Official%20Gene%20Set%20v3.2

Interesting notes:

- Seems to remove multiple features if they share the same location. If they share non-identical locations, only the selected feature will disappear.

**Comment by cmdcolin** [comment]
Re-appears after a refresh but does seem reproducible otherwise

**Comment by cmdcolin** [comment]
I think this is the fix for this bug. Need to send an "update" annotation event, rather than a delete 


    diff --git a/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy b/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
    index bc22e20..9583cdf 100644
    --- a/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
    +++ b/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
    @@ -188,7 +188,7 @@ class RequestHandlingService {
                 AnnotationEvent annotationEvent = new AnnotationEvent(
                         features: updateFeatureContainer
                         , sequence: sequence
    -                    , operation: AnnotationEvent.Operation.DELETE
    +                    , operation: AnnotationEvent.Operation.UPDATE
                 )
                 fireAnnotationEvent(annotationEvent)
             }

**Comment by erasche** [comment]
Yep, confirmed, patch fixes it for me.

**Comment by nathandunn** [comment]
Cool.  Just put it in as part of the other pull request.
