### ISSUE TITLE
remove split panel where it hides the interface in the SplitPanel

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#768]
- [x] remove SplitPanel in favor of DockPanel (or similar mechanism)
 - [x] annotator panel
 - [x] sequence panel
 - [x] user panel
 - [x] group panel

**Comment by nathandunn** [comment]
This actually hides some of our functionality so moving up.  Should be an easy fix.

**Comment by nathandunn** [comment]
Switched to bootstrap and looks like this. . . but having issues getting the exons to show up.  Also, we need some type of scrolling mechanism. 

<img width="559" alt="screen shot 2016-02-02 at 11 53 43 am" src="https://cloud.githubusercontent.com/assets/751274/12762362/ad6f7cc6-c9a3-11e5-8baf-79df773b33a4.png">

**Comment by nathandunn** [comment]
I stashed this . . this is probably because EVERYTHING needs to be bootstrap

**Comment by cmdcolin** [comment]
I feel like now the "details" and "coding" part takes up too much room. 

 Previously I would use the slider to make it go away, but now without the slider, it cannot be adjusted.

A close/(x) button would work too

**Comment by nathandunn** [comment]
@cmdcolin   I would agree that you need something like a disclosure panel.   If you want to add something, that would be great.

**Comment by monicacecilia** [comment]
This issue -which is #768- references PR #844, which references #778, which is related to #746, which is not ready. SO this, isn't ready either. :unamused:

**Comment by nathandunn** [comment]
@monicacecilia  #746 is very tangentially related to this and isn't really referenced here.  #778 is fixed here.  This was more the case where the split panels in Sequence and AnnotatorPanel (and to a lesser extent some of the other ones) would hide portions of the interface.   I think that this works now if you didn't notice this on those panels.  Please re-open if it is a problem.

**Comment by nathandunn** [comment]
I think this issue just needs clarification in 2.0.0-2.0.1 you could get this case where the "user" selection is hidden and details are obscured:

<img width="610" alt="screen shot 2016-03-04 at 11 12 30 am" src="https://cloud.githubusercontent.com/assets/751274/13537492/0ace36aa-e1fa-11e5-9a80-31c6fad161f5.png">

In 2.0.2 this is no longer possible as it fills the space given:

<img width="526" alt="screen shot 2016-03-04 at 11 13 49 am" src="https://cloud.githubusercontent.com/assets/751274/13537523/37807474-e1fa-11e5-89d9-0304f0b0eb22.png">

**Comment by monicacecilia** [comment]
:dancer:
