### ISSUE TITLE
Add label to History window to identify revert button

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#769]
In the 'History' window, add a label that identifies the function of the 'revert' button.
Suggested by @adnguyen999

**Comment by monicacecilia** [comment]
@deepakunni3 already working on this

**Comment by monicacecilia** [comment]
Assigned to @nathandunn for review. :bowtie:

**Comment by monicacecilia** [comment]
One thing not behaving as expected, though.... Sorry, I just caught this back. 

 When I use the revert button in the 'History' panel: ![screen shot 2016-03-03 at 4 46 18 pm](https://cloud.githubusercontent.com/assets/1714621/13514642/7e9052b2-e15f-11e5-9dca-a1317803b521.png) I expect the bookmark ![screen shot 2016-03-03 at 4 47 07 pm](https://cloud.githubusercontent.com/assets/1714621/13514652/98f80f00-e15f-11e5-9dcd-a756395dd4f6.png) to shift positions in order to indicate the 'new' current gene model. The image representing the gene model is updated, but the bookmark drawing remains With the version of the gene model that was available when I first pulled up the 'History' panel. -- It should also change right away. 

 You can close the 'History' panel and open it again to see the new placement of the bookmark. But it should happen right away.

**Comment by monicacecilia** [comment]
I'm tolerant of punting this down to 2.0.3, given that it is a minor thing - but it should be fixed ASAP after this release.

**Comment by nathandunn** [comment]
I think that it makes sense.

**Comment by nathandunn** [comment]
I do think I tried to work on this, but I can't remember if there were some minor issues preventing this.   Anyway, I'm sure its doable.

**Comment by nathandunn** [comment]
@deepakunni3   I think you just need to modify this code:

https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/AnnotTrack.js#L3410-L3425

You could handle it in the callback, but I think that this would be easier.  I think you *could* just add/remove the [iconClass](https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/AnnotTrack.js#L3559) and change the [labelText](https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/AnnotTrack.js#L3518-L3529).

**Comment by nathandunn** [comment]
It could be that we don't use the iconClass at all if that ends up being easier.  I think a * or a left-arrow should convey the same meaning.  http://www.webstandards.org/learn/reference/charts/entities/symbol_entities/

**Comment by monicacecilia** [comment]
Great, so clicking on the 'revert' button genomic element back to that state, and the 'bookmark' symbol now moves to the reverted state. This is great! 💃 
![screen shot 2016-06-02 at 10 53 36 am](https://cloud.githubusercontent.com/assets/1714621/15755116/3bd0d756-28b0-11e6-8a7f-10cb49bf7043.png)

However, the original request of adding a label to the button or to the column that reads 'Revert' or explains what the button is for, has not been met. Could we please add the words 'Revert to' at the top of this column? 

thanks!

**Comment by nathandunn** [comment]
I think that "Set" looks better.

![screen shot 2016-06-02 at 11 38 31 am](https://cloud.githubusercontent.com/assets/751274/15756584/c12cb7a2-28b6-11e6-8c22-7770a46f54ab.png)
![screen shot 2016-06-02 at 11 38 14 am](https://cloud.githubusercontent.com/assets/751274/15756585/c13b7fda-28b6-11e6-98d0-e2b1957afa4a.png)

**Comment by nathandunn** [comment]
@monicacecilia  Can you supply some feedback on the verbiage for above?

https://github.com/GMOD/Apollo/issues/769#issuecomment-223383479

Words are hard.

**Comment by monicacecilia** [comment]
How about just '_Revert_'?
'_Set_' by itself does not convey much meaning in this context.

**Comment by nathandunn** [comment]
👍

**Comment by monicacecilia** [comment]
💃
