### ISSUE TITLE
Granting "administrative" privilege on organism grants write permission to user database

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#771]
I recently discovered (through testing, thankfully not the "hard way") that granting the administrative privilege on an organism grants write access to the user database. 

The webservices docs say:

> `administrate` boolean - Indicate if user has administrative privileges for the organism

I would have expected by the docs, that granting the administrative privilege would allow the user to modify other user's permissions on an organism. However it seems to go the extra step to grant them the about to modify other user's names and emails.

**Comment by monicacecilia** [comment]
yikes! :scream: 
Thanks for catching that @erasche !

**Comment by monicacecilia** [comment]
@erasche @nathandunn 
We should have a discussion about what the possible scenarios are. Currently, admins can add, modify, and delete details about users. 

@erasche What is your case here? An administrator who can access / add/ modify the genomic data but is not able to access the users? Perhaps we are talking about some 'mid-level' permissions?

**Comment by erasche** [comment]
@monicacecilia . I was mostly just playing around with what was possible through the API, so this is less of a use case and more a user-story that might be applicable to other admins.

I see three levels of administrators:

| Level | Use Case / Permissions |
| --- | --- | 
Organism admins | Some users are administrators of a single organism. They should be able to add collaborators to help with their annotation process. Should not be able to edit any user details |
| Group admins | some users are administrators of a group of organism. They should be able to modify the group membership, and act as organism admins for individual organisms, adding/removing specific collaborators. (Maybe) can edit name / email for members of their group |
| Site admin | Current "admin" status, can manage everything |

**Comment by nathandunn** [comment]
@erasche  So, I think what we have right now is "Group" Admin (what we are calling organism admin).  I'm not sure if the use-case for "Organism" admin as you defined it would be in demand, but @monicacecilia might know better.

**Comment by erasche** [comment]
@nathandunn that works fine for me, an organism admin is overkill.

**Comment by nathandunn** [comment]
Alright, I'll fix this in the doc.

**Comment by monicacecilia** [comment]
:+1:

**Comment by monicacecilia** [comment]
@nathandunn just let me know when this has been update in the docs and we'll close. :bowtie:

**Comment by nathandunn** [comment]
Its in the web services doc.  I'll let you know when we deploy to staging.

**Comment by monicacecilia** [comment]
10-4.

**Comment by monicacecilia** [comment]
:dancer:
