### ISSUE TITLE
API to edit names of features

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#776]
I'm not seeing this in the current webServices documentation. Is it correct to think that there's no API for editing the name of features?

My use case is that we have students pick amongst multiple gene models to annotate a genome. After this process, the names are possibly quite out of order. We'd like to edit the names of every feature on the user created annotation track and rename the features sensibly before downstream analysis starts.

I'm happy to (try and) write this if it doesn't exist, but figured I'd file an issue here first in case.

**Comment by erasche** [comment]
Oh, it's already done, just not exposed to webservices. Ok. adding.

**Comment by nathandunn** [comment]
Awesome thanks!
