### ISSUE TITLE
Problem of deleting a user account, make users "inactive" instead of deleting

### ISSUE THREAD

**Issue by adnguyen999** [GMOD/Apollo#777]
Unable to delete a user account that has been assigned to an organism:

ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`apolloproduction`.`preference`, CONSTRAINT `FK_ro87rogww8hoobbwya2nn16xk` FOREIGN KEY (`user_id`) REFERENCES `grails_user` (`id`))

Suggesting solution:
ALTER TABLE 'preference' ADD CONSTRAINT 'FK_ro87rogww8hoobbwya2nn16xk` FOREIGN KEY ('user_id') REFERENCES 'grails_user' ('id');

**Comment by monicacecilia** [comment]
Thanks Anh-Dao!
@nathandunn we need to check whether this behavior has been fixed in v2.0.1

**Comment by monicacecilia** [comment]
Currently, a user with annotations to any organism cannot be deleted - this may be the source of the error. 
Instead we need to add:
- [ ] the ability to create _inactive_ users and 
- [ ] the ability to change an _active_ user into an _inactive_ one

**Comment by mpoelchau** [comment]
Sorry to be late to the discussion! In response to the discussion in issue #1175: 

Yes, to inactive users. However, how exactly would this differ from removing all permissions from all organisms? Would you change the 'global role' to 'inactive' in this case?

**Comment by nathandunn** [comment]
@mpoelchau  Yes, it would be globally inactive.  The key, is if there is any data associated with that data, we don't disassociate it, but a user can no longer log-in and they don't show up to normal users in lists.

**Comment by childers** [comment]
@nathandunn so are you thinking about making another account type "inactive" (or whatever) that ignores any permission settings or groups? That way group or separate permissions can be retained in the case the account gets reactivated?

**Comment by nathandunn** [comment]
@childers  That might be easier or just strip the permissions.  Typically if they have to be re-activated you'd want to re-review, but if its an advantage we can see.

**Comment by nathandunn** [comment]
@childers  / @mpoelchau  This is working in the way you are doing it now.  It just strips all permissions and groups (and some other metadata).    No filter, but this should solve most of your problems.  You can probably just change the username in the interim.  Hopefully this will save you time. 

Fixed by #777

**Comment by nathandunn** [comment]
Fixed by #1936
