### ISSUE TITLE
add an interim export panel

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#78]
Regarding the ability to export: would still like to be able to turn off the FASTA part of this (makes the file smaller) and would like to see options for including the author and timestamp data so that the data can be used downstream when it comes to processing/filtering the files.

**Comment by nathandunn** [comment]
I *think* that this is done (a while ago), but please verify my understanding.

**Comment by cmdcolin** [comment]
Do we include include "Owner/created by" in the exports yet?

**Comment by nathandunn** [comment]
We include "owner" but not "edited by", though 99% of the time, I would guess that they are similar . . unless added via a bulk export.

**Comment by cmdcolin** [comment]
Sounds good. This is a small quip about GFF3 format but apparently the "Owner" tag in our GFF3 is upper case, which is technically a reserved field in GFF3.

**Comment by nathandunn** [comment]
Can you should me where it is reserved?  I couldn’t find it, but I just want to see if it is something we should change. 

Thanks,

Nathan

**Comment by cmdcolin** [comment]
From http://sequenceontology.org/resources/gff3.html

"All attributes that begin with an uppercase letter are reserved for later use. Attributes that begin with a lowercase letter can be used freely by applications."

**Comment by nathandunn** [comment]
Thanks.   We should fix that.   I’ll add a ticket.  

Nathan

**Comment by monicacecilia** [comment]
Annotator panel, RefSequence tab offers option to download GFF3 with and without FASTA. Dialog box contains clear, easy to understand options. :dancer:
