### ISSUE TITLE
Foreign key constraints

### ISSUE THREAD

**Issue by adnguyen999** [GMOD/Apollo#780]
Tried to delete some data in the "feature" table and got errors:

ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`apolloproduction`.`feature_grails_user`, CONSTRAINT `FK_4dgbhgiw0vb9hqy2k5fqg3neh` FOREIGN KEY (`feature_owners_id`) REFERENCES `feature` (`id`))

Suggesting solution:
add fk constraint to table feature_grails_user

**Comment by nathandunn** [comment]
Hmm . . was there anything special about the feature that was annotated?  Have not run into this yet.

**Comment by monicacecilia** [comment]
@andguyen999 We discussed that this should be done using Web Services.
