### ISSUE TITLE
Add notes to sequence alterations

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#781]
Offer the possibility to include notes with further explanations for each  sequence alteration.

**Comment by monicacecilia** [comment]
@NehaVC already working on this

**Comment by deepakunni3** [comment]
Currently the notes are treated as non reserved properties for created SequenceAlteration with the tag 'Justification'.

**Comment by monicacecilia** [comment]
Assigned to @nathandunn for review. :bowtie:

**Comment by nathandunn** [comment]
Test: 
- Confirm editing
- Confirm view after edit
- Confirm export in GFF3
- Confirm export in FASTA

**Comment by monicacecilia** [comment]
After sequence alteration is added, cannot pull up 'Information'
![screen shot 2016-03-03 at 5 28 41 pm](https://cloud.githubusercontent.com/assets/1714621/13515353/7286185c-e165-11e5-90b8-b0113194fb3f.png)

Error reads:
 <code>TypeError: Cannot read property 'data' of undefined(…)</code>

Error persists after hard refresh.

**Comment by monicacecilia** [comment]
Test list from @nathandunn : 
- [x] Confirm editing. - Editing is possible.
- [x] Confirm view after edit. - Edit is visible, however, 'Information is not available- see below
- [x] Confirm export in GFF3
- [x] Confirm export in FASTA. - yes, alteration is taken into account when writing updated CDS, genomic, protein sequences.

**Comment by deepakunni3** [comment]
Having trouble reproducing this on master.

I also tested on `http://icebox.lbl.gov/Apollo-staging/` and cannot reproduce the bug.
The region I tested was `Group1.10:624846..625117`

**Comment by nathandunn** [comment]
Okay, I’ll take another shot at it as well. 

Nathan

**Comment by nathandunn** [comment]
@monicacecilia   I'm not seeing this either . . best tester name though.  Re-open if you reproduce.  

<img width="490" alt="screen shot 2016-03-04 at 8 48 35 am" src="https://cloud.githubusercontent.com/assets/751274/13533588/fe3b5f9e-e1e5-11e5-955f-ca167e5be9f4.png">
<img width="459" alt="screen shot 2016-03-04 at 8 48 26 am" src="https://cloud.githubusercontent.com/assets/751274/13533589/fe3e0d16-e1e5-11e5-833f-efd9aa619553.png">

**Comment by monicacecilia** [comment]
The problem, then, seems to be that Apollo is temperamental about response actions and time. I tried three different browsers and clean caches yesterday --- and I saw no details for 'Information'. 
I'm glad it is magically fixed! We have a good faerie godmother. :crown:
