### ISSUE TITLE
Viewing one strand at a time has strange behavior

### ISSUE THREAD

**Issue by mscampbell** [GMOD/Apollo#782]
This is what it looks like when I view both strands
<img width="465" alt="screen shot 2016-01-15 at 2 42 02 pm" src="https://cloud.githubusercontent.com/assets/6146248/12367383/58a7e540-bb96-11e5-8ce4-aab72d1184f8.png">

This is what it looks like when I view the minus strand
<img width="496" alt="screen shot 2016-01-15 at 2 41 44 pm" src="https://cloud.githubusercontent.com/assets/6146248/12367397/6d5ba01c-bb96-11e5-9c31-1a7519e57969.png">

This one is the problem. This is what it looks like when I try to view the plus strand only
<img width="454" alt="screen shot 2016-01-15 at 2 42 36 pm" src="https://cloud.githubusercontent.com/assets/6146248/12367420/9d1c611a-bb96-11e5-9f72-fe8b00a07520.png">

**Comment by monicacecilia** [comment]
Yep, a bug indeed :beetle: 
I can confirm that when toggling off the 'Show minus strand' box, all genomic elements  - in both directions - disappear from the window.
