### ISSUE TITLE
Unable to retrieve GFF3 from pseudogenes

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#784]
When trying to retrieve GFF3 files from pseudogenes, using any of the available methods (right-click menu over the genomic pseudogene, the 'Save track data' option, export GFF3 from 'Annotator Panel'), the GFF3 is not produced. Instead a blank window or an empty file are visible.

This was working well on v2.0.0. It is not working correctly in v2.0.1.

Error on browser reads:
<img width="1387" alt="screen shot 2016-01-15 at 3 49 31 pm" src="https://cloud.githubusercontent.com/assets/1714621/12368365/9ba2e1b6-bb9f-11e5-9a82-6dc4a70d5e77.png">

**Comment by monicacecilia** [comment]
Can also confirm it is a bug in v2.0.2

**Comment by nathandunn** [comment]
Related to #748 .

**Comment by monicacecilia** [comment]
I can confirm that his has been fixed. 
:dancer:
