### ISSUE TITLE
add filter summary of predictions by user

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#79]
A simple summary overview of the number of predictions (with some sort of faceting/breakdown) available under the admin tab would be really useful. These are more operational things about how people use WebApollo as part of a community annotation project rather than issues with the interface/functionality etc. Dan Lawson commented on wishing to get statistics of the number of predictions broken down by user, currently not a simple thing to do.

**Comment by nathandunn** [comment]
This might come in 2.0  as well.

**Comment by nathandunn** [comment]
can probably be added to a report page

**Comment by nathandunn** [comment]
To Test, verify this for:
- The reports page
- The Annotation tab.

**Comment by monicacecilia** [comment]
@nathandunn, what is the URL for is this "reports" page?

**Comment by nathandunn** [comment]
Anything on the admin panel.  The reports are specifically any of the ones below "Statuses":

![screen shot 2015-08-12 at 10 54 08 am](https://cloud.githubusercontent.com/assets/751274/9232086/895ec6ee-40e0-11e5-9055-e89ba2cdff73.png)

**Comment by monicacecilia** [comment]
Is this window supposed to be so slow to respond? e.g. ~45 seconds to display the second page of users. 

Also, do these boxes export something? if so, how do you retrieve the information? (clicking on them does not do anything), and if not, why can you "click" on them?

![screen shot 2015-08-12 at 11 03 05 am](https://cloud.githubusercontent.com/assets/1714621/9232323/da9d6398-40e1-11e5-856b-43086b18c1f9.png)

**Comment by nathandunn** [comment]
This was just a first-pass .. was originally intended for 2.0.1.  Haven't tested it with so much data.  Was not going to be in this release at all, but we had some time.  

I've not gotten any feedback on this, so I would suggest move this to 2.0.1 with suggested improvements, or closing this and opening a new issue with the suggested improvements for 2.0.1.

**Comment by nathandunn** [comment]
Also #488 is going to replace a lot of this.

**Comment by monicacecilia** [comment]
Then we should update the milestone.

**Comment by monicacecilia** [comment]
There's still a bug here. I am unable to look past the first page for any 'Sequences Report", except the human one. 

To reproduce: 
- Go to Annotator Panel/Admin/Report:Sequences report page, for example while looking at the Honey Bee genome. 
- Notice that the page automatically defaults to Human-Hg38 Sequences. 
- Switch to a different organism, and try either clicking on 'Next' or any page number other than '1' from the scroll index at the bottom of the page. 
![screen shot 2016-03-03 at 2 31 52 pm](https://cloud.githubusercontent.com/assets/1714621/13511988/c4458da8-e14c-11e5-927b-1a7358325f32.png)
- Notice that it always goes back to the first page of sequences from 'Human-Hg38'.

**Comment by nathandunn** [comment]
Have a one line fix for this .. Will push in a few. 

Nathan

**Comment by nathandunn** [comment]
Fixed by pull #917

**Comment by monicacecilia** [comment]
Well, This is what happens now when selecting the Honey Bee report. 
Behavior with other organisms has not changed - goes back to Human. 

I don't know if you already updated the server, but it got worse... 

<code>GET http://icebox.lbl.gov/Apollo-staging/sequence/report/3836 500 (Internal Server Error)changeOrganism @ (index):47onchange @ (index):149
Navigated to http://icebox.lbl.gov/Apollo-staging/sequence/report/3836
3836:90 GET http://icebox.lbl.gov/Apollo-staging/assets/restapidoc/restapidoc.js </code>

![screen shot 2016-03-03 at 6 56 42 pm](https://cloud.githubusercontent.com/assets/1714621/13516726/b1d69c78-e171-11e5-81f1-89241d23a09d.png)

**Comment by nathandunn** [comment]
I haven't actually had a chance to push this fixed yet so should be the same.

Nathan

**Comment by nathandunn** [comment]
@monicacecilia  I'll assign it to you when its ready to review (i.e., tagged) ;)

**Comment by nathandunn** [comment]
Am getting this error on staging, but only for honeybee . . . :

```
g.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Cannot invoke method div() on null object
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Cannot invoke method div() on null object
	at org.bbop.apollo.report.OrganismSummary.getProteinCodingTranscriptPercent(OrganismSummary.groovy:30)
	at gsp_apollo_sequencereport_gsp$_run_closure2.doCall(gsp_apollo_sequencereport_gsp.groovy:79)
	at gsp_apollo_sequencereport_gsp.run(gsp_apollo_sequencereport_gsp.groovy:109)
```

**Comment by nathandunn** [comment]
```
        transcriptCount && transcriptTypeCount? ((float) transcriptTypeCount.get("MRNA") / (float) transcriptCount).round(2) : 0
```

obviously MRNA is null when pulling out this type

**Comment by nathandunn** [comment]
This is very weird since the data is in there correctly.

**Comment by nathandunn** [comment]
This is fixed now. https://github.com/GMOD/Apollo/commit/c612459254d600641da12c74b9f5866381caa0e3

Was occurring if ONLY a non-MRNA feature was annotated on a scaffold.

**Comment by nathandunn** [comment]
Just as an FYI *ALL* of these report pages were done sort of quick and dirty with the idea that other folks would create their own reports.  However, at some point we should maybe think about cleaning them up.

**Comment by monicacecilia** [comment]
@nathandunn Thanks for the FYI. 
Is it possible to make the list of Annotators wrap around the box instead of extending it to the side?

![screen shot 2016-03-04 at 12 27 10 pm](https://cloud.githubusercontent.com/assets/1714621/13539326/85fcd228-e204-11e5-8d21-d9d9119f7e21.png)

**Comment by nathandunn** [comment]
Sure.   Surprised it didn’t already do that.  

Nathan

**Comment by monicacecilia** [comment]
Please close when you fix the wrapping. :)

**Comment by nathandunn** [comment]
Does wrap, but we can probably do better than that . . as there doesn't seem to be any padding:  

![screen shot 2016-03-04 at 2 04 47 pm](https://cloud.githubusercontent.com/assets/751274/13541610/27a39ac8-e212-11e5-86aa-e994b377d812.png)

Fixed . . buttons are buttons and not-buttons are not buttons and spacing is fixed:

![screen shot 2016-03-04 at 2 32 30 pm](https://cloud.githubusercontent.com/assets/751274/13542195/f3069366-e215-11e5-90d1-fe9bf437e405.png)
