### ISSUE TITLE
add a loading icon for long operations

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#791]

**Comment by monicacecilia** [comment]
Especially for 'Merge' and 'Split' functions.

**Comment by nathandunn** [comment]
@cmdcolin   I looked at this a bit.   I think that this will be VERY tricky with using something like the "standby" icon because the function (as a post) and response (as a websocket) are called in completely different contexts.   The only thing I was thinking (and may end up doing for other stuff) is to create a unique "event" key so a function can tell if its return event is coming back or another one is. 

Anyway, I'm happy to bump this to 2.0.3 with all of the other optimizations we have going on.  

Thoughts?

**Comment by cmdcolin** [comment]
I had been sort of interested in the trying to resolve the idea of the request and response being in different contexts too, but don't have any good idea at the moment

**Comment by nathandunn** [comment]
Well, let's punt this until 2.0.3 then.   I'll create a related issue for it.
