### ISSUE TITLE
merging and undo causes error

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#792]
- [x] test undo/undo merge:  add A (A1), add B (B1), change A (A2), merge A/B (AB), undo, undo (should both be there , A1, B1) == AB
  - [x] undo (A2/B1), redo A (AB)
  - [x] undo (A2/B1), redo B (AB)
  - [x] undo (A2/B1), undo (A1/B1) (test in an d failing)
- [x] test undo/ redo split: add A (A1), STE (A2), split (A3, B1), Flip B (B2)
   - [x] undo A (==A2) / redo B (A3/B2)
   - [x] undo A (==A2) / redo A (A3/B1), redo (A3/B2) (test in and failing)
   - [x] undo B (==A3/B1), undo B (==A2) (test in and failing)
   - [x] undo B (==A3/B1), redo B (==A3/B2)
- [x] set history fails (to the same place as undo) works on B, which fails (undo works on A?):
   - [x] **get history size is 0** . . . calling with B, not A . . . either search for others if not 
- [x] the original use-case should work correctly 
- [x] undo vs "setHistory" gives different results:
  - [x] **add tests for "findAllPrevious" sorted oldest(0) to newest (2) order (without a "sort" call)**
  - [x] **add tests for "findAllFuture" sorted oldest(0) to newest (2) order (without a "sort" call)**
  - [x] when calling it goes 2-1-1, instead of 1-2-1 . . . 1 should be the first add-transcripts . . does in both integration and unit tests
  - [x] **currentFeatureEvent ONLY returns a feature on an undo of a merge** . . should be the same 
  - [x] undo does A (merge to add transcript), which does "B" perfect, but then drops "A", which is confusing for either
- [x] generateHistory should mirror getHistory . . . feature on middle operation should have multiple features . . if just 1
- [x] unit test for a merge / modification on either side (getHistory  and getFutureEvents) . . . similar to this in FeatureEventServiceSpec:
   - [x] create test 
   - [x] validate test
   - [x] fix code to fix test 
- [x] create integration test that does the same thing:
   - [x] fix integration test (currently filters away wrong thing)
- [x] show history should work correctly (hides "current" / merge): 
  - [x] fix "currentFeature" part

====

Found by @monicacecilia 

```
Caused by: org.bbop.apollo.AnnotationException: Feature event list is the wrong size 0
```
Was working in 2.0.0.  

To reproduce: 
- Gene 1: GB40005
- Gene 2: GB40006

Steps:
- Add Gene 1
- Add Gene 2
- Modify Gene 1
- Merge Gene 2 to 1
- Undo merge

Expected Result:
- Gene 1 and Gene 2 are separate with the modification to Gene 1 

Observed Result(s):
- Fails to delete Gene 1, but does the merge correctly 

Modifying Gene 2 . . works fine.  

There are some other ways to make it fail.

**Comment by monicacecilia** [comment]
It is directional --- breaks left to right (not tied to direction of transcription).

**Comment by nathandunn** [comment]
Also easy to reproduce with 6 and 7 and also 15 and 16.   Did not happen with 31 and 32 or 18 and 17.

**Comment by nathandunn** [comment]
It seems to be 5' to 3', but otherwise non-directional.

**Comment by nathandunn** [comment]
I wonder if the infinite recursion "fix" caused this.  May need a better solution.

**Comment by nathandunn** [comment]
Noticed then when you do the merge you get this result:

<img width="780" alt="screen shot 2016-01-22 at 12 26 03 pm" src="https://cloud.githubusercontent.com/assets/751274/12522076/5e4a88b4-c103-11e5-9ef6-16188e87e2d8.png">


Checking the database gets a similar result . . the "merge" operation is never logged.

**Comment by nathandunn** [comment]
This is read EXACTLY out of the data.  So, that is a problem, as well, though what is stored in the database is perfect.

**Comment by nathandunn** [comment]
Even though it is returning data from the "retrieved" unique name, it seems to grab data only from the other side.

**Comment by nathandunn** [comment]
<img width="671" alt="screen shot 2016-01-22 at 12 43 21 pm" src="https://cloud.githubusercontent.com/assets/751274/12522630/924f7eaa-c106-11e5-9afb-9ffa11589996.png">
<img width="983" alt="screen shot 2016-01-22 at 12 43 15 pm" src="https://cloud.githubusercontent.com/assets/751274/12522631/92572574-c106-11e5-8913-0c131fb7c812.png">

**Comment by nathandunn** [comment]
Doing the same modification on the other gene yields the proper history.

**Comment by nathandunn** [comment]
Looking deeper into the "showHistory" aspect . . . When I do it on the RHS / upstream where it works I get a history of 3 (1/2/1).   My test seems to pass for some reason.  Not sure why, though.

**Comment by nathandunn** [comment]
The correct map is returned, but the "current" feature event is mis-identified.

**Comment by nathandunn** [comment]
- [ ] create unit test for a merge / modification on either side (getHistory  and getFutureEvents) . . . similar to this in FeatureEventServiceSpec

**Comment by nathandunn** [comment]
```undo_errors``` is the branch

**Comment by nathandunn** [comment]
There are a few issues:
1 - History is a "per-feature" thing.  If we have splits / merges, we can have multiple features, but we are only tracking a single transaction. 
2 - When getting history, etc. we DO want to get everything, so we want to use a slightly different mechanism.

**Comment by nathandunn** [comment]
Looks like the problem is that the index of the current feature event is miscalculated.  The FeatureEventMap (events per unique name) is defined in the tables above, but if the uniqueName is stored with the second uniqueName, it doesn't use the other merge ID to calculate parent.

**Comment by nathandunn** [comment]
![screen shot 2016-01-26 at 12 50 32 am](https://cloud.githubusercontent.com/assets/751274/12576202/d7a92682-c3c6-11e5-8f15-1f558a646dc7.png)

**Comment by nathandunn** [comment]
Unfortunataely, this is what gets rendered in "getHistory", which is obvioulsy incorrect by a lot. 

<img width="534" alt="screen shot 2016-01-26 at 10 53 47 am" src="https://cloud.githubusercontent.com/assets/751274/12591106/189347aa-c41b-11e5-8925-8a4725d2fa3f.png">

**Comment by nathandunn** [comment]
Though the FeatureEvent Map is correct.  The issue is when it adds the "previous" it reverses the sort.  Sort is done by dateCreated.

**Comment by nathandunn** [comment]
Should be notesd that when getting history, the array is returned from oldest (0) to newest (2).

**Comment by nathandunn** [comment]
Not every tree will have a (0) branch.  

I think the error is that when we do a "findAllPrevious" or "findAllFuture" they need to be delivered from 0->N oldest to newest so that they will always be sorted on delivery.

**Comment by nathandunn** [comment]
Use feature event graph to quickly find current feature (0 or 1 for each key).  

Generating history is just taking the current and adding each one to the proper index, merging the indices and adjusting to start at 0.

Undo / redo follows the graph forward and deletes or adds branch  if going through a split or merge.

Need to check the tests that they confirm this.

**Comment by monicacecilia** [comment]
Yes, it does cause an error. 
And it has not gone away. :cry: 

Tested like this: 
1. Drag GB40012
2. Drag GB40011
3. Shift-click to select one exon from each and use right-click menu to 'Merge'
4. Check History - looks it's ok
5. Undo Merge
6. Check History - looks ok for both gene models. 
7. Delete one exon from GB40011
8. Check History for GB40012, and...
- Error: <code>ErrorCtor {message: "Unable to load ../AnnotationEditorService status: 500", response: Object, status: 500, responseText: "<!DOCTYPE html>↵<!--[if lt IE 7 ]> <html lang="en"…lay:none;">Loading&hellip;</div>↵</body>↵</html>↵", xhr: XMLHttpRequest}</code>
- Image: ![screen shot 2016-03-03 at 5 52 33 pm](https://cloud.githubusercontent.com/assets/1714621/13515788/3a090c56-e169-11e5-9143-8b2aaf47c8f6.png)

I also tried it with gene models in the positive strand, same results.

**Comment by nathandunn** [comment]
Dang . . thanks for catching that.  Appreciate the detail.  Note.  History shows up for GB40011.  

```
neybee/data//tracks.conf
| Error 2016-03-03 20:20:46,789 [http-bio-8080-exec-8] ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [POST] /apollo/AnnotationEditorService - parameters:
data: {"operation":"get_history_for_features","features":[{"uniquename":"701432d7-f95f-4a24-ad0d-05731fe85db6"}],"track":"Group1.33"}
{ "track": "Group1.33", "features": [ { "uniquename": "701432d7-f95f-4a24-ad0d-05731fe85db6" } ], "operation": "get_history_for_features" }: 
Stacktrace follows:
Message: null
    Line | Method
->>  795 | $tt__buildMap                in org.bbop.apollo.FeatureEventService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    806 | $tt__buildMap                in     ''
|    386 | $tt__findFutureFeatureEvents in     ''
|    824 | $tt__generateHistory         in     ''
|    129 | _do_getHistoryForFeatures .  in org.bbop.apollo.AnnotationEditorController
|    198 | doFilter                     in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . . . . . . . in grails.plugin.cache.web.filter.AbstractFilter
|     65 | handleOperation              in org.bbop.apollo.AnnotationEditorController
|    198 | doFilter . . . . . . . . . . in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter                     in grails.plugin.cache.web.filter.AbstractFilter
|    449 | executeChain . . . . . . . . in org.apache.shiro.web.servlet.AbstractShiroFilter
|    365 | call                         in org.apache.shiro.web.servlet.AbstractShiroFilter$1
|     90 | doCall . . . . . . . . . . . in org.apache.shiro.subject.support.SubjectCallable
|     83 | call                         in     ''
|    383 | execute . . . . . . . . . .  in org.apache.shiro.subject.support.DelegatingSubject
|    362 | doFilterInternal             in org.apache.shiro.web.servlet.AbstractShiroFilter
|    125 | doFilter . . . . . . . . . . in org.apache.shiro.web.servlet.OncePerRequestFilter
|   1145 | runWorker                    in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                          in java.lang.Thread
```

**Comment by nathandunn** [comment]
I fixed this such that it only shows adding the transcript.  Once the delete has happened the shared merge disappears.   Any action before the "merge" will be needed:

<img width="728" alt="screen shot 2016-03-03 at 9 29 36 pm" src="https://cloud.githubusercontent.com/assets/751274/13518857/292bbc44-e187-11e5-89eb-66dc159932de.png">

**Comment by nathandunn** [comment]
@monicacecilia  pull request closed this . . . still needs to be tested . . . sorry about that

**Comment by monicacecilia** [comment]
woop woop! It's brilliant!
I threw in a few wrenches to see if Apollo would get confused, and it kept the 'History' stack, changing it as needed. I think we got it! @nathandunn you're a genius!
:dancer:
