### ISSUE TITLE
doc has 8080 port in it for database URL, should be no port specified

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#793]

**Comment by nathandunn** [comment]
I looked and looked (in the code) and I did not see us refer to using the 8080 port anywhere in the doc or sample files in conjunction with the words `jdbc` or `postgresql` or `mysql`.  In the user's guide?  If not, then can close.

**Comment by cmdcolin** [comment]
I can't find it either even if searching for "8080" in docs. Perhaps the concept of JDBC connector strings is confusing though and needs preface

**Comment by monicacecilia** [comment]
The number '8080' appears nine times in the documentation for configuration, only as part of example URLs. For example, when discussing 'Canned Comments': 
- <code>View your instances page for more details e.g. http://localhost:8080/apollo/cannedComment/</code>

Or when discussing 'Data Adapters':
- <code>They are configured to query your IOService URL e.g. http://localhost:8080/apollo/IOService with the customizable query.</code>

And again when describing the Apache and Nginx proxies. 

But it **does not appear** in the context of the database, <code>jdbc</code>, <code>postgresql</code>, or <code>mysql</code>.

**Comment by nathandunn** [comment]
Alright.  You can probably close it then.  

Nathan

**Comment by monicacecilia** [comment]
Just to be thorough, '8080' is also mentioned in the context of: 
- The temporary server that is created when you verify your install
- Logging in to your web interface after setting up the application
- Where to find the app after deployment
- Bulk loading annotations to the user annotation track
- Complaints about 8080 being in use in the 'Troubleshooting' section
- The description of the Command Line Tools
- Web Service API

But not in the context of the database. I'm closing this.
