### ISSUE TITLE
test 2.0.0 -> 2.0.1 migration on mysql

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#794]
@adnguyen999   found this with @cmdcolin  

Was wondering if @erasche  went through this process and had any thoughts on this.

**Comment by erasche** [comment]
Afraid we only use postgres, sorry @nathandunn.

**Comment by nathandunn** [comment]
NP . . . I thought you were using mysql.  Must have been someone else.

**Comment by nathandunn** [comment]
Note (if using homebrew [this part always disappears]).   Also user should check for InnoDB (default if 5.5+).  Current distributed version is 5.6 or 5.7 depending on platform.  5.1 (no 5.4-5.2) was 2013: https://downloads.mysql.com/archives/community/

```
A "/etc/my.cnf" from another install may interfere with a Homebrew-built
server starting up correctly.

To connect:
    mysql -uroot

To have launchd start mysql at login:
  ln -sfv /usr/local/opt/mysql/*.plist ~/Library/LaunchAgents
Then to load mysql now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
Or, if you don't want/need launchctl, you can just run:
  mysql.server start
```

**Comment by nathandunn** [comment]
I can test this as I'm already in PostgreSQL land

**Comment by nathandunn** [comment]
Procedure: 
1 - drop and create mysql database
2 - build 2.0.0, ./apollo run-local, add an organism, create / edit some features
3 - stop server
4 - checkout to 2.0.1, ./apollo run-local
5 - verify that everything is still, we can add an organism, and create / edit some features

**Comment by nathandunn** [comment]
Getting this error, implying that the database migration is not being used: 

<img width="829" alt="screen shot 2016-01-20 at 3 39 31 pm" src="https://cloud.githubusercontent.com/assets/751274/12466833/0f3c10f8-bf8c-11e5-8381-43c34b94d771.png">

**Comment by nathandunn** [comment]
Regular deployment yields the same result.

**Comment by nathandunn** [comment]
- [ ] retest with postgreSQL

**Comment by nathandunn** [comment]
Seems to be something very specific to mysql.   The solution is here (I hope): http://stackoverflow.com/a/10724980/1739366  . . but not sure if that just fixes it in one place.

**Comment by nathandunn** [comment]
Clearly run, but not executed on mysql. 
```
| 1445460972540-22 | nathandunn (generated) | changelog-2.0.1.groovy | 2016-01-20 21:58:41 |            22 | EXECUTED | 3:d409f1edac038a1264d030bdb314e7a9 | Modify data type |          | NULL | 2.0.5     |
| 1445460972540-23 | nathandunn (generated) | changelog-2.0.1.groovy | 2016-01-20 21:58:41 |            23 | EXECUTED | 3:72eaf1247036c2e73ac28bd75a094e2a | Modify data type |          | NULL | 2.0.5     |
| 1445460972540-27 | nathandunn (generated) | changelog-2.0.1.groovy | 2016-01-20 21:58:41 |            24 | MARK_RAN | 3:0b265d4077016a9e0c76e2e4ee85eac3 | Drop Column (x6) |          | NULL | 2.0.5     |
```

**Comment by nathandunn** [comment]
In 'Config.groovy' set:  debug 'liquibase' in log4j configuration:

Also, create "changelog.groovy" file is the preferred way:

```
databaseChangeLog = {
    include file: "changelog-2.0.1.groovy"
}
```

Most importantly, we removed the "schema==public" from the columnExists statemnt as it was causing problems with mysql.

**Comment by nathandunn** [comment]
Tested and working . ..  nothing else to test . . closing.
