### ISSUE TITLE
history window should be larger / sizeable

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#797]
If you have a lot of history, would be good to have it show along the entire page. 
- [x] fix icons
- [x] ~~add column header for last column~~ added title for hover instead
- [x] change "operations" to something for humans
- [ ] ~~increase size of window / scaling (%?)~~  . . this is non-trivial for current implementation .. should move to table or in a panel

**Comment by nathandunn** [comment]
![screen shot 2016-01-21 at 4 10 21 pm](https://cloud.githubusercontent.com/assets/751274/12498724/88afe108-c059-11e5-98c8-42c9f35d273b.png)

**Comment by monicacecilia** [comment]
@nathandunn I agree with the updated changes. The arrows and 'bookmark' are appropriate and *mostly* self-explanatory. We'll have to remember to update the documentation #772.
If you haven't added anything else after we chatted, then just let me know and I think we are ready to merge https://github.com/GMOD/Apollo/pull/818 for you.

**Comment by monicacecilia** [comment]
The last tick will be addressed in #819
