### ISSUE TITLE
link to transcript on the second page of the annotator panel fails

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#801]
Here is the error:

```
Uncaught java.lang.IndexOutOfBoundsException: Row index: 23, Row size: 106
annotator-0.js:8745 Uncaught java.lang.IndexOutOfBoundsException: Row index: 26, Row size: 106
```

**Comment by deepakunni3** [comment]
The index value supplied to AnnotatorPanel::displayTranscript() was according to the index w.r.t. entire data in dataGrid (as returned by the server) but when pagination is involved, the index required by getVisibleItem() is supposed to be relative to each page. That is, it should start from 0 for every page.

This can be achieved by:
`
AnnotationInfo annotationInfo = dataGrid.getVisibleItem(Math.abs(dataGrid.getVisibleRange().getStart() - geneIndex));
`

**Comment by nathandunn** [comment]
Ahh .  . excellent.  .Issue a pull request when you get it in there.  Let me know if you need any help with it. 

Nathan

**Comment by deepakunni3** [comment]
The change required is a one-liner but let me know if there is any downstream implications that I haven't forseen.

**Comment by monicacecilia** [comment]
The link now works. Thanks @deepakunni3 !
:dancer:
