### ISSUE TITLE
shortcut to navigate to the end of a feature

### ISSUE THREAD

**Issue by strumpfe** [GMOD/Apollo#802]
When appraising/building an annotation the user needs to look at the exon/intron boundaries. This usually means zooming in/out to navigate between junctions. Having a shortcut (keyboard or menu) to move left/right to the end of the selected feature would greatly ease this process. Note a similar feature exists in Artemis for those who have experience of this.

**Comment by monicacecilia** [comment]
Explanations for these are available:
- in user guide in section "[4.2.2 Exon Structure Integrity](http://genomearchitect.org/users-guide/)"
- From the 'Help' top-level menu in the Apollo main window. 

The text reads "Use the square bracket keys [ and ] to jump to the next exon splice junction or coding sequence (CDS). The curly bracket keys { and } allow users to jump to the next transcript."
