### ISSUE TITLE
organism "report" is not authorized

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#804]
http://icebox.lbl.gov/Apollo2/organism/report/ . .. gives a "Not authorized" message. 

{"error":"Not authorized"}

**Comment by nathandunn** [comment]
definitely broken in 2.0.1 and definitely already fixed in 2.0.2

**Comment by cmdcolin** [comment]
You would get this error in current master if you access that page while not logged in still

**Comment by nathandunn** [comment]
That's a separate issue.   With this issue, if you are logged in all of the other report pages showed up but this one.  

I'll create a separate issue for the other one, which I had also thought about.  Will need another login page.
