### ISSUE TITLE
changes pages: have timestamp include hour/min, include pagination row count, and selectable date range

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#806]
```
Can the timestamp have greater granularity i.e. hour/min rather than grouped to day and is it possible to control the pagination row count?
```

**Comment by nathandunn** [comment]
- [ ] timestamp includes hour / min
- [ ] pagination row / count
- [ ] selectable date range

=== also, if moving to pure AngularJS ===

- [ ] loose searches and search via Ajax
- [ ] sorting within a search range if possible

**Comment by nathandunn** [comment]
Date range is slightly wonky because of time-zones, but you should be able to do anything you want with it.

**Comment by monicacecilia** [comment]
Checked & tested.
