### ISSUE TITLE
Apollo should allow for any feature from the evidence tracks to be dragged up and annotated as gene.

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#81]
====== Colin ====

The way that things are now causes us to lose information at the gene level, because we are only using the transcript information. I brought this up at the hackathon and although we didn't get anywhere, we agreed that it was important.

From my experience, the technical issue is that if we try to load the gene level using HTMLFeatures, it doesn't enumerate the transcripts and instead thinks the gene is a single feature.

By contrast, the CanvasFeatures in JBrowse correctly identifies the transcript subfeatures, so it does not have this problem (see Figure).

Given that the difference here is simply on the "View" side of things (i.e. HTMLFeatures vs CanvasFeatures), perhaps it would not be too hard to fix the HTMLFeatures code, but given that it hasn't already been solved already, I cannot be sure.

===== Suzi =====

Regardless of what is in the GFF3 originally any kind of feature should be able to be dragged up as a "gene". That is, the type as specified in the input file is not relevant here.

"gene" is an option for the type of feature the user wants to create. Thus when any feature is dragged up where the user has selected "gene" (and it is the default) it should become part of a gene. This can happen in three ways: a) brand new because it doesn't overlap any existing gene; b) part of an existing gene because the coding sequence of the transcript overlaps in-frame with the coding sequence of an transcript (i.e. another isoform) or c) it extends an existing transcript.

It is always 3 levels for protein coding genes: gene->transcript->exon

**Comment by cmdcolin** [comment]
Here's one mailing list thread that is important to this http://gmod.827538.n3.nabble.com/Error-trying-to-add-CDS-as-a-gene-to-user-annotation-td4047026.html#a4047041
