### ISSUE TITLE
delete gene models

### ISSUE THREAD

**Issue by lfaino** [GMOD/Apollo#815]
Hi @nathandunn,
I`m not able to remove gene models... can you help please?

thanks
Luigi

**Comment by nathandunn** [comment]
Sure.  Can you provide more details?  

A screenshot and/or console log would be great, as well as a straight up description of the problem. 

Thanks,

Nathan

**Comment by nathandunn** [comment]
If you’d rather Skype, you can email me off-line:  

nathandunn@lbl.gov

Nathan

**Comment by lfaino** [comment]
let try to describe, or tomorrow we can skype when I`m at the office.
I loaded all the gene models  in the annotation track using the bulk loading from Apollo tools folder.
Some of the gene models are wrongly predicted and I would like to remove them. 
However, when I right click on the gene model and I delete the gene, this is does not disappear from the track. I can make all the changes and remove part of the gene (exons) but I can not remove completely the gene model. One exon it always remain.

**Comment by nathandunn** [comment]
Two questions:
1 - Do you see an error on the server end (tomcat logs / catalina.out) when you do a delete (typically a constraint violation)? 
2 - When you refresh the page do you see the changes? 

Thanks,

Nathan

**Comment by lfaino** [comment]
Hi @nathandunn,
it works now. i change the browser from chrome to firefox and now works...

i let you know if i have a problem again
thanks
Luigi

**Comment by nathandunn** [comment]
Awesome, I know that feeling.   Sometimes the "cache" gets stuck.  I advocate doing a cache refresh (shift-reload), but sometimes closing chrome is necessary as well.  This is more common if you are doing multiple updates to the same codebase.    

Let us know if the performance is better, as well.
