### ISSUE TITLE
Unexpected URLencoding of multiple items in GFF3 export

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#82]
See http://gmod.827538.n3.nabble.com/attribute-tags-URL-encoding-problem-td4047073.html
 Example on user interface of behavior

![screenshot-icebox lbl gov 2014-11-19 09-51-43](https://cloud.githubusercontent.com/assets/6511937/5109271/c84aa152-6fd5-11e4-83ce-1284bfd16061.png)

Output
Test=1%2C2;
Expected output
Test=1,2;

**Comment by nathandunn** [comment]
@deepakunni3   Can you recheck this for 2.0.0?  Thanks.

**Comment by cmdcolin** [comment]
It doesn't look like any metadata is coming through at the moment

**Comment by nathandunn** [comment]
@deepakunni3   This is blocked by #250 . . .

**Comment by nathandunn** [comment]
@deepakunni3   It looks like its not exporting attributes . .

**Comment by deepakunni3** [comment]
@nathandunn Now it does export all the attributes except 'owner'.
Also, the unexpected URL encoding of multiple items with same attribute name is fixed.

**Comment by nathandunn** [comment]
@deepakunni3    . .  your code looks correct for this . .  my code (setting the owner)  looks to be incorrect . .  I think you can mark this as ready and assign it to me unless there are further issues on it.

**Comment by deepakunni3** [comment]
@nathandunn  There is one issue. Fixing that now. Will mark it ready as soon as I finish.

**Comment by nathandunn** [comment]
great thanks

**Comment by monicacecilia** [comment]
Metadata are now being captured and this issue has been fixed. I can see the expected output on the 9th column after adding Test 1 and Test 2 to the Attributes section (i.e. Test=1,2;). However, I uncovered a problem with PubMed IDs. Reported on #264
