### ISSUE TITLE
Filters and sort are mutually exclusive in Changes report (v2.0.1)

### ISSUE THREAD

**Issue by strumpfe** [GMOD/Apollo#824]
Using the Changes report page you can either sort rows (by date, organism, name, user etc.) or filter by owner, feature type or organism. Unfortunately, the filtering/sorting appear to be mutually exclusive i.e. if I filter by organism and then attempt to sort by 'Last updated' the sort overrides and filter and rows for all organisms are again included. If I sort by 'Last updated' and then attempt to filter the rows revert to a non-sorted ranking.

**Comment by cmdcolin** [comment]
@strumpfe that is correct. I think it just needs to "repass" the params better if you perform the two actions (i.e. a filter and then a sort) then it keeps using the previous params.

Thanks for the report!

**Comment by monicacecilia** [comment]
Sorting is possible after filter. 
Filtering is possible after sorting. 
:dancer:
