### ISSUE TITLE
document wikidata / sparql data endpoint for evidence tracks

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#827]
We need to document the solution that @cmdcolin  and @putmantime found for adding wikidata sparql tracks.

**Comment by nathandunn** [comment]
FYI @goodb and @monicacecilia

**Comment by nathandunn** [comment]
Hey, @putmantime @cmdcolin   were we able to document this anywhere?  I need to do a progress report, and it would be good to get something. . . and more important a demo.  Feel free to shoot me an email if it would be better to have private.

**Comment by cmdcolin** [comment]
It's pretty close to done

This is a data directory for a bacterial genome with a SPARQL track


[sparql_data_directory.tar.gz](https://github.com/GMOD/Apollo/files/162387/sparql_data_directory.tar.gz)


It requires master branch of jbrowse with the disablePreflight option for SPARQL data stores

**Comment by cmdcolin** [comment]
Also, note: it also does not fully mesh with Apollo because it retrieves single level features (i.e. "bare CDS" features). Apollo client code doesn't handle this, nor does the server side, but the client side could synthesize a parent and subfeature structure from the single level feature to fix it

**Comment by cmdcolin** [comment]
This patch effectively fixes that "bare CDS" problem by just synthesizing a parent feature


```
diff --git a/client/apollo/js/View/Track/AnnotTrack.js b/client/apollo/js/View/Track/AnnotTrack.js
index f46a9cc..b53ca8d 100644
--- a/client/apollo/js/View/Track/AnnotTrack.js
+++ b/client/apollo/js/View/Track/AnnotTrack.js
@@ -970,7 +970,6 @@ define([
                     var singleParent = keys.length == 1;
                     var featureToAdd;
                     if (singleParent) {
-
                         featureToAdd = JSONUtils.makeSimpleFeature(parentFeatures[keys[0]]);
                     }
                     else {
@@ -999,8 +998,12 @@ define([
                         }
                         featureToAdd.get("subfeatures").push(dragfeat);
                     });
-                    featureToAdd.set("start", fmin);
-                    featureToAdd.set("end", fmax);
+                    if(!subfeatures.length) {
+                        featureToAdd = new SimpleFeature({data: {strand: strand, start: featureToAdd.get('start'), end: featureToAdd.get('end'), subfeature
+                    }
+
+                    if(fmin) featureToAdd.set("start", fmin);
+                    if(fmax) featureToAdd.set("end", fmax);
                     var afeat = JSONUtils.createApolloFeature(featureToAdd, "mRNA", true);
                     featuresToAdd.push(afeat);
```

**Comment by nathandunn** [comment]
Right now looking for something to have as a demo.   Master branch might be a problem, but I'm sure I can do a workaround.   Thanks.

**Comment by putmantime** [comment]
Hi Guys,
I have added the proper strand orientation and the wikidata item uri to the sparql query in the trackList.json file.
This would make a demo a little more impressive since the annotations are pointed in the proper direction and the direct link to the annotation in wikidata is there.
If you guys are interested in this new version how should I commit this?  My issue is again version control I guess since I am not currently on a branch.
Tim





Timothy E. Putman Ph.D.
Postdoctoral Research Associate 
The Scripps Research Institute
La Jolla, CA 92037

**Comment by nathandunn** [comment]
Thanks Tim.  

Do you have a sample query for human, mouse, zebrafish, honeybee, drosophila?   I can always do this with the SPARQL query that Colin gave me, but human is always more impressive ;) 

Nathan

**Comment by nathandunn** [comment]
Tim, 

You can taste the SPARQL query here, since it goes into “trackList.json” anyway, its not source-controlled.  At some point it should go in our (or the JBrowse) documentation.  

Thanks,

Nathan

**Comment by putmantime** [comment]
Hi Nathan,
 This brings up an issue in that the reference genome used is a bacterial .fasta file stored locally on my computer. I imagine it would be best if we could do something like hit the NCBI ftp site for the reference genome, then use that as the input for the sparql query.    As far as a human query, the strand orientation has not been loaded for human  or mouse genes, (human and mouse are in wikidata, Su Lab project but its not my project (I’m the resident microbiologist).  If you do want it to be human I could provide a query that searches for humans genes for a single chromosome, but the arrows will all be in the same direction.  
Again not my expertise though.
Tim

If you do want to use the microbial query that I have updated here it is straight from the trackList.json file.
"queryTemplate":   "PREFIX wdt: <http://www.wikidata.org/prop/direct/> \n PREFIX wd: <http://www.wikidata.org/entity/> \n SELECT ?start ?end ?uniqueID ?strand ?uri \n WHERE { \n ?gene wdt:P279 wd:Q7187 . \n ?gene wdt:P703 wd:Q20800254 . \n ?gene wdt:P351 ?uniqueID. \n ?gene wdt:P644 ?start . \n ?gene wdt:P645 ?end . \n ?gene wdt:P2548 ?wdstrand . \n   bind( IF(?wdstrand = wd:Q22809680, '1', '-1') as ?strand). \n bind(str(?gene) as ?uri).\n }\n"

**Comment by nathandunn** [comment]
Human and mouse would be good.   I can’t remember the specific API call from the trackList.   

If we fake the strand right now (can’t remember how that was done) I can just explain that the strand information has not been loaded yet, but it is clearly integrated with genewiki.  

Thanks,

Nathan

**Comment by cmdcolin** [comment]
I think human and mouse is a bit ambitious. There probably isn't the needed representation about exons, transcripts, and gene relationships to get a good gene model.

I think that the bacterial genome is actually a pretty good starter example though. It is very simple unspliced genes, and getting the strand information added is awesome (thanks @putmantime !!)


Here is a updated data directory with that new query from Tim added!


[sparql_data.tar.gz](https://github.com/GMOD/Apollo/files/163814/sparql_data.tar.gz)

**Comment by nathandunn** [comment]
Thanks.   I'm still getting the cross-site issue error . . this is fixed in master jbrowse . . or do I need to do something else?

**Comment by nathandunn** [comment]
Tim . . . are you okay with having the scaffold data be available . . or should we delete it?

**Comment by putmantime** [comment]
Scaffold data for the genome assembly?  I have no problem with that.

**Comment by nathandunn** [comment]
Great.  Thanks for your help.

**Comment by putmantime** [comment]
As far as humans vs microbes Its up to you guys.  As colin mentioned the microbial model in WD is much more straightforward and set up for this kind of query.   I am looking into the human query but it is complicated by multiple assemblies, transcript ids, gene annotations etc..  I might be able to figure out how to simplify that down to something that makes sense by the end of the day but i can’t guarantee that.
Tim

**Comment by nathandunn** [comment]
@monicacecilia  D you know what to do with this one?  Basically we just point to the JBrowse doc, or nothing at all since we can do most anything that JBrowse can do.

**Comment by monicacecilia** [comment]
This belongs to JB documentation -
