### ISSUE TITLE
Expose API for adding GO, Dbxref, Attributes, PMIDs

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#829]
Feature request / issue for me to track my work, I'll open a PR next week.

**Comment by nathandunn** [comment]
:+1:   

FYI, we should have an API already exposed for some of these

- [x] addAttributes is exposed - wraps addNonReservedProperties
- [ ] addNonPrimaryDbxRefs (needs a method in AnnotationEditorController) . . 

I think that the GO, DbXref, and PMID's all use the NonPrimaryDbxref method, so hopefully you can just add that one and you'll be done.  

I think that the information is pretty minimal (you can look in the websocket frames for content sent).  This is what is sent when adding non_primary (+ username/password):

```
{ "track": "Group1.33", "features": [ { "uniquename": "530ab50b-64ac-4c7d-8cf5-00030b419e62", "dbxrefs": [ { "db": "PMID", "accession": "19448641" } ] } ], "operation": "add_non_primary_dbxrefs" }
```

**Comment by erasche** [comment]
Ah, okay, I didn't realise all the dbxrefs were lumped together like that, that'll definitely make things easy.

Thanks for the snippet!

**Comment by nathandunn** [comment]
If you want to expose them all differently you can as well, but I think we just have the client send the specific info.  

Nathan

**Comment by nathandunn** [comment]
@erasche   Just moving to next release.  If you do have any software changes associated with this, just push them when you have them and they'll slip into whatever release we happen to be on.

**Comment by nathandunn** [comment]
Most likely, between bug fixes and testing, it will probably make it into this one.

**Comment by erasche** [comment]
@nathandunn I should have time this week to implement this, will keep you posted. I appreciate the updates and fast iterations on apollo releases, it's amazing.
