### ISSUE TITLE
FASTA export of CDS sequences is too permissive and includes ncRNAs

### ISSUE THREAD

**Issue by strumpfe** [GMOD/Apollo#833]
Whilst exporting CDS sequences as FASTA from an instance with ncRNA both the protein_coding transcripts and the non-coding ones where written to file.  I expect this behaviour for the 'cDNA' export but not the 'CDS' one. Is there a filter for annotation type missing?

**Comment by nathandunn** [comment]
FYI @deepakunni3  .  . for 2.0.3 . . ..

**Comment by monicacecilia** [comment]
ncRNAs are no longer included in CDS export via FASTA files. 💃
