### ISSUE TITLE
gff3 exports should include repeat regions and transposable elements + sequence alterations missing

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#836]
@monicacecilia   Please let me know if we shouldn't export these, but I can't think of a reason not too.  

@cmdcolin   I think this should be a pretty quick fix for you.

**Comment by cmdcolin** [comment]
Looks like a part of the optimization that I did. I specialized the query on the Gene table. It can probably be fixed, if it's fine with you maybe leave it unreverted and I'll get a fix shortly

**Comment by monicacecilia** [comment]
Yes, they should, and they do. :dancer:
