### ISSUE TITLE
sequence search is not working

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#838]

**Comment by nathandunn** [comment]
![screen shot 2016-01-29 at 5 03 24 pm](https://cloud.githubusercontent.com/assets/751274/12692327/5267ee04-c6aa-11e5-9bda-f3dc15cbcdc2.png)

**Comment by nathandunn** [comment]
Somehow the sequence search seems to have been lost.

**Comment by cmdcolin** [comment]
Forgot to add the string matching to the criteria query...will fix here in a minute

**Comment by monicacecilia** [comment]
Sequence search is now working. 
:dancer:
