### ISSUE TITLE
Using ?organism=organismName doesn't work if logged in (only in works in public/non logged in)

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#845]
The ?organism=organismName (instead of ?organism=organismId) was added in 2.0.1 but it doesn't work if you are logged in (goes through two different code paths)

Issue brought to my attention by @anaome http://gmod.827538.n3.nabble.com/Gmod-ajax-Navigate-to-ortholog-gene-in-a-different-organism-td4052815.html

**Comment by cmdcolin** [comment]
As a weird corallary, loadLink links work only if you are logged in. I.e., if you aren't logged in, and you click a loadLink method, then it doesn't take you to desired place

**Comment by cmdcolin** [comment]
Also, finally, it was also suggested to allow loadLink to accept a gene ID, as normally with ?loc=GENEID works in jbrowse but Apollo loadLink expects a chr:start..end format

**Comment by nathandunn** [comment]
These all seem to work with the code popup (logged in or logged out), which is the major use-case, unless folks are entering in URL's themselves.  We should probably support this, though not a high priority AFAIK.

I like the idea supporting the GENEID (or just feature name) in general.

**Comment by nathandunn** [comment]
Let me know if I mis-identified the severity.  Will be happy to look at a pull request either way.

**Comment by cmdcolin** [comment]
I'd just want to get @anaome a fix in some reasonable time frame.

The scenario is just an interesting customization to link between organisms in a webapollo deployment using some callbacks, so just demonstrating ability to specify organism names and gene ids would be good for that

**Comment by nathandunn** [comment]
Its a really neat use-case.   

I'm wondering if it would simply make more sense to add an "orthologs" section to the popup link below the first two, which would search for the GENE ID in other organisms and then supply the links for those additional organisms.

**Comment by nathandunn** [comment]
<img width="592" alt="screen shot 2016-02-02 at 3 49 29 pm" src="https://cloud.githubusercontent.com/assets/751274/12768506/df481714-c9c4-11e5-83c8-2c7f4db76d8c.png">

**Comment by nathandunn** [comment]
By "more below" I mean orthologs with the same or similar names.  There are quite a few libraries out there for calculating word "distance".

**Comment by cmdcolin** [comment]
Sounds pretty cool to me. I think they were just using the right click menus in jbrowse but making the webapollo side of things more configurable would be cool too.

**Comment by cmdcolin** [comment]
@anaome also brought up the fact that this can cause issues because apollo fails when two organisms are browsed at the same time

#441 documents that

**Comment by cmdcolin** [comment]
We need to codify the assertion that organism "name" is unique.

Also, we should make additional use of the OrganismProperties table to store attributes.

**Comment by monicacecilia** [comment]
See #1096 instead.
