### ISSUE TITLE
Clicking on 'prevent this page from opening additional dialogs' when deleting a model prevents subsequent models from being deleted

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#851]
Perhaps I'm misunderstanding the expected behavior of the 'prevent this page from opening additional dialogs' radio button that shows up in the dialog box when you delete several features in a row. In my mind, it should prevent the dialog box from opening in subsequent delete operations, allowing you to delete further models without additional warning - but instead, it prevents you from deleting more (until you refresh the browser).

Is this the expected behavior? If it is, perhaps the text can be changed to 'temporarily disable delete function' or something similar?  

(Tested on our local installation of Apollo 1.0.4, and just now on Apollo 2.0.2-SNAPSHOT on http://icebox.lbl.gov/Apollo-staging/annotator/index)

**Comment by monicacecilia** [comment]
@mpoelchau nah, that's a bug...

**Comment by deepakunni3** [comment]
I don't think this is a bug. 
The 'prevent this page from opening additional dialogs' is a default feature of a web browser where it detects the pop-ups created by Apollo as unsavory and provides user the option to stop these dialog boxes from appearing. When a user does select to block these dialog boxes and then tries to delete an annotation, there will be no user confirmation sent to Apollo to delete the annotation.

Although, I like the idea of Apollo asking user to disable pop-ups while deleting annotations.

**Comment by monicacecilia** [comment]
By the 'sound' of this it seemed like buggy behaviour.
I think it is indeed a *bug*, but not our bug (I can actually see  now that even the font is different). So it is more like a *bother*. 

@deepakunni3 I don't presume we can tell the browser how to respond? 

I actually **do not** like the idea of disabling pop-ups. Because I am already listening to the cries of the curator who forgot s/he had disabled them. --- unless it can be reset every time there's a refresh. 
... no, I still hear the cry. 

@mpoelchau since this seems to be a feature of the browser, and not Apollo, perhaps the solution could be a warning on our end that lets curators know that disabling pop-ups will prevent them from deleting features. 

Other suggestions?

**Comment by nathandunn** [comment]
I think that the easiest interim solution might be to use the dojo "confirm" dialog.  It would both A) look better and B) remove the idea of disabling popups.  

@cmdcolin  Is this something that you could throw in quickly?

**Comment by nathandunn** [comment]
Was just thinking something like this: 

https://dojotoolkit.org/reference-guide/1.10/dijit/ConfirmDialog.html

**Comment by nathandunn** [comment]
Was definitely a WA1 bug.

**Comment by mpoelchau** [comment]
Oh, the poor cries of the curator... yes, now I hear them too :). I agree that the dialog box shouldn't be disable-able.

**Comment by monicacecilia** [comment]
@nathandunn but not Apollo's bug. The browser's bug.

**Comment by deepakunni3** [comment]
@monicacecilia Yes, this can be avoided by modifying the way we currently create the confirmation dialog box. In fact, right now its an 'Alert Box' and this is what triggers the web browser to give users the option to disable it. We can replace it with something else as suggested by @nathandunn.

**Comment by monicacecilia** [comment]
@mpoelchau say that, 5 times faster. :)

**Comment by nathandunn** [comment]
Right, its the browser's bug.  However, using "alert" and "confirm" is great for debugging but otherwise embarrassing.

**Comment by nathandunn** [comment]
If you want to do that as well @deepakunni3  . .  I say whoever gets to it first.  It should be a pretty quick fix either way.

**Comment by deepakunni3** [comment]
@nathandunn Sure, I can work on it.

**Comment by nathandunn** [comment]
Fixed in #857

**Comment by monicacecilia** [comment]
Great! New dialog box is not disable-able. :smile: 

However, I miss the ability to confirm the 'Delete' with one keystroke instead of a mouse click. :disappointed:  See #919
