### ISSUE TITLE
Need to optimize FASTA exports

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#854]
I did a little profiling of the FASTA exports and it is indeed pretty slow. The main bottleneck with fasta is a bit different from the GFF3, because it is accessing the sequence data.

Example with latest master on the pythium dataset of 341 genes

    6m33.813s, 6m30.875s

I felt like previously it might not have been as slow, so I tested with 2.0.0 and it had faster results

Repeated runs of 2.0.0

     3m26.838s, 3m27.010s

So it's unfortunate that it slowed down, but even with 2.0.0, that's not really ideal. GFF3 export for comparison is now about 8 seconds for same dataset, so by comparison its still 25x slower even with 2.0.0

**Comment by nathandunn** [comment]
For 1 group, 50 genes I get:
Genomic: 2 seconds
cDNA: 15 seconds
CDS: 15 seconds
Protein: 15 seconds

**Comment by nathandunn** [comment]
Every time it hits a CDS for the last 3 it has to run this:

```
        Transcript transcript = transcriptService.getTranscript(cds)
        List <Exon> exons = exonService.getSortedExons(transcript)
```

So, could definitely see pulling these out ahead of time and calling them from within a map.

**Comment by monicacecilia** [comment]
:dancer:
