### ISSUE TITLE
Logging to sentry/raven/statsD

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#867]
It'd be great if we could push stats (memory usage, concurrent annotator count, etc) to a statsD server, and while we're at it, it'd be great to ship frontend + backend exception to our sentry server.

**Comment by nathandunn** [comment]
https://grails.org/plugin/raven

https://github.com/charliek/grails-statsd  (not sure if this is consistent with 2.4.5 or not).

**Comment by monicacecilia** [comment]
@erasche please feel free to start working on this if you wish to. We won't get to it for another few weeks.

**Comment by erasche** [comment]
@monicacecilia okay, thanks for the update! I'll try and get around to this next week or so.

**Comment by erasche** [comment]
Just an update -- tried building in sentry (we desperately need it) and hit

- https://github.com/agorapulse/grails-raven/issues/5
- https://github.com/agorapulse/grails-raven/issues/15

I've just now seen that 5 is a dupe of 15 with a suggestion to downgrade so 0.5.8 so I'll try that soon.

**Comment by nathandunn** [comment]
@monicacecilia types: @erasche please let us know if there is anything else we need to do on our end.

**Comment by erasche** [comment]
Note for others: As much as I desperately need this, I had to give up on this because I don't have the skills to implement it and the only extant libraries are non-functional. Ah well.
