### ISSUE TITLE
(2h) readthrough_stop_codon loops back through ORF and recalculates

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#87]
When setting the longest readthrough_stop_codon, loops to the end of the ORF and goes back to the start, ignoring the current exon.

Setting gene:  GB51598-RA

http://icebox.lbl.gov/WebApolloDemo/jbrowse/?loc=Group1.37%3A176611..181225&tracks=DNA%2CAnnotations%2CGeneID%2COfficial%20Gene%20Set%20v3.2&highlight=

vs:

http://icebox.lbl.gov/WebApolloDemoStaging/jbrowse/?loc=Group1.37%3A178762..179684&tracks=DNA%2CAnnotations%2CGeneID%2COfficial%20Gene%20Set%20v3.2&highlight=

Here is the post in the "bad" code:

{ "track": "Annotations-Group1.37", "features": [ { "uniquename": "4C7A242A14F7455E566B314AF637E4EE", "readthrough_stop_codon": true} ], "operation": "set_readthrough_stop_codon"}:

Here is the post in the "good" code:
{ "track": "Annotations-Group1.37", "features": [ { "uniquename": "46EAC7807735E002CE5348D11C129C98", "readthrough_stop_codon": true} ], "operation": "set_readthrough_stop_codon"}:

**Comment by nathandunn** [comment]
@monicacecilia   If you could retest this that would be great.  Thanks.

**Comment by monicacecilia** [comment]
The portion of the behaviour when setting a readthrough stop codon (as described in November) has been restored. Alas, testing has uncovered the following issues in the current version:

1. When choosing the "Set Readthrough Stop Codon" option from the right click menu, Apollo is indeed reading through the stop and choosing the next "Stop" signal downstream (3') of the readthrough. However, the original "Stop" is not being marked with a purple box; instead, a thinner, gray box appears over the triplet (TAA in the image). This may be related to #221 

### Expected Outcome
![screen shot 2015-04-14 at 1 44 10 pm](https://cloud.githubusercontent.com/assets/1714621/7147003/93c2d450-e2ac-11e4-8d6d-6ea008668e37.png)

### Observed Outcome
![screen shot 2015-04-14 at 1 44 02 pm](https://cloud.githubusercontent.com/assets/1714621/7147013/a52aecb4-e2ac-11e4-9455-9d4d291afc8f.png)

2. Also, after setting the readthrough, the option to "Unset Readthrough Stop Codon" should be available from the right-click menu. This may or may not be related to current status of "History" and "Undo/Redo".

### Expected Outcome
![screen shot 2015-04-14 at 1 38 06 pm](https://cloud.githubusercontent.com/assets/1714621/7147069/1ac91aae-e2ad-11e4-9553-9dab0822cdb1.png)

### Observed Outcome
![screen shot 2015-04-14 at 1 39 15 pm](https://cloud.githubusercontent.com/assets/1714621/7147073/1e1321a0-e2ad-11e4-8c54-eb3914c88316.png)

**Comment by nathandunn** [comment]
Not sure if this is related to #320 and #321

**Comment by deepakunni3** [comment]
Needs extensive testing.

One gene that ends up creating an issue is GB40834-RA

**Comment by nathandunn** [comment]
@monicacecilia   

@deepakunni3  Wanted you to review this.  This is a bug in 1.0 as well.  He was not sure what the issue with this particular gene / transcript was.

**Comment by monicacecilia** [comment]
@nathandunn what does the label "blocked" mean?

**Comment by nathandunn** [comment]
@monicacecilia  Just means we can't work on it yet.    You can remove it once we have our marching orders. ;)

**Comment by monicacecilia** [comment]
It would have been my pleasure to test, but something more bizarre is happening. 
While testing this, I happened to have two windows open, one on Group1.33 and one on group 1.37. For a reason I cannot explain, the gene models I am adding to 1.37 are ALSO being displayed in 1.33 - obviously in the wrong coordinates. 

Above is Group 1.33, and below is Group 1.37. Notice that gene models labeled the same appear in both groups. This is impossible, I am only editing in 1.37. 

![screen shot 2015-05-18 at 1 53 10 pm](https://cloud.githubusercontent.com/assets/1714621/7690174/ad4c69fc-fd66-11e4-8452-866d5e9cceb3.png)

If I refresh 1.33 (the wrong "place" for the genes), the models disappear, but if I add more models to 1.37, then 1.33 reflects those changes again. And the mode I test, the weirder it gets. For example, in the window below, the same gene model that I had loaded numerous times in the U-cA area (see the two models above) have canonical splice sites, whereas the last 2 I added (below), despite being the same gene model, now seem to have non-canonical splice sites. Notice that all the boundaries are highlighted in edge-matching, which indicates the coordinates are the same. So what is happening?? 

 
![screen shot 2015-05-18 at 2 05 58 pm](https://cloud.githubusercontent.com/assets/1714621/7690234/22e0eea4-fd67-11e4-8b6f-2e99a17f15e0.png)

**Comment by nathandunn** [comment]
Related to #310 . . . websockets recursive "ADD" operation does not seem to be filtering properly.  I had not tried this test, though.   However, I tried two different users and reference sequences and the same thing.    That is definitely a show stopper.  

That being said, any testing you can do with a single window should still be correct.

**Comment by monicacecilia** [comment]
.... something is REALLY, REALLY gone wrong. 
You are currently working on group 1.31, but I can see all your edits reflected in group 1.33. 

Your most recent edits to gene model GB51936-RA are shown below, but in a different scaffold:

![screen shot 2015-05-18 at 2 32 51 pm](https://cloud.githubusercontent.com/assets/1714621/7690748/23442ba0-fd6b-11e4-8aaf-d8e3c351890b.png)

**Comment by monicacecilia** [comment]
dearest señor @nathandunn, please forgive me if I don't sound so optimistic; alas, I strongly disagree with "that being said, any testing you can do with a single window should still be correct." ... how come I am testing on one window and it is showing up elsewhere? what else is happening that I am unable to see?  :scream:

**Comment by nathandunn** [comment]
I am fixing this in #391 . . . I’m going to no longer edit stuff on Icebox so you can keep testing.  Sorry you ran into that.  

Nathan

**Comment by nathandunn** [comment]
Okay, well find non-“UcA” tests then.  I’m working on #391 right now which will hopefully fix this.   Now is your time to test BLAT again ;)

Nathan

**Comment by monicacecilia** [comment]
??????????????????????!!!!!!!!!!!!!!!!!!!!! :angry:

**Comment by nathandunn** [comment]
Should be able to review again

**Comment by monicacecilia** [comment]
The following problems are solved: 
1. When choosing the "Set Readthrough Stop Codon" option from the right click menu, Apollo is indeed reading through the stop and choosing the next "Stop" signal downstream (3') of the readthrough. However, the original "Stop" is not being marked with a purple box; instead, a thinner, gray box appears over the triplet (TAA in the image). :heavy_check_mark:
2. Also, after setting the readthrough, the option to "Unset Readthrough Stop Codon" should be available from the right-click menu. This may or may not be related to current status of "History" and "Undo/Redo". :heavy_check_mark:

However, other problems with the "set/unset readthrough" operation were uncovered and are reported in #400 

I am closing this issue and we should now focus on #400.
