### ISSUE TITLE
The 'Organisms' drop down menu label goes missing after first display.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#870]
This isn't good. 

The 'Organisms' drop down menu label goes missing after it is first displayed. In Chrome. 

Reproduce by: 
1. Click on drop down menu
2. Let go, or click outside of the menu. 
ta-da. 

![screen shot 2016-02-11 at 10 11 55 pm](https://cloud.githubusercontent.com/assets/1714621/13000220/92067546-d10c-11e5-9595-7241aeac1e9a.png)

**Comment by monicacecilia** [comment]
In Firefox, the drop down menu is unable to display the list unless the cursor is rolling over it, for example see the image below. @erasche is reporting the same (Firefox?) error as part of #866 

![screen shot 2016-02-11 at 10 23 46 pm](https://cloud.githubusercontent.com/assets/1714621/13000354/509d2fd0-d10e-11e5-9ae1-4802917f5c70.png)

**Comment by childers** [comment]
I can confirm this from a fresh clone I setup yesterday. We saw this on firefox and chrome, in windows and OS X.

**Comment by erasche** [comment]
firefox & chrome on linux.

**Comment by cmdcolin** [comment]
Should be fixed in #872

**Comment by monicacecilia** [comment]
Looks great. :dancer:
