### ISSUE TITLE
mRNAs without strand can occur in UcA, and can't be moved to a strand

### ISSUE THREAD

**Issue by mpoelchau** [GMOD/Apollo#873]
Hi y'all,

We've recently noticed that it's possible for an annotator to create mRNA features without a strand specified. You can do this by uploading a gff3 without the strand specified, although there might be more creative ways that an annotator could accomplish this. Here's an example:

http://icebox.lbl.gov/Apollo-staging/annotator/loadLink?loc=Group1.1:1345175..1356995&organism=3836&tracks=Official Gene Set v3.2)

While there are probably some use cases where you would want an unstranded mRNA, I can't think of any right now, and this should usually be an unintentional 'feature'. There's nothing you can do to modify this once the model is up in the UcA besides re-create the model (the 'move to opposite strand' command is greyed out). I was wondering if it would be possible to either 1) disallow mRNAs (and possibly other feature types) without a strand in the UcA or 2) enable the 'move to opposite strand' function so annotators could add a strand after adding in the model.

**Comment by nathandunn** [comment]
Very curious to get feedback from @monicacecilia .  We could always assign a strand by default to the GFF3, or "set strand".

**Comment by monicacecilia** [comment]
Of the two options that @mpoelchau offers, I rather implement the latter. I would like for us default to assigning _positive strandedness_ to a feature without a strand in the GFF3, so that the curator can correctly keep or change the strand as necessary. 
That is... do what @nathandunn suggested. :bowtie:

**Comment by monicacecilia** [comment]
#1038 fixed and updated this.

@nathandunn I need a track of HTML, non-stranded features to be able to test this. A track with repeats, GC content, gaps, etc. could work.

**Comment by nathandunn** [comment]
Could dig through a BAM track?   I think that's where they came from originally.    Can you use the original link?

http://icebox.lbl.gov/Apollo-staging/annotator/loadLink?loc=Group1.1:1345175..1356995&organism=3836

**Comment by monicacecilia** [comment]
Ya see whatIwasTellingYouAboutThoseSpacesInTheURLs?

![screen shot 2016-06-02 at 1 55 29 pm](https://cloud.githubusercontent.com/assets/1714621/15760780/aa75f27c-28c9-11e6-9035-046548d0e96e.png)

**Comment by nathandunn** [comment]
I can change the link text to be: "Link icon" or "right-click" and copy to share.

**Comment by monicacecilia** [comment]
@nathandunn reads in BAM tracks often (although not always) have information about strandedness. In Honey Bee data on staging they do.

**Comment by deepakunni3** [comment]
RNA-seq BAMs would have reads with strand information whereas DNA-seq (genomic) BAMs are not likely to have reads with strand information.

**Comment by nathandunn** [comment]
@deepakunni3  If you know where some are let me know, otherwise I'm sure I can dig some up from somewhere or I can synthesize a track.

**Comment by nathandunn** [comment]
I added a volvox organism with a strandless track.

<img width="611" alt="screen shot 2016-06-02 at 8 06 12 pm" src="https://cloud.githubusercontent.com/assets/751274/15767529/a8ed588a-28fd-11e6-89d5-b4baa6926d99.png">

**Comment by nathandunn** [comment]
Retested and still works.

**Comment by monicacecilia** [comment]
@nathandunn, that's a funny track. :bowtie: 
- I checked and confirmed that genomic elements from the evidence tracks, that do not have 'strand' information, by default are converted to sense strand. 
- Checked and confirmed that genomic elements in the Uc-A area can be moved to the opposite strand.
- WRT @nathandunn's comment: "I can change the link text to be: "Link icon" or "right-click" and copy to share." No changes were made, but this can be a new issue for a later Milestone. 
Gets a 💃 !
