### ISSUE TITLE
Error: Organism directory must be an absolute path pointing to 'trackList.json'

### ISSUE THREAD

**Issue by MichelMoser** [GMOD/Apollo#876]
Dear all, 

I have probably a very basic error which might be fixed in an instant. I just dont know where to edit which file to set the Organism directory. 
I am using h2 as the database.
Could someone point this out for me? 

Thank you very much, 
Michel

**Comment by nathandunn** [comment]
The h2 database stores your annotations.  The JBrowse evidence track is what is stored in the trackList.json directory.   At a minimum these need your reference sequence in that directory and a single evidence track (kind of pointless without this).  

http://webapollo.readthedocs.org/en/latest/Apollo2Build.html#adding-data-to-apollo

You can also email ```apollo@lists.lbl.gov```.   You can also subscribe here:  https://docs.google.com/forms/d/1PkOm2SKiaAiAhCaMHEc0YFwFZ9nrZaZkbt29R8PW-W8/viewform

(the link is from the bottom of this page):  http://genomearchitect.org/

I'm going to close this for now, but let us know if you have any further questions.

**Comment by MichelMoser** [comment]
Hello, 
Thank you very much for the links and hints. 
Some questions remain about color settings and bam visualization. 

Is it feasible to modify apollo just the way JBrowse looks like? 
Is it for example possible to colour amino acids in the Reference Sequence track? 
Also is it possible to visualize spliced reads from alignments by different colour (similar to IGV)? So far i transformed them to bigwig files, which unfortunately gets rid of splicing information. When trying to load bams directly with --coverage option, one needs to set a fixed coverage range to display. Could it be set to a relative scale according to the highest count on the screen like with the bigwig settings?

If there are some informations how to modify color and display features, i would really like to give it a shot and also to write up some manual for others if wanted.

Thank you, 
Michel

**Comment by nathandunn** [comment]
You can configure it mostly like this:

http://gmod.org/wiki/JBrowse_Configuration_Guide#HTMLFeatures_Configuration_Options

Currently, we can't make it look like the JBrowse reference sequence track (it is on the list of things to do).  

I know that @cmdcolin  has added some stuff specifically for showing splice junction information, but I don't know where that resides.

**Comment by cmdcolin** [comment]
@nathandunn is correct that the sequence track can't be configured in Apollo. it is a different type of track than Jbrowse's sequence track but it should be on list of things to do as well :)

>Also is it possible to visualize spliced reads from alignments by different colour (similar to IGV)? 

You can put the term "overridePlugins": true into your BAM file configs in trackList.json and that will use the Alignments2 track type which has strand visualization.

>When trying to load bams directly with --coverage option, one needs to set a fixed coverage range to display. Could it be set to a relative scale according to the highest count on the screen like with the bigwig settings?

I believe that the SNPCoverage track will autoscale locally but it looks like add-bam-track.pl in jbrowse  warns you about entering a min_score and max_score unnecessarily. We can post a fix to that issue upstream in jbrowse, but for now you can delete the min_score and max_score lines out of your trackList.json. Just for viewing sake,  you can see the jbrowse demo browser coverage track autoscales locally http://localhost/jbrowse/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A43492..43543&tracks=volvox-sorted_bam_coverage&highlight=


Also the splice junction info that @nathandunn is a plugin that I developed for doing sashimi style plotting. If you're interested in it let me know and I can add more info https://github.com/cmdcolin/sashimiplot

**Comment by MichelMoser** [comment]
@nathandunn thank you very much. overridePlugins and removing the min_score and max_score improved visualization alot. 

@cmdcolin I would very much like to try the sashimi plots in jbrowse. So far i downloaded your plugin and added following lines to ./Apollo/web-app/jbrowse/jbrowse.conf: 

```
[ plugins.Sashimiplot ]
location = /home/moser/Tools/Apollo/sashimiplot
```

but i am not sure if this is the correct way to install plugins in webapollo. Also how do i access it for bam tracks? Do i have to modify the specific track configs?
Thanks, 
Michel
