### ISSUE TITLE
on IE10, getting a lot of space between widgets

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#877]
This is not in 2.0.1, confirmed, and it is part of 2.0.2-RC1 (staging).  

![screen shot 2016-02-15 at 9 22 45 am](https://cloud.githubusercontent.com/assets/751274/13055736/e239a900-d3c5-11e5-934f-c51537d75188.png)

**Comment by cmdcolin** [comment]
I can confirm this too on IE10. Maybe it is from the updated gwtbootstrap3? I found commit 734ded7fb07bcc has the updated libs.

**Comment by nathandunn** [comment]
Wouldn't surprise me, but I'm thinking it should be fixable.

**Comment by nathandunn** [comment]
the gwtbootstrap3 fixed other things, so I'd prefer not to remove it.

**Comment by cmdcolin** [comment]
@nathandunn doesn't appear to be that checking out to  734ded7~1 (i.e. one commit before that change)  fixed it either so maybe something else!

**Comment by cmdcolin** [comment]
I think I found the issue. Currently it says that there is 120% width on the columns in the annotator panel (after date column was added). I think it needs to be only 100%. So change should be something like this:


```
diff --git a/src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java b/src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
index 11dd7fb..7bc88ea 100644
--- a/src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
+++ b/src/gwt/org/bbop/apollo/gwt/client/AnnotatorPanel.java
@@ -488,11 +488,11 @@ public class AnnotatorPanel extends Composite {
         dataGrid.addColumn(lengthColumn, "Length");
         dataGrid.addColumn(dateColumn, "Date Last Updated");
 
-        dataGrid.setColumnWidth(0, "55%");
-        dataGrid.setColumnWidth(1, "15%");
-        dataGrid.setColumnWidth(2, "15%");
-        dataGrid.setColumnWidth(3, "15%");
-        dataGrid.setColumnWidth(4, "20%");
+        dataGrid.setColumnWidth(0, "45%");
+        dataGrid.setColumnWidth(1, "12%");
+        dataGrid.setColumnWidth(2, "12%");
+        dataGrid.setColumnWidth(3, "11%");
+        dataGrid.setColumnWidth(4, "20%%");
```


Speaking of that, it would be nice if the user could just adjust the widths?

**Comment by monicacecilia** [comment]
In IE10 (gulp, :astonished:) the space  has been reduced. 
However, it is displayed very oddly - please see #920
