### ISSUE TITLE
BLAT should fail gracefully if inappropriate sequence

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#88]
BLAT searchers should fail gracefully:
-- a warning alerting users they have pasted the inappropriate query to the search settings (protein and nucleotide) should appear, consequently avoiding performing the search if the correct query is not used.

**Comment by cmdcolin** [comment]
This is a random issue that I saw, but if you give the wrong path to a blat database in the blat_config.xml, it doesn't seem to throw an error; it is just empty when you hit the search

**Comment by nathandunn** [comment]
@cmdcolin   I believe this is in the BLAT realm.

**Comment by cmdcolin** [comment]
Should be reporting errors a bit better now

**Comment by monicacecilia** [comment]
Unfortunately, this is not ready. I am unable to test and I am getting the following error:

<code>
No signature of method: org.apache.catalina.loader.WebappClassLoader.loadClass() is applicable for argument types: (java.lang.String, java.lang.Boolean, java.lang.Boolean) values: [org.bbop.apollo.sequence.search.blat.BlatCommandLineNucleotideToNucleotide, ...]
Possible solutions: loadClass(java.lang.String, boolean), loadClass(java.lang.String), loadClass(java.lang.String), getClass(), findClass(java.lang.String)
</code>

![screen shot 2015-05-01 at 11 09 08 am](https://cloud.githubusercontent.com/assets/1714621/7434833/e74c5be8-eff2-11e4-95b2-6e49e6799e74.png)

**Comment by nathandunn** [comment]
This is a deployment / configuration error on my part.  I'll take a look.

**Comment by nathandunn** [comment]
@cmdcolin  

I fixed the first error https://github.com/GMOD/Apollo/commit/76f146b6f763e1d702ad173a5f8bbc56da130e09

but am now getting another one:

    Error running search: Cannot run program "/usr/local/bin/blat": error=2, No such file or directory


My config is this:

    apollo{
                sequence_search_tools {
                        blat_nuc {
                            search_exe = "/home/swdev/Software/blat/bin/blat"
                            search_class = "org.bbop.apollo.sequence.search.blat.BlatCommandLineNucleotideToNucleotide"
                            name = "Blat nucleotide"
                            params = "-minScore=0 -minMatch=1"
                        }
                        blat_prot {
                            search_exe = "/home/swdev/Software/blat/bin/blat"
                            search_class = "org.bbop.apollo.sequence.search.blat.BlatCommandLineProteinToNucleotide"
                            name = "Blat protein"
                            params = "-minScore=0 -minMatch=1"
                            //tmp_dir = "/opt/apollo/tmp"
                        }
                }
        }

What should my config look like?

**Comment by nathandunn** [comment]
I added "grails" around the "apollo" and I get the same error

**Comment by nathandunn** [comment]
![screen shot 2015-05-02 at 9 56 12 am](https://cloud.githubusercontent.com/assets/751274/7441910/7d67c2b6-f0b1-11e4-914b-62ead95b28a4.png)

**Comment by cmdcolin** [comment]
Are you editing Config.groovy or a different file

**Comment by nathandunn** [comment]
It is the apollo-config.groovy in my home directory that gets deployed.

Nathan

**Comment by cmdcolin** [comment]
Sorry to be pedantic but is there any indication your home directory is picked up at all? &nbsp;I think I read that you can add println statements to config files to check
&nbsp;I don't have the comp to test myself now


Sent from my Palm Pixi on AT&amp;T
On May 2, 2015 1:06 PM, Nathan Dunn &lt;notifications@github.com&gt; wrote: 



It is the apollo-config.groovy in my home directory that gets deployed.



Nathan



&gt; On May 2, 2015, at 11:05 AM, Colin Diesh &lt;notifications@github.com&gt; wrote:

&gt; 

&gt; Are you editing Config.groovy or a different file

&gt; 

&gt; 

&gt; 

&gt; Sent from my Palm Pixi on AT&amp;amp;T

&gt; On May 2, 2015 11:56 AM, Nathan Dunn &amp;lt;notifications@github.com&amp;gt; wrote: 

&gt; 

&gt; 

&gt; 

&gt; 

&gt; —

&gt; Reply to this email directly or view it on GitHub.

&gt; 

&gt; 

&gt; 

&gt; 

&gt; 

&gt; 

&gt; 

&gt; 

&gt; —

&gt; Reply to this email directly or view it on GitHub &lt;https://github.com/GMOD/Apollo/issues/88#issuecomment-98383280&gt;.

&gt;

**Comment by nathandunn** [comment]
Sorry, I meant the root directory I checkout it.  i.e., “./apollo-config.groovy”  

Nathan

**Comment by cmdcolin** [comment]
Ok well the easiest thing to do obviously is to edit Config.groovy. I'd just recommend a separate issue for defining the proper external apollo configs.

**Comment by nathandunn** [comment]
Okay . . . see #342 . .

**Comment by nathandunn** [comment]
It looks like this bug works.  I've added #342 in order to allow actual proper configuration of BLAT.

**Comment by monicacecilia** [comment]
Nope. Not working yet. 

![screen shot 2015-05-04 at 9 48 31 am](https://cloud.githubusercontent.com/assets/1714621/7457628/cf59fdb8-f242-11e4-90ab-85e0d02c8d2f.png)

**Comment by nathandunn** [comment]
@monicacecilia   I know its not working (thus #342 )  . . . however, this bug is fixed:

![screen shot 2015-05-04 at 9 55 58 am](https://cloud.githubusercontent.com/assets/751274/7457752/ce0a4912-f243-11e4-812a-d020778ca25f.png)

**Comment by monicacecilia** [comment]
Maybe it is working in your computer, it is not working on Apollo2 demo. I am entering an amino acid string to perform a nucleotide search and I am not getting this warning, only the error I posted above. So it is not "ready".

**Comment by nathandunn** [comment]
I know . . BLAT is not ready, but the title of the bug is:

"BLAT should fail gracefully if inappropriate sequence"

*this* works as expected.  Before it was throwing some other random error on the backend.   Now it is catching this error on the front-end.  

That being said, make sure that this works to your liking.   When #342 is fixed, you'll be able to test BLAT results.

**Comment by monicacecilia** [comment]
What I am saying is that this warning is NOT appearing in Apollo2 yet, so no, it does NOT work as expected. Unless we are talking about some parallel dimension in which you are able to see this in the testing site and I am not? ...

**Comment by nathandunn** [comment]
Ahh . . sorry for my denseness . . . I see.   I was just looking for a protein string, but clearly that is not what you were searching for.  Need more coffee. 

@cmdcolin   This is a bug in the older code, but the fix is pretty clear .. . 

1 - in SequenceSearch.js this line:
      else if (residues.match(/[^ACDEFGHIKLMNPQRSTVWXY\n]/)) {
            alert("The sequence should only contain non redundant IUPAC nucleotide or amino acid codes (except for N/X)");
            ok = false;
        }
   
2 - should be replaced with an if/else based on the tool selected, which comes through here:

 sequenceToolsSelect.value 

Would be nice in the drop-down if we could specify the type, but we can just use name for now.  Here are the codes (except X/N) apparently. 

http://www.dnabaser.com/articles/IUPAC%20ambiguity%20codes.html

Not sure if its worth using this BLAT for comparison:

https://genome.ucsc.edu/cgi-bin/hgBlat?command=start

**Comment by nathandunn** [comment]
I'm going to close this one (which appears to be working as I understood the original bug).  

More tightly confining the allowable sequence will go here for 2.0.1: 

https://github.com/GMOD/Apollo/issues/344

This has been in the code for several years.   The UCSC BLAT search behaves in a similar fashion, so I think it should be fine for now.

**Comment by monicacecilia** [comment]
In my opinion, UCSC BLAT behaving that way is not sufficient justification to not warn users when they enter the wrong sequence. 

The name of this issue is: 
"BLAT should fail gracefully if inappropriate sequence"

In an ideal Apollo world, when I mistakenly enter an amino acid sequence when I intended to run a nucleotide-based search, I would see an error warning of the failed search, and telling me why. 

For example, BLAST at NCBI warns me of my mistake as follows: 
![screen shot 2015-05-21 at 6 01 21 pm](https://cloud.githubusercontent.com/assets/1714621/7762077/b0b4072e-ffe3-11e4-9e01-fcbebbbf00aa.png)

Versus Apollo, which does not warn me of the error, and simply reads "No matches found". 
![screen shot 2015-05-21 at 6 03 51 pm](https://cloud.githubusercontent.com/assets/1714621/7762082/d220ff2a-ffe3-11e4-9012-a9679234f34b.png)

Is it not at all possible to issue a warning? And if so, what is the reason for this - other than UCSC doesn't do it either -- :)

**Comment by nathandunn** [comment]
@monicacecilia   Please see #344, which handles the case you're talking about.  

I agree that this needs to get fixed.  However, it needs to be better defined in case #344.

**Comment by monicacecilia** [comment]
So we can't have an error telling users they used the wrong sequence.

I don't know how BLAST does it, then. A nucleotide sequence is not rejected if it contains degenerate code. But a sequence with aa residues is rejected from nucleotide-based searches. Rejection also occurs when using nt sequences for aa-based searches.

Does anyone know how NCBI figures it out? 

![screen shot 2015-05-26 at 7 19 05 pm](https://cloud.githubusercontent.com/assets/1714621/7827439/2b2fcc62-03dc-11e5-8bc0-1a1a97d9caca.png)

**Comment by monicacecilia** [comment]
As a possible remedy, we could add a warning in front of the search option that reads: "Enter appropriate sequence for the selected option". Or something of the like.
