### ISSUE TITLE
Some updateOrganismInfo requests lacking authentication credentials

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#886]
![selection_530](https://cloud.githubusercontent.com/assets/458683/13091811/8a00383c-d4c2-11e5-912a-3a9ec9b45d6c.png)

Results in 

```
webapollo2_1 | 2016-02-16 21:31:36,152 [http-bio-8080-exec-435] WARN  apollo.SecurityFilters  - username/password not submitted
```

![selection_531](https://cloud.githubusercontent.com/assets/458683/13091822/98463928-d4c2-11e5-8589-9e7c8f90b9b3.png)

Don't know what's causing missing creds. We're still on 2.0.1. Will investigate more later.

**Comment by erasche** [comment]
Issues seems to have disappeared. We're on 2.0.2 so it may have been version-specific.

**Comment by monicacecilia** [comment]
@erasche Do you mean to say that you already using v2.0.2? 
Or do you mean to say "we" (you, us, all together) over here in Apollo land are "now" developing 2.0.2?

**Comment by erasche** [comment]
@monicacecilia sorry for lack of clarity.

we = my org. my org switched from 2.0.1 to 2.0.2 and I haven't seen this since. I did not expend any effort trying to debug this when I saw it on 2.0.1.

**Comment by monicacecilia** [comment]
Thanks @erasche. Understood. However, 2.0.2 is a release candidate. Not a stable release and thus, it __SHOULD NOT__ be used for production. I have not even finished testing things and there are a number of bugs we are ironing out. For example, you will be able to "select" ghost RNAseq reads, at the moment, as shown below. I recommend that you do not push updates to your servers yet. RCs are very volatile and we will be introducing more changes in the upcoming days. 

<img width="856" alt="screen shot 2016-02-29 at 6 50 12 pm" src="https://cloud.githubusercontent.com/assets/1714621/13416218/dcfe43b4-df15-11e5-834d-ddd9ff704882.png">

**Comment by erasche** [comment]
> Not a stable release and thus, it SHOULD NOT be used for production.

we live dangerously ;) we also have a pretty small, private user base and are not using anything past basic JBrowse gff3 display, and "edit feature attributes" of gene features. No RNAseq, no complex gene models, etc.

**Comment by monicacecilia** [comment]
@erasche :bowtie:  
While I can appreciate the desire to live dangerously, I can also imagine you may prefer to use your time wisely and avoid the constant updates from here on. So, I strongly recommend that you wait. With that said, of course you are the master of your own time. Have fun on the edge! :smile:
