### ISSUE TITLE
List of "Tracks" in Annotator panel jumps back up to the top after selection.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#898]
This is a very, very annoying bug (checked, and it is also in v2.0.1)

As the tile describes, after selecting a track from the list, the list jumps back up to the top. This means, for example, in the honey bee demo I cannot consecutively select the tracks for RNAseq reads - from the list in picture 1-, instead, right after selection, my view changes back  to the top and I have to scroll down again (picture 2).

__Picture 1.__
<img width="477" alt="screen shot 2016-02-29 at 6 09 09 pm" src="https://cloud.githubusercontent.com/assets/1714621/13415431/99f69a86-df0f-11e5-8f18-3a934e728a59.png">

__Picture 2.__
<img width="296" alt="screen shot 2016-02-29 at 6 04 24 pm" src="https://cloud.githubusercontent.com/assets/1714621/13415695/b671f37a-df11-11e5-8a10-ab7fbf25be0f.png">

**Comment by nathandunn** [comment]
@monicacecilia  Have a pull request in for this.  @deepakunni3  is going to review and then I'll tag it.

**Comment by deepakunni3** [comment]
@nathandunn Works as intended. :+1:

**Comment by monicacecilia** [comment]
:dancer:
