### ISSUE TITLE
Mysterious "Attributes" entries are automatically generated.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#902]
I did not enter these, they mysteriously turned up... :eyes:
![screen shot 2016-03-01 at 3 53 24 pm](https://cloud.githubusercontent.com/assets/1714621/13446183/1a036b1c-dfc6-11e5-8f76-aa4fab26c22a.png)

**Comment by nathandunn** [comment]
ahh . . .that is what I saw . . any idea how that is turning up?

**Comment by monicacecilia** [comment]
I don't have anything on the console... so, no. :disappointed:

**Comment by deepakunni3** [comment]
Does this happen after merging two transcripts?

**Comment by monicacecilia** [comment]
I just tried merging two transcripts using two methods, by right click over the two selected parts, and by dragging one piece into the other one. No error observed.

**Comment by deepakunni3** [comment]
@monicacecilia Okay, I had a theory but I don't think thats what is causing it :)

**Comment by nathandunn** [comment]
No . . . it occurs on “undo”.  Argh . . 

Nathan

**Comment by nathandunn** [comment]
Also occurs when setting history (backwards), which is unsuprsiging

**Comment by nathandunn** [comment]
when re-adding we have to JSON features:
```
key:value
value:None ??
```
and

```
key:type
value:[name:owner,cv:{name:feature_property}}
```

somehow these got pulled back out incorrectly, though

**Comment by nathandunn** [comment]
JSON coming back might be turning “owner” into a feature property . . . when converted into JSON and then gets converted back

**Comment by monicacecilia** [comment]
It's clear. 
:dancer:
