### ISSUE TITLE
Very difficult to see scales in evidence tracks while in Dark theme

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#906]
As shown in these images, it is difficult to read this scale when in Dark theme. Perhaps we could do improvements to this set up for better visualization. 

![screen shot 2016-03-01 at 5 00 21 pm](https://cloud.githubusercontent.com/assets/1714621/13447405/2e049c9e-dfd0-11e5-8af6-13d7dc295d16.png)

![screen shot 2016-03-01 at 5 00 32 pm](https://cloud.githubusercontent.com/assets/1714621/13447410/33d6e564-dfd0-11e5-9ea1-b21d8651fecb.png)

**Comment by cmdcolin** [comment]
@monicacecilia On my instance, the bigwigs have a grey background for the bigwigs so they stand out. Is that not the case for you? Same thing on icebox with the 2.0.1 too


![screenshot-localhost 8080 2016-03-01 19-26-40](https://cloud.githubusercontent.com/assets/6511937/13447757/8b4f95a8-dfe3-11e5-8e20-e4d76c398c84.png)

**Comment by monicacecilia** [comment]
Ah, I missed an important detail to add: the evidence tracks from the server have the background area. However, tracks that result from the "Add Combination Track" function (under "File"), do not. 

![screen shot 2016-03-01 at 5 32 27 pm](https://cloud.githubusercontent.com/assets/1714621/13447861/9b0dba3e-dfd3-11e5-816c-a737e7f258fb.png)
