### ISSUE TITLE
No glyphs for sequence alterations.

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#908]
In certain cases, sequence alterations glyphs do not appear, despite the fact that they were added and the dialog box had disappeared. I had to refresh the page in order to see the result of the alteration. 
It could be connectivity... but I figured I'd point his out. 

**Figure 1.** Alteration completed, before refresh: note that the gene has already incorporated the result of the alteration as shown by the truncated CDS.
![screen shot 2016-03-01 at 5 28 30 pm](https://cloud.githubusercontent.com/assets/1714621/13447971/41fca8f0-dfd4-11e5-864d-5b4aad625e54.png)

**Figure 2.** After refresh.
![screen shot 2016-03-01 at 5 28 50 pm](https://cloud.githubusercontent.com/assets/1714621/13447974/460d764a-dfd4-11e5-87d6-888fe5c85e74.png)

**Comment by nathandunn** [comment]
I *think* that this is due to the block-based rendering.  e.g., if you scroll in and out of frame it should show up again, but I ahve not tested this.

**Comment by monicacecilia** [comment]
... regardless of its origin, it should not be  happening, and I should not have to zoom out-and-back-in to be able to see it. :-1:

**Comment by nathandunn** [comment]
I think that what I’m trying to say is that it is a JBrowse issue, but I couldn’t tell you for certain.  Agree that it is not good.

**Comment by cmdcolin** [comment]
@nathandunn if it is "block based" as you said it's easy to trigger a redraw from within webapollo

I haven't looked into this yet, but can do so, and I imagine it would come back to something different

**Comment by nathandunn** [comment]
Yeah, this is just a guess.  I noticed when we went back and forth between color themes on Canvas that I saw the same effect.

**Comment by nathandunn** [comment]
I added the WA1Bug . . . but not sure how to reproduce it

**Comment by nathandunn** [comment]
@monicacecilia type: not able to reproduce any more. *cheers*.
