### ISSUE TITLE
update migration script to prune prefix and call all scaffolds

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#913]
- [x] add an "ignore-prefix" option that otherwise by default adds the "Annotation-" prefix when pulling
- ~~have sequenceNames read a file if no comma~~ (will just create a script for these so not trying to read in all of scaffolds)

**Comment by childers** [comment]
@nathandunn Will the target Apollo 2 database need the prefixes removed in the sequence names? I had planned on keeping the static JBrowse data the same, and just point Apollo 2 at the existing data directory.

**Comment by nathandunn** [comment]
No, if the tracks come in as “Annotation-“XYZ features will be written to the XYZ Scaffold (you have to add the organisms first, which will correctly name the scaffold anyway).

**Comment by childers** [comment]
Cool, Thanks for clarifying!
