### ISSUE TITLE
Support Tripal integrations

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#916]
We need to support ready export / integration from Apollo into Tripal.   Note @spficklin and @deepakunni3  . 

- ~~chado export plugin #145  (may do with Tripal 3 web services, instead?)~~ Tripal is using another mechanism.  Will add web services as a separate mechanism when it comes out.
- ~~custom tab for pulling in Tripal data #256 ~~
- ~~customized single-signon authentication iPlant and URL storage #136 , LDAP authentication #115 .    ~~Reference: related to drupal login (#117) and automatically create users #204 or just use web services. ~~

We need to make sure we develop most / all use-cases.   This could be done by creating an Apollo plugin specifically for this.

**Comment by deepakunni3** [comment]
The idea of Tripal web services sounds promising as Tripal specific rules can be enforced by the web services. 

There were couple of concerns raised by @spficklin wrt. Apollo doing a direct export to a Chado data source:
1. For Apollo instances that may not be on the same server as Tripal/Chado, it would require opening the firewall to allow remote connections directly to PostgreSQL. which causes concerns regarding security issues.
2.  Feature naming is a big deal on published databases.  Usually, when annotations are received by a genome database the curators have to massage the data to get the naming to match their policies. For instance, there are sometimes multiple instances of a genome for the same organism and sometimes there are different versions.
3.  How do we ensure that changes Apollo makes directly to Chado have no side effects?

**Comment by nathandunn** [comment]
I think that the short-term plan is that Deepak will finish out the Chado export, which is almost done.  This will open the doors for us to do other interesting things as well.  Worst-case, we have stuff to fix or user’s can still use the GFF3 export, but Deepak has been doing this against a full Chado schema, so I think we are good there for now (a Tripal 3 WS can still be added).

WRT to Tripal / GenSAS:
1 - any authentication implementation will involve us creating a separate user off of Drupal, which should be pretty doable.  
2 - creating a separate panel / page is something we sort of need anyway, and won’t be hard to do.  My plan is to have a config with the URL you want to load in the panel as well as any pattern that should be used when generating the URL (e.g., scaffold, organism, featureName).  It is scheduled for 2.0.3.    

WRT to 1, I see two mechanisms: A) pull  the user-details from Drupal on authentication, update the local user with the Drupal user and finally login or B) login locally with Drupal information, but any time a user  is added / updated in Drupal it makes a web-service to Apollo call to add / update user information.   In all cases we need to set the appropriate organism permissions for that user (will they be changing organisms?).

**Comment by nathandunn** [comment]
After talking with @spficklin  and @deepakunni3  . . @spficklin  is going to add a module to pull GFF3 from [the Apollo webservice directly to tripal](https://www.drupal.org/node/2688688).   We are going to add Drupal authentication services #938 to allow single-sign-on integration, as well.
