### ISSUE TITLE
Enable response to 'Delete' dialog box with keystroke

### ISSUE THREAD

**Issue by monicacecilia** [GMOD/Apollo#919]
I miss the ability to confirm the 'Delete' for a feature with one keystroke instead of a mouse click. :disappointed:
This is important. The more we can do to help decrease mouse-work the better.

**Comment by nathandunn** [comment]
ConfirmDialog doesn't seem to have a default.   Need to extend from JBrowse to make work.

**Comment by nathandunn** [comment]
Note that if you hit "tab" it goes to the first one and then hitting "space" triggers the button.  Typically with bootstrap you have the opportunity to use a default button.   If dojo doesn't offer the default I'm sure we can figure out a way to do it.

**Comment by nathandunn** [comment]
@monicacecilia types: This would be fantastic. However, I'm going to have to live with two keystrokes instead of one due to complexity with the code.
