### ISSUE TITLE
add mechanism to install jbrowse plugins during Apollo build phase

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#926]
Need a custom jbrowse section and plugins section.  If git, should check, do additional pull.  If 'url', should fetch locally or remotely.    Its groovy, not JSON, but its pretty similar. 

```
jbrowse {
    git {
        url= "https://github.com/GMOD/jbrowse"
        version= "master"
    }
    plugins {
           MyVariantInfo {
                git = 'https://github.org/GMOD/myvariantinfo'
                branch = 'master'
                alwaysRecheck = "true"
                alwaysPull = "false"
            }
            SashimiPlot {
                git = 'https://github.org/cmdcolin/sashimiplot'
                branch = 'master'
                alwaysPull = "true"
            }
            WebApollo{
               included = true
            }
        NeatHTMLFeatures{
            included = true
        }
       . . . . 
    }
}

```
This should simplify some of the ant build process as well.   When it does a lookup of plugins to insert, it can look through these.  

- [x] verify included during startup
- [x] hook in gradle to build and pull in configs
- [x] clone, checkout, pull from apollo config for each plugin
- [x] slurp config file from classpath for deployed
- [x] move all "ant" calls to $gradle_executable in apollo script and "gant" script
- [x] update examples 
- [x] update doc
- [x] clone, checkout, pull from apollo config for jbrowse

- [x] test run-local
- [x] test URL for JBrowse 
- [x] test deploy 
- [x] test test

- [ ] **integrate with travis**
- [ ] **test apollo release**

**Comment by nathandunn** [comment]
And then install the plugin in the annot.json as well.

**Comment by erasche** [comment]
Enthusiastic :+1: from me, would simplify my life. I was just about to figure out how I would do this.

**Comment by nathandunn** [comment]
You're welcome to ignore this issue and implement it anyway ;)   

For you (or anyone else), there are two issues:
1 - build: in build.xml we need to add additional clones when we install jbrowse and make sure they get copied / installed. 
2 - in JBrowseController we need to read the config to see if jbrowse.plugins exist and insert them after we insert annot.json

The tricky part is 1) . . making build.xml aware of apollo-config.groovy.  This will be much easier once we adopt gradle.  Gant can make calls to ant, though.

**Comment by nathandunn** [comment]
As an example of how to pull info from the configuration:

https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/SequenceService.groovy#L23

the appropriate config is referenced this way:

https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/SequenceService.groovy#L453

The annot.json is added here and can easily be expanded:

https://github.com/GMOD/Apollo/blob/master/grails-app/controllers/org/bbop/apollo/JbrowseController.groovy#L338

**Comment by nathandunn** [comment]
Gonna need this sooner than later.  If you've made any progress @erasche  let me know, otherwise, it is on my short-list for this and next week.

**Comment by nathandunn** [comment]
yeah grail 3 gets rid of gant (groovy ant) in favor of gradle, which is much better supported in the open-source community .. .  I'll put something together

**Comment by nathandunn** [comment]
```
ant.importBuild 'build.xml'
```

https://docs.gradle.org/current/userguide/ant.html

**Comment by nathandunn** [comment]
@erasche   . . this should be work (and in mainline now).  It may not work for the "release" version, but then again it may.    It also upgrades JBrowse by default (but you can set it to always pull from master as well).  

Let me know if there are any further problems.

**Comment by erasche** [comment]
@nathandunn sorry for delayed response, just wanted to say thanks for implementing this, will make my deploys much, much easier. Upgraded JBrowse is very exciting ... I've been wanting to take advantage of start codon/stop codon color config.

**Comment by cmdcolin** [comment]
@erasche Technically WA doesn't use the JBrowse sequence track, but you can use "overridePlugins: true" on the sequence track to prevent it from using the WA style

I'd be curious to know your experience with that.

**Comment by nathandunn** [comment]
@erasche   Be careful with the JBrowse sequence track in Apollo.   It works, but I think that there were issues with sequence alterations.  However, if you aren't using sequence alterations it shouldn't be a problem.

**Comment by erasche** [comment]
@cmdcolin will try, that would get us the 'original' JBrowse seq track which my PI has been clamoring for.

@nathandunn yeah, we aren't using any alterations.
