### ISSUE TITLE
Issue loading sequences in apollo with plugins

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#928]
I was trying to install @cmdcolin's GCContent plugin for every genome in our Apollo instance, per a PI request.

I saw 

```
| Error Exception in thread "Thread-13" 
| Error java.lang.ClassCastException: org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String
| Error         at org.codehaus.groovy.grails.project.compiler.GrailsProjectWatcher.run(GrailsProjectWatcher.java:114)
```

in the console whilst running `./apollo devmode`. Every request for sequence data starts to 404.

![selection_635](https://cloud.githubusercontent.com/assets/458683/13618281/33663afc-e57b-11e5-9b27-0b55f153d66c.png)

- I've tried including just the plugin in `annot.json`, no build error, sequence is visible.
- As soon as I add the track, I get the casting exception and no sequence is visible.

```xml
{                                                                                                                                          
   "urlTemplate" : "seq/{refseq_dirpath}/{refseq}-",                                                                                       
   "type" : "GCContent/View/Track/GCContentXY",                                                                                            
   "label" : "GC Content XY",                                                                                                              
   "storeClass" : "JBrowse/Store/Sequence/StaticChunked",                                                                                  
}                                                                                                                                        
```

is the configuration of the track.

**Comment by cmdcolin** [comment]
There shouldn't be any problems using the plugin if it's setup right (normally just add plugin to annot.json, drop files in web-app/jbrowse/plugins/GCContent, and you're set). 

![screenshot-localhost 8080 2016-03-08 16-32-52 png resize](https://cloud.githubusercontent.com/assets/6511937/13618787/add6070c-e54b-11e5-9d22-7b4a7d09e619.png)

If you are "compiling" the plugin in release mode, that I would use "apollo release", that will recursively go over the plugins in the jbrowse plugins directory and optimize the build

**Comment by erasche** [comment]
Progress....

With plugin, the sequence request is being made to 

`http://localhost:8080/apollo/jbrowse/plugins/WebApollo/json/seq/cf3/8c8/ee/Miro-0.txt`

without, it goes to

`http://localhost:8080/apollo/jbrowse/data/seq/cf3/8c8/ee/Miro-0.txt`

**Comment by erasche** [comment]
Setting:

```
"urlTemplate" : "../../../data/seq/{refseq_dirpath}/{refseq}-",
```

fixes the issue completely (though it's a bit unintuitive)
