### ISSUE TITLE
allow username to be non-email 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#939]
related to #938  (drupal authentication) and the work done by the NAL. 

As many other authentication schemas DO NOT support email as username (and is thus not displayable), we should do the same.  

This involves:
- [x] removing the email constraint from username
- [x] adding an email field (not required), with the email user constraint
- [x] adding a metadata field (to store JSON or any other additional information
- [x] allow login with email if different than username
- [x] **fix BUG where "owner" is not being stored when annotating feature**
- [x] is UserPanel, show email and username 
- [x] in report (and other places) make sure we see both if there
- [x] check webservices such that we can edit either
- [x] check rest of code for other instances

**Comment by nathandunn** [comment]
Test: 
- when the admin changes a user email to something that is not a user email it asks for confirmation

Yes, it is an ugly box

**Comment by monicacecilia** [comment]
Aww, I think it's a pretty little box. :bowtie: 
Also checked that user is able to log in without email address.
Works! Gets a dancer 💃
