### ISSUE TITLE
remove "view track label" from drop-down menu as it is now in JBrowse directly

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#944]
low priority, but quick

**Comment by nathandunn** [comment]
with the inclusion of 1.12.1, the icon for adding / removing tracks is native (and looks nicer) so we don't need to have added it anymore

**Comment by cmdcolin** [comment]
Sorry to be a contrarian but IMO our code for this is better. The current HideTrackLabels plugin causes the track labels pop up when you are scrolling around. Although I'm sympathetic to the "it's a feature not a bug" view, I find that really awkward

**Comment by nathandunn** [comment]
I didn't notice that before.  Maybe it needs a JBrowse ticket?  Might also be a better fade animation.
