### ISSUE TITLE
indicate start and stop codon on sequence track

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#945]
in the reference sequence track we should indicate the start and stop codons similar to the native JBrowse track with the exception that we want more muted colors and ONLY the codons to be colored. 

Noted by both @erasche  and @selewis

**Comment by selewis** [comment]
I would suggest making starting codons lighter and stop codons darker shades of the same color as the frame color they are in.

Alternately, make them bold or underline. But some indication so that you can quickly see them when eyeballing the sequence.

**Comment by erasche** [comment]
My boss will be *so* happy. For reference, here is how artemis behaves. Note that they stay visible even at higher zoom levels, but I recognise apollo hides the sequence track pretty quickly. xref https://github.com/GMOD/Apollo/issues/871

![utvalg_052](https://cloud.githubusercontent.com/assets/458683/19357507/846bb2dc-9161-11e6-9eef-dada22f215a0.png)
![utvalg_053](https://cloud.githubusercontent.com/assets/458683/19357506/8466e4d2-9161-11e6-8a95-3572ddfef429.png)

**Comment by nathandunn** [comment]
The relevant code is "SequenceTrack".   However, we need to account for alternate TranslationTables when creating the CodonTable:

<img width="827" alt="screen shot 2016-10-13 at 9 23 54 am" src="https://cloud.githubusercontent.com/assets/751274/19357497/ce18218a-9126-11e6-89e1-20800e130aaa.png">
<img width="340" alt="screen shot 2016-10-13 at 9 23 18 am" src="https://cloud.githubusercontent.com/assets/751274/19357496/ce17dec8-9126-11e6-8414-7008f9bb345c.png">

**Comment by erasche** [comment]
@nathandunn it isn't too bad to do, just need a list of start codons in the jbrowse conf. https://github.com/GMOD/jbrowse/pull/657

**Comment by nathandunn** [comment]
@erasche  @selewis  I'm not sure how soon we'll get to this.  Just taking notes right now (though feel free to tackle this).    

Looks like we indicate the stop codons, but not the starts (M).   Unfortunately, the way the proteins are added, it is a single text node and not individual divs, making highlighting individual sequences difficult.

**Comment by nathandunn** [comment]
i.e., div.createTextNode(residuesAA).

https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/SequenceTrack.js#L654

JBrowse creates table rows instead and populates individual cells:

https://github.com/GMOD/jbrowse/blob/master/src/JBrowse/View/Track/Sequence.js#L266-L286

The implementations are different because Apollo supports sequence Alterations.

**Comment by nathandunn** [comment]
Did this awhile ago
