### ISSUE TITLE
Production Apollo won't start? (Tomcat: Resource is not available)

### ISSUE THREAD

**Issue by laceysanderson** [GMOD/Apollo#951]
**My System:**
Apache-Tomcat 8.0.33
Postgresql 9.4
openjdk-7-jdk 7u75-2.5.4-2_amd64
Debian 7.5 (wheezy)
Apollo 2.0.2
Grails 2.4.5

When I `./apollo run-local` with tomcat stopped, everything works beautifully (ie: I see the interface for Apollo at localhost:8080/apollo and can interact with it without error).

Now, when I try to move to production I end up with HTTP Status 404: resource is not available at localhost:8080/apollo. Note: localhost:8080 shows the tomcat welcome page showing that tomcat at least is running properly. I've attached the tomcat log in case that helps (it meant nothing to me ;-) ).
[apollo-issue-tomcat.log.txt](https://github.com/GMOD/Apollo/files/194134/apollo-issue-tomcat.log.txt)

**What I did to "Move to production":**
I copied sample-postgres-apollo-config.groovy to apollo-config.groovy and filled in the user/password for all three stanza's. I created the database `apollo` and `apollo-production` as indicated and verified that postgresql can connect to apollo and apollo-production on localhost using that user/password combo.

I created the setenv.sh in [my tomcat]/bin/setenv.sh with the example config for a fragmented genome.

> export CATALINA_OPTS="-Xmx12288m -Xms8192m \
>        -XX:PermSize=256m \
>        -XX:MaxPermSize=1024m \
>        -XX:ReservedCodeCacheSize=64m \
>        -XX:+UseG1GC \
>        -XX:+CMSClassUnloadingEnabled \
>        -Xloggc:$CATALINA_HOME/logs/gc.log \
>        -XX:+PrintHeapAtGC \
>        -XX:+PrintGCDetails \
>        -XX:+PrintGCTimeStamps"

And confirmed it was used once tomcat was running:
`tomcat8  10545     1  2 11:26 ?        00:01:40 /usr/lib/jvm/java-1.7.0-openjdk-amd64/bin/java -Djava.util.logging.config.file=/opt/tomcat8/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xmx12288m -Xms8192m -XX:PermSize=256m -XX:MaxPermSize=1024m -XX:ReservedCodeCacheSize=64m -XX:+UseG1GC -XX:+CMSClassUnloadingEnabled -Xloggc:/opt/tomcat8/logs/gc.log -XX:+PrintHeapAtGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Djava.endorsed.dirs=/opt/tomcat8/endorsed -classpath /opt/tomcat8/bin/bootstrap.jar:/opt/tomcat8/bin/tomcat-juli.jar -Dcatalina.base=/opt/tomcat8 -Dcatalina.home=/opt/tomcat8 -Djava.io.tmpdir=/opt/tomcat8/temp org.apache.catalina.startup.Bootstrap start`

Then I ran `./apollo deploy` and waited patiently while it did it's thing. There did not appear to be any errors (Log attached for completeness). Then I copied the `target/apollo-2.0.2.war` into `[my tomcat]/webapps/` and started tomcat (again no errors). However, when I go to localhost:8080/apollo I get the 404 as mentioned.
[apollo-issue-deploy.log.txt](https://github.com/GMOD/Apollo/files/194135/apollo-issue-deploy.log.txt)

**Other things I noticed while trying to debug this on my own:**

1. Looking in [my tomcat]/webapps apollo-2.0.2.war was expanded into a full directory with the same name.
2. localhost:8080/apollo-2.0.2 gives me the same 404 error.
3. Using psql to peak at the production database shows that the schema has been applied implying that it was able to connect to postgresql
4. I'm hosting multiple JBrowse isntances that are working perfectly
5. When using run-local I can create an organism and connect it to a prepped data directory seeing my tracks, etc. perfectly.

And now I'm at a standstill and don't know what else to try/check. Suggestions? Thoughts? Help?

**Comment by nathandunn** [comment]
You need to copy apollo-2.0.2.war to webapps/apollo.war 

This will explode it to “apollo” and it should show up. 

You can probably turn off tomcat, rename the file to apollo.war, remove the old exploded directory and restart and it should deploy fine. 

Also, I’m not sure if you need 12 GB’s, but it certainly can’t hurt.  Probably only 4GB’s max would be necessary, with a 1GB min (you could monitor this).   Everything else should be fine though. 

Nathan

**Comment by laceysanderson** [comment]
Still not working :-( 

- Stopped tomcat
- removed webapps/apollo and the accompanying .war
- Updated my `apollo-config.groovy` to turn off the cache by adding the following at the top before environments:

> grails.cache.config = {
>         cache {
>             enabled = false
>             name 'globalcache'
>         }
>     }

- re-deployed apollo, moved the target/apollo-2.0.2.war to webapps/apollo.war
- restarted tomcat

I'm getting the same error in the log (I think? These errors are Awful to read) and the same 404.
[apollo-issue-tomcat-2.txt](https://github.com/GMOD/Apollo/files/194258/apollo-issue-tomcat-2.txt)

**Comment by cmdcolin** [comment]
@laceysanderson Maybe try just modifying the code grails-app/conf/Config.groovy to disable the cache?

I am even still wrapping my head around external configurations (generally we have dataSources configured in the external config, apollo-config.groovy, but I'm not sure just pasting the grails.cache.config onto the end of that file)

**Comment by laceysanderson** [comment]
Still not working...

**Summary of what was tried (credit goes to @cmdcolin and @nathandunn via Skype):**

- I am now using a freshly downloaded version of Tomcat 8.0.33 owned and started by my personal user
- Apollo has been cleaned (clean-all) and deployed multiple times
- In grails-app/conf/Config.groovy All cache related config has been commented out. Specifically, lines 101-103 (provider) and 112-122 (defaultCache). Also cache `enabled = false` on line 105.
- In grails-app/conf/DataSource.groovy we commented out lines 9-12
- Finally I am using the base suggested memory settings for tomcat:

> export CATALINA_OPTS="-Xms512m -Xmx1g \
>        -XX:+CMSClassUnloadingEnabled \
>        -XX:+CMSPermGenSweepingEnabled \
>        -XX:+UseConcMarkSweepGC \
>        -XX:MaxPermSize=256m"

We have confirmed that tomcat is working as expected and that my apollo database has been initialized. 

Tomorrow I will try with a clean download of apollo and maybe a different version of Tomcat (since 8.0.33 was released only 5 days ago ;-) ) but I am grasping at straws here.

**Comment by nathandunn** [comment]
Hmm .. Was thinking that if you did a stock install of both under your own username you could eliminate potential permission issues.  I'm wondering if if specify the disk store location if it will get any better. 

Nathan

**Comment by laceysanderson** [comment]
Spoiler Alert: it's still not working.

Another update: 
- I've now tried various version of apollo (dev from github, 2.0.2, 2.0.1 and 2.0.0) so if this problem is to do with apollo it hasn't been introduced recently or accidentally fixed ;-)
- I've also tried multiple versions of tomcat with the same results.
- I've tried both the clean sample postgres config and an altered one that's supposed to remove caching for all version combinations mentioned above.

@nathandunn how would I go about specifying the disk store location? 

Also, could you give me an idea of what the expanded apollo.war is supposed to look like so I can check that is happening correctly?

**Comment by nathandunn** [comment]
Hmm ..  add you did this with just yourself as the user as well (i.e., try not using service at all)? 

You would follow these directions here:

http://webapollo.readthedocs.org/en/latest/Troubleshooting.html?highlight=diskStore#disallow-writing-overflow-to-disk <http://webapollo.readthedocs.org/en/latest/Troubleshooting.html?highlight=diskStore#disallow-writing-overflow-to-disk>

If you want to create credentials for me over Skype I can take a look, as well. 

Nathan

**Comment by laceysanderson** [comment]
Yes, I did do all of the recent steps with both tomcat and apollo owned by me and executed ./bin/startup.sh for tomcat with my own user directly.

I also unhappily realized that you would also need an account on the firewall in order to try directly and there's no way my SysAdmin will give you one :-(

**Comment by nathandunn** [comment]
I'm going to try to duplicate what you did in virtualbox . . . will let you know what I Find.

**Comment by laceysanderson** [comment]
Specifying the data store doesn't help :-(

     grails.cache.config = {
              // avoid ehcache naming conflict to run multiple WA instances
              provider {
                  name "ehcache-apollo-"+(new Date().format("yyyyMMddHHmmss"))
              }
              cache {
                 enabled = true
                 name 'globalcache'
                 eternal false
                 overflowToDisk true
                 maxElementsInMemory 10000000
                 diskStore{
                     path '/opt/apollo/cache'
                 }
             }
         }

**Comment by nathandunn** [comment]
You really have something special going on.   I just got debian loaded, so I’m working on that.  

The only other thing I could suggest would be to try it on a separate machine and see if you get the same result.    

Nathan

**Comment by nathandunn** [comment]
@laceysanderson  I got it to work on debian / wheeze without a hitch in virtualbox.   I would say we should try building on another machine.

**Comment by nathandunn** [comment]
The only two differences I had, was using i386 openjdk and postgresql 9.1 instead of 9.4.  Very weird.  

The other possibility is deleting everywhere the ehcaching code is.  (BuildConfig.groovy, DataSource.groovy, and Config.groovy).

**Comment by laceysanderson** [comment]
My java temp directory is within tomcat and owned by me but just in case there is still some weird permissions going on I made it writable by everyone -still didn't work.

**Comment by nathandunn** [comment]
Lacey . . of these . . which are custom installed? 

My System:
Apache-Tomcat 8.0.33 (Nathan Download from tomcat)
Postgresql 9.4  (apt-get install)
openjdk-7-jdk 7u75-2.5.4-2_amd64 (apt-get install)
Debian 7.5 (wheezy) 
Apollo 2.0.2  (download from website)
Grails 2.4.5  (you actually don't have to install this . . grailsw will install locally)

**Comment by laceysanderson** [comment]
Exactly the same as you except that I installed Grails via sdk as it said in the instructions: http://webapollo.readthedocs.org/en/latest/Apollo2Build.html

**Comment by nathandunn** [comment]
Yeah, that shouldn’t make any difference.   It would give you a warning if it did. 

Nathan

**Comment by nathandunn** [comment]
After trying a bit of everything we discovered that Jira doesn't play nicely with others, even other Atlassian products:  https://confluence.atlassian.com/conf54/confluence-administrator-s-guide/integrating-confluence-with-other-applications/integrating-jira-and-confluence/installing-confluence-and-jira-together

Two tomcats didn't seem to help.    For now we (meaning @laceysanderson) are doing run-local, but will either try working with vagrant (creates an isolated VM - not sure if it will work) or more probably jetty.
