### ISSUE TITLE
can not delete sequence alteration 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#954]
When attempting to delete a deletion or substitution it attempts and then fails.  Doesn't always fail right away (after second time usually).

**Comment by nathandunn** [comment]
Reported by @selewis

**Comment by nathandunn** [comment]
@deepakunni3  Can you reproduce this?   I was having the same problem as @selewis  was but now it works perfectly.

**Comment by deepakunni3** [comment]
@nathandunn Can't seem to reproduce this bug.

**Comment by nathandunn** [comment]
K. thanks.
