### ISSUE TITLE
drop-down menu should detect available options for acceptor and donors

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#955]
reported by @selewis    We detect this in some instances, but not others.  Maybe its not picking up on strand? 

The software should determine whether the splice junction being clicked on is an acceptor (5' end) or a donor (3'end) and the available menu options should reflect this. VEEEERY confusing to see all 4 when only 2 are logically/biologically possible. And remember 5'&3' depends on which strand the gene is on.

**Comment by cmdcolin** [comment]
Technically we click on an exon when we do these operations, so all four operations are available

It might be possible to allow clicking on the splice site only though

**Comment by nathandunn** [comment]
@monicacecilia typing: have not been able to reproduce. Will re-open if reported again.
