### ISSUE TITLE
Add doc for grails plugins

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/Apollo#959]
It would be useful to allow grails plugins to be created for Apollo, and one thing that seems important is to actually modularize the core Apollo application to allow plugins to access Apollo data. That can be achieved by moving the domain classes themselves to a plugin. The reason for doing this is because, in general, a plugin cannot access the domain classes in the main app, but if the domains themselves are in a plugin, then this becomes trivial.

This article describes a good scenario like this http://www.bobbywarner.com/2011/06/21/grails-setup/

It suggests creating a "core" module (article suggests "grails create-plugin sampleapp-core") that contains domain classes, so that they can be shared within the app/plugin ecosystem

**Comment by nathandunn** [comment]
I changed the title, since you can already use them.

**Comment by cmdcolin** [comment]
I outlined a use case that involves a little more than documentation. For example, currently, if you create a plugin, and you want to add a new feature, or do anything with Apollo domain objects, it isn't really possible. I think there is a good workflow for solving that though

**Comment by nathandunn** [comment]
This is the doc for #968.
