### ISSUE TITLE
Comments field is restricted to ~256 characters per comment

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#963]
One of my users hit this. After 256 characters, the comment is accepted but will not be saved. On closing/re-opening the edit box it is missing.

**Comment by nathandunn** [comment]
Are these comment attributes (which it can have many of) or the description for a feature (of which there are one)?

**Comment by erasche** [comment]
Comments. Might affect other fields as well, did not test (yet)

**Comment by nathandunn** [comment]
@deepakunni3   Can you take a look at this?  I think you just need to change the field type in FeatureProperty to type of "text".  I looked in feature and "name" and "description" are already mapped that way. 

Thanks.

**Comment by deepakunni3** [comment]
@nathandunn Yes, we had that problem with feature name. 

I'll get a PR in quickly for this.

**Comment by nathandunn** [comment]
I'm not sure if will need to update the migration script for this.  Hopefully not. You can check earlier migration scripts to see if they had to do the same thing.

Nathan

**Comment by nathandunn** [comment]
The fix is in mainline.

**Comment by erasche** [comment]
Thanks so much!

**Comment by nathandunn** [comment]
Going to have @monicacecilia  test it to make sure it works for other stuff as well.

**Comment by erasche** [comment]
@nathandunn ah, sorry about that. Still not used to y'all's bug workflow quite yet.

**Comment by nathandunn** [comment]
No worries.

**Comment by monicacecilia** [comment]
Three whole paragraphs worth of [Hippie Ipsum](http://www.hippieipsum.me/) and the comments took just fine. Works well, and gets a💃 !

**Comment by nathandunn** [comment]
Nice.  I don't see carob everyday.
