### ISSUE TITLE
running Apollo (Jetty or Tomcat) with JIRA (Tomcat / PostgreSQL) fails with a cache error

### ISSUE THREAD

**Issue by laceysanderson** [GMOD/Apollo#965]
I am unable to get Apollo 2.0.2 running on Jetty 9.2.15 (v20160210). When I use `./apollo run-local` everything runs as expected but as soon as I use `./apollo deploy` and jetty I end up with "HTTP Error: 503 Service unavailable".

I've attached my jetty startup log ([jetty-startup-log.txt](https://github.com/GMOD/Apollo/files/203149/jetty-startup-log.txt)) to show the error. Notice that it is the same as mentioned in #465.

Since that issue seemed to think it was a caching issue and I know my system is having issues with caching (#951), I immediately disabled my cache directly in grails-app/conf/Config.groovy (I edited directly to ensure my changes were being picked up and at previous direction of @nathandunn when working with a similar issue in Tomcat). Changes are as follows:

    grails.cache.config = {
        // avoid ehcache naming conflict to run multiple WA instances
        provider {
            name "ehcache-apollo-"+(new Date().format("yyyyMMddHHmmss"))
        }
        cache {
            enabled = false                           // Changed this to disable the cache
            name 'globalcache'
            eternal false
            overflowToDisk false                      // Changed this for good measure ;-)
            maxElementsInMemory 10000
            maxElementsOnDisk 10000000
        }
        defaultCache {
            maxElementsInMemory 10000
            eternal false
            timeToIdleSeconds 120
            timeToLiveSeconds 120
            overflowToDisk true
            maxElementsOnDisk 10000000
            diskPersistent false
            diskExpiryThreadIntervalSeconds 120
            memoryStoreEvictionPolicy 'LRU'
        }
    }

Unfortunately this didn't change the error at all. Looking back into the previous issue I also confirmed that my jetty user can access and write to tmp and it can.

    $ sudo su -s /bin/bash jetty -c "touch /tmp/test.jetty.user.txt"
    $ ls -l /tmp/tes*
        -rw-r--r-- 1 jetty jetty 0 Apr  4 12:38 /tmp/test.jetty.user.txt

**Comment by nathandunn** [comment]
JIRA v6.3.6
Postgresql 9.4
openjdk-7-jdk 7u75-2.5.4-2_amd64
Debian 7.5 (wheezy)
Apollo 2.0.2
Grails 2.4.5

**Comment by nathandunn** [comment]
Good news: I got it to work
Bad news:  I got it to work

I used the 6.3.6 standalone (running it as a normal user) and a separate tomcat.  The only custom configuration was for the database).  

I can send you credentials via Skype tomorrow if you want to see what I did and what the system looks like.  

Failing that, I would see if you can't get me a guest account, but most likely that won't be necessary.

**Comment by nathandunn** [comment]
And using Docker is not a bad idea.

**Comment by nathandunn** [comment]
@laceysanderson  My guess is that somehow the init script is messing up which tomcat is being run and thus running another version of Apollo as well.  Maybe looking for an apollo.war file might be a good idea?

**Comment by laceysanderson** [comment]
Ok, I've made some progress: I now have tomcat & Jira running side-by-side. It turns out when I moved Tomcat to a different port to avoid collision with Jira there were actually two ports I had to change.

First, the port 8080 =>  port 8082
This is changed in [apache home]/conf/server.xml on Line 70 in my version:

    <Connector executor="tomcatThreadPool"
               port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" />

Second port 8005 => port 8006
This is changed in the same file on line 22 in my version:

    <Server port="8006" shutdown="SHUTDOWN">
      <Listener className="org.apache.catalina.startup.VersionLoggerListener" />
      
      
      <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
      
      <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
      <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
      <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />

Unfortunately I still don't have Apollo running but I thought I'd document that in case it helps someone else.

**Comment by nathandunn** [comment]
I'm going to close this for now as it seems to be system-specific.   Feel free to re-open if needed.
