### ISSUE TITLE
chado export should use save or update

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#967]
Mimicking what was done in WA1, we should use save or update (save without insert being specified).    The trick is that equalsHashCode uses the keys of Organism, Type, and UniqueId.   I think we can get away with just using uniqueName.    This is what we use locally in Apollo, as well (with OntologyId).

**Comment by deepakunni3** [comment]
@nathandunn Sure, sounds good.

**Comment by nathandunn** [comment]
For when you're done with the other one.

**Comment by nathandunn** [comment]
To test: try doing a chado export in the sequence panel.

**Comment by nathandunn** [comment]
Nothing to test . . nevermind
