### ISSUE TITLE
refactor for grails plugins

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#968]
This should be done in conjunction with the grails refactor #444  (grails upgrade) and #959 (doc) and fixing the #519 (change to security library needed to get handlers).   

Based on the excellent work done on @cmdcolin pull request #962.

**Comment by nathandunn** [comment]
I think some further requirements would be splitting up the repos and integrating with maven / bintray to maintain the plugins, though initially this could be done on the filesystem.

FYI @cmdcolin

**Comment by nathandunn** [comment]
Was thinking that this should allow for non-official plugins . . e.g., using something like bower / gradle to download the proper version of the code and then having that accessible.

**Comment by cmdcolin** [comment]
Not sure what you mean. JBrowse plugins? Grails plugins?

**Comment by nathandunn** [comment]
Grails plugins.  I'm not sure we want an "official" Grails 2.X / 3.X plugin.  It makes much more sense to use a maven type dependency.  Probably we can just publish it that way (we have our own plugin repository).  Was just thinking shorter-term you can download via git and use the file path, but its probably best to do it correctly the first-time.

**Comment by nathandunn** [comment]
Just wanted to dump search info.  Basically info on maintaining a working repos for grails plugins so we aren't doing multiple git downloads.  

http://stackoverflow.com/a/18453714/1739366
http://grails.1312388.n4.nabble.com/Caching-plugins-using-artifactory-td4640164.html
