### ISSUE TITLE
sync with JBrowse 1.12.2-release

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#971]
- [x] tag jbrowse/1.12.2-apollo
- [x] fix Config.groovy file
- [x] fix sample files?

**Comment by nathandunn** [comment]
@deepakunni3  @enuggetry   I might just tag a 1.12.2-Apollo in JBrowse (not a release) so that we can have a "locked" version that is tested against.   Will that work?

**Comment by enuggetry** [comment]
ok.  that would be fine.  We'll jump to 1.12.3 in the next maint release,
then.

**Comment by nathandunn** [comment]
So do you want me to call it 1.12.2 or 1.12.2-Apollo? 

Nathan

**Comment by enuggetry** [comment]
makes sense to add "apollo"

**Comment by nathandunn** [comment]
👍

**Comment by deepakunni3** [comment]
👍

**Comment by monicacecilia** [comment]
👍 

... everybody is doing it. :bowtie:

**Comment by nathandunn** [comment]
This is fixed now.
