### ISSUE TITLE
Organism listed multiple times if added via the add_organism.groovy twice 

### ISSUE THREAD

**Issue by childers** [GMOD/Apollo#990]
I was test loading some organisms using the add_organism.groovy script (which is very nice), and I accidentally ran the same command twice.  I didn't think anything was wrong as it appeared once in the organism list, but when I went to view the public genomes, it was listed multiple times.  I deleted the organism through the admin interface, refreshed and it was still there! I didn't think to look at the database before removing it to get back to one listing on the public genomes view, but is it adding multiple records for that species, then collapsing to only show one in the organism panel?

**Comment by nathandunn** [comment]
I'm going to have you test all our code from here on out to find these edge cases ;) 

If you look in the Organism table does it only show up once now or is it still there twice?

**Comment by childers** [comment]
( =

Right now it's in there one time.  I can try re-adding it...

It is still in the organism table one time, but now it shows twice in the public genomes page.

**Comment by nathandunn** [comment]
That is very weird.   It is just doing a select out of the Organism table.  You don't need to re-add it:

```
        [organisms: Organism.findAllByPublicMode(true, [sort: 'commonName', order: 'asc']), flash: [message: params.error]]
```

Maybe try restarting?  It might be cached (though that would be weird as well).

**Comment by childers** [comment]
Same behavior as before. It shows up one time in the organism panel and when I delete it, it still shows up and now shows once in the public genomes list (no reload).

**Comment by childers** [comment]
Can you see this on your end too?

**Comment by cmdcolin** [comment]
I have mentioned previously, but I think we should encode a uniqueness constraint on the Organism table  by name (https://github.com/GMOD/Apollo/issues/845#issuecomment-184759266)

**Comment by nathandunn** [comment]
@childers  Can you send me the URL?  I'll see if we can't do a duplicate add.   Also if you send me a dump of what you have (with some admin access) I might be able to take a look.

@cmdcolin I am not sure why the name is not constrained, though I feel as though it is probably intentional (e.g., isolating organisms).

**Comment by childers** [comment]
Sorry, this instance is up on our testing server, behind our firewall.  Do you have a test instance on icebox? 

When I checked, it was only in the organism table once as far as I could see.  It shows in the organism list once but has to be deleted for each load before it goes away, and shows multiple times in the public browser page.  @nathandunn, you said that it only does a select on the organism table.  Does the groovy script also add info into some other table (organism_organism_property, organism_property, etc all look empty)?

**Comment by nathandunn** [comment]
I'm curious if you are looking at the same database table that your web server is looking at.  

You can absolutely look at the demo on icebox.  I'll send you those via email.

**Comment by nathandunn** [comment]
@childers   Please re-open if you are still seeing this.
