### ISSUE TITLE
small changes to Chado 

### ISSUE THREAD

**Issue by nathandunn** [GMOD/Apollo#992]
From followup of #991.

So, @deepakunni3   Can you create a PR for the following (or create an issue if you want):
1 - move chado-schema-with-ontologies.sql.gz  out of the root directory and update the load_chado_schema.sh script to reflect that.
1 - add ChadoExport.md to index.rst
1 - comment out chado sections in the sample chado files (unless you want to automatically boot load)
1 - the chado sections should all be "update" instead of "create-drop" . . . similar to what is in postgres.tavis

**Comment by deepakunni3** [comment]
@nathandunn I'll reference this issue on the PR.

**Comment by nathandunn** [comment]
👍
