### ISSUE TITLE
Build issues on master with gradle/jbrowse

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#995]
It seems that the new `build.gradle` uses ant's build.xml definitions.

After a fresh clone of apollo, and running `./apollo devmode` and notice the following

```
[hxr@leda:~/work/apollo]$ cd jbrowse-download
[hxr@leda:~/work/apollo/jbrowse-download]$ git status
HEAD detached at 1.11.6-release
```

the only place that that is mentioned in `build.xml` which implies that the ant definition of JBrowse installation is overriding the `build.gradle`'s abilities to use bower. Additionally this is not a recursive clone, so JBrowse seems to fail to function entirely (missing dojo)

```
[hxr@leda:~/work/apollo/jbrowse-download]129$ git submodule init                                                                            (a13397c) 
Submodule 'src/FileSaver' (https://github.com/dkasenberg/FileSaver.js.git) registered for path 'src/FileSaver'
Submodule 'src/dbind' (https://github.com/rbuels/dbind.git) registered for path 'src/dbind'
Submodule 'src/dgrid' (https://github.com/SitePen/dgrid.git) registered for path 'src/dgrid'
Submodule 'src/dijit' (https://github.com/dojo/dijit.git) registered for path 'src/dijit'
Submodule 'src/dojo' (https://github.com/dojo/dojo.git) registered for path 'src/dojo'
Submodule 'src/dojox' (https://github.com/dojo/dojox.git) registered for path 'src/dojox'
Submodule 'src/jDataView' (https://github.com/rbuels/jDataView.git) registered for path 'src/jDataView'
Submodule 'src/json-schema' (https://github.com/kriszyp/json-schema.git) registered for path 'src/json-schema'
Submodule 'src/jszlib' (https://github.com/rbuels/jszlib.git) registered for path 'src/jszlib'
Submodule 'src/lazyload' (https://github.com/rbuels/lazyload.git) registered for path 'src/lazyload'
Submodule 'src/put-selector' (https://github.com/kriszyp/put-selector.git) registered for path 'src/put-selector'
Submodule 'src/util' (https://github.com/dojo/util.git) registered for path 'src/util'
Submodule 'src/xstyle' (https://github.com/kriszyp/xstyle.git) registered for path 'src/xstyle'
[hxr@leda:~/work/apollo/jbrowse-download]$ git submodule init                                                                               (a13397c) 
# no output this time around
```

**Comment by nathandunn** [comment]
Weird.  This is straight off of master?  

I will try it now.   I don’t think we explicitly checked that target (devmode) but obviously should have. 

Nathan

**Comment by erasche** [comment]
@nathandunn yep, straight off master (165def0c0b8c2bb6a102b094979efaf1eab12d33).

I don't run interactively very often, just picked devmode as it seemed reasonable and I didn't feel like re-reading the docs. I don't think this is specific to devmode though, since I believe its behaviour tied to the `build.gradle` file.

**Comment by nathandunn** [comment]
I just pushed a fix and it should be working.  Let me know.

**Comment by erasche** [comment]
@nathandunn fixed, brilliant, thanks.

**Comment by erasche** [comment]
Fyi the last command in `apollo`, the `jbrowse` action has a different capitalisation of Jbrowse than the rest of the commands.

**Comment by nathandunn** [comment]
So it does . . fixes that too.   Thanks for reporting.
