### ISSUE TITLE
Color by frame oddity with specific feature.

### ISSUE THREAD

**Issue by erasche** [GMOD/Apollo#998]
One of my users reported this and I'm not sure why it is happening.

They've got this feature, we're specifically concerned with 065a

![utvalg_722](https://cloud.githubusercontent.com/assets/458683/14662105/a0a9db6c-06a2-11e6-9d94-2bfd0e0fc8a2.png)

They couldn't figure out how to make it green, like was expected.

Moving the exon, this should be red, OK:

![utvalg_721](https://cloud.githubusercontent.com/assets/458683/14662159/0507c272-06a3-11e6-9707-b889693986e5.png)

This should be green though!

![utvalg_723](https://cloud.githubusercontent.com/assets/458683/14662157/05066580-06a3-11e6-9507-741abae724ce.png)

and so should this

![utvalg_719](https://cloud.githubusercontent.com/assets/458683/14662158/05075094-06a3-11e6-9d91-af0ac6fe9302.png)

it will turn red and blue fine, just green it refuses. I eventually corrected the exon boundary to match the CDS (not sure where they got that boundary from...) and it turned green perfectly fine.

![utvalg_725](https://cloud.githubusercontent.com/assets/458683/14662181/3bf64b46-06a3-11e6-8830-0495a9b71e57.png)

**Comment by nathandunn** [comment]
@erasche   What version is this?   

I'm not seeing this on 2.0.2.  I have been setting the translation start and end and setting exon boundaries and it seems to work properly. 

If you go to our demo are you able to reproduce this?

http://genomearchitect.org/WebApolloDemo

@deepakunni3   Is this something that you can reproduce?

**Comment by erasche** [comment]
@nathandunn 076f3a7227f9a9d061724fb23939339122ca9648 

and it isn't something I can reproduce anywhere else, even in my own instance. Feel free to close, I just wanted to document that this happened to us.

**Comment by nathandunn** [comment]
Ahh . . okay . . I'll kick the can down the road.  We run into these from time to time.
